### ISSUE TITLE
Incorrect semantic size tokens

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#10014]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The semantic size tokens do not match the size variables in the [Calcite UI Kit](https://www.figma.com/design/vB6xFCAFeW0zKrT4nKlh8Z/Calcite-UI-Kit-%26-Styles?m=auto&t=jLiIE3svZrbQCv3O-7).

### Expected Behavior

I would expect that they match to following
![CleanShot 2024-08-13 at 10 07 26@2x](https://github.com/user-attachments/assets/2b693bde-7b40-47f1-9ce8-c78247cfdfa9)

### Reproduction Sample

https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-design-tokens/src/semantic/size.json

### Reproduction Steps

Compare size.json to the size collection in Figma.

### Reproduction Version

v2.11.1

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package
- [X] @esri/calcite-design-tokens

### Esri team

Calcite (design)

**Comment by alisonailea** [comment]
part of the #8856

**Comment by geospatialem** [comment]
Verified on the `dev` branch.
