### ISSUE TITLE
Incorrect semantic space tokens

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#10012]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The tokens to define padding or margin at 10px and 24px are missing.

### Expected Behavior

The tokens match the variables specified in the [Calcite UI Kit](https://www.figma.com/design/vB6xFCAFeW0zKrT4nKlh8Z/Calcite-UI-Kit-%26-Styles?m=auto&t=jLiIE3svZrbQCv3O-7).

### Reproduction Sample

https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-design-tokens/src/semantic/space.json

### Reproduction Steps

Compare space.json with the Calcite UI Kit.

### Reproduction Version

v2.11.1

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on the `dev` branch.
