### ISSUE TITLE
CI: When ready for dev automation begins ensure the `needs triage` label is removed

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#10010]
### Priority impact

p - low

### Summary

When running the ready for dev automation check if the `needs triage` label is present, and if so, remove it from the issue.

### Desired Outcome

Check if the `needs triage` label is present when running the `ready for dev` automation. If present, remove the `needs triage` label.

### Resources

We'll probably just need a new removeLabel function to check if `needs triage` is present, and if so to remove it, similar to the assigned, but with additional logic:

https://github.com/Esri/calcite-design-system/blob/21114caa128b9a3175c7fc21e48f3b4b94c16f58/.github/scripts/notifyWhenReadyForDev.js#L39-L43

**Comment by DitwanP** [comment]
🍡 Verified with issue #[10122](https://github.com/Esri/calcite-design-system/issues/10122)
<img width="277" alt="Screenshot 2024-05-21 at 11 06 30 AM" src="https://github.com/user-attachments/assets/296e9557-f374-4224-a986-47bb9438f0c2">
