### ISSUE TITLE
CI: Priority labels aren't added in as-expected

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#10011]
### Priority impact

p - low

### Summary

Ensure priority labels are added by the CI when added via issue templates.

### Desired Outcome

Automatically add in the priority label :-)

### Resources

As an example, in #10010 the [run failed](https://github.com/Esri/calcite-design-system/actions/runs/10308576369). I had to individually added in the `p - low` label, despite our automation  https://github.com/Esri/calcite-design-system/issues/10010#event-13811560045

**Comment by DitwanP** [comment]
🍡 Verified 👆
<img width="277" alt="Screenshot 2024-05-21 at 11 06 30 AM" src="https://github.com/user-attachments/assets/f887e6df-d3d0-44d1-b3ef-b6cc10cc32e2">
