### ISSUE TITLE
[Panel] focus outline on is obscured behind the header

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#10022]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Currently the outline is hidden behind the header:
![image](https://github.com/user-attachments/assets/701667fe-68d5-4ab7-a099-396f317d97d6)

### Expected Behavior

The outline should be visible on top of the header.

### Reproduction Sample

https://codepen.io/Ditwan-Price/pen/gONxjaO?editors=1100

### Reproduction Steps

1. Open codepen
2. Tab to panel and notice the focus outline behavior

### Reproduction Version

2.11.1

### Relevant Info

(https://github.com/Esri/calcite-design-system/pull/9804#issuecomment-2270060429)

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
@DitwanP I've only noticed this issue in Chrome. Can you confirm?

**Comment by geospatialem** [comment]
Verified in `2.12.1` 🎉
