### ISSUE TITLE
Panel: add default padding to content area and css property to override it

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#10037]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Feedback item 2 from [this comment](https://github.com/Esri/calcite-design-system/pull/9804#issuecomment-2270060429) suggest that we are supposed to have a default padding set on the content area of `panel` and a CSS property to allow a user to override it. 

> there is no padding in the content area within the padding - I thought we were adding a default value here that matched header / footing padding and was overridable to 0?

### Acceptance Criteria

- [ ] There should be default padding on the content area of `panel` that matches header and footer
- [ ] A CSS property should be available to allow for overriding the default padding on the content area

### Which Component

`panel`

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by driskull** [comment]
We might be able to close this one. From discussion, we don't want to add padding to panel by default. Default padding has been added to the dialog component though.

**Comment by macandcheese** [comment]
Yeah, this was just a follow up to add an internal css property so our Dialog could set that directly vs. an extra div. If that's not needed we can close.

**Comment by driskull** [comment]
Agreed. @DitwanP can we close this one?

**Comment by geospatialem** [comment]
> We might be able to close this one. From discussion, we don't want to add padding to panel by default. Default padding has been added to the dialog component though.

Closing the above - default padding has been added to the `dialog` component to accommodate the above.
