### ISSUE TITLE
input, input-number and input-text should not set slotted actions to be disabled.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10055]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When slotting in an action into one of these component's `actions` slot, the action is set to be disabled if the component is disabled.

### Expected Behavior

Slotted elements disabled property are not modified

### Reproduction Sample

https://codepen.io/driskull/pen/KKjyQvL

### Reproduction Steps

1. open the codepen
2. notice the slotted action has the disabled attribute when it should not.

### Reproduction Version

2.11.0

### Regression?

No

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
@driskull They no longer have the disabled on them when inspected but are still functionally disabled, wanted to make sure this is what's intended. 

https://codepen.io/Ditwan-Price/pen/gOVPXEj?editors=1010

**Comment by driskull** [comment]
Yes, I think that should be fine. cc @jcfranco

**Comment by DitwanP** [comment]
🍠 Verified on `2.13.0-next.3`
