### ISSUE TITLE
[Date Picker / Input Date Picker] Shift focus from the input to the picker upon open

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#10069]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Summary

Since the `date-picker` component has a `role="dialog"` we need to shift focus from the `input-date-picker` to the `date-picker` upon opening.

The above will not be covered in #8402, but needs a `spike` to determine a time estimate for future implementation.

_Note that on closing the component focus shift performs as-expected._

### Actual Behavior

![image](https://github.com/user-attachments/assets/5668f65e-93c6-4ffc-8540-18551317836c)

### Expected Behavior

![image](https://github.com/user-attachments/assets/a3a84bf2-cb53-4ae2-bb7c-388fbdcfd8f8)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-date-picker/#sample

### Reproduction Steps

1. Visit the [component sample](https://developers.arcgis.com/calcite-design-system/components/input-date-picker/#sample)
2. In the sample, either click the `input-date-picker` component or when in focus press the down arrow key to expand the component
3. Observe the focus doesn't shift to the `date-picker` component upon opening

### Reproduction Version

`2.11.1`

### Working W3C Example/Tutorial

https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/#ex_label

### Relevant Info

Part of the ArcGIS Enterprise audit (instance id: `2236594110`) from May 2024, listed as a severity 8 of 10. However, the user can still navigate to the component using `tab`, so listing the priority as medium.

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Enterprise

**Comment by ashetland** [comment]
It feels counter-intuitive to focus on "previous month" first. Digging into this a bit, as a keyboard user, it is easier to type into the input than it is to navigate the Date Picker. Do we need to keep the dialog role? Could we follow this example and keep keyboard users focused on the input only. https://mui.com/x/react-date-pickers/date-range-picker/

**Comment by anveshmekala** [comment]
This issue is a side effect of https://github.com/Esri/calcite-design-system/issues/10243 . Currently, when input-date-picker is open using ArrowKeys focus is supposed shift on to date-picker. Code is in place for `setFocus` method to be invoked on `date-picker`.
