### ISSUE TITLE
[Dialog] Add `escapeDisabled` prop

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-design-system#10080]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add prop to disable closing dialog on escape key. Modal, which we need to replace, had this. 

We have a lot of complicated workflows (element configuration) in modals and don't want people to accidentally close out of it. Especially when the escape key can be used for other purposes in the modal like closing dropdowns.

### Acceptance Criteria

When `escapeDisabled` is present, disables the closing of the component on escape key.

### Which Component

calcite-dialog

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Dashboards

**Comment by DitwanP** [comment]
Sending back to resolve an issue where the `panel` is still closing the `dialog` even with the `escapeDisabled` prop present.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.24` 
https://codepen.io/Ditwan-Price/pen/eYwybyr
