### ISSUE TITLE
[Dialog] Some slotted content appears below or overlaps the header/footer

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-design-system#10095]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When slotting absolute positioned content into the default slot of the `dialog`, it can appear below the header and overlap with the footer and its contents. We use shell in modal, and I don't think we can work around this by adjusting its positioning. 

Here is a shell in the `dialog`'s default slot. Notice the first action is hidden below the header, the footer bar is missing and the content overlaps the footer buttons. 
![image](https://github.com/user-attachments/assets/d8700072-9d8c-4af7-aaf6-3c1f33300795)

vs the same content in `modal`'s `content` slot
![image](https://github.com/user-attachments/assets/e9ce73ed-d09b-4b16-8339-061996284efd)

### Expected Behavior

Same as `modal`, all content should appear between the header and footer. 

### Reproduction Sample

https://codepen.io/ellupp/pen/LYKOmPa?editors=1101

### Reproduction Steps

1. click button to open dialog and observe

### Reproduction Version

2.11.1

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Dashboards

**Comment by driskull** [comment]
The issue is actually with the shell component. The shell component is positioned absolutely, so it doesn't slot well into dialog.

**Comment by driskull** [comment]
@DitwanP I un-spiked this one.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.29`
https://codepen.io/Ditwan-Price/pen/BagxoGq?editors=1100

**Comment by ellenupp** [comment]
Thank you!

**Comment by geospatialem** [comment]
Summarizing our internal conversations, but due to some regressions with the above, we will be reverting the change above, and re-evaluating next steps in the `3.0`, or November release. 

cc @driskull @jcfranco @ellenupp

**Comment by jcfranco** [comment]
Per our conversation, we'll look at rolling back https://github.com/Esri/calcite-design-system/pull/10496, and addressing this issue, once https://github.com/Esri/calcite-design-system/pull/10241 lands in the November release.

**Comment by DitwanP** [comment]
🍡 Verified on `3.0.0-next.16`
