### ISSUE TITLE
ShellPanel: add event for when collapsed changes

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10116]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The collapsed property should have an event so a user can listen and know when the property is toggled.

### Acceptance Criteria

A "onCalciteShellPanelToggle" event.

### Relevant Info

https://community.esri.com/t5/calcite-design-system-questions/monitor-shell-panel-status-collapsed-expanded/m-p/1524142#M699

### Which Component

calcite-shell-panel

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by macandcheese** [comment]
Just a pattern question - Is this strange to introduce an event for a property that a user can't change by interacting with the component (we don't have a "collapse" button or UI)? In that example they would have some other element interaction they could monitor via event right?

**Comment by driskull** [comment]
Thats a good question to discuss @jcfranco

**Comment by macandcheese** [comment]
Could be affected by https://github.com/Esri/calcite-design-system/issues/9828 - if Shell Panel had its own closable Panel rendered internally and folks weren't slotting their own, this event would come about as a result of that.

**Comment by jcfranco** [comment]
I believe all of our events are based on some level of user interaction, so if collapsing is only possible through property setting, an event wouldn't be warranted (see https://github.com/Esri/calcite-design-system/issues/8927#issuecomment-2008544995).

**Comment by driskull** [comment]
Ok Ill close this one 👍
