### ISSUE TITLE
Dialog: closable calcite panels placed inside a dialog will close the dialog

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10129]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When placing a panel inside a dialog and closing the panel, the dialog will be closed.

This is because the dialog listens for the `calcitePanelClose` event to close the dialog. If the event bubbles up, it closes the dialog. The workaround is to stop propagation of the `calcitePanelClose` event.

### Expected Behavior

I would expect closing internal panels to not close the dialog.

### Reproduction Sample

https://codepen.io/fcbasson/pen/YzoazZE

### Reproduction Steps

1. open the codepen
2. close the panel inside the dialog
3. notice the dialog closes

### Reproduction Version

2.11.1

### Relevant Info

In components that use `calcite-panel` internally and listen to its events, we should make sure the element we are looking for is emitting the events and that any other elements do not trigger any action.

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`

https://github.com/user-attachments/assets/2807458d-2aa4-4dc8-82cf-5bf6c8e03b19
