### ISSUE TITLE
[Table] Selected checkbox on the table header is always active for `selection-mode=multiple`

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-design-system#10123]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The selected checkbox on the table header is always active for `selection-mode=multiple` which is confusing for users when they haven't selected anything

![image](https://github.com/user-attachments/assets/2227095c-a20a-419a-b9ae-89420012edfb)

### Expected Behavior

The checkbox should be empty

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/table/

### Reproduction Steps

Use `multiple` for `selection-mode`

### Reproduction Version

latest

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
cc @ashetland @SkyeSeitz we could use "unfilled" for nothing selected, "filled" for partially selected, and "filled and brand" for all selected? This would be a simple change if so, WDYT?

**Comment by SkyeSeitz** [comment]
Not sure if a `check-square` state is super beneficial for a "Select all" feature. Either all items are selected or I would expect to see an empty checkbox as an indicator that I can turn "Select all" on. Is there a value to an intermediate state? It's not consistent with our Checkbox intermediate property.

**Comment by macandcheese** [comment]
Right now there is no difference between the none selected and some selected states. But we could use an indeterminate check square icon, I don’t see one in the library currently ..

**Comment by SkyeSeitz** [comment]
It would be the minus-square-f icon. 
<img width="134" alt="image" src="https://github.com/user-attachments/assets/02f75c80-d230-4bf4-ab43-9d435a752de2">

If we think the intermediate state for a Select all function is important, I think that would be clear enough 👍

**Comment by macandcheese** [comment]
Ah, missed that while searching.. the icon isn’t tagged as “square” or “indeterminate” in metadata. There’s filled and unfilled.

**Comment by SkyeSeitz** [comment]
Could absolutely use those tags 😂

> There’s filled and unfilled.

Figured we can match the Checkbox intermediate state which appears filled.
<img width="33" alt="image" src="https://github.com/user-attachments/assets/2643e248-3681-4439-a0e7-c6e03e5bbb45">

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.28`
https://codepen.io/Ditwan-Price/pen/zYVWJKz?editors=100
