### ISSUE TITLE
[List] setFocus doesn't work when filter is enabled

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-design-system#10136]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calling a list's `setFocus` when it has `filter-enabled` does not focus the list or any of its child elements. 

### Expected Behavior

When the filter is enabled, `setFocus` should place focus on the list's input. 

### Reproduction Sample

https://codepen.io/ellupp/pen/abgYKWM?editors=1010

### Reproduction Steps

1. Click "focus list" button. Nothing happens.
2. Compare when removing `filter-enabled` from the list. Click the button -> first list item is focused. 

### Reproduction Version

2.11.1

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Dashboards

**Comment by driskull** [comment]
I think this is actually an issue with the filter component.

https://codepen.io/driskull/pen/MWMVqmb?editors=1010

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.31` 
https://codepen.io/Ditwan-Price/pen/yLdjpwM?editors=1010
