### ISSUE TITLE
Combobox: Entering filter text when no results are visible will close the combobox

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-design-system#10156]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a single or single-persist combobox has a selected item, and the user enters text leading to no items, the combobox closes suddenly, showing the selected value.

### Expected Behavior

If a combobox has a selected item, and the user enters filter text, don't close the combobox. The filterText should remain visible with no results displayed. 

### Reproduction Sample

https://codepen.io/paulcp/pen/LYKmQQK?editors=100

### Reproduction Steps

1. In a single select combobox with a selected item, type in the combobox until no results are visible
2. After a short delay, type any key
3. Notice the combobox collapses
4. If you click the combobox again, you'll see your text still present, but again any keypress will collapse the menu

### Reproduction Version

2.11.1 (latest)

### Relevant Info

Something between 2.9.0 and 2.11.0 (which I believe was the next release?) broke this behavior. 

### Regression?

2.9.0

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

This is causing one of our UI's not to work as it's built around the user searching their combobox and it keeps closing on them.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by anveshmekala** [comment]
Combobox closes when no filtered results are shown as per spec https://github.com/Esri/calcite-design-system/issues/9617.
Agree that `filterText` should be retained when no results are shown.

cc: @driskull

**Comment by geospatialem** [comment]
Verified in `2.14.0-next.11`, where the component will close per [Anvesh's comment above](https://github.com/Esri/calcite-design-system/issues/10156#issuecomment-2400297595), but `filterText` is present in the component. Also keeps focus in the component upon closing, making a much better experience for the user:

![verify-10156](https://github.com/user-attachments/assets/2c9c41f8-af63-42b5-b5da-2ebf3b586e55)
