### ISSUE TITLE
calcite-card does not properly handle dynamically added footer slot content

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-design-system#10152]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Dynamically added footer slots do not render.

### Expected Behavior

Dynamically added footer slots like `<div slot="footer-end">` will render.

### Reproduction Sample

I think this can only be reproduced by creating a stencil component that uses calcite-card. I could probably do this in React Codesandbox but I don't know react well enough.

### Reproduction Steps

Create a component like this:

```tsx
import { Component, Host, State, VNode, h } from '@stencil/core';

@Component({
  tag: 'parent-component',
  // styleUrl: 'parent-component.css',
  shadow: true,
})
export class ParentComponent {

  // The button works as expected, toggling the slot on and off
  // But _only_ if the initial value of showSlot is true
  @State() showSlot = false;

  maybeRenderSlot(slotName): VNode {
    if (this.showSlot) {
      return <div slot={slotName}>foobar</div>;
    }
  }

  render() {
    return (
      <Host data-element="parent-component">
        This is the parent component
        <calcite-button onClick={_ => this.showSlot = !this.showSlot}>Toggle Slot</calcite-button>
        {/* slotted component is just a very simple stencil component with a named slot
            to try to determine if the problem is specific to calcite-card
            slotted component works as expected
        <slotted-component>
          {this.maybeRenderSlot("main")}
        </slotted-component> */}
        <calcite-card>
          WAT
          {/* <div slot="footer-start">foo</div> */}
          {this.maybeRenderSlot("footer-end")}
        </calcite-card>
      </Host>
    );
  }
}
```

Then run the samples and observe that the calcite-button in the component works when the initial value of `showSlot` is true but not when the initial value of `showSlot` is false.

### Reproduction Version

2.11

### Relevant Info

I think this can be fixed by doing something like this in calcite-card:

```tsx
@State() hasFooterStart = false;

@State() hasFooterEnd = false;

get hasFooter(): boolean {
  return this.hasFooterStart || this.hasFooterEnd;
}

private handleFooterStartSlotChange = (event: Event): void => {
  this.hasFooterStart = slotChangeHasAssignedElement(event);
};

private handleFooterEndSlotChange = (event: Event): void => {
  this.hasFooterEnd = slotChangeHasAssignedElement(event);
};

private renderFooter(): VNode {
  const { hasFooter } = this;
  return (
    <footer class={CSS.footer} hidden={!hasFooter}>
      <slot name={SLOTS.footerStart} onSlotchange={this.handleFooterStartSlotChange} />
      <slot name={SLOTS.footerEnd} onSlotchange={this.handleFooterEndSlotChange} />
    </footer>
  );
}
```

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

I causes one of the components we commonly use on customer sites to not work properly.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
Will need to address https://github.com/Esri/calcite-design-system/issues/6059 to mitigate.

**Comment by DitwanP** [comment]
🍭 Verified locally on `dev` with code from provided repro case. Footer now shows up when `showSlot` is defaulted to `false`

https://github.com/user-attachments/assets/f459bf54-4431-43c7-8cfd-a45585957292
