### ISSUE TITLE
Calcite shell panel div.container wrapper does not honor the width of the shell panel

### ISSUE THREAD

**Issue by gayukumar** [Esri/calcite-design-system#10176]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

https://codepen.io/khoomgayu/pen/yLdqaZY?editors=100

this codepen we can see that the calcite tabs does need to have the overflow actions but due to div.container not honoring the width of the shell panel it is overflowed and chopped of the content

### Expected Behavior

```ts
// This is a work around to make sure we do not have the overflow and takes the width of calcite shell panel into the div wrapper in shadow root
    const shadowEl = this.calciteShellPanelRef?.shadowRoot?.querySelector(".container");
    if (shadowEl) {
      (shadowEl as any).style.width = "100%";
    }
```

width of the div.container needs to honor the parent width

### Reproduction Sample

https://codepen.io/khoomgayu/pen/yLdqaZY?editors=100

### Reproduction Steps

verify the overflow menu in the code pen

### Reproduction Version

2.11.1

### Relevant Info

Chrome browser, but happens on any os or browser

### Priority impact

impact - p1 - need for current milestone

### Impact

High impact as the R3 map viewer needs this.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.4`

**Comment by DitwanP** [comment]
🍡 Verified on `2.13.0-next.4`
https://codepen.io/Ditwan-Price/pen/vYqQYoE?editors=100

**Comment by gayukumar** [comment]
@DitwanP how do I test it in my repo? Is this part of `2.12.2`?

**Comment by gayukumar** [comment]
@DitwanP the height of panel is not supported by the shadow div.content please fix this as well thanks. 👍 
```tsx
const shadowContentEl = this.calciteShellPanelRef?.shadowRoot?.querySelector(".content");
    if (shadowContentEl !== null && shadowContentEl !== undefined) {
      if ((shadowContentEl as any).style.height !== "100%") {
        (shadowContentEl as any).style.height = "100%";
      }
    }
```

**Comment by DitwanP** [comment]
@gayukumar You can test in your repo using the version I listed above with the verification comment `2.13.0-next.4` or a more recent `next` version.

**Comment by DitwanP** [comment]
> @DitwanP the height of panel is not supported by the shadow div.content please fix this as well thanks. 👍
> 
> ```tsx
> const shadowContentEl = this.calciteShellPanelRef?.shadowRoot?.querySelector(".content");
>     if (shadowContentEl !== null && shadowContentEl !== undefined) {
>       if ((shadowContentEl as any).style.height !== "100%") {
>         (shadowContentEl as any).style.height = "100%";
>       }
>     }
> ```

If possible, could you provide a repro for this as well so we can visually see the issue that you are referring to here.
