### ISSUE TITLE
[Panel] popover in panel constrained to panel content

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#10180]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

As of 2.12.0 a popover in a panel is constrained to the content area of the panel excluding the title and footer areas. This can cause unnecessary y overflow/scrolling and the popup not aligning with the header action if trigger thereby.

2.12.0

![image](https://github.com/user-attachments/assets/03b0694a-725d-43db-ae5b-6f8d4972a879)

2.11.1

![image](https://github.com/user-attachments/assets/808a4b19-f32e-4284-acf7-0917de876ff8)

This is particularly an issue with floating panels that may not have all the necessary height in the content area.

![image](https://github.com/user-attachments/assets/2e0f48a5-78f7-4227-8e51-002d4dbd7fe0)

![image](https://github.com/user-attachments/assets/5f068af1-7c8f-4152-a83f-f8e1f5224f2f)

### Expected Behavior

Popover should use the entire panel.

![image](https://github.com/user-attachments/assets/1b7e5d2e-57cb-4355-938b-dfe73e34fcff)

### Reproduction Sample

https://codepen.io/COV-GIS/pen/RwzBgGW

### Reproduction Steps

1. Switch between the 2.11.1 and 2.12.0 resource tags.
2. Click on the gear iconed action.

### Reproduction Version

2.12.0

### Regression?

2.11.1

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

It would be nice to have this fixed sooner than later.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
@COV-GIS adding `overlay-positioning="fixed"` to the `popover` should mitigate the above: https://codepen.io/geospatialem/pen/vYqaeMo

```html
<calcite-popover auto-close closable heading="Options" scale="s" overlay-positioning="fixed" placement="bottom-end">
    ...
</calcite-popover>
```

**Comment by driskull** [comment]
This is due to the setting of the `position:relative` in this PR: https://github.com/Esri/calcite-design-system/pull/10117

The way to avoid this is to move the popover outside of the panel. Like so: https://codepen.io/driskull/pen/yLdqPPq?editors=1000

**Comment by COV-GIS** [comment]
Thanks @geospatialem and @driskull.

I have tried to avoid using fixed positioning unless absolutely necessary. But looks like that will have to be the way to go in this case. Not practical to create a separate popover component to create outside the panel on account of my component having the panel element itself the root of the vnode.

Closing.

***

Can you answer a quick unrelated question @driskull? Why is panel (and by extension dialog) footer now focusable? And only by clicking the footer or heading; but not by tabbing. If it needs to be for accessibility or the like it should also include the top focus:

![image](https://github.com/user-attachments/assets/1d7ad653-340e-423c-8364-d70dfa1a9700)
