### ISSUE TITLE
Sass compiler does not throw an error when expected

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#10188]
### Priority impact

p - low

### Summary

Sass names refactor in the `loader` revealed that Sass compiler did not throw an error when it was referencing a function that does not exist.

### Desired Outcome

Sass compiler should throw an error when referencing a function that does not exist.

**Comment by jcfranco** [comment]
This is a [known limitation for unknown Sass functions](https://sass-lang.com/documentation/at-rules/function/#plain-css-functions:~:text=gradient(%23f2ece4%2C%20%23e1d7d2)-,%E2%9A%A0%EF%B8%8F%20Heads%20up!,on%20your%20stylesheet%E2%80%99s%20output%20to%20be%20notified%20when%20this%C2%A0happens!,-%F0%9F%92%A1%20Fun%20fact%3A):

> ### ⚠️ Heads up!
>
> Because any unknown function will be compiled to CSS, it’s easy to miss when you typo a function name. Consider running a [CSS linter](https://stylelint.io/) on your stylesheet’s output to be notified when this happens!
 
 Stylelint's [`function-no-unknown`](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-no-unknown) rule can help with this. Local testing looks good, but we need to specify which functions to ignore, as it doesn't do this automatically. Currently, we only have 2 custom sass functions, so we can add coverage for this easily. 
 
Keeping track of custom functions will be a manual process for now, but we may be able to automate this.

**Comment by jcfranco** [comment]
> Keeping track of custom functions will be a manual process for now, but we may be able to automate this.

This step has ben automated via a `pre-commit` hook.

**Comment by DitwanP** [comment]
🍭 Verified locally on `dev`
