### ISSUE TITLE
Loader no longer animating

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#10182]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Loader no longer animating.

### Expected Behavior

Loader should be animated.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/loader/

### Reproduction Steps

I came across this with button loading: https://developers.arcgis.com/calcite-design-system/components/button/ Check `loading` property checkbox.

Can also be seen on any reference page when the sample is loading.

### Reproduction Version

2.12.0

### Regression?

2.11.1

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Possibly related to https://github.com/Esri/calcite-design-system/pull/9957.

**Comment by geospatialem** [comment]
After closer inspection it appears the regression is from #10147 from the following lines: https://github.com/Esri/calcite-design-system/commit/3c4775ce1d59d72389511287ee51c3f36ac403f7#diff-98ccabacd6112ddd54974f877b97ee4e4db45ca390ab1326c026a0f70b5d0dd4.

We should explore screenshot testing that supports multiple snapshots after timeline to ensure the component spinning is performing as-expected.

**Comment by geospatialem** [comment]
Verified in `2.13.0-next.5` with https://codepen.io/geospatialem/pen/poXQJWz
