### ISSUE TITLE
Slots Missing from Calcite Modal

### ISSUE THREAD

**Issue by dnrr-fd** [Esri/calcite-design-system#10194]
### Description

Please add the slots back for the Modal component. I know it is deprecated but I am still using it and need the reference.

### Which Component

Modal

**Comment by jcfranco** [comment]
Thanks for reaching out. This might be a documentation site issue, as we haven't removed any slots (see [documented slots](https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/src/components/modal/modal.tsx#L61-L67)). cc @geospatialem @DitwanP @macandcheese

**Comment by jcfranco** [comment]
@macandcheese pointed out the issue. ✨🏆✨ This should be fixed in next week's patch release.

**Comment by DitwanP** [comment]
🍡 Verified

**Comment by geospatialem** [comment]
@dnrr-fd Updated in this morning's September 5th documentation site update: https://developers.arcgis.com/calcite-design-system/components/modal

![image](https://github.com/user-attachments/assets/83bc9f67-e853-42f7-8148-c7c023d57451)

**Comment by dnrr-fd** [comment]
Thanks!
