### ISSUE TITLE
shell-panel: z-index changed

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#10222]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Popovers with a z-index of 100 that used to appear over a shell-panel are now appearing below the shell-panel. 
<img src=https://github.com/user-attachments/assets/2b1c5ca2-cbff-4ca6-b24a-792d31e609aa width=250/>

new
![image](https://github.com/user-attachments/assets/3ea177b0-f459-4dce-84ae-3c375fe9fe30)

old
![image](https://github.com/user-attachments/assets/9efe23b0-34a7-4fc6-8bc5-d9ec97e42cba)

cc @jcfranco 

### Expected Behavior

z-index of shell-panel stays at 2.

### Reproduction Sample

https://codepen.io/afreitag/pen/XWzOjwK

### Reproduction Steps

Click on the button and see the popover open on top. Now change to 2.12.1 and do that again. You have to change the z-index of the popover from 100 to 400 to make it work again.

### Reproduction Version

2.12.0 and 2.12.1

### Regression?

yes

### Priority impact

impact - p0 - emergency

### Impact

Some Map Viewer components overwrite the default popover z-index to 100 for popovers appearing above the panels but below the global-nav dropdowns. It has to be 100 or less for the global-nav, but now 400 or above for shell-panel.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Possibly as a result of https://github.com/Esri/calcite-design-system/pull/9912. Will explore alternative approaches, outside of tokens to accommodate.

**Comment by geospatialem** [comment]
Verified on the `dev` branch:

![verify-10222](https://github.com/user-attachments/assets/03be2e74-42d9-4bfc-9c9c-264621eef88d)
