### ISSUE TITLE
Flow should stop propagation of calciteFlowItemBack event

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10225]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

calciteFlowItemBack propagates past a flow and potentially to another flow further up the DOM

### Expected Behavior

calciteFlowItemBack event stops propagation at the first parent flow

### Reproduction Sample

https://codepen.io/driskull/pen/GRbPReK

### Reproduction Steps

1. open codepen
2. click back button on flow
3. the console.log should not occur

### Reproduction Version

2.12.2

### Regression?

No

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Closing - can use the target or the composed path instead.
