### ISSUE TITLE
Potentially unused class members

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10234]
### Description

Some Calcite components seem to have unused members - could you review these to check if they can be removed?

### Proposed Advantages

Less code

### Which Component

- `action-bar`: `expandToggleEl`
- `action-pad`: `expandToggleEl`
- `combobox`: `toggleCloseEnd`, `toggleOpenEnd`
- ~`dropdown`: `defaultAssignedElements (never read)`, `slotChangeHandler`~ reverted by bbe0ced9dd91d170d23b5680d71a18c03eae83b8
- `modal`: `initialOverflowCSS`
- `tab-title`: `containerEl`, `parentTabNavEl`
- `time-picker`: `calciteInternalTimePickerBlur`, `calciteInternalTimePickerFocus` (emitted, but no one listens to them)
- `tree-item`: `childrenSlotWrapper`

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by maxpatiiuk** [comment]
P.S.: github action for this issue failed: https://github.com/Esri/calcite-design-system/actions/runs/10741293371/job/29791330869
Potentially because I am an outside member?

**Comment by geospatialem** [comment]
> P.S.: github action for this issue failed: https://github.com/Esri/calcite-design-system/actions/runs/10741293371/job/29791330869
> Potentially because I am an outside member?

Thanks for letting us know, this might be an issue with our CI. We have an open issue for the priority labels with https://github.com/Esri/calcite-design-system/issues/10011. We may need one for the product labels as well cc @DitwanP for additional investigation 🕵🏻, if we need to also take a look at the product label automation as well.

**Comment by DitwanP** [comment]
✨🧹✨
