### ISSUE TITLE
[Slider] potentially unintentional property name collision

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10235]
### Description

HTMLElement has a "translate" boolean property
slider.tsx has a "translate" private method
This collision is potentially unintentional - could you rename the private method?

### Proposed Advantages

Avoids collision

### Which Component

slider

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍡 Verified
