### ISSUE TITLE
[Refactor] refactor-out JSX spread usages.

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10236]
### Description

Calcite has 10 usages of JSX spread syntax (`{...props}`).
This syntax is not supported in lit-html at the moment.
Several alternative solutions are available.
See [this documentation](https://qawebgis.esri.com/arcgis-components/?path=/docs/references-lumina-jsx--docs#spread-attributes) page for options

### Proposed Advantages

Better performance
Better type checking

### Which Component

Several - search for `\{...` in your IDE

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
✨🧹✨
