### ISSUE TITLE
List - dynamically changing list-items within a list causes existing filter and new list-items to be out of sync

### ISSUE THREAD

**Issue by iyouth23** [Esri/calcite-design-system#10230]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a filter is applied to a `calcite-list` and the `calcite-list-items` within that list are modified, the resulting list-items that show up do not match what is expected based on the `filterText`.

### Expected Behavior

The filter and the list-items within a `calcite-list` should always be in sync.

### Reproduction Sample

https://codepen.io/iyouth66/pen/LYKMpbQ?editors=1000

### Reproduction Steps

- Open this codepen: https://codepen.io/iyouth66/pen/LYKMpbQ?editors=1000
- Click "List 1" > a `calcite-list` should populate with three list-items > Now filter by "Avenir" > The list items filter properly so that only two items are showing > Now click "List 2", which changes the content of the calcite-list to four different list-items > **the items don't show up** > Now change "Avenir" to "Aveni" to trigger a filter change > The filtered items show up again.

### Reproduction Version

Not a regression

### Relevant Info

cc @driskull

### Priority impact

impact - p1 - need for current milestone

### Impact

Affects our font-picker in ArcGIS Online, which handles two filterable lists with unique content.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Verified with the Chromatic build:

![verify-10230](https://github.com/user-attachments/assets/86b86992-f703-4759-988c-d90231b117a9)
