### ISSUE TITLE
Closed floating elements should not cause scrollbars

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10240]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Closed floating elements cause scrollbars

### Expected Behavior

Closed floating elements should not cause scrollbars

### Reproduction Sample

https://codepen.io/driskull/pen/RwzEMYv?editors=1100

### Reproduction Steps

1. open the codepen
2. notice the scrollbars shown due to a closed popover

### Reproduction Version

2.12.2

### Relevant Info

https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/63967

### Regression?

No

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment]
@geospatialem @DitwanP moved this one to October.

**Comment by iyouth23** [comment]
+1 from the AGOL Map Viewer team - we have multiple instances of this bug occurring on production, so the impact is high.

<details><summary>Demo</summary>

https://github.com/user-attachments/assets/e5879ed9-730c-496f-95ca-248bc615fd12

</details>

**Comment by zaramatheson** [comment]
@driskull @geospatialem Any chance this one could get priortized for a 2.13 patch? It affects a few spots in MV.  We are investigating the workaround desccribed in the JSAPI issue, but it would have to be implemented in quite a fewplaces.

**Comment by driskull** [comment]
@zaramatheson let me know if the workaround is working for you. I'll defer to @jcfranco and @geospatialem for when this can be installed.

**Comment by iyouth23** [comment]
> @zaramatheson let me know if the workaround is working for you. I'll defer to @jcfranco and @geospatialem for when this can be installed.

@driskull I'm unable to apply the workaround to these Map Viewer cases, but I'm not sure if it's a case of our components being nested too deep within other components, or something else. The workaround for the API also seems most relevant for hidden elements, but our concern is more related to currently visible elements whose content overflows a specified max-height, which feels like a slightly different issue.

Just for a paper trail, the Map Viewer scroll issues are coming from this change: https://github.com/Esri/calcite-design-system/pull/10117/files#diff-0b45120ffa61191421f1699207bb91da11d979e0a76a1b28d50353a3b17394c2R172 that adds `position: relative` to `<div class="content-wrapper">` in `calcite-panel`.

cc @AdelheidF

**Comment by driskull** [comment]
It could be a separate issue than this one.

From the screenshot gifs, it seems like its more likely a flex/display issue. Something isn't taking up its full height which is causing the multiple scroll bars.

Its hard to be sure without a good reproduction case we can use.

If it is the `position: relative` on the flow-item or panel, you can easily override it by setting a style on the element. That style is applied to the host of the component so it can be overriden.

Can you try setting `position:static` or `position:inherit` to see if it fixes your use case?

**Comment by iyouth23** [comment]
`position: static` and `position: inherit` don't seem to have any effect. I'm wondering if there's something else going on here. Sometimes the extra scrollbar doesn't show up when selecting certain dropdown items, even if there _is_ overflow. I'm not sure why this is.

If I then go in and delete the `calcite-dropdown` component we're using, the extra scrollbars still remain, which suggests a different root cause for this issue 🤔

https://github.com/user-attachments/assets/ff572b84-6afe-4b44-adb3-2c6b0b472fc9

**Comment by iyouth23** [comment]
Here's an updated repro case: https://codepen.io/iyouth66/pen/BaXKYxz?editors=1100. Observe that setting the height on a `div` inside a `calcite-panel` and specifying `overflow-y: scroll` on that `div` triggers that extra space.

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.7`
