### ISSUE TITLE
calcite-input-time-zone issues

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-design-system#10289]
### Check existing issues
- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

#### 1. [related: [#8112](https://github.com/Esri/calcite-design-system/issues/8112), [#8005](https://github.com/Esri/calcite-design-system/issues/8005)] `Input Time Zone` does not support a few IANA names like:
   - America/Argentina/Buenos_Aires
   - America/Indiana/Indianapolis
   - America/Kentucky/Louisville
   - Asia/Ho_Chi_Minh

#### 2. [related: [#8005](https://github.com/Esri/calcite-design-system/issues/8005)] `Input Time Zone` does not support IANA time zone representing fixed offsets like:
   - Etc/GMT
   - Etc/GMT+1
   - Etc/UTC

#### 3. Other irregularities:
  - `Pacific/Fiji` maps to `"Fiji, Fiji"`. Fiji is the name of the country not a city.
  - `Asia/Hong_Kong`, should it be "Hong Kong, China" not "Hong Kong, Hong Kong"
  - ditto for `Asia/Macau` 

 #### 4. When `value` is programmatically updated the country portion is omitted.

#### 1. Expected:
  - "Buenos Aires, Argentina"
  - "Indianapolis, United States"
  - "Louisville, United States"
  - "Ho Chi Minh City, Vietnam"

#### 2. Expected:
As discussed with @emmilaakso212 and @jcfranco, perhaps the component should have a new leading group entitled "Fixed" with entries for "Coordinated Universal Time" and other fixed offsets.
![image](https://github.com/user-attachments/assets/958a028a-6a60-491c-bdab-ce8fcb2135fb)

### Reproduction Sample
https://codepen.io/richiecarmichael/pen/yLdwdyZ?editors=1000

#### For (1) to (3):
- Click [here](https://developers.arcgis.com/calcite-design-system/components/input-time-zone/) to open the input-time-zone sample page.
- Enter text in the `value` property.
- Observe updated widget.

#### For (4):
- Click [here](https://codepen.io/richiecarmichael/pen/yLdwdyZ?editors=1000) to open codepen app
- Click blue "change time zone to NYC" button
- Observe first `input-time-zone` component.

### Reproduction Version
2.12.1

### Relevant Info
Windows w/ Microsoft Edge version 128

### Regression?
No

### Priority impact
impact - p3 - not time sensitive

### Impact
Blocking [#64863](https://devtopia.esri.com/WebGIS/arcgis-js-api/pull/64863).

### Calcite package
- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team
ArcGIS Maps SDK for JavaScript

// @jcfranco

**Comment by jcfranco** [comment]
Bouncing back to me based on @richiecarmichael's early testing ✨🏆✨:

1. > I'm seeing some odd behavior when items are picked. Items are being overwritten.
2. > Would be look better if the items in the global group were sorted in numerical order rather than alphabetical?
3. > I think Ho Chi Minh, Vietnam should be [Ho Chi Minh City](https://en.wikipedia.org/wiki/Ho_Chi_Minh_City), Vietnam.
4. > When a city search has no results, the search field is cleared and the original results selected. I tried searching for "banana" but can only get to "ban".

**Comment by DitwanP** [comment]
🍠✨ Verified locally on `dev`
