### ISSUE TITLE
input-number `value` typed as number instead of string

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#10290]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

input-number `value` typed as number instead of string

### Acceptance Criteria

input-number `value` typed as number instead of string

https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/src/components/input-number/input-number.tsx#L341

### Which Component

input-number

### Example Use Case

input-number `value` is typed as a string but is a number. Basically I'm tired of `const x = input.value as unknown as number;` to make typescript happy. And not being able to deconstruct the input element object.

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/8578.
