### ISSUE TITLE
[Input-Date-Picker] valueAsDate array value not handled by watcher

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10291]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The type of `valueAsDate` is `Date | Date[]`.

However, the watcher here has wrong type:

https://github.com/Esri/calcite-design-system/blob/791fd782ac275c27e7a32b37b62e9c48b4a18f42/packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx#L189-L190

`this.datePickerActiveDate` has type `Date`, so assigning `Date[]` to is is an error

### Expected Behavior

Update the watcher to handle the `Date | Date[]` property type

### Reproduction Sample

-

### Reproduction Steps

-

### Reproduction Version

2.13.0-next.9

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
Possibly handled by https://github.com/Esri/calcite-design-system/pull/8402. cc @anveshmekala

**Comment by DitwanP** [comment]
This does not seem to be an issue any more, not getting any errors as described.
