### ISSUE TITLE
Input Date Picker Range steals focus from other inputs

### ISSUE THREAD

**Issue by fnquinteros** [Esri/calcite-design-system#10301]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When you click on the date picker and then directly click on any other input, the focus goes back to the date picker.

### Expected Behavior

The focus should go to the element clicked and should't go back to the date picker

### Reproduction Sample

https://codesandbox.io/p/devbox/dreamy-ioana-h6qh2h?file=%2Fsrc%2FApp.jsx%3A12%2C7&workspaceId=f51e3505-54ad-4d46-9b44-07aefd12f0d7

### Reproduction Steps

1. Click Date picker (opens calendar)
2. Click another input

### Reproduction Version

latest

### Relevant Info

Tested on a Macbook on Chrome.

### Priority impact

impact - p1 - need for current milestone

### Impact

This is part of a new functionality we're implementing that releases in December under a feature flag for controlled user testing. This issue compromises accessibility, so it would be great to have it fixed for the upcoming release.

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Urban

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-design-system/pull/8402 might fix this. @anveshmekala

**Comment by anveshmekala** [comment]
focus is invoked `onClose` [here ](https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx#L878)which is causing the issue.

Fixed in https://github.com/Esri/calcite-design-system/pull/8402

**Comment by DitwanP** [comment]
Verified on `2.14.0-next.19`

https://codesandbox.io/p/devbox/elegant-nobel-ts9qnt
