### ISSUE TITLE
[Action Pad] Horizontal action groups do not align

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#10307]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Action pad groups are slightly unaligned
<img width="266" alt="Screenshot 2024-09-13 at 3 38 08 PM" src="https://github.com/user-attachments/assets/489598b6-de41-41ee-b3eb-23f4a7ac6d89">

### Expected Behavior

Action pad groups are aligned

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/action-pad/

### Reproduction Steps

1. Go to sample
2. Change to "Action Pad with groups"
3. Change to horizontal layout
4. See issue

### Reproduction Version

2.12.2

### Regression?

2.11

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Potentially related to #10058

**Comment by alisonailea** [comment]
Issue identified. There is an extra border-block-end. PR incomming.

**Comment by geospatialem** [comment]
Verified with Chromatic build:
![image](https://github.com/user-attachments/assets/70d02c03-72c5-400f-8a0b-913b0e97c612)
