### ISSUE TITLE
Migrate component framework to Lit

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#10310]
### Priority impact

p - high

### Summary

Migrating to Lit will enable us to leverage key features that will streamline development and improve our overall workflow.

Blocked issues: #8249, #0220, #8307, #9057, #9090, #10038, #10237, #10263, #9089, #7631, #9494, #10399, #10423, #10422, #10376, #991, #10619, #10227, #9260

### Desired Outcome

Components are fully Lit-based.

#### Related

#10356
#10352
#10344 
https://github.com/Esri/calcite-design-system/issues/8073#issuecomment-2174193805 (might address potential bug)

**Comment by DitwanP** [comment]
Verified 🔥
