### ISSUE TITLE
[Panel] is displayed when initially closed

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10320]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Panel is displayed when closed initially

### Expected Behavior

Panel is not displayed

### Reproduction Sample

https://codepen.io/driskull/pen/qBzGzmB?editors=1000

### Reproduction Steps

1. open the codepen
2. notice that panel is shown when it should't be

### Reproduction Version

2.12.2

### Regression?

No

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by abp6318** [comment]
Beat me to logging this one. Thank you for writing this up. The ArcGIS Hub team has a temp fix in our repo:

```css
calcite-panel[closed] {
  @apply hidden;
}
```

**Comment by DitwanP** [comment]
🍠 Verified on `2.13.0-next.15`
