### ISSUE TITLE
Dialog - escapeDisabled prevents all text edits

### ISSUE THREAD

**Issue by iyouth23** [Esri/calcite-design-system#10337]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Adding `escapeDisabled: true` to the `calcite-dialog` component will prevent text from being entered in any editable component (input, text-area, etc.).

### Expected Behavior

`escapeDisabled: true` should prevent the dialog only from closing when the Escape key is pressed. It should not affect text inputs in other areas.

### Reproduction Sample

https://codepen.io/iyouth66/pen/dyBBdMj?editors=1100

### Reproduction Steps

1. Open this codepen: https://codepen.io/iyouth66/pen/dyBBdMj?editors=1100
2. Try to type in the `calcite-text-area` component
3. Observe that you cannot add text at all.

### Reproduction Version

2.11.0

### Relevant Info

I see this `handlePanelKeyDown` method which appears to block all key presses from having any effect if `escapeDisabled` is `true`: https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/src/components/dialog/dialog.tsx#L799.

### Priority impact

impact - p1 - need for current milestone

### Impact

Needed for any migration from `calcite-modal` to `calcite-dialog`.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
