### ISSUE TITLE
Refactor-out usages of Stencil's "readTask"

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10348]
### Description

In 3 files, Calcite uses Stencil's `readTask()` function.

Could you check if there was a particular reason readTask was used or was it just a performance micro optimization?

Lit's default [re-render scheduling is very simple](https://github.com/lit/lit/blob/42260c2d3bb179756e109616338936de2a589801/packages/reactive-element/src/reactive-element.ts#L1297-L1318) - they don't provide readTask/writeTask. However, they expose hook for customizing the scheduling, letting you implement your own alternatives of Stencil's readTask/writeTask if it is important to have them.
 
Stencil's readTask/writeTask is a smart performance optimization, but it's hardly used - no usages at Esri outside of Calcite, and Calcite has only 3 usages.

TODO:
- check if readTask() is needed
- if not, refactor out it's usages

### Proposed Advantages

Compatibility with Lit's default scheduling system

### Which Component

3 files:
- https://github.com/Esri/calcite-design-system/blob/7fe16011957a45f3340ba9bfe137bcae258bf314/packages/calcite-components/src/components/stepper/stepper.tsx#L14
- https://github.com/Esri/calcite-design-system/blob/7fe16011957a45f3340ba9bfe137bcae258bf314/packages/calcite-components/src/components/tab-nav/tab-nav.tsx#L10
- https://github.com/Esri/calcite-design-system/blob/7fe16011957a45f3340ba9bfe137bcae258bf314/packages/calcite-components/src/utils/openCloseComponent.ts#L1

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍠✨
