### ISSUE TITLE
refactor(tests): migrate away from newSpecPage

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10349]
### Priority impact

p - low

### Test type

Unit tests

### Which Component(s)

Heading

### Unstable Tests

Calcite has 1410 newE2EPage tests and only 2 newSpecPage tests in one file:

https://github.com/Esri/calcite-design-system/blob/7fe16011957a45f3340ba9bfe137bcae258bf314/packages/calcite-components/src/components/functional/Heading.spec.tsx#L2C10-L2C19

To simplify migration, Lumina temporary provides newE2EPage() function that matches Stencil's API. In the long term, it would be great to migrate to Vitest browser test to improve DX, performance and integrations with Storybook.

Given that newSpecPage is only used by Calcite in one file, Lumina doesn't provide Stencil's equivalent of newSpecPage.

TODO:
- Refactor the usage of newSpecPage in Heading.spec.tsx. Options: https://github.com/Esri/calcite-design-system/issues/10349#issuecomment-2377606428

### PR skipped, if applicable

#

**Comment by maxpatiiuk** [comment]
Lumina has an alternative to `newSpecPage`, and support for JSX in tests, but this is only supported in Vitest browser mode tests.

Since you are in Puppeteer E2E tests for now, some options come to mind:
- (simplest) In your test, use the `render()` function from lit-html directly to render the functional component to some html markup. This render() function will be called in Node.js, not browser.
- (verbose) Create a wrapper web component class for functional component and test that web component like you do any other component class
- (tricky) import the `render()` function from lit-html in the browser (using `await page.addScriptTag` or `await page.evaluate()`) and render the function component there.

**Comment by DitwanP** [comment]
🍡 Verified
