### ISSUE TITLE
refactor(SASS): update declarations that appear after nested rules

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10347]
### Description

After updating SASS dependency to the latest in Lumina'ted Calcite, I started seeing this warning:

```yaml
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
4   │ ┌   * {
5   │ │     box-sizing: border-box;
6   │ │   }
    │ └─── nested rule
... │
8   │     color: var(--calcite-color-text-2);
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    src/assets/styles/_host.scss 8:3       @import
    src/assets/styles/includes.scss 9:9    @import
    src/components/action/action.scss 1:9  root stylesheet
```

Looks like this can be tackled before the migration.

### Proposed Advantages

Avoids deprecated syntax

### Which Component

src/assets/styles/_host.scss

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by driskull** [comment]
> Looks like this can be tackled before the migration.

Agreed.

**Comment by maxpatiiuk** [comment]
Another occurrence in src/components/tip-manager/tip-manager.scss

Doesn't seem to be anywhere else.

**Comment by jcfranco** [comment]
> src/components/popover/popover.scss

Can you confirm this warning occurs in `popover.scss`? I don't get the warning when doing a quick check on the file.

**Comment by maxpatiiuk** [comment]
Yes
I am getting a warning here:
https://github.com/Esri/calcite-design-system/blob/46a37e0c4bfd5461ce24d9488fcf80fc844bab77/packages/calcite-components/src/components/popover/popover.scss#L100-L104

Looks like that line was added just 4 days ago - maybe your local branch is out of date?
https://github.com/Esri/calcite-design-system/pull/10253

**Comment by jcfranco** [comment]
Thanks for confirming. I'll update my PR.

There seems to be a difference (or bug) with the Sass playground. It showed the warning for the other files, but [not `popover`](https://sass-lang.com/playground/#eJy1Vk2P2jAQvedXWBwqWGEWutsLqBJST/0NVbUyzoS4OHZkO3xsxX/v2AnBYQNFFRUcxp7xezOeZzuz2fMTEWulDRCXgwViXbWy5Ok5WRZiLxTJpGZOqDWtBM21deT3sc/FjNG7yLdiFijXRakVqLAomdfLE0Io5Uxy4YDGEO9UqBT2c7JlZngOKXWpt2BO7rHPs4Dh4P27H04a92A0WiRIshSKyyqFD3kP0d/rDJl7b53g8IdFZvg6sIOfo5DtJAeWYnAYELJkZSkPxMHeUTWjO8PKMF/u6UttHOjnBVrH5HiJWdyBOe1Avp4gX65Ayjsgu1l+OUG+diHDwmZZqYVyuOmwxe5ZqrCLi4hbl6Aa2m7knAglnGAyRE/62syUKGKqlTYpmJBTbVKrpUixHzjB+GZtdKVS1JLU5po2LuPGF3Fhkmao8iZq5uXSEt7GjmL6cZuIlw6mwWZU9hoo10a1QR9RIycNCTfq7t/Q+ughdSakfOwW3eR8e7PO6A0E7tp8zCZ6Vq9mMLFQMgn7IBNvUFY5HUYIUViK9OB4HmZ+VdaJ7IBzzLhYWNN4sLoiucYrNd9Q+Kvw/qmu0yltCtthCF0ZYBucK0KWgT7plmpBZpSDP2042uXIYUvGAU+nKZj00Vo5WgDKpgi13Ew93Aw3Eq9vjm47viEBE6rbFwMSdbGFtjfByGlWSXnuF+rlPFC6vZCC2CD1Jwf/nyY5szTqfaf7PrP6znpscRzLCq/UlZ40RbUl7U7GKanksq6oVw2F1PggrirntKK8bxs9APHJ4znb0VykKahFAzwnU/x5HUQ3TJB3kOjj75qWxMP/L4pzCONOhH2JI9v6HsBqc2bKu1ibgh/J6d/NuZXaOUiHLSBTIEfjHo/v/yhWRq277udN9/sKP1/+AK3BQRw=). A local, scoped, sass build shows the warning now.

**Comment by geospatialem** [comment]
@maxpatiiuk Would you be able to verify the SASS refactor / this one for us? ☺️

**Comment by maxpatiiuk** [comment]
The changes look good and no longer produce warnings!
