### ISSUE TITLE
[Action-Pad] potentially unused mutation observer

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10353]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Action-pad component creates a mutation observer:

https://github.com/Esri/calcite-design-system/blob/6f42a868f5cc65ae8a7c89f22ad9057b90fe4bca/packages/calcite-components/src/components/action-pad/action-pad.tsx#L152C3-L154

However once created, that observer is not used - `observer()` or `unobserve()` is never called on it.

If I am reading the code right, this observer has no effect.

### Expected Behavior

Either observer is supposed to be used, and it's a bug that it's not used, or it should be removed as dead code.

For an example of mutation observer being used, see how it's used in Action:
- https://github.com/Esri/calcite-design-system/blob/6f42a868f5cc65ae8a7c89f22ad9057b90fe4bca/packages/calcite-components/src/components/action/action.tsx#L177
- https://github.com/Esri/calcite-design-system/blob/6f42a868f5cc65ae8a7c89f22ad9057b90fe4bca/packages/calcite-components/src/components/action/action.tsx#L194

### Reproduction Sample

-

### Reproduction Steps

-

### Reproduction Version

v2.12.2

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment]
Seems like it should be used in order to update newly slotted `calcite-action-group` elements with the layout of them.

**Comment by maxpatiiuk** [comment]
Looks like popover has the same issue:

https://github.com/Esri/calcite-design-system/blob/4160af11ccb6bfb79314720e6f53b811f1cc6cb4/packages/calcite-components/src/components/popover/popover.tsx#L252

**Comment by driskull** [comment]
I think we need an eslint test to make sure mutation observers are observed and disconnected within a file :) cc @jcfranco

**Comment by maxpatiiuk** [comment]
> I think we need an eslint rule to make sure mutation observers are observed and disconnected within a file :) cc @jcfranco

It might be better to just create a controller for that - the controller will take care of observing connected/disconnect.

Controllers would simplify a lot of boilerplate you are having - connectMessages, connectLocalized, setComponentLoaded, etc - all of that will go away

**Comment by DitwanP** [comment]
🍠 Verified locally on `dev`
