### ISSUE TITLE
[Sheet] Add support for non-modal Sheet, other improvements

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#10364]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Placeholder issue for a set of enhancements to improve the Sheet component. This will support more use-cases and improve consistency with the Dialog component.

Rendering a Panel inside Sheet will provide an enhanced developer experience as well as ensure visual similarity in implementations.

### Acceptance Criteria

- Sheet renders Panel to match Dialog, passing through appropriate slots + properties.
- Sheet adds nonmodal display by default (breaking change) to match Dialog
- Keeps the "overlay / float" display types
- Resizability is added to Sheet - using an updated affordance with generous hit area to support the thumb gestures / mobile behavior that is common + expected with these displays (design to discuss: swipe tolerances for min / max height (or width), swipe tolerance for `close`, etc). Note that this doesn't apply just to mobile viewport sizes - these are needed behaviors in larger environments as well.

### Relevant Info

cc @SkyeSeitz @ashetland for ui / ux discussion + final properties / slots needed from a design perspective.

### Which Component

Sheet

### Example Use Case

As a designer-user - I want to use a nonmodal Sheet, and have the visual display match Dialog and other components

As a developer-user - I want to build the component in a similar manner to Dialog, and simplify the need to manage properties with my own slotted Panel inside Sheet

As an end-user - I want to use common mobile "niceties", like large hit areas for thumb dragging, and swipe interactions. 

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
This is covered in issues #7591, #9828

**Comment by ellenupp** [comment]
Hi @macandcheese, @ashetland, the title part of this issue (non-modal sheet) doesn't seem to be addressed by the issues linked above. Is this still something you're considering?

**Comment by macandcheese** [comment]
Yes, I think we can re-purpose this issue or open a new one to ensure that is addressed and added as a feature. cc @geospatialem

**Comment by geospatialem** [comment]
> Yes, I think we can re-purpose this issue or open a new one to ensure that is addressed and added as a feature. cc [@geospatialem](https://github.com/geospatialem)

cc @DitwanP Can you open a new issue / reopen the above (with some edits - as-needed) to address the a non-modal sheet issue Ellen mentions [above](https://github.com/Esri/calcite-design-system/issues/10364#issuecomment-2702210434) and in the original [description](https://github.com/Esri/calcite-design-system/issues/10364#:~:text=Acceptance%20Criteria,environments%20as%20welll) above?

**Comment by macandcheese** [comment]
Plus 3 from Dev Summit
