### ISSUE TITLE
[T9n] "messages" prop no longer needs to be exposed for usage in tests

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10399]
### Description

Blocked by https://github.com/Esri/calcite-design-system/issues/10310

Every Calcite component declares `messages` as an undocumented prop for usage in tests.

https://github.com/Esri/calcite-design-system/blob/f50c1707c81729ed55c55bc7ab7a9157b38a1b2b/packages/calcite-components/src/components/chip/chip.tsx#L118-L124

I believe the only usage in tests was this place:

https://github.com/Esri/calcite-design-system/blob/f50c1707c81729ed55c55bc7ab7a9157b38a1b2b/packages/calcite-components/src/tests/commonTests/t9n.ts#L36-L38

In Lumina, exposing `messages` as a prop is not necessary. Instead, the test can access internal component members in the following way:

```tsx
 getCurrentMessages = async (): Promise<MessageBundle> => { 
   return page.$eval(tag, (el: CalciteComponentsWithMessages) => el.manager.component.messages); 
 }; 
```

The `manager` property is the same both on the html proxy element and on the actual lit component. It has a `component` property for accessing the lit component (in turn, `component` has an `el` property for accessing the html proxy).
This property is not part of public typings or public documentation - it's for internal usage only.

### Proposed Advantages

Slight performance improvement and bundle size reduction because `messages` property would no longer need to be included in the lazy-loading metadata for each component.

### Which Component

All

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by maxpatiiuk** [comment]
Looks like there are also a few other props that were exposed for testing only:

eg carousel.tsx:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/c2a9eb78-0e66-406f-aee9-144d7bbe4369">

**Comment by DitwanP** [comment]
🍡 Verified
