### ISSUE TITLE
.setFocus() not working on several components in newer Chrome versions

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10394]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calling .setFocus() on calcite-action-group has no effect.

### Expected Behavior

If .setFocus() method on the calcite-action-group element is called, I am expecting the focus to move to first focusable element.

### Reproduction Sample

https://codepen.io/maxpatiiuk/pen/wvVBQXw?editors=1010

### Reproduction Steps

1. Open the codepen
2. Open console
3. See the the active element before and after the .setFocus() call remains the same

### Reproduction Version

2.13

### Relevant Info

The codepen works like expected in Chrome 119. Does not work in Chrome 128.

Calcite has E2E test for setFocus in calcite-action-group. Since Stencil's Puppeteer is using Chrome 119, the test is passing. Upon updating Chrome to 129, the test is failing:

https://github.com/Esri/calcite-design-system/blob/f50c1707c81729ed55c55bc7ab7a9157b38a1b2b/packages/calcite-components/src/components/action-group/action-group.e2e.ts#L58

---

Another example:

1. On the [docs page for action-bar](https://developers.arcgis.com/calcite-design-system/components/action-bar/), from the list of samples select "Action Bar with groups"
2. Open DevTools and find the calcite-action-group element rendered by the sample
3. Call .setFocus() method on that element in the devtools console.
4. In Chrome 119 that would focus the first slotted in action. In Chrome 129 this has no effect.

---

Possible solution:

Setting `delegatesFocus: true` for calcite-action element seems to fix this issue.
You already have it on calcite-action-group, but might need to add it to calcite-action too:
https://github.com/Esri/calcite-design-system/blob/f50c1707c81729ed55c55bc7ab7a9157b38a1b2b/packages/calcite-components/src/components/action-group/action-group.tsx#L38-L40

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by maxpatiiuk** [comment]
Also affects `calcite-date-picker.setFocus()`

**Comment by maxpatiiuk** [comment]
input-date-picker is affected too:

In Chrome 119 clicking on the `arrow-right` icon between the two text inputs will move focus to the first input.

![Screenshot 2024-10-05 at 13 29 47](https://github.com/user-attachments/assets/bb85b5c6-68a8-4154-95ba-cde351a4b8d0)

In Chrome 128 that does not happen.

**Comment by maxpatiiuk** [comment]
Also affecting calcite-inline-editable - that component by default tries to do `this.el.focus()`, which does not appear to move focus to the slotted-in input anymore.

Calling `this.inputElement?.setFocus();` instead works, but only if I add `delegatesFocus:true` to calcite-input (and same would have to be done for all the other inputs).

In general, it appears that `delegatesFocus:true` should be added to most (all?) Calcite components.

**Comment by maxpatiiuk** [comment]
Also affects `<calcite-menu>` test:
https://github.com/Esri/calcite-design-system/blob/aef57ddb325299e473495ab747ab4d8abeb4babd/packages/calcite-components/src/components/menu/menu.e2e.ts#L21-L25

Fixed by adding delegatesFocus to `calcite-menu-item` and changing `this.el.focus()` in `calcite-menu` to `this.menuItems[0]?.focus();`

**Comment by jcfranco** [comment]
> In general, it appears that delegatesFocus:true should be added to most (all?) Calcite components.

We should revisit our findings, but based on our [earlier exploration on `delegatesFocus`](https://github.com/Esri/calcite-design-system/issues/5147#issuecomment-1349616672), I wouldn't suggest enabling this by default for all components.

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.7` 🎉
