### ISSUE TITLE
[ESLint] Remove `ban-props-on-host`, `enforce-ref-last-prop`, `require-event-emitter-type` rules

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10398]
### Priority impact

p - low

### Summary

Calcite developed an `enforce-ref-last-prop` ESLint rule.
Such rule is not necessary in Lumina - the JSX `ref` prop is moved to be the last prop at build time, thus the sort order in the component code does not matter.

**Update**: Also remove `ban-props-on-host` and `require-event-emitter-type` rules as they will no longer be needed.

### Desired Outcome

After migrating to Lumina, remove the `ban-props-on-host`, `enforce-ref-last-prop` and `require-event-emitter-type` ESLint rules

**Comment by jcfranco** [comment]
We can deprecate and remove this in 3.x since https://github.com/Esri/calcite-design-system/pull/9086/files disabled the rule for components.

**Comment by jcfranco** [comment]
@geospatialem @DitwanP How do you suggest we proceed with this issue? We're deprecating now, but removing in 3.x.

**Comment by geospatialem** [comment]
Verified removals on the `dev` branch. 🧹 

Reassigning the issue back to development to remove the remaining markdown files 🔜 :
- [ban-props-on-host.md](https://github.com/Esri/calcite-design-system/blob/dev/packages/eslint-plugin-calcite-components/docs/ban-props-on-host.md)
- [require-event-emitter-type](https://github.com/Esri/calcite-design-system/blob/dev/packages/eslint-plugin-calcite-components/docs/require-event-emitter-type.md)
