### ISSUE TITLE
components: refactor aria-attributes to properly set values

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10407]
### Description

- only sets `aria-expanded` on button when present on host
- properly sets `boolean` values to strings on other components 
- removes `aria-hidden` from screen reader text

### Proposed Advantages

accessibility

### Which Component

all applicable

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍠 Verified locally on `dev`
