### ISSUE TITLE
[Dialog] All keydown events trapped when escape-disabled is present

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-design-system#10410]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When `escape-disabled` is present on a dialog, all keydown events are prevented so you can't for example tab between focusable elements or type in an input. 

### Expected Behavior

`escape-disabled` only impacts keydown on escape key

### Reproduction Sample

https://codepen.io/ellupp/pen/poMJEOp?editors=1000

### Reproduction Steps

1. Try typing in the input in the dialog, nothing happens

### Reproduction Version

2.12.2

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

needed for us to start using dialog in place of modal

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Dashboards

**Comment by geospatialem** [comment]
@ellenupp this should be mitigated in the upcoming `2.13.0` release via https://github.com/Esri/calcite-design-system/pull/10336. 

[Here's an example of the verification locally](https://github.com/Esri/calcite-design-system/issues/10363#issuecomment-2365302824) if of interest:

![verified](https://github.com/user-attachments/assets/dc69d4b8-909e-416c-b322-7a7b593d2e06)

Going to mark the above as a duplicate and close it out. 👍🏻

**Comment by ellenupp** [comment]
Ah thanks, only checked for duplicates in open issues!

**Comment by geospatialem** [comment]
> Ah thanks, only checked for duplicates in open issues!

Absolutely no worries, appreciate you filing so we can investigate either way! 🤜🏻🤛🏻
