### ISSUE TITLE
[Tests/card] Redundant event spy created

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10412]
### Priority impact

p - low

### Test type

a typo in a test

### Which Component(s)

card

### Unstable Tests

The following test for the calcite-card event creates two identical event spies:

https://github.com/Esri/calcite-design-system/blob/699e166f19786cee7c9b4a542a1d19426c1051ed/packages/calcite-components/src/components/card/card.e2e.ts#L91-L92

Based on the 2nd variable name, it seems like one of them is a typo. Was "click" event expected instead?

### PR skipped, if applicable

#

**Comment by DitwanP** [comment]
🍡✨
