### ISSUE TITLE
[Chip] close button icon color token not working in some configurations

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#10428]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `--calcite-chip-close-icon-color` token for `chip` is not working when `appearance` is default and the `kind` is set to either `"brand"` or `"inverse"`.

Look at the close icon for the two `chips` in the bottom left.
![image](https://github.com/user-attachments/assets/72ab069c-2bb9-4149-94e1-deb6dc0dbb57)

### Expected Behavior

The color set by the token should be applied with this `chip` configuration. 

### Reproduction Sample

N/A

### Reproduction Steps

1. Setup a chip with the described properties and values.
2. Change the close icon color with the `--calcite-chip-close-icon-color` token 
3. Notice the color not changing as expected

### Reproduction Version

2.13.0

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified by @DitwanP in the [PR](https://github.com/Esri/calcite-design-system/pull/10493#issuecomment-2398076847) 🎉
