### ISSUE TITLE
[ESLint] Remove require-event-emitter-type rule

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10423]
### Priority impact

p - low

### Summary

Blocked by https://github.com/Esri/calcite-design-system/issues/10310

Calcite developed an `require-event-emitter-type` ESLint rule.
Such rule is not necessary in Lumina because the default event emitter type is `void` rather than `any`.
Also, if event emitter type is not `void`, then the first argument in `.emit()` is mandatory (in Stencil it was always optional, leading to possible bugs if you forgot to provide the payload)

### Desired Outcome

Remove the `require-event-emitter-type` ESLint rule after the migration.

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/10482/.

**Comment by DitwanP** [comment]
🍡 Verified
