### ISSUE TITLE
[ESLint] remove ban-props-on-host ESLint rules

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10422]
### Priority impact

p - low

### Summary

Blocked by https://github.com/Esri/calcite-design-system/issues/10310

Calcite developed an `ban-props-on-host` ESLint rule.
Such rule is not applicable in Lumina because `<Host>` does not exist in Lit.

Instead, you can set props or attributes imperatively inside of connectedCallback or render.
It seems like Stencil's `<Host>` didn't check if attributes were already set by the user and would overwrite them. Imperatively, you can use `??=` instead of `=` when assigning props to avoid overwriting existing value.
The codemod takes care of migrating all `<Host>` usages.

### Desired Outcome

After migrating to Lumina, remove the `ban-props-on-host` ESLint rule.

**Comment by maxpatiiuk** [comment]
Blocked by https://github.com/Esri/calcite-design-system/issues/10310

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/10482/.

**Comment by DitwanP** [comment]
🍡 Verified
