### ISSUE TITLE
[input-time-zone] Remove unused time zone and country translations

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#10438]
### Description

https://github.com/Esri/calcite-design-system/issues/10289 ensures consistent time zones across browsers, so there are translations that are no longer valid.

### Proposed Advantages

Leaner translation bundle.

### Which Component

`calcite-input-time-zone`

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍡 Verified
