### ISSUE TITLE
calcite-card: calcite-cards nested within a parent calcite-card receive the same styling as the parent

### ISSUE THREAD

**Issue by LanceStasinski** [Esri/calcite-design-system#10467]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

In v2.13.0, calcite-cards that are nested within other calcite-cards receive the same styling as the parent. For example, the `--calcite-card-background-color` CSS property applies to the parent card and all children cards. This was not the case in v2.12.2 and before.

v2.13.0
![Screenshot 2024-10-01 at 12 54 01 PM](https://github.com/user-attachments/assets/8789a00a-e8af-4201-95a7-23431003f1e1)

v2.12.2
![Screenshot 2024-10-01 at 12 55 06 PM](https://github.com/user-attachments/assets/89481aff-6f56-44e8-bfb4-c9d0850e3a17)

### Expected Behavior

I expect that the CSS custom property applies to the card that matches the selector and not it's descendants. 

### Reproduction Sample

https://codepen.io/Lance-Stasinski/pen/XWvXRbq?editors=100

### Reproduction Steps

1. Nest a calcite-card within another calcite-card
2. Add a `style='--calcite-card-background-color: red;'` attribute to the parent calcite card.
3. Notice that the child card receives the red background as well. 

### Reproduction Version

2.13.0

### Relevant Info

MacOS Sonoma 14.6.1
Chrome 129.0.6668.70

### Regression?

2.12.2

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

We use nested calcite-cards in Field Maps Designer, and we style the cards differently based on their nesting depth. This change has broken the styling of the nested cards.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by macandcheese** [comment]
IMO this is an expected result - an easy workaround could be to set `initial` for that css property on the nested component: https://codepen.io/mac_and_cheese/pen/mdNreOe?editors=1000

**Comment by jcfranco** [comment]
I agree w/ @macandcheese. It looks like the cascading behavior of custom CSS props is working as intended.
