### ISSUE TITLE
Drop Angular wrappers in Calcite 3.0

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10465]
### Description

As per discussion №1281 in the AWC repository, AWC will phase out Angular wrappers for the 4.31 release.
Calcite can consider doing the same for the 3.0 release.

### Proposed Advantages

Fewer packages to maintain.
Fewer dependency version conflicts.
Smaller bundle size for consumers (without wrappers compared to with wrappers)

### Which Component

*

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by geospatialem** [comment]
Verified in the issue templates, packages, and workflows across the `dev` branch.
