### ISSUE TITLE
[shell-center-row] slotted action bar position change will not update shell center row

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10468]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If action-bar position changes after being slotted, the ordering of elements will be incorrect.

### Expected Behavior

If action-bar position changes after being slotted, the ordering will be correct.

### Reproduction Sample

https://codepen.io/driskull/pen/oNKbWzR?editors=1010

### Reproduction Steps

1. open codepen
2. wait 500ms
3. notice that actionBar position doesn't change

### Reproduction Version

2.13.0

### Relevant Info

https://github.com/Esri/calcite-design-system/pull/10451#discussion_r1783192493

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
It looks like the above was also mentioned in a PR for inclusion. During yesterday's triage session we discussed closing the above since `shell-center-row` is now deprecated. Closing the above out.
