### ISSUE TITLE
Make `npm dedupe` work

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10481]
### Priority impact

p - low

### Summary

Yarn has a very important command `yarn dedupe` for avoiding duplicate versions of the same dependency being present in the codebase (which can cause issues due for dependencies that rely on global state)

NPM has an equivalent `npm dedupe` command, however, it is failing in the Calcite monorepo:

![Screenshot 2024-10-02 at 22 13 46](https://github.com/user-attachments/assets/1539a80a-28be-456d-9928-6a7a0be298c0)

The error might get fixed by https://github.com/Esri/calcite-design-system/issues/10465

### Desired Outcome

Fixing the errors reported by this command would be quite useful for the Lumina migration as I am seeing duplicate versions of dependencies like vite/vitest/puppeteer/postcss, that are causing issues.

![image](https://github.com/user-attachments/assets/fbd479ad-635a-4f5b-9107-06380ecdc1ef)

**Comment by DitwanP** [comment]
Verified locally, ran with no errors 👌
