### ISSUE TITLE
[Input-time-zone] setting "open" before render() throws an error

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10491]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If you set "component.open=true" prop before calcite-input-time-zone component had it's render(), an exception will be throw here because `this.comboboxEl` is still undefined:

https://github.com/Esri/calcite-design-system/blob/def59bb5f723ac79053038a30b8128957952ff25/packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx#L202

### Expected Behavior

There should not be an exception

### Reproduction Sample

https://codepen.io/maxpatiiuk/pen/GRVqEmj?editors=1010

### Reproduction Steps

1. Set `.open=true` property or a calcite-input-time-zone after component's constructor() triggered but before render().
2. See exception in the console.

### Reproduction Version

2.13.0

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍡 Verified on `3.0.0-next.11`
