### ISSUE TITLE
[input-date-picker] faulty element visibility assertion

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10490]
### Priority impact

p - low

### Test type

incomplete test

### Which Component(s)

input-date-picker

### Unstable Tests

The following input-date-picker test is supposevely checking whether the date-picker calendar wrapper is open:

https://github.com/Esri/calcite-design-system/blob/42c132913f710912038554fd7eae0879ec3a0df1/packages/calcite-components/src/components/input-date-picker/input-date-picker.e2e.ts#L162-L168

However, it appears that this test condition is passing even if the date-picker wrapper is not open. (e.g if I move this assertion to be before `await input.click();`, it still passes).

TODO:
- Improve this assertion (or add `this.open` check)?
- Evaluate other places that may be similarly effected

**Comment by jcfranco** [comment]
This might get resolved by https://github.com/Esri/calcite-design-system/pull/8402. cc @anveshmekala

**Comment by DitwanP** [comment]
No longer an issue.
