### ISSUE TITLE
calcite tab icon coloring support

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-design-system#10497]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

It would be great if the `iconStart` and `iconEnd` properties for the calcite tab-title both had different css tokens so that they could be colored differently.

### Acceptance Criteria

Should be able to create a tab title with a start and end icon with different colors.

### Which Component

calcite-tab-title

### Example Use Case

![image](https://github.com/user-attachments/assets/9c12d303-b1b6-4bb5-a355-cf1a120d9d20)

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by jcfranco** [comment]
@geospatialem We'll have to push this to the November milestone. I missed that https://github.com/Esri/calcite-design-system/pull/10358 needs to land before the tabs component tokens can be installed. I still have to make some follow-up changes to the PR, but it's very close.

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.36` with the `tab` tokens:

```css
.holiday {
  --calcite-tab-icon-color-start: Chartreuse;
  --calcite-tab-icon-color-end: Crimson;
}
```

![image](https://github.com/user-attachments/assets/d62148e6-7911-4077-bba0-a444644a08fa)
