### ISSUE TITLE
[Shell Center Row] Add deprecation doc / logging to component

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#10506]
### Description

The Shell Center Row component was deprecated in `2.11.0` according to the docs: https://developers.arcgis.com/calcite-design-system/components/shell-center-row/

However there is no deprecation logging or `@deprecated` tag in the component file. I'd expect this to match the information conveyed on the documentation site.

### Which Component

Shell Center Row

**Comment by geospatialem** [comment]
Verified via console logging in `2.14.0-next.11` and for the component deprecation in the .tsx file on `dev`

![image](https://github.com/user-attachments/assets/fa250d16-6693-443b-982a-09f30fe44418)

**Comment by ellenupp** [comment]
@geospatialem I noticed that since the shell center row is bundled with the shell, this deprecation log shows up whenever using the shell even if not using the center row component. Can something be done about that?

**Comment by geospatialem** [comment]
> @geospatialem I noticed that since the shell center row is bundled with the shell, this deprecation log shows up whenever using the shell even if not using the center row component. Can something be done about that?

Great catch, @ellenupp! We've got a PR to address the above, and plan to address via a patch soon.
