### ISSUE TITLE
[Pagination] Remove gap at start and end of component.

### ISSUE THREAD

**Issue by aPreciado88** [Esri/calcite-design-system#10513]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As a result of adding a 2px gap to all of the component's elements in [#9991](https://github.com/Esri/calcite-design-system/issues/9991), there is now a 2px gap at the start and end of the component. This gap should be removed, to avoid spacing issues when left or right aligning the component.

Current behavior (space added at start and end of component):

![image](https://github.com/user-attachments/assets/3e871f34-205a-4be5-bb5a-6ba0bf9567c1)

Expected behavior (no spacing at start and end of component):

![image](https://github.com/user-attachments/assets/df4c4fbc-33bb-455f-becb-0b5e7433a886)

### Acceptance Criteria

Remove gap at start and end of component.

### Which Component

Pagination

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified on `2.14.0-next.13`
![image](https://github.com/user-attachments/assets/e561a90c-b4fe-4fd7-a118-34ed63660e5c)
