### ISSUE TITLE
[Alert] --calcite-alert-edge-distance regression 

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#10520]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `--calcite-alert-edge-distance` property has been made internal so users are no longer able to make adjustments as needed with this property. 

### Expected Behavior

- The property should be reverted back to being public so it can be accessed by users. 
- The properties name should also be changed to align with component token naming conventions.

### Reproduction Sample

https://codepen.io/Ditwan-Price/pen/yLmVRvY?editors=1000

### Reproduction Steps

1. Open codepen
2. Notice alert is positioned at the bottom of the page instead of `"20rem"` up from the bottom edge
3. Change calcite version on line 6 and 7 from `2.13.0` to `2.12.2` or lower and note the alert position changes

### Reproduction Version

2.13.0

### Regression?

2.12.2

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
“—calcite-alert-placement-offset”?

**Comment by alisonailea** [comment]
`alert.offset`

or more general

`floating-ui.offset`

"placemet-offset" seems long

@SkyeSeitz and @ashetland, any ideas?

**Comment by macandcheese** [comment]
`placement-offset` does tie directly to the `placement` property name. Alert also doesn't use floating ui - for components that do do, we have `offsetDistance` and `offsetSkidding` but these are attributes / properties, not css properties. Maybe `--calcite-alert-offset-distance` to match somewhat?

**Comment by alisonailea** [comment]
to align with existing schema this should be something like 
component = alert
element = offset
type = size

so `alert.offset.size` would match the current schema

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
