### ISSUE TITLE
Setting the "selected" prop on a CalciteDropdownItem doesn't work as expected

### ISSUE THREAD

**Issue by Aldemaros** [Esri/calcite-design-system#10601]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Hello! I'm using Calcite React within Esri's Experience Builder to create an UI. 

I need to set the "selected" prop on a **CalciteDropdownItem**  to either true or false (based on data that's coming from parent components through the props). 

However, when I do this all the items appear as selected, regardless if **selected** is set to true or false:
This is the code:
```
<CalciteDropdown width="m">
    <CalciteButton slot="trigger">Select landform</CalciteButton>
    <CalciteDropdownGroup group-title="Natural places">
        <CalciteDropdownItem selected={false}>Mountain</CalciteDropdownItem>
        <CalciteDropdownItem selected={false}>River</CalciteDropdownItem>
        <CalciteDropdownItem selected={true}>Waterfall</CalciteDropdownItem>
        <CalciteDropdownItem selected={true}>Rainforest</CalciteDropdownItem>
        <CalciteDropdownItem selected={false}>Tundra</CalciteDropdownItem>
        <CalciteDropdownItem selected={false}>Desert</CalciteDropdownItem>
    </CalciteDropdownGroup>
</CalciteDropdown>
```
When you open the drop-down, all 6 items are selected:

![image](https://github.com/user-attachments/assets/e76bc094-6bf9-4e69-a796-dd18e6f84601)

### Expected Behavior

Only the items with:
`selected={true}`
should be selected on the interface, the other ones shouldn't.

### Reproduction Sample

https://codepen.io/Aldemaro/pen/RwXjrRx?editors=1010

### Reproduction Steps

1. Open the codepen
2. Click on the drop-down

### Reproduction Version

2.13

### Relevant Info

Windows 10, MS Edge

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

This issue makes it hard to use the dropdown component when you are pre-setting the values based on your data

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by Aldemaros** [comment]
Just a note: the same happens with the **disabled** prop.

**Comment by geospatialem** [comment]
@Aldemaros There are some "gotchas" for React, where `true` and `undefined` (instead of `false`) must be used. Check out our [React Gotchas section](https://developers.arcgis.com/calcite-design-system/resources/frameworks/#gotchas) for more details on how to integrate with React.

**Comment by Aldemaros** [comment]
> @Aldemaros There are some "gotchas" for React, where `true` and `undefined` (instead of `false`) must be used. Check out our [React Gotchas section](https://developers.arcgis.com/calcite-design-system/resources/frameworks/#gotchas) for more details on how to integrate with React.

Oh..... that's very good to know, thank you very much for pointing it out!

**Comment by geospatialem** [comment]
Of course! 🤜🏻🤛🏻

@Aldemaros Once you are able to confirm the above works, could you close out the issue? Otherwise if you continue to experience similar behavior, could you update the issue's context?
