### ISSUE TITLE
[text-area] Max length can't be safely removed

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#10619]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When removing the text-area `max-length` attribute, the component gets into a bad state where the text gets removed but the user will see a red border if they type in any characters.

This happens either when using `maxLength={undefined}` in Stencil or `textAreaElement.removeAttribute("max-length")`. It does not happen when explicitly setting `textAreaElement.maxLength = undefined`, however this causes typescript to complain.

### Expected Behavior

When `max-length` is removed, the component acts as if `max-length` was never set.

### Reproduction Sample

https://codepen.io/mpayson/pen/mdNpdaR

### Reproduction Steps

1. Open the sample
2. Click the button
3. Start typing in text, see a red border appears

### Reproduction Version

2.13.0

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Data Pipelines

**Comment by jcfranco** [comment]
This will likely get resolved by #10310.
