### ISSUE TITLE
Invalid JSDoc syntax used on component classes?

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10658]
### Description

In several components, Calcite component is decorated with not one, but several JSDoc blocks:

https://github.com/Esri/calcite-design-system/blob/b78626c17ee415b6cf95ac0db83bd08250b69f66/packages/calcite-components/src/components/button/button.tsx#L43-L47

Is this intentional, or a bug?

VSCode's on-hover tooltip appears to only parse the last JSDoc - the previous ones are disregarded. Same for Lumina.

### Which Component

Alert, Button, Link, Notice, Tab-Title

**Comment by jcfranco** [comment]
cc @geospatialem @DitwanP

**Comment by geospatialem** [comment]
Verified on the `dev` branch 🧹
