### ISSUE TITLE
Using `slot="content"` breaks calcite-dialog

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-design-system#10665]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

With `<div slot="content">`
![image](https://github.com/user-attachments/assets/b33f723e-e5af-46d3-a671-a71e5f6b29a5)

### Expected Behavior

With `<div>`
![image](https://github.com/user-attachments/assets/93202cc3-8543-46c0-a15b-d5fd8be00fd2)

### Reproduction Sample

https://codepen.io/miketschudi/pen/VwoxEWP

### Reproduction Steps

1. Go to Codepen and see not-very-nice dialog
2. Remove `slot="content"`, and dialog looks great

### Reproduction Version

2.13.2

### Relevant Info

Windows 11 Enterprise; Chrome 130.0.6723.92

### Priority impact

impact - p3 - not time sensitive

### Impact

No impact because I used the default slot instead. But wanted to let you know about doc.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Solutions

**Comment by macandcheese** [comment]
Related: https://github.com/Esri/calcite-design-system/issues/10323

**Comment by driskull** [comment]
Yeah, I don't think this is a bug. It could be improved with renaming the slot or improving documentation.

**Comment by geospatialem** [comment]
> Related: #10323

@MikeTschudi Thanks for reporting! Closing out the above in favor of the duplicate effort in #10323, which is targeted for the December milestone as part of `3.0.0`.
