### ISSUE TITLE
Focus moves to the time-picker popover when clicking input-time-picker's text input

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#10668]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Clicking or triple-clicking the input in `input-time-picker` automatically moves focus to the first field in the `time-picker` popover.

### Expected Behavior

The `time-picker` should never gain focus unless it is explicitly clicked or tabbed into.  Focus should stay in the input when it is clicked with the mouse.

### Reproduction Sample

https://codepen.io/eriklharper/pen/xxvjeze

### Reproduction Steps

1. Left-click with the mouse in the input
2. Result: focus moves to the hour field in the `time-picker` popover.

### Reproduction Version

next

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
