### ISSUE TITLE
calcite-dialog shows event `calciteDialogBeforeClose`, but code doesn't appear to support it

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-design-system#10667]
### Description

At 2.13.2, have to use undocumented `beforeClose()` as with calcite-modal.

### Which Component

calcite-dialog

**Comment by driskull** [comment]
@MikeTschudi this seems to be working here:

```js
 dialog.addEventListener("calciteDialogBeforeClose", console.log);
```

https://codepen.io/driskull/pen/YzmvWpa?editors=1000

Can you elaborate on the issue?

**Comment by MikeTschudi** [comment]
@driskull, I saw the problem in HTMLCalciteDialogElement, and so I didn't get as far as running it since my TypeScript wouldn't build:
![image](https://github.com/user-attachments/assets/88badff5-46b0-418f-a32a-cb5683807c3e)

**Comment by driskull** [comment]
@MikeTschudi yeah that code wouldn't work since its an event and not a property.

**Comment by MikeTschudi** [comment]
Whereas beforeClose is accepted because it's a property that acts like an event?
![image](https://github.com/user-attachments/assets/07d8209b-cd3b-4e07-8e8a-ab542ccfb6f8)

**Comment by driskull** [comment]
Correct.

- `beforeClose` is a property that accepts a function returning a promise.
- `calciteDialogBeforeClose` is an event.

**Comment by MikeTschudi** [comment]
Got it.  Let's close this issue.

**Comment by geospatialem** [comment]
Closing per the [discussion above](https://github.com/Esri/calcite-design-system/issues/10667#issuecomment-2452277490).
