### ISSUE TITLE
Update Angular examples to use components directly

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#10674]
### Description

After https://github.com/Esri/calcite-design-system/issues/10465 lands, the [Angular example](https://github.com/Esri/calcite-design-system/tree/dev/examples/components/angular) and [template](https://codesandbox.io/p/sandbox/little-fire-2hx4qh?file=%2Fpackage.json%3A26%2C13) need to be updated to consume components without the wrapper.

### Which Component

N/A

### Resources

https://angular.dev/errors/NG8001#debugging-the-error

**Comment by geospatialem** [comment]
Verified on the `dev` branch 🥇
