### ISSUE TITLE
Example for Core Concepts: Patterns 

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-design-system#10684]
### Description

The example for "Core Concepts: Patterns" doesn't look quite right. The submit button probably isn't intended to be that tall.

https://developers.arcgis.com/calcite-design-system/core-concepts/#patterns

MacOS/FireFox 132.0

### Which Component

Not a component.

### Resources

![image](https://github.com/user-attachments/assets/2ad28678-bdc7-4537-9608-2b484373f97b)

**Comment by geospatialem** [comment]
Installed to the documentation site's `next.sites`, which should go live in tomorrow's 11/6 release.

**Comment by geospatialem** [comment]
Verified on the [Core concepts page](https://developers.arcgis.com/calcite-design-system/core-concepts/#patterns) this morning. Thanks for reporting, @gpbmike! 🏆
