### ISSUE TITLE
[Tooltip] Safari: tooltip will reappear and block actions with the menu

### ISSUE THREAD

**Issue by doreenbrinkman** [Esri/calcite-design-system#10715]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The fix to #10416 is not working for Safari.
Follow instructions in issue linked and test in Safari browser (codepen below).  Working for Chrome and Firefox.

### Expected Behavior

Action is not blocked by tooltip

### Reproduction Sample

https://codepen.io/doreenbrinkman/pen/vYoQexP

### Reproduction Steps

1.  Click on save icon
2.  Move to action
3.  Action is blocked by tooltip

### Reproduction Version

2.13.2

### Relevant Info

Safari

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

Makes choosing the action more difficult

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Data Pipelines

**Comment by geospatialem** [comment]
Spike needed to determine any considerations and/or limitations to consider for support in the Safari browser.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
