### ISSUE TITLE
Sort Handle - update large scale size

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#10723]
### Description

When set to large scale, `calcite-sort-handle` should use a large scale Action. It is currently using small scale.

### Proposed Advantages

Large scale Action use 24px icons, which is the system norm.

### Which Component

Sort Handle

### Relevant Info

cc @aPreciado88 @driskull 

Related to issue #7100 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

**Comment by ashetland** [comment]
It looks like scale is being passed to `calcite-dropdown`, but not to `calcite-action`.

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.46` on Storybook with the `Scales` > `scales draggable` story 📖
