### ISSUE TITLE
`.json` file imports appearing in public typings

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#10803]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Generated types for Calcite components include imports to `.json` files:

```yaml
node_modules/@esri/calcite-components/dist/components/calcite-color-picker-hex-input/customElement.d.ts:7:39 - error TS2732: Cannot find module '../calcite-color-picker/assets/t9n/color-picker.t9n.en.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

7 import { default as T9nStrings } from '../calcite-color-picker/assets/t9n/color-picker.t9n.en.json';
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@esri/calcite-components/dist/components/calcite-date-picker-month-header/customElement.d.ts:3:39 - error TS2732: Cannot find module '../calcite-date-picker/assets/t9n/date-picker.t9n.en.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

3 import { default as T9nStrings } from '../calcite-date-picker/assets/t9n/date-picker.t9n.en.json';
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@esri/calcite-components/dist/components/calcite-date-picker-month/customElement.d.ts:6:39 - error TS2732: Cannot find module '../calcite-date-picker/assets/t9n/date-picker.t9n.en.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

6 import { default as T9nStrings } from '../calcite-date-picker/assets/t9n/date-picker.t9n.en.json';

node_modules/@esri/calcite-components/dist/components/calcite-input-date-picker/customElement.d.ts:11:47 - error TS2732: Cannot find module '../calcite-date-picker/assets/t9n/date-picker.t9n.en.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

11 import { default as DatePickerMessages } from '../calcite-date-picker/assets/t9n/date-picker.t9n.en.json';
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@esri/calcite-components/dist/components/calcite-input-time-picker/customElement.d.ts:10:47 - error TS2732: Cannot find module '../calcite-time-picker/assets/t9n/time-picker.t9n.en.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

10 import { default as TimePickerMessages } from '../calcite-time-picker/assets/t9n/time-picker.t9n.en.json';

```

Two issues with this:
- since assets are moved during build, the import path in the .d.ts file is not valid
- TypeScript by default does not resolve .json imports - TypeScript config needs to have `--resolveJsonModule` - we can't assume every consumer of a Lumina-authored library will have this TypeScript setting enabled.

Fortunately, these .d.ts imports are only present for the above 5 components - all other .d.ts files have messages type inlined.
The part that is special about these 5 components is that they consume the T9n type directly, rather than wrap it in `useT9n` call.

I opened an issue 2047 in AWC to provide a better long term solution for this, but for short term, we can just turn direct references to JSON types into indirect ones to make TypeScript inline the type in .json files

### Expected Behavior

There should not be .json imports in public .d.ts files as they are not supported by TypeScript unless `resolveJsonModule` option is enabled in the tsconfig of your consumer - can't assume that.

### Reproduction Sample

see steps

### Reproduction Steps

Run `grep '\.json' -r dist/components/` to see all .json imports in the build output directory

### Reproduction Version

3.0.0-next.16

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍡 Verified locally
