### ISSUE TITLE
[segmented-control] SegmentedControlChange event is emitted before change occurs

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10810]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The selectedItem is incorrect at the time the event is emitted

### Expected Behavior

The selectedItem is correct at the time the event is emitted

### Reproduction Sample

https://codepen.io/driskull/pen/oNKRYYb?editors=1000

### Reproduction Steps

1. open codepen
2. Select a new item 
3. view console
4. The selectedItem for the event is incorrect

### Reproduction Version

3.0.0-next.13

### Regression?

2.13.2

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified on the `dev` branch 👍🏻
