### ISSUE TITLE
Default transitions not wired properly

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#10837]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

https://github.com/Esri/calcite-design-system/pull/8797 unintentionally removed the transition duration on all default props.

### Expected Behavior

Default transitions should honor the `--calcite-duration-factor`.

### Reproduction Sample

https://codepen.io/jcfranco/pen/XWvvXEz?editors=100

### Reproduction Steps

Hover over the checkbox and notice the check border immediately change color.

### Reproduction Version

2.13.2

### Regression?

2.7.0

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
Verified locally on `dev`
