### ISSUE TITLE
[Input type="textarea"] Remove custom grab handle visual

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#10864]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

To better help implement tokens and update this deprecated "input type textarea" to match the newer Text Area, we should remove the custom "grab handle" and instead use the default browser handle.

### Acceptance Criteria

<img width="837" alt="Screenshot 2024-11-25 at 10 37 27 AM" src="https://github.com/user-attachments/assets/06e0c056-2d24-4239-bb88-7cb831ba0eb4">

### Which Component

Input type textarea

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
