### ISSUE TITLE
Research: Skeleton States

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-design-system#1088]
Add skeleton state mixin(s) for the appearance of loading UIs

Current design:

[Skeleton States Comp.zip](https://github.com/Esri/calcite-components/files/5343077/Skeleton.States.Comp.zip)

**Comment by macandcheese** [comment]
I think this is part of a larger discussion / implementation and we should use this as a research issue for the time being

**Comment by samanthahunter** [comment]
Info thus far from Hub team: 
The vast majority of skeleton screens implemented today act exclusively as splash screens. 
- we have implemented a shimmer effect on splash screen (SVG) using gradients in Hub ..
However, skeleton loaders were intended to progressively load content, replacing skeleton placeholder objects with content like real text and images as soon as they are available. (And the more I'm reading its not recommenced to use SVGs but pure css)..

Why to add? Skeletons enhance perceived performance (how fast something feels to a user). [Read More](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a) - Example of MS Teams using this method of replacing objects as you can see some content is loaded and some is not in [this video](https://esriis.sharepoint.com/:v:/s/ArcGISHub/EfeI_9hprcZNnLQ7HvTdOlcBqT1IpXC-1dMeg3U67CN_Lw?e=0vUFKK) (< Esri only link).

Hub dev recommended this article about how to [build skeleton screens with css custom properties](https://css-tricks.com/building-skeleton-screens-css-custom-properties/) - we have not yet tested this in Hub

**Comment by macandcheese** [comment]
Still valid.

**Comment by macandcheese** [comment]
Still valid, nice to have post 1.0 IMO

**Comment by ajturner** [comment]
Relevant ideas from @rweber-esri [about skeleton configuration in this issue](https://github.com/Esri/hub-components/issues/621)

**Comment by geospatialem** [comment]
closing in favor of https://github.com/Esri/calcite-design-system/issues/5162
