### ISSUE TITLE
Use localization patterns for trailing periods

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#10890]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Remaining effort from #7708 for hardcoded strings WRT **trailing periods** should be pulled into t9n bundles or use a formatting utility.

https://github.com/Esri/calcite-design-system/blob/fc2c720bc69db81075b7e021d69c4cb7e2c2b5a9/packages/calcite-components/src/components/stepper-item/stepper-item.tsx#L228

### Expected Behavior

_Coming soon_, ultimately avoid hardcoded strings

cc @jcfranco @annierm18

### Reproduction Sample

https://codepen.io/jcfranco/pen/RwEpwbL?editors=100

### Reproduction Steps

1. Open [codepen](https://codepen.io/jcfranco/pen/RwEpwbL?editors=100)
2. Look at console to see the hardcoded assistive text

_Note that the sample is specific to one component, the descriptive hardcoded values are depicted in the summary above._

### Reproduction Version

1.8.0

### Relevant Info

https://github.com/Esri/calcite-design-system/issues/7708

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
Specifically for Stepper Item - we may be able to re-design this to avoid this period altogether - AFAIK it is only stylistic - we can probably do a small adjustment and place the localized number in an avatar or other UI. cc @SkyeSeitz @ashetland

**Comment by jcfranco** [comment]
@macandcheese That would be great!

**Comment by macandcheese** [comment]
Can we get a new issue for the design change specifically?

**Comment by annierm18** [comment]
Response from the Translation team:

"Now we see how they structure it, it should be fine to hard code it. Please make sure to test Arabic and Hebrew closely to check the order is correct."

In summary, it is okay to hardcode the trailing period in this instance. This means the "." string does not need to be put in the translation bundles. Just make sure to test with RTL languages.

**Comment by jcfranco** [comment]
Based on ☝️, we can close this one. Thanks, @annierm18!
