### ISSUE TITLE
Updating the scale property on List doesn't update child elements

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#10932]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The List component doesn't updating child `list-item` or `list-item-group` components when its `scale` property is modified.

### Expected Behavior

Changes to the list's scale should propagate down to its children.

### Reproduction Sample

https://codepen.io/eriklharper/pen/OPLVYNo?editors=1011

### Reproduction Steps

1. Open Codepen
2. Change scales in the select dropdown to see that no visible change occurs.

### Reproduction Version

3.13.2

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

> @eriklharper I also noticed if you change the scale on the list it isn't updating the child items. There should be something in `willUpdate` to handle changes to `scale`. cc @jcfranco. Can we get an issue @geospatialem? We should get this fixed for beta testing.

Good call, this is something that should be supported.  I can get on that issue today, it should be just a matter of setting it up to watch the changes on `scale` in `willUpdate`.

_Originally posted by @eriklharper in https://github.com/Esri/calcite-design-system/issues/10853#issuecomment-2512279198_

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.42` 👍🏻
