### ISSUE TITLE
Assigning deprecated `half` value causes TypeScript errors

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#10934]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

https://github.com/Esri/calcite-design-system/pull/10786 should include `half` in the updated types. `Exclude` also needs to be corrected to be:

```ts
Extract<Width, "auto" | "full" | "half">;
```

instead of

```ts
Extract<"auto" | "full" | "half", Width>;
```

See https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union.

### Expected Behavior

Deprecated `half` is still valid in types.

### Reproduction Sample

https://stackblitz.com/edit/github-fxftrg?file=main.ts

### Reproduction Steps

Open the repro case and notice the TS error.

### Reproduction Version

3.0.0-next.40

### Regression?

2.13.2

### Priority impact

impact - p1 - need for current milestone

### Impact

This will cause TS errors for existing use of the deprecated value.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.46`
