### ISSUE TITLE
[List] Enhance displayMode documentation

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10947]
### Description

Can we add more doc for displayMode on list?

We should say when to use flat vs nested and that when nested is used all child nested lists should also have nested for consistency.

### Which Component

List

### Resources  
- [Teams discussion](https://teams.microsoft.com/l/message/19:meeting_ODIzNzI2NzMtZDM2Yi00ZWY0LWJjM2MtYTA4Yjg3Yjc2NmNk@thread.v2/1733184162133?context=%7B%22contextType%22%3A%22chat%22%7D)
- [Original PR](https://github.com/Esri/calcite-design-system/pull/10852)
- [Verified example with `displayMode="nested"`](https://codepen.io/geospatialem/pen/MYggPPV)

**Comment by DitwanP** [comment]
🍠 Verified
