### ISSUE TITLE
[List] padding corrections to new scales

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#10940]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

There are some padding discrepancies on medium and large scale when comparing to the [design spec](https://www.figma.com/design/91sfHrYNt0Il6B4pEZZ749/List-scales%2C-sorting%2C-groups%2C-and-interaction?node-id=982-37071&m=dev&focus-id=1066-43440).

**Medium scale:**

- When `drag-enabled` and `display-mode="nested"`, the `selection-container` only has right padding.

**Large scale:**

- The content-container has 20px of right padding
- The row-container has 20px of left padding

**All scales:**
- There is extra left padding on `drag-enabled display-mode="nested" selection-appearance="icon"`

### Expected Behavior

**Small scale:**

- [x] When `drag-enabled display-mode="nested" selection-appearance="icon"`, row-container `padding-inline-start` should be 0px

**Medium scale:**

- [x] When `drag-enabled` and `display-mode="nested"`, the `selection-container` has 4px padding-inline (space.xxs)
- [x] When `drag-enabled display-mode="nested" selection-appearance="icon"`, row-container `padding-inline-start` should be 4px

**Large scale:**

- [x] content-container `padding-inline-end` should be 16px (space.lg)
- [x] row-container `padding-inline-start` should be 16px (space.lg)
- [x] When `drag-enabled display-mode="nested" selection-appearance="icon"`, row-container `padding-inline-start` should be 4px

### Reproduction Sample

https://esri.github.io/calcite-design-system/?path=/story/components-list--scales

### Reproduction Steps

Inspect elements as noted above.

### Reproduction Version

v3.0.0-next.41

### Relevant Info

Follow up to PR #10853.
cc @eriklharper 

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on Storybook. 📚
