### ISSUE TITLE
calcite-input-time-zone need to remove `console.log`

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-design-system#10981]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `input-time-zone` component is generating console messages. Specifically see [here](https://github.com/Esri/calcite-design-system/blob/6716c546d77d25361c7a7c5566c86164eba4f9c0/packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx#L388-L404).

### Expected Behavior

See above

### Reproduction Sample

https://codepen.io/richiecarmichael/pen/yLdwdyZ?editors=1000

### Reproduction Steps

1. Open [this](https://codepen.io/richiecarmichael/pen/yLdwdyZ?editors=1000) codepen.

### Reproduction Version

Components 3.0.0-next.49

### Relevant Info

Edge on Windows 10.

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment]
Maybe we should have a lint warning for console logs in tsx files. I don't see any other console.log usage in tsx files elsewhere in the codebase.

**Comment by jcfranco** [comment]
@driskull Way ahead of ya! https://github.com/Esri/calcite-design-system/pull/11104

**Comment by jcfranco** [comment]
_he yelled confidently, 2 weeks later_ 😂

**Comment by DitwanP** [comment]
🍡 Verified on `3.0.0-next.78`
