### ISSUE TITLE
Extend `csstype` typings with custom css variables

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#11013]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

React, Lumina, Preact and other JSX libraries are using `csstype` library to provide typing for the `style={}` property.

The types are quite type-safe. However, as a side-effect they throw a type-error for usage of unknown properties, including CSS variables. Example: https://devtopia.esri.com/WebGIS/calcite-design-system/issues/172#issuecomment-5180412:

There are a number of things the consumer of Calcite's components can do to silence TypeScript (for example https://stackoverflow.com/questions/52005083/how-to-define-css-variables-in-style-attribute-in-react-and-typescript)

### Acceptance Criteria

However, it might be better long term for Calcite to extend the TypeScript interface provided by `csstype` - this way users of Calcite will get intellisence for CSS variables, and will avoid TypeScript errors.

Documentation on how to do that:
- https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors

### Which Component

all

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
@pragyamishra56 Thanks for your interest in this issue! We’ll be handling it as part of the upcoming 3.0 release. Regarding collaboration, we have a process in place, so I’d recommend checking out our [contributing guidelines](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md#i-want-to-contribute-what-should-i-work-on) for more details.

**Comment by jcfranco** [comment]
@maxpatiiuk Typing custom CSS props per component might be tricky since we have composite components with their respective custom CSS props in addition to global ones. Here are a few options I see:

1. Add a catch-all interface for all custom Calcite CSS props (like [this](https://github.com/Esri/calcite-design-system/blob/dev/packages/calcite-components/src/tests/commonTests/themed.ts#L202)) to mitigate migration issues related to stricter types via Lumina.
    **Pro**: simple, can be automated
    **Con**: will not catch invalid props (e.g., `--calcite-does-not-exist`)
2. Use an interface that includes all known custom CSS props (both public and internal)
    **Pro**: simple, can be automated
    **Con**: can lead to incorrect/confusing styling (e.g., accepting a custom prop that is not relevant)
3. Have each component's style object use a global style interface + component-scoped ones
    **Pro**: allowed props would be more accurate, might be able to automate
    **Con**: complex to set up and maintain, will not include subcomponent props
4. Have each component's style object use a global style interface + component-scoped ones including subcomponents
    **Pro**: would be correct
    **Con**: complex to set up and maintain

Maybe we can start with 1 and explore 4 via automation down the road? 

cc @benelan, @alisonailea @driskull, @macandcheese

**Comment by driskull** [comment]
> Maybe we can start with 1 and explore 4 via automation down the road?

I agree with that assessment. 👍

**Comment by macandcheese** [comment]
1 seems like a good bet.

**Comment by maxpatiiuk** [comment]
Since CSS variables cascade, and you can slot-in any calcite components inside some calcite components, "accepting a custom prop that is not relevant" is not a problem that can be solved.
For short term, option 1 is fine.

> Use an interface that includes all known custom CSS props (both public and internal)

Would it make sense to have separate interface for internal typings vs external typings? (inside calcite, internal css variables will be present in types, but externally they won't)

Also, do you already have a capability to create and maintain such interface? (eg is there a machine readable list of all css variables calcite components use?)

**Comment by jcfranco** [comment]
> Since CSS variables cascade, and you can slot-in any calcite components inside some calcite components, "accepting a custom prop that is not relevant" is not a problem that can be solved.

FWIW, I meant style's type displaying CSS props for unrelated components (e.g., IntelliSense showing CSS props of `calcite-panel` in `calcite-button`), but you do bring up a solid point about the cascade. 

Should Lumina allow any custom CSS property instead? Augmenting each component’s style object type might make DX more complex than necessary.

> Would it make sense to have separate interface for internal typings vs external typings? (inside calcite, internal css variables will be present in types, but externally they won't)

Possibly. This would align with internal props.

> Also, do you already have a capability to create and maintain such interface? (eg is there a machine readable list of all css variables calcite components use?)

We could use the `@prop` annotated custom CSS props to help with component ones and the design tokens output for the shared ones. We don't have all internal ones annotated, so we would have to do something about them.

**Comment by jcfranco** [comment]
Per our discussion, we'll proceed with step 1 for the time being. Thanks, y'all!

**Comment by DitwanP** [comment]
🍠 Verified locally
