### ISSUE TITLE
`input-time-zone` not rendering in Chrome

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#11047]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `<calcite-input-time-zone>` element no longer renders in Chrome.

### Expected Behavior

The `<calcite-input-time-zone>` element renders in Chrome.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-zone/

### Reproduction Steps

1. Visit the doc page and open the console to see several errors stemming from the `input-time-zone` component trying to render.

### Reproduction Version

2.13.2

### Relevant Info

macOS 15.1.1, Chrome 131. Firefox and Safari appear to be unaffected.

Stack traces:

```
RangeError: Invalid time zone specified: Factory
    at new DateTimeFormat (<anonymous>)
    at t._getFormatter (index.mjs:50:25)
    at t.isoToTimeZone (index.mjs:31:32)
    at index.mjs:35:30
    at Array.map (<anonymous>)
    at index.mjs:29:32
    at Array.map (<anonymous>)
    at i (index.mjs:26:26)
    at d (index.mjs:81:30)
    at B (utils.ts:156:24)
```

```
TypeError: Cannot read properties of undefined (reading 'map')
    at U.renderItems (input-time-zone.tsx:569:31)
    at U.render (input-time-zone.tsx:556:19)
    at Qe (index.js:1756:39)
    at Be (index.js:1708:5)
    at index.js:1686:38 <calcite-input-time-zone calcite-hydrated>​…​</calcite-input-time-zone>​
```

```
index.js:52 TypeError: Cannot set properties of undefined (setting 'open')
    at U.openChanged (input-time-zone.tsx:202:21)
    at U.componentDidLoad (input-time-zone.tsx:516:10)
```

### Regression?

2.12.2

### Priority impact

impact - p0 - emergency

### Impact

Our forms are unable to show time-zone offsets and end users are unable to enter time-zone data.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by nwhittaker** [comment]
Possibly due to a bug in Chrome. I updated to the latest Chrome patch release (`131.0.6778.140`) and am no longer seeing the issue.

**Comment by geospatialem** [comment]
> Possibly due to a bug in Chrome. I updated to the latest Chrome patch release (131.0.6778.140) and am no longer seeing the issue.

@nwhittaker Good catch, and yes this was a result of a Chrome bug. More context on the issue and Calcite's hotfix for the solution is mentioned in #10895 and the resolution earlier this week in [Franco's note here](https://github.com/Esri/calcite-design-system/issues/10895#issuecomment-2536853511). 🔨 🔧
