### ISSUE TITLE
t9n: update translation file names

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#11081]
### Description

Currently translation files follow `<componentName>.t9n.<lang>.json` format since Lumina Migration. As per https://devtopia.esri.com/WebGIS/arcgis-web-components/discussions/1522, to align t9n file naming convention between arcgis-web-components, Calcite and JS API, `messages.<lang>.json` naming convention is porposed.

### Proposed Advantages

- uniform naming pattern for translation files across AWC & Calcite
- supports use of Lumina useT9n controller

### Which Component

All components 

### Relevant Info

[AWC Issue](https://devtopia.esri.com/WebGIS/arcgis-web-components/discussions/1522)
[AWC PR ](https://devtopia.esri.com/WebGIS/arcgis-web-components/pull/1804)

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

**Comment by geospatialem** [comment]
Verified on the `dev` branch 🎉
