### ISSUE TITLE
Enhancement: Utility to select first focusable (tabbable) element within a component's shadow DOM

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#1292]
### Description

Enhancement: Utility to select first focusable (tabbable) element within a component's shadow DOM

### Acceptance Criteria 

A utility to find the first element to focus inside a component.

### Relevant Info 

Would help define the default experience for setFocus() on a component. Some components may not have anything inside to focus and focus on its container.

#### Which Component

All

#### Example Use Case

https://github.com/Esri/calcite-components/issues/1277

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/commit/fb241ce94cd7d1109d29830fee4ea7050a03307a when [`focusFirstTabbable`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/utils/dom.ts#L262) was introduced. Closing!
