### ISSUE TITLE
Bug: Dismissible "x" icon is too small in the panel component

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/calcite-design-system#1755]
### Summary
If you enable "dismissable" in the panel component an "x" icon is added to the panel header but the icon size by default is small. The x icon at this scale is noticeably smaller than the other icons in the header. 

### Reproduction Steps

Enable dismissible in the sample: 
https://esri.github.io/calcite-components/?path=/story/components-app-panel--basic

### Relevant Info 
In order to workaround this in the app I have to create my own calcite button or action and add it to the header and explicitly set the scale to m or l.  Then I have to handle closing the panel when the button is clicked.

**Comment by macandcheese** [comment]
Thoughts on this @asangma

**Comment by macandcheese** [comment]
Cc @ashetland @SkyeSeitz for a review, unless the slotted actions are using scale L actions, both the close button and the actions should render scale S icon, but I think that svg itself is just small. I know we were thinking of making some changes to close button on modal, panel, etc so this could be wrapped up in an audit / design pass too.

**Comment by ashetland** [comment]
> Cc @ashetland @SkyeSeitz for a review, unless the slotted actions are using scale L actions, both the close button and the actions should render scale S icon, but I think that svg itself is just small. I know we were thinking of making some changes to close button on modal, panel, etc so this could be wrapped up in an audit / design pass too.

Yeah I agree we could do a audit / design pass on this when we update close buttons across the board. I also agree the 16px svg of the `x` does feel a little small (there seems to be more margin around the `x` when compared to other icons). We'd have to wrap an icon update into the mix once we define the update.

**Comment by SkyeSeitz** [comment]
I agree the small close icon on the small `modal` does feel mismatched and could benefit from a scale increase. 
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/29716057/210874258-5409b34d-4aa2-403e-b11a-df958da11f73.png">

However, if we increase the size of the `x` icon, we will have to consider the impacts to other components consuming it such as `chip`: 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/29716057/210878384-b3fd9b34-4334-45f5-9070-e561d44145a9.png">

**Comment by ashetland** [comment]
The original issue was talking about Panel specifically. Interestingly, though, Modal has a scale prop and it is currently using matching `s`, `m`, and `l` icons. Since Panel has no scale prop, could we default to using a `m` scale x in the close button? 

I still think a full audit is likely necessary since we're going to look at close button across the system. Maybe will end up with a new `calcite-close-button` component?

**Comment by SkyeSeitz** [comment]
Yes, sorry forgot to address/include Panel 🙃. Thanks for catching that, @ashetland and I agree it does demonstrate the need for an audit.

**Comment by geospatialem** [comment]
Designers will work through an audit and follow-up. Milestone needs to be considered once design work is completed. cc @ashetland @SkyeSeitz

**Comment by macandcheese** [comment]
Propose closing this one, the scale of the icon should match as long as the icons slotted by a user are set:

cc @SkyeSeitz to confirm

<img width="585" alt="Screenshot 2023-10-19 at 10 57 22 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/e6435d0d-1f8b-43ae-847f-61c2b2e51afa">
