### ISSUE TITLE
New Component: input-color

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-design-system#1934]
To be added in the suite of inputs.

suggested name: `input-color`

- Can invoke color picker from swatch. (need ability to disable that functionality for use inside color picker)

design:
![image](https://user-images.githubusercontent.com/14083530/114058512-224e4c00-9859-11eb-92a1-cc07e18887db.png)

Figma link:
https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A9270

**Comment by macandcheese** [comment]
Can this support being used on it's own as a display swatch? It would also be nice if this could support displaying a set of values (ie for a gradient), and having that be a clickable entity w/out an entry field.

**Comment by bstifle** [comment]
yeah display would be dope. and gradient/ramps would be cool, somethin like this:

![image](https://user-images.githubusercontent.com/14083530/119204249-984df180-ba5a-11eb-8402-8fcf488d7b57.png)

**Comment by jgibson02** [comment]
This would be exactly what we're looking for to replace the custom color picker we built in ArcGIS Velocity

![image](https://user-images.githubusercontent.com/5069711/130142894-2a7cdbd5-24ce-423c-8676-bc044be93511.png)

**Comment by mjuniper** [comment]
We would love something like this too for use in [hub-metadata-editor-field](https://esri.github.io/hub-components/?path=/story/components-hubmetadataeditorfield--input).

**Comment by macandcheese** [comment]
Note for @ashetland we should re-evaluate these proposed designs for validity.

**Comment by yelenakreyndel** [comment]
Design work needs to be complete for May release for implementation to be complete in September. Assigning this to @mitc7862. Please update acceptance criteria if needed. If not needed, please confirm. Thanks!

**Comment by ashetland** [comment]
Related to this, there are updated designs for Color Picker that haven't yet been implemented.

**Comment by macandcheese** [comment]
> Related to this, there are updated designs for Color Picker that haven't yet been implemented.

Do we need a separate issue to track that (separate from opacity feature). Those updates would be separate from this task IMO.

**Comment by ashetland** [comment]
> > Related to this, there are updated designs for Color Picker that haven't yet been implemented.
> 
> Do we need a separate issue to track that (separate from opacity feature). Those updates would be separate from this task IMO.

Question for @jcfranco, I think. I believe the idea was to incorporate it into issue #749, but it might more sense to track it separately.

**Comment by geospatialem** [comment]
Duplicate issue, closing in favor of #1616.
