### ISSUE TITLE
New Component: FlowMenu and FlowMenuItem

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#2004]
### Description
Items used to indicate a list of drill-in items.
Currently, users can create this type of interaction using value-list, but there it's too easy for the UI to vary across different implementations.

This UX will likely be seen more broadly.

Also, usage of things like a single "FlowMenuItem" is already happening.

Maybe it's more generic e.g. "DrillinMenu" and "DrillinMenuItem" but you might already see on issue with that. Also, it should generally be used with Flow and FlowItem.

#### User Stories
Multi-level interfaces.

### Acceptance Criteria 
Support
* label
* description
* icon
* slot in start position (e.g. for small thumbs or whatever)

### Helpful Details
And example of this UX in Charts.
<img width="1595" alt="Screen Shot 2021-04-20 at 4 37 44 PM" src="https://user-images.githubusercontent.com/12503298/115476903-aa3c3a80-a1f7-11eb-8eec-f59cf95c48a9.png">

**Comment by bstifle** [comment]
@asangma agreed this is good, but can we make the > icons 16px?

**Comment by bstifle** [comment]
also, assuming these will be able to handle summary, and a support icon, and be able to flip sides from start-to-end?

**Comment by asangma** [comment]
@bstifle 

Thanks for helping clarify deets.

* summary: yes
* icon: yes (probably only on the start side)
  * maybe also include a slot on the start side to put whatever in there, e.g. a 48px thumb
* flip : no, but maybe there's a use case for this?

**Comment by bstifle** [comment]
perfperfperf

**Comment by asangma** [comment]
@driskull @macandcheese @jcfranco 
Should this be a wrapper for PickList and PickListItem?

**Comment by asangma** [comment]
This project might be dependent on #2117

**Comment by driskull** [comment]
Should this be more generic like `ListMenu` and `ListMenuItem`? Does it need to be tied to flow? I'm thinking it might have uses outside of the flow component.

**Comment by macandcheese** [comment]
> Should this be more generic like `ListMenu` and `ListMenuItem`? Does it need to be tied to flow? I'm thinking it might have uses outside of the flow component.

Agreed. This kind of pattern is commonly called a drillin or drilldown:

https://get.foundation/sites/docs/drilldown-menu.html

**Comment by asangma** [comment]
Related #2117

**Comment by asangma** [comment]
@driskull 
> Does it need to be tied to flow? 

It might be useful to have a basic FlowMenuItem wrapper around ListItem.
As we can see in the example above, we can quickly see inconsistencies in something as simple as the size of the chevron icon. Might also be useful to have a "flow" or "drill-in" event...?

**Comment by driskull** [comment]
@asangma what I mean is that it doesn't need to be called "calcite-flow-menu". It can be more generic like "calcite-drill-in"

**Comment by macandcheese** [comment]
> @asangma what I mean is that it doesn't need to be called "calcite-flow-menu". It can be more generic like "calcite-drill-in"

Yes... we should take every opportunity to use human-readable / standard UX nomenclature for our components. Someone new to the system will be looking for "drill-in" not "flow-menu-item".

**Comment by driskull** [comment]
Yeah, it's one of the issues I have with ValueList/PickList => they are not standard UI terms.

**Comment by julio8a** [comment]
> Yeah, it's one of the issues I have with ValueList/PickList => they are not standard UI terms.

Can we standardize these and make the names more approachable before 1.0?

Cc'ing @jcfranco

**Comment by jcfranco** [comment]
☝🏼  Yeah, we should definitely target component renames before 1.0.0 since they're trickier to maintain in a non-breaking fashion. 

Can we create an issue to collects all rename candidates and try to do them in a sprint before 1.0.0?

**Comment by julio8a** [comment]
Yes, @macandcheese and @bstifle can work on it. Bryan and Adam, please create an issue for this and work on new name proposals for components that need updating. 

Franco and I will triage for a sprint.

**Comment by driskull** [comment]
It would be nice to schedule this one for a milestone after the new list PR gets merged. cc @jcfranco @benelan

**Comment by macandcheese** [comment]
@jcfranco @asangma Can the flow / flow-item and existing UI like List solve for this? Doing some issue cleanup...

**Comment by driskull** [comment]
I think we should research what a11y role this should be. We might be able to use some components internally to set this one up. It looks like it would just be a menu or menubutton role.

I think this issue is valid and we should create a new component for this kind of menu.

**Comment by macandcheese** [comment]
Could look at leveraging the in progress "vertical" `nav-menu` and `nav-menu-item` components. The "hamburger menu" use case is intended to be constructed using a `flow` / `flow-item` inside a `sheet`: 
![Screen Shot 2023-03-13 at 11 32 07 AM](https://user-images.githubusercontent.com/4733155/224796839-8fdb6149-4cc3-43b9-92cd-cc950da7a541.png)

**Comment by driskull** [comment]
yeah I think that would be a good part to reuse here.

**Comment by driskull** [comment]
@macandcheese is there a newer issue for this one? The JSAPI has a need for a component like this.

If not, can we get this into a milestone? cc @geospatialem

**Comment by macandcheese** [comment]
I really think we can use the upcoming `Menu / Menu Item` from the Nav initiative (screenshot above). I think we're considering calling them more general "Menu / Menu Item" and not "Nav Menu / Nav Menu Item".

Were you thinking the wrapping "Flow Menu" would handle the logic? Otherwise it could be nice to just say use a Menu here, which is what we'll tell folks to do when they create vertical Navigation in this way.

**Comment by driskull** [comment]
Yeah menu makes sense. Is there an issue we can link to and close this one?

**Comment by macandcheese** [comment]
@asangma @driskull any issue closing this with the availability of Menu? List can also work for more complex situations if certain slotted content is needed. 

https://codepen.io/mac_and_cheese/pen/LYqPaXP?editors=100

**Comment by macandcheese** [comment]
I'm going to close this as the above components seem to fit the bill. Feel free to re-open if still needed.
