### ISSUE TITLE
Bug: Pagination - setting `pageSize` to 0 logs console error

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#2093]
### Actual Behavior

Setting "pageSize" to 0 will crash the Storybook and cause the page to be killed (at least in Chrome)

### Relevant Info

https://codepen.io/mac_and_cheese/pen/eYLLbbN?editors=1000

Chrome Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by jcfranco** [comment]
I originally thought this was a storybook configuration issue (similar to https://github.com/Esri/calcite-components/issues/1127), but it looks like the problem is at the root of the component. I think we should update `pagination` to prevent `num` (number of items per page) being less than 1. @anveshmekala @macandcheese @driskull WDYT?

**Comment by jcfranco** [comment]
Repro case: https://codepen.io/jcfranco/pen/dyJRrgB?editors=1000

**Comment by anveshmekala** [comment]
Yup agreed. It is better to make sure `num` prop value is always greater than 1. Does this mean we mask the text to be one even if the user type in zero ?

**Comment by macandcheese** [comment]
> I think we should update `pagination` to prevent `num` (number of items per page) being less than 1.

Agreed. I think it’s named to correlate to a specific ArcGIS data structure but ‘num’ as a prop name is a little confusing here - we don’t use shorthand names like that anywhere else

**Comment by macandcheese** [comment]
In the component's latest state, the page doesn't crash, but the component does throw a console error : https://codepen.io/mac_and_cheese/pen/eYLLbbN?editors=1000

**Comment by geospatialem** [comment]
Verified the component's `pageSize` is set to `1` if a user or change tries to modify the property to `0` (or less). ✨
