### ISSUE TITLE
Enhancement: stepper item events

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-design-system#2094]
## Description
The `calcite-stepper-item` component does not emit any events on click or keypress. Our implementations of the stepper component in ArcGIS Monitor require us to watch for when a stepper item becomes active inorder to determine which step to render within the form adjacent to the stepper component. 

#### Acceptance Criteria 
Add an event to `calcite-stepper-item` that triggers on click, enter keypress and spacebar keypress 
ex. `onCalciteStepperItemActive`

#### Which Component
calcite-stepper-item

## Example Use Case

<img width="1092" alt="Screen Shot 2021-05-04 at 1 18 06 PM" src="https://user-images.githubusercontent.com/55154968/117057878-3318a300-acdb-11eb-851e-688bd8f0ceb9.png">

<img width="1091" alt="Screen Shot 2021-05-04 at 1 16 47 PM" src="https://user-images.githubusercontent.com/55154968/117057703-02d10480-acdb-11eb-9465-8a0b60a53903.png">

**Comment by nwhittaker** [comment]
Ran into a scenario where this event would've been helpful. For example, if the user should visit each step in order, but can revisit a past step at anytime, the program can lose track of which is the active step when the user clicks a previous stepper title.

**Comment by geospatialem** [comment]
Emit on stepper/stepper-item change, rather than on click/hover.

**Comment by jcfranco** [comment]
@joeyHarig @nwhittaker I believe https://github.com/Esri/calcite-design-system/pull/9351 would take care of this. Can you confirm?

**Comment by nwhittaker** [comment]
>I believe https://github.com/Esri/calcite-design-system/pull/9351 would take care of this. Can you confirm?

Yes, I believe so, if it also emits when the user clicks on the stepper's heading.

**Comment by jcfranco** [comment]
Awesome. Thanks for confirming!

**Comment by geospatialem** [comment]
Verified in `2.9.0-next.22` with https://codepen.io/geospatialem/pen/YzbWgQV.

Includes two new events:
* `stepper`: `calciteStepperChange`
* `stepper-item`: `calciteStepperItemSelect`
