### ISSUE TITLE
Enhancement: calcite-tile - can't set focus on component

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#2141]
### Actual Behavior

As a keyboard user when tabbing through the UI it jumps over the `calcite-tile` component. It has an `onClick` action and I can't access it via keyboard navigation.

Focus jumps from the block header (Information) directly to the link (Manage layer properties).

![image](https://user-images.githubusercontent.com/44481292/118169901-52e84f00-b3de-11eb-848c-2f45616d7b0a.png)

### Expected Behavior

I expect a focus box around the tile so I can hit enter to execute the onClick action.

**Comment by macandcheese** [comment]
I’m not sure having a calcite notice be a wholly clickable entity is intended. It can contain a slotted link, or the optional close button can be focused.

Thoughts here @bstifle ?

**Comment by AdelheidF** [comment]
> I’m not sure having a calcite notice be a wholly clickable entity is intended. It can contain a slotted link, or the optional close button can be focused.

Ideally we'd like to have the close button be replaceable with another action, e.g. the info icon. If the focus goes there, then that's fine.

**Comment by macandcheese** [comment]
Makes sense - there was a similar request for alert - attached a related comment to above issue - maybe that one is sufficient and this one can close?

**Comment by AdelheidF** [comment]
> and this one can close?

Still valid for calcite-tile, I updated the description

**Comment by jcfranco** [comment]
@macandcheese Can you confirm if the tile should always be focusable, regardless of whether it has a link or not? Or is this specifically for the 'has link' case?

**Comment by macandcheese** [comment]
I don’t think it should be focusable without a link - there’s no possible interaction there AFAIK.

**Comment by AdelheidF** [comment]
What if we want the entire tile clickable

![image](https://user-images.githubusercontent.com/44481292/119750690-af238800-be4e-11eb-8146-7971adf8c6c5.png)

**Comment by bstifle** [comment]
that is currently possible! @AdelheidF

**Comment by AdelheidF** [comment]
> I don’t think it should be focusable without a link...
> What if we wanted the entire tile clickable...
> that is currently possible!

yes, but I can't set the focus on the tile. The focus jumps over the tile when using keyboard navigation. As a keyboard user I could never execute the click event on the tile because the tile never get the focus.

<img src=https://user-images.githubusercontent.com/44481292/119769477-5ca69380-be6f-11eb-988c-5e32379af9ad.png width=250/>

**Comment by macandcheese** [comment]
I think the ask here is for a `setFocus()` method on `calcite-tile` @jcfranco @AdelheidF  ?

**Comment by AdelheidF** [comment]
> I think the ask here is for a setFocus() method on calcite-tile

I don't necessarily need to call `setFocus()`, but I want to be able to tab to a calcite-tile and hit enter/space to execute a click handler. Some keyboard users might want to tab to it to call the href.

Here is a sample. The first 2 tiles have an onclick and the bottom 2 tiles have an href. after the page loads the first button has the focus, then start tabbing. You can see it jumps right over the 2 tiles with the onclick (this is what I need). I also noticed that a tab leaves the page completely with the href (I don't need this, but just telling you).
https://codepen.io/afreitag/pen/NWvMmee?editors=1000

**Comment by AdelheidF** [comment]
Closing this as I can use the added `content-start` and `content-end` slots with actions, so the focus goes there.

**Comment by jcfranco** [comment]
Reopening. Discussed with the team and we will be enhancing tile with a button mode to support the original use case of having an entire tile be clickable.

**Comment by ashetland** [comment]
@SkyeSeitz see @jcfranco's [comment](https://github.com/Esri/calcite-components/issues/2141#issuecomment-972325012) about a button mode for Tile.

**Comment by SkyeSeitz** [comment]
This enhancement for dev to add a button mode to non-selectable Tiles in the Tile Redesign Epic is noted in the [Figma specs](https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A3032&mode=dev).

**Comment by eriklharper** [comment]
This will be resolved as part of #6662

**Comment by geospatialem** [comment]
Closing per Erik's comment above in https://github.com/Esri/calcite-design-system/issues/2141#issuecomment-2018958031
