### ISSUE TITLE
Tailwind: consume npm package for Tailwind config (post v1 release)

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-design-system#2143]
### Description
Calcite-components currently includes its own Tailwind config. Eventually this config should move to our other project (for use in other applications). Then, calcite-components can install the Tailwind configuration via the npm package instead.

### Acceptance Criteria 
calcite-components gets its Tailwind configuration from the npm package instead.

### Relevant Info 
#1500

**Comment by driskull** [comment]
@benelan @jcfranco I think we can start on this one too. Bringing tailwind config into its own repo.

**Comment by samMatenaer** [comment]
as a user of calcite and tailwind, it'd be great to be able to extend from the calcite tailwind config. at the moment, i copy the tailwind config from this repo and use it in my projects.

**Comment by geospatialem** [comment]
Adding the `design tokens` label for consideration as part of this effort.

**Comment by geospatialem** [comment]
We'll proceed with #6602 to publish Tailwind Config as a preset later in 2024. Closing the above in favor of 6602.
