### ISSUE TITLE
Enhancement: Refactor BlockSection design and spacing

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#2232]
### Description
Refactor BlockSection to use Label.

### Acceptance Criteria 
Don't break stuff.

### Relevant Info 
Current implementation allows switch and text to be misaligned.
![image](https://user-images.githubusercontent.com/12503298/120004292-6d4c2c00-bf8b-11eb-9d26-09dc73e89c13.png)

#### Which Component
BlockSection

#### Example Use Case
All of them.

**Comment by jcfranco** [comment]
@asangma Do you have cycles to work on this for the next sprint? Otherwise, I can label this as 'help wanted'.

**Comment by jcfranco** [comment]
The original misalignment is no longer present in the latest release (see https://codepen.io/jcfranco/pen/jOXreMj?editors=1100).

![Screenshot 2023-09-01 at 11 18 30 AM](https://github.com/Esri/calcite-design-system/assets/197440/9b091f17-5c09-4057-be40-28ad165242c5)

Closing based on the above.
