### ISSUE TITLE
New Component: Meter

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#2249]
### Description
A consistently formatted and styled meter component that leverages the native meter element.

#### User Stories
Consistently display data limits, quotas, disc space, etc. 

Can also be useful for item completeness, profile "filled out" progression messaging, etc.

### Helpful Details
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

Adobe Spectrum's implementation: https://spectrum.adobe.com/page/meter/#Anatomy

They don't seem to leverage the native "levels" that are associated with color, but they DO have consistently placed and formatted descriptive and value text areas.

- Ensure it works both with / without the "step" attributes (always one color OR stepped color based on those "steps")

Online "item completeness": 
![Screen Shot 2021-06-07 at 9 49 17 AM](https://user-images.githubusercontent.com/4733155/121059584-7badfb00-c776-11eb-8b53-3d89c3566095.png)

Enterprise Manager :
![Bitmap](https://user-images.githubusercontent.com/4733155/121067383-d6982000-c77f-11eb-8209-ef860a5202b6.png)

**Comment by bstifle** [comment]
gonna jump on this design this week

**Comment by paulcpederson** [comment]
Here's a couple other versions of this UI from Online:  

<img width="368" alt="Screen Shot 2021-06-07 at 10 48 25 AM" src="https://user-images.githubusercontent.com/1031758/121065743-f595b280-c77d-11eb-807b-272774bf2457.png">

<img width="502" alt="Screen Shot 2021-06-07 at 10 48 09 AM" src="https://user-images.githubusercontent.com/1031758/121065772-faf2fd00-c77d-11eb-9407-18a6c68947ba.png">

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/121101447-788c2c80-c7c1-11eb-8038-616e6256122e.png)
![image](https://user-images.githubusercontent.com/14083530/121101458-7f1aa400-c7c1-11eb-8d51-41d073836219.png)
![image](https://user-images.githubusercontent.com/14083530/121101487-8b066600-c7c1-11eb-84a7-4ab3a80886e4.png)

Initial designs. any thoughts/additions/concerns lemme know!

**Comment by bstifle** [comment]
Leaving discussion open for this until next Wednesday 6/16

**Comment by bstifle** [comment]
Alrighty! Moving this one over to developer hands

**Comment by driskull** [comment]
@jcfranco @julio8a  I think new components need to go through an API design process before being implemented.

Just looking at the designs, it's not super clear on how the API for this component should be implemented.

The native HTML meter element has the following attributes: min, max, low, high, optimum, value.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter#attributes

It seems like this component:

- Has a `label` that is optional but always on top. Would we be better off using a calcite-label to wrap this instead?
- Has a  `value`, `min`, `max`, `remainder`, `remainderLabel`?, `valueLabel`? , `maxLabel`? The labels go after the value but sometimes are shown in place of the value altogether?
- Seems to be some way to position the meter above, below, or in-between the labels/values?
- `low`, `high`, `optimum` values are optional and render red/yellow/green.
- Seems like the color of the meter can be altered as well? Does this need a prop? or would this be a CSS var?
- Seems like there's some way to alter the appearance to be unfilled?

I think for new components we should maybe have a meeting to go over these requirements first. Its kinda tricky to decipher how the component should behave.

I'm not sure this is an issue someone can just grab and implement.

**Comment by jcfranco** [comment]
@driskull I was thinking the API would come from the implementation phase, but we could tweak this of course. 

Looking closer at the existing summary and your comment, I agree with you that this needs more detail. Along with the design mockups, we should make sure the summary lists the requirements on what this component should do. For example,

```
The meter should: 
  * support the following display modes [...deets].
  * not be focusable.
  * not be interactive.
  * ...
```

Having this would help with the API design, testing and even planning if the scope is too big. We can even work on a requirements starter template to guide this part of the process.

@julio8a WDYT? Can we beef up the requirements before tackling this one in this sprint?

**Comment by driskull** [comment]
Sounds good @jcfranco. More documented requirements along with the designs should be enough if they are thorough.

**Comment by bstifle** [comment]
@jcfranco i can provide more details for this

**Comment by juliepowell** [comment]
This is a good candidate for Calcite - consistent design to be used across ArcGIS. Should it be ported from ArcGIS App Components?

**Comment by yelenakreyndel** [comment]
A design task to create a component is assigned to @macandcheese using this issue. Design work needs to be complete for May release for us to implement this component in September. I recommend renaming this component to Progress Indicator or Progress to align with industry standard. @macandcheese, I left some comments for you in the description. 
Cc'ing @jcfranco @geospatialem

**Comment by macandcheese** [comment]
>  I recommend renaming this component to Progress Indicator or Progress to align with industry standard.

Some questions to clarify here... 

We already have a [progress component](https://developers.arcgis.com/calcite-design-system/components/progress/) that replicates the native [progress element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress). This issue is to add a new meter component to replicate the native [meter element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter). The two native elements have different use cases and configuration options. Additionally the existing arcGIS component is `arcgis-meter`.

Adobe's Spectrum has a nice succinct use case distinction between their versions: https://spectrum.adobe.com/page/meter/#Progress-bar-or-meter?

**Comment by macandcheese** [comment]
> Adam, please let us know what design work is needed and how would it be different from what Bryan already provided. 
I'll be sending out a survey post dev-summit. The way our labels work has changed since this initial design work so will update that and reconcile any other changes in requirements that surface from survey. But I imagine it won't be drastically different in appearance. 

> Adam, will this work be designed in Figma or prototyped or both?
Likely both, the API for this should follow the [native meter element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter#attributes) closely. cc @jcfranco

**Comment by geospatialem** [comment]
Updating design work to the June milestone.

**Comment by geospatialem** [comment]
Verified on the `main` branch with the following properties:
- `appearance`
- `fillType`
- `groupSeparator`
- `high`
- `label`
- `labelType`
- `low`
- `max`
- `messageOverrides`
- `min`
- `numberingSystem`
- `rangeLabels`
- `scale`
- `unitLabel`
- `value`
- `valueLabel`

cc @ashetland @SkyeSeitz for Figma UI kit additions.
