### ISSUE TITLE
Tooling: global test utility for focused components when disabled/loading

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#2532]
## Summary 

I've noticed a few "control" components that when disabled, they can still be focusable. For example, you can still tab to a disabled calcite-input element and hit enter on it. 

https://github.com/Esri/calcite-components/issues/2378#issuecomment-876809215

## Measure of Success 

We should setup a global test to test any component that has a disabled or loading property to make sure that it cannot be tabbed to nor any of its child elements can be tabbed into.

If we want to take this one step further, we could make sure that when the components is not disabled or loading, only 1 element within the component is focusable at a time. That might be out of scope for this test though.

### Resources 

https://github.com/Esri/calcite-components/issues/2378

**Comment by jcfranco** [comment]
The `disabled` test helper already [covers tabbing when disabled](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/tests/commonTests.ts#L1100). Currently, `loading` doesn't set `disabled`, so we can't reliably test for this yet.

**Comment by jcfranco** [comment]
> Currently, loading doesn't set disabled, so we can't reliably test for this yet.

We decided to separate `loading` and `disabled` at 2.0.0 (see https://github.com/Esri/calcite-design-system/pull/8292), so this no longer holds. 

Closing since the `disabled` test helper covers focusing via keyboard and mouse when disabled.
