### ISSUE TITLE
Enhancement: CalciteListItem add styles for slotted CalciteHandle

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#2767]
### Description
ListItem has styles for Action and Icon.
It should have similar styles for Handle.

### Acceptance Criteria 
Match UI.

#### Which Component
CalciteListItem

#### Example Use Case
When ListItems are in SortableList and using Handle for the handle.

**Comment by benelan** [comment]
@asangma Is this still valid?

**Comment by benelan** [comment]
@asangma can you elaborate on what styles you want to provide for Handle?

**Comment by macandcheese** [comment]
Propose to close this as List now has drag built in cc @asangma

**Comment by geospatialem** [comment]
Closing per the above comments.
