### ISSUE TITLE
Enhancement: Add "hint-text" to calcite-label

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-design-system#2793]
### Description
Add `hint-text` property to `calcite-label`

### Acceptance Criteria 
need text separate from calcite-message and calcite label to solve for static support text

### Relevant Info 
Could be neat to use for character count requirements

#### Which Component
`calcite-label`

#### Example Use Case
![Hint stuff](https://user-images.githubusercontent.com/14083530/129118796-11a631b1-5772-4357-b30e-074a1ad9c054.png)

**Comment by macandcheese** [comment]
Can we at least style plain text in that named slot? If it’s not a prop, consistency of visual style goes out the window, which we have begun to lose sight of while making many of these props just open slots. 

Right now calcite label is just one big slot anyway for the most part… so folks can already put non-styled / non-text content and position and style themselves.

**Comment by julio8a** [comment]
This still needs more design for different layouts on input, i.e. inline.

**Comment by geospatialem** [comment]
Adding the slot will require a major refactor, and will be prioritized after next month's release. cc: @ashetland, @Elijbet

Once prioritized the effort should be coupled with #4155 and #5079.

**Comment by geospatialem** [comment]
Follow-up includes:
- Gathering use case feedback from teams, and
- Determine requirements of #6743 for inclusion/next steps on the above.

**Comment by ashetland** [comment]
Closing in favor of #5079 for inline slot.
