### ISSUE TITLE
Research: Look into markdown linting

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#2861]
### Background

At the moment we run prettier on markdown files but there is not any linting. Having some automatic checks for the documentation would make life a lot easier as the product grows. I found a couple options:

[eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown) - This one would be the easiest to integrate and is what I would look at first. It lints code blocks inside of markdown files and would be great for consistent usage examples. It says "Lint JS, JSX, TypeScript, and more inside Markdown." So I would test to see if the 'and more' includes linting html and custom elements.

[markdownlint](https://github.com/DavidAnson/markdownlint) - This one lints the whole markdown file rather than the just the code blocks. However it isn't an eslint plugin. I wouldn't spend any time on this one for now but I just wanted to throw it out there as an option.

I'd love to hear opinions from the team about whether this is worth looking into.
@jcfranco @julio8a @driskull @caripizza @macandcheese 

### Desired Outcome 
- Find out if there are any markdown linting options that work for our use case

**Comment by driskull** [comment]
Would we want to exclude automatically generated doc markdown files like the component readme's

**Comment by benelan** [comment]
@driskull Yeah that would make sense. For the eslint plugin just focusing on the markdown files in the usage directory for each component would be enough.

**Comment by benelan** [comment]
### Findings
[eslint-plugin-markdown]( https://github.com/eslint/eslint-plugin-markdown) works by identifying fenced code blocks inside markdown files and linting them with the plugins/rules used in the repo. Therefore the html fenced code blocks in the usage examples will not be linted unless we adding a plugin or rules for html. It is possible to only lint the usage markdown files and you can define rules for specific types of fenced code blocks, as described [here](https://github.com/eslint/eslint-plugin-markdown#advanced-configuration).
```js
"overrides": [
    {
      // 2. Enable the Markdown processor for all .md usage files.
      "files": ["./src/components/*/usage/*.md"],
      "processor": "markdown/markdown"
    },
    {
      // 1. Target ```html code blocks in .md files.
      "files": ["./src/components/*/usage/*.md/*.html"],
      "rules": {
       // ...
      }
    }
  ],
```

### Next steps
- Setting this aside for now since it is not an easy implementation
- Later, probably after v1, I'll look into eslint plugins for html
- I would only use the html plugin on the fenced code blocks in the usage markdown files

**Comment by jcfranco** [comment]
Addressed by https://github.com/Esri/calcite-design-system/pull/6355. Closing!

**Comment by jcfranco** [comment]
@benelan Got a little trigger-happy there. 😅 LMK if we need to create a follow-up issue for the next steps mentioned above.
