### ISSUE TITLE
Enhancement: improve `form` stories for Screener visual regression tracking + docs 

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-design-system#2969]
### Description
Add stories for Screener which articulate form configurations we support.

These stories should include `calcite-label` wrapping any relevant form control components, in each of its `layouts`. (I'm not sure where they should live, maybe just under the existing "Label > Wrapping components other than Input" stories?)

### Acceptance Criteria 
New stories are added to Storybook which show calcite-label wrapping relevant form control components in each of its layouts.

### Relevant Info 
Goals:
- a) establish baseline for UI regressions with wrapping calcite-label layouts and its nested controls
- b) document how our form related controls/components can be used with a native `form` element

#### Which Component
Form controls + calcite-label

#### Example Use Case
We can even model the stories after the form demo from Matt/Franco's DevSummit video:
https://codepen.io/driskull/pen/gOgPvaN

**Comment by caripizza** [comment]
@jcfranco this is the issue you asked me to ping you about from this week's core team meeting wiki agenda. I believe it started from @driskull's "Should we support native form elements inside calcite-label?" topic. Please re-word/edit as needed.

**Comment by jcfranco** [comment]
Closing as our `formAssociated` helper covers all supported use cases, stories are exclusively used for screenshot tests and `calcite-label` does not support native form elements.
