### ISSUE TITLE
Tooling: Ensure demo pages are axe-compliant

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#3063]
## Summary 

Running axe on the demo pages will help catch invalid use cases that may be referenced as samples. For example, [this label example](https://github.com/Esri/calcite-components/blob/de25ec6/src/demos/calcite-label.html#L200-L252) is not valid as nested label elements are not supported per https://www.w3.org/TR/2013/CR-html5-20130806/forms.html#the-label-element.

As a first step, the [`head`](https://github.com/Esri/calcite-components/blob/master/src/demos/_assets/head.ts) script for demo pages can be updated to inject `axe-core` and have it run on initial load or similar and report its findings on the console. 

## Measure of Success 

[`aXe`](https://www.npmjs.com/package/axe-core) runs at demo-page runtime and reports violations in a `calcite-modal` or `calcite-notice`.

**Comment by geospatialem** [comment]
Will continue to work on efforts with Storybook/stories and axe e2e testing.
