### ISSUE TITLE
Bug: onCalciteListItemChange fires without user interaction

### ISSUE THREAD

**Issue by apfister** [Esri/calcite-design-system#3191]
### Actual Behavior
Setting the `selected` property of a `CalcitePickListItem` programmatically will cause the `onCalciteListItemChange` event to fire. 

### Expected Behavior
The `onCalciteListItemChange` should not fire as there was no user interaction.

### Reproduction Steps and Sample
Steps to reproduce are in the codesandbox

https://codesandbox.io/s/nostalgic-roman-vl78n?file=/src/App.js 

### Relevant Info
Using calcite-components-react
_Version_: `@esri/calcite-components-react@0.7.0`

**Comment by jcfranco** [comment]
Closing since there is a workaround and `pick-list` is deprecated. It is recommended to use `list` instead (where events will emit as expected).
