### ISSUE TITLE
Add Chromatic Test for text wrap  for block

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#3280]
### Description
Add a screener test to verify text wrap in `calcite-block-section`  
### Acceptance Criteria 
Parse a  long string or URL in the `calcite-block-section` and verfiy if the content is wrapped when the width of the `calcite-`block is set to `400px`
### Relevant Info 
Refer to issue #3069 
#### Which Component
`calcite-block-section`

**Comment by jcfranco** [comment]
@anveshmekala Can you double check this is still needed? If not, we can close this.

**Comment by geospatialem** [comment]
Verified on `main` branch
