### ISSUE TITLE
Enhancement: Input type="textarea" prevent resize and set width/height of component

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-design-system#3312]
### Description
This enhancement request is for the component `Input` of type="textarea". There are cases when it is desired to prevent the textarea element from being resized and to set a specified height and/or width of the element. This enhancement request is to add those capabilities to the `input` component or to provide additional context for an individual component.

### Acceptance Criteria 
- [ ] prop for a set height of the textarea element
- [ ] prop for a set width of the textarea element
- [ ] prop to prevent/allow resizing of the textarea element

### Relevant Info 
- [HTML <textarea> Docs](https://www.w3schools.com/tags/tag_textarea.asp)
- [CSS Resize prop](https://www.w3schools.com/cssref/css3_pr_resize.asp)

#### Which Component
Input

#### Example Use Case
_see above_

**Comment by macandcheese** [comment]
Related:
https://github.com/Esri/calcite-components/issues/2866
https://github.com/Esri/calcite-components/issues/863

**Comment by jmanke** [comment]
We also have a need to customize resize on the `textarea`. In our case, we require `resize: vertical`.

**Comment by BennyBaruba** [comment]
In the ArcGIS Mission app, we need to set the initial Text Area size to 100px to visually accommodate a max limit of 400 characters.  Without requiring the users to scroll.  We had a workaround to set this.  However the moving of the Text Area input to the shadow root in a recent version of Calcite Components, broke the code we were using to do this.  Thanks for looking into this.

**Comment by macandcheese** [comment]
A native `textarea` has `row` and `col` attributes - When we break this out to its own computer I wonder if we can use these and then provide a css variable to pass `resize: none` to the shadowed `textarea`

**Comment by yelenakreyndel** [comment]
@ashetland

**Comment by geospatialem** [comment]
This issue is blocked awaiting creation of https://github.com/Esri/calcite-components/issues/863, which was included in the design phase of the new component, `calcite-textarea`. 

Prior to addressing this enhancement, the `textarea` component will be developed and implemented. cc @ashetland

**Comment by jcfranco** [comment]
Closing as [`calcite-text-area`](https://developers.arcgis.com/calcite-design-system/components/text-area/) supports this.
