### ISSUE TITLE
Enhancement: combobox invalid prop and status

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-design-system#3406]
### Description
Combobox should have an invalid state (add a status prop)
### Acceptance Criteria 
Combobox shows red border and can accept an input-message as well.
#### Which Component
`calcite-combobox`
#### Example Use Case
want to show that the combobox is a required field, so when someone clicks in and doesn't select something, set the status to invalid and display an error message (in the form of an `input-message`).

**Comment by macandcheese** [comment]
@sam11927 do you still have a need for this invalid state on Combobox? 

The `input-message` can be placed adjacent to the Combobox itself like this: https://codepen.io/mac_and_cheese/pen/bGxQEMv?editors=1000

**Comment by geospatialem** [comment]
Rescoped to fit the combobox's invalid status and include a prop.

**Comment by geospatialem** [comment]
Part of a larger validation epic effort slotted for late 2023.

**Comment by geospatialem** [comment]
Refer to the [Figma file](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=956-94284&mode=design&t=tPqHJcVdxmJmZ6L2-0) and image below:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/52eaf790-91bb-47e4-9bb1-9522c348c445)

**Comment by geospatialem** [comment]
Verified in `2.1.0` with https://codepen.io/geospatialem/pen/PoLYZoL with the `status`, `validationIcon`, and `validationMessage` props.
