### ISSUE TITLE
Enhancement: allow dragging start/end dates for Date Picker ranges

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#3428]
### Description
Add the ability drag the start/end dates to change the selected day when using the date picker.

### Acceptance Criteria 
Dragging changes the selected day

### Relevant Info 
From holistic feedback

#### Which Component
`calcite-date-picker`

**Comment by geospatialem** [comment]
@benelan Do we have additional insight into the holistic feedback for next steps?

**Comment by ashetland** [comment]
Do we have thoughts on closing this one or have we had any additional feedback?

**Comment by ashetland** [comment]
Closing as not planned, but could be revisited at a later date if needed.
