### ISSUE TITLE
calcite-tile with content slot

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#3462]
### Description

A place where we can e.g. insert a chip.

![image](https://user-images.githubusercontent.com/44481292/140971662-38431ba1-00f7-419b-9009-577382020e1c.png)

### Acceptance Criteria 

- [x] Deprecate “content-start” slot

<img width="228" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/440092e1-b504-46ae-a976-eec36892a410">

- [x] Deprecate “content-end” slot

- [x] Implement "content-top" slot

- [x] Implement “content-bottom” slot
A slot for adding non-actionable elements at the end of the component's content.
<img width="433" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/a3c98a6d-308e-4919-b344-e90e803a1c51">

- [ ] Add “image”slot accounting for issue #4701 
<img width="246" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/c1846d10-5eef-4f16-819c-7fe21ccdc114">

### Relevant Info 
Figma Specs outlined here:
https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A2785&mode=dev

#### Which Component
Calcite Tile

**Comment by SkyeSeitz** [comment]
Link to Figma specs: https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A2738&mode=dev

**Comment by eriklharper** [comment]
Per discussion on 3/26 we decided to add a `content-top` and `content-bottom` slot that renders content either above or below all the Tile content, and the plan is to deprecate both `content-start` and `content-end` slots in favor of these 2 new slots.

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.17` with the following html:

```html
<calcite-tile icon="heavy-snow" heading="Mount Frost" description="Base snow depth is 41-cm with all lifts open. Surface conditions are in good condition.">
  <calcite-chip class="new" kind="brand" slot="content-top" scale="s">New</calcite-chip>
  <calcite-chip class="new" kind="outline" slot="content-bottom">Report conditions</calcite-chip>
</calcite-tile>
```

![image](https://github.com/Esri/calcite-design-system/assets/5023024/b58a7786-3b17-48c1-9481-181c007af5c6)
