### ISSUE TITLE
Some components are missing RTL equivalent CSS

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#3668]
### Actual Behavior

Some components are missing RTL equivalents for animation, box-shadow, gradients, etc.

- [x] alert
- [x] date-picker-day
- [x] date-picker-month-header
- [x] input-date-picker
- [x] loader
- [x] panel

### Expected Behavior

All components offer RTL support when these styles are used. 

Use logical properties for text-align, floats/positions/resize, and box model properties width/height and margin/padding/border to be set based on the language used. Provide RTL support wherever these are not available. 

### Relevant Info

Eg. some of the date box shadows use x-offset.
```
:host([start-of-range]) :not(.calcite--rtl),
:host([end-of-range]) .calcite--rtl {
  .day-wrapper {
    border-start-start-radius: 40%;
    border-end-start-radius: 40%;
    box-shadow: inset 4px 0 var(--calcite-ui-foreground-1);
  }
  .day {
    opacity: 1;
  }
}
```

_Reproducible version_:  v1.0.0-beta.94

- [x] CDN
- [x] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by driskull** [comment]
@jcfranco can we maybe shelve this issue to the backburner? I think we might just wait to revisit these.

**Comment by jcfranco** [comment]
I think we should at least look for any animation props that would look odd in RTL. The rest may be minor and worth tackling later. I'll defer to the UXperts™: @macandcheese @asangma

**Comment by macandcheese** [comment]
@jcfranco @driskull Are there

> I think we should at least look for any animation props that would look odd in RTL. The rest may be minor and worth tackling later. I'll defer to the UXperts™: @macandcheese @asangma

Maybe we can open individual issues for each offense as we find them, like the date picker one provided?

**Comment by jcfranco** [comment]
Sounds good. Let’s repurpose this one for the date picker and I’ll create separate issues for anything that came up in https://github.com/Esri/calcite-components/pull/3636#issuecomment-989262308.

**Comment by Elijbet** [comment]
Actually, I decided to rework this issue to cover all the components that need physical positioning swapped with logical, and have multiple PRs instead of separate issues. I noticed that there are quite a bit of components just with box-shadow physical positioning not accounting for RTL.

**Comment by geospatialem** [comment]
Trying to verify this across the components, but not seeing updates/changes across components between `beta.86` and `next` with `dir="rtl"`.

@jcfranco @Elijbet - Are there any specifics we should look into while verifying through the components?

**Comment by geospatialem** [comment]
Assigning back to development for further investigation to determine the changes needed for all styling, and `dir="rtl"`. cc @Elijbet

**Comment by macandcheese** [comment]
Is this still an actionable issue? Might be good to close this and, if any issues are found, open new individual tickets. 

cc @driskull @Elijbet

**Comment by driskull** [comment]
Agreed. looks like they are all checked.

**Comment by macandcheese** [comment]
Closing based on above.
