### ISSUE TITLE
Enhancement: Subtitle/description for combobox-item

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-design-system#3695]
### Description
Provide a subtitle/description prop for displaying a secondary label on a combobox-item

### Acceptance Criteria 
- [ ] A prop is provided to render a secondary label within a combobox-item

#### Which Component
combobox-item

#### Example Use Case
In ArcGIS Velocity, we have a spatial reference selector which has ~9000 items, and users often are familiar with choosing a spatial reference by either the text label (e.g. "GCS WGS 1984") or by its numeric WKID (e.g. "4326"), so we used the `subtitle` prop that calcite-react `MenuItem`s provide to display the numeric WKID on the menuitem, and filtering automatically filters against that subtitle as well.

![image](https://user-images.githubusercontent.com/5069711/145895069-f03dc354-5140-401d-b42e-cdf747357ee7.png)

Due to a bug in calcite-react where scrolling while using the `appendToBody` and `virtualized` props together will cause the dropdown to close, we are looking to switch to using calcite-components combobox instead, but not having this subtitle is a serious UX drawback.

**Comment by macandcheese** [comment]
This would probably be best implemented as a `content-end` slot.

**Comment by hccampos** [comment]
We should also have the ability to provide a value to be displayed in the input when the combobox is closed. In this spatial reference case, it could display the WKID or some other shorter representation of the spatial reference.

In our case, we bumped into this while working on a Timezone picker where we have a long name with the IANA code and the UTC offset, but we don't want to display all that information in the input itself, since it would make the input too large.

**Comment by ashetland** [comment]
Designs for a `description` prop and a `content-end` slot are ready to go in [this Figma file](https://www.figma.com/file/ujZYHdimnVC3yA2PyYOH85/Epic%3A-Combobox-Redesign?type=design&node-id=115-76403&mode=dev). Also outlined is a proposed `value-short` prop to address the needs in [this comment](https://github.com/Esri/calcite-components/issues/3695#issuecomment-1499257085).

**Comment by ashetland** [comment]
A round of feedback has resulted in some fine-tuning to do on the abbreviated value prop and its behaviors.

**Comment by ashetland** [comment]
Revised designs ready in [this Figma file](https://www.figma.com/file/ujZYHdimnVC3yA2PyYOH85/Epic%3A-Combobox-Redesign?type=design&node-id=142-78995&mode=dev). 

Includes `description` prop, `content-end` slot, and a new prop for an abbreviated label to be shown in the input and in the item.

Possible names:

- `text-label-short`
- `text-label-abbreviation`

Notes for docs:

- When provided, displays an abbreviated value in the Comobobx Item when Combobox is expanded and displays as the selected value in the input.
- Recommend 5 characters max.

cc @jcfranco @SkyeSeitz @macandcheese

**Comment by SkyeSeitz** [comment]
Any concerns with `text-label-abbr`?

**Comment by SkyeSeitz** [comment]
Although `text-label-short` is less characters (always a plus), its role may be a bit ambiguous? `text-label-abbreviated` or `text-label-abbreviation` comes with perhaps more clarity, imo.

**Comment by ashetland** [comment]
> Although `text-label-short` is less characters (always a plus), its role may be a bit ambiguous? `text-label-abbreviated` or `text-label-abbreviation` comes with perhaps more clarity, imo.

Added a couple more options to the [list above](https://github.com/Esri/calcite-design-system/issues/3695#issuecomment-1610369185).

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.12`

![Screenshot 2024-07-16 at 2 50 57 PM](https://github.com/user-attachments/assets/3c571e6e-1a0f-44ce-aa28-404dd93927d2)

**Comment by ashetland** [comment]
Reopening issue to correct a couple small misses during design review. [Design spec](https://www.figma.com/design/ujZYHdimnVC3yA2PyYOH85/Epic%3A-Combobox-Redesign?node-id=142-78995&m=dev) has been updated. cc @jcfranco

**Comment by DitwanP** [comment]
🍡 `Verified on 2.11.0-next.21`
