### ISSUE TITLE
Rework the internal contributing and conventions doc

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#3818]
### Description 
The goal is to get the internal doc looking like [Hub's](https://esri.github.io/hub-components/?path=/docs/guides-setup--page)

1. I am going to break the conventions into different files by topic so that they can be items in the storybook sidebar like above.
    - Testing
    - Documentation
    - A11y
    - i18n
    - Style
    - Maybe more?

2. I will audit the existing conventions and remove any that are no longer valid.

3. Then start beefing up the conventions with unspoken stuff we all just do. If you all think of anything specific that needs to be added to the conventions comment on this issue or edit the description below.

### Which Component
NA
### Resources 
Specific conventions that need to be added (feel free to add more here)
- [require more usage of the accessible test helper. So that when a new slot is added its a11y is tested](https://github.com/Esri/calcite-components/pull/3579#issuecomment-1002830027)

cc @driskull @jcfranco @macandcheese 

---
## TODO
* Internal patterns
  * form-associated components
  * labelable components
  * conditionally-slotted rendering components
  * internal event handling
  * distinguishing between internal and external prop setting
  * global attribute utils
  * observer creation (mutation, intersection, resize)
* Testing
  * E2E vs spec
  * common test helpers
* Naming
  * event variable name (`e: event` vs `event: event`)

**Comment by jcfranco** [comment]
Jotting some ideas:

* Internal patterns
  * form-associated components
  * labelable components
  * conditionally-slotted rendering components
  * internal event handling
  * distinguishing between internal and external prop setting
  * global attribute utils
* E2E vs spec testing

**Comment by geospatialem** [comment]
Related: #7724 - could explore a new patterns documentation page which includes https://github.com/Esri/calcite-design-system/issues/3818#issuecomment-1015996968 and `open`/`close` to better serve users.

**Comment by jcfranco** [comment]
Confirmed w/ @benelan. This is no longer as we've started moving internal doc to our wiki. Closing!
