### ISSUE TITLE
Action appearance="clear" hover state should follow general pattern

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#3834]
### Actual Behavior
When Action has `appearance="clear"`, its hover state is kind of a border.

### Expected Behavior
It should probably be a solid background color and follow the same pattern that Button uses and utilize `--calcite-button-transparent-hover`.

Yes, that's what Button uses for `appearance="transprent"`, but that's a different discussion.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/abLYBNr

1. Hover over the Action.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by macandcheese** [comment]
@asangma are any other changes to existing components needed to make this consistent across the library?

**Comment by macandcheese** [comment]
@asangma - I'm going to move this to an enhancement request. There are other components that use the `clear` prop name so we should audit these consistently if we decide to make a change.

**Comment by macandcheese** [comment]
@ashetland @SkyeSeitz can we take a look at this now that the nomenclature has changed and see what's needed here?

**Comment by ashetland** [comment]
Agree. The `appearance`=`transparent` should follow the same hover pattern as Button. Is this another audit situation of hover states on transparent appearance?

**Comment by ashetland** [comment]
[Figma file](https://www.figma.com/file/9w88XL7TvWob68kHIcFWZx/Action-transparent-hover-%5B3834%5D?type=design&node-id=401-8255&mode=dev) for reference.

**Comment by geospatialem** [comment]
Verified in the `main` branch. 
![verify-transparency-action-hover-state](https://github.com/Esri/calcite-design-system/assets/5023024/2242095c-6a9d-4ca4-89e3-b0680696e828)
