### ISSUE TITLE
Action: deprecate "compact" property

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#3859]
### Description
Deprecate the `compact` property.

### Acceptance Criteria 
Include updates to screener and and e2e tests.

#### Which Component
CalciteAction

**Comment by asangma** [comment]
cc @AdelheidF @kevindoshier Do you know if this property is being used?

**Comment by AdelheidF** [comment]
Yes, it's used in filter and layer-override.

**Comment by AdelheidF** [comment]
used here:
![image](https://user-images.githubusercontent.com/44481292/148129042-8785231c-12a9-418d-a774-e10342a5b9b4.png)

without it:
![image](https://user-images.githubusercontent.com/44481292/148128974-d7854340-79d8-4f59-97fe-ce48ae73a70b.png)

**Comment by driskull** [comment]
This property might be ok to have as it just adjusts internal width.

**Comment by macandcheese** [comment]
I think this should be internal if needed at all. In the examples above, using "compact" isn't aligning the x with the carets above or below it anyway.

**Comment by AdelheidF** [comment]
At least it shows at the end of its 'row'. If we take compact away the x just appears somewhere in the middle of the 'row'.

**Comment by geospatialem** [comment]
Similar to `tile`'s `embed` property. If the above proposal is adopted, we should revisit the change to both `action` and `tile` props.

**Comment by brittneytewks** [comment]
Design has confirmed this is good to go, makes sense to proceed forward

**Comment by brittneytewks** [comment]
Removed figma changes label, will track progress for this work in monday.com

**Comment by DitwanP** [comment]
🍡 Verified

**Comment by AdelheidF** [comment]
So compact goes away and is not being replaced with anything else?

**Comment by driskull** [comment]
I think we will likely have a CSS variable added to adjust padding. Is that correct @alisonailea?

**Comment by macandcheese** [comment]
You could use a transparent calcite-button there, which renders as a square without text present.

**Comment by alisonailea** [comment]
> I think we will likely have a CSS variable added to adjust padding. Is that correct @alisonailea?

We aren't currently making spacing variables unless it's needed. @AdelheidF would you please create a ticket?

**Comment by AdelheidF** [comment]
I guess arcgis-button works. To me action would make more sense though.

![image](https://github.com/user-attachments/assets/397be37d-0047-4ee3-9c11-9ada2076bf71)

**Comment by macandcheese** [comment]
I think we want to see button used more when it is a standalone element not contained within a parent and positioned to the extent (in a bar, panel area, etc.). You could use margin-inline-start: auto on the above (or, some other css) to achieve the spacing you had previously. The Card Group also has some built in selection that could be explored by your designers.
