### ISSUE TITLE
Refactor getSlotted dom tests to run in browser

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#3882]
### Description 

Refactor getSlotted dom tests to run in browser

### Proposed Advantages 

This will allow accurate testing of getSlotted() to see if it has assignedNodes.

### Relevant Info 

https://github.com/Esri/calcite-components/pull/3788#discussion_r780580724

It might be a good idea to refactor all the dom e2e tests so that the whole utility file is able to be executed in browser for the most accurate testing.

#### Which Component

N/A

**Comment by jcfranco** [comment]
Closing, will instead work on removal with https://github.com/Esri/calcite-design-system/issues/6059. cc @geospatialem @driskull
