### ISSUE TITLE
Enhancement: Request for Nesting, Drag and Drop, Collapse for Value List Items

### ISSUE THREAD

**Issue by saumeel12** [Esri/calcite-design-system#3997]
### Description

This is a feature request for the List Item/ Value List component. This is part of an effort to bring the UI for Content and Member Categories into Calcite. 

This was originally opened here: https://github.com/Esri/calcite-components/issues/3551 but has been updated with newer designs in this issue. This also works with Inline editing for list item which I believe is an active issue.

### Acceptance Criteria

Implementation of this request should allow:

1. List Items to nest under other list items, forming a type of hierarchy
2. The ability to drag List items to rearrage and change nesting hierarchy based on certain rules applied to it.
3. The ability to Show/hide list items nested under another list item through an expand/collapse

### Relevant Info

This enhancement was discussed with Alan and Mitch to determine this as an effective enhancement. This is planned tentatively for 10.1 release.

### Which Component

List item and Value List

### Example Use Case

<img width="1050" alt="Screen Shot 2022-01-24 at 3 34 47 PM" src="https://user-images.githubusercontent.com/87037561/150882887-4940f2c6-a5b7-4575-ade7-e02dd1e30eca.png">
<img width="1041" alt="Screen Shot 2022-01-24 at 3 35 08 PM" src="https://user-images.githubusercontent.com/87037561/150882928-b39ea2cf-46d7-417b-a8ff-98858a3cf92b.png">
<img width="1046" alt="Screen Shot 2022-01-24 at 3 35 24 PM" src="https://user-images.githubusercontent.com/87037561/150882961-e5e6a6a2-5896-4cb9-93de-0e3611980197.png">

<img width="1120" alt="Screen Shot 2022-01-24 at 3 32 53 PM" src="https://user-images.githubusercontent.com/87037561/150882700-b95ccf73-e99a-4664-a2f6-280edf7a14ad.png">
<img width="1174" alt="Screen Shot 2022-01-24 at 3 30 55 PM" src="https://user-images.githubusercontent.com/87037561/150882516-dc088d92-f17d-457d-94d7-f96308e2247f.png">
<img width="1087" alt="Screen Shot 2022-01-24 at 3 31 10 PM" src="https://user-images.githubusercontent.com/87037561/150882545-07df8285-37ce-488c-b734-42afae2664ff.png">

<img width="1079" alt="Screen Shot 2022-01-24 at 3 31 26 PM" src="https://user-images.githubusercontent.com/87037561/150882573-4e058bd7-c7b5-4eff-84e5-9f82509686df.png">

**Comment by saumeel12** [comment]
@asangma

**Comment by jcfranco** [comment]
> The ability to Show/hide list items nested under another list item through an expand/collapse

`value-list` is deprecated, but for `list`, this is the only outstanding item that might be applicable. cc @SkyeSeitz @ashetland

**Comment by ashetland** [comment]
I believe this is covered? https://esri.github.io/calcite-design-system/?path=/story/components-list--nested-items

**Comment by jcfranco** [comment]
Sweet! Thanks for spotting that, @ashetland!

Based on the above, I'll go ahead and close this.
