### ISSUE TITLE
Enhancement: Custom labels for slider handles and ticks

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-design-system#4004]
### Description

Currently the slider supports a `labelHandles` prop which shows the numeric value of each handle above the slider. There are many cases where the numeric value is not user friendly, and we'd like the ability to set a custom handle text. 

### Acceptance Criteria

API should allow for dynamically updating the custom handle text in response to changes. We propose adding this via an additional prop `formatLabels` which accepts a function:

```
<calcite-slider formatLabels={(value: number) => string} />
```

This function returns a string and must be synchronous. Each time we render a tick label or a handle label, we call this function if available and render the resulting string instead. If this function is not defined or doesn't return a string, the original value is used.

### Relevant Info

I can work on a solution to this for review as we need this for the current release.

This is a more abstract solution to https://github.com/Esri/calcite-components/issues/557 (closed due to inactivity) and is semi related to https://github.com/Esri/calcite-components/issues/2584 as it's the same concept for for handles rather than ticks.

Please respond with thoughts on the API and especially naming as this is a rather esoteric prop concept.

### Which Component

calcite-slider

### Example Use Case

There are lots of applications of this capability:

- Cleanly displaying current value if slider is stepless and shows long decimals (#557)
- Locale specific number formatting
- Slider representing currencies having particular formatting requirements
- Slider representing configurable memory or hard drive size (in bytes, kilobytes, megabytes, gigabytes, etc)
- Level of detail selection (ie 0 = "World" and 12 = "Street")
- Non regular interval sliders (logarithmic, exponential, etc)

**Comment by geospatialem** [comment]
> This came up in a [Community question](https://community.esri.com/t5/calcite-design-system-questions/format-labels-values-on-slider/m-p/1173994#M137) as well.

A second [Community question](https://community.esri.com/t5/calcite-design-system-questions/remove-digit-separator-from-slider/m-p/1192723#M179) arose on this topic as well, also specific to using Slider with years.

**Comment by geospatialem** [comment]
This issue will be prioritized after the 1.0 release next month.

**Comment by DitwanP** [comment]
🚀 Verified on `2.8.0-next.9`
![Screenshot 2024-04-24 at 3 30 23 PM](https://github.com/Esri/calcite-design-system/assets/60022782/f213b82e-d801-4ddf-8b70-4758d908b1ec)
