### ISSUE TITLE
calcite-accordion-item content padding

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#4012]
### Description

`calcite-accordion-item`'s shadow dom `div[class="accordion-item-content"]` has a rendered padding of `0 0.75rem 0.5rem 0.75rem`. The top padding of `0` puts any content right up against the bottom of the accordion header and the header focus can overlap the content by a pixel or so.

### Acceptance Criteria

~~Put some space between `calcite-accordion-item` header and content.~~
See [Calcite Design Solution](https://github.com/Esri/calcite-design-system/issues/4012#:~:text=No%20response-,Calcite%20Design%20Solution,-Apply%20default%20padding) below

### Which Component

`calcite-accordion-item`

## Calcite Design Solution

- [ ] Apply default padding to Accordion Item's content slot to match the header padding at each scale.
~~Add separate CSS vars for the header area and the content area, per [comment](https://github.com/Esri/calcite-design-system/issues/4012#issuecomment-1367487005)~~
- [ ] Add CSS var to adjust the space around the content slot

Medium scale example:
![CleanShot 2024-09-19 at 16 39 19@2x](https://github.com/user-attachments/assets/99ebe317-69a3-48bb-9dcf-1b16cf88d8a3)

**Comment by paulcpederson** [comment]
I also ran into this. I tried to use the `--calcite-accordion-item-padding` CSS var but it still doesn't allow adding padding to the top of the content. Further, it also applies the padding to the item's title/header area. Would be nice to make this padding configurable and also allow setting just the content padding.

**Comment by ashetland** [comment]
Design recommendations add to description above.

**Comment by geospatialem** [comment]
This was not addressed in https://github.com/Esri/calcite-design-system/pull/9861, will need to be a follow-up consideration for design tokens.

**Comment by alisonailea** [comment]
Ah! Got it. Will address ASAP

**Comment by geospatialem** [comment]
The above will have two different solutions:
1. **Phase I: Component tokens** to support user-defined spacing via CSS variables (targeted in September 2024)
2. **Phase II: Default spacing** which will alter the component's default spacing. Added the `visual changes` label as this will have visual changes to the component (targeted in November 2024)

**Comment by ashetland** [comment]
Updated the Calcite Design Solution section above. We only need to provide a variable to control the spacing around the content slot, per the original request. This would match our pattern across the system. This [comment](https://github.com/Esri/calcite-design-system/issues/4012#issuecomment-1367487005) was misread. If control over the header spacing is also required, a new issue should be filed.

**Comment by DitwanP** [comment]
🍡 Verified on `3.0.0-next.20`
