### ISSUE TITLE
Expose CSS variable to style accordion item header in active state 

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-design-system#4060]
### Description

When an accordion item is selected within an accordion, provide a css variable to configure the color of just the accordion item header to more obviously indicate that it is selected. 

There appears to be `--calcite-accordion-item-background` but that seems to color the entire accordion background (header and contents).

### Acceptance Criteria

![image](https://user-images.githubusercontent.com/29421380/152454224-39300388-ae0c-4aab-a1cc-8e8f5f8862f8.png)

### Which Component

calcite-accordion-item

**Comment by macandcheese** [comment]
Thoughts @asangma ? 

Before adding something like this I’d like to try making the active accordion item more obvious by default than providing this variable, we run into issues here as some accordion appearance types has no x-padding on the header.

**Comment by geospatialem** [comment]
This also came up in a [Community post](https://community.esri.com/t5/calcite-design-system-questions/add-style-to-dynamically-added-calcite-accordion) on 9/21/2022 to modify the header color.

As mentioned in the description above the background can be changed. Additionally, a customized border and icon color (if present) can be accessed, but not the header or description text color.

A Codepen example for context: https://codepen.io/geospatialem/pen/dyezJQN

**Comment by geospatialem** [comment]
While not related to `accordion-item`, a similar question was asked on [Community](https://community.esri.com/t5/calcite-design-system-questions/changing-style-of-collapsible-calcite-blocks/m-p/1260640#M330) on 2/22/2023 related to `block` headings. 

Perhaps a pattern we could consider across components with `heading` attributes?

**Comment by macandcheese** [comment]
Still not sure we need to allow for this level of customization.

**Comment by CharanGIS** [comment]
Hi, would it be better to have <calcite-blocks> within <calcite-accordion-item> similar to his [example](https://developers.arcgis.com/calcite-design-system/components/accordion/)

**Comment by geospatialem** [comment]
Will revisit once tokens have been implemented to determine next feasible steps.

**Comment by ashetland** [comment]
Agree with the above that the requested level of customization may not be advisable — Accordion Items can't be selected, only expanded or collapsed. It may be worth looking at so padding tweaks to make the expanded state more clear. See [Carbon's Accordion](https://carbondesignsystem.com/components/accordion/usage/#live-demo) as an example.

**Comment by macandcheese** [comment]
Agree - tokens would allow this level of customization as well depending on granularity of token exposed per component.

**Comment by geospatialem** [comment]
+1 from another [Esri Community member](https://community.esri.com/t5/calcite-design-system-questions/add-style-to-dynamically-added-calcite-accordion/m-p/1527458/highlight/true#M716) on 8/26/2024

**Comment by macandcheese** [comment]
Yeah that case makes sense - ideally these would just be `--calcite-accordion-item-x` properties with heading, description, icon, background-color, etc. - then users can style as they wish based on :hover, [selected], etc., as they need.

**Comment by alisonailea** [comment]
Per Aaron's comment, https://github.com/Esri/calcite-design-system/issues/4060#issuecomment-1624336914
we don't want to break existing design patterns, is there another solution here?

**Comment by macandcheese** [comment]
I think we should still expose the props. If a user decides to base those styling decisions on the open state, that’s up to them. 

We can document defensively about that as we should with all these component specific props, but not having accordion-item properties to achieve the Community post example where all of the items are themes, does seem like a missing story, IMO.

**Comment by geospatialem** [comment]
Verified in `2.13.0-next.14` with https://codepen.io/geospatialem/pen/RwzzPNE for `expanded` and the `:hover` states:

![image](https://github.com/user-attachments/assets/6ec9eeb0-9cba-4c89-96df-dd0341838aa7)
