### ISSUE TITLE
calcite-button: Allow "download" property when "href" property is set

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-design-system#4077]
### Description

When passing in an href to the calcite-button, it becomes an `a` tag under the hood, so it would be useful to have a `download` property added to match the native behavior.

### Acceptance Criteria

When the`href` property has a value, a `download` attribute on the <calcite-button> element can be passed through to the underlying `a` element.

### Relevant Info

A download attribute on the <calcite-link> element is passed through to the underlying <a> element.

Original suggested by @macandcheese in https://github.com/Esri/calcite-components/issues/3758#issuecomment-999066372

### Which Component

calcite-button

### Example Use Case

```html
<calcite-button download="index.html" href="data:...">
  Download demo
</calcite-button>
```

**Comment by geospatialem** [comment]
Should consider all components where an `href` can be added as part of the enhancement effort.

**Comment by Ninkuk** [comment]
Hi @jcfranco I'd like to contribute to this by adding the download property to the button component. I'll follow the same implementation as the download property in the link component. Is it alright if I take this up?

**Comment by jcfranco** [comment]
@Ninkuk Belated thanks for taking this on. 🎉

I've assigned the issue, updated labels and assigned to the March release.

**Comment by DitwanP** [comment]
🍡 Verified on `2.7.0-next.2` that the download prop is passed down to `a` tag.
https://codepen.io/Ditwan-Price/pen/BaEjOVE?editors=100
