### ISSUE TITLE
Virtualized Select Component

### ISSUE THREAD

**Issue by brettephillips** [Esri/calcite-design-system#4112]
### Description

Enhance the Select component to contain a virtualized property that will render rows as the user scrolls (lazy loading dropdown items).

### Acceptance Criteria

- [ ] Virtualized property is added
- [ ] Virtualized property is optional
- [ ] Select dropdown items are not loaded at once, but instead when needed

### Which Component

Select

### Example Use Case

https://calcite-react.netlify.app/select

**Comment by geospatialem** [comment]
Select cannot be virtualized due to its current structure. However virtualization will be tackled across the design system as part of the effort mentioned above in #7384. Closing out the issue per the structure of `select`, and effort of the epic.
