### ISSUE TITLE
calcite-input-date-picker: not preventing typing values outside or min/max

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-design-system#4276]
### Actual Behavior

When typing into the input, I can change the value to be less than the min or greater than the max

![below_min_input_date_picker](https://user-images.githubusercontent.com/44479773/159097261-bbdf25f9-0634-49cc-bbb7-239e2225003a.gif)

### Expected Behavior

The textbox should restrict the user input to be within the min/max values similar to how the actual date picker is behaving.

### Reproduction Sample

https://codepen.io/rpanichakit/pen/popyPVX?editors=1001

### Reproduction Steps

1. Click into the input and delete "8" to turn 3/18/2022 to 3/1/2002
2. Observe that the value is changed and that the event triggered the div to display the new value property

### Reproduction Version

beta.79

### Relevant Info

Windows 10, Chrome 99.0.4844.74

**Comment by ethanbdev** [comment]
Could be related: https://github.com/Esri/calcite-components/issues/4187

**Comment by jcfranco** [comment]
@anveshmekala on blur, as stated above.

**Comment by anveshmekala** [comment]
how do we handle the case where the user type in an invalid value outside of min/max range and the `value` prop isn't parsed initially. Thoughts ? @macandcheese @jcfranco

**Comment by jcfranco** [comment]
Wouldn't it be set to the initial value in this case? Let me know if I missed something.

**Comment by anveshmekala** [comment]
> Wouldn't it be set to the initial value in this case? Let me know if I missed something.

In the case where value prop isn't parsed initially.

Example: ( assume user entered 01/01/2050 in input field after first render.)

` <calcite-input-date-picker min="2022-05-01" max="2022-05-15" ></calcite-input-date-picker>`

**Comment by geospatialem** [comment]
Prioritization and next steps will be made after this month's 1.0 release.

Validation of the component while in `range` mode is not straightforward, and the component may need a redesign, and as a result will need evaluation from the team later this month.

**Comment by geospatialem** [comment]
Should be prioritized once we complete the mobile effort for the design aspects.

**Comment by geospatialem** [comment]
Effort should be executed with https://github.com/Esri/calcite-design-system/issues/3526

More info on [Figma](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=956-94284&mode=design&t=tPqHJcVdxmJmZ6L2-0) and below:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/d696f6fc-8cd0-41f9-963b-984fdde35b2e)

**Comment by geospatialem** [comment]
Verified in `2.8.0-next.19` with https://codepen.io/geospatialem/pen/jORoLWq when the component's `max` is set to `"4/30/2024"`:

![verify-4276](https://github.com/Esri/calcite-design-system/assets/5023024/2ffd3441-b7e3-4ba9-8845-db2be2848a3e)
