### ISSUE TITLE
[Combobox] Add an option to limit the amount of displayed chips

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#4326]
### Description

The Combobox can often become crowded when many chips are selected. 

Propose to add a `limitChips`(name tbd) property that appends all additional chips after that numeric value to a non-dismissible "+n" chip.

Questions to answer:
- What chips are visible - is it decided by order entered, alphabetically, etc.
- Should there be an affordance for "no individual chips" - as in, "4 selected", 6 selected", "1 selected", etc.
   - If so, is that exclusive from this request? If not, how do they interact?
- What happens when the combobox is interacted with - do the "+3" chips appear in-combobox? in-dropdown? nowhere?

### Acceptance Criteria

As a user, I can choose a number of chips to display, after which, all selected items would be appended to a non-dismissible catch-all.

Also note of [Aaron's comment](https://github.com/Esri/calcite-design-system/issues/5226#issuecomment-1613918426)

For example, limit-chips="2" would result in: 

This would result in a display of <chip (1) ><chip 2 (x) ><+n>

### Relevant Info

MUI's "limit tags" https://mui.com/components/autocomplete/#limit-tags

_No response_

### Which Component

Combobox

### Example Use Case

My product offers a state-selection Combobox to a user. Often times, a user can select 5+ states, which clutters the combobox and causes my UI to break. I want to limit the amount of chips displayed.

**Comment by LeviRemi** [comment]
Customer example where they dislike how other containers in the same row grow in height to accommodate the ever-expanding combobox. This layout also does not scale well for large quantities of selection. 
<img width="869" alt="Screen Shot 2022-03-29 at 2 20 27 PM" src="https://user-images.githubusercontent.com/21701076/160709136-b9d01749-887e-4d82-81ac-368b4785ccb5.png">

**Comment by mMa2** [comment]
The displayed selected chips keep growing and occupy too much real estate, hide other components on the UI, it is too crowded for the user to see other items. Please consider options as 1)shrink the display text 2) have a textbox labelled down to show selected items, no displaying chips

**Comment by ashetland** [comment]
Proposing a new `display-mode` prop that would address the need to limit the number of chips displayed while also making Combobox a more responsive component. 

Full designs and context with other issues from epic #6720 are available in [**this Figma file**](https://www.figma.com/file/ujZYHdimnVC3yA2PyYOH85/Epic%3A-Combobox-Redesign?type=design&node-id=370-86756&mode=dev).

This property does not affect `selection-mode=”single”`.

### displayMode Values
`show-all` (default)
 Current behavior — Combobox grows in height to accommodate chips as items are selected.

`single `
Combobox displays a single chip that shows the total number of selected items or “All selected” when all items are selected. (See [related designs](https://www.figma.com/file/ujZYHdimnVC3yA2PyYOH85/Epic%3A-Combobox-Redesign?type=design&node-id=274-82801&mode=dev) for `select-all`, issue #2311.)

`fit-to-line` 
Combobox will display chips in the order they are selected, but will not grow in height. Additional selections are added to a chip that displays the number of selected items not shown (+n). When the width is small enough to only accommodate a single chip, that chip follows the behaviors outlined in `single` (total number or “All selected”.)

### Note
Chips that display “All selected” or “n selected” or “+n” are not closable. This is to prevent a conflict with the clear-all button.

**Comment by geospatialem** [comment]
There are a few remaining items needed for resolution, including tests and additional team reviews. Reallocated to the November release for inclusion. cc: @brittneytewks

**Comment by geospatialem** [comment]
Verified in `2.0.0-next.1` with the [following Codepen](https://codepen.io/geospatialem/pen/rNPdQmd) for `selectionMode` of `"ancestors"` and `"multiple"` with `selectionDisplay` of `"all"`, `"fit"`, and `"single"`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/512b3682-756f-4f4d-b358-7d35beacffe1)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/d78e82ac-c352-4b73-befb-e5b0c4d95133)
