### ISSUE TITLE
[Switch] preventDefault when using spacebar to interact

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#4378]
### Description

Currently, using the `space` key to interact with the `calcite-switch` causes the page to scroll. We should mimic the behavior of `calcite-checkbox` (and `calcite-switch` itself with `enter` key), and allow users to interact with the `space` key in the same way they can an `enter` key - toggling the control and not scrolling the page.

### Acceptance Criteria

Using `space` key to interact with `calcite-switch` does not scroll the page in addition to toggling the control.

### Which Component

`calcite-switch`

### Example Use Case

See demo:
https://codepen.io/mac_and_cheese/pen/yLpKoYL?editors=100

**Comment by jcfranco** [comment]
This is longer reproducible with the latest: https://codepen.io/jcfranco/pen/XWoWXpE?editors=100. Closing!
