### ISSUE TITLE
Improve input property descriptions for min/max and minLength/maxLength

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#4418]
### Description

1. The current descriptions for `min`, `minLength`,`max`, and `maxLength` are not sufficient to explain the difference in use. We should update these to provide more information to a user.

### Which Component

Input (and eventually, input-number...)

### Resources

Stems from Teams discussion: 
https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1650293562164?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1650293562164&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1650293562164

**Comment by jcfranco** [comment]
Doc has been improved (see https://github.com/Esri/calcite-design-system/commit/cd532710c324e0f0ffb4c01d34dba78dda9a5b74). Closing!
