### ISSUE TITLE
Expose calcite-components CSS variables for spacing

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-design-system#4437]
### Description

Add CSS variables with the spacing sizes calcite-components uses. For example, `--calcite-spacing-1: 0.25rem` or `--calcite-spacing-3: 0.75rem`. This would allow consumers of calcite-components to have consistent spacing throughout their project. Currently, one must either define their own spacing to match calcite-components (or by extension, TailwindCSS), or integrate TailwindCSS into their project.

### Acceptance Criteria

Expose all spacing used by calcite-components through CSS variables.

### Which Component

calcite-components

### Example Use Case

A new project uses calcite-components and is not interested in using TailwindCSS. To keep their app looking consistent with calcite-components, they can use CSS variables provided by calcite-components for CSS properties such as `padding`, `margin`, `right`, `left`, etc.

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/7180.
