### ISSUE TITLE
Split up playground stories from screenshot tests

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#4458]
### Description

Our storybook started off as a playground for all components and then got used as the base for screenshot tests. Both of these should be split up to have a clearer separation of the two and to make it easier to add types of each. Because of the mix, it's not clear whether test ones should enable all knobs or not (they should not). 

### Proposed Advantages

Clear separation of test and demo stories. Possibly faster test run times as not all would need to run for screenshot tests.

### Which Component

- [ ] `accordion` 
- [ ] `accordion-item` 
- [ ] `action` 
- [ ] `action-bar` 
- [ ] `action-group` 
- [ ] `action-menu` 
- [ ] `action-pad`
- [ ] `alert`
- [ ] `avatar`
- [ ] `block`
- [ ] `block-section`
- [ ] `button` 
- [ ] `card` 
- [ ] `checkbox`
- [ ] `chip`
- [ ] `chip-group`
- [ ] `color-picker`
- [ ] `combobox`
- [ ] `combobox-item` 
- [ ] `combobox-item-group` 
- [ ] `date-picker` 
- [ ] `dropdown` 
- [ ] `dropdown-group` 
- [ ] `dropdown-item` 
- [ ] `fab` 
- [ ] `filter` 
- [ ] `flow` 
- [ ] `flow-item` 
- [ ] `icon` 
- [ ] `inline-editable` 
- [ ] `input` 
- [ ] `input-date-picker` 
- [ ] `input-message` 
- [ ] `input-time-picker` 
- [ ] `input-time-zone`
- [ ] `label` 
- [ ] `link` 
- [ ] `list` 
- [ ] `list-item` 
- [ ] `list-item-group` 
- [ ] `loader` 
- [ ] `menu`
- [ ] `menu-item`
- [ ] `meter`
- [ ] `modal` 
- [ ] `navigation`
- [ ] `navigation-logo`
- [ ] `navigation-user`
- [ ] `notice` 
- [ ] `option` 
- [ ] `option-group`
- [ ] `pagination` 
- [ ] `panel` 
- [ ] `pick-list` 
- [ ] `pick-list-group`
- [ ] `pick-list-item` 
- [ ] `popover` 
- [ ] `progress` 
- [ ] `radio-button` 
- [ ] `radio-button-group` 
- [ ] `rating`
- [ ] `scrim`
- [ ] `segmented-control` 
- [ ] `segmented-control-item` 
- [ ] `select`
- [ ] `shell`
- [ ] `sheet`
- [ ] `shell-center-row` 
- [ ] `shell-panel`
- [ ] `slider` 
- [ ] `split-button` 
- [ ] `stepper` 
- [ ] `stepper-item` 
- [ ] `switch` 
- [ ] `tab`
- [ ] `tab-nav` 
- [ ] `tab-title` 
- [ ] `table`
- [ ] `table-cell`
- [ ] `table-header`
- [ ] `table-row`
- [ ] `tabs` 
- [ ] `text-area`
- [ ] `tile` 
- [ ] `tile-select` 
- [ ] `tile-select-group` 
- [ ] `time-picker` 
- [ ] `tip` 
- [ ] `tip-group` 
- [ ] `tip-manager` 
- [ ] `tooltip` 
- [ ] `tree` 
- [ ] `tree-item` 
- [ ] `value-list`
- [ ] `value-list-item` 

### Relevant Info

![download-1](https://user-images.githubusercontent.com/197440/165561711-9fa51938-57ac-4ec3-a53d-0718a23ffc9d.jpg)

**Comment by geospatialem** [comment]
Solution should consider splitting up using separate folders, would have a separate test file.

**Comment by jcfranco** [comment]
The special story story name suffixes might need to be revisited as well.

**Comment by jcfranco** [comment]
This is superseded by https://github.com/Esri/calcite-design-system/issues/9084 and https://github.com/Esri/calcite-design-system/pull/9030 (conventions doc update).
