### ISSUE TITLE
Loader - design issues

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#4470]
### Actual Behavior

When `inline` 
* the `text` string is placed poorly

When `inline`  and `determinate`
* the `value` string is too big inside the circles
* the stroke color is too dark and hard to distinguish from the blue stroke

When not `inline`
* the `text` string is placed poorly

### Expected Behavior

When `inline` and `determinate`
* suggest not rendering the `text` string
* suggest not rendering the `value` string
* use the correct stroke color, e.g. match the color when not `inline`

When not `inline`
* better styling for the `text` string

### Reproduction Sample

https://codepen.io/mtb-alan/pen/QWQLKvq

### Reproduction Steps

1. View the sample

### Reproduction Version

latest

## Calcite Design Recommendations
See this [comment](https://github.com/Esri/calcite-design-system/issues/4470#issuecomment-2293611780) for design specs.

**Comment by asangma** [comment]
It looks like inline Loader has a `stroke: currentColor` on it.

**Comment by macandcheese** [comment]
We should evaluate the need for these string props at all, if this is the only bug report maybe they aren't worth maintaining? If we do keep them, we'll need design improvements for the bugs shown in that codepen.

**Comment by geospatialem** [comment]
Will investigate further to help prioritize after next month's release if breaking changes are needed (May release), or if we can incorporate into an earlier release.

**Comment by macandcheese** [comment]
@asangma want to take a stab at some of these design improvement proposals :) ?

**Comment by geospatialem** [comment]
> @asangma want to take a stab at some of these design improvement proposals :) ?

@asangma WDYT about taking a look into some prospective design opportunities in July?

**Comment by geospatialem** [comment]
Updated the issue context above to include the design considerations of `inline` with `text` per [this Community thread](https://community.esri.com/t5/calcite-design-system-questions/inline-not-working-with-loader/m-p/1322717#M481).

**Comment by jacqueskeet** [comment]
Please see the Figma file for the proposed designs here: 

https://www.figma.com/design/3ZUBn0JzuDTqQ1LYYtDdXT/Loader?m=dev&focus-id=1786-768

**Comment by DitwanP** [comment]
@jcfranco Looks mostly good to me, just want to know if the inline variants should still be black. In [this post](https://github.com/Esri/calcite-design-system/issues/4470#issuecomment-2293611780) looks like they should now be blue? I don't have access to the full Figma right now but LMK if it's as planned and this one can be marked as verified. 
![image](https://github.com/user-attachments/assets/a7885f59-0893-4d44-9123-1aa63f9a60cb)

**Comment by DitwanP** [comment]
🍠 Verified locally on `dev`
