### ISSUE TITLE
Revisit form util to only have the topmost form owner handle all the form logic

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#4506]
### Description

Revisit form util to only have the topmost form owner handle all the form logic

### Proposed Advantages

Only the parent top-most form control will handle sending data to the form. This eliminates conflicting form components sending data to the form and uses less event listeners so performance should be better.

### Which Component

All form supported components. 

### Relevant Info

https://github.com/Esri/calcite-components/pull/4439#pullrequestreview-966482680

**Comment by driskull** [comment]
Using our own components inside shadowRoot of others.

**Comment by jcfranco** [comment]
I believe this may no longer be valid. Only the topmost form component handles interacting with the parent form (following our form component pattern). Child form components do have the plumbing to associate themselves with a form, but it depends on them receiving a `form` property (topmost form component handles and does not pass along) or having an associated form field `name` (both set by users).

**Comment by jcfranco** [comment]
I'm going to go ahead and close this based on ☝️. #8126 should help streamline our form components.
