### ISSUE TITLE
Filter - support preventing the escape key to clear the filter

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#4507]
### Description

Filter - support preventing the escape key to clear the filter

https://github.com/Esri/calcite-components/pull/4439#pullrequestreview-952512490

We could add the event listener on the document using the @Event decorator and check to see if it has event.defaultPrevented in this case as a solution to keep the logic on this component.

### Acceptance Criteria

A user can call preventDefault() on the escape key event and stop the filter from being cleared.

### Relevant Info

https://github.com/Esri/calcite-components/pull/4439#pullrequestreview-952512490

### Which Component

Filter

### Example Use Case

A user has a parent component that needs the escape key to do something without clearing the filter

**Comment by geospatialem** [comment]
Closing, no valid use case at this time.
