### ISSUE TITLE
Calcite input numeric does not limit typed in numbers to min/max

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-design-system#4566]
### Actual Behavior

When using `<calcite-input>` as a number the user is still allowed to type in numbers outside the min/max range. While it was mentioned that this mirrors browser behavior https://github.com/Esri/calcite-components/issues/622#issuecomment-635662595.

However `<calcite-input>` as a number also does not allow you to type in non-numeric number which differs from default browser behavior (which allows you to type in non numeric characters).

### Expected Behavior

We have had bugs introduced because we thought `min` and `max` would actually restrict users from typeing in numbers outside the `min` and `max` it seems reasonable that most people actually expect this to limit what users can type in and make it consistent with other calcite components behavior.

It seems pretty obvious from https://github.com/Esri/calcite-components/issues/622 and https://github.com/Esri/calcite-components/issues/4276 that people expect `min` and `max` to limit the value users can type into the input.

when a number outside the min/max is entered either:

1. Set the value to the closest to the mix/max
2. Reset the value to the previous value

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input/

### Reproduction Steps

You can reproduce this in https://developers.arcgis.com/calcite-design-system/components/input/

1. Set type to `number`
2. Set a min and max
3. Type something in outside the min/max range.

### Reproduction Version

beta.81

**Comment by geospatialem** [comment]
We plan to address validation across components in the near future and have added this issue to an Epic (#4598) for tracking purposes.

**Comment by geospatialem** [comment]
For dev implementation, refer to the [Figma documentation](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=956-94284&mode=design&t=tPqHJcVdxmJmZ6L2-0):

![image](https://github.com/Esri/calcite-design-system/assets/5023024/12701c5b-8608-496b-a885-8ff6a28e46fb)
