### ISSUE TITLE
Simplify box-shadows

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#4568]
### Description

Currently our box-shadows use multiple shadows. The visual result is subtle but not necessary for usability.
See a comparison here: https://codepen.io/mtb-alan/pen/mdXWpJo

### Proposed Advantages

Simplifying the box shadows will reduce code.
It will improve creating and managing related styles in design assets (Figma UI kit).

### Which Component

All

### Relevant Info

See proposed sample here: https://codepen.io/mtb-alan/pen/mdXWpJo

**Comment by asangma** [comment]
cc @macandcheese @rmstinson

**Comment by asangma** [comment]
Related to #1431

**Comment by jcfranco** [comment]
Closing in favor of #1431.
