### ISSUE TITLE
Refactor globalAttributes utility to handle common fallback options

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#4576]
### Description

I could see the fallback options for the document and "en" being used a lot. 

example: `const lang = this.globalAttributes["lang"] || document.documentElement.lang || "en";`

### Proposed Advantages

I wonder if we can DRY this up so that every component getting "lang" doesn't have to set these fallbacks.

The goal would be that any component using `this.globalAttributes["lang"]` has the same fallbacks.

### Which Component

All components

### Relevant Info

https://github.com/Esri/calcite-components/pull/4574#discussion_r876069296

**Comment by jcfranco** [comment]
At least for the `lang` case, there's now a [`getLocale` util](https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts#L298-L311), which DRYs up this issue's use case. Are there any other cases we would need a fallback for?

**Comment by geospatialem** [comment]
No longer relevant, has been addressed in previous efforts.
