### ISSUE TITLE
[Tooltip] Setup tests for text aligned to center

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#4654]
### Test type

Screener

### Which Component(s)

Tooltip

### Unstable Tests

_no response_

### Test error, if applicable

_no response_

### PR skipped, if applicable

_no response_

### Additional Info

For epic #4632

https://esri.github.io/calcite-components

#### Scope

When components aren't accounting for when the body is aligned to center.

#### Action needed

Screenshot test needed to account for body alignment to center.

**Comment by geospatialem** [comment]
Closing in favor of the epic effort of https://github.com/Esri/calcite-design-system/issues/4632 to streamline the effort and simplify messaging/execution.
