### ISSUE TITLE
[Tile / Tile Group] Add visual scales

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#4759]
### Description

We should bring these components in line with others by adding additional scales to provide S, M, L.

### Acceptance Criteria

Additional scales are added to these components, and to the Figma component library.

### Which Component

Tile / Tile Group

**Comment by SkyeSeitz** [comment]
Link to Figma specs: https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A2738&mode=dev

**Comment by geospatialem** [comment]
Verified in `2.2.0-next.18` when `tile`'s `scale` is set to `"s"`, `"m"`, or `"l"` (`"m"` is the default).

![image](https://github.com/Esri/calcite-design-system/assets/5023024/5bb275b2-0e62-4fdc-9fc8-b7a1176e6144)

cc @SkyeSeitz + @eriklharper It looks like the original ask was for both `tile` and `tile-group`. The [Figma file](https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?node-id=720%3A2738&mode=dev) mentions adding a new `tile-group` component, but I'm not seeing the addition in the code. Is that part of this issue, or a different issue? Want to verify before closing the above out. TIA! 🙌🏻 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/10f1038b-7ac2-4772-8548-def6cd6bb3de)

**Comment by geospatialem** [comment]
Closing with `tile` completed per https://github.com/Esri/calcite-design-system/issues/4759#issuecomment-1893985006, and `tile-group` will be addressed in next months release with https://github.com/Esri/calcite-design-system/issues/8615.
