### ISSUE TITLE
Rename properties that start with non/no in favor of xyz-disabled

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#4824]
### Description

Properties that start with no or non should be renamed to xyz-disabled. For example, `noPadding` would become `paddingDisabled`.

### Proposed Advantages

Good practices

### Which Component

block - `noPadding` to `paddingDisabled`
loader - `noPadding` to `paddingDisabled`
modal - `noPadding` to `paddingDisabled`

tip - `nonDissmissible` to `closeDisabled`

list-item - `nonInteractive` to `interactionDisabled` 
pick-list-item - `nonInteractive` to `interactionDisabled` 
value-list-item `nonInteractive` to `interactionDisabled` 

Feel free to add any properties I missed or change the suggested, new property names.

### Relevant Info

cc @mat

**Comment by jcfranco** [comment]
Closing as the only remaining props are for deprecated components (`pick/value-list`).
