### ISSUE TITLE
Scale of calcite-button icons

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#4853]
### Description

The scale of the icons in a `<calcite-button>` element are locked to the `"s"` size. For icon-only buttons, it'd be helpful to be able to user larger-scaled icons.

### Acceptance Criteria

Allow some way to set the scale of the button's icons.

One proposal is, for a `<calcite-button>` element without any text content, is to apply its own `scale` property to any defined `iconStart` or `iconEnd` properties.

### Relevant Info

A workaround is to wrap `<calcite-button>` around a `<calcite-icon>` element, however this is not optimal as the button does not apply consistent padding around its contents. As a result, the button appears slightly rectangular instead of square.

### Which Component

calcite-button

### Example Use Case

E.g. a transparent "x" button for closing a widget:

```html
<calcite-button appearance="transparent" color="neutral" icon-start="x" label="Close ..."></calcite-button>
```

**Comment by macandcheese** [comment]
Scale "s" / "m" buttons will use "s" scale icon and scale l button will use "m" scale icon. I don't know if we want to allow customization of icon scale separately from the containing component, as this could lead to cases where similarly scaled buttons have unmatched icon scale.

cc @SkyeSeitz @ashetland for design decision.

**Comment by SkyeSeitz** [comment]
I agree with the concern Adam mentioned and would prefer to keep the icon scale linked to the scale of the Button to ensure padding matches intended icon scale and consistency with icons in surrounding components with a shared scale as mentioned above.
