### ISSUE TITLE
Allow configuration of card box-shadow

### ISSUE THREAD

**Issue by FelFly** [Esri/calcite-design-system#4855]
### Description

We'd like to be able to change the `box-shadow` on `.calcite-card-container`. Today, `box-shadow` appears only on hover and is set to transparent on the default state. We'd really like to be able to be visible at all times.

### Acceptance Criteria

AS an individual viewing a card component,
AND not interacting with the card component,
THEN I would see a box-shadow on the card,
AND IF I hover my cursor over the card,
THEN I would not observe any changes to the box-shadow.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/card/

### Example Use Case

I don't have a code snippet; I only have the original design mocks that we're trying to get close to achieving: https://xd.adobe.com/view/acf4ddf9-e39a-4f7f-a852-bbd803f86956-f9a7/

**Comment by geospatialem** [comment]
@FelFly The above linked issue #5204 removed the box shadow on hover, so it can be adjusted with css to fit the use case, similar to [this example](https://codepen.io/geospatialem/pen/WNPRJvM).

![image](https://github.com/Esri/calcite-design-system/assets/5023024/5ad4dca9-9ed7-4f68-8774-046e9d963da1)
