### ISSUE TITLE
Avatar: add option to set the background color

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#4900]
### Description

Add a CSS variable or property that allows users to change the background color of `calcite-avatar`. That is a pretty common use case in profile configuration. The app developer would have to choose colors that meet contrast ratio guidelines, and then the user could select one of those colors in the profile UI.

### Acceptance Criteria

A CSS variable (my preference) or property for changing `calcite-avatar`'s background color.

### Relevant Info

From https://community.esri.com/t5/calcite-design-system-questions/avatar-choose-colour-and-3-character-id-display/m-p/1191371

### Which Component

`calcite-avatar`

### Example Use Case

Like how Esri Community lets you choose different background colors for globes:
![image](https://user-images.githubusercontent.com/10986395/178376133-aecb5363-17d3-4181-a57c-68d94e72025b.png)

Only it would be different background colors w/ initials for `calcite-avatar`.

**Comment by geospatialem** [comment]
Related to efforts from https://github.com/Esri/calcite-design-system/issues/7180.

Additional consideration: Add a screenshot test to ensure color contrast is part of the effort with sufficient foreground and background contrast.

**Comment by evan-cx** [comment]
Our team would like this implemented

**Comment by DitwanP** [comment]
🍠 Verified locally on `dev`
![image](https://github.com/user-attachments/assets/82de9d15-c8de-4428-84d4-f9bb2aa79938)

**Comment by evan-cx** [comment]
Thanks guys!
