### ISSUE TITLE
[Block] Add icon property, update slot nomenclature

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#4932]
### Description

The current Block slot documentation / naming is overly limiting, in practice an action or other element may be applicable :

https://developers.arcgis.com/calcite-design-system/components/block/#component-api-slots-control

### Which Component

Block

Proposing that we rename the current slots to ones more consistent with the system:

Control -> Actions End
Icon -> Content Start

Additionally: 

Icons are extremely common to see in Blocks. The vast majority of the time, they are simply using Calcite UI Icons that could be provided via prop. Sometimes they need to be custom image or other graphic, and for those cases, the "content-start" slot should be sufficient.

Add: Add an icon property that can be used in lieu of icon slot. Of course, folks can still slot a custom icon here, but providing an icon slot will ensure more consistently implemented designs in more cases while still preserving the location for custom icon or image. This will display alongside "content-slot", and if populated, that slot should not replace this icon provided via property.

**Comment by macandcheese** [comment]
Probably a good candidate for the internal Stack component here - even "icon" could probably just be "content-start".

**Comment by ashetland** [comment]
Related #4935

**Comment by jcfranco** [comment]
Similar to https://github.com/Esri/calcite-design-system/issues/6918, existing slots should be deprecated to allow developers time to migrate to the new ones before we remove them in a future breaking change release.

**Comment by ashetland** [comment]
[Figma file](https://www.figma.com/file/7uLiqKs0ZGUeMa8OmNQQoP/Block%2FBlock-Section-icon-prop-and-slot-naming-%5B4932%2C-8110%5D?type=design&node-id=2754-34186&mode=dev) documenting the changes for the above and deprecating the `status` prop to align with #8110. Recommend implementing them together.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
