### ISSUE TITLE
Add a common test util for all OpenCloseComponents

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#4968]
### Description

Add a common test util for all OpenCloseComponents.

### Acceptance Criteria

A common utility to handle https://github.com/Esri/calcite-components/pull/4962#pullrequestreview-1043972984

### Relevant Info

https://github.com/Esri/calcite-components/pull/4962#pullrequestreview-1043972984

### Which Component

All openCloseComponents

**Comment by geospatialem** [comment]
Verified on the `main` branch. ✨
