### ISSUE TITLE
Emit `calciteStepperItemChange` when navigating by stepper methods

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#5021]
### Description

When a user clicks a button that invokes a [stepper method][1] and navigates a stepper, the stepper should emit a `calciteStepperItemChange` events.

[1]: https://developers.arcgis.com/calcite-design-system/components/stepper/#component-api-methods

### Acceptance Criteria

A stepper emits a `calciteStepperItemChange` whenever the step changes either by clicking a stepper-item heading or via a stepper method.

### Which Component

calcite-stepper

### Example Use Case

In some cases, it's necessary to force a user to visit steps in order. This can currently be accomplished by disabling subsequent steps and offering a button that, when clicked, enables the next step and navigates to it via the stepper's `nextStep()` method.

In order to cleanly track the current step and which steps have been visited (regardless if the user clicked the button or navigated to a previously enabled step by clicking its heading), it'd be helpful to unify that code in a single `calciteStepperItemChange` handler.

Another use case is the event provides an indicator that the step is rendered and ready for any setup work (e.g. setting initial focus).

**Comment by jcfranco** [comment]
We only emit change events on user interaction, so any code calling the stepper methods needs to sync up accordingly. Reason being that the code calling the stepper methods knows that there is potentially a change in step, hence why we don't emit. It also helps avoid cases where we can't distinguish where a change event came from. 

I think what's missing is a property to easily know the selected stepper item. FYI, I'll have a PR for cleaning up event payloads this week that will introduce this prop.

**Comment by macandcheese** [comment]
Some items here as follow up from triage:
- This component does not adhere to the convention of limiting publicly methods. Propose to remove the current methods.
- Currently, the [calciteStepperItemChange](https://developers.arcgis.com/calcite-design-system/components/stepper/#api-reference-events-calciteStepperItemChange) is emitted from Stepper. There is no event emitted from Stepper Item.
- To match other components, we should emit StepperItemChange from Stepper Item and emit a new StepperChange from Stepper

**Comment by jcfranco** [comment]
> Installed and assigned for verification.

False alarm. Updated the label on the wrong issue. 😅

![nothing-to-see](https://github.com/Esri/calcite-design-system/assets/197440/2abd9843-3390-4f69-9d4d-c520b4e14cbd)

**Comment by jcfranco** [comment]
Spike summary:

* This should be feasible for this release.
* Per https://github.com/Esri/calcite-design-system/issues/6134#issuecomment-2067087240, we won't pursue removing methods.
* In addition to proposed events, parent event will be deprecated in favor of child events.

**Comment by jcfranco** [comment]
Added to this milestone per ☝️.

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/2094 as title and description are closer to the changes #9351 will include. cc @geospatialem
