### ISSUE TITLE
scrim description should mention that it does not prevent keyboard interaction

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#5049]
### Description

The visual appearance of scrim and mouse behavior may lead developers to think it also prevents interacting with the contents behind it. 

### Which Component

`calcite-scrim`

### Resources

https://github.com/Esri/calcite-components/blob/master/src/components/scrim/readme.md
https://github.com/Esri/calcite-components/blob/master/src/components/scrim/scrim.tsx

**Comment by geospatialem** [comment]
This was tackled as part of #5587 in late October as a result of https://github.com/Esri/calcite-design-system/issues/5587#issuecomment-1724082376

Available on our doc site: https://developers.arcgis.com/calcite-design-system/components/scrim/#accessibility.
