### ISSUE TITLE
Filter: allow users to choose to match or ignore specific item properties

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#5063]
### Description

Right now `calcite-filter` matches every property of the item's object. It would be great if we could create a new property that specifies either properties to ignore or the properties to match. The property type `Array<string>` so it would need to be set in JavaScript. Something like

```js
filterElement.ignoreFields = ["OBJECTID", "address"]
```
or
```js
filterElement.matchFields = ["city", "state", "county"]
```

thoughts on this @jcfranco?

### Acceptance Criteria

A new property that either matches or ignores specific properties of filter's item objects.

### Which Component

calcite-filter

### Example Use Case

I was putting together a pagination sample for someone and noticed inconsistent filter results:
https://codepen.io/benelan/pen/qBoxdwv

I realized it was because I was adding a hex string `color` property for the card's thumbnail, which was also being matched. It would have been great to be able to do something like 

```js
filterElement.ignoreFields = ["color"]
```
or
```js
filterElement.matchFields = ["NAME", "CITY", "STATE"]
```

You can work around the constraint by passing a subset of the items' properties to `calcite-filter` and then matching the item back to the full dataset with an `id` or something that does get provided to filter. But it seems like a useful option for people anyway, and relatively low effort on our end to remove certain properties before filtering.

**Comment by driskull** [comment]
I prefer having an allowList like `filterElement.matchFields = ["NAME", "CITY", "STATE"]` but that would be considered a breaking change since fields would need to be configured going forward if someone is using `calcite-filter` as a standalone component. We document filter so they could be.

Should this move to a breaking change release? Or do we want to go with a blockList instead?

**Comment by jcfranco** [comment]
We could also consider the default to match all unless the user sets the allow list. This would preserve the existing behavior, allow users to ignore certain fields and doesn't require users to set anything by default.

**Comment by driskull** [comment]
Sounds like a good plan

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
