### ISSUE TITLE
Flow: do not remove child items from the DOM when drilling

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#5072]
### Description

Update `calcite-flow` to no longer remove a `calcite-flow-item` from the DOM when drilling. Instead, a `selected` property should be added to `calcite-flow-item` to determine which item is actively visible instead of assuming the last child item in a flow wins. The `calcite-flow` will be updated to look at the `selected` property of a `calcite-flow-item`.

### Acceptance Criteria

- Flow Items are no longer removed from the DOM when drilling.
- New `selected` property on Flow Item is used instead

### Relevant Info

blocked until #5071 is completed

### Which Component

calcite-flow
calcite-flow-item

**Comment by driskull** [comment]
@benelan @jcfranco Is this something we want to do pre 1.0?

If we add an `open` property to the `flow-item`, to support it in `flow` we would also probably need to add an `open` property to `panel` which I don't think we want to do.

**Comment by geospatialem** [comment]
@driskull We're looking for a `spike` for an initial prototype of what we could achieve in an upcoming breaking change release WRT the `flow` and `flow-item` behavior above.

**Comment by driskull** [comment]
Sounds good @geospatialem. I can work on this.

**Comment by driskull** [comment]
@geospatialem have prototype here: https://github.com/Esri/calcite-design-system/pull/9390

Can we unspike this? 🌵
