### ISSUE TITLE
Make reproduction bot smarter

### ISSUE THREAD

**Issue by benmccann** [Esri/calcite-design-system#5078]
### Summary

I filed an https://github.com/Esri/calcite-components/issues/5077 and had the "incomplete issue report" label applied eventhough I provided a reproduction

### Desired Outcome

Github reproductions should be supported. codepen, codesandbox, and jsbin cannot be used to reproduce Node.js issues. stackblitz could also be added as a supporter reproduction platform

**Comment by benelan** [comment]
Thanks for the feedback! To provide some background, [here is the bot](https://github.com/marketplace/actions/need-more-info) I created to check for samples. It works by checking for text specified in [a config](https://github.com/Esri/calcite-components/blob/master/.github/need-info.yml). I'll find a way to match GitHub URLs as samples without getting false positives when linking to other issues or PRs. Could probably update the bot to use regex.

**Comment by geospatialem** [comment]
Additional effort is needed to improve the bot per https://github.com/Esri/calcite-components/pull/5190#issue-1344728781. Research should be conducted to execute next steps for improvement.

**Comment by benelan** [comment]
I think #5190 and the change to a form issue template with the sample field marked as required is sufficient here.
