### ISSUE TITLE
[calcite-label] Label text cursor type on hover should match the control it wraps

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-design-system#5197]
### Description

When a `calcite-label` wraps a control, it always uses the `text` cursor even though it is clickable and will focus the control it wraps. This is especially relevant for the checkbox where interacting with the label will actually selec / deselect the checkbox. Here is a gif example of what I mean:

![860BB6D8-5722-4DC1-9C43-0B5551D5A3B6](https://user-images.githubusercontent.com/52869490/185998488-88f5db72-bba3-429f-a3ab-0105fca96eca.GIF)

### Acceptance Criteria

The cursor type of the label on hover would match the cursor type of the control.

### Which Component

calcite-label

**Comment by macandcheese** [comment]
It would be tough to match the cursor style of any slotted control since they can vary - it seems like a native `label` element uses the `default` cursor though, not `text`.

Would that be a safer / more expected default? FWIW a native checkbox uses `default` too, not `pointer`, so maybe we should evaluate instances where we use that.

**Comment by jcfranco** [comment]
Agreed on the complexity. Probably not worth it if users may not expect a cursor change based on default browser behavior.

**Comment by ethanbdev** [comment]
I think default works, or an easy way for a component consumer to customize it via a variable? Really we just want the consistency

**Comment by geospatialem** [comment]
@ethanbdev As Adam and Franco mentioned we're aiming to provide similar support to the default. You could, however, add a `cursor:pointer` styling to reflect the change, similar to https://codepen.io/mac_and_cheese/pen/OJdWOYp.

Closing the above as unplanned with some workarounds possible, and to stay in alignment with the default behavior.
