### ISSUE TITLE
[Block] collapsible prop should persist when control slot is populated

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#5248]
### Description

Requesting that when the control slot is populated in Block, the collapsible chevron does not go away. 

### Acceptance Criteria

The collapsible chevron persists when the control slot is populated.

### Which Component

Block

**Comment by macandcheese** [comment]
Related - we should look into aligning these slots with our other components - introducing the `action / content / start / end` paradigm from List. The current `icon` and `control` are unique to Block and are a bit limiting w/r/t layout needs. cc @asangma

**Comment by asangma** [comment]
We should discuss this as it would have broad effects on in-production interfaces where real estate is at a premium and where the current design of a mutually exclusive chevron and control (what would be action-end) has proven to be functional or at least non-problematic.

**Comment by macandcheese** [comment]
I am not sure lack of logged user problems justifies not evaluating components for improvement. That said, it would obviously be good to test the proposed change against those cases and see if it is more trouble than its worth, or if there is an escape hatch, but the functionality / ui is inconsistent currently.

**Comment by macandcheese** [comment]
Closing in favor of #4935
