### ISSUE TITLE
comboBoxItem.toggleSelected() triggers an event

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-design-system#5278]
### Actual Behavior

When calling [toggleSelected()](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-methods-toggleSelected), the `calciteComboboxChange` event is emitted.

### Expected Behavior

When calling [toggleSelected()](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-methods-toggleSelected), the `calciteComboboxChange` event **should not be** emitted, per [the documentation](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-methods-toggleSelected):

> <html>
<body>

Name | Description | Signature | Returns
-- | -- | -- | --
toggleSelected | Used to toggle the selection state. **By default this won't trigger an event**. The first argument allows the value to be coerced, rather than swapping values. | toggleSelected(coerce?: boolean) => Promise<void> | Promise<void>

</body>
</html>

### Reproduction Sample

https://codepen.io/gavinr/pen/abGvxGd?editors=0010

### Reproduction Steps

1. Open the codepen https://codepen.io/gavinr/pen/abGvxGd?editors=0010
2. Open the developer tools
3. Click "Select an item in the combobox programmatically" button
4. Expected: no event is emitted (no console.log() shown in developer tools)
    - Actual: event is emitted (console.log() shown in developer tools)

### Reproduction Version

1.0.0-beta.93

**Comment by jcfranco** [comment]
This is no longer applicable as `toggleSelected` was made private before `calcite-components` went out of beta.
