### ISSUE TITLE
Define and adopt a consistent tooltip pattern for all components

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#5319]
### Description

Define a consistent pattern for adding tooltips to components.

Currently, we have some tooltips that are built in and configured by a property. We also have some components that allow slotting a tooltip component.

We should clean up this pattern and define when one vs the other is allowed or if both should always be allowed.

### Acceptance Criteria

A consistent pattern/rule for tooltips in components.

### Relevant Info

https://github.com/Esri/calcite-components/pull/5256#issuecomment-1247015094

### Which Component

All

**Comment by driskull** [comment]
The pattern should cover

- Default tooltips: If and when tooltips should be present by default within a component.
- Turning off default tooltips: If we should be able to disable a tooltip that is present by default.
- Slotting tooltips in place of default tooltips: Overriding a default tooltip with a custom one.

**Comment by geospatialem** [comment]
No tooltip should be used by default. The developer can configure as-needed via a slot for their UI, if needed.
