### ISSUE TITLE
Common resource to store debounce consts

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#5371]
### Background

> Sidebar: maybe we need a common resource to store these types of consts. I think debouncing would follow the same delay.

https://github.com/Esri/calcite-components/pull/4527#discussion_r976809350

It would be nice if we had a location where we all shared common debounce timeouts for usage throughout components.

### Desired Outcome

A utility resource to store debounce timeouts. Potentially similar to the storage of z-index values.

**Comment by DitwanP** [comment]
🍡 Verified
