### ISSUE TITLE
Unstable test: icon

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#5495]
### Test type

e2e

### Which Component(s)

icon

### Unstable Tests

calcite-icon › rendering › loads icon when it's close to viewport

### Test error, if applicable

FAIL src/components/icon/icon.e2e.ts (23.022 s)
  ● calcite-icon › rendering › loads icon when it's close to viewport

    expect(received).toBeTruthy()

    Received: ""

      75 |       await page.waitForChanges();
      76 |
    > 77 |       expect(path.getAttribute("d")).toBeTruthy();
         |                                      ^
      78 |     });
      79 |
      80 |     describe("scales", () => {

      at Object.<anonymous> (src/components/icon/icon.e2e.ts:77:38)
          at runMicrotasks (<anonymous>)

### PR skipped, if applicable

#5491

**Comment by jcfranco** [comment]
This was unskipped in https://github.com/Esri/calcite-design-system/pull/10926.

**Comment by geospatialem** [comment]
Verified on the `dev` branch 👍🏻
