### ISSUE TITLE
Refactor to remove any instances of added hidden prop

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#5548]
### Description

We shouldn't need to add or document this property since it’s already a global attribute common to all HTML elements.

### Proposed Advantages

Remove redundancy. 

### Which Component

Input
Input-number
Input-text

**Comment by jcfranco** [comment]
Stencil v4 allows us to [watch global attributes](https://stenciljs.com/docs/reactive-data#watching-native-html-attributes), so we can leverage this wherever needed.

**Comment by geospatialem** [comment]
Verified in `2.2.1-next.0` with https://codepen.io/geospatialem/pen/OJqmqEm, where the `hidden` attribute is supported as a global attribute.
