### ISSUE TITLE
Shell: Add slots for displaying content at the top/start and bottom/end of the center.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#5668]
### Description

Allow users to place floating content over the top and bottom of the default slotted content center content.

These slots can be called something like `center-start` and `center-end` or something similar. We can eventually deprecate and phase out the `center-row` slot.

Other suggestions:

- `content-start`/`content-end`

### Acceptance Criteria

Ability to place floating content at the top and bottom over the default slotted content.

### Relevant Info

https://community.esri.com/t5/calcite-design-system-questions/align-calcite-panel-to-bottom-of-the-screen/m-p/1227083#M266

### Which Component

calcite-shll

### Example Use Case

```html
<calcite-shell>
  <calcite-panel slot="center-start"></calcite-panel>
  <calcite-panel slot="center-end"></calcite-panel>
</calcite-shell>
```

### Esri team

N/A

**Comment by macandcheese** [comment]
@driskull - Functionality like this is included in the proposal for updated shell / shell panel behavior. cc @asangma @mitc7862

**Comment by macandcheese** [comment]
@bluespider42 would it be possible to attach a screenshot, sketch, or mock-up of what you mean, so we can better understand the request? Thanks!

**Comment by bluespider42** [comment]
![panel](https://user-images.githubusercontent.com/8672628/202496420-00a1f18a-d7b2-4129-94dc-72bd06b25c5e.png)

Sorry, I'm not sure how best to illustrate this. But with the action bar you can have the action at the bottom, as a user I would expect this to open the panel at the bottom left corner.

**Comment by geospatialem** [comment]
Added [additional acceptance criteria and context](https://github.com/Esri/calcite-design-system/issues/1932#issuecomment-1908630791) to the related issue. Closing in favor of the efforts of #1932.
