### ISSUE TITLE
Calcite Input component use with file type

### ISSUE THREAD

**Issue by canadajebus** [Esri/calcite-design-system#5675]
### Description

There is no documentation on how to use the input component when the type is "file".  How do I use the file?  I'm trying to get a simple case working where a csv is added from a local location and use as a layer for a map.

```
// Create the File input
this.urlInput = domConstruct.create("calcite-input",{
  id: "addData_fileInput",
  type: "file",
  calciteInputInput: (event) => {
    console.log(event);
    // const url = URL.createObjectURL(event.target.value);
    const csvLayer = new CSVLayer({
      url: event.target.value
    });
    this.map.add(csvLayer); 
  }
}, this.container);
```

### Which Component

input where type : "file"

**Comment by benelan** [comment]
Hi, I apologize for the delayed response, we've been ramping up for our v1 release. I logged an issue to add the `files` property to Input, but here is a workaround for now: https://codepen.io/benesri/pen/MWXZONP?editors=1011

**Comment by geospatialem** [comment]
Mitigated as part of #5890.
