### ISSUE TITLE
Unable to scroll constrained block content

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#5686]
### Actual Behavior

If the height of a block's content exceeds the height of the block, it's not possible to constrain the content to `100%` of the block and scroll the overflow.

### Expected Behavior

If the height of a block's content exceeds the height of the block, it is possible to constrain the content to `100%` of the block and scroll the overflow.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/BaxOQga

### Reproduction Steps

1. Visit the code sample
2. Try to scroll the first block and see it shows the current behavior where the user is unable to scroll the contents of the block.
3. Try to scroll the second block and see it is patched to show the expected behavior of being able to scroll the contents of the block.

### Reproduction Version

beta.97

### Relevant Info

Related to https://github.com/Esri/calcite-components/issues/5422.

### Impact

Field Maps has a modal layout where a block is used to expand/collapse a preview area. The preview area has a somewhat fixed height (relative to the height of the viewport) but a variable amount of content, so it needs to be scrollable.

The current workaround is to use a custom layout and lose the expand/collapse behavior.

### Esri team

ArcGIS Field Apps

**Comment by jcfranco** [comment]
I believe this is doable w/o any further changes to block. Can you give this a try? https://codepen.io/jcfranco/pen/GRGrVeN

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.36` with https://codepen.io/nwhittaker-esri/pen/BaxOQga

![image](https://github.com/Esri/calcite-design-system/assets/5023024/d6cc4399-ed0d-4e6c-91ea-322f28848387)
