### ISSUE TITLE
Unable to use `dispatchEvent()` on the `dropdown-trigger` to open/close a dropdown

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#5689]
### Actual Behavior

The dropdown does not respond to keyboard events invoked with [`dispatchEvent()`][1] on the `dropdown-trigger` slot.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent

### Expected Behavior

The dropdown does respond to these keyboard events.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/oNyLQwr

### Reproduction Steps

In codepen, dispatched events don't seem to trigger the listeners on custom elements, for some reason. So the code sample may need to be recreated and run locally.

1. Visit the code sample
2. Click the **"Enter" keydown** button and notice the dropdown does not open

### Reproduction Version

beta.97

### Relevant Info

The `keyDownHandler` is bailing early here because `target` is the `dropdown-trigger` element, and `this.referenceEl` is the `.calcite-dropdown-trigger-container` element:

https://github.com/Esri/calcite-components/blob/90e9831bdb8a29e2ce8925ef3464549c1295882b/src/components/dropdown/dropdown.tsx#L554

### Impact

This issue makes it difficult to write tests asserting keyboard events propagate correctly to a dropdown.

### Esri team

ArcGIS Field Apps

**Comment by driskull** [comment]
@nwhittaker why do you need to dispatch the event? Can you just set the dropdown to `open`?

**Comment by nwhittaker** [comment]
I'm dispatching the event in a test because I'm interested in asserting the event made it to the dropdown. Specifically, I have a dropdown inside a tree-item. In this scenario, if the dropdown is focused, keyboard events appear to have no effect or are consumed by the tree-item, unless their propagation is stopped.

If it's a high level of effort to fix, I could add my own handlers, but it seemed reasonable enough to expect the `open` property to have been toggled when dispatching the event on the trigger.

**Comment by driskull** [comment]
Yeah this is tricky because the event listener is in the shadowRoot. To fix this, I think we would need to setup a composed event or refactor the dropdown to use a referenceElement approach.

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.2` with https://codepen.io/geospatialem/pen/YzdExqq

```html
<p>Simulate event on the trigger:
  <button type="button" onclick="keydown('Enter');">"Enter" keydown</button>
</p>

<calcite-dropdown>
  <calcite-button id="trigger" slot="trigger">Open dropdown</calcite-button>
  <calcite-dropdown-group selection-mode="single" group-title="Selection Mode: Single">
    <calcite-dropdown-item>Relevance</calcite-dropdown-item>
    <calcite-dropdown-item selected>Date modified</calcite-dropdown-item>
    <calcite-dropdown-item>Title</calcite-dropdown-item>
  </calcite-dropdown-group>
  <calcite-dropdown-group selection-mode="multi" group-title="Selection Mode: Multi">
    <calcite-dropdown-item selected>Maps</calcite-dropdown-item>
    <calcite-dropdown-item>Layers</calcite-dropdown-item>
    <calcite-dropdown-item open>Data</calcite-dropdown-item>
  </calcite-dropdown-group>
  <calcite-dropdown-group selection-mode="none" group-title="Selection Mode: None">
    <calcite-dropdown-item>Mountain</calcite-dropdown-item>
    <calcite-dropdown-item>River</calcite-dropdown-item>
  </calcite-dropdown-group>
</calcite-dropdown>

<script>
function keydown(key) {
  const triggerEl = document.getElementById("trigger");
  triggerEl.dispatchEvent(new KeyboardEvent("keydown", { key: key, bubbles: true }));
}
</script>
```
