### ISSUE TITLE
Tooltips no longer move along x/y axis when transitioning to the `open` state for the first time

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#5697]
### Actual Behavior

The first time a tooltip's reference element is hovered, the tooltip appears abruptly in place. Subsequent hoverings of the reference element show a smoother transition of the tooltip from hidden to visible along the x or y axis (depending on how the tooltip is positioned relative to the reference element).

### Expected Behavior

The tooltip transitions in smoothly along the x or y axis the first time its reference element is hovered.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/ExRNKoZ

### Reproduction Steps

1. Visit the code sample
2. Hover the text and note the tooltip appears in place (it may help to slow down animations in devtools)
3. Hover the text again and note the tooltip now transitions along the x or y axis when showing/hiding.

### Reproduction Version

beta.97

### Regression?

next.606

### Impact

For performance reasons, Field Maps generates some tooltips "just in time" when the reference element is hovered. As a result, the way these tooltips visually appear is inconsistent with how other tooltips in the app appear.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Will determine if other floating UI fixes, such as #6520 improve this bug.

**Comment by driskull** [comment]
@nwhittaker is this issue still present in the latest release?

**Comment by nwhittaker** [comment]
@driskull, I updated the pen in the description to 1.7.0 and still see the originally observed behavior.

**Comment by driskull** [comment]
Thanks for confirming!

**Comment by jcfranco** [comment]
This should be fixed now via https://github.com/Esri/calcite-design-system/pull/8001 (see [updated repro case](https://codepen.io/jcfranco/pen/yLZZgBP)).

@nwhittaker Can you confirm?

**Comment by nwhittaker** [comment]
I updated a [fork of the repro][1] to `2.0.0` and the issue looks resolved to me. Thanks!

[1]: https://codepen.io/nwhittaker-esri/pen/ExrrpgO

**Comment by geospatialem** [comment]
Verified per Nate's comment [above](https://github.com/Esri/calcite-design-system/issues/5697#issuecomment-1845567472).

**Comment by driskull** [comment]
Reopened issue and added triage label. see #8409 for reasoning.

**Comment by geospatialem** [comment]
Spike to explore the transitions of the `tooltip` upon opening as it relates to overall performance of the component. 

With the intent to focus on a future milestone in mid/late 2024 at the earliest if a solution is reached.

**Comment by driskull** [comment]
@geospatialem I tried a few things and couldn't figure out a way to get this animation to work correctly the first time. Maybe someone else wants to take a shot at it?

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.4`

Before (First hover):

https://github.com/user-attachments/assets/3bbd2e14-710e-42f3-a0b7-b5cd40bec0fc


After (First hover): 

https://github.com/user-attachments/assets/5ca5e043-ae35-4315-9d84-deaffd94d849
