### ISSUE TITLE
Add validation and status prop to Input Time Picker

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#5723]
### Description

Since the status is deprecated on the label component, there is no built-in way to give a visual indication of the status for `input-time-picker`.

### Acceptance Criteria

Add a `status` property to `input-time-picker` that behaves like other input components that implement this property.

### Which Component

`input-time-picker`

### Esri team

ArcGIS Business/Community Analyst

**Comment by jcfranco** [comment]
Linked to validation epic. cc @geospatialem

**Comment by geospatialem** [comment]
Refer to the [Figma file](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=956-94284&mode=design&t=tPqHJcVdxmJmZ6L2-0) for more information:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/f304162f-1363-4e39-b49c-b6321fb4001d)

**Comment by geospatialem** [comment]
Closing in favor of the efforts completed in https://github.com/Esri/calcite-design-system/issues/8057, where the status property was added, along with an internal input-message for displaying validation messages.

Additional efforts will be completed in https://github.com/Esri/calcite-design-system/issues/8000 for setting the validity state of the component internally.
