### ISSUE TITLE
Tab Nav loses underline after rebuilding

### ISSUE THREAD

**Issue by avkolomeets** [Esri/calcite-design-system#5751]
### Actual Behavior

We create `calcite-tab-nav` and then add items to it programmatically. As a result, the first time it works fine, but after re-populating again, the selection (underline) is not shown.

### Expected Behavior

Selected tab must be underlined.

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/rNKwXXp?editors=100

### Reproduction Steps

See the sample above.

(1) Click the "Rebuild" button once. It works fine.
(2) Click the button again, the underline is not shown.

![image](https://user-images.githubusercontent.com/5318527/201817398-0c73a5d3-d829-4d1a-ac9e-cee4a0b99cef.png)

### Reproduction Version

beta.98

### Esri team

ArcGIS Business/Community Analyst

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-design-system/issues/8800 might take care of this one. Blocking.

**Comment by jcfranco** [comment]
Confirmed this was addressed by #8800 (see [updated repro case](https://codepen.io/jcfranco/pen/QWXdpOE?editors=1000)). cc @geospatialem @DitwanP

**Comment by geospatialem** [comment]
Verified in Franco's updated repro case (_[above](https://github.com/Esri/calcite-design-system/issues/5751#issuecomment-2257197665)_). 🎉
