### ISSUE TITLE
Provide default slot for Value List Item

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-design-system#5775]
### Description

Right now there is no way to place custom content in the value list item instead of the label.
We could like the ability to place some custom content, such as images, not only plain text.

### Acceptance Criteria

Provide `default` slot.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/value-list-item/

### Example Use Case

See how we use the value list right now. We have to hack it by placing the content inside the shadow root.

![image](https://user-images.githubusercontent.com/5318527/202444359-0e629862-d65e-4958-a3f1-24e44f8f5cc9.png)

### Esri team

ArcGIS Business/Community Analyst

**Comment by geospatialem** [comment]
@cont-kolomeets The above is now supported with the updated `list` and child components where default slots, and `content-start`, `actions-start`, `content-end` and `actions-end` slots are supported, similar to this sample: https://codepen.io/geospatialem/pen/WNPVYgV


![image](https://github.com/Esri/calcite-design-system/assets/5023024/215ad487-f735-4e8c-96c7-ef77d9b48ef2)


Closing per the support mentioned above, but reach out if this doesn't fit the use case described above.
