### ISSUE TITLE
Refactor screenshot test-only stories (containing `_TestOnly` suffix) to remove legacy knobs

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#5779]
### Description

Scan all component stories to refactor `_TestOnly` cases to remove knobs. Eg. a number of `darkThemeRTL_TestOnly`, some locale tests in `input-time-picker`, and others have legacy knobs. 

Looks like in an effort to lower our snapshot count we excluded unnecessary stories by converting them to test-only, but they haven't been refactored yet to follow the documentation https://github.com/Esri/calcite-components/blob/master/conventions/Documentation.md#screenshot-test-only-stories.

Some might also need to be trimmed down to the minimal HTML needed to reproduce the test scenario.

### Proposed Advantages

Clean-up unused code. 

### Which Component

All components.

**Comment by DitwanP** [comment]
🍡 Verified
