### ISSUE TITLE
Enhance indicator positioning with a wide `calcite-action`

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-design-system#5860]
### Description

The positioning of the indicator looks a bit weird when the action is wide:
![image](https://user-images.githubusercontent.com/52869490/204918346-dc0dfc79-569b-4603-93bb-fdf273d48924.png)

It would be nice if no matter what the width of the action, the indicator would show in the bottom right of the icon.

### Acceptance Criteria

The indicator is in the bottom right of the icon on a calcite-action without text enabled, regardless of action width.

### Relevant Info

From @macandcheese:

> Right now it’s just absolutely positioned to the action component entire container, when text-enabled is not true maybe it could 
> be absolutely positioned to the icon container

### Which Component

calcite-action

### Example Use Case

https://codepen.io/eborgen/pen/RwJYExY?editors=100

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Added an issue creation priority label of `p3 - want for upcoming milestone`, which weren't available at the time of issue creation.

**Comment by macandcheese** [comment]
This will be fixed in https://github.com/Esri/calcite-design-system/issues/6879 and is expected to land for the next release.
