### ISSUE TITLE
calcite-input type="file" 'Choose File' button should use calcite-button

### ISSUE THREAD

**Issue by bluespider42** [Esri/calcite-design-system#5888]
### Description

The input `<calcite-input type="file"></calcite-input>` renders the default file chooser.  
I think it should at least use a `<calcite-button>` button for the "Choose File" button to match the rest of the UI.

### Acceptance Criteria

Change file widget to match the rest of the UI

### Which Component

input type="file"

### Esri team

N/A

**Comment by macandcheese** [comment]
Implementer note: This should be part of a larger design task for a custom file upload input type - single / multiple. It's notoriously hard / impossible to make consistent styling changes to the browser default file upload UI. Hub Components has an example of this, I think it's a good candidate for inclusion in Calcite Componnets.

**Comment by geospatialem** [comment]
While the action is supported as part of `calcite-input`, Calcite cannot add a `calcite-button` due to limitations of the property use from native html.

**Comment by macandcheese** [comment]
Better support for this UI will be included here: https://github.com/Esri/calcite-design-system/issues/6545
