### ISSUE TITLE
calcite-split-button:  click events dont seem to fire

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-design-system#5902]
### Actual Behavior

The 2 events `onCalciteSplitButtonPrimaryClick` and `onCalciteSplitButtonSecondaryClick` dont seem to fire when they are clicked

### Expected Behavior

The 2 events `onCalciteSplitButtonPrimaryClick` and `onCalciteSplitButtonSecondaryClick` should be triggered

### Reproduction Sample

https://codepen.io/kevindoshier/pen/abKPGMZ

### Reproduction Steps

1. Use example linked above
2. Click the various links

### Reproduction Version

1.0.0-next.654

### Regression?

beta.98

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Hey @kevindoshier, outside of frameworks, [JavaScript would be needed to execute the events](https://codepen.io/geospatialem/pen/eYKxJGo), such as:

```js
const splitBtn = document.querySelector("calcite-split-button");
splitBtn.addEventListener("calciteSplitButtonPrimaryClick", () => console.log("Primary click"));
splitBtn.addEventListener("calciteSplitButtonSecondaryClick",() => console.log("Secondary click"));
```

In React `onCalciteSplitButtonPrimaryClick` and `onCalciteSplitButtonSecondaryClick` should be performing as-expected. Although there was a workaround for some [Vue versions](https://community.esri.com/t5/calcite-design-system-questions/event-handler-directive-not-support-for-components/td-p/1214503).

**Comment by driskull** [comment]
@kevindoshier for now, can you listen for the `calciteDropdownSelect` on the split button?

```
 splitBtn.addEventListener("calciteDropdownSelect",() => console.log("Secondary click"));  
```

@geospatialem we may need to add an event for this.

I think Franco and I discussed actually removing these two click events on the split button since they aren't really useful. Ideally, a user would just listen to events on the slotted button and slotted dropdown. In this case, the dropdown is actually in shadowRoot so we either need to create a new event or refactor split button so a user slots the whole dropdown and not just a group. @eriklharper @macandcheese @benelan  thoughts?

**Comment by kevindoshier** [comment]
@driskull - yep that works, thank you

**Comment by geospatialem** [comment]
We've opened an issue above to expose an event on the `calcite-dropdown-item` component to be incorporated into next month's release.

Additionally, will evaluate the pattern for the `calcite-split-button` after next month's release to determine next steps.

**Comment by kevindoshier** [comment]
I noticed with the latest `.next` version, event.detail was removed, but now im not sure how to get the selected dropdown item from the split-button

**Comment by driskull** [comment]
@kevindoshier you can listen for the event `calciteDropdownItemSelect` on a dropdown-item or any parent element as it will bubble up.

**Comment by kevindoshier** [comment]
@driskull - cool thanks, I was missing that

**Comment by geospatialem** [comment]
> @geospatialem can we add more doc on this in the changelog?

@driskull The `calciteDropdownItemSelect` was [added as a feature](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#features) (located below the breaking changes) in the changelog. Will add a note to the `dropdown` component breaking changes and add additional context to the `dropdown-item` feature, but we don't have anything comparable to the `split-button` component to add to. ☹️

**Comment by driskull** [comment]
@geospatialem yeah that's fine. Lets just add a note about the feature added in the breaking change.

**Comment by geospatialem** [comment]
Spike to consider options available, to determine the type of event to be introduced.

**Comment by geospatialem** [comment]
WRT the above, it looks like the dropdown-item context can be provided with the `calciteDropdownItemSelect` event added via https://github.com/Esri/calcite-design-system/issues/5940.

Here's a [Codepen sample in 2.0.0](https://codepen.io/geospatialem/pen/vYbobBE) showcasing the functionality, also depicted below:

```js
document.querySelector("calcite-split-button").addEventListener("calciteDropdownItemSelect", (e) => console.log(e.target.label));
```
