### ISSUE TITLE
[ Tile / Tile Select / Tile Select Group ] Tile and its content position

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-design-system#5937]
### Description

Some feature requests to match up with AGO design

### Acceptance Criteria

* Add scale for layer icon. Right now it's hardcoded to `l` (I think this is the same as https://github.com/Esri/calcite-components/issues/4759)
* Allow tile's content heading to be on the same line as tile's icon

### Which Component

Tile / Tile Select / Tile Select Group

### Esri team

ArcGIS Online

**Comment by SkyeSeitz** [comment]
Thank you for your patience on this one, @ptmdmusique. Similar to [7215](https://github.com/Esri/calcite-design-system/issues/7215), there are currently no plans to add an inline icon to Tile/Tile Select as the List or Radio Button Group component provide this layout. See [this codepen ](https://codepen.io/ashetland/pen/bGOvaBp?editors=1000)demonstrating how to use their slots for inline icons. 

Re: icon scale, we plan to add an **image slot** to the Tile Design enhancements tracked [here](https://github.com/Esri/calcite-design-system/issues/6662), which will allow you to slot any size icon or alternative image to the start of a Tile. 

Closing this particular issue out in favor of existing Calcite components mentioned above and issues in the 6662 Epic.
