### ISSUE TITLE
fix(alert): `auto-dismissable` pauses timer while there is a focus on an element inside `alert` component

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#5960]
### Description

Follow-up fix to #5872

While the timer pauses when hovering over, it's not pausing when the focus is inside the alert and the cursor is not. For instance, if a slotted `calcite-link` has `focus`, the timer should pause as well. 

Also small refactors to rename private handle events for `onPointerOut` and `onPointerOver` handlers and corresponding tests. 

### Acceptance Criteria

`auto-dismissable` pauses timer while there is a focus on an element inside `alert` component

### Which Component

alert

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `2.9.1-next.3`:

![verify](https://github.com/Esri/calcite-design-system/assets/5023024/31fe5759-f8ac-4fab-b978-7842ba3367eb)
