### ISSUE TITLE
[Modal] a prop to stop modal from focusing on the first focusable in content

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-design-system#5971]
### Description

It would be nice if there was a prop I can pass in to prevent the modal from auto focusing on the first focusable element in the content and instead focus on the close button of the modal.  

The current default behavior that auto focuses the first focusable element in content can cause the content body to auto scroll all the way down if the focusable element is at the bottom and there's a bunch of content above it that causes the scrollbar to appear.

### Acceptance Criteria

Allow passing a prop to tell `calcite-modal` to always auto focuses the close button even if there are focusable elements in the content.

### Which Component

calcite-modal

### Example Use Case

Codepen sample
https://codepen.io/rpanichakit/pen/mdKgOGp?editors=100

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
This has been incorporated as part of a previous release, @rpanichakit9541 can you verify [this updated `modal` sample in`2.0.0`](https://codepen.io/geospatialem/pen/WNPVLLp) is the expected behavior?

**Comment by rpanichakit9541** [comment]
Looks good to me! Thank you.
