### ISSUE TITLE
Color Picker: Number greater than 255 changes back to latn from other numbering systems

### ISSUE THREAD

**Issue by annierm18** [Esri/calcite-design-system#5978]
### Actual Behavior

When a number greater than 255 is entered in the RGB fields, the numbering systems changes from that specified in the numbering system attribute to latn.

![Screenshot (107)](https://user-images.githubusercontent.com/25759835/206819798-597d25d0-b96c-4112-a519-d24a3b25ef7e.png)

### Expected Behavior

I expect the number to remain in the numbering system that I specified using the numbering-system attribute and not change to latn.

### Reproduction Sample

https://codepen.io/ainermfc/pen/JjZVJdN?editors=100

### Reproduction Steps

1. Open a codepen for color picker
2. Set numbering-system to a numbering system other than latn, like "arab"
3. Click in either the R, G, or B input
4. Type in two numbers

### Reproduction Version

beta.97

### Esri team

N/A

**Comment by jcfranco** [comment]
The culprit lies in the channel input's clamping logic: https://github.com/Esri/calcite-components/blob/master/src/components/color-picker/color-picker.tsx#L366-L391. Need to take a closer look.

**Comment by geospatialem** [comment]
Re-allocating to the upcoming March milestone.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.25`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/7250212f-4300-43fe-a601-f10f1c658fbc)
