### ISSUE TITLE
Need events for Accordion

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-design-system#5985]
### Description

Right now Accordion emits no events. There is no way to know if an item was expanded by the user.

### Acceptance Criteria

Accordion must emit `expandedStateChanged` event or something like this.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/accordion/

### Example Use Case

Need to track which item is currently expanded by the user. Is there a workaround for now?
If found that listening to `click` event on `accordion-item` does the trick, I just check if event.target === item itself.

### Esri team

ArcGIS Business/Community Analyst

**Comment by macandcheese** [comment]
it might also be worth adding a read-only prop for expanded items similar to Dropdown: https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-selectedItems

**Comment by jcfranco** [comment]
Closing as duplicate of https://github.com/Esri/calcite-design-system/issues/4531.
