### ISSUE TITLE
Refactor all `OpenCloseComponent`s with the new pattern where `onToggleOpenCloseComponent` replaces `connect` logic

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#6018]
### Description

- Implement `OpenCloseComponent` interface on all relevant components.
- Use the new pattern where `onToggleOpenCloseComponent` replaces both `connectOpenCloseComponent` and `disconnectOpenCloseComponent`.
- ~Once implemented on all components, clean up the util to remove the connect pattern helpers in favor of `onToggleOpenCloseComponent` helper.~

### Proposed Advantages

Consistency across relevant components and less functions to import into each component from the util. This new pattern simplifies the overall logic. 

### Which Component

All components and the util itself.

- [x] alert
- [x] dropdown
- [x] tooltip
- [x] popover
- [x] input-date-picker
- [x] combobox

**Comment by geospatialem** [comment]
The top two bullet points have been verified on the `main` branch. ✨ 

The last bulletpoint was edited as it is not part of the effort. Instead future refactoring will be taking place via https://github.com/Esri/calcite-design-system/issues/6017, https://github.com/Esri/calcite-design-system/issues/4398, https://github.com/Esri/calcite-design-system/issues/5056, and https://github.com/Esri/calcite-design-system/issues/5074, with the following priorities:
1. Apply utility across all components
2. Refactor the utility
3. Incorporate a test utility
