### ISSUE TITLE
CalciteButton: aria-expanded not being read by screenreader

### ISSUE THREAD

**Issue by phenderson00** [Esri/calcite-design-system#6033]
### Summary

Screenreader does not indicate to user that button is expandable despite aria-expanded being properly set on the `calcite-button` component.

### Actual Behavior

We are using a `calcite-popover` with a `calcite-button` as its reference element. When the button gets focus, the button label and "button" are read by the screenreader but "expandable" is not read aloud. I can see in the Dev Tools that the aria-expanded state is being correctly updated on the button.

### Expected Behavior

The expectation is that after reading the button label and "button", the screenreader will read "expandable" (or something to that effect) to indicate to the user that clicking the button will reveal more content, a `calcite-popover` in this case.

### Reproduction Sample

https://codesandbox.io/s/calcite-button-aria-expanded-not-read-by-screenreader-oh4y6s?file=/src/App.js

### Reproduction Steps

1. Turn on screenreader
2. Tab until focus arrives at button
3. Hear "Any age groups, button" be read

### Reproduction Version

0.35.0

### Relevant Info

Windows 10, Chrome 108.0.5359.99, Narrator, JAWS

### Esri team

Professional Services - Midwest Delivery Center

**Comment by brittneytewks** [comment]
Removed "needs triage" since a priority is set and estimate is indicated

**Comment by geospatialem** [comment]
@phenderson00 Thanks for re pining this! This request seems to be more in line of an enhancement, but in line with the native `button` functionality.

We'll take a look at an upcoming milestone to determine next steps.

Some findings below during triage/next steps:
- The native `button` functionality will announce "expand" or "collapse" to AT when `aria-expanded` is toggled and coupled with an `aria-controls` attribute associated with the content's `id`.
- A [Codepen sample](https://codepen.io/geospatialem/pen/gOBOBRK) for context

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.16` with JAWS and NVDA in https://codepen.io/geospatialem/pen/xxmagmG
