### ISSUE TITLE
Refactor `getElementProp` across child components as an outdated pattern.

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#6038]
### Description

Refactor `getElementProp` across child components as an outdated pattern.

Parents should be setting props on the child if it’s a tightly coupled component pair. With this current pattern if the parent prop changes the child doesn't know about the changes to the parent.

For all relevant components props are passed down and children no longer look up for the prop. To achieve this the parent gets a mutation observer to modify children where necessary.

### Proposed Advantages

- Bring consistency to child styling, where there is a tightly coupled component pair. 
- Children are in sync with parent props.
- Independent components retain autonomy, eg. a large-scale modal with small-scale child components.

### Which Component

All coupled components: where the child shares their parent’s name, like `list/list-item, flow/flow-item, combobox/combobox-item`.

- [x] accordion-item
    - [x] `iconType`
    - [x] `iconPosition`
    - [x] `scale`
    - [x] `selectionMode`
- [x] combobox-item
    - [x] `scale`
    - [x] `selectionMode`
- [x] combobox-item-group
   - [x] `scale`
- [x] dropdown-group
    - [x] `scale`
- [x] dropdown-item
    - [x] `scale`
    - [x] `selectionMode`
- [x] segmented-control-item
    - [x] `scale`
    - [x] `appearance`
    - [x] `layout`
- [x] stepper-item
    - [x] `icon`
    - [x] `numbered`
    - [x] `layout`
    - [x] `scale`
- [ ] tab-title
    - [x] `position`
    - [x] `scale`

**Comment by eriklharper** [comment]
Prior art: https://github.com/Esri/calcite-components/blob/master/src/components/radio-button-group/radio-button-group.tsx#L106-L117

**Comment by geospatialem** [comment]
Verified in the `main` branch. 🎉
