### ISSUE TITLE
Expand-Toggle: Rename `intl*` properties

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#6043]
### Description

Currently, `<Expand-Toggle/>` uses ` intlExpand` & `  intlCollapse` properties to add accessible names to the action node. As part of 1.0 we removed `intl` prefixed props. To keep it consistent with the coding conventions, these props need to be renamed with descriptive names.

### Proposed Advantages

Keeps the code consistent across the repo

### Which Component

Exapnd-Toggle

### Relevant Info

Post 1.0 as the component is `internal`

**Comment by jcfranco** [comment]
This was addressed in https://github.com/Esri/calcite-design-system/pull/7352. Closing!
