### ISSUE TITLE
Audit components to remove `getSlotted` util instances

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6059]
### Description

Many components use `getSlotted` and will need to be refactored in favor of a new pattern.

### Proposed Advantages

The `getSlotted` util is no longer a recommended pattern - `onSlotChange` is preferred. 

### Which Component

**Note: prioritize `card` effort in the initial stages first, if at all possible -- related issue: https://github.com/Esri/calcite-design-system/issues/10152**

- [x] `accordion-item` #10447
- [x] `action-bar`
- [x] `action-group`
- [x] `action-pad`
- [x] `alert` #10448
- [x] `block` #10449
- [x] `card` ❗  - prioritize in October 2024
- [x] `combobox-item` #10450
- [x] `inline-editable` #10456
- [x] `input` #10458
- [x] `input-number` #10458
- [x] `input-text` #10458
- [x] ~`modal`~ (deprecated) #10469
- [x] `notice` #10453
- [x] ~`pick-list-group`~ (deprecated)
- [x] ~`pick-list-item`~ (deprecated)
- [x] `shell`
- [x] `shell-center-row` #10451
- [x] `shell-panel`
- [x] `table`
- [x] `tile`
- [x] `tile-group`
- [x] ~`tip`~ (deprecated) #10470
- [x] `tree-item` #10462
- [x] ~`value-list-item`~ (deprecated)

### Relevant Info

cc @driskull

**Comment by driskull** [comment]
This one would be nice to get onto a milestone sometime in the next year.

**Comment by rweber-esri** [comment]
See my [comment](https://github.com/Esri/calcite-design-system/issues/10152#issuecomment-2368479741) on [10152](https://github.com/Esri/calcite-design-system/issues/10152). Hub is observing slotted content not working in `calcite-card` even when we _immediately_ slot the content into the component during initial component render on `2.12.1`. This is observed when rendering `calcite-card` from other Stencil components (JSX) Hub internally develops/maintains that are lazy loaded (may play a factor) in our Ember application. Not sure if that influences priority, but we seem to be unable to reliably slot certain content in `calcite-card` at this time.

**Comment by driskull** [comment]
@geospatialem @DitwanP besides `card` which are next highest priority? Should we prioritize this list for future implementation?

**Comment by jcfranco** [comment]
@driskull's been crushing it with this audit! Some of the associated PRs are fixes, so we might need to adjust this issue to accommodate for testing and verification. cc @geospatialem @DitwanP

**Comment by driskull** [comment]
Should we update `modal` since it will be around till v4?

**Comment by DitwanP** [comment]
🍠✨ Verified. The e2e and screenshot tests does indeed provide good coverage for this! 💪

**Comment by jcfranco** [comment]
Agreed. We can also keep an eye out for anything our testing may have missed. For context, the fix-side on the related PRs addresses the point from [this PR](https://github.com/Esri/calcite-design-system/pull/5380):

> The conditionalSlot utility class will not work if ComponentA slots into a slot in ComponentB.
