### ISSUE TITLE
Accordion icon-position can only be set as an attribute

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-design-system#6199]
### Actual Behavior

If you set `accordionEl.iconPosition = "start"` the icons of the children accordion items will still appear at the end of the accordion. 

However, if you use `accordionEl.setAttribute("icon-position", "start")` or just set it with kebab case in the DOM, it works great. 

### Expected Behavior

All props should function using either attributes or... props. We generally prefer using the camel case versions as you get much better type hinting for the values. 

### Reproduction Sample

https://codepen.io/paulcp/pen/VwBaPEd?editors=0010

### Reproduction Steps

1. look at the icon position (will be at the end)
2. now change the code to use the attribute version
3. notice the icon moves to the start

### Reproduction Version

All

### Esri team

ArcGIS Online

**Comment by driskull** [comment]
Yeah, this is another reason to refactor using the `getElementProp` util.

**Comment by geospatialem** [comment]
Work should be conducted prior to https://github.com/Esri/calcite-components/issues/6038.

**Comment by geospatialem** [comment]
Reallocating to the July milestone.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.26`
