### ISSUE TITLE
Documenting conventions for the coupled parent-child relationship.

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#6200]
### Description

Parents should be setting props on the child if it’s a tightly coupled component pair.  We don’t want people setting them individually. We’d have inconsistencies with different scales for example, which might not be intended. The logic to achieve this is outlined in #6038.

Not applicable for independent components, where it makes sense for the child to have autonomy, eg. a large modal with smaller child components. These children of course need to retain their scale.

Define what a coupled parent-child is and what isn’t:
Tightly coupled components will be required to have the child share their parent’s name, like `list/list-item`, `flow/flow-item`, `combobox/combobox-item`.

Questions:
Does this apply to all props on all coupled children? Do we just refactor all at once or go case by case?

To do:
Children’s props should be refactored to not be public (remove `@Prop` decorator). 
Undocument these new internal props, so it’s clear the user shouldn’t be setting these. 
Keep defaults for children’s internal props that are controlled by parents.
Don’t reflect, as this would expose them. 
This means that CSS classes need to be updated to use classes instead of attributes.

Once we decide the rules and document the convention in a markdown then we can spin up an epic issue.

### Which Component

All

**Comment by geospatialem** [comment]
The milestone should be associated with https://github.com/Esri/calcite-components/issues/6038 as the two are related and should be addressed together.

**Comment by Elijbet** [comment]
Closing, as it is now combined with #6038.

**Comment by Elijbet** [comment]
Closing, as it is now combined with https://github.com/Esri/calcite-design-system/issues/6038.
