### ISSUE TITLE
[calcite-slider] The snapping mode does not honor the min setting

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#6229]
### Actual Behavior

1. The `min` value is not honored in snap mode, the snap value is not correct. e.g. I cannot snap to 1,3,5,7,9 with min=1 step=2
![image](https://user-images.githubusercontent.com/26078106/210548255-d0d0e412-f686-4b8a-bf21-0fb76432d747.png)

2. The value will be toFixed according to the decimal places of step, but when I have decimal min value and integer step value, the min value cannot be snapped even if the above issue is fixed

3. When the max value does not meet the step setting, it can be snapped sometimes when the calculation rounds up
![image](https://user-images.githubusercontent.com/26078106/210548654-d9fd9a5c-4fc5-4e35-8ae8-c0c47f50d8dd.png)

### Expected Behavior

1. The snapped function should consider min value
2. The snapped function should also consider the decimal places of the min value
3. The max value should not be snapped if it does not meet step setting

### Reproduction Sample

https://codepen.io/fendiaoxiaoshuazi/pen/zYLKEXb?editors=1000

### Reproduction Steps

1. Try sample 1, you cannot scroll to 1,3,5,7,9
2. When the first issue is fixed, the 1.5 min value cannot be reached
3. The max 10.5 can be snapped but this is not correct

### Reproduction Version

beta.97

### Esri team

N/A

**Comment by jcfranco** [comment]
This needs to wait for https://github.com/Esri/calcite-design-system/issues/5827 to land first as it's going to introduce some breaking changes to slider, especially ticks and steps. cc @geospatialem @brittneytewks

**Comment by fendiaoxiaoshuazi** [comment]
Any update on this issue?

**Comment by jcfranco** [comment]
@fendiaoxiaoshuazi ICYMI, this should be fixed in our upcoming release. ✨🎚️✨

**Comment by DitwanP** [comment]
🍯 Verified on `2.8.0-next.0`
