### ISSUE TITLE
[calcite-dropdown]: max-height of calcite-dropdown-content not set if max-items = total items

### ISSUE THREAD

**Issue by juliannemarik** [Esri/calcite-design-system#6230]
### Actual Behavior

If the `max-items` passed into the `calcite-dropdown` equals the total number of `calcite-drodown-item`s in the dropdown, then the `max-height` of the `calcite-dropdown` is not set and it falls back to the default height. 

### Expected Behavior

The maximum number of `calcite-dropdown-item`s (as specified by `max-items`) should be displayed before showing a scroller. This currently works in all cases except for when `max-items` = `calcite-dropdown-item`s.

I _believe_ the issue is [here](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/dropdown/dropdown.tsx#L635) and that this should be: 
```tsx
return items.length >= maxItems ? maxScrollerHeight : 0;
``` 

But I'm not sure if this has other impacts. 

### Reproduction Sample

https://codepen.io/juliannemarik/pen/poZEbNq

### Reproduction Steps

1. Open the codepen example
2. Notice that the dropdown doesn't show all 10 items without scrolling even though `max-items` is specified as 10 on line 10
3. Change `max-items` to 9 and observe that it _does_ respect this value. It only doesn't work for 10

### Reproduction Version

beta.99

### Impact

We currently have a workaround for this bug right where we basically add an empty `calcite-dropdown-item` to the dropdown. We hide this empty `calcite-dropdown-item` and it allows us to show all dropdown items before scrolling. This isn't ideal, but it works for now. 

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
Verified on `3.0.0-next.71` with the original repro and our sample playground example

![image](https://github.com/user-attachments/assets/0f2e3dd6-1acc-4b5b-8683-765197fcf4f9)

![image](https://github.com/user-attachments/assets/1d2284e8-49ee-41a8-b5c3-2bd0ea859276)
