### ISSUE TITLE
Calcite-Combobox > Focus item in dropdown displays gray active dot

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-design-system#6245]
### Description

The calcite combobox dropdown menu displays the currently selected item with a small blue dot (see "Carrot" below). The first item in the dropdown always has focus and is displayed with a blue outline and small gray dot (see "Apple" below).

The small gray dot next to Apple could be confusing to the user. Some users might this is it the default value, or perhaps original value.

![image](https://user-images.githubusercontent.com/2531121/211086873-13afceb5-4f48-4ce1-94d7-a7064732add1.png)

// @adam

### Acceptance Criteria

Refer to the [Figma file](https://www.figma.com/design/c6v9o8y5KgztitlvDudaQy/Interactive-state-audit-%26-improvements?node-id=1-2&t=J8pxiqWOzqfYHpD3-0).

- [ ] Add `foreground.3 bg` on `:pressed`
- [ ] Remove previewed grey dot or checkmark on `combobox-item` `:focus`
- [ ] Do not show gray dot next for focused items in the calcite combobox dropdown.

### Which Component

Combobox 

### Multiple Selection
1. https://developers.arcgis.com/calcite-design-system/components/combobox/
2. Click comboxbox toggle button.
3. Engineering is checked even though not added.

![image](https://user-images.githubusercontent.com/2531121/211087889-59d2776f-cfab-412e-ba93-8f1f3f7cf95d.png)

### Single Selection

1. https://developers.arcgis.com/calcite-design-system/components/combobox/
2. Change selection-mode to "single"
3. Click comboxbox toggle button.
4. Engineering is dotted even though not added.

![image](https://user-images.githubusercontent.com/2531121/211088096-49c9da42-1ce8-41d4-a428-0d9d2c937462.png)

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by macandcheese** [comment]
Thanks for opening @richiecarmichael - @ashetland @SkyeSeitz can we take a look at this?

I agree it may be confusing. Additionally, our behavior between Dropdown and Combobox are different. In Dropdown, hover shows the grey dot, while focus does not. In Combobox, hovering shows no dot, but focusing does. It seems like adopting the Dropdown approach in Combobox could solve potential confusion:

<img src="https://user-images.githubusercontent.com/4733155/211088677-74ee1817-24da-4b7e-b815-1ccca5bd5c89.png" width=600px>
<img src="https://user-images.githubusercontent.com/4733155/211088676-3efe0653-28ab-4210-ada5-d9f435a1ddb9.png" width=600px>


Additionally (may be a separate issue) - Dropdown automatically focuses the first (or only) selected item in the list, Combobox always seems to focus the first item whether there is an existing selection or not. Should we address that as well?

**Comment by DitwanP** [comment]
This is included in a larger epic https://github.com/Esri/calcite-design-system/issues/7733

**Comment by SkyeSeitz** [comment]
Discussed this with Aaron in context of our interaction state audit. I think we can move forward with this issue separately after all before further refinements to Combobox. 

Here is the proposed design to remove the selection icon preview on focused Combobox Items:
<img width="900" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/250ea175-b445-4001-bcca-9843f5d081e2">

**Comment by SkyeSeitz** [comment]
Re: focus order, for Combobox it might make sense to default to focusing the last item selected in order to prioritize keeping selected items in view?

**Comment by geospatialem** [comment]
Verified on `3.0.0-next.51` with all `selectionModes`, for instance `"multiple"`:
![verify-combobox-active](https://github.com/user-attachments/assets/b9622bfa-c5ff-48a5-85a7-3643b440b595)
