### ISSUE TITLE
Can't use TabNav inside Tabs

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-design-system#6255]
### Actual Behavior

When using a stand along TabNav component inside a tab's content, the Tabs component catches its events and switches tabs unexpedely. It works as if I can switch tabs not only from the top TabNav, but using the ones places inside the actual tabs.

![image](https://user-images.githubusercontent.com/5318527/211283698-a7240471-a040-45e6-9ad9-34fc7b4bdb2c.png)

### Expected Behavior

The Tabs component must NOT catch "calciteInternalTabChange" from the tabs' content. To work this around I had to catch this event on the tab's content and stop its propagation.

    on(content, "calciteInternalTabChange", (event) => event.stopPropagation());

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/VwBPqMW?editors=1000

### Reproduction Steps

See the sample. Add a stand-alone TabNav inside a tab.

### Reproduction Version

beta.98

### Esri team

ArcGIS Business/Community Analyst

**Comment by driskull** [comment]
@cont-kolomeets I think a `calcite-tabs` element is just missing in-between the two sets of tabs in order to separate them and their events.

Example: https://codepen.io/driskull/pen/gOQqYow?editors=1000

**Comment by jcfranco** [comment]
@cont-kolomeets Closing based on ☝️ as it is the recommended pattern. Feel free to reach out if you have further questions.

**Comment by cont-kolomeets** [comment]
@jcfranco Sounds good! Thanks!
