### ISSUE TITLE
Tests for the color-picker alpha input box fail

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#6266]
### Test type

unstable tests

### Which Component(s)

color-picker

### Unstable Tests

calcite-color-picker › color inputs › alpha enabled › color gets propagated to support inputs › valid color › allows nudging values

calcite-color-picker › color inputs › alpha enabled › color gets propagated to support inputs › valid color › allows modifying color via hex, RGB, HSV, opacity inputs

calcite-color-picker › color inputs › alpha enabled › color gets propagated to support inputs › when no-color › clearing color via supporting inputs › clears color via opacity input

calcite-color-picker › color inputs › alpha enabled › color gets propagated to support inputs › when no-color › clearing color via supporting inputs › restores previous color value when a nudge key is pressed

calcite-color-picker › color inputs › alpha enabled › color gets propagated to support inputs › when no-color › clearing color via supporting inputs › changes the value to the specified format after being empty

### Test error, if applicable

Protocol error (Input.dispatchKeyEvent): Target closed.

### PR skipped, if applicable

#6265

### Additional Info

color-picker tests are heavily nested with many nested functions. This is making the tests hard to read and may be causing some of the instability.

**Comment by jcfranco** [comment]
Tests were restored in https://github.com/Esri/calcite-design-system/pull/2841/.

Closing!
