### ISSUE TITLE
Tooltip `beforeClose` and `close` events sometimes not emitted

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6279]
### Actual Behavior

If a tooltip is open inside a container when a `display: none` style is set on the container, the tooltip never emits `calciteTooltipBeforeClose` and `calciteTooltipClose` events.

### Expected Behavior

If a tooltip is open inside a container when a `display: none` style is set on the container, the tooltip still emits `calciteTooltipBeforeClose` and `calciteTooltipClose` events.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/bGjRNEW

### Reproduction Steps

1. Visit the sample and open the console.
2. Mouse into the red-bordered box and see the "Hover for Tooltip" text appear.
3. Mouse onto the "Hover for Tooltip" text and wait for the tooltip to open.
4. Quickly mouse out of the red-bordered box and wait a few seconds. Notice that none of the tooltip's close events are logged to the console.

### Reproduction Version

next.721

### Relevant Info

IIRC, `transitionstart` and `transitionend` events don't fire if the element doesn't have display which may explain why the tooltip isn't emitting its close events.

### Impact

For performance reasons, the Field Maps web-app has some logic that remove a tooltip after it closes. In some cases, those tooltips appear alongside buttons that gain/lose display depending on whether a containing element is being hovered.

The current solution is to wait a hard-coded amount of time before removing the tooltip, but waiting for the event would be cleaner and easier to maintain.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Related `modal` issues to `beforeClose` to possibly investigate together: #6407, #6381, #6379

**Comment by geospatialem** [comment]
Verified in the `main` branch.
![verify-tooltip-events](https://github.com/Esri/calcite-design-system/assets/5023024/670e13c1-0adb-47b4-8b88-b2aecc6b3e80)
