### ISSUE TITLE
Make sure the component descriptions in their readmes are done gud

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#6312]
### Description
The component descriptions are used in the VSCode completion I added in #6150, so we should clean them up a bit.

All externally-used components should have a description above the Auto Generated Below comment in their sibling readme.md.
We should make sure the descriptions are up to date (e.g. they don't mention removed props, old patterns, etc.)
Grammar/punctuation/capitalization/tone/verbiage/etc can use some proof reading
As an example, accordion-item's completion description is currently this lol:

https://github.com/Esri/calcite-components/blob/985cc4f5f09f8a81ec4353ae5a4b9ccfcd2f10cf/src/components/accordion-item/readme.md?plain=1#L3

### Which Component
All of the components that people will use. For example components only used internally like color-picker-swatch or date-picker-day can be skipped if necessary.

### Resources
This issue will need some experimenting to figure out what's possible. A few initial questions:

Is everything above the Auto Generated Below comment included in the completion description? Just the first paragraph? First sentence(s)?
Can we include code blocks for examples?
Can we include links to the component's documentation page?
Based on the [standard's readme](https://github.com/microsoft/vscode-custom-data) it sounds like it accepts [HTML customData](https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md) and [CSS customData](https://github.com/microsoft/vscode-css-languageservice/blob/main/docs/customData.md), so we could potentially get fancy with it if Stencil permits us. Not sure how Stencil implemented it on their end or how much leeway they give us to customize the customData.

I think our goal for these should be to help people decide which component to use without providing an overwhelming amount of info. I'm sure a lot of it can be copy pasted from the afd doc.

It would be nice to have one source of truth for component description doc, @macandcheese is there any way to source text from the component readmes in the afd site? That way it could all live in CC. That would align with my goal of using the usage snippets for the doc samples too.

cc @jcfranco since we recently discussed a single source of truth in CC for the doc

One thing to note is that Microsoft leads the way in IDE standards/specs. So other IDEs will likely adopt the customData standard if it gets enough traction.

Some examples of widely used IDE standards that Microsoft created:
[https://microsoft.github.io/language-server-protocol](https://microsoft.github.io/language-server-protocol)
[https://microsoft.github.io/debug-adapter-protocol/](https://microsoft.github.io/debug-adapter-protocol/)

But even if the customData standard dies, it would still be nice to cleanup and setup a single source of truth for our doc.

**Comment by benelan** [comment]
Awesome thanks for the context. Yeah we should have some time to cleanup the usage snippets in CC and setup some parsers in AFD after the v1 craziness dies down.

**Comment by DitwanP** [comment]
After discussion, the plan for this changed to adding a link to the doc site page of each component instead of a description that we would then have to maintain going forward. 

🍡 Verified that every user facing component now has a link to it's doc site page.
