### ISSUE TITLE
Additional navigation methods for pagination element

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6344]
### Description
The pagination element currently only exposes methods for navigating to its previous and next pages. Similarly to what the stepper element offers for [navigation methods](https://developers.arcgis.com/calcite-design-system/components/stepper/#methods), it'd be useful to have more programmatic navigation options.

### Acceptance Criteria
Can programmatically navigate the <calcite-pagination> element to:

1. The first step
1. The last step
1. An arbitrary step
1. The prev/next step (as it currently does)

###  Relevant Info
An immediate use case is that'd it help clean up some unit testing code that needs to navigate to the last page. Currently, we're achieving that by dipping into the pagination element's shadow DOM and clicking buttons.

### Which Component
Pagination

### Example Use Case
No response

### Esri team
ArcGIS Field Apps

**Comment by DitwanP** [comment]
🍡 Verified on `2.8.0-next.10`
https://codepen.io/Ditwan-Price/pen/MWRxjEX?editors=1011
