### ISSUE TITLE
List, List-group, and List-item currently do not have any scale at any level.

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#6353]
### Background
Would like to start a discussion with design to explore if components like List, Panel, etc., should have a scale.
First, let’s assemble the components that fit the description.

Demo of List | List-group | List-item: grouped and nested: https://codepen.io/elijbet/pen/XWBqgqy
Demo of List | List-group | List-item: Rich content: https://codepen.io/elijbet/pen/OJwZmEK

### Desired Outcome
Which group of components should have no scale and why.

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/7100

cc: @sagewall We've added the Maps SDK for JS label to the above issue for tracking.
