### ISSUE TITLE
Split Button - consistent borders and dividers

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#6364]
### Actual Behavior
Recent issues #6332 and #5331 and their related fixes have revealed some additional clean up work on Split Button. See the illustration below:
image

### Expected Behavior
See above illustration. Note that PR #6350 fixed transparent/inverse.

### Reproduction Sample
https://developers.arcgis.com/calcite-design-system/components/split-button/

### Reproduction Steps
Open documentation sample
Change appearance and kind properties to match illustration
Reproduction Version
1.0.3

### Relevant Info
cc: @anveshmekala

### Regression?
No response

### Impact
No response

### Esri team
Calcite (design)

**Comment by ashetland** [comment]
Re-adding missing image referenced above
![image](https://user-images.githubusercontent.com/108549080/232852368-874a8a27-3fc1-4095-9d30-6e8c1efb7440.png)

**Comment by geospatialem** [comment]
Verified on the `main` branch with the [following specs above](https://github.com/Esri/calcite-design-system/issues/6364#issuecomment-1513516565).
