### ISSUE TITLE
[Action] - Remove stale tooltip slot

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6371]
### Description

The Action component still contains code for the now-outdated use case of slotting a tooltip in a “tooltip” slot. There is also stale example code showing this pattern.

### Proposed Advantages
Removing these outdated patterns will clean the component code, and no longer documents an unsupported pattern.

### Which Component
Action

### Relevant Info
From Teams channel feedback cc @jcfranco

**Comment by geospatialem** [comment]
The slot is no longer recommended, the updated code is the following - for future documentation/release summary:

```html
<calcite-action id="action-with-tooltip" text="Layers" icon="layers" text-enabled></calcite-action>
<calcite-tooltip reference-element="action-with-tooltip">
    <span>More information about layers</span>
</calcite-tooltip>
```

**Comment by DitwanP** [comment]
🍡 Verified
