### ISSUE TITLE
[Slider] Unexpected behavior when programmatically updating props

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6375]
### Actual Behavior

When programmatically updating slider, the changes don't accurately reflect in the component:

https://user-images.githubusercontent.com/4733155/215389203-c45ffe12-c1c2-46d4-8921-a9e5cf88e1dc.mov

### Expected Behavior

I'd expect the Slider to accurately reflect the updated property values

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/gOjjjZO?editors=1000

### Reproduction Steps

1. Open Codepen
2. Use the buttons to adjust the Slider component
3. See component not reflect changes correctly.

### Reproduction Version

1.0.3

### Regression?

Could not find a working previous version

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on the `main` branch.
