### ISSUE TITLE
Closing a modal using built-in UI calls `beforeClose` twice

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6379]
### Actual Behavior

Closing a modal via its built-in close button, the `esc` key, or clicking outside the modal invokes the modal's `beforeClose` callback twice.

### Expected Behavior

Closing a modal via its built-in close button, the `esc` key, or clicking outside the modal invokes the modal's `beforeClose` callback once.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/QWBVvYP

### Reproduction Steps

1. Visit the pen and open the console.
2. Close the modal via either its close button, pressing the `esc` key, or clicking outside the modal.
3. Notice `beforeClose` is logged twice.

### Reproduction Version

1.0.3

### Impact

The Field Maps web app has some modal's that need to confirm their closure in cases where data loss could occur. We'd like to use the `beforeClose` callback to do this, but having it called twice in some cases could introduce unintended side-effects.

### Esri team

ArcGIS Field Apps

**Comment by driskull** [comment]
I think this is because the watcher for `open` is calling close as well as the click handler.

**Comment by geospatialem** [comment]
Verified with `1.7.0-next.9`.
