### ISSUE TITLE
`Uncaught (in promise)` error when rejecting modal's `beforeClose()` promise

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6381]
### Actual Behavior

Returning a rejected promise from a modal's `beforeClose()` callback causes an `Uncaught (in promise)` error to be logged in the devtools console.

### Expected Behavior

Returning a rejected promise from a modal's `beforeClose()` callback does not log an error.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/dyjqzqP

### Reproduction Steps

1. Visit the pen and open the browser's dev tools (not CodePen's).
2. Close the modal.
3. See an error is logged to the dev tool's console tab.

### Reproduction Version

1.0.3

### Relevant Info

Stack trace:

```
index.html:1 Uncaught (in promise) undefined
Promise.then (async)
close                            @ p-7cb32fff.entry.js:6
```

### Impact

The modal's `beforeClose()` callback is an affective way to cancel closing a modal if some precondition is not met. For example, the Field Maps web app has some modals that may need to confirm some data loss before closing. If the user ends up not confirming, the modal should not close. This flow is achievable by having the `beforeClose()` callback return a rejected promise.

In this scenario, the rejected promise does not represent an exceptional state. Not catching it introduces a couple problems:
1. Muddies error logging.
2. Can cause automated tests to fail.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.9`
