### ISSUE TITLE
[Loader] Animation buggy on iOS

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6383]
### Actual Behavior

Animation of Loader is buggy on iOS (Safari and Chrome): 

https://user-images.githubusercontent.com/4733155/215604731-64df3324-1c5b-47c9-b7a2-782e70d00047.MP4

### Expected Behavior

I'd expect the loader to animate smoothly.

### Reproduction Sample
https://developers.arcgis.com/calcite-design-system/components/loader/

### Reproduction Steps

A simple loader in isolation in code pen or in the developer site sample displays the issue.

### Reproduction Version

1.0.3

### Relevant Info

I noticed this on my iOS devices. I don't have an Android device to test but would be good to confirm. Can use XCode Simulator to recreate locally.

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
Worth noting that this is also reproducible on OS X (Ventura 13.5, Safari 16.6).

**Comment by geospatialem** [comment]
Verified with iOS 16.6 in Chrome.
