### ISSUE TITLE
[Combobox] Using `space` key while focusing on a Combobox Item advances selection

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6387]
### Actual Behavior

Using the `space` key while focus is on a Combobox Item ("combobox open") advances focus to the next item.

### Expected Behavior

I might expect `space` to behave like `enter` - cc @geospatialem for a11y opinion.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/combobox/

### Reproduction Steps

1. View sample link
2. Open the combobox
3. Use the `space` key
4. See that the focused item "advances" to the next one without selection.

### Reproduction Version

1.0.3

### Regression?

Functioned this way as far back as beta.86, at least.

### Impact

Unsure, but struck me as unexpected.

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
> I might expect `space` to behave like `enter`

Would concur, per the [W3C combobox](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) where `spacebar` and `Enter` keys perform the same action on its items.

Also, of note also applies to the `tab` key, but that might be out of scope for this issue.

**Comment by geospatialem** [comment]
Verified in `1.6.0-next.5`
