### ISSUE TITLE
New Component - Sheet

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6391]
### Description
As proposed, add a new "Sheet" component to our component roster.

### User Stories
Functionally, this should behave similarly to a modal. The sheet should be used for content that is not displayed to a user until it is explicitly invoked. Consider displaying a bottom sheet, edge-of-page drawer, etc.

### Acceptance Criteria
The component should include:

- Page blocking scrim behind the content container.
- 4 placement options for each edge of the screen (default to left?)
- Like modal, dismissal can occur due to user clicking / tapping on scrim.
- Like modal, offer properties to disable outside click.
- By default, covers the entire viewport.
- Alternatively, like Modal, offers a slot within Shell to constrain to the extent of the Shell component.
- When slotted in Shell, extends over header and footer slots. Scrim extends to extent of the Shell component.

### Relevant Info
This differs from the proposed enhancement to add an "overlay" mode to Shell panel in the following ways:

- "overlay" mode of Shell Panel has no blocking scrim.
- "overlay" mode of Shell Panel does not extend past extent of Shell center content area (does not cover header or footer)

Modal has a docked property that could conflate with a "position bottom" sheet. Explore deprecation of the former and guidance for users as to use which, when.

### Helpful Details
The expected child components should be a Panel, or Flow and Flow Item. Developers should control the open state in tandem with the closable / closed state of a Panel, like Shell Panel.

https://developer.apple.com/design/human-interface-guidelines/components/presentation/sheets/

### Esri team
Calcite (design)

**Comment by macandcheese** [comment]
@ashetland lets sync up on Figma spec for this once everyone's schedule calms down a bit.

**Comment by ashetland** [comment]
> @ashetland lets sync up on Figma spec for this once everyone's schedule calms down a bit.

Sounds like a plan.

**Comment by driskull** [comment]
@macandcheese should sheet side placement be flipped in RTL direction?

**Comment by driskull** [comment]
> Alternatively, like Modal, offers a slot within Shell to constrain to the extent of the Shell component.

I think we should have a separate issue that depends on this one to add a slot within the shell component. @macandcheese or @geospatialem do you want to create this follow up issue?

**Comment by macandcheese** [comment]
> @macandcheese should sheet side placement be flipped in RTL direction?

Yep, I think we do this with Alert / Shell Panel slots, etc., with similar names.

> I think we should have a separate issue that depends on this one to add a slot within the shell component.
Opened - https://github.com/Esri/calcite-components/issues/7154

**Comment by driskull** [comment]
@macandcheese does the sheet have a close button or any other UI/slots?

**Comment by macandcheese** [comment]
Nope - accepts a default content slot. The recommendation will be to use a Panel with closable and handle the Sheet in the same way a user handles the Panel closing within a Shell Panel, and provides the behavior of Scrim within modal - closing the scrim and hiding any slotted content when interacted with. This can be turned off the same way Modal does with a `outside-close-disabled`.

LMK if you think we should reconsider this, but the idea was to basically be a Shell Panel with Modal's page blocking scrim + positioning.

**Comment by driskull** [comment]
Do we need...

- outsideCloseDisabled prop?
- escapeDisabled prop?
- scale prop?
- width prop?
- kind prop?
- beforeClose prop?
- Is this focus trapped?

cc @macandcheese

**Comment by macandcheese** [comment]
> Do we need...
> 
> * outsideCloseDisabled prop?  ✅ 
> * escapeDisabled prop?  ✅ 
> * scale prop? 🙅
> * width prop? 🅰️ 
> * kind prop? 🙅 / 🅱️ 
> * beforeClose prop?  ✅ 
> * Is this focus trapped?  ✅ 
> 
> cc @macandcheese


🅰️  -  Shell Panel has W/H-scale props and css vars. Shell Panel also has horizontal / vertical layout. Since Sheet will have "position" (t/b/l/r) instead of layout - we can likely have a single scale and min/max css vars for resizing. 

🅱️ - not to start at least. 

Also from Shell Panel:

`resizable` : For now we can use the exact affordances of Shell Panel. In the future all of these should get an improvement ((https://github.com/Esri/calcite-design-system/issues/5652))
`displayMode`: overlay(default) / float :
![Group 14](https://github.com/Esri/calcite-design-system/assets/4733155/9868f573-f440-43c8-894b-4981f709f078)

Resizing and `display-mode` can follow up as well if needed, would consider them nice to have at launch.

Let me know what you think of the above - or if having this hybrid approach is too confusing. The main reason for not having slotted areas like Modal (header, content, footer, etc.) is to more easily allow Panel to be the main and expected content placed in a sheet - which itself has the same slots.

**Comment by driskull** [comment]
@macandcheese @jcfranco should sheet have the same zindex as modal or do we need another layer/token variable?

**Comment by macandcheese** [comment]
Same as Modal I'd think. Similarly we'd want to document / recommend a user only displays one Sheet at a time.

**Comment by driskull** [comment]
Lets do resizing as a followup next milestone, we can do displayMode for the initial release.

**Comment by driskull** [comment]
@macandcheese should `sheet` handle overflow to allow scrolling if the content is larger than the sheet? Modal does this so wanted to check.

Otherwise, the user would have to rely on something like panel to handle overflow of content.

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.13` with the following:

### Properties
- `beforeClose`
- `displayMode`
- `escapeDisabled`
- `heightScale`
- `focusTrapDisabled`
- `label`
- `open`
- `outsideCloseDisabled`
- `position`
- `widthScale`


### Events
- `calciteSheetBeforeClose`
- `calciteSheetClose`
- `calciteSheetBeforeOpen`
- `calciteSheetOpen`


### Methods
- `setFocus`
- `updateFocusTrapElements`

cc @SkyeSeitz @ashetland @brittneytewks for Figma UI kit updates
