### ISSUE TITLE
Modal `beforeClose` behaves differently when removing `open` attribute

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6407]
### Actual Behavior

Closing a modal via its built-in UI (close button, escape key, or outside click) can be interrupted by having its `beforeClose()` callback return a rejected promise.

However closing a modal by removing its `open` attribute can not be interrupted in the same way. The modal also enters into an inconsistent state where its `open` and `isOpen` properties are out-of-sync and an `overflow-hidden` class remains on the document element.

### Expected Behavior

Closing the modal by removing the `open` attribute and having its `beforeClose()` callback return a rejected promise does no leave the modal in an inconsistent state.

Ideally the `open` attribute is restored, but if not, maybe generate a warning for this scenario and then provide an API method that can be used to programmatically close a modal in a way that is interruptible by the `beforeClose()` callback.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/JjBeJVr

### Reproduction Steps

1. Visit the pen and click the **Open** button to open the modal.
2. Click the modal's **X** button and see it does not close, as expected because `beforeClose` returns a rejected promise.
3. Click the modal's **Close** button and see the modal disappears, unexpectedly.
4. Use devtools to see the pen iframe's `<html>` element retains the modal's `overflow-hidden` CSS class and the `.modal` element within the modal's shadow-dom retains the `modal--open` class.

### Reproduction Version

1.0.3

### Impact

Having `beforeClose()` reject is useful for flows where the app needs to confirm the closure of a modal.

One workaround is for the consumer to run `beforeClose()` themselves before actually removing the `open` attribute. However this leads to some more complicated code to prevent `beforeClose()` from running more than once per close attempt.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Research needed to determine next steps, if related to #6279, or if additional mitigation is needed.

**Comment by brittneytewks** [comment]
Hey @driskull, for research consideration in this milestone for time estimate and priority to be added

**Comment by driskull** [comment]
Maybe we need to introduce a public close method that would handle this and return a promise. cc @jcfranco 

> Use devtools to see the pen iframe's <html> element retains the modal's overflow-hidden CSS class and the .modal element within the modal's shadow-dom retains the modal--open class.

I think its weird that the watcher is calling beforeClose. The watcher should just honor what was done and remove the necessary classes.

**Comment by driskull** [comment]
Changed the estimate since this requires a new pattern discussion.

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.9`.
