### ISSUE TITLE
Combobox Item Group - add space after grouped items

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#6412]
### Description

It is currently very difficult to know where a `combobox-item-group` ends. Adding space at the bottom of grouped items will provide visual separation between the group and any following content. 

### Acceptance Criteria

- Bottom padding added to `combobox-item-group` at all scales.
- Added padding would not be present if the group has no items, allowing for the use of only the group heading (with no extra padding) when nesting groups.

### Relevant Info

Thank you to @Anastasiia-Boleiko for bringing this to our attention!

A design, with a possible final spec, is available in Figma.

### Which Component

Combobox Item Group

### Esri team

Calcite (dev)

**Comment by Anastasiia-Boleiko** [comment]
Thanks a lot for filing this enhancement! It will be really helpful👍

**Comment by ashetland** [comment]
Design spec available in this [Figma file](https://www.figma.com/file/IMJzSur0pnbTcw7RW719yf/Combobox-Group-Spacing-%5BIssues-%236412%2C-%236384%5D-%5Benhancement%5D?type=design&node-id=107-35777&t=fSD1StP4Bv6l8Pi5-11).

**Comment by geospatialem** [comment]
Verified in the `main` branch:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/82483f46-fb8c-4ff7-9bac-998d0a0c9582)
