### ISSUE TITLE
Split button has uneven opacity when in a `disabled` and `loading` state

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6453]
### Actual Behavior

A split-button element in a `disabled` and `loading` state shows the primary button as noticeably more faded than the dropdown trigger:

<img width="198" alt="Screenshot 2023-02-09 at 8 19 41 PM" src="https://user-images.githubusercontent.com/421496/217976528-a62c655e-3c99-4688-90cd-a76c3f2e935f.png">

### Expected Behavior

A split-button element in a `disabled` and `loading` state shows the primary button and dropdown trigger with the same levels of opacity:

<img width="198" alt="Screenshot 2023-02-09 at 8 20 37 PM" src="https://user-images.githubusercontent.com/421496/217976562-8fc828e9-9011-496b-9869-3be00aee4ed4.png">

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/split-button/

### Reproduction Steps

1. Visit the doc page for the split button
2. Enable both the `disabled` and `loading` properties

### Reproduction Version

1.0.5

### Relevant Info

It looks like the primary button becomes disabled when in the `loading` state. So adding the `disabled` state is probably doubling up on its opacity.

### Impact

The primary button becomes faded to the point that it can be difficult to read. Due to the low contrast of this state, this could also be considered an accessibility issue.

### Esri team

ArcGIS Field Apps

**Comment by jcfranco** [comment]
@geospatialem This should have been fixed by https://github.com/Esri/calcite-design-system/pull/8292. See [updated repro case](https://codepen.io/jcfranco/pen/Yzbypba).

**Comment by geospatialem** [comment]
Verified in `2.8.2` 🎉 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/02bfea76-56f1-4782-a476-3edbc4078633)
