### ISSUE TITLE
[Action Bar] "Stray" clicks on Action Bar focus bottom action / toggle / first action

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6462]
### Actual Behavior

I noticed this in the documentation site app, but it seems to happen in our plain component setup as well.

If there are no bottom-actions, the toggle button gains focus.

If there are no bottom-actions and `expandDisabled` (so no expand toggle), the first item in the action bar is focused.

This video shows the issue both in the app itself and the action bar sample:

https://user-images.githubusercontent.com/4733155/218555803-0f26b253-b860-4b02-9d78-af41fca1bdb5.mov

### Expected Behavior

I would not expect a "stray" click on the Action Bar to focus the first bottom-actions action, the expand toggle, or the first action.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/dyqbrOz?editors=100

### Reproduction Steps

1. Go to Codepen
2. Click the "empty space" between the top and bottom actions.

### Reproduction Version

1.0.5

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Research to be conducted to determine a time estimate for an upcoming milestone.

**Comment by macandcheese** [comment]
Potential css-only fix: Adjust flex / margin on the bottom action group elements to not fill available space.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.25`
