### ISSUE TITLE
calcite-input type=number with ar in FireFox using wrong decimal separator

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#6471]
### Actual Behavior

Chrome (this is correct):
![image](https://user-images.githubusercontent.com/44481292/218866858-50cfee5f-d632-42f1-ba40-7da57ff537fd.png)

FireFox (this is wrong):
![image](https://user-images.githubusercontent.com/44481292/218868630-3dfb1d61-3fd5-4c99-bfd2-01f3bc8d4aa5.png)

This is not reproducible in this codepen:
https://codepen.io/afreitag/pen/jOapXNW

But I can repro this by creating a very simple Stencil component.

arcgis-test.tsx:
```
import { Component, Host, h, VNode } from "@stencil/core";
@Component({
  tag: "arcgis-test",
  shadow: true
})
export class ArcgisTest {
  render(): VNode {
    return (
      <Host>
        <calcite-input value="3.33" type="number" />
      </Host>
    );
  }
}
```

index.html
```
<!DOCTYPE html>
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <title>arcgis test</title>

    <!-- calcite components -->
    <link href="../../vendor/@esri/calcite-components/calcite.css" rel="stylesheet" />
    <script type="module" src="../../vendor/@esri/calcite-components/calcite.esm.js"></script>

    <!-- arcgis app components -->
    <script type="module" src="../../build/arcgis-app.esm.js"></script>
    <link rel="stylesheet" href="../../build/arcgis-app.css" />

    <style>
      html,
      body {
        padding: 0;
        margin: 0;
        height: 100%;
        width: 100%;
      }
      #display {
        width: 300px;
        padding: 20px;
      }
    </style>

    <script type="module">
      const main = async () => {
        document.getElementById("display").appendChild(document.createElement("arcgis-test"));
      };
      main();
    </script>
  </head>

  <body>
    <div id="display"></div>
  </body>
</html>
```

### Expected Behavior

In Arabic the correct decimal separator is a dot ('.').

### Reproduction Sample

https://codepen.io/afreitag/pen/jOapXNW

### Reproduction Steps

create the Stencil component

### Reproduction Version

1.0.5

### Regression?

no

### Esri team

ArcGIS Map Viewer

**Comment by annierm18** [comment]
Additional info: Our 3rd party vendors reproduced this issue in Safari and Firefox in the Latitude/Longitude textbox on the MapViewer "Add media layer" page. Here is a codepen that shows that the decimal can be entered in Chrome but not FF: https://codepen.io/ainermfc/pen/mdzGzey?editors=100

cc: @olga8614 @benelan

**Comment by jcfranco** [comment]
@benelan Could you take a look at this one? 👀

**Comment by benelan** [comment]
This looks resolved in `1.6.1`p can you verify @annierm18?

**Comment by benelan** [comment]
Likely related to #6607

**Comment by AdelheidF** [comment]
looks good now

**Comment by geospatialem** [comment]
Closing per [Adelheid's comment above](https://github.com/Esri/calcite-design-system/issues/6471#issuecomment-1688882662) 👆🏻
