### ISSUE TITLE
[Popover]: Skipped unstable test 

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#6472]
### Test type

unstable test

### Which Component(s)

Popover

### Unstable Tests

calcite-popover › setFocus › should focus close button

### Test error, if applicable

Summary of all failing tests
FAIL src/components/popover/popover.e2e.ts (44.325 s)
  ● calcite-popover › setFocus › should focus close button

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      224 |         options?.shadowFocusTargetSelector
      225 |       )
    > 226 |     ).toBe(true);
          |       ^
      227 |   }
      228 |
      229 |   // wait for next frame before checking focus

### PR skipped, if applicable

#6465

**Comment by jcfranco** [comment]
This was unskipped a while ago and seems to have been stable since. Closing as self-verified!
