### ISSUE TITLE
[Tree item] Focus support for `action-end`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6481]
### Actual Behavior

When `tree-item`s contain `action-end`, the focus outline is:
1. Not depicted on the `tree-item`s right side, and
2. The `action-end`s outline is only depicted on the left and right, and not the top or bottom.

![verify-tree](https://user-images.githubusercontent.com/5023024/219082609-cc939136-bc7c-4736-a8c8-0923b223ac09.gif)

cc @ashetland @SkyeSeitz 

### Expected Behavior

A full focus outline around the `tree-item` and `action-end`.

### Reproduction Sample

https://codepen.io/geospatialem/pen/abazZgJ

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/abazZgJ)
2. Keyboard into the `tree` and `tree-item` using the `tab` key
4. Observe "Child 1"'s focus outline
5. Press `tab` again to observe the focus on the `action-end`
6. Press the `tab` key 3 additional times to observe the focus of "Child 3" containing additional child elements while expanded

### Reproduction Version

1.0.6

### Relevant Info

This was a tradeoff as a result of #6403. Context is provided via https://github.com/Esri/calcite-components/pull/6403#issuecomment-1431609932 and below comments.

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
Wanted to share an idea after working on https://github.com/Esri/calcite-components/pull/6519 for a bit and noticing focus getting obscured by the slotted actions. If we moved the focus to the internal node container, we would get something like the following:

![tree-alt-focus](https://user-images.githubusercontent.com/197440/221788706-00d254bc-f3da-4526-838b-7da83e554e91.gif)

The main difference would be that focus on tree-items with deep nesting would no longer cover the outermost tree-item in focus. 

### before

<img width="276" alt="Screenshot 2023-02-27 at 11 54 45 PM" src="https://user-images.githubusercontent.com/197440/221790180-830cf977-515f-4b88-8684-c7aca0232565.png">

### after

<img width="282" alt="Screenshot 2023-02-27 at 11 59 26 PM" src="https://user-images.githubusercontent.com/197440/221790154-92e4340d-8a98-4f33-826e-58ed43724a60.png">

<details>
  <summary>Here's the patch in case we want to move forward with this or something similar.</summary>

**Note**: this is built on top of #6519 

```diff
diff --git c/src/components/tree-item/tree-item.scss w/src/components/tree-item/tree-item.scss
index b7df99580..b38679f88 100644
--- c/src/components/tree-item/tree-item.scss
+++ w/src/components/tree-item/tree-item.scss
@@ -10,7 +10,7 @@
 }
 
 .node-actions-container {
-  @apply flex justify-between;
+  @apply flex;
 }
 
 @include calciteHydratedHidden();
@@ -108,15 +108,23 @@
 
 // focus styles
 :host {
-  @apply focus-base;
+  @apply outline-none;
+
+  .node-container {
+    @apply focus-base;
+  }
   &:focus,
   &:active {
-    @apply focus-inset outline-none;
+    .node-container {
+      @apply focus-inset;
+    }
   }
 }
 
 :host(:focus:not([disabled])) {
-  @apply focus-inset outline-none;
+  .node-container {
+    @apply focus-inset outline-none;
+  }
 }
 
 .actions-end {
@@ -152,7 +160,7 @@
 }
 
 .node-container {
-  @apply relative flex items-center;
+  @apply relative flex grow items-center;
 
   .checkmark,
   .bullet-point {

```
</details>

**Comment by ashetland** [comment]
I like this idea. Focusing each item like in the above example feels like how I would expect it to work, whereas focusing the entire set when selecting the outermost item feels unexpected to me.

**Comment by geospatialem** [comment]
Possibly related: https://github.com/Esri/calcite-components/issues/6509?

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.9`
