### ISSUE TITLE
[Stepper] Focus outline appears slowly

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6482]
### Actual Behavior

The Stepper Item focus outline appears slowly and makes the component appear sluggish, or broken: 

https://user-images.githubusercontent.com/4733155/219099845-05e26769-0e5a-4b38-b54c-bdcb9b388e24.mov

### Expected Behavior

I'd expect the focus outline to appear without transition, as in other components

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/MWqYjOb?editors=1000

### Reproduction Steps

1. Go to Codepen
2. Use mouse or keyboard to navigate through the outline
3. See the slow transition of focus outline

### Reproduction Version

1.0.5

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍬 Verified on `2.7.2-next.5`
