### ISSUE TITLE
Block: too many loading indicators

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#6485]
### Actual Behavior

Block's header has two loading indicators. 
![image](https://user-images.githubusercontent.com/108549080/219140725-96af0fc1-9614-44be-a8cd-bc5c466e0e60.png)

### Expected Behavior

One loading indicator, either on the left or the right. Prefer the inline calcite-loader for consistency.

### Reproduction Sample

https://codepen.io/ashetland/pen/GRBbOXK

### Reproduction Steps

1. Open codepen.
2. Collapse and expand Blocks to see loading behavior.

### Reproduction Version

1.0.5

### Relevant Info

cc @alan

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
Cc @asangma / @mitc7862 for insight / historical context / need for MV

**Comment by ashetland** [comment]
After a quick chat with @asangma, propose we use the calcite-loader for consistency, but use the icon slot like before. This would reduce adding more items to the right side.

![image](https://user-images.githubusercontent.com/108549080/219192591-632c063a-bc24-4471-924c-b8585f4117ae.png)

**Comment by geospatialem** [comment]
Moving back to development per https://github.com/Esri/calcite-design-system/pull/7239#issuecomment-1618721579 and https://github.com/Esri/calcite-design-system/pull/7239#issuecomment-1619163107
