### ISSUE TITLE
color-picker-swatch: support a 'no color' display

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#6496]
### Description

![image](https://user-images.githubusercontent.com/44481292/219802039-f4bacc24-4310-4216-91af-d59a062dd4f3.png)

### Acceptance Criteria

If no color is set display the 'no color' look. The tooltip should say 'No color'.

### Relevant Info

We're using a workaround that adds these red lines to a white color swatch, but the tooltip displays "#FFFFFF" which is not good.

![image](https://user-images.githubusercontent.com/44481292/219802541-3d401bec-1223-4eca-b97b-850f049e6369.png)

### Which Component

calcite-color-picker-swatch

### Example Use Case

Symbol styler inline input

![image](https://user-images.githubusercontent.com/44481292/219802316-4ba7af14-7040-406a-b232-741a2e9e8c9b.png)

### Esri team

ArcGIS Map Viewer

**Comment by ashetland** [comment]
Color Picker Swatch does have no-color styling, but without a tooltip. https://codepen.io/ashetland/pen/dywVxzO

**Comment by AdelheidF** [comment]
Oh I see, it looks like this then.

![image](https://github.com/Esri/calcite-design-system/assets/44481292/962cbd1c-fae5-4198-836d-0653dcae822a)

**Comment by AdelheidF** [comment]
This probably got implemented after we added the workaround. Closing...
