### ISSUE TITLE
[Card / Alert / Notice] Improve alignment of slotted text

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6499]
### Description

We've received feedback that the spacing of our text / subtext lockup in our Card is a bit wonky. We should evaluate this from a visual standpoint and determine what changes we should make. Let's consider similar lockups like those in Alert, Notice, etc., and ensure they are consistent.

### Acceptance Criteria

The text / subtext lockup is visually improved in card, and is made consistent with other similar lockups.

### Relevant Info

It seems like even Alert and Notice are a bit off. I'd say a middle ground between those two would work best

### Which Component

Card

### Example Use Case

![Group 1](https://user-images.githubusercontent.com/4733155/220477497-e1448465-b644-405e-88bb-e8904ef86510.jpg)

### Esri team

ArcGIS Business/Community Analyst

**Comment by ddred11** [comment]
@SkyeSeitz @ashetland  I think the lockup between title and the subtitle could be tightened a bit. Seems a little loose and not quite what one would expect. Came across this in a discussion with @macandcheese.

**Comment by ashetland** [comment]
Thanks @ddred11, completely agree with you there. In fact we're looking into making this consistent across the system. We've made a first pass audit and now need to look at each scale of all the components identified. 

![image](https://user-images.githubusercontent.com/108549080/220974346-96242d00-bfe0-45eb-b8a7-6cc8cec7f04f.png)

**Comment by ashetland** [comment]
Need to confirm 2px gap spacing works at each scale and post final recommendations.

**Comment by SkyeSeitz** [comment]
Proposing a 2px increment when applying to scales. Card, Block, List Item and Tiles do not currently have a scale prop, however this pattern would extend well to those variants in the future. [See more](https://www.figma.com/file/7nVDQ7ZCAb7YSYpvUeaUID/Slotted-text-alignment-%5Bissue-6499%5D?type=design&node-id=517%3A12429&t=m4Ym1W5saMRXWMsO-1)
<img width="1565" alt="image" src="https://github.com/Esri/calcite-components/assets/29716057/2020d745-3534-4b88-9745-53c9c3d9a43f">

**Comment by macandcheese** [comment]
I think we should close this in favor of this one: https://github.com/Esri/calcite-design-system/issues/7623, which is newer and more comprehensive.

**Comment by brittneytewks** [comment]
Close in favor of #7623 https://github.com/Esri/calcite-design-system/issues/7623
