### ISSUE TITLE
[Input Date Picker Range]: save previously selected start and end dates on the calendar

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-design-system#6501]
### Actual Behavior

Whenever the start and end dates have been set, the latest state of the calendar will be shown when clicking any of them. 

https://user-images.githubusercontent.com/35533801/220742202-e8ff1777-6ff1-4800-8d22-2034d7337773.mp4

### Expected Behavior

The value of the start date on the calendar will be shown when clicking on the start date input, and the end date when clicking on the end date input field.

https://user-images.githubusercontent.com/35533801/220742374-9c73290c-d789-43ae-b5c9-ce1a45e25a3b.mp4

### Reproduction Sample

https://codepen.io/svlesiv/pen/WNgwBNL

### Reproduction Steps

* Set the Start Date to Feb 1st, 2023
* Set the End Date to April 22nd, 2023
* Click on the Start Date input field
* The latest calendar state (April) will be shown

### Reproduction Version

v1.0.7

### Esri team

ArcGIS Site Scan

**Comment by Olga8614** [comment]
Also reported by BYS: https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/46825

**Comment by jcfranco** [comment]
It looks like the issue is being caused by the logic handling the caret/toggles (e.g., blur/focus? 🤔❓). I did a quick test using `pointer-events: none` on the toggles and the component seems to work as expected.

**Comment by DitwanP** [comment]
🍠 Verified locally on `main`
![Screenshot 2023-12-15 at 11 15 11 AM](https://github.com/Esri/calcite-design-system/assets/60022782/8c479bb0-851a-4a0b-89b8-ea96c20ea85d)
