### ISSUE TITLE
[calcite-action-bar] bottom-actions slot name not consistent with similar slots

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#6517]
### Actual Behavior

All action slot names are named `actions-<placement>`, and `bottom-actions` does not follow this pattern.

### Expected Behavior

`bottom-actions` to be renamed `actions-bottom`.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/action-bar/#api-reference-slots-bottom-actions

### Reproduction Steps

👀 slot name

### Reproduction Version

1.0.7

### Relevant Info

This name was introduced when the component got moved from the calcite-app-components repo and the name probably didn't get revisited since.

Not urgent, but we can deprecate the existing slot and introduce the new one. 

### Priority impact

p3 - not time sensitive

### Esri team

Calcite (dev)

**Comment by brittneytewks** [comment]
Removed "needs triage" since a priority is set and estimate is indicated

**Comment by geospatialem** [comment]
Verified in `1.6.0-next.3` with: 

```html
<calcite-action-group slot="actions-end">
```
