### ISSUE TITLE
[New Component] Carousel / Carousel Item (from Tip Manager / Tip)

### ISSUE THREAD

**Issue by yelenakreyndel** [Esri/calcite-design-system#6536]
### Description

Create a new component for Carousel / pane slider. Design work needs to be complete by September for implementation to be complete by January 2024.

### User Stories

@macandcheese 
@mitc7862 
please gather requirements from product teams and update user story based on that information. 

### Acceptance Criteria

please gather requirements from product teams and update acceptance criteria based on that information. 

### Helpful Details

This should re-purpose Tip and Tip Manager - existing components that function similarly to a Carousel. Making those components more generic in name would open up to more use cases while still supporting the few instances where Tip / Tip Manager are used in the wild. The existing use case can be solved for by using the new Carousel / Carousel Item components and slotting content inside each slide - Notice, Blocks, etc., 

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
cc @benelan for the `stale` label and closing automation. Is there a way we can add the `stale` label, or similar, but not close out issues?

**Comment by macandcheese** [comment]
I think the auto-close is good, but maybe if the tag has been removed since it was last set, do not attempt to re-assign

**Comment by DitwanP** [comment]
🍡Verified locally on `main` 🎠
