### ISSUE TITLE
List: Allow collapsing of item groups

### ISSUE THREAD

**Issue by ade10176** [Esri/calcite-design-system#6537]
### Description

Support collapsing of item groups. Users often have a long list of items in a group. Allowing them to collapse each group will support workflow efficiency. 

### Acceptance Criteria

Collapse/expand Layers, Tables, or Basemaps independently when clicked
https://codepen.io/nwhittaker-esri/pen/bGxeMVq

### Which Component

List

### Esri team

ArcGIS Field Apps

**Comment by nwhittaker** [comment]
From https://github.com/Esri/calcite-design-system/issues/8515#issuecomment-1874646314:

>One design consideration is that we'd want to style top-level groups differently from nested groups. For example, the Layers and Rivers groups within this [prototype](https://codepen.io/nwhittaker-esri/pen/bGxeMVq).

**Comment by ashetland** [comment]
Collapsible grouping can be accomplished by slotting List into Block, Block Section, or Accordion. List's `group` prop can be used to enable sorting between Blocks. See this [codepen](https://codepen.io/ashetland/pen/NWQWZvq?editors=1100).

`calcite-filter` can also be used to filter multiple Lists. See this [tutorial](https://developers.arcgis.com/calcite-design-system/tutorials/filter-recent-earthquakes/).

With these solutions, we'd like to maintain current hierarchical relationships and avoid unnecessary overlap between components.

**Comment by ashetland** [comment]
Collapsible grouping can be accomplished by slotting List into Block, Block Section, or Accordion. List's `group` prop can be used to enable sorting between Blocks. See this [codepen](https://codepen.io/ashetland/pen/NWQWZvq?editors=1100).

`calcite-filter` can also be used to filter multiple Lists. See this [tutorial](https://developers.arcgis.com/calcite-design-system/tutorials/filter-recent-earthquakes/).

With these solutions, we'd like to maintain current hierarchical relationships and avoid unnecessary overlap between components.
