### ISSUE TITLE
[List / List items] Support custom filtering supporting a filter function with a prop

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6544]
### Description

A way to opt in to an stripped-down behavior when clicking a list-item that contains nested list-items.

Originally included selection and filtering asks, now placed in two separate issues:
- Filtering (_below_)
- Selection via #8515 

### Acceptance Criteria

Filtering a list of items with nested list-items:
* Parent list-item is visible when it does not match but any leaf items do match.
* Parent list-item is _not_ visible when it _does_ match but no descendent leaf items match.
* Parent list-item is not visible when no descendent leaf items match.
* Consider https://github.com/Esri/calcite-design-system/issues/3454  as part of the upcoming effort

### Which Component

calcite-list-item

### Example Use Case

The Field Maps web app would like to use the calcite-list element to display the layers in a map. For group layers, nested layers are shown as child list-items.

Selecting a leaf layer navigates the app for further handling of the layer. However, the app does not provide further handling for group layers. They are treated more like folders that organize sets of layers -- so clicking them in the list should have no effect other than to drill down to leaf layers.

### Esri team

ArcGIS Field Apps

**Comment by brittneytewks** [comment]
Scheduling time with FieldApps to understand use case in more depth

**Comment by nwhittaker** [comment]
Added some stripped-down filtering behavior to the issue description that should also be part of any discussion.

**Comment by geospatialem** [comment]
Reallocating to the May release for design considerations.

**Comment by ashetland** [comment]
Propose we model the changes to List selection behaviors after what is outlined in issue #6912 for Tree. This likely means adding a `children` selection mode and modifying the behaviors of `single`. I've started mocking this up today.

**Comment by ashetland** [comment]
### Selection modes
Final proposal for revising the existing `single` and `multiple` selection-modes and adding `children` and `multichildren` can be found in this [Figma file](https://www.figma.com/file/xsoNW0ysPJQUEi8WYFwFHz/List-selection-behavior-%5Bissue-6544%5D?type=design&node-id=509-24962). See also the image below. This would be consistent with changes to Tree in issue #6912 and pr #6926.

![image](https://github.com/Esri/calcite-components/assets/108549080/e3ed207c-6887-4295-9e75-d120cabcf031)

### Hover states
Hover states for the new hit targets should follow what was also defined for Tree Item in issue #6930.

### Filtering
Since the parent would still be selectable in `children` and `multichildren`, I propose the current filtering behavior be retained for these modes.

For the revised `single` and `multiple`, however, the behaviors outlined in the original post should be adopted:
> Filtering a list of items with nested list-items:
> 
> Parent list-item is visible when it does not match but any leaf items do match.
> Parent list-item is _not_ visible when it does match but no descendent leaf items match.
> Parent list-item is not visible when no descendent leaf items match.

### Nested indentation levels
With these new/revised selection modes, nested indentation behavior should be reconsidered as part of issue #6632.


@nwhittaker, let me know if we've missed anything here.

**Comment by nwhittaker** [comment]
Thank @ashetland -- looks really good!

One clarifying question on the single-selection mode. When a child is selected and the parent is clicked to collapse and then clicked again to expand, we'd need the child to remains selected. Is that doable?

Other than that, I think the single-selection mode will work well for us, @ade10176?

**Comment by ashetland** [comment]
Yep, that is the intent for both single and multiple. I've added a clarifying note to the [Figma file](https://www.figma.com/file/xsoNW0ysPJQUEi8WYFwFHz/List-selection-behavior-%5Bissue-6544%5D?type=design&node-id=509-24962) that can be seen here:

![image](https://github.com/Esri/calcite-components/assets/108549080/ed936c79-4de0-4766-bd64-443909d9c4bc)

**Comment by ade10176** [comment]
Agreed w/ @nwhittaker looks great @ashetland !

**Comment by ashetland** [comment]
Thanks all!

**Comment by ade10176** [comment]
Looking to get this supported in Calcite so we can use it in Field Maps @ashetland

**Comment by driskull** [comment]
I'm not really sure I understand this issue. It would help if the requests were separated into separate issues for filtering and selecting. Could we do that?

With regards to the selection requests, I think this is why we have different selection modes.

**Comment by driskull** [comment]
> Parent list-item is not visible when it does match but no descendent leaf items match.

This one seems odd to me.

> Parent list-item is not visible when no descendent leaf items match.

This should be `Parent list-item is not visible when no descendent leaf items match and parent does not match` correct?

I think this is how these are already working. Is there a repro where we can see the unexpected scenario?

**Comment by nwhittaker** [comment]
>>Parent list-item is not visible when it does match but no descendent leaf items match.
>
>This one seems odd to me.

The **Example Use Case** section should flesh out the reasoning for this behavior. To clarify, our parent list items are group layers which have no actions or selection behaviors (other than open/close) associated with them. As a result, it doesn't make sense for Field Maps to show them in the results if they don't contain any matching leaf layers.

In other words we're interested in finding non-group layers within a nested, or non-nested, layer structure. Groups should fail the filter if it makes them appear to be empty.

---

>>Parent list-item is not visible when no descendent leaf items match.
>
>This should be `Parent list-item is not visible when no descendent leaf items match and parent does not match` correct?

Your edit makes sense in the context of the previous requirement. However, as a standalone requirement, it's more complete to say if none of the descendants match, we want to hide the parent regardless if it itself matches.

---

It's not narrowly scoped to the requirements of this issue, but I have an old [codepen prototype][1] that tests out the list functionality in the context of how we'd be using it. It might be helpful to check out to get a feel for what we're looking to do.

Depending on how specialized our requests are getting, there's certainly flexibility on our end in terms of how declarative the API is. For example, adding support for the `hidden` attribute to `<calcite-list-item>` so we can hide it ourselves, if needed.

[1]: https://codepen.io/nwhittaker-esri/pen/bGxeMVq

**Comment by driskull** [comment]
> For example, adding support for the hidden attribute to <calcite-list-item> so we can hide it ourselves, if needed.

The hidden attribute should already work on list-item's as well as any other component.

I think we could support custom filtering through a property where a user can define their own filter logic by supplying a function. That seems like it would be best to handle all these use cases.

**Comment by nwhittaker** [comment]
>The hidden attribute should already work on list-item's as well as any other component.

I did not find that to be the case: https://codepen.io/nwhittaker-esri/pen/MWxaLRp. I'd expect all the list items to be hidden there.

**Comment by driskull** [comment]
Ah, yeah the filter is removing it. Can you open a separate issue for this? We can fix it by hiding filtered items differently so we are not using the hidden attribute.

**Comment by driskull** [comment]
@geospatialem can we repurpose this issue to instead "support custom filtering logic"? Allowing a user to provide a filter function via a property.

**Comment by driskull** [comment]
@geospatialem @DitwanP what would you expect this custom filter prop on the list to be named?

**Comment by geospatialem** [comment]
> @geospatialem @DitwanP what would you expect this custom filter prop on the list to be named?

Naming is hard 😅 - was trying to think of a way we could add `filter...` to the beginning part of the prop name for consistency with other filter props, but came up empty. @driskull Dig the direction you headed with `customFilter`. 🥇

**Comment by nwhittaker** [comment]
>>@geospatialem @DitwanP what would you expect this custom filter prop on the list to be named?
>
>Naming is hard 😅 - was trying to think of a way we could add filter... to the beginning part of the prop name for consistency with other filter props, but came up empty. @driskull Dig the direction you headed with customFilter. 🥇

A predicate function is one that always returns `true` or `false`. How about `filterPredicate`?

**Comment by driskull** [comment]
@nwhittaker @geospatialem how about:

```tsx
/** Specifies a function to handle filtering. */
  @property() filterItems: (listItems: ListItem["el"][]) => ListItem["el"][];
```

@geospatialem @DitwanP Should the custom filter function require that `filterText` be defined? (not empty string) or should we allow the custom filter function to worry about the filterText property? I lean towards not having a requirement that it be set. It could allow users do their own filtering independent of the UI.

**Comment by driskull** [comment]
Actually, I think i like the `filterPredicate`, ill go with that.

**Comment by geospatialem** [comment]
> Should the custom filter function require that `filterText` be defined? (not empty string) or should we allow the custom filter function to worry about the filterText property? I lean towards not having a requirement that it be set. It could allow users do their own filtering independent of the UI.

Also lean towards not having a defined `filterText` be a requirement, otherwise it might make the story a bit confusing for devs to implement.

> The other question is should `filterPredicate` work even when `filterEnabled` is false?

Maybe we should lean towards supporting it regardless of `filterEnabled`? If so, could this potentially accommodate #10258?

**Comment by geospatialem** [comment]
Verified with `3.0.0-next.76` and https://codepen.io/geospatialem/pen/vEBxZqy

```js
const listEl = document.getElementById("custom-list");

listEl.filterPredicate = (item) => {
  if (listEl.filterText === "test") {
    return true;
  }

  return item.value === "item2";
};
```
