### ISSUE TITLE
[List and List Item] Provide list item sorting

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6554]
### Description

Add full parity to the `list` component, which is provided in the `value-list` and `pick-list` components.

May also include a refactor of the `sortable` utility, which some teams use for their own use and should be consulted if a breaking change is necessary.

### Acceptance Criteria

- [ ] Drag and drop functionality of the `list-item`s
   - [ ] Mouse and keyboard support
   - [ ] Keyboard support when screen readers are active for both Windows (NVDA, JAWS) and Mac (VoiceOver) users

### Relevant Info

Part of the https://github.com/Esri/calcite-components/issues/6430 epic

### Which Component

- List
- List item

### Example Use Case

Depicted with `value-list` and `value-list-item`: 
https://codepen.io/geospatialem/pen/abjxWwL

### Esri team

Calcite (dev)

**Comment by driskull** [comment]
Before we can tackle this, we should discuss whether we should be using the SortableList component internally here or getting rid of that component.

**Comment by AdelheidF** [comment]
This is what we're using currently.

![image](https://user-images.githubusercontent.com/44481292/225123512-c311740b-1bca-42a9-a546-d8cfe2d75c8c.png)![image](https://user-images.githubusercontent.com/44481292/225123569-13d9e9c9-d477-4a1e-9a0b-e657dc83e7d6.png)

**Comment by driskull** [comment]
We need a whole sorting strategy before we can tackle this. The strategy should cover...

- Sorting between two separate lists or instances of components
- Fixing sorting when a child has sorting of its own (currently these are conflicting with list/block/etc)

**Comment by geospatialem** [comment]
Adding a tag to this issue to Hub components and cc @vivzhang in regards to the issue description above:

> May also include a refactor of the sortable utility, which some teams use for their own use and should be consulted if a breaking change is necessary.

**Comment by macandcheese** [comment]
Adding two pieces of feedback we got about Value List for consideration here w/r/t keyboard usage from this closed issue: https://github.com/Esri/calcite-components/issues/4231

> 
> Following up from Teams chat - some improvements to the value list while in drag-enabled mode to make using with a keyboard a bit easier:
> 
> Add support for esc to exit that mode (currently only hitting spacebar again exits the mode)
> Add support for home / end to quickly move an item to either extent (and preventDefault so the page doesn't scroll up / down)

**Comment by Anastasiia-Boleiko** [comment]
Currently, in ArcGIS Urban, we have several use cases of custom lists/accordions that seem to match the List/Block/Accordion component functionality. In several cases, it's a bit difficult to choose a proper Calcite component. I would appreciate your suggestions or perhaps, our cases can turn out into future List component enhancements.

### Case 1:
- List items are not expandable
- Enhanced content (content-start, content-end slots, actions-end etc)
- Searchable
- Actions in the list header (1. Add might be moved into the line with a search; 2. Button to filter the list that expands a popover)

**Component:**
 - List (seems to fit the needs) + filter and other actions are configured manually using Search, Action, Popover etc.
![image](https://user-images.githubusercontent.com/119309703/230152036-2e9a7913-b97a-4b01-a0d6-6a817d910b6a.png)


### Case 2:
- List items are not expandable
- Enhanced content (content-start, content-end slots, actions-end etc)
- Reorderable

**Component:**
 - List (seems to fit the needs, but is a bit hacky)
 - Table ?
<img width="803" alt="Screenshot 2023-04-05 at 18 16 31" src="https://user-images.githubusercontent.com/119309703/230147200-181938b4-f0ca-473b-bbb5-2437f38974ad.png">

### Case 3
- List items **are expandable**
- Enhanced content (content-start, content-end slots etc)

**Component:**
 - List (seems to fit the needs + filter and other actions are configured manually using Search, Action, Popover etc)
 - Block? (no enhanced content)
 - Accordion? (no enhanced content)

![image](https://user-images.githubusercontent.com/119309703/230152891-da3341ca-4ce5-4ff3-9fe5-8f1217aa8abe.png)

### Case 4
- Enhanced content (content-start, actions-end slots etc)
- Draggable (from one list to another)
- Keyboard support darg&drop

**Component:**
 - List? 

https://user-images.githubusercontent.com/119309703/230155412-7ba7a81c-e798-4e2f-88d9-eb46dafa1716.mov

**Comment by driskull** [comment]
@geospatialem @jcfranco we may need to make this one a breaking change.

I'm running into trouble with sorting of children because we slot a `<calcite-list-item>` inside of another `<calcite-list-item` like so:

```html
<calcite-list>
  <calcite-list-item>
    <calcite-list-item></ calcite-list-item>
  </calcite-list-item>
</calcite-list>
```

In order to fix this, we may need to require the following:

```html
<calcite-list>
  <calcite-list-item>
    <calcite-list>
      <calcite-list-item></ calcite-list-item>
    </calcite-list-item>
  </calcite-list>
</calcite-list>
```

Let me know if you'd like to meet to discuss this. If we do this breaking change, this milestone may need to change.

**Comment by geospatialem** [comment]
Documentation update to follow the change is needed to showcase what devs will need to achieve sorting, which differs from the current workflow. 

See [Matt's note above, the second example](https://github.com/Esri/calcite-components/issues/6554#issuecomment-1581608974).

**Comment by geospatialem** [comment]
Verified with https://codepen.io/geospatialem/pen/bGQzavG in `1.5.0-next.33`. Opened #7426 for finalizing AT support.
