### ISSUE TITLE
[Accordion Item] Stretch slotted actions to fill height of component

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6565]
### Description

Noticed this while testing out https://github.com/Esri/calcite-components/issues/6561 / https://github.com/Esri/calcite-components/issues/2884#issuecomment-1454349330.

Slotted actions don't stretch to fill the height:

<img width="747" alt="Screen Shot 2023-03-04 at 10 49 10 AM" src="https://user-images.githubusercontent.com/4733155/222923774-74958e7b-01de-48ae-931b-2c734554a487.png">

### Acceptance Criteria

We should follow how we handle this in other components - stretching the actions to fill when we expect the component as a slotted child, for example in Alert:

<img width="871" alt="Screen Shot 2023-03-04 at 10 52 27 AM" src="https://user-images.githubusercontent.com/4733155/222923802-f46f47e3-1556-48eb-a43a-1b42bedcf777.png">

### Which Component

Accordion Item

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Adding context to the above - once the above lands ✈️  we have a follow-up internal documentation update (issue 703).

**Comment by DitwanP** [comment]
🍠 Verified on `2.14.0-next.6`
![image](https://github.com/user-attachments/assets/819dbc90-eb79-46b0-b79c-1b1ba2aad5db)
