### ISSUE TITLE
[Docs] Improve Animation Documentation and Class Availability

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6577]
### Description

We can do a better job of documenting the animation classes, and add the "missing" versions (currently, we have in, down, up, scale, but not defined directions like "from-start", or "from-end".

### Which Component

All components:
https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/assets/styles/_animation.scss

### Resources

This came up as feedback from a user during Developer Summit.

**Comment by geospatialem** [comment]
Will add some content as part of the design token effort later this year, targeted for late summer.

**Comment by geospatialem** [comment]
Discussed with the team internally and we will not be publicly documenting the animation classes at this time. Closing the above as unplanned.
