### ISSUE TITLE
[Shell Panel] Allow `resizable` on `displayMode:float` Shell Panel

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6578]
### Description

This came up from a customer during Developer Summit - right now `resizable` is only available when the Shell Panel is not `detached`. The user would like to be able to resize a `detached` Shell Panel.

### Acceptance Criteria

The Shell Panel allows use of `resizable` when `detached` is set.

### Which Component

Shell Panel

### Example Use Case

Resize a detached shell panel.

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
+1 from UC customer and allow resizing of height and width.

**Comment by geospatialem** [comment]
Closing out the above in favor of #5652, where `shell-panel` will improve its resizing functionality with its drag handle affordance.
