### ISSUE TITLE
calcite-input-time-picker - Add support for fractional seconds

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-design-system#6591]
### Description

The `calcite-input-time-picker` needs to be extended to support milliseconds. Specifically the component needs an option to include milliseconds in the display and also an editing experience.

![image](https://user-images.githubusercontent.com/2531121/224866821-a1c588ab-282e-4b1d-819b-8e9ea631075d.png)

#### Perhaps:
```html
<calcite-input-time-picker fractionalSecondDigits=3 value="13:07:04.102" />
```

### Acceptance Criteria

- Add flag to  `calcite-input-time-picker` to support millisecond display and editing
- Allow user to edit milliseconds

### Which Component

```html
<calcite-input-time-picker />
```

### Esri team

ArcGIS Maps SDK for JavaScript

### Reference
1. JSAPI - Enhancement - Editor- Support New Date Fields (see [#50595](https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/50595))
2. JSAPI - Enhancement - FeatureTable - Support New Date Fields (see [#50596](https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/50596))

**Comment by ashetland** [comment]
Tagging this for necessary updates to Figma component. cc @SkyeSeitz

**Comment by richiecarmichael** [comment]
Just updated the proposed design:

**From:**
```js
<calcite-input-time-picker showMilliseconds=true value="13:07:04.102" />
```
**To:**
```js
<calcite-input-time-picker fractionalSecondDigits=3 value="13:07:04.102" />
```
...to align with `Intl`'s [fractionalSecondDigits](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#fractionalSecondDigits) property. This provides greater control (i.e. tenth, hundredth or thousandth of a second) depending on the precision of the data.

`fractionalSecondDigits` (on **MDN**) states that valid values are `0`, `1`, `2` and `3`. However that this differs from **ES2021** which only allows `undefined`, `1`, `2` and `3`. This discrepancy is logged and _backlogged_ [here](https://github.com/tc39/ecma402/issues/590). I would suggest using values `0`, `1`, `2` and `3`.

**Comment by SkyeSeitz** [comment]
Design specs complete and available at the links below.
Time Picker: https://www.figma.com/file/fBkmuAy3R4BfjAWlRi2KjS/Calcite-Web-UI-Kit?node-id=10501%3A265212&t=6m3XXmjynq4AoQio-1
Input Time Picker: https://www.figma.com/file/fBkmuAy3R4BfjAWlRi2KjS/Calcite-Web-UI-Kit?node-id=12360%3A246650&t=6m3XXmjynq4AoQio-1

**Comment by geospatialem** [comment]
Reallocating to the May milestone, where it is expected to land soon for additional texting in `next`.

**Comment by ubatsukh** [comment]
@jcfranco we will not using this component at 4.27 as we decided to only support `read-only` versions of the new date/time fields at 4.27. However, we will pick up this component as soon as the 4.27 is released. 

You can find the general updates on adding support for new date/time fields from this planning doc issue: https://devtopia.esri.com/WebGIS/arcgis-js-api-planning-docs/issues/287#issue-1369706

**Comment by geospatialem** [comment]
Reallocated to the upcoming July milestone per the discussion [above](https://github.com/Esri/calcite-components/issues/6591#issuecomment-1550107523).

**Comment by geospatialem** [comment]
Reallocated to the August milestone with the UC approaching and addressing critical bugs in next week's June patch release.

**Comment by jcfranco** [comment]
Passing the torch to @eriklharper for this one. 🔥🔥🔥

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.17` with the following:

```html
<calcite-input-time-picker step="0.1" value="10:37:09.5"></calcite-input-time-picker>
```
