### ISSUE TITLE
[List] Change multiple icon or Add prop to support multiple icon types

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6603]
### Description

Before replacing the deprecated `pick-list` with the `list`, the `selectionAppearance` icon defaulted to a simple check. 

For consistency with the previous structure of `pick-list`, we could either:

1. Change the multiple icon to be in line with the `pick-list` and add the `"check"` icon, **or**

2. Allow users select from a few differing options. Could be similar to the `accordion`'s [`iconType`](https://developers.arcgis.com/calcite-design-system/components/accordion/#api-reference-properties-iconType) prop.

#### `pick-list` (current and expected in `list`):
![image](https://user-images.githubusercontent.com/5023024/225160312-10496357-cff8-48a6-bf21-636791e5c836.png)

#### `list` (current):
![image](https://user-images.githubusercontent.com/5023024/225160280-dbec4dac-1683-4479-9abf-3f5cb8bc53bf.png)

### Acceptance Criteria

Support the `"check"` icon when the `list`'s  `selectionAppearance` is set to and `selectionMode` is set to `multiple`.

#### Expected:
![image](https://user-images.githubusercontent.com/5023024/225159848-1fec890a-a7a8-46a8-8046-9d2a5ee936f0.png)

### Relevant Info

Came up in a [Community discussion](https://community.esri.com/t5/calcite-design-system-questions/change-selection-appearance-icon-of-calcite-list/m-p/1267708#M349) on 3/14/23.

### Which Component

`list` and `list-item`

### Example Use Case

For testing/current use case: https://codepen.io/geospatialem/pen/WNgzByM

![image](https://user-images.githubusercontent.com/5023024/225160312-10496357-cff8-48a6-bf21-636791e5c836.png)

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Consider with https://github.com/Esri/calcite-components/issues/6700

**Comment by ashetland** [comment]
Closing in favor of #6700
