### ISSUE TITLE
OpenCloseComponents do not emit when setting `--calcite-duration-factor`

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#6604]
### Actual Behavior

Setting `--calcite-duration-factor` to 0 allows users to skip animations, but prevents (before)open/close events from being emitted.

cc @Elijbet 

### Expected Behavior

All (before)open/close events to be emitted regardless of transition duration.

### Reproduction Sample

https://codepen.io/jcfranco/pen/WNgJemJ?editors=1010

### Reproduction Steps

Click on toggle and notice how events are not emitted in the console.

### Reproduction Version

1.0.8

### Priority impact

p3 - not time sensitive

### Impact

This will impact any users explicitly setting `--calcite-duration-factor` to 0 that rely on the before+open/close events.

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Workaround: https://codepen.io/jcfranco/pen/gOdeVpq?editors=1000 (Context: https://github.com/Esri/calcite-components/issues/6582#issuecomment-1469253860)

**Comment by jcfranco** [comment]
This should be fixed by https://github.com/Esri/calcite-design-system/pull/7258.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.38`
