### ISSUE TITLE
calcite-dropdown: focus lost after tabbing through

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-design-system#6610]
### Summary

When I tab to a `calcite-dropdown` then hit "Spacebar" to open it and tab through all the items. Once I pass the last item the dropdown closes and the focus is lost.  I would think that the focus would either focus back onto the button that opened the dropdown or the next focusable element after the dropdown, but neither is true.  Interestingly if I then hit tab again it then focuses on the next focusable element.

### Actual Behavior

Focus disappears after tabbing through all the option of the dropdown

### Expected Behavior

It should focus on the next focusable element after the dropdown.

### Reproduction Sample

https://codepen.io/rpanichakit/pen/RwYJKeL?editors=100

### Reproduction Steps

1. Tab to the "Dropdown button" and hit "Spacebar" to open it
2. Tab through all the options
3. Note that the dropdown auto closes, but the focus is not lost
4. If you tab an extra time, then the focus goes to the next focusable element

### Reproduction Version

1.0.8

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Discussing option to no longer allow tabbing through the component - only arrow keys will be used. Closing only occurs with `esc`, and the focus will be retained back to the trigger element.

**Comment by anveshmekala** [comment]
The focus is restored on to trigger element with calcite latest version `1.5.0` . This issues will be repurposed to avoid tabbing through the dropdown items when opened as per [W3C spec](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/#:~:text=When%20focus%20is%20on%20a%20menuitem%20in%20a%20menu%20or%20menubar%2C%20move%20focus%20out%20of%20the%20menu%20or%20menubar%2C%20and%20close%20all%20menus%20and%20submenus.).

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.9`. 

Where once the component is focused the arrow keys, `Home` (first item) and `End` (last item), `Esc` (closed when opened) are achievable. The `tab` key will proceed to the next focusable element in the page (`shift` + `tab` to the previous focusable element in the page).
