### ISSUE TITLE
Epic: Audit and update indentations and nested hierarchy across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6632]
### Background

Perform an audit across components to determine consistency and if needed update indentation for consistency across the design system, in particular within the nested hierarchy of the component.

Resulted from discussion in #6384

### Components to address indentations
- [x] #7099 
- [x] #7095 
- [x] #7100 
- [x] #7105 
- [x] #7096 

### Audited list of components from research (completed on 6/2/23):
- `accordion` (does not apply)
- `accordion-item` (does not apply)
- `action` (does not apply)
- `action-bar` (does not apply)
- `action-group` (does not apply)
- `action-menu` (does not apply)
- `action-pad` (does not apply)
- `alert` (does not apply)
- `avatar` (does not apply)
- `block` (does not apply)
- `block-section` (does not apply)
- `button` (does not apply)
- `card` (does not apply)
- `checkbox` (does not apply)
- `chip` (does not apply)
- `color-picker` (does not apply)
- `combobox` 
- `combobox-item` 
- `combobox-item-group` 
- `date-picker` (does not apply)
- `dropdown` (no nesting, but including for icon spacing)
- `dropdown-group` (no nesting, but including for icon spacing)
- `dropdown-item` (no nesting, but including for icon spacing)
- `fab` (does not apply)
- `filter` (does not apply)
- `flow` (does not apply)
- `flow-item` (does not apply)
- `icon` (does not apply)
- `inline-editable` (does not apply)
- `input` (does not apply)
- `input-date-picker` (does not apply)
- `input-message` (does not apply)
- `input-time-picker` (does not apply)
- `label` (does not apply)
- `link` (does not apply)
- `list` 
- `list-item` 
- `list-item-group` 
- `loader` (does not apply)
- `menu`
- `menu item`
- `modal` (does not apply)
- `notice` (does not apply)
- `option` (does not apply)
- `option-group` (does not apply)
- `pagination` (does not apply)
- `panel` (does not apply)
- `pick-list` (deprecated)
- `pick-list-group` (deprecated)
- `pick-list-item` (deprecated)
- `popover` (does not apply)
- `progress` (does not apply)
- `radio-button` (does not apply)
- `radio-button-group` (does not apply)
- `radio-group` (does not apply)
- `radio-group-item` (does not apply)
- `rating` (does not apply)
- `scrim` (does not apply)
- `select` (does not apply)
- `shell` (does not apply)
- `shell-center-row` (does not apply)
- `shell-panel` (does not apply)
- `slider` (does not apply)
- `split-button` (does not apply)
- `stepper` (does not apply)
- `stepper-item` (does not apply)
- `switch` (does not apply)
- `tab` (does not apply)
- `tab-nav` (does not apply)
- `tab-title` (does not apply)
- `tabs` (does not apply)
- `textarea`(does not apply)
- `tile` (does not apply)
- `tile-select` (does not apply)
- `tile-select-group` (does not apply)
- `time-picker` (does not apply)
- `tip` (does not apply)
- `tip-group` (does not apply)
- `tip-manager` (does not apply)
- `tooltip` (does not apply)
- `tree` 
- `tree-item` 
- `value-list` (deprecated)
- `value-list-item` (deprecated)

**Comment by SkyeSeitz** [comment]
Linking issue #7076 for hover/click area considerations.

**Comment by geospatialem** [comment]
All issues verified 🎉
