### ISSUE TITLE
DataGrid - add slot "toolbar"

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#6648]
### Description
The Data Grid component needs a common UI pattern for toolbar actions around a data grid. This can be provided in the form on a <slot name="toolbar"></slot> element.

### User Stories
Most table patterns at Esri include related elements like buttons and a search bar which update the related table. A custom component will allow for normalization of common patterns and accessibility best practices while still allowing for customization based on the needs of a specific app team.

### Acceptance Criteria
Component has the slot name "toolbar"
If the wrapper component assigned to the "toolbar" slot  is a <div> it should be set with display="contents" to lift it's children up as first class components within the context of the toolbar slot and laid out with flexbox rules.
Child elements of the wrapper assigned to the "toolbar" slot are keyboard accessible

#### CSS classes
start
end
center

### Relevant Info

Should be done after #6647

### Which Component

#1574
#6647

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Design will be sought in the May milestone. 

Once design has been completed, will be re-routed for dev, targeted for the August release.

**Comment by geospatialem** [comment]
Closing due to duplication of 6697.
