### ISSUE TITLE
DataGrid - add slot "footer"

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#6652]
### Description

The Data Grid component needs a common UI pattern for footer elements. This can be provided as a slot element

### User Stories

I want the DataGrid to have a place to include a pagination component.

### Acceptance Criteria

DataGrid Component has the slot name "footer"
If the wrapper component assigned to the "footer" slot  is a <div> it should be set with display="contents" to lift it's children up as first class components within the context of the toolbar slot and laid out with flexbox rules.
Child elements of the wrapper assigned to the "footer" slot are keyboard accessible

CSS classes
start
end
center

### Relevant Info

Epic: #1574

### Helpful Details

```
<calcite-datagrid>
    <calcite-pagination slot="footer" />
</calcite-datagrid>
```

### Which Component

Epic: #1574
Requires: #6697

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Design will be sought in the May milestone. 

Once design has been completed, will be re-routed for dev, targeted for the August release.

**Comment by geospatialem** [comment]
Closing due to duplication of 6697.
