### ISSUE TITLE
DataGrid - set items by attribute

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#6653]
### Description

Calcite DataGrid should allow for the virtualization of a table to give customers a simple interface for creating Esri style data tables. This should include an item attribute on the custom component and an items prop in the custom element. Changing either should trigger a "render" method

* a render utility function which accepts 
  * the table to update
  * a list of items
  * a renderItem function (should this be customizable?)
  * options object
    * headers (boolean)
* a render method on the DataGrid component which calls the render utility function
  * create a data table from the data
  * look for a <thead> in slotted children and set cell headers by key if found
  * if "showHeaders" attribute is true and there is no <thead> in slotted children DataGrid should generate the column headers.

### Acceptance Criteria

Calcite DataGrid has an "items" attribute which accepts a string of JSON data (an array of objects).
Changing the items attribute will
1. create a data table from the data
3. look for a <thead> in slotted children and set cell headers by key if found
4. if "showHeaders" attribute is true and there is no <thead> in slotted children DataGrid should generate the column headers.

### Relevant Info

Epic: #1574

### Which Component

Epic: #1574

### Example Use Case

As a DataGrid user I want to build a data table by setting a "items" attribute on the calcite-datagrid.

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (dev)

**Comment by yelenakreyndel** [comment]
@alisonailea Could you please assign a milestone? Thanks!

**Comment by geospatialem** [comment]
Design will be sought in the May milestone. 

Once design has been completed, will be re-routed for dev, targeted for the August release.

**Comment by geospatialem** [comment]
Closing due to duplication of #6697.
