### ISSUE TITLE
DataGrid: Mobile layout

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#6654]
### Description

The DataGrid should have an optional attribute to reconfigure table items in a vertical layout for better mobile interaction. This should be used in cases when Calcite consumers want to show all data in a set in a mobile layout.

### Acceptance Criteria

* DataGrid has an optional `layout="vertical"` attribute
* setting the layout attribute to "vertical" will trigger a reload of the DataGrid
* each item will become a nested table
* column headers will become row headers for each item
* row headers will become table captions 
* row cells values will become a single column

### Which Component

Epic: #1574

### Example Use Case

As a Calcite customer I want to provide data sets on a small mobile screen without horizontal scrolling.

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (dev)

**Comment by alisonailea** [comment]
Will require design from @macandcheese and @mitc7862

**Comment by geospatialem** [comment]
Design will be sought in the May milestone. 

Once design has been completed, will be re-routed for dev, targeted for the August release.

**Comment by geospatialem** [comment]
Closing due to duplication of 6697.
