### ISSUE TITLE
[Shell Panel] Resizable handle element positioned beneath slotted Panel header

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6658]
### Actual Behavior

The shell panel handle element doesn't display above the Panel header:
<img width="667" alt="Screen Shot 2023-03-24 at 1 29 05 PM" src="https://user-images.githubusercontent.com/4733155/227632854-3b844cca-732e-4c23-afbb-cc2d81f21c1b.png">

### Expected Behavior

As a user, I'd expect the resize element to position over the entire Shell Panel and any slotted content

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/yLxGxJP?editors=1000

### Reproduction Steps

1. Open Codepen
2. Drag / Focus Resize Element
3. Notice overlap

### Reproduction Version

1.1.0

### Regression?

Unsure

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Related #5652 for the handle design to accompany this effort.

**Comment by macandcheese** [comment]
+1 from UC customer

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.4`
![image](https://github.com/user-attachments/assets/ae0bf230-4f09-49c8-b5c1-0dedf232a03a)
