### ISSUE TITLE
Support multiple focus-traps on an app/page

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#6659]
### Description

Support multiple focus-traps on an app/page

### Acceptance Criteria

Apps can share the focus trap stack so that they don't clash with each other in different apps.

### Relevant Info

https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/50190#issuecomment-4017341

### Which Component

All focus-trap components

### Example Use Case

This sample loads a webmap that will prompt for authentication.
https://codepen.io/ellupp/pen/QWVbPPb?editors=1000

Open the sample, and remove "focus-trap-disabled" from the calcite-modal. The UI becomes unresponsive and you see the exceptions in the console. warning- this entirely froze codepen for me even after killing the tab and opening a new one, I needed to restart chrome.

### Priority impact

p4 - not time sensitive

### Esri team

N/A

**Comment by geospatialem** [comment]
Workaround is to disable the focus trap in the component.

**Comment by driskull** [comment]
I think we should elevate this issue. The workaround is to basically disable an accessibility feature.

**Comment by geospatialem** [comment]
> I think we should elevate this issue. The workaround is to basically disable an accessibility feature.

@jcfranco WDYT about adding this in to the current (May) milestone?

**Comment by jcfranco** [comment]
@driskull June is a patch-only release, though. If July is too late, let's sync up tomorrow to hash out a plan.

**Comment by driskull** [comment]
July is probably fine then. Lets just get it on the board.

**Comment by driskull** [comment]
https://stackoverflow.com/a/70184233

**Comment by geospatialem** [comment]
Verified in `master` where the `FocusTrap` is imported into `config.ts` and into the `focusTrapComponent` utility.
