### ISSUE TITLE
Dropdown: disabled property for Dropdown Item

### ISSUE THREAD

**Issue by olga-knyazeva** [Esri/calcite-design-system#6667]
### Description

The dropdowns in our app can have some items disabled, which is currently not possible with the CalciteDropdown component.

### Acceptance Criteria

Ability to make an individual Dropdown item disabled.

### Which Component

calcite-dropdown-item

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Urban

**Comment by Anastasiia-Boleiko** [comment]
Hello,

Could you please clarify what is the approximate time for having this feature in the Calcite release?

Thank you.

**Comment by geospatialem** [comment]
> Hello,
> 
> Could you please clarify what is the approximate time for having this feature in the Calcite release?
> 
> Thank you.

@Anastasiia-Boleiko Thanks for pinging this issue, we'll be assigning to a future milestone shortly.

**Comment by AdamWMoqrane** [comment]
High priority for Studio team please!

**Comment by DitwanP** [comment]
Verified locally on `main`

Waterfall option set to disabled.
![image](https://github.com/Esri/calcite-design-system/assets/60022782/156d73ca-dbf2-40c5-9000-25a73146063c)

**Comment by DitwanP** [comment]
Mistake on my part , Aaron mentioned to me that although the dropdown Item is greyed out and not selectable it is still showing hover effects as well as pressed effects. 

We want to remove those when an item is disabled.

https://github.com/Esri/calcite-design-system/assets/60022782/c4a23099-8401-4009-80d0-bc2a1da309bb

**Comment by DitwanP** [comment]
🍠 Looks great! Verified locally on `main`

https://github.com/Esri/calcite-design-system/assets/60022782/9b581563-522e-4d8f-86cd-ca638681a34e
