### ISSUE TITLE
[Combobox] Responsive layout

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6674]
### Description

Mobile responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

- [ ] 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
- [ ] 2. Components need to be designed for the following breakpoints:
    - [ ] Small (s), `476px`
    - [ ] Medium (m), `768px`
    - [ ] Large (l), `1152px`
    - [ ] Extra larger (xl), `1440px`

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`combobox`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
@rmstinson presented Combobox iterations, which could improve the use of space on all screen sizes, but especially crucial for smaller screen sizes and mobile devices. 

These explorations also consider the impacts of the following issues: #3074, #3695, & #4326.  

_Next steps: Based on today's feedback, Mike will iterate on the most promising solutions, including incorporate Adam's suggestion for Combobox Chips to live outside of the input field for us to discuss as a team on Tuesday (05/16)._ 

<img width="646" alt="image" src="https://github.com/Esri/calcite-components/assets/29716057/cf6e21e5-4a10-49e1-a5d5-9346f40e4f93">

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
@rmstinson presented [explorations](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?type=design&node-id=3530%3A99866&t=TZACBPkgdhiNKgHz-1) of Combobox Chips living outside of the input field as a footer or directly under the input field. We ultimately came back to the current build improved by the related enhancements: https://github.com/Esri/calcite-components/issues/3074 https://github.com/Esri/calcite-components/issues/4326

<img width="1153" alt="image" src="https://github.com/Esri/calcite-components/assets/29716057/c04cb829-5521-4893-a107-cb3ee1ffa303">

_Next steps: @geospatialem we may not need this separate issue once 3074 & 4326 are addressed. 4326 is already under way. Perhaps we can triage 3074 and get Mike assigned? Let me know what you advise. Thanks!_

**Comment by geospatialem** [comment]
> Next steps: @geospatialem we may not need this separate issue once 3074 & 4326 are addressed. 4326 is already under way. Perhaps we can triage 3074 and get Mike assigned? Let me know what you advise. Thanks!

Awesome, thanks for the update! 🙌🏻 Looks like 3074 is triaged to Franco, so should be good to go?

@SkyeSeitzDoes Looks like https://github.com/Esri/calcite-components/issues/4326 might need assignment. Should I assign to Mike for July?

**Comment by SkyeSeitz** [comment]
@geospatialem Yes, sorry mixed up those issue numbers - do a Missy Elliott and "flip it and reverse it" 🙏🏽 please and thank you.

**Comment by ashetland** [comment]
Closing in favor of #4326
