### ISSUE TITLE
[Input] Responsive layout

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6677]
### Description

Mobile responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

- [x] 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
- [x] 2. Components need to be designed for the following breakpoints:
    - [x] Small (s), `476px`
    - [x] Medium (m), `768px`
    - [x] Large (l), `1152px`
    - [x] Extra larger (xl), `1440px`

- [x] 3. Add truncation to placeholder and value props for all Calcite Input components:
    - [x] Input
    - [x] Input Text
    - [x] Input Number 
    - [x] Input Date Picker
    - [x] Input Time Picker 
    
**Current behavior**
https://github.com/Esri/calcite-design-system/assets/29716057/07d7b4d4-fd1a-4efe-a8cf-3a2b82c42899
<img width="291" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/3507583c-a688-456e-9802-af464cc3ef5b">

**Expected behavior**
https://github.com/Esri/calcite-design-system/assets/29716057/8a25f049-96a9-4dbd-8eb2-4c923c1c6373
<img width="456" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/a7c6089b-c428-4955-98f0-bdad65b52ccb">

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`input`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
We determined that Input does not need enhancements under the responsive layout initiative as it can be used on small screens and mobile devices as is with some simple documentation guidance to avoid overcrowding with limited horizontal real estate. 

@geospatialem Can we close this issue out for the reason above? Thanks!

**Comment by geospatialem** [comment]
Closing per [Skye's note](https://github.com/Esri/calcite-components/issues/6677#issuecomment-1535175875) above.

**Comment by SkyeSeitz** [comment]
Hi @geospatialem Can we reopen this issue based on the need for truncation as listed in the updated description? Since this is a need across all Calcite Input components let me know if you suggest re-opening all 5 specific issues or if we can track the 5 inputs in this single issue. Thank you!

**Comment by geospatialem** [comment]
> Hi @geospatialem Can we reopen this issue based on the need for truncation as listed in the updated description? Since this is a need across all Calcite Input components let me know if you suggest re-opening all 5 specific issues or if we can track the 5 inputs in this single issue. Thank you!

@SkyeSeitz Looks like we've got a list above of all 5 inputs, so we could leverage this one issue. LMK if that works, otherwise we can organize additional issues later this week.

**Comment by geospatialem** [comment]
Due to staffing availability, reallocated to November to tackle. A developer should be assigned early in the milestone to ensure it lands earlier in the milestone.

**Comment by anveshmekala** [comment]
Can we add calcite-text-area to the list ?

**Comment by jcfranco** [comment]
@geospatialem @brittneytewks Lowered the estimate for this one. I think we can use the [`:placeholder-shown`](https://caniuse.com/css-placeholder-shown) pseudo class for this.

**Comment by jcfranco** [comment]
I've submitted a PR that updates all inputs from the list above. While I did update `input-date-picker` and `input-time-picker` I noticed that these will only truncate when a user is typing an unrealistic value and blurs the input. The breakpoint stories will need to be updated when they support interactions to mimic the scenario I mentioned to properly show truncation. cc @SkyeSeitz @ashetland

**Comment by jcfranco** [comment]
Forgot to mention that I added `calcite-text-area` to the list as @anveshmekala suggested, but LMK if we need to move to a separate issue. 

@anveshmekala Do you have bandwidth to pick up text area's truncation?

**Comment by anveshmekala** [comment]
>@anveshmekala Do you have bandwidth to pick up text area's truncation?

Yep.

**Comment by ashetland** [comment]
@jcfranco Hmmm, yeah not sure how much sense this makes on Input Date/Time Picker. I thing I'd expect invalid text to be removed from these onBlur? For the placeholder at least, I does look like we need to add a gap before the dropdown chevron. Both Input Pickers look like this in this edge-case width:
![CleanShot 2023-11-13 at 09 25 08@2x](https://github.com/Esri/calcite-design-system/assets/108549080/50b3261f-931a-49a3-a52f-77e98fac8bb7)

**Comment by ashetland** [comment]
Also not sure it would make sense from the design perspective. I'd expect entered text to be clipped and scrollable like it is now.

**Comment by jcfranco** [comment]
Removed `text-area` from the list per @anveshmekala and @ashetland's recommendation. 🤜💥🤛

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.3`, where the list below of components are supported down to 300px:
-  Input
- Input Text
- Input Number
- Input Date Picker
- Input Time Picker

![image](https://github.com/Esri/calcite-design-system/assets/5023024/5d6ea0bf-426d-49a6-8544-ede7ce4b2e99)
