### ISSUE TITLE
[Pagination] Responsive layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6687]
### Description

Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
 2. Components need to be designed for the following breakpoints:
- [ ] Small (s), `476px`
- [ ] Medium (m), `768px`
- [ ] Large (l), `1152px`
- [ ] Extra larger (xl), `1440px`

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`pagination`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today: 
@rmstinson presented iterations for a Pagination on smaller screen sizes and mobile devices. Below is the solution we landed on, which Mike will refine before our final design proposal. 

<img width="917" alt="image" src="https://user-images.githubusercontent.com/29716057/228684378-55d28182-72ae-4623-a223-8e8c03633453.png">


_Additional action items for the team: Look at how this could also be used on desktop size viewports._

**Comment by rmstinson** [comment]
Added another section with final revisions! Figma link here: https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?node-id=13257%3A304540&t=sQkUqpbjmja9kXmQ-1

Here are the screenshots of the three options for screen widths ranging from 320px-479px. Full designs in the Figma link above :) 

<img width="1206" alt="Screenshot 2023-03-31 at 2 16 59 PM" src="https://user-images.githubusercontent.com/12650705/229232919-2a9fc570-c4f3-41e9-9951-bc98091fd9d4.png">

**Comment by macandcheese** [comment]
Some feedback - I like `A` in the screen above the best. It keeps the touch area for back and forth close together and anchors the controls to the sides - `B` and `C` don't seem to be visually as well spaced.

I would be interested to see a combination of the location of the `<` `>` in `A` with another text treatment. 

Not a huge fan of the caret or the blue color, I wonder if we can look at some other styles for that button? Maybe treating the "100" differently than the "of 199" like the `B` example (we could treat the entire area as a larger hit area).

**Comment by ashetland** [comment]
I lean most toward [A] as I look at these more. I through together a couple quick riffs based on [A] to add to the mix. I flipped the element order here as an exploration, but could go with the original order as well.
<img width="1068" alt="CleanShot 2023-04-03 at 08 32 19@2x" src="https://user-images.githubusercontent.com/108549080/229558037-1b167529-f320-46f3-8acd-b8271f1f1dec.png">

Also, I thought this would be some good food for thought since we talked about "items per page at one point" (may be out of scope here). I found what the Carbon team chooses to display at different widths interesting:
<img width="708" alt="CleanShot 2023-04-03 at 08 19 53@2x" src="https://user-images.githubusercontent.com/108549080/229559843-88261254-52f0-436e-80b6-933ffc1dd2cb.png">
<img width="411" alt="CleanShot 2023-04-03 at 08 19 32@2x" src="https://user-images.githubusercontent.com/108549080/229559855-c062ac63-e68d-457d-9121-363f470e1f22.png">

**Comment by SkyeSeitz** [comment]
I lean towards the flipped order with chevron back/forward controls. Explored a slightly different caret+txt treatment with spacing overrides. Could totally use `calcite-select` component as we discussed:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/29716057/229590745-f9e49d1a-0d9d-4e98-a44e-3d1dfd32c585.png">

**Comment by macandcheese** [comment]
[](https://media3.giphy.com/media/l0Ex9w7OHj6M3ieK4/giphy.gif)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
@rmstinson to add `compact, chevrons-start | chevrons-end` variants to all three scales. 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/29716057/232855293-295f9f26-86ff-4e36-ba6a-ea58be8dff10.png">

**Comment by rmstinson** [comment]
Added the mobile pagination in the Figma file - here's a screenshot of the variants, including the Popover+list for the page selection:

<img width="586" alt="pagination-mobile-pic" src="https://user-images.githubusercontent.com/12650705/233437474-63353022-140f-4ec5-b678-a4727be5912a.png">

**Comment by SkyeSeitz** [comment]
Final design proposal for compact variations can be found [here](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?type=design&node-id=13439%3A317512&t=RSl3UaLdMiwqdDs0-1).

**Comment by rmstinson** [comment]
Not sure if it's needed, but here are the breakpoints for the component:

![pagination_breakpoints](https://github.com/Esri/calcite-components/assets/12650705/03252f10-8cb7-47ee-9547-2427f9469176)

**Comment by driskull** [comment]
Is there a way we can have the menu be a button in some cases instead of a menu to select a page?

Here is our current usage:

![Aug-10-2023 13-30-57](https://github.com/Esri/calcite-design-system/assets/1231455/5a48ff7f-00b7-4410-85ab-71729512801b)


![Aug-10-2023 13-36-31](https://github.com/Esri/calcite-design-system/assets/1231455/23f101d4-31a8-4b84-82a6-01071f2f3508)


In some cases its not pages but results and its better to select a result by looking at its title rather than just a number.

**Comment by driskull** [comment]
@asangma should we redesign the current popup pagination to look more like this with the pagination arrows on the far right and the button on the far left?

**Comment by asangma** [comment]
It looks like the pagination design has evolved since my last sync with Calcite on this.
We'll have to see what it looks like in the Features widget.

**Comment by asangma** [comment]
The design works nicely when it has room to breathe.
Seems like it might suffer in more compact scenarios like Features and by extension Popup.
<img width="393" alt="image" src="https://github.com/Esri/calcite-design-system/assets/12503298/43a5c786-9131-441c-9c27-d088b9818183">

**Comment by driskull** [comment]
I'm not sure the `Popover+list` is the best way to go about a selection of pages. Why not the `calcite-select` component?

The `Popover+list` is essentially a role of dialog and a role of treegrid inside of it. Its also focus trapping. I would expect a single component here that can be operated with just arrow keys once tabbed into.

@SkyeSeitz @rmstinson @geospatialem can you comment on the above?

**Comment by driskull** [comment]
I think it would also be good if we have an option to turn off the pagination menu. What do you think?

**Comment by macandcheese** [comment]
Agreed - I think that complex of an interaction is outside the scope of a Calcite Components pagination component. I'd expect Pagination to be limited to (at the most), page selection, "page size / items per page" selection, and direct page selection.

Launching a "rich detail" list of Pagination options like in the above widget is valid UI, but I think it's something you could build separately, as the content could be drastically different depending on need. Like @driskull mentioned, I think that particular UI could probably use a dropdown, having an entire Panel header UI there in a List seems kind of heavy.

**Comment by driskull** [comment]
Do we want to kick this issue back to design? its slotted for the current responsive milestone. cc @brittneytewks

**Comment by macandcheese** [comment]
Will defer to @SkyeSeitz but I think the plan is to add additional display modes and the responsive behavior will be to collapse the number of visible "page steps" as container size shrinks.

I don't think this component needs to consider having UI of "launch a list or dropdown or other component to have a rich selection". That IMO is not really part of pagination.

**Comment by driskull** [comment]
Maybe a user could just slot in something that displays at the xs size? Then they could add a menu/button/whatever?

**Comment by macandcheese** [comment]
Yeah. I think at any size really, just place that adjacent to the pagination, pagination’s responsive adjustment  could just be reduce number of pages shown as needed. The other view modes are good to have as an option at any viewport.

**Comment by SkyeSeitz** [comment]
Thanks for the thoughts above, folks. I am in agreement the first question is regarding scope of what we consider responsive- I would consider the following behavior a responsive Calcite Pagination component. 

https://github.com/Esri/calcite-design-system/assets/29716057/0b8a0014-853f-4ef6-bd18-4d5273e54bb8

**Comment by SkyeSeitz** [comment]
Updated [Figma link](https://www.figma.com/file/iCQBMp5Q5zlSfyE9NxkdO7/Pagination---responsive?type=design&node-id=310-9795&mode=dev) for responsive feature. 

Sounds like non-responsive features that are valuable at any viewport size, such as items per page or additional display modes, can be logged separate from this issue 👍🏽

**Comment by geospatialem** [comment]
Verified in `next` for all but very specific smaller XS dimensions. A follow-up issue was created for the specific size, anticipated for September/October.
