### ISSUE TITLE
[Segmented-control] Responsive Layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6688]
**Description**
Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

**Acceptance Criteria**
 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
 2. Components need to be designed for the following breakpoints:
- [ ] Small (s), 476px
- [ ]  Medium (m), 768px
- [ ]  Large (l), 1152px
- [ ]  Extra larger (xl), 1440px

**Relevant Info**
Part of epic https://github.com/Esri/calcite-components/issues/6670

**Which Component**
`segmented-control`

**Example Use Case**
No response

**Priority impact**
p4 - not time sensitive

**Esri team**
Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
@jacqueskeet presented iterations for Segmented Control on smaller screen sizes and mobile devices. We identified suggested patterns for users to follow with already provided or planned (issue #6413) functionality. 

_**Next steps:** Jacques will document these patterns and share with the team_

<img width="904" alt="image" src="https://user-images.githubusercontent.com/29716057/230460168-32a6ad2a-9053-4fb8-a26c-eacb4de053a6.png">

**Comment by SkyeSeitz** [comment]
@jacqueskeet's documentation for Segmented Control usages on smaller viewports can be found [here](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?node-id=1770-116475). 
This content is ready for us to pick up when adding best practice documentation to Segmented Control on [developers.arcgis](https://developers.arcgis.com/calcite-design-system/components/segmented-control/)

**Comment by SkyeSeitz** [comment]
@geospatialem internal issue has been logged if we want to close this one out :)

**Comment by geospatialem** [comment]
Per the [note above](https://github.com/Esri/calcite-design-system/issues/6688#issuecomment-1644722714) closing out this issue for a documentation usage update.
