### ISSUE TITLE
[Tile] Responsive Layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6690]
### Description

Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
2. Components need to be designed for the following breakpoints:

- [ ] Small (s), 476px
- [ ]  Medium (m), 768px
- [ ]  Large (l), 1152px
- [ ]  Extra larger (xl), 1440px

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`tile`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
I will be rolling responsive layout considerations into the [Tile redesign epic ](https://github.com/Esri/calcite-components/issues/6662) in June.

**Comment by SkyeSeitz** [comment]
Link to Figma Specs: https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A2738&mode=dev

**Comment by geospatialem** [comment]
Closing as effort will instead focus on responsive layout with the effort of the `tile` redesign and new component `tile-group` in https://github.com/Esri/calcite-design-system/issues/6662 and https://github.com/Esri/calcite-design-system/issues/8615 respectively.

**Comment by geospatialem** [comment]
Verified with https://codepen.io/geospatialem/pen/zYbQZYx in `2.5.1` for the `alignment` and min and max widths for each scale. Updated context is #6662.
