### ISSUE TITLE
[Tile Group] Responsive layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6691]
### Description

Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

#### Task breakdown:
- [ ] https://github.com/Esri/calcite-design-system/issues/8615

1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
2. Components need to be designed for the following breakpoints:

- [ ] Small (s), 476px
- [ ] Medium (m), 768px
- [ ] Large (l), 1152px
- [ ] Extra larger (xl), 1440px

### Which Component

`tile-group`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
I will be rolling responsive layout considerations into the [Tile redesign epic ](https://github.com/Esri/calcite-components/issues/6662) in June.

**Comment by SkyeSeitz** [comment]
Link to Figma specs: https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A2738&mode=dev

**Comment by eriklharper** [comment]
> I will be rolling responsive layout considerations into the [Tile redesign epic ](https://github.com/Esri/calcite-components/issues/6662) in June.

Since this is part of the Tile redesign epic, does that mean we won't apply responsiveness changes to the planned-to-be-deprecated Tile Select Group/Tile Select components?

**Comment by SkyeSeitz** [comment]
Discussed and decided to roll responsiveness into the Tile & Tile Group redesign to avoid applying new functionality to Tile Select and Tile Select Group which will be deprecated shortly after in favor of Tile and Tile Group.

**Comment by geospatialem** [comment]
Closing as effort will instead focus on responsive layout with the effort of the `tile` redesign and new component `tile-group` in https://github.com/Esri/calcite-design-system/issues/6662 and https://github.com/Esri/calcite-design-system/issues/8615 respectively.
