### ISSUE TITLE
[Checkbox] Responsive Layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6692]
### Description

Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
2. Components need to be designed for the following breakpoints:

- [ ]  Small (s), 476px
- [ ]  Medium (m), 768px
- [ ]  Large (l), 1152px
- [ ]  Extra larger (xl), 1440px

### Which Component

`checkbox`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
Checkbox needs a size adjustment on the large scale for use on small screen and mobile devices. The following proposal is to change the large 16px Checkbox to 18px with a 44px hit target.
<img width="297" alt="image" src="https://user-images.githubusercontent.com/29716057/236292391-f454d671-f426-4ca1-8725-19b4df1e3c32.png">
[Link to specs](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?node-id=1616%3A113187&t=G1UGmY26oFahPopH-1)

**Comment by SkyeSeitz** [comment]
Updated [Figma file](https://www.figma.com/file/RB5r1PlfjOxRBgx4aA00cq/Checkbox---responsive-%5B6692%5D?type=design&node-id=1%3A2&mode=design&t=ynQz9Cciv1wv04SD-1) with AA hit target at 24px 🚀

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.7` with `checkbox` and `card` when `selectable`, where the differing sizing of `--calcite-checkbox-size` will adjust to the `24px` hit target at a minimum.
