### ISSUE TITLE
[Shell] Responsive layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6693]
### Description

Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
 2. Components need to be designed for the following breakpoints:

- [ ]  Small (s), 476px
- [ ]  Medium (m), 768px
- [ ]  Large (l), 1152px
- [ ]  Extra larger (xl), 1440px

### Which Component

`shell`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
Related work that should solve for this:  https://github.com/Esri/calcite-components/issues/6449

**Comment by SkyeSeitz** [comment]
Manuela's [mock ups ](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?type=design&node-id=13620%3A283096&mode=design&t=NXmCEDNssHx1p9Q0-1)of the patterns above.

**Comment by macandcheese** [comment]
@SkyeSeitz what here is actionable? All of the widths can be customized via css. Having better defaults re: https://github.com/Esri/calcite-design-system/issues/7616 could help.

I think there's merit to a "collapsed but has a toggle to open" Shell panel affordance but it is separate responsive behavior as it could be useful at any viewport size.

**Comment by SkyeSeitz** [comment]
> @SkyeSeitz what here is actionable? We've added some features to Shell Panel since this was opened. All of the widths can be customized via css. The "show / hide UI" is an app-level pattern that can be achieved with existing components. Map Viewer does this I believe.
> 
> Having better defaults re: #7616 could help any issues with width.
> 
> I think there's merit to a "collapsed but has a toggle to open" Shell panel affordance but it is separate from responsive behavior effort as it could be useful at any viewport size, and should just be a separate enhancement.

You are right - the proposed enhancements have since then been covered in other issues or are possible at the app level 🚀
All that would be left is considering adding documentation for responsive best practices, which ideally would be separate effort. 

@geospatialem We can close out this issue as complete.

**Comment by geospatialem** [comment]
@SkyeSeitz as far as documentation, is there anything we can document (😆) on the documentation effort prior to closing the issue out?

**Comment by macandcheese** [comment]
I think we could have a new, separate low-priority enhancement issue for "collapsed Shell Panel" affordance that collapses the slotted Panel AND action bar and provides an affordance to show it again, but nothing specifically for mobile.
