### ISSUE TITLE
[Stepper] Responsive layout

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6694]
### Description

Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
2. Components need to be designed for the following breakpoints:

- [x]  Small (s), 476px
- [x]  Medium (m), 768px
- [x]  Large (l), 1152px
- [x]  Extra larger (xl), 1440px

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`stepper`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
I presented iterations for a Stepper on smaller screen sizes and mobile devices. Below is the solution we landed on, which I will refine before our final design proposal with additional variants and vertical orientation.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/229244718-675e8645-bcdb-46d4-ac73-0d8c3dfa8ece.png">

**Comment by SkyeSeitz** [comment]
Added [all variants](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?node-id=3624%3A105603&t=mjOP1jFnYACx7TSE-1) for us to review in Tuesday's meeting with a few follow up questions. 
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/29716057/231034037-0439bbf9-8038-4cf6-9629-7ecf8a5deb35.png">

**Comment by geospatialem** [comment]
Verified on `2.0.0-next.1` with default, `numbered`, `icon`, and `numbered` w/ `icon`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a9bdbd0d-058a-4ac9-a896-4f86b5b2ff49)
