### ISSUE TITLE
Have a clearer unselected state in Calcite List 

### ISSUE THREAD

**Issue by CodeBarker** [Esri/calcite-design-system#6700]
### Description

We've had users share that the unselected state of the calcite list doesnt immediately communicate it is selectable.  When one or more items is selected by default it is not as critical, However for lists where there is no default selection it just looks like empty space and users are confused

#### Current 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3944714/228623592-0f83a54c-c26f-4a19-ba37-d153450e2c01.png">

#### Desired
<img width="412" alt="image" src="https://user-images.githubusercontent.com/3944714/228623989-0c4e5b2c-3891-46a2-9259-543a834f5618.png">

### Which Component

calcite list / calcite list item 

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment]
@asangma Agreed, either using the circle-empty + check-circle-f or square and square-check-f here would clear this up.

**Comment by asangma** [comment]
@macandcheese I could also see something like an `appearance="minimal"` or something that would mimic PickList's selection indicators but with an added hover state that shows the check or dot. I can add mockups if that's helpful.

**Comment by asangma** [comment]
💯

**Comment by asangma** [comment]
And yeah...the spacing needs some love. :)

**Comment by asangma** [comment]
Suggested spacing between the selection icon and the text:
Use the same spacing that Button has between its content and icon...and maaaaybeee that spacing could be a little tighter (0.5rem for medium)? 😬

**Comment by hcampos-esri** [comment]
Another feedback we got, specifically with regards to the `selection-appearance="border"` was that the focus highlight and the border can cause confusion. When the focus outline is visible, it seems as though the list item is selected.
![1a7938f1-da23-4b3f-b404-5fb74ee86225](https://github.com/Esri/calcite-design-system/assets/136828178/b60a0ce0-3d75-4fad-88e7-a2efbc1da8ae)
![dbd3d086-456e-4656-bf55-9f8da73e333b](https://github.com/Esri/calcite-design-system/assets/136828178/34c09e98-5802-44cd-b6cd-0c9d83a84363)

**Comment by Anastasiia-Boleiko** [comment]
Hi there👋
Also, some feedback regarding the List component😉. 
In our case, we were also playing a bit with styling of the List to adjust it to our needs and realized, that the icon selection-`appearance="icon"` adds quite a large gap before the label, so we decided to proceed with a selection-`appearance="border"`. But it would be really nice to have an additional "flag" that shows a selection. Just as an idea: add a background (on the screenshot it's a ui-brand with 0.1 opacity).
<img width="200" alt="Screenshot 2023-07-06 at 16 44 13" src="https://github.com/Esri/calcite-design-system/assets/119309703/351eeab2-693a-402d-8fdc-381d1ae2ed9a">

**Comment by RSantosGIS** [comment]
From my comment in Teams:

Hey Calcite, good morning.  I was wondering, is there a way to get actions in slots for CalciteList to have the same hover behavior as block?  Calcite Block only does hover styling on the action, and stops propogation to the parent (so the whole block isn't also hover-styled).  List, however, appears to propagate the hover to the parent, which causes the whole list element to be hover highlighted except sibling actions it also creates an unattractive "border" around said sibling, like so (my mouse is hovering the ellipsis action, as indicated by the red dot):
![MicrosoftTeams-image (10)](https://github.com/Esri/calcite-design-system/assets/36513418/f0176e22-e7ea-40d3-b7a9-4513783295b3)

**Comment by ashetland** [comment]
[Figma designs](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---icon-%26-hover-consistency-%5B7181%5D?type=design&node-id=1004-10047&mode=dev) available for updated selection iconography and tweaks to the border selection appearance to retain visibility when focused. Related designs for other components are included for reference. We plan to look more deeply at hover states as part of a future system-wide appearance effort.

**Comment by driskull** [comment]
This one would be nice to bump priority on.

**Comment by ashetland** [comment]
Agreed.

**Comment by driskull** [comment]
I don't think this one is "ready for dev" right?

**Comment by geospatialem** [comment]
> I don't think this one is "ready for dev" right?

@driskull It looks like it was marked ready with the [following Figma resources](https://github.com/Esri/calcite-design-system/issues/6700#issuecomment-1714679947) without the hover states. cc @ashetland

**Comment by ashetland** [comment]
Yep see [this comment](https://github.com/Esri/calcite-design-system/issues/6700#issuecomment-1714679947). Lot's of improvements outlined in that file that address the selected-state issues outline above. Hover treatments should be looked at separately.

**Comment by driskull** [comment]
Ok sounds good!

**Comment by driskull** [comment]
Just curious, why not radio button icons for the single select mode?

It seems like the clearer unselected state would still be an issue when in single selection as only one circle filled in circle icon would be shown.

**Comment by driskull** [comment]
> When focus ring is active, increase width to 6px to retain visibilty

I don't think there is a token value for a 6px value. Should we get one added? cc @alisonailea 

I only see `borderWidth.4`. It doesn't go bigger than that.

**Comment by ashetland** [comment]
> Just curious, why not radio button icons for the single select mode?
> 
> It seems like the clearer unselected state would still be an issue when in single selection as only one circle filled in circle icon would be shown.

We got feedback that folks preferred the dot, but that was before Table took the icon approach. Should discuss with @SkyeSeitz and @macandcheese. If we prefer the circles, I can update the design file.


> I don't think there is a token value for a 6px value. Should we get one added? cc @alisonailea
> 
> I only see `borderWidth.4`. It doesn't go bigger than that.

Yep, we'll need to add a token for that one.

**Comment by driskull** [comment]
Thanks @ashetland, let me know about the icons. I would think that if the `"unselected state of the calcite list doesnt immediately communicate it is selectable"` is an issue with the checkmarks it would also be an issue for the radio.

Do we need an issue for the token? If so, can we get one created

**Comment by ashetland** [comment]
We'd like to align with the single selection modes of Dropdown, Combobox, and Tree. In all these cases with the added hover interaction (ghosted dot/border), the selectable affordance becomes more obvious and is easily learned without the repetitive noise of the empty circles on all the items. We would like to reserve the empty container for an actual checklist (selection-mode=“multiple”).

**Comment by ashetland** [comment]
> Thanks @ashetland, let me know about the icons. I would think that if the `"unselected state of the calcite list doesnt immediately communicate it is selectable"` is an issue with the checkmarks it would also be an issue for the radio.
> 
> Do we need an issue for the token? If so, can we get one created

We've decided to forego dynamically changing the border selection indicator width onFocus for now as it produced less than desirable effects. The new font weight change when `selected` should still help differentiate selection states when focused.

**Comment by DitwanP** [comment]
🍬 Verified locally on `main`

**Comment by ethanbdev** [comment]
Hey all, with this issue the default hover pointer was changed for the list item - would it be possible to keep that and re-visit hover states? Maybe checking with folks?

We have discussed before we have a pattern of using the list item in the style of a button for a flow-like ux. I can try track down other discussions we have had on this

![image](https://github.com/Esri/calcite-design-system/assets/52869490/98aeeb6d-5bb5-46b8-8aaa-286c25fa28e0)

**Comment by driskull** [comment]
@ethanbdev for the hover to be present, the selctionMode should be set to something other than "none". Otherwise this could be done using CSS token variables.

**Comment by ethanbdev** [comment]
Related: https://github.com/Esri/calcite-design-system/issues/6123

**Comment by ethanbdev** [comment]
> @ethanbdev for the hover to be present, the selctionMode should be set to something other than "none". Otherwise this could be done using CSS token variables.

Hey, I linked the issue with the original discussion on this, will that no longer be supported?

**Comment by macandcheese** [comment]
Another option here is Menu Items, here is an example from the documentation with Flow / Flow Item and Menu / Menu Item: https://codepen.io/mac_and_cheese/pen/qBvrQOz?editors=1000

**Comment by mpayson** [comment]
I think the challenge is our apps are using calcite-list like a list of buttons, not as a list of dependent selectable items or non-interactive elements. This pattern is relatively common in our apps right now, and it looks like is part of the Figma designs for this issue (selectionMode="none" has hover and pressed states)

If it's helpful, another area this pattern is used in web analysis is to show a list of input layers, where clicking on the layer should open a dialog to replace that layer, and clicking the slotted "x" should remove that layer from the list

<details> 
<summary> Screenshot </summary>

<img width="848" alt="Screenshot 2024-01-17 at 6 03 04 PM" src="https://github.com/Esri/calcite-design-system/assets/5892789/afe3b0d8-1dbd-4430-8662-592f2d9f9c6e">

</details>

**Comment by geospatialem** [comment]
Reopening to revert the installation above, and discuss alternatives for future implementation to ensure precious support mentioned in https://github.com/Esri/calcite-design-system/issues/6700#issuecomment-1896911919 and https://github.com/Esri/calcite-design-system/issues/6700#issuecomment-1897391994.

The revert will be part of an upcoming maintenance release targeted prior to R1. cc @ethanbdev @mpayson

**Comment by macandcheese** [comment]
@mpayson not sure if this changes the selectionMode need, but I do find it strange the List Item itself is triggering that Replace Layer action. It seems like something that could be invoked from an action within the List Item itself:

<img width="411" alt="Screenshot 2024-01-17 at 3 45 32 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/f20b4bfa-a176-474f-bb53-c9857ec4dc20">

**Comment by geospatialem** [comment]
The default hover pointer change has been reverted and is verified in `2.2.1-next.1` with https://codepen.io/geospatialem/pen/XWGaopO.

![cursor](https://github.com/Esri/calcite-design-system/assets/5023024/216ac8ae-e4e8-4114-a241-6a6d4378639e)

A new issue has been created to add a new selection mode in the future, while also supporting the pointer, via #8634.

Closing the above as verified.
