### ISSUE TITLE
Radio button labels should hug text content in radio button groups

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#6703]
### Actual Behavior

By default, the child elements of a `<calcite-radio-button-group>` are stretched to fill the full width of their parent. If the children are labels, this can mean a significant amount of white-space has a hidden behavior of selecting a radio button if the user happens to click in it.

### Expected Behavior

Only clicking the label's text content should select its assoc. radio button. Alternatively, if it's more usable, all labels are the same width as the widest label.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/oNPOVzL

### Reproduction Steps

1. Visit the sample and compare the observed vs. expected fieldsets.
2. Click anywhere in the cyan area to select a radio button.

### Reproduction Version

1.2.0

### Priority impact

p4 - not time sensitive

### Impact

Styling the radio-group manually is an easy workaround, but not readily apparent since labels typically have transparent backgrounds.

Similar usability/ergonomic problems as described in https://github.com/Esri/calcite-components/issues/6702.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Due to the wide use of `label`, team members will work towards a deprecation in the coming months and plan out a breaking change with a future release. A milestone will be assigned in the coming weeks.

**Comment by jcfranco** [comment]
The approach from #9793 doesn't require any changes to `label` and would no longer be a breaking change. 🎉 cc @macandcheese

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.14`

<img width="531" alt="Screenshot 2024-07-17 at 1 06 28 PM" src="https://github.com/user-attachments/assets/58bac300-f62a-4942-9bce-4551fd74c5a8">
