### ISSUE TITLE
Need option to remove overlay for modal and be able to move it

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-design-system#6704]
### Description

In our app we have many instances of dialogs that can be shown at a specified position on the screen and can be moved and resized (optional). We hacked the existing `modal` component to achieve this result.
Using `popover` will not work as well, because even though it doesn't have any overlay, you can't really move it.

**Could you suggest how to use Calcite for this case?**

![image](https://user-images.githubusercontent.com/5318527/228804190-febe4dd0-c19d-491d-87ad-e7bcacc21049.png)

### Acceptance Criteria

The following options would be appreciated.

- Ability to show the dialog without its overlay and at a specified position on the screen.
- Ability to move the dialog by dragging it by the top header.
- Ability to resize the dialog.

The problem is that if you add these properties the `modal` will stop being `modal` but will have to be called `dialog` or something.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/modal/

### Example Use Case

See the description above.

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Business/Community Analyst

**Comment by geospatialem** [comment]
Closing in favor of the `dialog` and `modal` effort in https://github.com/Esri/calcite-design-system/issues/7886.
