### ISSUE TITLE
[number input] property to allow integers only

### ISSUE THREAD

**Issue by JonUihlein** [Esri/calcite-design-system#6706]
### Description

Add a property to `<calcite-number-input>` to only allow integers (no decimals).

Alternatively, adding a `places` property to control significant figures might be interesting (with `0` also forcing integers only). 

### Acceptance Criteria

In most cases, this would simply prevent users from typing `.` and `,`.
Invalid values supplied via the constructor, programmatically, or via a direct copy+paste could either be rounded or ignored. 

### Relevant Info

Currently, we must enforce this ourselves by overriding "bad" values in the associated `onchange` event.

Inspired by:
https://github.com/Esri/calcite-components/issues/2009#issuecomment-839204684

### Which Component

`<calcite-input-number>`

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by hgonzago** [comment]
The `maximumfractiondigits` property in `Intl.NumberFormat` takes care of this.

**Comment by JonUihlein** [comment]
Actually, this seems like a regression.

`<calcite-input type="number" />` prevented decimals in a previous release:
https://codepen.io/jonuihlein/pen/JjaqrJe

`<calcite-input type="number" />` and `<calcite-input-number />` allowing decimals by default:
https://codepen.io/jonuihlein/pen/NWLVaRr

This change in default behavior changed might have been outlined in release notes, but how do we go back to the previous behavior of "integers only"?

**Comment by geospatialem** [comment]
> @geospatialem is there someone we can assign this too, or get an update? This use to work before as @JonUihlein mentioned. This behavior is preventing a migration to use this calcite input in Editor for the JS SDK. Thanks!

@banuelosj thanks for re-pinging this enhancement request - we're targeting this for the upcoming August milestone. cc @hgonzago

**Comment by hgonzago** [comment]
Thanks @geospatialem 👍

**Comment by jcfranco** [comment]
@benelan Can you take a look at this one?

**Comment by benelan** [comment]
> The `maximumfractiondigits` property in `Intl.NumberFormat` takes care of this

![](https://i.imgflip.com/7xakt0.jpg)

Every single time...

**Comment by geospatialem** [comment]
Verified in `1.7.0` with:

### Only integers (result = 55)
```html
<calcite-input-number integer value="5.5"></calcite-input-number>
```

### Floats allowed  (result = 5.5)
```html
<calcite-input-number value="5.5"></calcite-input-number>
```
