### ISSUE TITLE
[Testing] Add helper / preferred pattern testing `selectedItem/s` property value

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6713]
Where `selectedItem/s` properties are tested - each component implementing these tests currently has a different pattern for checking this value and comparing to expected elements.

Dropdown: https://github.com/Esri/calcite-components/blob/09a1bbbe575ab2ea3f52f39b18010f2807962c39/src/components/dropdown/dropdown.e2e.ts#L57
List: https://github.com/Esri/calcite-components/blob/6253ef4fea28663875195f610613a1e5443b7b66/src/components/pick-list/shared-list-tests.ts#L16
Stepper: https://github.com/Esri/calcite-components/blob/b94414b48904903774f40560cbfc6bf3e4e819ab/src/components/stepper/stepper.e2e.ts#L443

It would be nice to have a shared utility / helper for this to use across all tests.

### Additional Info
Follow up issue from Teams chat with cc @jcfranco

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/9243. Closing as self-verified!
