### ISSUE TITLE
New `position` property for Modal component

### ISSUE THREAD

**Issue by Anastasiia-Boleiko** [Esri/calcite-design-system#6734]
### Description

Currently, Modal components are centered both horizontally and vertically.
But when a modal has dynamic content (so potentially different body content height), modal content "moves" (jumps) in 2 directions (to top and to bottom) due to being centered vertically.

### Acceptance Criteria

The Modal component has a property that allows to set TOP, CENTER etc position.

### Relevant Info

Example: https://atlassian.design/components/modal-dialog/examples

### Which Component

Modal

### Example Use Case

Modal dialog with tabs and different content heights.

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Urban

**Comment by geospatialem** [comment]
Closing in favor of the `dialog` and `modal` effort in https://github.com/Esri/calcite-design-system/issues/7886, which is currently aimed to support a `placement` property.
