### ISSUE TITLE
List: when filtered additional up/down arrow keystrokes required to focus past unfiltered (hidden) list-items

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#6736]
### Actual Behavior

When a list is filtered and the up/down arrow keys are used to select list-items extra up/down keystrokes are required to focus next list-item if unfiltered (hidden) list-items are between filtered list-items.

This might also be an accessibility issue. I'm not familiar enough to say for certain.

### Expected Behavior

One up/down keystroke to focus the next filtered (visible) list-item.

### Reproduction Sample

https://codepen.io/COV-GIS/pen/mdzdyZq

### Reproduction Steps

See sample.

Oddly, in the sample on first arrow down after filtering it skips to the second list-item. I have not observed this behavior in the component I'm working on where I noticed the behavior noted above.

### Reproduction Version

1.2.0

### Priority impact

p4 - not time sensitive

### Impact

It does not. Just reporting.

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.28`:

![verify-list-filter-arrow-keys](https://github.com/Esri/calcite-design-system/assets/5023024/62828dc7-a9d8-496f-81bc-02d18e9508c7)
