### ISSUE TITLE
[Combobox] Unexpected keyboard navigation with arrow keys

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6750]
### Actual Behavior

When using Combobox in Multiple selection mode, navigating through the Chips with arrow keys produces unexpected behavior.

Using the arrows to navigate after entering Chip area with keyboard, focuses the chip in the wrong direction. Additionally, at some times the placeholder text disappears

### Expected Behavior

I would expect the arrow keys to navigate correctly, and not have the placeholder text occasionally disappear as I interact with the chip focus with arrows.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/KKGKbpy?editors=1000

### Reproduction Steps

1. Open Codepen
2. Use `Tab` to focus Combobox - first chip's close button will be focused first.
3. Use `Tab` again to focus the second chip's close button.
4. Use `Left Arrow` - expect to see the first chip's close button focused.
5. Instead, the third chip's close button is focused.
6. Notice that the placeholder text occasionally disappears while using keyboard arrows

### Reproduction Version

1.2.0

### Relevant Info

https://user-images.githubusercontent.com/4733155/230530328-f4280bbb-79b8-4b3e-b3da-1045fd3e7e9c.mov

### Priority impact

p2 - want for current milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Related and could be approached together, possibly with `chip-group` as a refactor https://github.com/Esri/calcite-design-system/issues/6776 + https://github.com/Esri/calcite-design-system/issues/6777

**Comment by macandcheese** [comment]
We also might want to disallow opening the dropdown via down arrow while a Chip's close button is in focus.

**Comment by driskull** [comment]
This may have been fixed in #6776. cc @DitwanP

**Comment by driskull** [comment]
It looks like the input is made transparent when a chip is actively focused. Anyone know why that is? cc @paulcpederson @macandcheese  

```
"input--transparent": this.activeChipIndex > -1,
```

Is there a valid reason to not show the placeholder when a chip is being focused?

**Comment by macandcheese** [comment]
I don't think so, I'd expect it to remain visible. In the video in the original post above it seems to happen only when the Chip closest to the input has its close button focused. Not sure if its changed since that video however.

**Comment by paulcpederson** [comment]
I think the interaction behavior was modeled after https://mui.com/material-ui/react-autocomplete/#multiple-values

**Comment by driskull** [comment]
@paulcpederson @macandcheese should we get design's opinion here? I'd prefer to remove it if possible but would like their approval.

cc @SkyeSeitz @ashetland

**Comment by ashetland** [comment]
Agreed, looks like a bug to me.

**Comment by driskull** [comment]
Thanks @ashetland. PR to remove it is ready.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
