### ISSUE TITLE
text-area: add validation with `label` requirement + `invalid` prop for invalid text area styles

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-design-system#6770]
### Description

We'd like to move our textareas to use the new `calcite-text-area` component, but we are missing the `status` prop we had with `calcite-input`. 

### Acceptance Criteria
 `text-area` should have a status prop which allows setting invalid to show an error state with a message below. 

- [ ] Add Label* update to required prop
- [ ] Add invalid prop with triggers:
    - required
        - max-length exceeded
- [ ] Deprecate the `status` prop in favor of an `invalid` pop as they might not be needed for an `"idle"` or `"valid"` status
- [ ] Update invalid styling to a 2px bottom border, for instance (example below):

<img width="376" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/b24d6c4c-db7b-46d4-9310-7fb7d270da4a">

### Which Component

calcite-text-area

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Online

**Comment by jcfranco** [comment]
Related: https://github.com/Esri/calcite-components/issues/4598.

**Comment by geospatialem** [comment]
Repurposing the above request from the efforts of the validation epic mentioned [above](https://github.com/Esri/calcite-design-system/issues/6770#issuecomment-1506088709), where we will:
1. Add `Label`* update to **required** prop
2. Add **invalid** prop with triggers:
    - required
    - max-length exceeded

More information can be sought on the [Figma form validation file](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=956-94285&mode=design&t=tPqHJcVdxmJmZ6L2-0).

![image](https://github.com/Esri/calcite-design-system/assets/5023024/274a326c-4914-4d69-a64b-77cbdf332e21)

**Comment by geospatialem** [comment]
Closing in favor of the efforts completed in https://github.com/Esri/calcite-design-system/issues/8057, where the status property was added, along with an internal input-message for displaying validation messages.

Additional efforts will be completed in https://github.com/Esri/calcite-design-system/issues/8000 for setting the validity state of the component internally.
