### ISSUE TITLE
[Combobox] While focusing on Chip's close button, spacebar opens Combobox menu

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6777]
### Actual Behavior

When using Combobox, and focus is on a select item's representative chip's close button - using Space key will open the Combobox item dropdown. 

### Expected Behavior

I'd expect the Space key to close the chip (match Enter), as the Chip component in isolation does.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/combobox/

### Reproduction Steps

1. Open sample on dev site
2. Select some items from Combobox
3. Focus chip close button with keyboard
4. Use "Space" key
5. Combobox will open and chip will not close

### Reproduction Version

1.2

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Related and could be approached together with https://github.com/Esri/calcite-design-system/issues/6750 + https://github.com/Esri/calcite-design-system/issues/6776

**Comment by geospatialem** [comment]
It looks like the `combobox` still opens when using the spacebar on both Windows and Mac across browsers with https://codepen.io/geospatialem/pen/yLrMZWW. 

@Elijbet reassigning back to ya to take another peek to investigate what might be happening. 👀

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.15` 🎉
