### ISSUE TITLE
Multiple CalciteSegmentedControlItems Selected

### ISSUE THREAD

**Issue by brettephillips** [Esri/calcite-design-system#6799]
### Actual Behavior

When using the `onCalciteSegmentedControlChange` to update the selected item along with the checked property, something occurs in the hydration process causing multiple items to be selected. It seems as if the `checked` property remains even if it is set to `undefined`.

### Expected Behavior

I would expect only a single item to be selected

### Reproduction Sample

https://codesandbox.io/s/musing-banach-7txiso?file=/src/App.js

### Reproduction Steps

1. Open the provided link
2. Click the second item "Apple"
3. Notice that the third item "Pear" is also selected

### Reproduction Version

1.2.0

### Priority impact

p1 - need for current milestone

### Esri team

ArcGIS Velocity

**Comment by geospatialem** [comment]
It looks like the repro case above is showing an example with Accordion

@brettephillips Could you post an updated code sample for us to determine next steps with the `segmented-control`?

**Comment by geospatialem** [comment]
Closing in favor of #6860, where a repro sample is present and displays the workaround.
