### ISSUE TITLE
Fix test error caused by running t9n common test helper on input-date-picker

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#6812]
### Test type

unstable test

### Which Component(s)

input-date-picker

### Unstable Tests

`commonTests#t9n`

### Additional Info

Stems from https://github.com/Esri/calcite-components/pull/6669#issuecomment-1514993359:

> Something in the `input-date-picker` updates isn't meshing with the [locale switching assertion](https://github.com/Esri/calcite-components/blob/master/src/tests/commonTests.ts#L1047-L1081).

**Comment by jcfranco** [comment]
@AlexanderRyzhov Thanks for reaching out. I'd like to point out that the DatePicker widget from the ArcGIS JS SDK technically doesn't use `calcite-input-date-picker` internally. The `FeatureForm` widget does use `calcite-input-date-picker`, but it should still pick up the language if set in the browser or via `esriConfig` (unless [it's not supported](https://developers.arcgis.com/calcite-design-system/resources/localization/#calcite-supported-languages), in which case it will default to `en`). Could this be what you're observing?

**Comment by AlexanderRyzhov** [comment]
it's my fault, actually the problem is in `FeatureForm` widget, not `DatePicker` component. 
And the language in browser is Russian (ru), which should be supported.
Hope this helps.

**Comment by jcfranco** [comment]
I'll go ahead and close this as the test error was fixed in https://github.com/Esri/calcite-design-system/pull/6669.

@AlexanderRyzhov Apologies for the delayed reply, but if you're still observing localization issues with the `calcite-input-date-picker`, would you mind creating a new issue with an isolated repro case (without `FeatureForm`)? Thanks!
