### ISSUE TITLE
Accordion Item icons do not contain textLabel property

### ISSUE THREAD

**Issue by tannerjt** [Esri/calcite-design-system#6813]
### Summary

The [accordion item](https://developers.arcgis.com/calcite-design-system/components/accordion-item) contains `iconEnd` and `iconStart` properties, but there is currently no way to add [textLabel](https://developers.arcgis.com/calcite-design-system/components/icon/#api-reference-properties-textLabel) support for the rendered icon component.  The support for `textLabel` is desired for additional accessibility support on the current implementation of the accordion for the field info attribute list on [hub about pages](https://hub.arcgis.com/datasets/NIWA::the-ceratioid-anglerfishes-lophiiformes-ceratioidei-of-new-zealand/about)

<img width="738" alt="Screen Shot 2023-04-19 at 10 16 07 AM" src="https://user-images.githubusercontent.com/3883995/233150833-7e49e2ae-a642-4566-9658-5485590ba5b0.png">

### Actual Behavior

When using Voice Over with accordions, no information is available regarding the icon used on any accordion item.

### Expected Behavior

Information to be provided to the end user, when using Voice Over, that would describe the icon used for each accordion item.

### Reproduction Sample

https://hub.arcgis.com/datasets/NIWA::the-ceratioid-anglerfishes-lophiiformes-ceratioidei-of-new-zealand/about

### Reproduction Steps

1. Go to the example page provided, or to any accordion with accordion items that contain icons
2. Enable Voice Over utility
3. Observe the speech output

### Reproduction Version

v1.0.7

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
For a workaround in the interim... An `action` could be slotted with `actions-start` or `actions-end`, where the content is focusable to users: https://codepen.io/geospatialem/pen/zYMavzM. Content could also contain a `tooltip` with additional context. 

However, with the shadow DOM there isn't a way to add an `aria-label` for context, which could be part of a future solution.

**Comment by geospatialem** [comment]
Closing the above issue out with the workaround in https://codepen.io/geospatialem/pen/zYMavzM. If the workaround isn't sufficient or another use case needs to be achieved, the issue can be reopened, or a new issue opened.
