### ISSUE TITLE
[Combobox] filtering does not work when Item text labels are not unique

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-design-system#6814]
### Actual Behavior

When calcite-combobox contains multiple calcite-combobox-items with the same text-label, filtering breaks.

### Expected Behavior

I expect filtering to work.

### Reproduction Sample

https://codepen.io/mjuniper/pen/JjmRQpV?editors=1000

### Reproduction Steps

1. Click in the combobox
2. type "conf"

Expected: the combobox groups/items would be filtered to just the ones in the "arcgis-configuration-editor" group.

Observed: The items are not filtered.

### Reproduction Version

1.2.0

### Relevant Info

[This issue](https://github.com/Esri/calcite-components/issues/4348) seems similar but it is closed.

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
Verified in `1.8.1-next.0`
![verify-filter](https://github.com/Esri/calcite-design-system/assets/5023024/1d09b644-6433-4189-938d-ec0cb2a7b874)
