### ISSUE TITLE
[Chip] Add opt-in affordance for closing `closable` chip with keyboard.

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6825]
### Description

As suggested in Chip Group PR, consider having an additional and opt-in (or opt-out?) functionality to allow users to use a key (probably `delete`) to close a `closable` chip while focused on the chip. Currently a user must navigate to the close button to take this action via keyboard.

### Acceptance Criteria

Chip has a new property - `allow/disallow-close-via-key` (with a better name) to enable the described functionality.

### Which Component

Chip cc @jcfranco 

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified with `3.0.0-next.36` using the new `close-on-delete` attribute using the `del` and `backspace` keys:

```html
<calcite-chip value="dark-grey" label="Dark grey basemap" icon="basemap" closable close-on-delete></calcite-chip>
```

When `close-on-delete` is not present on the component, no action occurs when using the `del` and/or `backspace` keys. 🎉
