### ISSUE TITLE
Input type number does not work with French (F) AZERTY keyboard layout

### ISSUE THREAD

**Issue by ChristopheSuter** [Esri/calcite-design-system#6854]
### Actual Behavior

Problem when using calcite input type number with French (France) keyboard layout AZERTY on keyboards without numeric pad.

The user needs to hold the [SHIFT] key to enter numbers and this does not work (no input token) on calcite input but does work on native input type number

### Expected Behavior

Input should work as native input

### Reproduction Sample

https://codepen.io/geospatialem/pen/QWZpepg

### Reproduction Steps

Change your keyboard layout to French (France) and try to input number :
https://codepen.io/geospatialem/pen/QWZpepg

### Reproduction Version

1.2.0

### Relevant Info

MacOS/Chrome

### Priority impact

p1 - need for current milestone

### Impact

User can not use input

### Esri team

N/A

**Comment by geospatialem** [comment]
This was also reported as BUG-000157826.

**Comment by geospatialem** [comment]
possibly related #7039

**Comment by eriklharper** [comment]
@ChristopheSuter what platform and browser are you running that allows you to type the non-number pad numeric keys in the native html number input?  I'm on macOS Ventura 13.4 and this the behavior I see when I type 1234567890 on the non-number pad keys in the following browsers:

Safari:
![image](https://github.com/Esri/calcite-components/assets/821864/cce4c235-8493-4ef9-b7fd-580a39299167)

Firefox
![image](https://github.com/Esri/calcite-components/assets/821864/bc6fdac3-6154-482a-8a88-573d3a4cbe5d)

Chrome
![image](https://github.com/Esri/calcite-components/assets/821864/b7e28842-a5d5-4011-a364-4a5ba9f6f973)

**Comment by eriklharper** [comment]
This is the keyboard I've selected in the system settings input sources option 
![image](https://github.com/Esri/calcite-components/assets/821864/7452fea5-7350-4f32-965d-16a9da209742)

**Comment by ChristopheSuter** [comment]
Ventura 13.3.1 and Chrome
Make sure it is the only layout in your settings ..
<img width="733" alt="image" src="https://github.com/Esri/calcite-components/assets/78811924/14c0a00d-93a8-4e69-82d2-9cbb534c741c">

<img width="790" alt="image" src="https://github.com/Esri/calcite-components/assets/78811924/9cdaaf21-2513-4e6b-83d4-35814db10d0b">

**Comment by eriklharper** [comment]
Hmm... still can't replicate it, even after removing all input sources except ABC - AZERTY.  Does it require a system restart after applying those changes?

**Comment by anveshmekala** [comment]
i am able to reproduce the error with Ventura 13.3.1 and Chrome.

**Comment by geospatialem** [comment]
A fix has been added to our latest release, `1.4.3`.

@ChristopheSuter could you verify if the fix is mitigated with the AZERTY keyboard and `input` where `type="number"` in [this sample](https://codepen.io/geospatialem/pen/wvQJKEp)?

**Comment by geospatialem** [comment]
Verified on Mac OS in Chrome with [this sample](https://codepen.io/geospatialem/pen/wvQJKEp) in `1.4.3`.
