### ISSUE TITLE
Segmented Control Checked State Not Updating

### ISSUE THREAD

**Issue by nikki-lea** [Esri/calcite-design-system#6860]
### Actual Behavior

Controlling state from a parent component results in segmented control not toggling between options as expected. 

The following workaround doesn't work in this case:
`      <CalciteSegmentedControl
        onCalciteSegmentedControlChange={(e) => {
          setSearchType(e.target.value);
        }}
      >
        <CalciteSegmentedControlItem
          checked={searchType === "DATA" ? true : undefined}
          value="DATA"
        >
          Data
        </CalciteSegmentedControlItem>
        <CalciteSegmentedControlItem
          checked={searchType === "ALL" ? true : undefined}
          value="ALL"
        >
          All
        </CalciteSegmentedControlItem>
      </CalciteSegmentedControl>`

Prior discussion here: https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1682444266735?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1682444266735&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1682444266735&allowXTenantAccess=false

### Expected Behavior

User should be able to have "ALL" as default with focus, then click the left choice, "DATA" and have that one selected and with focus, then be able to select the right choice, "ALL", then have that one selected with focus. 

### Reproduction Sample

https://codesandbox.io/s/frosty-lovelace-wtoxlm?file=/src/App.js

### Reproduction Steps

1. Click "DATA" on the "not working" version
2. Click "ALL" on the "not working" version

### Reproduction Version

1.1.0

### Priority impact

p4 - not time sensitive

### Impact

No impact since workaround provided.

### Esri team

ArcGIS Enterprise

**Comment by josercarcamo** [comment]
Unfortunately, unless we do something very complex in JS, I don't think this has a solution. Per https://stackoverflow.com/questions/63071001/checkbox-is-checked-even-though-checked-false, the behavior is a product of HTML 5/JS. I've tried many ways to get it to work; however, the problem is that HTML 5 considers the "checked" attribute of an element to be true whenever it is present on the element and false whenever it is not, regardless of the value of "checked". Setting "checked" to "undefined" behaves unpredictively as demonstrated in https://codesandbox.io/p/sandbox/frosty-lovelace-wtoxlm?file=%2Fsrc%2FApp.js%3A19%2C11-19%2C40.

**Comment by jcfranco** [comment]
@josercarcamo Can you investigate a bit more into why the state isn't updating properly? We have a workaround for booleans in [React's doc's gotchas section](https://developers.arcgis.com/calcite-design-system/resources/frameworks/#gotchas), which doesn't seem to work in particular for `segmented-control`. There is a known issue where the presence of the attribute impacts styling (see [Stencil repro case](https://github.com/jcfranco/stencil-styling-issues-with-non-standard-boolean-attr-support)), but this seems unrelated to that.

**Comment by jcfranco** [comment]
@josercarcamo Whipped up [this codepen](https://codepen.io/jcfranco/pen/NWVzgar?editors=1001) that demonstrates the same, or very similar, selection issue in vanilla JS.

**Comment by josercarcamo** [comment]
After further investigation, I arrive at the following code and it works:

![image](https://github.com/Esri/calcite-design-system/assets/138070439/0915055b-0bf9-4a9e-a832-4050a7cbea1b)

I can click the button to select/unselect the "Win32" item:

![image](https://github.com/Esri/calcite-design-system/assets/138070439/ce152484-3a11-42a2-bef4-25cff4c5e77e)
![image](https://github.com/Esri/calcite-design-system/assets/138070439/4d794f71-f3c7-46a0-9138-c0b2d451701e)

**Comment by josercarcamo** [comment]
This code also works with "undefined":

![image](https://github.com/Esri/calcite-design-system/assets/138070439/9fc006ea-0416-498a-9afb-83822f5d576d)

**Comment by josercarcamo** [comment]
![image](https://github.com/Esri/calcite-design-system/assets/138070439/df669aba-d3b2-4d58-b3c2-14032d876fb7)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.1`
