### ISSUE TITLE
Enable control over checkbox change events in a Calcite Card component

### ISSUE THREAD

**Issue by ialixandroae** [Esri/calcite-design-system#6872]
### Description

As a developer, I would like to use the [CalciteCard](https://developers.arcgis.com/calcite-design-system/components/card/) React components with the checkboxes being visible, and to be able to capture and handle the event triggered by clicking the `checkbox`.

The `Card` component is being controlled by a passed down props type `boolean`, which will dictate whether the `Card` is selected or not (by using this props inside the `selected` prop).
The `checkboxes` are visible by setting the `selectable` property to `true`.

**Example of using the component**

```
<CalciteCard
          key={keyId}
          selected={true}
          selectable={true}
          thumbnailPosition="inline-start"
          onCalciteCardSelect={() => this.foo(args)}
>
```

As demonstrated in the code example above, the Card should always be rendered as selected (with the outline/contour having, for example, the blue color), and with its checkbox being checked

![Screenshot 2023-04-27 at 10 25 07](https://user-images.githubusercontent.com/18401030/234804230-e381d0d5-5e12-44b8-95b1-a718290969e6.png)

If the user will perform a click event on the checkbox (which in current state is checked), this action will unselect the Card component and will check the checked checkbox. 
This action overwrites the `selected={true} `property set on the `Card` component.

As a developer I would like to be able to use `event.preventDefault()` or `event.stopPropagation()` on the `onChange()` event function, triggered by clicking the checkbox, and to be able to control the state of the Card component and the state of the checkbox (if it will be checked or not, despite the click event).

**Story example:**
- after clicking the already checked checkbox of a `Card` element, after the click is performed, I would like a `Modal` element to appear. A user confirmation is needed inside the `Modal`, before deciding if the performed click will uncheck the checkbox and unselect the Card element.

**Usage in React:**
- the React best practices recommend the option to use checkbox elements either in controller or uncontrolled modes (environments). Moreover, a local widget state could be used to control whether a checkbox is checked or unchecked.
- In the case of Card elements we would need a similar pattern to be available, and because both the Card and the checkbox are present together in the big UI component, and they need to be in sync, to be able to control both
- their state can be rendered via the passed props

### Acceptance Criteria

The developer must have control over the state by being able to capture and handle the change or click events performed on the Card or on the checkbox. If the user story requires, the developer must be able to block the click event changing the state of the Card (selected or not) or the state of the checkbox (checked or unchecked), typically by stopping the propagation of the event (eg. using `event.preventDefault()`)

### Relevant Info

MDN Events: `preventDefault()` method
https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

### Which Component

CalciteCard: https://developers.arcgis.com/calcite-design-system/components/card/

### Example Use Case

```
<CalciteCard
          key={keyId}
          selected={true}
          selectable={true}
          thumbnailPosition="inline-start"
          onCalciteCardSelect={() => this.foo(args)}
>
```

### Priority impact

p1 - need for current milestone

### Esri team

ArcGIS GeoBIM

**Comment by macandcheese** [comment]
Everything above is totally valid but complicated by using an actual checkbox element inside our card.

If we just use an action or other element with appropriate roles styled to behave like a checkbox, users would only have to deal with the event coming from the card’s select event. That said, all the comments in the above issue still stand for other places with nested controls (Tile Select?) that developer users don’t have direct access to.

**Comment by macandcheese** [comment]
Related #7223

**Comment by macandcheese** [comment]
I think this would be covered by #7223 and the proposed change in event behavior to align with our other `selectionMode` components and remove the internal checkbox cc @geospatialem if we want to close this in favor of that.

**Comment by geospatialem** [comment]
> I think this would be covered by https://github.com/Esri/calcite-design-system/issues/7223 and the proposed change in event behavior to align with our other selectionMode components and remove the internal checkbox cc @geospatialem if we want to close this in favor of that.

Closing in favor of the proposed `card-group` component in https://github.com/Esri/calcite-design-system/issues/7223.

> @ialixandroae - the single-persist mode mentioned in this thread has been added 🎈

Codepen sample showing the `list`'s `selectionMode` of `"single-persist"`: https://codepen.io/geospatialem/pen/NWeBWJe
