### ISSUE TITLE
Action: text-only actions render off-centered

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-design-system#6879]
### Actual Behavior

There is an extra margin to the right of a calcite action which prevents it from being properly centered in cases where the action is displayed inline with an auto width.

### Expected Behavior

Shoudl be able to render an action which is just text where the text is centered in the bounding box of the action. 

### Reproduction Sample

https://codepen.io/paulcp/pen/zYmzEdQ

### Reproduction Steps

1. Notice the extra space to the right of the word "testing"

### Reproduction Version

v1.3.1

### Relevant Info

All OS, all browsers.

Caused by https://github.com/Esri/calcite-components/pull/6562 , broken in 1.1.0

### Regression?

v1.0.8

### Priority impact

p4 - not time sensitive

### Impact

We'd like to display a text-only action. We already have these in some interfaces so it will be broken until the upstream calcite issue is fixed. 

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
+1 - this is pretty noticeable in some interfaces. cc @SkyeSeitz @ashetland

**Comment by ashetland** [comment]
I think ideally the fix in pr #6562 would only apply to Actions inside an Action Bar. Another possible way to address this might be to have Action Bar account for the space needed by the indicator instead of the Actions themselves. Are vertical Action Bars the only place the indicator space matters? I'd expect horizontal Action Bars could be a little more fluid, like the behavior in Chip Group.

**Comment by ashetland** [comment]
[Figma file](https://www.figma.com/file/Q16YuSQQTJKCpeT4CN0XCA/Action%3A-text-only-actions-render-off-centered-%5B6879%5D?type=design&node-id=530-170&mode=dev) for this issue. Restores Action to previous behavior and requires Action Bar accommodate the needed space for the indicator.

**Comment by SkyeSeitz** [comment]
> [Figma file](https://www.figma.com/file/Q16YuSQQTJKCpeT4CN0XCA/Action%3A-text-only-actions-render-off-centered-%5B6879%5D?type=design&node-id=530-170&mode=dev) for this issue. Restores Action to previous behavior and requires Action Bar accommodate the needed space for the indicator.

Accounting for the indicator space at the Action Bar level makes a lot of sense 👍🏽

**Comment by driskull** [comment]
Can we just position the indicator absolutely like we do when there is an icon? This should be a simple fix.

I'm not sure how we're expecting the action bar to account for extra space. The width of the action bar is based off of the action content inside.

**Comment by macandcheese** [comment]
WDYT @SkyeSeitz @ashetland - I think positioning this absolutely on any provided icon makes sense. That would still solve the original issue that was fixed that caused this one (expanding action bar with indicator on longest string).

For cases that an icon is not provided and the Action is `text-enabled` - it could be displayed alongside the text as it was previous to the change that caused this new issue.

**Comment by ashetland** [comment]
> For cases that an icon is not provided and the Action is text-enabled - it could be displayed alongside the text as it was previous to the change that caused this new issue.

Would Action Bar need to expand to accommodate the indicator like it did before in this case?

**Comment by macandcheese** [comment]
Yeah, in the case that there are no icons present. But that's a small case and the bump in width is ... less impactful in a negative way... I'd say than the current behavior. The original issue of "action bar with icons becoming wider when indicator is present on longest string" won't occur when icons are used.

**Comment by DitwanP** [comment]
Verified locally with the `main` branch
<img width="168" alt="Screenshot 2023-11-20 at 1 52 02 PM" src="https://github.com/Esri/calcite-design-system/assets/60022782/95762c15-a89b-44c0-8aa8-7367888fa998">
