### ISSUE TITLE
[color-picker] add `clearable` property and deprecate `allowEmpty`

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#6880]
### Description

For consistency, the color-picker should use `clearable` for the value-clearing behavior.

### Acceptance Criteria

1. `clearable` property is added
2. `allowEmpty` is deprecated

### Which Component

`calcite-color-picker`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.11` with both the new `clearable` and deprecated `allow-empty` attributes. ✨👍🏻✨
