### ISSUE TITLE
Chevron icon should be 24px (medium) on large scale Input Date/Time Pickers

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#6889]
### Actual Behavior

The chevron icons are set to small scale.
<img width="358" alt="CleanShot 2023-04-28 at 15 23 07@2x" src="https://user-images.githubusercontent.com/108549080/235263883-68c104a5-5e3d-4a69-a9bc-50952de308bf.png">
<img width="266" alt="CleanShot 2023-04-28 at 15 23 36@2x" src="https://user-images.githubusercontent.com/108549080/235263887-b5dcf76f-9237-484a-9fc2-5af8c7f846ca.png">

### Expected Behavior

They should be set to medium scale to match the size of the other icons.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-picker/

### Reproduction Steps

1. Open component sample
2. Select Input Time Picker or Input Date Picker
3. Change scale to large

### Reproduction Version

1.3

### Priority impact

p2 - want for current milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.10.0-next.7` of 24px on the icon when `scale="l"`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/b28b009b-b3b3-41b0-b11d-f7ad6bdca186)
