### ISSUE TITLE
Add ability to restrict character input to calcite-input-time-picker

### ISSUE THREAD

**Issue by BennyBaruba** [Esri/calcite-design-system#6898]
### Description

As it stands now, users can input any characters into the calcite-input-time-picker.  

![image](https://user-images.githubusercontent.com/5122225/235706890-6fe26dc1-689b-415a-8a97-dcac9ba8639a.png)

This enhancement is a request to add the ability to restrict what characters can be typed in directly to the calcite-input-time-picker. For english the user should only be able to type in 2 numbers for each the hour, minutes and seconds and only am or pm in a 12 hour format.

### Acceptance Criteria

- calcite-input-time-picker only allows the correct characters to be manually typed in

### Relevant Info

A similar issue exists with the calcite-input-date-picker.

![image](https://user-images.githubusercontent.com/5122225/235709496-ace2e497-69b0-4652-8367-28d2be7c6fa5.png)

### Which Component

calcite-input-time-picker

### Example Use Case

![image](https://user-images.githubusercontent.com/5122225/235708966-203f217f-f390-4bc6-a8fb-660e7d715817.png)

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Mission

**Comment by geospatialem** [comment]
Should we consider using error handling for a solution and/or strip out invalid values? For instance, [Atlassian](https://atlassian.design/components/datetime-picker/date-picker/examples) will let the user type in a value and then reset once the component's blurred.

**Comment by DitwanP** [comment]
We want masked inputs for time-picker.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/2709, where masking will be considered as part of the effort,
