### ISSUE TITLE
Read-only Input Date/Time Pickers should not have dropdown affordance

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#6899]
### Actual Behavior

When `read-only` both `input-date-picker` and `input-time-picker` show a chevron to indicate there is a dropdown.
<img width="1021" alt="CleanShot 2023-05-02 at 11 12 56@2x" src="https://user-images.githubusercontent.com/108549080/235751308-0d2c6fac-e242-4d93-b98e-6391e12087e1.png">
<img width="1021" alt="CleanShot 2023-05-02 at 11 15 43@2x" src="https://user-images.githubusercontent.com/108549080/235751318-828592ab-ce70-4213-a977-68336e3cfd5c.png">

### Expected Behavior

`read-only` should be used to indicate a non-interactive data field and thus would have do dropdown picker to open.
![CleanShot 2023-05-02 at 11 12 56@2x](https://user-images.githubusercontent.com/108549080/235752133-43e993c7-2efa-4f43-8570-8d4bed8772cc.png)
![CleanShot 2023-05-02 at 11 15 43@2x](https://user-images.githubusercontent.com/108549080/235752118-55b63a32-cbeb-4ef8-bdcf-a2edcfe3397e.png)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-date-picker/

### Reproduction Steps

1. Open component sample for `input-date-picker` or `input-time-picker`
2. Select read-only

### Reproduction Version

1.3

### Relevant Info

cc: @jcfranco 

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on `main` for `input-date-picker` and `input-time-picker` with the `read-only` attribute.
