### ISSUE TITLE
[Block Section] Text hierarchy and spacing

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#6905]
### Description

BlockSection heading is very similar to Block's heading.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/12503298/235787709-be77745d-cec2-4f2c-b098-00c95c5d90df.png">

Suggest using normal font weight for BlockSection headings.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/12503298/235787899-d45dcedc-9b30-4b49-a657-1e4ca3b9a86e.png">

Also, it seems that the padding in the content area of Block doesn't match the inline padding used in most other areas. Right now, it's at 0.625rem whereas most other places 0.75rem is used. Suggest updating to 0.75rem for better alignment.

<img width="1093" alt="Screen Shot 2023-05-02 at 2 17 34 PM" src="https://user-images.githubusercontent.com/12503298/235788381-c84c6272-4122-4e90-b46d-34226cc07153.png">

@SkyeSeitz would appreciate your feedback.

### Acceptance Criteria

Better text hierarchy and padding alignment.

### Which Component

Block and BlockSection

### Example Use Case

Using Block and BlockSection together.

### Priority impact

p4 - not time sensitive

### Esri team

N/A

## Final design recommendations
See [comment](https://github.com/Esri/calcite-design-system/issues/6905#issuecomment-1804189189)

**Comment by SkyeSeitz** [comment]
I agree, I think better text hierarchy is something we could take a look at 👍🏽

Funnily enough, the Block content section padding in Figma lines up Block text and Block Section text at 0.75rem/12px already. So either Figma missed this change or we have just been slightly misaligned since the Figma component was built- thanks for pointing out, Alan! This fix would also nicely center align Block's expand chevron and Block Section's Switch. 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/29716057/235808335-752247c5-8ffc-476d-95a9-88cb9c01a904.png">

**Comment by asangma** [comment]
Thanks @SkyeSeitz.

@geospatialem This isn't urgent but the UtilityNetwork widget would be much happier if this change gets in soon. :)

**Comment by ashetland** [comment]
Design notes for this issue ([Figma file](https://www.figma.com/file/MpA4NiFBK0PY2PcSpRpnrz/Block-%26-Block-Section---text-hierarchy%2C-spacing%2C-padding-%5B6905%2C-7146%5D?type=design&node-id=513-18426&mode=dev) available as well):

### Block

- Update `--calcite-block-padding` default to 0.75rem

![image](https://github.com/Esri/calcite-design-system/assets/108549080/dcf0d061-e647-4f7e-92ab-9ab69bf36f95)

### Bock Section

- Update idle font weight to regular
- Maintain existing onHover behaviors

![image](https://github.com/Esri/calcite-design-system/assets/108549080/695ffb08-30a4-4582-ac2a-8fdac606fa7e)

**Comment by ashetland** [comment]
Could be coupled with #7146

**Comment by geospatialem** [comment]
Opened https://github.com/Esri/calcite-design-system/issues/9323 to address `block`, the above has been re-scoped, targeted for June's release to address `block-section`.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
