### ISSUE TITLE
[Modal] Generalize naming of Footer slots

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6918]
### Description

Follow up to Responsive design meeting...

Right now, Modal has prescriptively named slots that is at odds with nomenclature throughout the system. We should consider making these more general "-start / -end" footer slots.

### Acceptance Criteria

Footer slot naming is evaluated for consistency with other system slots.

### Relevant Info

cc @jcfranco @SkyeSeitz 

We will need to add best practices and document the recommended ordering for the buttons or slotted content.

### Which Component

Modal

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
Additional note: existing slots should be deprecated to allow developers time to migrate to the new ones before we remove them in a future breaking change release.

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/7886 - where the new `dialog` component can determine the need for the above, across all of the component's slots.
