### ISSUE TITLE
[Bug] Combobox Item inherits scale from parent Label

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#6962]
### Actual Behavior

As mentioned in Teams - Combobox Item is inheriting a scale from the parent Label. While we recommend using the same scale for label, and controls, this should not happen.

Of note, the Combobox input is not inheriting, only the Combobox Item.

### Expected Behavior

The Combobox should set the scale on Combobox Item, here is the problematic lookup: https://github.com/Esri/calcite-components/blob/fa0fe58e487ba4e7d79e2d19a4fc5acda51b0e08/src/components/combobox-item/combobox-item.tsx#LL100C6-L100C6

As a note, we shouldn't allow mix match of Combobox / Combobox Item scales - so Combobox should set and ensure any scale on child Combobox Item matches.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/XWxYZqW?editors=100

### Reproduction Steps

1. Open Codepen
2. Note that the Scale of the Combobox Items are "L"

### Reproduction Version

1.3.1

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
☂️ issue with pattern and effects/purpose with parent inheritance: https://github.com/Esri/calcite-design-system/issues/6038
