### ISSUE TITLE
fix(tree): parent item behavior of single, children, and multichildren selection modes

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#6971]
### Actual Behavior

There are a few additional bug fixes needed on the recent adjustments to Tree's selection of parent category w/out selecting children #6926

1. Hit target to expand parent Tree Item does not include icon + text area
2. Parent Tree Items with decedents are selectable in single, children, and childrenmulti selection modes

### Expected Behavior

1. Hit target to expand parent Tree Item includes icon + text area
2. Parent Tree Items with decedents are not selectable in single, children, and multichildren selection modes

![NONE](https://github.com/Esri/calcite-components/assets/29716057/14a2b103-b2db-41ff-adf9-bf21099e2d5b)
![SINGLE](https://github.com/Esri/calcite-components/assets/29716057/3fc37a7c-5c3f-471d-9604-49b0bb93585c)
![MULTI](https://github.com/Esri/calcite-components/assets/29716057/5df98073-42d0-44e4-9eab-8398c2a30da9)
![CHILDREN](https://github.com/Esri/calcite-components/assets/29716057/6a5fe6b9-64f8-4ec9-a243-8b180efd6468)
![MULTICHILDREN](https://github.com/Esri/calcite-components/assets/29716057/02a30aac-d157-4e99-93c4-fa0e77f14378)

[link to mock ups](https://www.figma.com/file/R0B6ljDBIyKPtEa5GXjSjx/Tree-%5BSelection-%26-Hover-States%5D-%5B6912%2C-6930%5D?type=design&node-id=102%3A20921&t=c2TOspUGNmQyiHhR-1)

### Reproduction Sample

https://esri.github.io/calcite-components/?path=/story/components-tree--simple&knob-checked=true&knob-disabled=true&knob-filterEnabled=true&knob-intl-deselect=Deselect&knob-intl-loading=Loading&knob-intl-select=Select&knob-label=Checkbox&knob-loading=true&knob-scale=m&knob-selectable=true&knob-selected=true&knob-thumbnail-position=block-start

### Reproduction Steps

Open Tree samples in Story book and click on parents of the mentioned selection modes.

### Reproduction Version

v1.3.1

### Relevant Info

Related Issues: https://github.com/Esri/calcite-components/issues/6912, https://github.com/Esri/calcite-components/issues/6444, https://github.com/Esri/calcite-components/issues/6509

### Priority impact

p2 - want for current milestone

### Impact

Resolving this bug fix will allow us to move forward on related enhancements & bug fixes to List #6544

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
cc @geospatialem @ashetland

**Comment by geospatialem** [comment]
Research will be conducted to determine time estimate for future milestone assignment.

**Comment by ashetland** [comment]
Behaviors should also match designs in issue #6544 for List

**Comment by geospatialem** [comment]
Verified behavior mentioned in https://github.com/Esri/calcite-design-system/issues/6971#issue-1712956963 for all `selectionMode` types in `1.9.0-next.16`.
