### ISSUE TITLE
[Color Picker] Hue thumb handle partially hidden under swatch

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7005]
### Actual Behavior

The thumb handle on the `color-picker` is partially hidden under the swatch.

![image](https://github.com/Esri/calcite-components/assets/5023024/b17d6c45-1b1b-4a29-a4d3-12e7ac517de6)

### Expected Behavior

The thumb should fall within the slider bounds, but still map to the edges.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/color-picker/#sample

### Reproduction Steps

1. Open the [sample](https://developers.arcgis.com/calcite-design-system/components/color-picker/#sample)
2. Observe when the color is to the far left the handle is partially covered by the swatch

### Reproduction Version

1.4.0

### Regression?

1.3.1

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Map Viewer

**Comment by ashetland** [comment]
Discovered some related issues that are present at each scale, but most pronounced on `scale="s"`. See the attached screen recording.

- Using a mouse, the farthest right extent of the sliders cannot be reached
- The opacity slider doesn't respond to arrow keys
- Hue slider nitpick: I think a more expected UX is for the hue slider to range from 0 to 360, not 0 to 359.

https://github.com/Esri/calcite-components/assets/108549080/5f010f73-6042-4bf7-80cd-06deb070a2c0

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.36` 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/8b77fcbe-f1cf-4044-9b48-d72d0656eb46)
