### ISSUE TITLE
[Combobox] Single Select Combobox text can overlap close button

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7020]
### Actual Behavior

The close button can overlap a populated combobox in single-select: 
<img width="288" alt="Screen Shot 2023-05-24 at 12 57 20 PM" src="https://github.com/Esri/calcite-components/assets/4733155/ab890935-8275-4a57-8dd6-531e72adbe5c">

### Expected Behavior

I would not expect the close button to overlap text.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/rNqRNGd?editors=1000

### Reproduction Steps

1. Open Codepen
2. See overlap when Codepen iFrame narrow enough to cause it

### Reproduction Version

1.4.0

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
This happens without the clear button too

Single, clear-disabled:
<img width="146" alt="CleanShot 2023-05-24 at 14 55 27@2x" src="https://github.com/Esri/calcite-components/assets/108549080/24cd4733-1c27-48fb-bec0-4a77e23e2b96">

Multiple, clear-disable:
<img width="240" alt="CleanShot 2023-05-24 at 14 57 13@2x" src="https://github.com/Esri/calcite-components/assets/108549080/19f8fc46-71db-44b7-b4eb-1c9e1a535222">

Multiple:
<img width="254" alt="CleanShot 2023-05-24 at 14 56 34@2x" src="https://github.com/Esri/calcite-components/assets/108549080/82f34720-4901-480b-b070-6d1be2f8bb5b">

**Comment by Elijbet** [comment]
> This happens without the clear button too
> 
> Single, clear-disabled: <img alt="CleanShot 2023-05-24 at 14 55 27@2x" width="146" src="https://private-user-images.githubusercontent.com/108549080/240750095-24cd4733-1c27-48fb-bec0-4a77e23e2b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODkyMDcsIm5iZiI6MTcwNzI4ODkwNywicGF0aCI6Ii8xMDg1NDkwODAvMjQwNzUwMDk1LTI0Y2Q0NzMzLTFjMjctNDhmYi1iZWMwLTRhNzdlMjNlMmI5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNjU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWI4YTBjNDk4N2E0NmYwOTFkY2RmZmFjMWU2NWIyODE1OTdlYjdkZWNkMmM2YTA0MGM1ZTRmOGQ5ZDc4YWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wwiNu29mZk7FRD_57jgupsiJvL_R9mrskt15d3AR824">
> 
> Multiple, clear-disabled: <img alt="CleanShot 2023-05-24 at 14 57 13@2x" width="240" src="https://private-user-images.githubusercontent.com/108549080/240750469-19f8fc46-71db-44b7-b4eb-1c9e1a535222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODkyMDcsIm5iZiI6MTcwNzI4ODkwNywicGF0aCI6Ii8xMDg1NDkwODAvMjQwNzUwNDY5LTE5ZjhmYzQ2LTcxZGItNDRiNy1iNGViLTFjOWUxYTUzNTIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNjU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWIwZWJkNWQ1ODIxMTU5NTBkYTE4NWUzOTU2M2NiNjNjYWU4MTMyM2RhMGFjZWNhNzEzNWZkOGI4Y2NhNDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VZyc39aOBoxGpHnw6M_Xso3bHetNWifawjE9IA043OU">
> 
> Multiple: <img alt="CleanShot 2023-05-24 at 14 56 34@2x" width="254" src="https://private-user-images.githubusercontent.com/108549080/240750511-82f34720-4901-480b-b070-6d1be2f8bb5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODkyMDcsIm5iZiI6MTcwNzI4ODkwNywicGF0aCI6Ii8xMDg1NDkwODAvMjQwNzUwNTExLTgyZjM0NzIwLTQ5MDEtNDgwYi1iMDcwLTZkMWJlMmY4YmI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNjU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2M5YzM4MGM2ZjdjNDQ1YmMyYzFiNzgxNWFhOTQxNjRlYTU4MjY3M2M4YWE2NjEwMDVjOTc3YzA4YmY4OGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8FLLJZxUg2e3H5UzfMNQxbp-Jy3GeajJ_3lS8wJPWRw">

Can I get a design input of what the expected behavior should be? Are we looking for truncation? @ashetland @macandcheese @SkyeSeitz

**Comment by DitwanP** [comment]
🍠 `Verified` on 2.7.0-next.2
![image](https://github.com/Esri/calcite-design-system/assets/60022782/93fb1508-cb70-42bd-8f4f-8f14f0b0b863)
