### ISSUE TITLE
List: Expose Events for dragging between Lists

### ISSUE THREAD

**Issue by Csmith246** [Esri/calcite-design-system#7046]
### Actual Behavior

For the Calcite List component, when you set `dragEnabled` to `true`, and the `group` value of more than two lists to the same key, and then move items between the lists, none of the current Event's on the List get triggered. This makes it difficult to react to drags between lists.

### Expected Behavior

When a List Item gets dragged from one List to a different List, maybe trigger events such as `calciteListDragOut` and `calciteListDragIn` on the respective lists. This would broadcast what specifically has occurred within the lists, and allow the wider application to perform any behaviors that are tied to a move between lists. 

### Reproduction Sample

~https://codepen.io/csmith55/pen/YzJMzYg?editors=1001~
https://codepen.io/geospatialem/pen/OJaGeVN

### Reproduction Steps

Notice in the sample that:

- Each list has the same `group` value
- All events are being tracked on List 1

If you drag any list items from list 2 or 3 into list 1, no events are fired. If you drag any out of List 1, still no events are fired.

### Reproduction Version

~https://www.npmjs.com/package/@esri/calcite-components/v/1.4.1-next.4~
1.5.1

### Priority impact

p2 - want for current milestone

### Impact

Technically, I don't believe this behavior has ever worked, but we got around that in our application by finding a reference to the internal SortableJS object and adding `onAdd` and `onRemove` methods. This fix on the Calcite side (https://github.com/Esri/calcite-components/commit/b4bbdf3d709b8b1adb04fe090957451f731f48bb) caused our work around not to work anymore, so an official solution is now desirable. Thanks!

### Esri team

ArcGIS Instant Apps

**Comment by Csmith246** [comment]
@driskull Would you have any update on this?

**Comment by geospatialem** [comment]
With the `list` sorting support in `1.5.1`, it looks like the events are exposed with the exception if a new `list-item` is added to the `list`. The request should include adding a listener if a new `list-item` is added, perhaps with the `calciteListOrderChange` event?

Updated Codepen to `list`/`list-item` in `1.5.1`: https://codepen.io/geospatialem/pen/OJaGeVN

Recording showing events are registered, unless a `list-item` is added to the first `list`:
![list-event-listeners](https://github.com/Esri/calcite-design-system/assets/5023024/f12335b3-49d6-48c1-bdfb-e0a93d07b376)

**Comment by Csmith246** [comment]
@geospatialem we've got a requirement for supporting accessible keyboard dragging between lists, as well. Could we add that to this issue? Or would it be better to make a new enhancement request for that?

**Comment by geospatialem** [comment]
> @geospatialem we've got a requirement for supporting accessible keyboard dragging between lists, as well. Could we add that to this issue? Or would it be better to make a new enhancement request for that?

Great question, @Csmith246! For tracking could you create a [new enhancement request](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=enhancement%2C0+-+new%2Cneeds+triage&projects=&template=enhancement.yml)? It seems like a good enhancement to separate out from the events.

**Comment by driskull** [comment]
@jcfranco should we have one event for adding and removing of items or do we want separate events? 

- `onDragAdd`
- `onDragRemove`

vs

- `onDragMove`

**Comment by driskull** [comment]
We're using the `onSort` event from SortableJS and that should happen anytime there's an add or remove.

```js
// Called by any change to the list (add / update / remove)
	onSort: function (/**Event*/evt) {
		// same properties as onEnd
	},
```

We'll need to investigate why its not emitting correctly. My guess is that its something we're doing to fix VDOM errors.

Bumped this issue to estimate-5. cc @geospatialem

**Comment by driskull** [comment]
I think we can mark this one as a bug as well.

**Comment by geospatialem** [comment]
Verified in `1.7.0`

**Comment by Csmith246** [comment]
Big thank you from Instant Apps! 🙏
