### ISSUE TITLE
calcite-color-picker: apply entered hex value immediately

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#7057]
### Description

Spin off from https://github.com/Esri/calcite-components/issues/4072

If you enter a new hex value either via copy/paste or by typing a new value you need to click completely outside of the color-picker or on another focusable element inside the color-picker to see that new color value being applied. 
Instead it should apply the new value as soon as a valid new value got entered.
If this is not possible then commit the value on blur.

I find the current workflow confusing.

https://codepen.io/afreitag/pen/bGmZGPR

### Acceptance Criteria

new color value gets applied as soon as a valid hex value got entered

### Which Component

calcite-color-picker

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Map Viewer

**Comment by ashetland** [comment]
[Figma file](https://www.figma.com/file/h0vqgnnTvcDhrsJLyiQyOm/Color-Picker%3A-apply-entered-hex-value-immediately-%5B7057%5D?type=design&node-id=566-7567&mode=dev) ready for dev.

**Comment by ashetland** [comment]
Removed `figma changes` label as no updates will be needed for the Figma library.
