### ISSUE TITLE
[Tab-Title]: truncate text past certain length

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#7068]
### Description

Truncate the `tab-title` text when it reaches 8px away from the x-button at all scales. This is a better behavior than the current wrapping. 

Stems from: #7026

This would need to have the tooltip applied for sighted users, just like the truncated button does (or any component with a set height).

More specifically, an `HTML label` should be used to reveal the full text for sighted users, and the `calcite-tooltip` is to provide additional context where needed. 

Figma layout from @SkyeSeitz 
![image](https://github.com/Esri/calcite-components/assets/19231036/b717753f-eca9-46c3-bfbd-0c2ec5912ccb)

### Acceptance Criteria

Long text is truncated and an html tooltip is provided for sighted users. 

### Which Component

tab-title

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Closing in favor of the responsive design and design changes proposed and targeted for this milestone via https://github.com/Esri/calcite-design-system/issues/6689.

**Comment by DitwanP** [comment]
Anne Fitz from Maps SDK still marked this as a top priority request for them so I reached out and got the following information when asking if the response design changes would remove their need of truncation on tabs.

"The tabs are often titled with the name of featuresets, which typically comes from the layer name in the map. Layer names can get quite long, and thus one layer can take up most of the screen real estate. It would be nice to be able to set a max-width, or similar api surface, to allow for tab titles to get truncated after a certain length. This way we would minimize the impact of large layer names on our workflows."

Example:

<img width="1162" height="1042" alt="Image" src="https://github.com/user-attachments/assets/50c26e33-4707-416c-aac1-e27ace057b44" />

**Comment by DitwanP** [comment]
One #14005 lands, you should be able to achieve truncation without needing to reopen this issue.
