### ISSUE TITLE
Update API reference descriptions for consistency across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7071]
### Description

Comb through all components and update all API ref descriptions to fit our style guide from https://github.com/Esri/calcite-components/issues/4442, which include:

- Use complete sentences with proper grammar, capitalization, and punctuation.  
- No abbreviations, e.g. use "property" instead of "prop".  
- Verbs must be in present tense (e.g., `"emits"` instead of `"emitted"`).  
- When referring to the component that the property/slot/method/css variable belongs to, call it "the component".  
- Use the full tag name when referencing other Calcite Components (prefix with `calcite-`), e.g. `calcite-button` instead of `button`.  
- For plural context, use `calcite-button`s instead of `calcite-button` elements.  
- Use backticks (``` ` ```) for the names of slots, events, properties, CSS variables, and component names.  
    - In line with the JSAPI docs [example](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-View.html#ready)  
    - Docs will incorporate styling with [afd-calcite-documentation issue #490](https://github.com/ArcGIS/afd-calcite-documentation/issues/490)  
- Use double quotes (`"`) for the values of properties/attributes and event details.  
- Only use single quotes (`'`) as apostrophes.  
- No links or URLs allowed in descriptions. If a link is necessary, a [custom JSDoc tag](https://stenciljs.com/docs/docs-json#custom-jsdocs-tags) should be added and parsed in the SDK site.  
- Refrain from using "e.g." or "i.e." references. Leverage "such as" (or similar) where examples are referenced.  
- Use "Accessible" instead of "Aria" language  
- Verify slots don't use the text "optional" in their descriptions  
- Remove optional JSDoc tags for props (`?`)

### Original Issue Description
Our property/slot/method descriptions are all over the place right now. We need to decide on some conventions, and then audit and proofread to make sure they are consistent. Some things to consider:

- Should they be sentences with proper case/punctuation/grammar, or should they be more like bullet points?
- Which verb tense should we use?
- Which quotation marks should be used (single vs double vs tick) in the descriptions? Should different quotation marks be used for different purposes (`calcite-xyz` vs "value")? e.g. [`disableCloseOnSelect`](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-disableCloseOnSelect) uses double and [`overlayPositioning`](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-overlayPositioning) uses single
- How should components be named when mentioned in the description? Should they be the full tag name? Should they be in quotes? - [here](https://developers.arcgis.com/calcite-design-system/components/button/#component-api-properties-splitChild) [here](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-properties-ancestors) [here](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-properties-icon) [here](https://developers.arcgis.com/calcite-design-system/components/flow/#component-api-methods-back)
- Should links be allowed in the description? If so, how should they be formatted? e.g. [`indeterminate`](https://developers.arcgis.com/calcite-design-system/components/checkbox/#component-api-properties-indeterminate), [`download`](https://developers.arcgis.com/calcite-design-system/components/link/#component-api-properties-download), [`value`](https://developers.arcgis.com/calcite-design-system/components/color-picker/#component-api-properties-value)

In addition to the consistency conventions, there is a lot of clean up that needs to happen. For example, 
- The description does not need to mention the default, since it is specified in the table - [here](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-width) 
  - This also applies to documentation that is linked out, and contains many properties. 
- The description does not need to specify that it is read-only, since it displays a chip based on a jsdoc tag [here](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-selectedItems)
- Product names should be capitalized, e.g. "Calcite UI Icons" vs [this](https://developers.arcgis.com/calcite-design-system/components/button/#component-api-properties-iconStart)

This is not an exhaustive list, but it is a start. If anyone else has something to add please feel free. @geospatialem and I will decide on and document the conventions, and then start updating the jsdoc.

### Which Component

All components

<details>
<summary>Progress checklist</summary>

- [x] `accordion` - Ditwan and Kitty
- [x] `accordion-item` - Ditwan and Kitty
- [x] `action` - Ditwan and Kitty
- [x] `action-bar` - Ditwan and Kitty
- [x] `action-group` - Ditwan and Kitty
- [x] `action-menu` - Ditwan and Kitty
- [x] `action-pad` - Kitty
- [x] `alert` - Kitty
- [x] `avatar` - Kitty
- [x] `block` - Ditwan
- [x] `block-section` - Ditwan
- [x] `button` - Ditwan
- [x] `card` - Ditwan
- [x] `checkbox` - Ditwan
- [x] `chip` - Ditwan
- [x] `chip-group` - Ditwan
- [x] `color-picker` - Ditwan
- [x] `combobox` - Ditwan
- [x] `combobox-item` - Ditwan
- [x] `combobox-item-group` - Ditwan
- [x] `date-picker` - Ditwan
- [x] `date-picker-day` - Ditwan
- [x] `date-picker-month` - Ditwan
- [x] `date-picker-month-header` - Ditwan
- [x] `dropdown` - Ditwan
- [x] `dropdown-group` - Ditwan
- [x] `dropdown-item` - Ditwan
- [x] `fab` - Ditwan
- [x] `filter` - Ditwan
- [x] `flow` - Ditwan
- [x] `flow-item` - Ditwan
- [x] `graph` - Ditwan
- [x] `handle` - Ditwan
- [x] `icon` - Ditwan
- [x] `inline-editable` - Ditwan
- [x] `input` - Ditwan
- [x] `input-date-picker` - Ditwan
- [x] `input-message` - Ditwan
- [x] `input-text` - Ditwan
- [x] `input-time-picker` - Ditwan
- [x] `input-time-zone` - Ditwan
- [x] `label` - Ditwan
- [x] `link` - Ditwan
- [x] `list` - Ditwan
- [x] `list-item` - Ditwan
- [x] `list-item-group` - Ditwan
- [x] `loader` - Ditwan
- [x] `menu` - Kitty
- [x] `menu-item` - Kitty
- [x] `meter` - Kitty
- [x] `modal` - Kitty
- [x] `navigation` - Kitty
- [x] `navigation-logo` - Kitty
- [x] `navigation-user` - Kitty
- [x] `notice` - Kitty
- [x] `option` - Kitty
- [x] `option-group` - Kitty
- [x] `pagination` - Kitty
- [x] `panel` - Kitty
- [x] `pick-list` - Kitty
- [x] `pick-list-group` - Kitty
- [x] `pick-list-item`  - Kitty
- [x] `popover`  - Kitty
- [x] `progress` - Kitty
- [x] `radio-group` - Kitty
- [x] `radio-group-item` - Kitty
- [x] `rating`  - Kitty
- [x] `scrim`  - Kitty
- [x] `segmented-control` - Kitty
- [x] `segmented-control-item` - Kitty
- [x] `select`  - Kitty
- [x] `sheet` - Kitty
- [x] `shell`  - Kitty
- [x] `shell-center-row`  - Kitty
- [x] `shell-panel` - Kitty
- [x] `slider` - Kitty
- [x] `split-button` - Kitty
- [x] `stepper` - Kitty
- [x] `stepper-item` - Kitty
- [x] `switch` - Kitty
- [x] `tab` - Kitty
- [x] `tab-nav` - Kitty
- [x] `tab-title` - Kitty
- [x] `tabs` - Kitty
- [x] `table` - Kitty
- [x] `table-header` - Kitty
- [x] `table-row` - Kitty
- [x] `table-cell` - Kitty
- [x] `text-area` - Kitty
- [x] `tile` - Kitty
- [x] `tile-select` - Kitty
- [x] `tile-select-group` - Kitty
- [x] `time-picker` - Kitty
- [x] `tip` - Kitty
- [x] `tip-group` - Kitty
- [x] `tip-manager` - Kitty
- [x] `tooltip` - Kitty
- [x] `tree` - Kitty
- [x] `tree-item` - Kitty
- [x] `value-list` - Kitty
- [x] `value-list-item` - Kitty

</details>

### Verified checklist

- [x] `accordion` - Kitty
- [x] `accordion-item` - Kitty
- [x] `action` - Kitty
- [x] `action-bar` - Kitty
- [x] `action-group` - Kitty
- [x] `action-menu` - Kitty
- [x] `action-pad` - Kitty
- [x] `alert` - Kitty
- [x] `avatar` - Kitty
- [x] `block` - Kitty
- [x] `block-section` - Kitty
- [x] `button` - Kitty
- [x] `card` - Kitty
- [x] `checkbox` - Kitty
- [x] `chip` - Kitty
- [x] `chip-group` - Kitty
- [x] `color-picker` - Kitty
- [x] `combobox` - Kitty
- [x] `combobox-item` - Kitty
- [x] `combobox-item-group` - Kitty
- [x] `date-picker` - Kitty
- [x] `dropdown` - Kitty
- [x] `dropdown-group` - Kitty
- [x] `dropdown-item` - Kitty
- [x] `fab` - Kitty
- [x] `filter` - Kitty
- [x] `flow` - Kitty
- [x] `flow-item` - Kitty
- [x] `icon` - Kitty
- [x] `inline-editable` - Kitty
- [x] `input` - Kitty
- [x] `input-date-picker` - Kitty
- [x] `input-message` - Kitty
- [x] `input-text` - Kitty
- [x] `input-number` - Kitty
- [x] `input-time-picker` - Kitty
- [x] `input-time-zone` - Kitty
- [x] `label` - Kitty
- [x] `link` - Kitty
- [x] `list` - Kitty
- [x] `list-item` - Kitty
- [x] `list-item-group` - Kitty
- [x] `loader` - Kitty
- [x] `menu` - Ditwan
- [x] `menu-item` - Ditwan
- [x] `meter` - Ditwan
- [x] `modal` - Ditwan
- [x] `navigation` - Ditwan
- [x] `navigation-logo` - Ditwan
- [x] `navigation-user` - Ditwan
- [x] `notice` - Ditwan
- [x] `option` - Ditwan
- [x] `option-group` - Ditwan
- [x] `pagination` - Ditwan
- [x] `panel` - Ditwan
- [x] `pick-list` - Ditwan
- [x] `pick-list-group` - Ditwan
- [x] `pick-list-item`  - Ditwan
- [x] `popover`  - Ditwan
- [x] `progress` - Ditwan
- [x] `radio-group` - Ditwan
- [x] `radio-group-item` - Ditwan
- [x] `rating`  - Ditwan
- [x] `scrim`  - Ditwan
- [x] `segmented-control` - Ditwan
- [x] `segmented-control-item` - Ditwan
- [x] `select`  - Ditwan
- [x] `sheet` - Ditwan
- [x] `shell`  - Ditwan
- [x] `shell-center-row`  - Ditwan
- [x] `shell-panel` - Ditwan
- [x] `slider` - Ditwan
- [x] `split-button` - Ditwan
- [x] `stepper` - Ditwan
- [x] `stepper-item` - Ditwan
- [x] `switch` - Ditwan
- [x] `tab` - Ditwan
- [x] `tab-nav` - Ditwan
- [x] `tab-title` - Ditwan
- [x] `tabs` - Ditwan
- [x] `table` - Ditwan
- [x] `table-header` - Ditwan
- [x] `table-row` - Ditwan
- [x] `table-cell` - Ditwan
- [x] `text-area` - Ditwan
- [x] `tile` - Ditwan
- [x] `tile-select` - Ditwan
- [x] `tile-select-group` - Ditwan
- [x] `time-picker` - Ditwan
- [x] `tip` - Ditwan
- [x] `tip-group` - Ditwan
- [x] `tip-manager` - Ditwan
- [x] `tooltip` - Ditwan
- [x] `tree` - Ditwan
- [x] `tree-item` - Ditwan
- [x] `value-list` - Ditwan
- [x] `value-list-item` - Ditwan

**Comment by geospatialem** [comment]
@DitwanP Found a few small additions we could make while verifying some components:

- [ ] It looks like we could add in backticks to `input-time-zone`'s `referenceDate` prop, WRT the `Date`, and backticks and double quotes to `"YYYY-MM-DD"` and `"YYYY-MM-DDTHH:MM:SS.SSSZ"`.

https://github.com/Esri/calcite-design-system/blob/72a1ce4dd8d94ed092c4c24c37e7209eff67e544/packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx#L156

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a3ff4814-6527-4e5e-a6bc-36dabf8fc127)

- [ ] It looks like `input-time-zone`'s events don't have doc yet, maybe we could add some context in for folks?

https://github.com/Esri/calcite-design-system/blob/72a1ce4dd8d94ed092c4c24c37e7209eff67e544/packages/calcite-components/src/components/input-time-zone/input-time-zone.tsx#L214-L222

![image](https://github.com/Esri/calcite-design-system/assets/5023024/88d64fa7-8de4-42e3-a154-23d291052edd)

Were we also aiming to include other props with multiple selections as part of this effort? It looks like there may be a few remaining items, including: 

- [ ] `combobox`'s `selectionDisplay`:
https://github.com/Esri/calcite-design-system/blob/72a1ce4dd8d94ed092c4c24c37e7209eff67e544/packages/calcite-components/src/components/combobox/combobox.tsx#L125-L127

- [ ] `shell-panel`'s `displayMode`:
 https://github.com/Esri/calcite-design-system/blob/72a1ce4dd8d94ed092c4c24c37e7209eff67e544/packages/calcite-components/src/components/shell-panel/shell-panel.tsx#L77-L80

**Comment by DitwanP** [comment]
> Were we also aiming to include other props with multiple selections as part of this effort? It looks like there may be a few remaining items, including:

😱 I thought we got all the selectionMode props. Anything else that needed to be listed out in a similar fashion I was going to make a separate PR for those. At least that was the plan. 

I'll get the PR in to address the things you mentioned here.

**Comment by DitwanP** [comment]
> > 😱 I thought we got all the selectionMode props. Anything else that needed to be listed out in a similar fashion I was going to make a separate PR for those. At least that was the plan.
> 
> Ah, gotcha. Do we want a separate issue to address those props, or we should work towards addressing them in this issue? I'm good with either approach.

I don't have a preference either, I'm fine with leaving this one open and getting a PR added in for those changes, that seems like the simplest route.

**Comment by DitwanP** [comment]
The only thing of note that I came across when validating was this. 

- Do we want to remove these parenthesis from [navigation-user](https://github.com/Esri/calcite-design-system/blob/dc5cfb3b1073c18d9036b97647beb308aeddc128/packages/calcite-components/src/components/navigation-user/navigation-user.tsx#L36C1-L37C29) and reword the sentence?
![image](https://github.com/Esri/calcite-design-system/assets/60022782/09bef262-e929-4ab2-8ca6-f73459f0df66)

**Comment by geospatialem** [comment]
> * Do we want to remove these parenthesis from [navigation-user](https://github.com/Esri/calcite-design-system/blob/dc5cfb3b1073c18d9036b97647beb308aeddc128/packages/calcite-components/src/components/navigation-user/navigation-user.tsx#L36C1-L37C29) and reword the sentence?

It's also part of `avatar`'s `thumbnail` prop. 

I think the parenthesis help differentiate the focus since its dependent on what the developer is implementing, but if we have a revision in mind - we could change it as well. WDYT?

https://github.com/Esri/calcite-design-system/blob/dc5cfb3b1073c18d9036b97647beb308aeddc128/packages/calcite-components/src/components/avatar/avatar.tsx#L22-L23

**Comment by cris6097** [comment]
[celebrate]     Cris Ortega reacted to your message:
________________________________

**Comment by cris6097** [comment]
[0]     Cris Ortega reacted to your message:
________________________________

**Comment by DitwanP** [comment]
> I think the parenthesis help differentiate the focus since its dependent on what the developer is implementing, but if we have a revision in mind - we could change it as well. WDYT?

That makes sense, I think its fine to stay.

**Comment by DitwanP** [comment]
🍡 @geospatialem verified the top half of components, and I verified the bottom half.
