### ISSUE TITLE
refactor: add the `@example` tag to all code snippets within JSDoc

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#7072]
### Description

Refactor to add the `@example` tag to all code snippets within JSDoc for the linter to apply the proper formatting. With the current ESLint plugin settings all the indenting gets removed, and commented code blocks become unreadable. 

See: https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.README/rules/check-indentation.md

e.g. https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts#L215

### Proposed Advantages

Readability

### Which Component

all

### Relevant Info

Stems from #7007

**Comment by geospatialem** [comment]
The above was [aimed at commonTests](https://github.com/Esri/calcite-design-system/pull/7007#discussion_r1204617651) only and they have been resolved with examples and proper formatting - nice work @Elijbet! Closing the above.
