### ISSUE TITLE
[Navigation Logo] Add `heading-level` Property

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7075]
### Description

The `heading` text in Navigation Logo should be able to optionally render as a heading level, via a `headingLevel` property. This should not affect the visual display of the component, only the internally rendered component.

### Acceptance Criteria

This should match other instances of this `headingLevel` property, such as in Panel: https://developers.arcgis.com/calcite-design-system/components/panel/#api-reference-properties-headingLevel

### Which Component

Navigation Logo

### Example Use Case

A user may want the rendered heading to render as a semantic heading level.

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified on `main`
