### ISSUE TITLE
[Navigation Logo] Use larger font size for Heading when Summary not present

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7080]
### Description

Currently, the Navigation Logo is rendering the same size font for heading when description is present or not. We should conditionally increase the font size of the heading when it is on its own, as this is the primary identification 

### Acceptance Criteria

One step larger font size is used when description is not present.

### Relevant Info

cc @ashetland @SkyeSeitz @juliepowell

### Which Component

Navigation Logo

### Priority impact

p2 - want for current milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.17`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/316de78d-89ec-43c7-a412-c832582177c3)
