### ISSUE TITLE
[Shell] Add `navigation` slot, deprecate `header` slot

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7087]
### Description

Now that the Navigation component has been added, we should add a "navigation" slot to Shell and recommend that over a deprecated "header" slot.

### Acceptance Criteria

Shell gains "navigation" slot, "header" slot is deprecated but remains usable.

### Which Component

Shell

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by driskull** [comment]
What about apps that are using the header for things that are not navigation? Maybe both slots should be kept?

**Comment by macandcheese** [comment]
The Navigation component can contain just the app title in a Logo component or other controls, doesn’t have to be Menu. 

Other cases could still use the “navigation” slot if they didn’t want to place the content in a Navigation component directly. But at least then it would reflect the recommended component - currently it’s not as clear that should be where Navigation is always slotted.

**Comment by geospatialem** [comment]
Closing to keep the slot name as-is with `"header"` as many other components and/or solutions could be slotted in, besides `navigation`.
