### ISSUE TITLE
`dropdown`, `dropdown-item`, `dropdown-group` update icon spacing

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7095]
### Description

Update icon spacing to make more consistent with the rest of Calcite. This was outlined as part of the work to audit and update nested indentations to improve visual hierarchy across components (Epic #6632).

### Acceptance Criteria

![image](https://github.com/Esri/calcite-components/assets/108549080/25cab87e-cf3c-4ac5-ba7e-bbe1e294f442)

### Relevant Info

[Figma file also available](https://www.figma.com/file/ua4NiNaOLrs5nGo5bECBfZ/Dropdown-Icon-Spacing-%5Bissue-7090%5D?type=design&node-id=287-113361) for additional details and a comparison to the current build.

### Which Component

Dropdown Item

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified spacing across scales in `2.9.0-next.18` with https://codepen.io/geospatialem/pen/bGyeZwM, where:
- `s` is `8px`
- `m` is `12px`
- `l` is `16px`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/22abc734-016d-4181-a47b-0062a94d0622)
