### ISSUE TITLE
[Tree, Tree-Item] update indentation & add padding for better visual hierarchy

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7096]
### Description

Update indentation and spacing for`tree-item`s. This was outlined as part of the work to audit and update nested indentations to improve visual hierarchy across components (Epic https://github.com/Esri/calcite-components/issues/6632).

### Acceptance Criteria

- [x] Update item indent value
- [x] Add `padding`
- [x] Add `gap`
- [x] Remove `min-height`
- [x] Remove `padding` around all icons
- [x] Correct `lines` alignment
- [x] Correct icon position in `selection-mode=“ancestors”`

[Full Figma specs for all scales](https://www.figma.com/design/LV1M8Hjoc2aD5zBr61XCa2/Nested-Indent-Spacing-%5Bepic-6632%5D?node-id=287-113361&m=dev&focus-id=246-227576)

Before/after example:
![CleanShot 2024-10-28 at 08 47 09@2x](https://github.com/user-attachments/assets/c2aada33-3a8f-4c81-b463-239c0874b619)

### Which Component

Tree, Tree Item

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on Storybook with `3.0.0-next.60`.
