### ISSUE TITLE
[Combobox Item, Combobox Item Group] - update indentation for better visual hierarchy

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7099]
### Description

Update indentation padding when nesting `combobox-items` and `combobox-item-groups`. This was outlined as part of the work to audit and update nested indentations to improve visual hierarchy across components (Epic https://github.com/Esri/calcite-components/issues/6632).

### Acceptance Criteria

- [x] Items slotted in a group should have their `indent-multiplier` reset to 1
- [x] Update group-label `padding-inline` to match item padding

[Figma spec for all scales](https://www.figma.com/design/LV1M8Hjoc2aD5zBr61XCa2/Nested-Indent-Spacing-%5Bepic-6632%5D?node-id=287-113361&m=dev&focus-id=305-99983)

Before/After example:
![CleanShot 2024-10-30 at 15 00 19@2x](https://github.com/user-attachments/assets/7581a063-94b2-48cb-9eac-6573834f4639)

### Which Component

Combobox Item
Combobox Item Group

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

Blocked by https://github.com/Esri/calcite-design-system/issues/10897

**Comment by geospatialem** [comment]
Blocked by #10897, moving to December to accommodate.

**Comment by geospatialem** [comment]
Verified on [Storybook](https://esri.github.io/calcite-design-system/?path=/story/components-controls-combobox--nested-groups-test-only) with `3.0.0-next.60`.
