### ISSUE TITLE
[List], [List Item], [List Item Group]: add scales, update padding and spacing, update font sizes

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7100]
### Description

Add scales and related updates to List, List Item, and List Item Group. See this [Figma file](https://www.figma.com/design/91sfHrYNt0Il6B4pEZZ749/List-scales%2C-sorting%2C-groups%2C-and-interaction?node-id=982-37071&m=dev&focus-id=1066-43440) for full specs. Note that file also contains other related updates to List.

### Acceptance Criteria

- [x] Add scales
- [x] Update padding and spacing
- [x] Update font sizes
- [x] Align bottom border to content area
- [x] Revised hit targets to meet AA minimum
- [x] Add default padding to content with CSS vars for overrides - 🚧 `breaking change` ❗ 
- [x] Use inner-shadow for `selection-appearance="border"` to maintain alignment

### Relevant Info

These are updated designs since this issue was originally created. They prioritize reducing unnecessary whitespace around elements to conserve horizontal real estate, 24px AA minimum hit targets, and improving visual hierarchy when nesting.

Pair with #9173, #9174, and #9175

Full specs available in [Figma file](https://www.figma.com/design/91sfHrYNt0Il6B4pEZZ749/List-scales%2C-sorting%2C-groups%2C-and-interaction?node-id=982-37071&m=dev&focus-id=1066-43440), before/after reference below:
![Slice 1](https://github.com/user-attachments/assets/b7c92582-840c-4135-8c11-4b34aea299fc)

### Which Component

List
List Item
List Item Group

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by driskull** [comment]
We may wan to reconsider how we indent child items as well. Currently, we only indent within the item but not the whole item.

<img width="310" alt="image" src="https://github.com/Esri/calcite-design-system/assets/1231455/d619ba44-11d1-481b-8cd5-a6188177c145">

The problem with this is that the selection is still far to the side and when dragging a child there isnt a good way to distinguish where its going because they are all indented the same. No matter how deep the child is, the element spans the whole width. 

I think we did this originally so that the hover/active/focus spans the whole width of the list but I think we should reconsider.

<img width="493" alt="image" src="https://github.com/Esri/calcite-design-system/assets/1231455/a0ded77d-e94d-4512-bd48-fec3500df173">

**Comment by driskull** [comment]
@ashetland can the "indent entire item" be included in this as well? Do we have approval/consensus to do that?

**Comment by ashetland** [comment]
> @ashetland can the "indent entire item" be included in this as well? Do we have approval/consensus to do that?

Yep, happy to look at that for this. I did start exploring some options, but haven't run any of the visuals by @SkyeSeitz or @macandcheese yet.

**Comment by ashetland** [comment]
Thanks for your patience on this one, @driskull! We'd like to hold off on making the updates outlined above for now. After more discussion, we've decided it would better to take a deeper look into nesting and grouping List Items. We're going to pull this one back into the design pipeline and I will update the issue description accordingly. cc @SkyeSeitz @macandcheese @geospatialem

**Comment by driskull** [comment]
Sounds good. Just want to again push for nesting the whole item as it provides better UX and visual feedback for dragging an item. Without nesting the whole item, its difficult to tell where the item is actually being placed when nested items occur.

![nested-drag-ux](https://github.com/Esri/calcite-design-system/assets/1231455/9e0aaf77-bb3c-41fd-ac2d-140c237c8198)

**Comment by zaramatheson** [comment]
![image](https://github.com/Esri/calcite-design-system/assets/50747646/1fc13daf-0aec-4ec2-8095-223563d4f2da)
Another example from Map Viewer using a heavily nested KML layer of the difference after updating to the calcite list (right)

**Comment by ashetland** [comment]
Ouch. Yes.

**Comment by sagewall** [comment]
cc @sagewall

**Comment by jgrayson-apl** [comment]
+1 for having a more pronounced visual difference between the calcite-list-item label and description please.  Here's an example of what we struggle with where we need the label to be larger in size:

![f587b254-a940-4a05-a23e-a4c085df8238](https://github.com/Esri/calcite-design-system/assets/5324720/5a078cbf-d320-40bf-9a73-b3b50656e54b)

**Comment by ashetland** [comment]
As part of the refinement of the designs for this, we intend on incorporating the font sizes outlined in issue #7623. The above example would look like this post-implementation:
![Frame 259](https://github.com/Esri/calcite-design-system/assets/108549080/09db42d7-d43f-4093-a133-f2a482ae012f)

**Comment by ashetland** [comment]
Updated issue title and description to reflect new designs.

**Comment by ashetland** [comment]
@driskull I've updated the title and description of this issue based on our discussion and the new designs. I also added the `breaking changes` and `visual changes` labels.

**Comment by driskull** [comment]
@geospatialem @ashetland I think this should be moved milestone since it will have breaking changes. right?

**Comment by ashetland** [comment]
Makes sense to me

**Comment by geospatialem** [comment]
Thanks @driskull and @ashetland, and great catch! 

We'll be planning the breaking change release timeline in the next few weeks. Stay tuned for when we can add this to an upcoming milestone.

**Comment by ashetland** [comment]
Thanks @geospatialem! This should also be paired with #9173 and #9174.

**Comment by driskull** [comment]
@ashetland @geospatialem do we have a milestone for this issue?

**Comment by geospatialem** [comment]
> @ashetland @geospatialem do we have a milestone for this issue?

@driskull Added the above, https://github.com/Esri/calcite-design-system/issues/9173 and https://github.com/Esri/calcite-design-system/issues/9174 to November's milestone for the breaking changes.

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.40` with:
- `scale` (`"s"`, `"m"`, `"l"`)
- `selectionMode` (`"single"`, `"multiple"`, `"none"`, and `"single-persist"`)
- `selectionAppearance` (`"border"`, `"icon"` )
- `displayMode` of `"nested"`, `"flat"`)
