### ISSUE TITLE
`menu`, `menu-item` vertical layout: update indentation padding and icon spacing

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7105]
### Description

For `menu-item` `layout=vertical`, update indentation padding when nesting `menu-items` and update icon spacing for consistency. This was outlined as part of the work to audit and update nested indentations to improve visual hierarchy across components (Epic https://github.com/Esri/calcite-components/issues/6632).

See [Figma file](https://www.figma.com/file/LV1M8Hjoc2aD5zBr61XCa2/Nested-Indent-Spacing-Across-Components?type=design&node-id=353-113071&t=8EyGVFh0IreYmb1D-11) for full spec and additional context.

### Acceptance Criteria

For vertical layout:
- [x] Update indentation padding of `menu-items`
- [x] Update icon spacing in `menu-items`
- [x] Adjust position of `arrow-right` when href is populated

### Which Component

Menu Item

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.28`
