### ISSUE TITLE
calcite-navigation-logo: allow slot/property for icon instead of image

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-design-system#7124]
### Description

For the new calcite-navigation-logo, please provide a slot/property for an icon instead of image as _most_ of the time we don't have an application specific image and use a simple icon instead.

### Acceptance Criteria

We need the ability to use an icon instead of a in image 

### Which Component

calcite-navigation-logo

### Priority impact

p4 - not time sensitive

### Esri team

N/A

**Comment by jgrayson-apl** [comment]
FYI: found a workaround by adding a do-nothing calcite-action to the 'navigation-action' slot of the calcite-navigation. Not ideal as we don't have the direct ability to disable pointer interactions and calcite-icon won't align correctly...  but ok for now.

**Comment by geospatialem** [comment]
Verified in `1.10.0-next.8`, also for `rtl`, with the following:

```html
<calcite-shell>
  <calcite-navigation slot="header">
    <calcite-navigation-logo heading="Whale sightings" icon="globe" description="2023 data observations" slot="logo">
    </calcite-navigation-logo>
  </calcite-navigation>
</calcite-shell>
```
