### ISSUE TITLE
calcite-shell: provide alternate layout orientation of slotted content

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-design-system#7129]
### Description

Please provide the ability to better control the layout orientation of the slotted content.  For simple GIS apps we need the ability to better control how the slotted content is arranged on the page, especially when embedding a calcite-shell inside a calcite-shell.  Here's a simple example:

design=sidebar
![layout_design_sidebar](https://github.com/Esri/calcite-components/assets/5324720/360ae3c2-fcee-40e0-b2b7-4727d9cf2452)

design=headline
![layout_design_headline](https://github.com/Esri/calcite-components/assets/5324720/83b190df-7d1b-489c-be56-06d4967181a9)

### Acceptance Criteria

Concept also explained here: https://developers.arcgis.com/javascript/3/jshelp/inside_dojoLayouts.html

### Which Component

calcite-shell

### Priority impact

p4 - not time sensitive

### Esri team

N/A

**Comment by macandcheese** [comment]
To keep naming consistent, this could be achieved through a `layout` property on Shell that accepts `horizontal` and `vertical` and defaults to the current behavior. The `header` / `footer` slots should remain unchanged in their placement.
