### ISSUE TITLE
Navigation user has an AGOL user object property filling out all user information in the component

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-design-system#7136]
### Description

The navigation user components accepts an optional user property based on the data structure of the user object from ArcGIS REST JS. It lets the navigation user component show the name, username and eventually the profile picture of the user.

Documentation on the User object can be found here: https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-portal/IUser

### Acceptance Criteria

The navigation user components shows the user information when the user property in the navigation user component is populated with the User object from the ArcGIS REST JS (portal) package. 

### Relevant Info

The profile picture is not in the User object itself, but can be find like this function: https://github.com/Esri/calcite-react/blob/ae9ac239c63242c860142e453ab2950e2b6009b6/src/ArcgisAccount/accountManagerUtils.js#L258

### Which Component

Navigation User

### Example Use Case

https://calcite-react.netlify.app/arcgis-account

### Priority impact

p4 - not time sensitive

### Esri team

Professional Services - Services Delivery

**Comment by geospatialem** [comment]
Closing the above as it is out of scope for Calcite and is product-specific. As Adam [mentions above](https://github.com/Esri/calcite-design-system/issues/7136#issuecomment-1584765185), this could be a good component with other teams situated in the Maps SDK for JS team.
