### ISSUE TITLE
[calcite-slider] If the group separator is space, the number will be cut off at group separators

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#7151]
### Actual Behavior

Language like ru uses space as the group separator, and when the space is used as the group separator, the number will be cut off in between.
![image](https://github.com/Esri/calcite-components/assets/26078106/a9af51b4-bbb0-4bf3-82cd-b1de0fdb9381)
![image](https://github.com/Esri/calcite-components/assets/26078106/47c007f4-6997-4794-9e36-417e7bfef9ef)

### Expected Behavior

Even the space is used as the group separator, the number should not be broken into multiple lines.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/slider/

### Reproduction Steps

1. Enable group separator
2. Change the locale to ru

### Reproduction Version

v1.4.1

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Survey123

**Comment by geospatialem** [comment]
Verified in `1.5.1-next.4`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/aa17f68e-8b24-46e3-9a3d-23a687574565)
