### ISSUE TITLE
[Shell] Add "Sheet" Slot

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7154]
### Description

Similar to Alert, and Modal, we should offer a slot within Shell to accept a https://github.com/Esri/calcite-components/issues/6391.

### Acceptance Criteria

Depends on https://github.com/Esri/calcite-components/issues/6391

### Which Component

Sheet, Shell

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.13`.
