### ISSUE TITLE
Access to the textLabel property of the combobox

### ISSUE THREAD

**Issue by lkoumis** [Esri/calcite-design-system#7176]
### Description

Presently, I can get the value of the combobox by just using the 
`document.getElementById("combo_id").value`
however to get the textLabel property, the calciteComboboxChange method has to be used. 
This scenario is very complex, if I have multiple comboboxes and I want to get the textLabel of all the comboboxes when I click a button? Also, what if the user changes the value of one of the comboboxes. It is becoming complex to gather the current textLabel of all comboboxes the ones that were modified and the ones which didn't. 

### Acceptance Criteria

Ability to get the textLabel property similar to the way you can get the value of the combobox

document.getElementById("combo_id").value
document.getElementById("combo_id").textLabel

Avoid needlessly more complex code to get the textLabel property.

### Which Component

Combobox
Combobox-Item

### Priority impact

p1 - need for current milestone

### Esri team

N/A

**Comment by benelan** [comment]
Can you please provide a quick description of the use case for why you need to get the Combobox Item's `textLabel` and why the `value` isn't sufficient? E.g. an example of the data and what you need to do with it after a user selects an item.

**Comment by geospatialem** [comment]
@lkoumis Could you provide a use case for the above request for the Calcite team to evaluate and consider?

**Comment by lkoumis** [comment]
THe values of the comboxes can be very long. In my case they are urls and they are very similar to each other. When the user select each combobox, as a developer I have to script the further actions with the selected values. Each selected url requires different action. When you work with 10 or more comboboxes,  it becomes necessary to keep a legend of what each value represents because of the url's complex address and I can't keep track of the values which is 50 or more characters contained in urls. THe work can be a lot more simple, if I could use the textLabel is a similar fashion like the value.  Currently, it requires more steps to acquire the textLabel. This is a request. If ESRI finds it too cumbersome to implement it, then I guess we have to deal with it. Thank you.

**Comment by geospatialem** [comment]
@lkoumis The `combobox` is functioning as-designed, so will be closing the above issue out. However, there are workarounds, and its possible to store [data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) to accommodate the long urls. 

For instance:

```html
<calcite-combobox-item data-url="https://placebear.com/" value="bear" text-label="Bear"></calcite-combobox-item>
```

But, if that's not feasible for the use case, a few lines of JavaScript should fit the need. For instance: https://codepen.io/geospatialem/pen/BaeRpyB

Closing the above based on the workflow described above and as the component is functioning as-designed.
