### ISSUE TITLE
`calcite-input-number` - input keeps increasing/decreasing if the mouseup happens outside the increment/decrement button

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-design-system#7188]
### Actual Behavior

If a user clicks the increment/decrement button on the number input, the moves the mouse button off the increment/decrement button, the input value continues to increase/decrease. The user has to re-click to make it stop

Observe in the video the increment button loses focus but the value keeps increasing until I click again

### Expected Behavior

I think it should stop increment/decrement as soon as the mouse out happens and the button loses focus

### Reproduction Sample

https://codepen.io/eborgen/pen/ExOKNLP?editors=1010

### Reproduction Steps

![issue-long-mouse-press](https://github.com/Esri/calcite-design-system/assets/5023024/67a9d7dc-8450-42f4-8ad3-ca4e2ede4566)

See gif above

### Reproduction Version

1.4.2

### Relevant Info

Reproducible in latest chrome/ff - does not seem browser specific

Not reproducible using `calcite-input` type `number`

### Priority impact

p3 - want for upcoming milestone

### Impact

I think its an odd user behavior but  changing the value without user action / no easy way to stop it is confusing

### Esri team

ArcGIS Web Analysis

**Comment by ethanbdev** [comment]
Another test case I just found - if you use the keyboard up/down keys, then tab to lose the focus on the input, the same behavior happens.

**Comment by anveshmekala** [comment]
Hi @ethanbdev , i am unable to repro the issue in the Codepen link  using Chrome 118.0 version and FF 118.0.2 . Additionally tested with latest calcite version 1.9.2 and couldn't repro either. Is this still reproducible?

**Comment by ethanbdev** [comment]
> Hi @ethanbdev , i am unable to repro the issue in the Codepen link using Chrome 118.0 version and FF 118.0.2 . Additionally tested with latest calcite version 1.9.2 and couldn't repro either. Is this still reproducible?

Let me check with the team

**Comment by ethanbdev** [comment]
> Hi @ethanbdev , i am unable to repro the issue in the Codepen link using Chrome 118.0 version and FF 118.0.2 . Additionally tested with latest calcite version 1.9.2 and couldn't repro either. Is this still reproducible?

It still reproduces for me, same chrome version and calcite version. I update the codepen to the latest.

**Comment by anveshmekala** [comment]
Thanks for the confirmation @ethanbdev , I am able to repro this by clicking on the increment/decrement button for longer period of time before moving it away.

**Comment by geospatialem** [comment]
Additional testing and review will take place later this week, and should be available as part of `next`. For now moving to the November milestone.

**Comment by geospatialem** [comment]
With the verification the mouse click event has been resolved, and additional effort is needed to fulfill the arrow keys (when holding down) and shifting focus outside of the component, observed in https://codepen.io/geospatialem/pen/RwvjdaG with `1.11.0-next.3`. cc @anveshmekala
