### ISSUE TITLE
[Shell / Shell Panel]: Allow slotted `displayMode: float` Shell Panels to position absolutely

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7199]
### Description

Currently, when using Shell (without `content-behind`), there really is no use for the "float" `displayMode` value - it positions itself over a swim lane and has a "floating shadow" - but it is not positioned absolutely over main slotted content area.

This means that layouts with one "dock" and one "float" slotted Shell Panel cannot be achieved without `content-behind`, which is not always desirable.

### Acceptance Criteria

In a Shell  (without `content-behind`), the "float" value of `displayMode` behaves as an absolutely positioned element, and truly "floats" above the content. It should behave similarly to "float" when `content-behind` is set on Shell.

### Relevant Info

While it seems we want to keep `content-behind` for the time being as it can be useful for certain mapping needs, adjusting the "non `content-behind`" Shell story in this way will allow more layouts to be achieved. 

### Which Component

Shell / Shell Panel

### Example Use Case

Current with a "float" Shell Panel slotted in "panel-end":
![Screen Shot 2023-06-20 at 9 35 32 AM](https://github.com/Esri/calcite-components/assets/4733155/94f83312-8c6f-4ced-aa2c-7cbc89d64e45)

Desired with a "float" Shell Panel slotted in "panel-end":
![Screen Shot 2023-06-20 at 9 36 00 AM](https://github.com/Esri/calcite-components/assets/4733155/90fc84cd-8764-4536-9bc7-25ed30a8f749)

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
+1 from UC customer

**Comment by macandcheese** [comment]
Related: https://github.com/Esri/calcite-design-system/issues/1932

**Comment by geospatialem** [comment]
Added [additional acceptance criteria and context](https://github.com/Esri/calcite-design-system/issues/1932#issuecomment-1908630791) to the related issue. Closing in favor of the efforts of #1932.
