### ISSUE TITLE
[Loader / Progress] Make value property consistent

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7207]
### Description

Currently, Progress accepts a value between 0 -> 1.0, whereas Loader accepts a value between 0 -> 100. It would be nice to gain alignment between these components.

### Acceptance Criteria

I have no preference which is used, but have both of these components use a similar expected value.

### Which Component

Progress / Loader

### Example Use Case

As a user, having two different types of value for similar components can be unexpected.

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by Elijbet** [comment]
Did a bit of research of similar libraries. Spectrum, Shoelace, Carbon, ui5 all use 100% max value for progress/loader. Some don't have a loader, or call loaders progress circle/ring instead. Vaadin is the only one so far that uses a range 0-1.

**Comment by benelan** [comment]
I vote for changing loader instead of progress, because there is no native loader and I'd prefer to keep progress in line with what native does:

**Comment by benelan** [comment]
Also could we call this a breaking change instead of a fix? If people are setting values in their app, changing the default progress/loader range would change how much of the task appears completed.

**Comment by Elijbet** [comment]
@benelan, @jcfranco 
We looked at our components vs native components and saw this distribution:

From our API consistency, we're looking at:

**0 – 100**
* loader
* meter

**0 – 1**
* progress
 
Taking your point, if we compare those to native equivalents, we've got:

**0 – 1**
* progress
* meter

We decided to deviate from native. It seems to be more in line with existing component libs and meter doesn't follow this either.
We also felt that from a dev perspective, you'd likely expect 0-100.

**Comment by geospatialem** [comment]
Verified on the `dev` branch, where `progress` has a `type="determinate"` and a specified `value` between `0` and `100`):

```html
<calcite-progress type="determinate" value="92"></calcite-progress>
```

As mentioned in Eliza's comment [above](https://github.com/Esri/calcite-design-system/issues/7207#issuecomment-2460985536) `loader` and `meter` already contain this pattern (confirmed on the `dev` branch) with the following for `loader` (_Note_: `100` is considered `complete` on the component):

```html
<calcite-loader label="Loading the holidays" text="Loading..." type="determinate" value="92"></calcite-loader>
```
