### ISSUE TITLE
Provide unique link text to assistive technology

### ISSUE THREAD

**Issue by shellchulx** [Esri/calcite-design-system#7210]
### Description

Currently, the semantics are not mapped to the accessibility API for calcite-link with the role="presentation", which the Calcite team explains as why the aria-label isn't read back to all AT. An enhancement request to add support for a label attribute for calcite-link could help fix this. 
![Screenshot 2023-06-21 at 4 27 05 PM](https://github.com/Esri/calcite-components/assets/14854017/e15b940d-10fb-46e9-848b-c8658a7d84dd)

cc @catherinehynes 

### Acceptance Criteria

NVDA will read the aria-label

### Which Component

calcite-link

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Enterprise

**Comment by geospatialem** [comment]
@shellchulx Could you provide a use case for the benefit of a `label` over the current slotted link text for us to consider and prioritize the enhancement?

**Comment by catherinehynes** [comment]
@geospatialem The ArcGIS Enterprise accessibility evaluation at 10.9.1 included an audit of the portal home app Organization > Licenses page, which has a **Manage** link for many different types of add-on licenses:

![image](https://github.com/Esri/calcite-components/assets/9846742/bfd149b2-faca-438b-90b5-cd40695f4a64)

This is where we were hoping to add a `label` for each link so we could have a more descriptive name for AT.

**Comment by geospatialem** [comment]
> This is where we were hoping to add a `label` for each link so we could have a more descriptive name for AT.

Thanks for the quick response, @catherinehynes! Out of curiosity could the `button` component work in this use case? Wondering if perhaps it could provide a [similar use case](https://developers.arcgis.com/calcite-design-system/components/button/#accessibility), as it contains `href` and `label` attributes.

For instance: https://codepen.io/geospatialem/pen/dyQOyEZ

**Comment by geospatialem** [comment]
@catherinehynes @shellchulx Would the [above recommendation with `button`](https://github.com/Esri/calcite-design-system/issues/7210#issuecomment-1603467881) fit the use case? If changing the component altogether isn't feasible, could a `.sr-only`, or similar, `span` element be added to provide unique context?

**Comment by geospatialem** [comment]
@catherinehynes @shellchulx Circling back to the above, was `button` able to achieve the need?

**Comment by geospatialem** [comment]
Closing the above with the [recommended workflow](https://github.com/Esri/calcite-design-system/issues/7210#issuecomment-1603467881).
