### ISSUE TITLE
Provide set focus functionality to the component calcite-accordion-item

### ISSUE THREAD

**Issue by shellchulx** [Esri/calcite-design-system#7211]
### Description

https://developers.arcgis.com/calcite-design-system/components/button/#api-reference-methods-setFocus

Can we add a setFocus function to `calcite-accordion-item`? This function is not configured, while it is for many other calcite elements like button etc in the reference link. 

To get it focused on the `calcite-accordion-item`, `shadowRoot.querySelector` is used in my but I know this is not the best practice.

cc @catherinehynes @rpanichakit9541 @MHB6119

### Acceptance Criteria

Don't need to use `shadowRoot.querySelector` to focus

### Which Component

calcite-accordion-item

### Example Use Case

- [x] 2. After hitting enter on Save button, focus should return to the Feature Server Configuration drop-down menu 

![image](https://github.com/Esri/calcite-components/assets/14854017/a39b5a25-17a4-48cd-b773-045356a3b348)

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Enterprise

**Comment by DitwanP** [comment]
🍬 Verified on `2.9.0-next.18`
