### ISSUE TITLE
calcite-input-date-picker: throws two change events for valueAsDate

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#7218]
### Actual Behavior

If you set the date via `valueAsDate` the `input-date-picker` component throws 2 `calciteInputDatePickerChange` events. This is not happening when using the `value` prop.

### Expected Behavior

It should only throw one event if you change the date value once. Both for `value` and `valueAsDate`.

### Reproduction Sample

https://codepen.io/afreitag/pen/yLPOpVY

### Reproduction Steps

Open codepen and change the date once of each of the input-date-pickers. You can see that the second version throws 2 events initially.

### Reproduction Version

1.4.2

### Regression?

no

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Map Viewer

**Comment by DitwanP** [comment]
Verified locally on `main` 🍡

**Comment by AdelheidF** [comment]
looks good to me too using 2.1.0
