### ISSUE TITLE
Adding a default start and end date to the range in the calcite-input-date-picker

### ISSUE THREAD

**Issue by nudeshi** [Esri/calcite-design-system#7238]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates

### Description

The inclusion of a default range functionality in the date picker is essential for enhanced usability and efficient date selection. It allows users to quickly access and modify preexisting start and end dates, minimizing manual input and improving overall user experience. This feature simplifies the process of changing default ranges, offering a seamless and intuitive interface for date selection.

### Acceptance Criteria

The `calcite-input-date-picker` should include a default range option that displays preexisting start and end dates, allowing users to immediately view and work with those dates.

### Which Component

`calcite-input-date-picker`

### Priority impact

p2 - want for current milestone

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Developer Experience

**Comment by geospatialem** [comment]
@nudeshi Apologies for the delayed response. Can you follow-up with a use case for the above so the team can work towards prioritizing the effort. 

Wondering about what is being implemented or is the goal for achieving. Do you have a Codepen or mockup to provide on the context?

**Comment by geospatialem** [comment]
@nudeshi Following up if you can provide a use case or defined goal. Could you create a Codepen or mockup to provide the team with context for prioritization?

**Comment by geospatialem** [comment]
Closing the above without a use case to proceed forth. @nudeshi Will re-open if additional context is provided in this issue.
