### ISSUE TITLE
The calcite-slider slider component breaks when the tick number is too large 

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#7242]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates

### Description

The calcite-slider slider component breaks when the tick number is too large.
<img width="1728" alt="image" src="https://github.com/Esri/calcite-components/assets/26078106/0b0ff862-68c4-4721-9b45-3042683de83f">
<img width="1728" alt="image" src="https://github.com/Esri/calcite-components/assets/26078106/f352fa67-dfe8-4035-8f02-d54735474848">

### Acceptance Criteria

Automatically group/cluster the ticks to reduce the tick number. Then, the slider won't break the web page.

### Which Component

calcite-slider

### Example Use Case

We use the the slider component in the Survey123 to support a new slider question type. Sometime user might accidentally set the slider question with too many ticks, which drops the page performance or breaks the page.

### Priority impact

p4 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Survey123

**Comment by macandcheese** [comment]
I'd consider this a bug and a pretty serious one as it can potentially crash the page. 

It's reproducible in Codepen as well - note the component doesn't even load if the page doesn't freeze for you: https://codepen.io/mac_and_cheese/pen/qBQrJXY?editors=1000

It seems to become worse the more ticks need to be rendered - whether that's a very high 'max' value and a step of '1', or a reasonable max and a fractional step value that causes thousands to render like '.1'.

Defer on priority between Medium / High - cc @geospatialem / @jcfranco
