### ISSUE TITLE
Low color contrast in Button and Segmented Control in dark mode

### ISSUE THREAD

**Issue by Anastasiia-Boleiko** [Esri/calcite-design-system#7250]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates

### Summary

The Calcite Button and the selected option of Calcite Segmented Control (appearance: solid) have low contrast Components in the dark mode.

WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. WCAG 2.1 requires a contrast ratio of at least 3:1 for graphics and user interface components (such as form input borders). WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.

Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger.

### Actual Behavior

In both cases, the `font-size: 14px`, `color: #353535` and `background: #009AF2 `
**Color contrast is 4.03.**

<img width="300" alt="Screenshot 2023-06-30 at 13 15 12" src="https://github.com/Esri/calcite-components/assets/119309703/39b0aeaa-765e-4a4e-bcf1-a4afc1646853">

### Expected Behavior

Proposal: Change the color to `color: var(--calcite-ui-text-inverse)` (#151515) for example.
**Color contrast is 6.**
<img width="300" alt="Screenshot 2023-06-30 at 17 20 06" src="https://github.com/Esri/calcite-components/assets/119309703/83f7ab02-5e35-409a-a415-815c1492802e">

### Reproduction Sample

https://codepen.io/anastasiia-zrh/pen/JjeNrRy?editors=100

### Reproduction Steps

1. Add a Segmented Control/Button to a page
2. Make sure that the page is in the dark mode
3. Make sure that the [appearance](url) parameter is set to` default (solid)`
4. Make sure that the `kind` parameter is set to ` default (brand)`

### Reproduction Version

v1.4.3

### Working W3C Example/Tutorial

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Urban

**Comment by ashetland** [comment]
Preliminary digging showed that Segmented Control is set to ui-background instead of ui-text-inverse. Further digging need to confirm all configs on Button and Segmented Control.

**Comment by jacqueskeet** [comment]
Button (as of v1.7) seems to not have the issue. It's passing AA standards as intended. Segmented Control on the other hand requires a color update on the text from **ui-background** to **ui-text-inverse**. Update already done on the Figma kit. See [here](https://www.figma.com/file/fBkmuAy3R4BfjAWlRi2KjS/Calcite-Web-UI-Kit?type=design&node-id=5919-156189&mode=design&t=pwjG7kIiOsBZ69Ni-4).

**Comment by geospatialem** [comment]
Verified in `1.10.0-next.7`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/616f9123-b15d-4ea8-92cb-b219c862c543)
