### ISSUE TITLE
Ensure all `setFocus` calls return `setFocus` from internal components

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7270]
### Description

For consistency, components implementing `setFocus` that end up calling `setFocus` on internal, supporting components should return the promise from this method call.

cc @driskull 

### Proposed Advantages

All `setFocus` calls are chained properly.

### Which Component

Any component implementing `setFocus` whose method calls `setFocus` or the `focusElement` helper.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

**Comment by geospatialem** [comment]
Verified on `master`.
