### ISSUE TITLE
Update the focusable test helper and spec test to correctly test focusing internal elements

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7276]
### Test type

New test

### Which Component(s)

focusable commonTest

### Test error, if applicable

https://github.com/Esri/calcite-design-system/pull/7255#pullrequestreview-1511807784

### PR skipped, if applicable

#

### Additional Info

https://github.com/Esri/calcite-design-system/pull/7255#pullrequestreview-1511807784

**Comment by driskull** [comment]
Yeah I think it would 👍

**Comment by jcfranco** [comment]
Awesome, closing!
