### ISSUE TITLE
[Link] Incorrect underline animation in RTL

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7284]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The underline animation does not correctly animate in the expected direction when in RTL.

### Expected Behavior

I'd expect the animation to correctly display as it does in LTR, but flipped.

cc @SkyeSeitz @ashetland - I know we've talked about changing this animation altogether and favoring something less... busy - maybe an additional px height on hover, just color change, etc., so could be a good opportunity to look at that.

Related: https://github.com/Esri/calcite-design-system/issues/6569

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/qBQXYKB?editors=1000

### Reproduction Steps

1. Go to Codepen
2. See difference in animation

### Reproduction Version

Latest

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
cc @ashetland @SkyeSeitz WDYT/ any thoughts on changes to the `link` animation?

**Comment by SkyeSeitz** [comment]
I could definitely see a few options where the animation is removed. I think I lean towards just an instant color change from 40% opacity to 100%, as seen in [the prototype below](https://www.figma.com/proto/YwTpfq3LjR1UrPX8lQ8ON4/%5BLink%5D-Incorrect-underline-animation-in-RTL-%5Bissue-7284%5D?page-id=2%3A165&type=design&node-id=101-147&viewport=787%2C644%2C3.65&t=JHS3vgF2LWeLz4BU-1&scaling=min-zoom&mode=design).  

https://github.com/Esri/calcite-design-system/assets/29716057/71c8f58b-15d8-4174-88e4-c6a6044413aa

**Comment by ashetland** [comment]
I like that instant change. Mocked up a bump from 1px to 2px for the indicator @macandcheese mentioned just for comparison. I think I go for the simple version or just instant timing.
![CleanShot 2023-08-07 at 12 09 13](https://github.com/Esri/calcite-design-system/assets/108549080/20af8261-0513-41bc-8120-b0d2ed11e348)

**Comment by SkyeSeitz** [comment]
Clarifying question for @macandcheese 😅 - Additional px to the underline or the height of the link? [Prototype](https://www.figma.com/proto/YwTpfq3LjR1UrPX8lQ8ON4/%5BLink%5D-Incorrect-underline-animation-in-RTL-%5Bissue-7284%5D?page-id=2%3A165&type=design&node-id=105-87&viewport=192%2C562%2C2.73&t=Z143UHpvQgkhJ7ds-1&scaling=min-zoom&mode=design) below to demonstrate:

https://github.com/Esri/calcite-design-system/assets/29716057/2a75ab64-806f-446d-bdcf-7e571a886faa

**Comment by jcfranco** [comment]
@macandcheese Could you help clarify the comment above?

**Comment by macandcheese** [comment]
Sorry, which comment 😅

I think the immediate issue can be fixed with no design change, and then we can separately discuss an update there cc @SkyeSeitz @ashetland (I wouldn't think that a border change bumps the height up like in that example)

**Comment by jcfranco** [comment]
@macandcheese I was referring to https://github.com/Esri/calcite-design-system/issues/7284#issuecomment-1668445088, apologies for not specifying earlier. 

One more question, are we keeping the animation as is, but inverting it or are we also simplifying it to just color change?

**Comment by macandcheese** [comment]
The scope of the issue initially was intended to just fix the RTL implementation. It works fine in LTR. I think this other discussion is good and we should update the visual, but can be moved to a separate design issue?

**Comment by jcfranco** [comment]
Looks like the animation has been broken since v2.7.0 (possibly by https://github.com/Esri/calcite-design-system/pull/8797).

**Comment by macandcheese** [comment]
Heh - well in this case it's a "fix" as it behaves the same in both. I don't think the animation really adds anything. Maybe we can remove the code that isn't working and use another issue to track improvements. I'd think anything that lets us get rid of the "transparent underline" css, etc. could be nice.

**Comment by ashetland** [comment]
Agreed

**Comment by DitwanP** [comment]
Verified locally on `dev`

Fixed animations:


https://github.com/user-attachments/assets/15039e4e-b0bf-4acc-b62e-f53e641ca2d4
