### ISSUE TITLE
[Combobox] Append custom values to top of Combobox dropdown, not bottom

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7288]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, when `allow-custom-values` is true and a user adds a custom value, it is appended to the bottom of the Combobox dropdown. 

This can be confusing, as when presented alongside groups, it's not clear if the added value is part of the last group due to indentation:

<img width="1019" alt="Screen Shot 2023-07-06 at 11 12 58 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/631c0989-be7a-40ff-9486-c10e2b276b3b">

### Acceptance Criteria

The appended items are added to the top

### Relevant Info

There are probably additional desirable configurations - sometimes an app may want to add a created item to a specific group, or allow a user to remove an item they've created.

cc @ashetland @mitc7862 

### Which Component

Combobox

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.21`
