### ISSUE TITLE
calcite-tree stays in indeterminate state when all children are programmatically de-selected

### ISSUE THREAD

**Issue by sonofflynn89** [Esri/calcite-design-system#7291]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

On the ArcGIS Hub team, we use the `calcite-tree` component with `selection-mode="ancestors"` to render a dynamic option tree. We also have filter chips that users can dismiss to programmatically unselect an option:

![image](https://github.com/Esri/calcite-design-system/assets/30124777/550a9428-1d72-46d1-9fd2-e5174ca99c72)

When a tree only has 1 option selected (displaying the parent node as `indeterminate`) and we dismiss the filter chip (indicating that the option should be de-selected programmatically), the option gets de-selected **BUT** the parent node remains in an indeterminant state.

https://github.com/Esri/calcite-design-system/assets/30124777/36441d8d-0cff-4700-96ca-d9b98c564b46

### Expected Behavior

Since all child nodes of the tree are unselected, the parent node should also be changed to the `unselected` state

### Reproduction Sample

https://codepen.io/sonofflynn89-the-reactor/pen/KKrXVJe

### Reproduction Steps

- Open the above code pen
- Note that the tree on the right has one child option selected, with the parent in indeterminant state
- Click the "programmatically de-select" button to remove the `selected` attribute from all the tree nodes
- Note that the option is deselected, but the parent remains indeterminant

### Reproduction Version

1.4.3

### Priority impact

p3 - want for upcoming milestone

### Impact

This is a noticeable visual bug on our new search page, which we will be releasing out of beta in early August.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
Effort should be researched and executed in coordination with #7104

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.9`
