### ISSUE TITLE
[Slider] Expose slider fill css variable

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7312]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

UC customer request to add css variable for the fill of the slider - adjusting brand value also changes the handle which is not desirable. 

### Acceptance Criteria

Css variable for slider fill is exposed and made public. 

### Which Component

Slider

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by alisonailea** [comment]
Reopening to make sure this is addressed in token work

**Comment by DitwanP** [comment]
Closing now that tokens have been added.
