### ISSUE TITLE
[Audit] Consistent corner radius treatment

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#7322]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

There is currently a mix of various rounded and sharp corners throughout elevated and non-elevated Calcite components. This proposal is to take a more consistent approach to Calcite's corner radius style. 

<img width="1410" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/d843bf97-bee0-4fc8-b602-f5a0379fd0ca">
<img width="1442" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/f3e9e40b-ae59-45c3-b197-6cb28bd71f27">

### Acceptance Criteria

Three possible directions: 

1. **Sharp**: Align rounded corners to Calcite's existing sharp corner style
2. **Elevated Rounded**: Add 4px corner radius to Notice and Time Picker to match other elevated components
3. **Rounded**: Align all component corners to the 4px corner radius for a consistent style

Specs available at this [Figma link ](https://www.figma.com/file/nSYVDcjpssA6p0zXM3Imh3/Corner-Radius-Pattern-Audit?type=design&node-id=514%3A113721&mode=dev)

### Which Component

This proposal would affect currently rounded corners on the following components: 

Date Picker (sharp corners are already included in Epic #6721)
Alert
Modal
Dropdown
Action Pad
Tooltip
Popover

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
While, I understand the logic of rounding corners on elevated components, I do not consider it necessary and am leaning towards proposal 1, where we are more intentional about a cohesive sharp corner approach. Alternatively, I am not inherently opposed to proposal 3 with 4px corners because that, too, is a visually consistent style. This direction, however, would obviously require more conversation as it is quite a significant brand change. 

cc @ashetland @macandcheese

**Comment by SkyeSeitz** [comment]
@ashetland @macandcheese After further discussion, thoughts on closing this issue out if the only action item left is to consider removing Button's rounded prop in favor of a CSS var?

**Comment by ashetland** [comment]
If that's all that's left, then yeah, okay with closing.

**Comment by geospatialem** [comment]
Closing per https://github.com/Esri/calcite-design-system/issues/7322#issuecomment-1712033927 and https://github.com/Esri/calcite-design-system/issues/7322#issuecomment-1712044764. cc @SkyeSeitz and @ashetland
