### ISSUE TITLE
[Enhancement] Add optional property to modify Calcite Combobox treatment of commas

### ISSUE THREAD

**Issue by solowt** [Esri/calcite-design-system#7332]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add a property to the combobox to specify whether commas should be treated as delimiters or part of the user input (currently default behavior). If commas are treated as delimiters, the user's input string should be split based on the commas.

Similar enhancement request: https://github.com/Esri/calcite-design-system/issues/4672

### Acceptance Criteria

When the requested property is enabled, a user who enters a string like `tag1, tag2, tag3` should end up with three different combobox items rather than a single one.

### Relevant Info

Before pressing enter:

![Screenshot from 2023-07-18 15-02-44](https://github.com/Esri/calcite-design-system/assets/10148145/07d7fb5d-47d4-4d93-85ad-e66945b9b462)

After pressing enter currently:

![Screenshot from 2023-07-18 15-05-59](https://github.com/Esri/calcite-design-system/assets/10148145/d068c27d-932f-4698-a021-92cea143a0c7)

After pressing enter with the new property set:

![Screenshot from 2023-07-18 15-04-12](https://github.com/Esri/calcite-design-system/assets/10148145/258d4ca2-55e3-4156-adce-fdf52d29b7ba)

### Which Component

Combobox

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Mission

**Comment by geospatialem** [comment]
Example use case: `Washington, D.C.`

**Comment by jcfranco** [comment]
@solowt Would immediately committing a value on `,` (https://github.com/Esri/calcite-design-system/issues/4672) help achieve this or is there a difference in what this issue proposes (e.g., split all commas-delimited values on `Enter`)?

**Comment by solowt** [comment]
Immediately committing a value on `,` would work too. Also, our preference would be that this behavior is configurable.

**Comment by jcfranco** [comment]
> Also, our preference would be that this behavior is configurable

Just to confirm, are you referring to the behavior of committing on `Enter` vs `,`? If so, this might have to go through design first.

**Comment by solowt** [comment]
Just the `,`.

**Comment by jcfranco** [comment]
[Belated] Closing in favor of #4672, based on ☝️.
