### ISSUE TITLE
Click event not registered for interactive elements inside the tooltip of focused element

### ISSUE THREAD

**Issue by minhiu** [Esri/calcite-design-system#7343]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

I have a `calcite-action` element, which has a button inside its tooltip.
If I click (focus) on this `calcite-action` element, the button won't be assigned the click event.

![Screen Shot 2023-07-19 at 10 45 56 AM](https://github.com/Esri/calcite-design-system/assets/26468092/55abd475-4ef3-458c-894e-29d04d72bfae)

### Expected Behavior

The button should be assigned a click event, regardless of the `calcite-element` is being focused or not.

### Reproduction Sample

https://codepen.io/minhiu/pen/LYXrEEG?editors=1000

### Reproduction Steps

See the sample

### Reproduction Version

1.4.3

### Priority impact

p4 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Business/Community Analyst

**Comment by cont-kolomeets** [comment]
Here is a demo of how the Button inside the tooltip fails to be clicked.

![sort](https://github.com/Esri/calcite-design-system/assets/5318527/2a0c910c-ee38-4337-b370-890531ae7ceb)

**Comment by jcfranco** [comment]
This is the remaining part of #5318 (see https://github.com/Esri/calcite-design-system/pull/6732#issuecomment-1515120105). I had forgotten to create a follow-up issue, so thanks for reporting this!

@cont-kolomeets Do you also share the same priority/impact from the description?

**Comment by cont-kolomeets** [comment]
@jcfranco 
> Do you also share the same priority/impact from the description?

Actually, I would up the priority a bit to make it nice to have for the upcoming release (1.5 or at least 1.6).

**Comment by driskull** [comment]
I don't think placing actionable elements inside a tooltip should be supported. For this, a popover should be used instead.

**Comment by driskull** [comment]
@geospatialem can we enhance the doc to say that content within tooltips should not be interactive

**Comment by jcfranco** [comment]
> I don't think placing actionable elements inside a tooltip should be supported. For this, a popover should be used instead.

Great catch. We'll still have to address the remaining part of #5318 in order to support https://github.com/Esri/calcite-design-system/issues/6298, which would make it easier for anyone using tooltip for this to switch over.

> @jcfranco should we prevent pointer events on content within tooltips?

Not at this time. There's some functionality missing in popover that would break anyone currently slotting interactive content in tooltip. Can you create an issue to revisit this later?

**Comment by jcfranco** [comment]
I just realized that this has nothing to do with disabled components as I originally thought. 😅 Bright side is that it makes makes this less complex for sure.

**Comment by driskull** [comment]
Yeah I was wondering why we were talking about disabled components :D

**Comment by geospatialem** [comment]
Documentation update context provided on `tooltip`, which is installed and anticipated for tomorrow's documentation release.

**Comment by geospatialem** [comment]
Verified on the [developer site](https://developers.arcgis.com/calcite-design-system/components/tooltip/)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/c4464173-8499-4d6c-bf4d-8c5d16ab3902)
