### ISSUE TITLE
[Docs] Misc issues

### ISSUE THREAD

**Issue by maxxxxxdlp** [Esri/calcite-design-system#7350]
### Description

I went through all Calcite documentation pages and found several issues. Reporting them here. If you prefer I open a separate GitHub issue for each, I can do so.

- [x] https://developers.arcgis.com/calcite-design-system/tutorials/create-a-mapping-app/#dynamically-resize-the-view
    The code sample uses 45px - should be 49px (as in previous code sample, as in codepen, as in actual default action bar size)
- [ ] https://developers.arcgis.com/calcite-design-system/core-concepts/#component-on-ready:~:text=callback%20of%20requestAnimationFrame%20ensures
    The documentation makes it sound that `requestAnimationFrame` is mandatory for the code to work - I don't think it's needed, but I might be confused. Can you please clarify why it's needed or link to an article with more information?
- [ ] https://developers.arcgis.com/calcite-design-system/tutorials/apply-core-concepts/#add-the-results-list:~:text=function%20resultClickHandler(result%2C%20index)%20%7B
    This code appears to be needlessly complex - the `result` argument of `resultClickHandler` is always going to be same value as `popup` variable, isn't it? if so, the function can be simplified quite a bit.
- [ ] https://developers.arcgis.com/calcite-design-system/tutorials/filter-recent-earthquakes/#display-the-earthquakes
     I wasn't familiar with the `document.createRange()` api - consider adding a docs link or clarifying
- [x] https://developers.arcgis.com/calcite-design-system/components/action/#:~:text=Panel-,Pick%20List,-Value%20List
    Mentions deprecated `PickList` component - should use `List` instead
- [ ] https://developers.arcgis.com/calcite-design-system/tutorials/create-a-mapping-app/#:~:text=Solution-,View%20in%20CodePen,-Estimated%20time
    On every page that as "View in CodePen" link, the element is rendered as a `<button type="submit">`, not a `<a href="...">`, thus right click doesn't work and accessibility semantics is wrong
- [ ] https://developers.arcgis.com/calcite-design-system/icons/?library=Point%20Symbols&version=2.1.7
     When switching between icon libraries (`Calcite UI` / `Meridian` / `Point Symbols`), it should scroll me to the top of the webpage
- [ ] https://developers.arcgis.com/calcite-design-system/components/input/
     The "Input with Input Message" variant should probably be the last one in the list as it's the most complicated and utilizes things introduced in previous variants
- [ ] Why does both `<calcite-input>` and `<calcite-input-number>` exist? and others for other types? which one should be used when? the docs don't explain this
- [x] https://developers.arcgis.com/calcit-design-system/components/rating/
     The "Rating with Label" example variant includes "show-chip" prop, but not "average" or "count", thus chip is not visible, and so `show-chip` prop is ignored

     Similarly, the "Rating - read-only in card" example variant includes "average" and "count", but not "show-chip", thus chip is not visible, and `average`/`count` props are ignored

- [ ] The icons on the docs sidebar and in the header break some of the time - sometimes happens when switching pages, but not always (could be because of cache). I am on Chrome 114 (latest version at the moment), on macOS 13.4.1 (the latest allowed by Esri) - system language and browser language is US English
    ![Screenshot 2023-07-14 at 10 38 26](https://github.com/Esri/calcite-design-system/assets/40512816/4430e4eb-7e00-4316-8e26-82291b316697)
- [ ] `Card` and `Tip` components are somewhat similar - consider either merging them together or clarifying in the docs which should be used when.

### Which Component

Several. See above links

**Comment by geospatialem** [comment]
The above completed issues have been addressed. Closing the remaining items in favor of internal documentation issues opened in Calcite and the Developer repos.
