### ISSUE TITLE
[Enhancement] Use `part` html attribute to make styling easier

### ISSUE THREAD

**Issue by maxxxxxdlp** [Esri/calcite-design-system#7353]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A `part` html attribute exists to allow developers using web components to style elements in shadow DOM.

Calcite does not appear to be using it at all at the moment.

### Acceptance Criteria

`part` and `exportparts` html attributes are utilized generously in Calcite web components to make styling easier

Alternatively, add more css variables and props to give more control of web component internals

### Relevant Info

Stencil docs:
- https://stenciljs.com/docs/styling#css-parts

MDN docs:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/part
- https://developer.mozilla.org/en-US/docs/Web/CSS/::part
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts

### Which Component

I need this in `<calcite-action>` and `<calcite-slider>` at the moment, but theoretically in all components

### Example Use Case

I am using `<calcite-action>` and `<calcite-slider>` inside of `<calcite-action-group>`.

- I need to add border radius for the 4 edge buttons of the d-pad and the slider (can't simply add border radius to `<calcite-action-group>` as that will cut off the focus outline)
- I wish to add a style like this to only have focus outline when using keyboard:
   ```css
   button:focus:not(:focus-visible) {
     outline: none !important;
   }
   ```
- I need to disable the margin on the slider div container.
- The `calcite-action > button` has padding-inline and padding-block values that don't match:
  
   ![Screenshot 2023-07-20 at 16 09 22](https://github.com/Esri/calcite-design-system/assets/40512816/24f95380-a988-48fb-8b7d-24107b681441)

  As a result, when I put actions in a 3x3 grid, the grid is shaped like a rectangle rather than a square

At the moment, I solve these issues by injecting my styles into the web component by creating a `<style>` tag inside of it using JavaScript, but that solution is hacky and fragile:

![Screenshot 2023-07-20 at 15 55 35](https://github.com/Esri/calcite-design-system/assets/40512816/32253deb-bdf6-4d2f-95d7-aae107de8e76)

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by macandcheese** [comment]
Following up from Teams - At this point we aren't planning to add css parts. We've discussed it as something to re-evaluate in the future, but for now we plan to use css variables to expose intended theming. 

That said - our upcoming work to introduce design tokens should make overriding things like box-shadow, border-radius, etc., much easier with system or component level theming. This effort can be tracked here: https://github.com/Esri/calcite-design-system/issues/7180

The Action Pad should be able to achieve that layout in the meantime: https://codepen.io/mac_and_cheese/pen/mdQzRXo?editors=1000
