### ISSUE TITLE
[All Inputs, Inline Editable, Text Area] Add validation styling for consistency

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7355]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add validation for consistency across the design system to the `input` and `inline-editable` components

For `inline-editable` consider Inputs to confirm how they impact and if further validation support is needed on the component.

### Acceptance Criteria
- [ ] Add Label* update to **required** prop
- [ ] Add an **invalid** or status prop
    - triggers:
        - required  
        - leverage native input invalid messages for types
- [ ] Deprecate the `status` prop in favor of an `invalid` pop as they might not be needed for an `"idle"` or `"valid"` status
- [ ] Update invalid styling to a 2px bottom border, for instance:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/7963fc50-d1d0-4900-8389-591394bd6574)

#### Additional context from Figma:
![image](https://github.com/Esri/calcite-design-system/assets/5023024/ce7f785f-c023-49c5-ad8c-02f194101c3e)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/c2dcf9ca-7442-434d-a369-f2d58338cd7f)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a83afd7b-25d6-42a3-82c3-7e20be9bf925)

See the [Figma file](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=956-94284&mode=design&t=tPqHJcVdxmJmZ6L2-0) for development implementation.

### Relevant Info

https://github.com/Esri/calcite-design-system/issues/4598

### Which Component

`input`, `inline-editable`

### Example Use Case

Validation

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Related: https://github.com/Esri/calcite-design-system/issues/7413

**Comment by ashetland** [comment]
Updated the title of this issue to make it clear this issue applies to all input/form components.

**Comment by brittneytewks** [comment]
Removed Figma changes label as this will be tracked in monday.com

**Comment by geospatialem** [comment]
Focus is scoped to `input` and `text-area`, with `inline-editable` if time allows - applies to the styling when the component is `"invalid"`.

**Comment by ashetland** [comment]
Design is cancelling this style change request.
