### ISSUE TITLE
[Input Date Picker] In Firefox and Safari, numbering-system="latn" should change numbers in date header for "ar" to "latn" numbers

### ISSUE THREAD

**Issue by annierm18** [Esri/calcite-design-system#7383]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The numbers in the date header (e.g. 7/26/2023) and the value in the input appear in "arab" numbers.

### Expected Behavior

The numbers should appear in "latn" numbers. This is so that the component can be consistent with the default behavior for lang="ar" in Edge and Chrome.

### Reproduction Sample

https://codepen.io/ainermfc/pen/XWyxRWw?editors=100

### Reproduction Steps

1. Open the input time picker in Firefox or Safari
2. Set the dir to rtl (not necessary)
3. Set lang="ar"
4. Set numbering-system="latn"

### Reproduction Version

1.4.3

### Relevant Info

Calcite history related to this issue can be found in the comments of https://github.com/Esri/calcite-design-system/issues/3079, e.g https://github.com/Esri/calcite-design-system/issues/3079#issuecomment-1168964195 

This is the part in the Calcite code which handles the browser default discrepancy: 
https://github.com/Esri/calcite-design-system/blob/8dcfbd1a2e23d7fe73c11ff64913c7c95e6a3a9f/packages/calcite-components/src/utils/locale.ts#L139-L142

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Urban

**Comment by DitwanP** [comment]
🍬 Verified locally on `main`
