### ISSUE TITLE
[Menu/Menu Item] Doubling up borders when last nested Menu Item is a dropdown

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#7386]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When the last `menu-item` in a nested `menu-item` is itself a dropdown, two borders double up with the last `menu-item` open, as seen below:

<img width="269" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/6521830c-d88a-424e-83f2-2d9764d0ff01">

### Expected Behavior

I would expect one border to be present- the longest border associated with the top parent `menu-item`

### Reproduction Sample

https://codepen.io/skyeseitz/pen/eYQPoOG

### Reproduction Steps

1. Open **Vegetables** Menu Item
2. Open **Peppers** Menu Item
3. Double border is below **Habanero**

### Reproduction Version

v1.4.3

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.28`.
