### ISSUE TITLE
[Flow] Back button tooltip is aligned incorrectly when used inside popover

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-design-system#7391]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When you put a flow inside a popover and launch it from a shell. The back button tooltip for the flow's header will not be aligned correctly. I've seen different alignments but none of them point at the actual back action.

### Expected Behavior

The tooltip should point at the back button

### Reproduction Sample

https://codepen.io/paulcp/pen/wvQQqgM?editors=1000

### Reproduction Steps

1. Click open popover
2. Hover over the back button inside the popover
3. Observe the alignment

### Reproduction Version

1.4.3

### Relevant Info

Looks like this broke between beta.98 and beta.99. If I had to guess I'd say probably related to this pr https://github.com/Esri/calcite-design-system/pull/5688/files

### Regression?

v1.0.0-beta.98

### Priority impact

p4 - not time sensitive

### Impact

This is a minor layout bug, but does make the tooltip look broken. Strictly visual but a nice to fix.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
This has been mitigated using a native tooltip in `1.5.1`. While the tooltip doesn't point to the back button it is situated near the button like so:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/e15ba904-57ec-4c21-a0f3-2d3b2b11600f)
