### ISSUE TITLE
color-picker: Arrow Keys on Alpha channel is changing hue value. 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7394]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When opacity slider is focused , using arrow keys to move the thumb is changing the hue slider rather than the opacity slider.

### Expected Behavior

When focused, using arrow keys on opacity slider should change the opacity value.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/GRwPWGK?editors=100

### Reproduction Steps

1. Navigate to the opacity slider thumb in the code-pen sample.
2. Make sure opacity slider thumb is focused.
3. Use any of the arrow keys to move the thumb.
4. Observe the hue slider change in value.

### Reproduction Version

1.4.3

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.30` 🎨
