### ISSUE TITLE
Modal sometimes emits `beforeClose` and `close` events out of order

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#7395]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If a modal is closed almost immediately after opening it, the modal's `calciteModalClose` event is emitted before its `calciteModalBeforeClose` event.

### Expected Behavior

The modal's `calciteModalClose` event is always emitted after its `calciteModalBeforeClose` event.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/RwqqXXP

### Reproduction Steps

1. Visit the code sample and open the console.
2. See the `"close"` message is logged before the `"before-close"` message.

### Reproduction Version

1.4.3

### Relevant Info

Chrome 115, macOS 13.5.

The repro is contrived, but mimics a real scenario with modals in an automated testing environment.

Specifically, the modal's `.close` button is observed to emit a `transitionend` event during the window in which the modal's open/close behavior is listening for transition events. The modal misinterprets the close button's bubbling `transitionend` event as the modal's own `transitionend` event and, as a result, emits its `calciteModalClose` event prematurely.

This screenshot shows some debugging output when opening/closing a modal. The expanded event outlined in red is the close button's offending `transitionend` event:
![Screenshot 2023-07-30 at 3 56 05 PM copy](https://github.com/Esri/calcite-design-system/assets/421496/7747ff0f-d4b5-4b96-9eb2-f08ab84f35fc)

A suggestion is for the modal's listeners to ignore bubbling transition events.

### Priority impact

p3 - want for upcoming milestone

### Impact

This issue leads to hard-to-debug automated test failures which can necessitate complex workarounds.

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Field Apps

**Comment by jcfranco** [comment]
@nwhittaker Thanks for reporting this. 

It looks like `onToggleOpenCloseComponent` needs to check the event's target, similar to the logic used by `connectOpenCloseComponent`. cc @Elijbet

**Comment by jcfranco** [comment]
This should be fixed by https://github.com/Esri/calcite-design-system/pull/7258.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.28`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/fe19ab3b-553f-4d7e-916c-e2a436d78409)
