### ISSUE TITLE
Tooltip emitting too many open/close events

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7396]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Multiple events are emitted before open/close, and on open/close.

### Expected Behavior

A single event is emitted before open/close, and on open/close.

### Reproduction Sample

https://codepen.io/jcfranco/pen/PoxXjWe?editors=1000

### Reproduction Steps

Hover over the link to display the tooltip, then hover out to have the tooltip hide.

Note there's more than 1 open/close event emitted when this happens.

### Reproduction Version

next (1.5.0)

### Regression?

1.4.3

### Priority impact

p1 - need for current milestone

### Impact

This will cause tooltip's open/close event handlers to be invoked multiple times vs the expected 1.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `next` with 4 events. ✔️
