### ISSUE TITLE
Scrim not updating loader scale on resize

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7420]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Scrim is not updating its internal loader scale based on its size.

### Expected Behavior

Internal loader scale changing according to scrim's size at runtime.

### Reproduction Sample

https://codepen.io/jcfranco/pen/eYQxmPG?editors=1000

### Reproduction Steps

There are 2 loaders set up in the test case.

The left one is updating the scrim's size dynamically and the other one takes the available space.

Notice how loader remains the same size.

For the dynamic one, you can change the initial scale on the scrim to see the expected loader scale.

### Reproduction Version

1.4.3

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.33`.
