### ISSUE TITLE
Panel: When content is not defined or temporarily hidden, thicker borders occur

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7423]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When the content of a panel is temporarily collapsed, a double border is seen because both the footer and heading have a border.

### Expected Behavior

Ideally, if the content is not displayed, the border for the heading or action-bar is not shown.

### Reproduction Sample

https://codepen.io/driskull/pen/QWJYvRm

### Reproduction Steps

1. Open the codepen
2. See how there is a thick border when the content is not displayed
3. This is because both the footer and the heading or action bar have a border

### Reproduction Version

1.4.3

### Relevant Info

N/A

### Priority impact

p4 - not time sensitive

### Impact

Need to be able to collapse a panel and not have the border shown

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.33`.
