### ISSUE TITLE
Chip/Chip Group selection icon padding

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7425]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When in `selection-mode="single" | "single-persist"`, there are a few errors in padding around the selection icon. 

### Expected Behavior

See this [Figma file](https://www.figma.com/design/HB1Ollf1D1Csy2PtXJ3Hai/Chip-selection-affordance-%26-padding?node-id=501-15580&m=dev) for the correct padding.

### Reproduction Sample

https://codepen.io/ashetland/pen/zYMLqyd?editors=1000

### Reproduction Steps

1. Open the codepen
2. Note padding around the selection icon

### Reproduction Version

1.4.3

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
Here's the design spec for this one https://www.figma.com/design/HB1Ollf1D1Csy2PtXJ3Hai/Chip-selection-affordance-%26-padding?node-id=501-15580&m=dev

**Comment by Elijbet** [comment]
Closing, as this was address with [feat(chip): enhance multi-select group affordance](https://github.com/Esri/calcite-design-system/pull/9286#top) #9286.

**Comment by Elijbet** [comment]
Closing, as this was address with [feat(chip): enhance multi-select group affordance](https://github.com/Esri/calcite-design-system/pull/9286#top) #9286.

**Comment by Elijbet** [comment]
Closing, as this was address with https://github.com/Esri/calcite-design-system/pull/9286#top https://github.com/Esri/calcite-design-system/pull/9286.
