### ISSUE TITLE
[calcite-flow-item] set tooltip to open bottom by default

### ISSUE THREAD

**Issue by lboyd93** [Esri/calcite-design-system#7433]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The back button on the flow item component has a tooltip that opens above by default. We would like to request the tooltip to open below by default so that we can avoid this issue in the Map Viewer and the JS Maps SDK.

![flow-item-back-tooltip](https://github.com/Esri/calcite-design-system/assets/22916889/bfb4f400-fc35-48b3-9956-b55b75c84ec4)

cc @driskull 

### Acceptance Criteria

Setting the back button's tooltip to show below by default.

### Which Component

[Calcite Flow Item](https://next.sites.afd.arcgis.com/calcite-design-system/components/flow-item/)

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `1.5.1-next.1`, where the placement will be below the mouse cursor. Context is provided to AT users, but will not be present via keyboard keys.

![verify-title-bottom-default](https://github.com/Esri/calcite-design-system/assets/5023024/55b892a2-ea9e-4f97-8942-0d65919fe0b0)
