### ISSUE TITLE
flow-item back button tooltip at wrong location initially

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#7436]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

![image](https://user-images.githubusercontent.com/44481292/215876929-ed5b2c4b-0ca9-4aeb-a6eb-0be267e93ace.png)

After creating a second flow-item the focus moves to the back button and the tooltip initially displays at the top left corner.

leftover from https://github.com/Esri/calcite-design-system/issues/6400

### Expected Behavior

tooltip is always next to the back button

### Reproduction Sample

https://codepen.io/afreitag/pen/rNQRNzE

### Reproduction Steps

open Codepen
Click on blue button and watch top left corner.

### Reproduction Version

1.5.0-next.36

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified in `1.5.1-next.1` with the updated native tooltip.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/391d6d73-f8cb-466f-a27c-36e6c0605f19)
