### ISSUE TITLE
`calcite-accordion-item` that is not direct child of `calcite-accordion` does not expand when clicked

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-design-system#7448]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using the `calcite-accordion-item` standalone or with a shadow boundary between it and the parent `calcite-accordion`, it does not expand on click.

> use case is we have a component that uses shadow dom wrapping each accordion item, so they need to look up the accordion parent with a closestAcrossShadowDOM Looks like they are just assuming the parent element will be an accordion and that is not the case.

### Expected Behavior

It should expand when clicked

### Reproduction Sample

https://codepen.io/eborgen/pen/eYQXReo?editors=1000

### Reproduction Steps

1. Try to expand the accordion item and see that it does not

### Reproduction Version

1.5.0

### Regression?

Yes - 1.4.3

### Priority impact

p0 - emergency

### Impact

This is preventing the item browser from working correctly pending a refactor of the dom structure. Its okay to accomodate in a breaking change release, but there is no immediate way to support this + older calcite versions.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by ethanbdev** [comment]
cc: @paulcpederson

**Comment by jcfranco** [comment]
@ethanbdev Can you confirm that the repro case up to date? Earlier versions show the same behavior. Went as far back as 1.0.3.

**Comment by ethanbdev** [comment]
> @ethanbdev Can you confirm that the repro case up to date? Earlier versions show the same behavior. Went as far back as 1.0.3.

Yes, I think the problem is actually the shadow boundary between them, let me work on that

**Comment by ethanbdev** [comment]
@jcfranco repro case updated

**Comment by jcfranco** [comment]
Thanks. It looks like the regression was introduced by https://github.com/Esri/calcite-design-system/commit/2b09abacf4f265866f44f210a8c83b580e865fdf. cc @Elijbet

**Comment by geospatialem** [comment]
Verified in `1.5.1-next.3`.
