### ISSUE TITLE
Input Time Zone offsets don't change scale

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7457]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When setting the scale to small or large on Input Time Zone, the offsets in the dropdown stay at medium scale.

### Expected Behavior

The offsets in the dropdown should match the scale of the parent.

### Reproduction Sample

https://codepen.io/ashetland/pen/eYQXGEy?editors=1000

### Reproduction Steps

1. Open the codepen
2. Open each dropdown

### Reproduction Version

1.5

### Relevant Info

cc @jcfranco 

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
@ashetland I'm not able to see the issue in the latest release (see https://codepen.io/jcfranco/pen/VwqjVNZ?editors=1000). Can you confirm?

**Comment by jcfranco** [comment]
Looks like it got fixed by https://github.com/Esri/calcite-design-system/commit/f8a1b91ec9cc39d61a03ee2c9d65e1849b8938fd. Thanks, @Elijbet! 🎉😀

Closing!
