### ISSUE TITLE
list: Drag handle is unavailable for non english locale. 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7460]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When `dragEnabled` boolean is set to `true` in `calcite-list` and `lang` is set to a locale  other than english (ex: sr, tr, th etc)  drag handles are not visible.

### Expected Behavior

drag handles should be visible when `dragEnabled` is `true` irrespective of the locale 

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/ZEmPaOm?editors=1001

### Reproduction Steps

1. Open the codepen
2. Observe the difference between `lang='de'` and `lang='en'`

### Reproduction Version

1.5.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.5.1-next.2`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/fafe6ab7-336d-479b-b9e4-a9e9b7e8b10a)
