### ISSUE TITLE
calcite-combobox: set height of list

### ISSUE THREAD

**Issue by itsminj** [Esri/calcite-design-system#7469]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Allow for height to be set in combobox list, as when there are too many items to show in the list then the list can be cut off

### Acceptance Criteria

When a height is set on the combobox and the combobox is clicked, then the list that is shown should abide to that height

### Which Component

calcite-combobox

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Web Analysis

**Comment by itsminj** [comment]
Here is an image to further clarify the issue:
<img width="799" alt="Screenshot 2023-08-07 at 1 09 55 PM" src="https://github.com/Esri/calcite-design-system/assets/110480375/561e929c-0887-4106-a7d6-4355fedb1a8d">

**Comment by jcfranco** [comment]
@itsminj Have you tried using the [`maxItems`](https://developers.arcgis.com/calcite-design-system/components/combobox/#api-reference-properties-maxItems) prop? This should help you cap the items displayed when open.

**Comment by itsminj** [comment]
That works. Thank you. Closing
