### ISSUE TITLE
Input clearable not rendering in CC React

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7475]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `input` isn't loading when using `clearable` and ` value` of undefined.
![image](https://github.com/Esri/calcite-design-system/assets/5023024/a2cf5164-8de4-4b5f-b451-5c71fc669326)

### Expected Behavior

![image](https://github.com/Esri/calcite-design-system/assets/5023024/91a8ef00-a34a-4810-a4ee-2765136b0cdb)

### Reproduction Sample

https://codesandbox.io/s/input-clearable-error-1-5-forked-ykqyq8?file=/src/App.js

### Reproduction Steps

1. Open the [sample](https://codesandbox.io/s/input-clearable-error-1-5-forked-ykqyq8?file=/src/App.js)
2. Observe the error message
3. Open the [1.4.0 sample](https://codesandbox.io/s/input-clearable-error-1-5-forked-mqmfn5?file=/src/App.js)
4. Observe no error message

### Reproduction Version

1.5.0

### Relevant Info

[1.5.0](https://codesandbox.io/s/input-clearable-error-1-5-forked-ykqyq8?file=/src/App.js) and [1.4.3](https://codesandbox.io/s/input-clearable-error-1-5-forked-mqmfn5?file=/src/App.js) examples

### Regression?

1.4.3

### Priority impact

p1 - need for current milestone

### Impact

Error messages. In the doc site, prevents the component from loading altogether. cc @macandcheese 

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
Workaround is setting `""` instead of `undefined`...

**Comment by driskull** [comment]
Installed a fix. There could be a refactor that handles more use cases so we may want to keep this issue open for another milestone.

**Comment by geospatialem** [comment]
[Verified by Ben in the PR](https://github.com/Esri/calcite-design-system/pull/7476#issuecomment-1668653884)

**Comment by geospatialem** [comment]
Reopening if we want to include more use cases mentioned by [Matt above](https://github.com/Esri/calcite-design-system/issues/7475#issuecomment-1668673075).

**Comment by jcfranco** [comment]
Closing. The pending refactor [suggested in the PR](https://github.com/Esri/calcite-design-system/pull/7476) would simply make value handling more robust.
