### ISSUE TITLE
Enhancement: add `footer-content` slot for custom footer and a property for `footer` layout

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#7478]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A panel slot for custom footer content; and a property to control the layout of the footer.

### Acceptance Criteria

Unlike the `header-content` slot, which simply slots the element and its classes/styles, the `footer` slot does not allow for custom content by slotting all `footer` slotted elements in a shadow dom element constrained by its styling. The name change from `footer-actions` to `footer` seems like just a name change despite the `footer` description of "A slot for adding custom content to the footer.", the behavior is the same.

A `footer-content` slot would allow for truly custom content with the overflow/scrolling content benefits of the `footer` slot by slotting it like `header-content`.

But don't get rid of `footer`.

The behavior of the `footer` slotted elements as-is is very useful for a single button or two buttons ("ok"/"cancel" workflows), being the most common use.

![image](https://github.com/Esri/calcite-design-system/assets/14297903/c203d4e2-b030-4666-ae4f-a8d1d96166fb)

![image](https://github.com/Esri/calcite-design-system/assets/14297903/b31860c7-0d8a-49a2-80aa-75dfac1d3f7a)

But there are situations when there are more than two buttons, which lead to other workflows, are best best displayed vertically.

![image](https://github.com/Esri/calcite-design-system/assets/14297903/bfa58a25-065f-4c81-8460-8154a8abe9a7)

^ a "pseudo" footer by styling without the overflow/scrolling content benefits.

Add a property like `footerLayout` with `horizontal` (default) and `vertical` values. Vertical adding flex direction `column` and an appropriate `gap` style.

I don't see where both `footer-content` and `footer` would both be used. But if they where, `footer-content` would be above 'footer` without a border separator between the two.

### Which Component

panel

### Example Use Case

As shown above for footer layout.

The flexibility of having custom footer content for notices or controls related to actions taken in panel content, especially on mobile devices, would be useful.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by SkyeSeitz** [comment]
Thanks, @COV-GIS for the details! We can consider providing the appropriate gap style according to scale, though, however stacking content in the current footer slot should already be possible by adding a div and setting any style needed on the div.

**Comment by DitwanP** [comment]
It seems like the functionality should be achievable with what Skye suggested above. https://codepen.io/Ditwan-Price/pen/PovgvoB

Please let me know if this still doesn't cover the use cases that you need. @COV-GIS

**Comment by COV-GIS** [comment]
That works @DitwanP and confirmed: https://codepen.io/COV-GIS/pen/OJYYmMw?editors=1000

There must have been some change to the shadow styles since I opened this. At that time there were large left/right "padding gaps" on either side of the footer slot contents with these same styles.

Thanks.
