### ISSUE TITLE
[Panel] No longer has border under header

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7489]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Panel no longer has a border under a header:
<img width="1049" alt="Screenshot 2023-08-08 at 1 25 32 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/ae530966-1699-49c1-8e8f-3473917ecebf">

### Expected Behavior

I'd expect / want Panel to still have a border under header:
<img width="1107" alt="Screenshot 2023-08-08 at 1 25 27 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/e7d3deca-d734-4685-bb9c-f15a17ff9a7a">

### Reproduction Sample

Below

### Reproduction Steps

Compare the two Codepen:
1.4.3 - border: https://codepen.io/mac_and_cheese/pen/qBQweyr?editors=1000
1.5.1 - no border: https://codepen.io/mac_and_cheese/pen/GRwLVGd?editors=1000

### Reproduction Version

1.5.1

### Regression?

1.4.3

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.6.0-next.3`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/7b0a10b7-7c58-4e48-bd38-fa3166930eac)
