### ISSUE TITLE
[Chip Group] TypeError caused by unfound element

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7490]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Running into some error using Chip Group / Chip in React environment with programmatically populated Chips...

![Screenshot 2023-08-08 at 10 45 44 AM](https://github.com/Esri/calcite-design-system/assets/4733155/b8f1a301-b317-4d22-92f2-e4fd269d30a9)
![Screenshot 2023-08-08 at 10 33 17 AM](https://github.com/Esri/calcite-design-system/assets/4733155/b3c2e3dd-2253-4c43-8130-b8ca73bf0a1f)

### Expected Behavior

I'd expect no error

### Reproduction Sample

-

### Reproduction Steps

-

### Reproduction Version

1.5.1

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
#7487

**Comment by geospatialem** [comment]
Verified in `main`.
