### ISSUE TITLE
Enable read-only prop for Navigation Logo

### ISSUE THREAD

**Issue by apfister** [Esri/calcite-design-system#7495]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

I'd like to have the Navigation Logo component provide a `readOnly` property. When enabled, the component is used only for displaying the Title and/or subtitle and invites no user interaction.

### Acceptance Criteria

having a prop on the component may be easiest?

### Which Component

Navigation Logo https://developers.arcgis.com/calcite-design-system/components/navigation-logo/

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

N/A

**Comment by macandcheese** [comment]
In Input, `readOnly` results in a focusable component, but right now the content in a Navigation Logo can't be reached via focus if `href` is not populated.

The result of this issue: https://github.com/Esri/calcite-design-system/issues/7078 will be to always have the element focusable, currently it has a hover effect but cannot be focused when `href` not populated.

As a result, all Navigation Logo instances with href or without will be focusable. But I think it still needs to be focusable to support AT. cc @geospatialem to confirm or ... disconfirm the above. If its the latter, we could look at a `nonInteractive` property or something similar.

**Comment by geospatialem** [comment]
> As a result, all Navigation Logo instances with href or without will be focusable. But I think it still needs to be focusable to support AT.

Concur with @macandcheese's summary above, the component should always be focusable for AT support to provide context to more users.

However, we have plans to address conditions on `navigation-logo` depending on the presence of `href` as Adam mentioned above via #7078.

Closing the above as its not a pattern Calcite supports at this time for a11y support and web patterns with navigation.
