### ISSUE TITLE
Make Actions in horizontal ActionBar fill space.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#7496]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

When ActionBar is `layout="horizontal` AND in a flex container such as Panel, the ActionBar fills the space, and the Actions keep their content-based widths.

<img width="630" alt="image" src="https://github.com/Esri/calcite-design-system/assets/12503298/b892d7b5-86f7-4d24-bd81-154bd45256a6">

Propose adding `flex: 1 0 auto` to Action when in ActionBar and ActionPad to let Action fill the space. OR possibly just setting that style on Action.
<img width="636" alt="image" src="https://github.com/Esri/calcite-design-system/assets/12503298/4529217d-93f7-4778-b807-918c2a5c406e">

Please see [this codepen](https://codepen.io/mtb-alan/pen/JjeqOZq?editors=1100) to see how it affects the different layouts.

### Acceptance Criteria

Make Actions in horizontal ActionBar and ActionPad look better.

### Which Component

Action or ActionBar and ActionPad

### Example Use Case

Toolbar in a panel.
See the above codepen.

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by asangma** [comment]
Note: this might be considered a bug?

**Comment by macandcheese** [comment]
I think we'd want to enable this only when Action Bar layout is grid (after we add it). I don't think this would always be desirable.

**Comment by macandcheese** [comment]
I think we'd want to enable this only when Action Bar layout is grid (after we add it https://github.com/Esri/calcite-design-system/issues/7438). It may require the columns on group to be set in some way.

But I don't think it's a bug or needed by default when in horizontal. I don't think this would always be desirable - for example in horizontal action bar in a shell panel's bottom / top panel slot - or in in this example I think the current fixed width Action is a better design than if they were to all fill available space: https://codepen.io/mac_and_cheese/pen/JjeqpjN?editors=1000

**Comment by asangma** [comment]
Thanks @macandcheese. That totes makes sense.
Do you think it's a prop we could add to either ActionBar/Pad or Action?

**Comment by macandcheese** [comment]
Yeah - it's possible now with Action Pad: https://codepen.io/mac_and_cheese/pen/QWJRQGW?editors=1000

But it has a requirement of using an Action Group and setting columns to an appropriate amount. I do wonder if columns could accept an "auto" or "all" value to avoid needing to know?

In - Dropdown, we require the Dropdown Item to be in a Dropdown Group, where certain properties are set / expected. Not sure if we want to enforce that here.

**Comment by ashetland** [comment]
Should this just be what the grid layout does? I've always found it confusing that the "grid" can look un-grid-like:

**This**
<img width="313" alt="CleanShot 2023-08-09 at 11 35 11@2x" src="https://github.com/Esri/calcite-design-system/assets/108549080/8ed22596-fee4-40eb-9189-8798dbd40aa3">


**vs this**
<img width="349" alt="CleanShot 2023-08-09 at 11 31 13@2x" src="https://github.com/Esri/calcite-design-system/assets/108549080/b5a581f3-2b10-404d-b0e8-d07d19d72647">

**Comment by macandcheese** [comment]
That is how grid works currently - https://codepen.io/mac_and_cheese/pen/QWJRQGW?editors=1000

Just need to add it to Bar, I think. The Collapse really is pretty useless in those cases though, at least IMO. I almost wonder if Action Bar / Pad should have expanded off by default vs. having to disable it, since for most horizontal use cases it's not ... always at least ... necessary with tooltip on action, etc.

**Comment by driskull** [comment]
@asangma @macandcheese this was brought up from the Maps SDK team that they felt like the actions here should take up the full space and its weird the "...more" isn't all the way to the right.

<img width="416" alt="image" src="https://github.com/Esri/calcite-design-system/assets/1231455/ff68f760-94c0-4fab-8981-50d050aa6c36">

**Comment by macandcheese** [comment]
Agreed, I think it's a good option for some cases. As long as .. not doing it.. remains possible.

**Comment by driskull** [comment]
> That said, in that example, I'd expect More and Zoom out to be "docked" to the right and not flex to fill space,

I can make zoom out docked to the right. That might help the appearance a bit.

**Comment by asangma** [comment]
That makes sense. Like render "internal" actions in their own group?

**Comment by driskull** [comment]
yeah maybe. I think ill hold off for now though

**Comment by geospatialem** [comment]
Reconsolidating the effort in #7438 for later this year. Closing the above.
