### ISSUE TITLE
Support panel collapsing

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7498]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add the ability to collapse a `calcite-panel`.

Some use cases for the panel call for the ability to collapse the content of the panel with a button in the header.

For example:

![Aug-09-2023 10-58-19](https://github.com/Esri/calcite-design-system/assets/1231455/8511f2b4-3239-4424-b695-c0cf2ad6a563)

### Acceptance Criteria

This would be done by adding a `collapsable` property as well as a `collapsed` property.

### Relevant Info

https://github.com/Esri/calcite-design-system/pull/7491

### Which Component

calcite-panel

### Example Use Case

```html
<calcite-panel collapsable collapsed heading="My Panel">Hello World!</calcite-panel>
```

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment]
One question I had is if the collapse button should always be farthest to the left or next to the close button?

**Comment by macandcheese** [comment]
I'd think we would want to place it alongside other component-rendered content, but cc @SkyeSeitz @ashetland @asangma

**Comment by SkyeSeitz** [comment]
In a [similar conversation on Block](https://github.com/Esri/calcite-design-system/issues/4935#issuecomment-1570629475), we discussed the chevron being placed adjacent to the heading at all times and not at the extent. This would also allow for the close-button to remain at the end which should be consistent.

**Comment by SkyeSeitz** [comment]
Summarizing a few thoughts that consider this pattern across Block, Panel, and Accordion:
While placing collapse at the start of `actions-end` nicely "book-ends" the expand/collapse hitbox on Block, Panel's hitbox is only tied to the collapse button itself, so it is preferable to have it fall at the end of Panel when `closable="false"` and is consistent with Accordion's end chevron. 

<img width="1705" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/dcb45a5e-7756-4781-b9e7-3c76d5df050e">

[Link to Figma file](https://www.figma.com/file/Q8vlRa7HxlpLplR1onYD6a/Support-panel-collapsing-%5B7498%5D?type=design&node-id=105%3A6589&mode=dev)

cc @asangma for any additional thoughts.

**Comment by driskull** [comment]
@asangma if you're ok with having the collapse next to the close button should I update the popup to do that?

**Comment by asangma** [comment]
I think if the heading container were to be the hit-area for expand/collapse, we'd want to have the heading and expand/collapse icon all be contained in the same button.

If expand/collapse is its own distinct hit area that the component renders, it makes sense to have it be next to the other actions that Panel renders, i.e. the close button.

**Comment by driskull** [comment]
Yeah that makes sense. So should it be its own distinct area or not?

**Comment by asangma** [comment]
Ergonomically, having the heading container be the button aligns with Accordion and Block, no?

**Comment by macandcheese** [comment]
Yes, both of those are intended to be wholly clickable - Not sure if we want to change Panel to match. Tree, for example could have a separate hit area for collapsing as well, so not sure it’s a need to match Block / Accordion here…

**Comment by driskull** [comment]
I'm ok with the whole title being clickable or just the action. Either way seems fine to me.

**Comment by macandcheese** [comment]
I think because Panel have a possibility of having some really wide width in some cases, such as in a bottom / top action bar, making it a smaller, Action-sized area rendered next to the close (when provided) is the best option here. Sound good @asangma @SkyeSeitz @ashetland ?

**Comment by ashetland** [comment]
> I think because Panel have a possibility of having some really wide width in some cases, such as in a bottom / top action bar, making it a smaller, Action-sized area rendered next to the close (when provided) is the best option here. Sound good @asangma @SkyeSeitz @ashetland ?

Agreed

**Comment by driskull** [comment]
@asangma one thing you brought up from the Popup work is that the icons should be reversed if the panel expands up vs down. We would need to achieve this from some kind of property since the panel itself doesn't know anything about the direction its expanding.

Is this worth doing via a prop?

If we do this for panel, the same argument could be made for doing it to accordion or block. You can see an example of an accordion opening up here: https://codepen.io/driskull/pen/PoXEBMZ?editors=1000



![Sep-21-2023 08-50-00](https://github.com/Esri/calcite-design-system/assets/1231455/76c6899a-7262-45c7-a43d-d2f38e2c21bb)

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.12` with `panel` and `flow-item` with https://codepen.io/geospatialem/pen/rNoKdag with the `collapse-direction`, `collapsed`, and `collapsible` attributes.
