### ISSUE TITLE
[Tabs / Tab Nav / Tab Title] When used outside Tabs, selected prop and style not correctly applied to Tab Title

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7512]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Currently, when using Tab Nav outside the Tabs component - the active underline bar accurately moves, but the component does not receive the `selected` property or related styles: 

![Screenshot 2023-08-11 at 2 59 49 PM](https://github.com/Esri/calcite-design-system/assets/4733155/7ca4b21d-5132-4ad2-8224-2c4640cbe614)

### Expected Behavior

When using Tab Nav outside the Tabs component [as documented](https://developers.arcgis.com/calcite-design-system/components/tab-nav/), have the `selected` prop accurately update.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/XWyLYmm?editors=1000

### Reproduction Steps

1. visit Codepen
2. change both tabs
3. Notice the property not applied to the first Tab Nav

### Reproduction Version

1.4.3

### Relevant Info

If we do say Tabs is required to wrap a Tab Nav, maybe we can not render the border or any padding / margin when no Tab component are provided. I do think the Tab Nav on its own is valid, for example if slotted somewhere it is impractical to use adjacent div, and an app uses the Tab Nav events to show / hide their own content. 

Related - https://github.com/Esri/calcite-design-system/issues/2721

cc @mitc7862 

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Consider as part of refactor to the related  (_also mentioned above_) https://github.com/Esri/calcite-design-system/issues/2721

**Comment by geospatialem** [comment]
Spike to confirm if `tab-nav` can be used independently. If not, should consider closing this and update the documentation page with additional context/workflow patterns for folks.

**Comment by jcfranco** [comment]
It looks like standalone `tab-nav` worked prior to v1, but since then, there doesn't seem to be any documentation or examples about standalone usage (the closest thing I found was this [demo page update](https://github.com/Esri/calcite-design-system/pull/713/files) and original [basic usage file](https://github.com/Esri/calcite-design-system/pull/2306/files#diff-d28043e35e50a04c3997b910deb025d7993fb4921bcf1de2a8aa032c4f1fae16)). From that perspective, the component is behaving as expected, but I agree with @macandcheese's point about `tab-nav` potentially being useful by itself for some use cases. @macandcheese could you share more info on your use case and the priority/impact?

**Comment by macandcheese** [comment]
I don’t have one for anything I’m working on, but it was a supported case that stopped working. 

I’m fine to just not support this if no one else reported it - as it hasn’t worked in a long time - especially if this coincides with a larger component refactor to Tab component / Tab Group.

**Comment by jcfranco** [comment]
> I don’t have one for anything I’m working on, but it was a supported case that stopped working.

Yeah, this use case was a bit inconspicuous before we went out of beta. Unless any of the existing props are related to this behavior (I _think_ they're unrelated), I'd like to propose either backlogging or closing until we get more requests for this use case. cc @geospatialem

**Comment by macandcheese** [comment]
Agreed - Menu should be able to solve for use cases where this was implemented. I'd suggest closing and folks can open new issues if needed.

**Comment by geospatialem** [comment]
Closing per https://github.com/Esri/calcite-design-system/issues/7512#issuecomment-1877588286 and https://github.com/Esri/calcite-design-system/issues/7512#issuecomment-1877591558.

If the use case comes up in the future we can explore alternative methods, or to Adam's point above, potentially could be solved using `menu`.
