### ISSUE TITLE
[Shell Panel] Add `displayMode` value that matches `Shell Center Row: detached` display

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7513]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As part of the story to deprecate Shell Center Row - we need to add a `displayMode` to Shell Panel with additional capability - to have the entire Shell Panel "float" away from the page border.

### Acceptance Criteria

A new `displayMode` is added to Shell Panel. Propose to call this mode "float", and change the current "float" to "float-detach" to more clearly convey the difference. Open to naming ideas.

Current Shell Center Row:
![Screenshot 2023-08-11 at 3 26 49 PM](https://github.com/Esri/calcite-design-system/assets/4733155/56da101a-e2bb-41bb-a8c7-e9b82fa276c4)

Proposed in Shell Panel:

![Screenshot 2023-08-11 at 3 33 05 PM](https://github.com/Esri/calcite-design-system/assets/4733155/5a0c4d43-e61d-48ab-a7f1-45435ce36225)

Note - there are some margin differences we can work on here - also, this requires the user to set their "layout" in the Shell Panel to "vertical" and adjust width, maybe that can be smoothed. Potentially - there could be more "position" properties than start / end and it could be "top / bottom / start / end". We could use the Shell Panel's slot to set which css var are being used instead of "layout". But, that's a bit tangential.

### Relevant Info

This would allow us to deprecate Shell Center Row as this is the last remaining functionality not offered by Shell Panel. Currently, this would have the same oddities "float" does without `content-behind` set on a parent Shell, but they can be improved together in the future.

Maybe we could consider renaming "overlay" to "dock-overlay" to match the thing-modifier format?

cc @asangma @mitc7862 

### Which Component

Shell Panel

### Example Use Case

As a designer - I want to have a Panel + Action Bar within a Shell Panel "float" above the map without having the Action Bar attached to the edge of the container. Currently, I can't achieve this with built in styles in Shell Panel, but I could with Shell Center Row.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
cc @brittneytewks @geospatialem - prioritizing this for next available milestone could help us deprecate Shell Center Row in the following release.

**Comment by SkyeSeitz** [comment]
Figma specs are available here: https://www.figma.com/file/AnRJbFQ31ZK04NkP22ylLU/Shell-Panel%3A-displayMode-%5B7513%5D?type=design&node-id=310%3A9795&mode=dev

Tagging in @jcfranco for comments on changing the current `float` value name to `float-detach`. This would be a breaking change, but would allow the new proposed displayMode to be called `float` and provide further accuracy to the names. 

_**Related consideration Adam brought up:**  the position of the action bar is currently set using the `position` prop on Shell Panel, which we may want to update to `action-bar-position` for clarity._

**Comment by josercarcamo** [comment]
In terms of naming, how about "content-detach" and leave "float", but with this different meaning?

**Comment by josercarcamo** [comment]
Yeah, another naming suggestion would be "content-detach" and leave "float" but with the new behavior.

**Comment by SkyeSeitz** [comment]
"content-detached" might add a bit more clarity 👍🏽

**Comment by josercarcamo** [comment]
@SkyeSeitz @driskull @jcfranco this is what I have so far. Please advise on how to proceed regarding the height of the action bar.

![image](https://github.com/Esri/calcite-design-system/assets/138070439/ce91b6b5-6d11-441a-96ed-aeadbbbe05be)

**Comment by jcfranco** [comment]
> Please advise on how to proceed regarding the height of the action bar.

@josercarcamo It's not clear to me from the screenshot, but could you provide more info on the action-bar height blocker?

**Comment by driskull** [comment]
> A new displayMode is added to Shell Panel. Propose to call this mode "float", and change the current "float" to "float-detach" to more clearly convey the difference. Open to naming ideas.

@macandcheese this is a bit confusing because it would introduce breaking changes if `float` started behaving differently.

**Comment by macandcheese** [comment]
Yeah, open to other naming ideas there.

**Comment by geospatialem** [comment]
The team will instead pursue a `"float-all"` and `"float-content"`, deprecating `"float"` to avoid a breaking change. cc @macandcheese @SkyeSeitz @josercarcamo
