### ISSUE TITLE
Option for Scrim to be placed inside parent div, not over the entire screen

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-design-system#7515]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The current behavior of the Calcite Scrim is to scrim the entire page, but it would be nice if there was an option so that it would instead scrim 100% of the width and height of the parent container instead.  This would make it more versatile.  For example, the Studio team would like to use the scrim to cover only the main content zone containing a new map view when content is open, rather than the entire UI.

### Acceptance Criteria

Scrim has option to only fill its parent container rather than the whole page.

### Which Component

Calcite Scrim

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Knowledge

**Comment by macandcheese** [comment]
It should behave like that now, is there a repro case where it is taking up the whole page?

https://codepen.io/mac_and_cheese/pen/mdQNOGj?editors=100

**Comment by macandcheese** [comment]
Ah - ok it needs to be in a parent with `position: relative` https://codesandbox.io/s/nice-ardinghelli-2g63t3?file=/src/App.js - should work there.

**Comment by RSantosGIS** [comment]
ah ok, got it, thanks!

**Comment by RSantosGIS** [comment]
After making the change, it looks like it's working great.  I've closed the issue, though perhaps I would consider adding this to the documentation / sample

**Comment by macandcheese** [comment]
Ah, it needs to be inside a parent with postion:relative.

**Comment by macandcheese** [comment]
Re-opening to add note in documentation about needing a parent with postion:relative 

cc @geospatialem

**Comment by geospatialem** [comment]
Added context to the "Overview" section and a sample, which went live and is available on the [documentation site](https://developers.arcgis.com/calcite-design-system/components/scrim/).

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a16c254e-6232-42dd-b43b-264f03db3ff9)
