### ISSUE TITLE
Calcite Block header-menu-actions popover style/direction control

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-design-system#7516]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

I would like to have the same options for positioning the Block header-menu-actions overflow popover/dropdown menu that I do for the Calcite Dropdown
- overlay positioning, to allow me to overflow the parent container
- placement (with extended options), to allow me to position it in the start/end of the left/right/top/bottom

You can see how this doesn't feel great below:

Collapsed Behavior:
![image](https://github.com/Esri/calcite-design-system/assets/36513418/93108cb6-9764-4c6c-90db-ab99127dda49)

Expanded Behavior:
![image](https://github.com/Esri/calcite-design-system/assets/36513418/7cb190d7-7c03-4aa3-89b5-dd29d53dbf89)

Desired Behavior (achieved with a Calcite list item under the block using a dropdown, since our sublayers don't need to be expanded further):
![image](https://github.com/Esri/calcite-design-system/assets/36513418/67ac4dec-9630-4ba4-a1a8-001265bc086f)

### Acceptance Criteria

Block header-menu-actions has same placement options as dropdown

### Which Component

Calcite Block

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Knowledge

**Comment by jcfranco** [comment]
Thanks for submitting this. 

Could you clarify which component you're using in your screenshots? Block doesn't have a menu.

**Comment by RSantosGIS** [comment]
Just Calcite Block with Calcite actions that are in the blocks header-menu-actions slot:

![image](https://github.com/Esri/calcite-design-system/assets/36513418/f1d46e76-79c5-4172-938f-00520a9cea06)

**Comment by geospatialem** [comment]
Spike needed to determine which components should accommodate placement, such as `block`, `panel`, `action-group`, etc.

**Comment by driskull** [comment]
Seems like we should just add `placement` and `flipPlacements` properties to all three of these components.

**Comment by DitwanP** [comment]
🍭 Verified locally on `dev`

One example below, `menuPlacement`: bottom & `menuFlipPlacements`: ["left"]

https://github.com/user-attachments/assets/1d5c0db4-5bc0-4d59-b64a-f43b4dabdbe1
