### ISSUE TITLE
Calcite-select returns option's text value when the option's attribute is empty

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-design-system#7519]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calcite-select returns the value of the option's text (the value between the option tags) if the option's value attribute is empty.

### Expected Behavior

Calcite-select should be returning an empty value of string if the option's value attribute is empty

### Reproduction Sample

https://codepen.io/arjan_esrinl/pen/ZEmgaVv

### Reproduction Steps

1. Open DevTools
2. Select in both select elements the 'Lakes' option
3. CalciteSelect will return the text value 'Lakes'. The native select returns an empty string

### Reproduction Version

1.5.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Professional Services - Services Delivery

**Comment by jcfranco** [comment]
For anyone else facing this, as a workaround, you could introduce a "no value" value and normalize it when handling the event: https://codepen.io/jcfranco/pen/oNQKdEg?editors=1111

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/4032, which is targeted for the September milestone.
