### ISSUE TITLE
Change CI and branching strategy to support multiple release targets in preparation of v2

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#7526]
### Summary

Right now our release CI is set up to release `next` when there are deploy-able pushes to `main`. Meanwhile,`release-please` maintains a `latest` release PR that gets automatically updated on pushes to `main`. When we are ready for a latest release, we install the `release-please` PR.

This has been working nicely. However, we will still need to support v1 after we release v2, so we will need to have multiple release branches. We will also be creating release candidates (`rc`) in preparation of v2, which will be separate from the existing `next` releases.

We could use [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), but it minimizes the value `release-please` provides of having a constantly updating PR that we can check on.

Here is my suggestion:

In preparation of v2, I think we should create an `rc` branch, which is where we will install breaking changes. Our release CI targeting `main` can stay as is for additional v1 releases. This way we don't have to wait until the last minute to install and test breaking changes. We could start right away while continuing with our existing v1 setup.

We can merge or cherry-pick commits from `main` to `rc` on an ongoing basis (even automatically) or be more strategic about it when we are ready to deploy a release candidate.

When we are ready for our v2 release, we create a new `legacy` branch off of `main` and then merge the `rc` branch into `main` (IMPORTANT: we would need to make sure not to squash merge it so we don't loose the `rc` branch's breaking change commit history).

`release-please` will update its PR with the breaking changes, and we can release v2 once everything looks good.

After we release v2, we will be left with a `main` branch and a `legacy` branch. We can then cherry-pick commits from `main` onto `legacy` as needed for v1 patches.

### Desired Outcome

- A new branching workflow that allows us to deploy from multiple branches
- Additional scripts/actions/automation for release candidates and eventually releases for the previous major version

### Resources

cc @jcfranco @geospatialem @alisonailea for your thoughts/ideas

**Comment by geospatialem** [comment]
Verified in the repo, with the `main` and `rc` branches and scripting.
