### ISSUE TITLE
Input Time Zone: can't retrieve appropriate offset value or message after deselecting dropdown option

### ISSUE THREAD

**Issue by ian13262** [Esri/calcite-design-system#7530]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Deselecting the currently selected time zone from the `calcite-input-time-zone` dropdown causes an `offsetValue` error in Dev Tools Console and an inability to retrieve the offset value.

### Expected Behavior

When no time zone is selected, `offsetValue` should have some appropriate value or string indicating as such so that we can appropriately handle setting time zones.

### Reproduction Sample

https://codepen.io/iyouth66/pen/PoXYZJG

### Reproduction Steps

1.) Open Codepen > Open the `calcite-input-time-zone` dropdown
2.) Deselect the currently selected time zone
3.) Open Dev Tools > Console
4.) An `offsetValue` error is displayed

### Reproduction Version

1.5

### Relevant Info

cc @jcfranco

### Regression?

N/A

### Priority impact

p3 - want for upcoming milestone

### Impact

We need the `offsetValue` when setting time zones in Map Viewer (or eventually the corresponding representative IANA string - see #7430). When all options are deselected, this needs to be indicated somehow as well.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Online

**Comment by jcfranco** [comment]
**Implementer's note**: this should now be feasible via combobox's new [`single-persist` mode](https://github.com/Esri/calcite-design-system/pull/7583).

**Comment by geospatialem** [comment]
Verified in `1.8.0`.
