### ISSUE TITLE
Time Picker: Clicking nudge value buttons should focus the corresponding input

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#7533]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Clicking `time-picker`'s up/down nudge buttons don't gain their own focus, but should probably focus the input the buttons are affecting the value of.

### Acceptance Criteria

Clicking the up or down buttons in `time-picker` for any of the editable values should focus the corresponding input.

### Which Component

`time-picker`

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified with `1.8.0-next.0`

![verify-7533](https://github.com/Esri/calcite-design-system/assets/5023024/cb9bc82d-51a0-42f2-a6ae-4eee4265ca84)
