### ISSUE TITLE
[Action Bar] Deprecated "bottom-actions" slot doesn't work

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7534]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

We recently added "actions-end" slot to Action Bar, and deprecated "bottom-actions". But when using "bottom-actions" - the component does not render slot contents.

### Expected Behavior

I'd expect the deprecated slot to still render.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/VwqZjbB?editors=1000

### Reproduction Steps

1. Go to Codepen
2. View "bottom-actions" slot in HTML
3. Change to "actions-end"
4. See slotted contents appear

### Reproduction Version

1.6.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `1.6.1-next.2` with the `"bottom-actions"` and `"actions-end"` slots.
