### ISSUE TITLE
Tooltip: add `interactive` property to enable/disable hover persistence

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#7536]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add boolean `interactive` property to enable/disable tooltip hover persistence; closing the tooltip as soon at the target is no longer hovered without a delay when disabled.

### Acceptance Criteria

As stated.

### Which Component

tooltip

### Example Use Case

The current behavior is problematic with list items containing actions with tooltips and other situations where components with tooltips are grouped together. If the hover state switches from the target to the tooltip, it persists and blocks other actionable elements the user moved to. Placement isn't always an effective work around on account of blocking another action. I noticed this behavior before in some edge cases with action bar action tooltips and adjacent panel content. But isn't as detrimental to usability.

![image](https://github.com/Esri/calcite-design-system/assets/14297903/332defb1-f8c9-48ab-8f8e-309194a30624)

A related issue. Clicking on an action slotted tooltip fires any click events wired to the target as would be expected of a descendent. However, if the user crosses an action triggering the tooltip which covers the action the user actually wants to click and happens to "catch" the tooltip when clicking the wrong action is taken.

I looked at a few tooltip libs/components and websites, including github and google products to investigate tooltip implementations. There seems to be a mix of implementation with non-persistence being more common. Tooltips with persistence are non-blocking or have interactive content. tippy.js has the optional `interactive` property to essentially making it a popover. Since there is a popover component and the tooltip docs say for concise hints and to use popover for interactive content, I initially thought to suggest removing this behavior all together. However I did see a couple persistent tooltips with dynamic content that a user may wish to select and copy. I can also see where having a tooltip with context and a "Learn more" link or the like might make persistence useful.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by jul11557** [comment]
The ArcGIS Mission product team would also benefit from this enhancement. We switched many of our html title attributes to calcite tooltips to improve a11y, and the tooltips seem to block other actionable elements on the page. We would love if:
* there would be an option to change or disable how long the tooltip persists after user hovers away (as described in this issue), and/or
* the ability to reduce the padding size on the tooltip — they seem a big _larger_ than typical tooltips which might contribute to the issue of them blocking other elements for too long

**Comment by COV-GIS** [comment]
> the ability to reduce the padding size on the tooltip — they seem a big larger than typical tooltips which might contribute to the issue of them blocking other elements for too long

https://github.com/Esri/calcite-design-system/issues/5334

**Comment by macandcheese** [comment]
Another consideration is that hovering over the tooltip itself will persist the tooltip, we've heard feedback this is a bit strange and it might be expected to dismiss after hovering stops on the inoking element.

**Comment by jul11557** [comment]
I never noticed that behavior. Interesting! I also hadn't noticed before that the tooltip content can be copied.

I don't know how much value there is in persisting while hovering over the tooltip, since users will likely be hovering over the action element to read the text. However, if the ability to copy the tooltip text is important, then it seems likely the tooltip would need to persist, to allow the user time to select & copy. 

These behaviors aren't particularly valuable for our product team's use cases, but can't speak for others.

**Comment by driskull** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#accessibility_concerns

> The tooltip must stay open when hovered, even if that technically means the mouse moves out of the owning element. As content which appears on hover can be difficult or impossible to perceive if a user is required to keep their mouse pointer over the trigger, [WCAG 1.4.13](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable#guideline_1.4_make_it_easier_for_users_to_see_and_hear_content_including_separating_foreground_from_background) states that content made visible should be persistent, meaning it should not disappear without user action.

**Comment by geospatialem** [comment]
Calcite follows the [tooltip role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role), in that:

> [The tooltip] must stay open when the mouse moves over the tooltip itself, and should also close when the user presses the
`Escape` key.

However, the component's `placement` attribute may accommodate use cases where multiple actions and tooltips are displayed in an app. For instance: https://codepen.io/geospatialem/pen/pomPeKQ -- also present in the [component sample playground](https://developers.arcgis.com/calcite-design-system/components/tooltip/#sample), where the actions contain tooltips displayed in different locations to accommodate the UI.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/82d24661-122a-4f44-8667-ab91a2b54751)


```html
<calcite-tooltip label="Trails layer" reference-element="trail-1" placement="bottom">
  ...
</calcite-tooltip>
```

The component performs as-expected and the above enhancement request is not in scope of the design system, thus closing the above issue out as unplanned at this time.
