### ISSUE TITLE
List: Support keyboard dragging between different Lists

### ISSUE THREAD

**Issue by Csmith246** [Esri/calcite-design-system#7537]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Be able to use the keyboard to drag between lists. Currently, you can only drag via keyboard within a List. 

### Acceptance Criteria

Grouping multiple lists together, be able to perform drag and drop of different list items with only the keyboard.

In terms of implementation, I'd assume using the left/right arrows when in keyboard drag mode on a List Item would just find the next List in the page (to the left or right) and then move the item to that List, if it exists.

### Relevant Info

Ref to similar issue: https://github.com/Esri/calcite-design-system/issues/7046

### Which Component

Calcite List

### Example Use Case

In Instant Apps, our Position Manager ties 4 Calcite Lists together. The desire is to support keyboard only movement between the lists for accessibility.

![PositionManagerAccessibilityRequest](https://github.com/Esri/calcite-design-system/assets/22039422/f33fd893-464b-4aef-9964-9f8252a42ff0)

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Instant Apps

**Comment by geospatialem** [comment]
Effort should be considered with the effort in https://github.com/Esri/calcite-design-system/issues/7426

**Comment by geospatialem** [comment]
Dependent on the `spike` for https://github.com/Esri/calcite-design-system/issues/9261.

**Comment by driskull** [comment]
@geospatialem I'd like to implement a menu to be able to move items up, down, first, last and between lists.

Something like: https://atlassian.design/components/pragmatic-drag-and-drop/examples/#list

However, to do this, the current space bar key for starting movement would need to change to open a menu.

Would we want to pursue this route in place of the existing functionality of moving with arrow keys?

**Comment by geospatialem** [comment]
> @geospatialem I'd like to implement a menu to be able to move items up, down, first, last and between lists.
> 
> Something like: https://atlassian.design/components/pragmatic-drag-and-drop/examples/#list
> 
> However, to do this, the current space bar key for starting movement would need to change to open a menu.
> 
> Would we want to pursue this route in place of the existing functionality of moving with arrow keys?

@driskull This sounds like a great approach! But would think this would fall into a breaking change, is it something we could hold off on until late 2024?

**Comment by driskull** [comment]
Yes, if we want to move this issue to another milestone.

**Comment by driskull** [comment]
This is going to require a new internal component to handle the dropdown menu.

I can't use `calcite-handle` because it would require a large refactor and `calcite-sortable-list` requires it as is.

**Comment by driskull** [comment]
@geospatialem if we don't want a dropdown menu to move, we could go with a dialog like shown

Dialog design: https://atlassian.design/components/pragmatic-drag-and-drop/examples/#list
Menu design: https://atlassian.design/components/pragmatic-drag-and-drop/examples/#board

@ashetland @SkyeSeitz what are your thoughts?

**Comment by ashetland** [comment]
I think I'm missing the nuance, both those example look the same. I like the gropings in the menu for in-list and between-list
![CleanShot 2024-10-03 at 16 10 42@2x](https://github.com/user-attachments/assets/d4ddeb45-e84d-42da-928e-54321d48ce8d)

**Comment by driskull** [comment]
@ashetland sorry, see the tree example: https://atlassian.design/components/pragmatic-drag-and-drop/examples/#tree

**Comment by ashetland** [comment]
Oh! Thanks, @driskull. I definitely prefer the dropdown menu of the Dialog. It's harder to track context in the state.

**Comment by ashetland** [comment]
What's the issue with the dropdown approach? In the linked examples, [enter], [space], and [down-arrow] all open the menu.

**Comment by driskull** [comment]
> What's the issue with the dropdown approach? In the linked examples, [enter], [space], and [down-arrow] all open the menu.

Nothing, I just wanted to consult some designers to make sure we're taking the right approach.

**Comment by ashetland** [comment]
Awesome. Really like this direction. Also like that click+drag doesn't open the menu, but a simple click does open it.

**Comment by driskull** [comment]
When moving lists, do you think it should move to the top or the bottom of the list? My initial feeling was the bottom but the demos linked move to the top.

**Comment by ashetland** [comment]
I prefer top of the list. This would also match the behavior of Combobox with `allow-custom-values`.

**Comment by ashetland** [comment]
Now that we're using Action for the drag handle, we need to override it's icon color from `text.3` to `border.input` to match our prior implementation. `border.input` is preferred to keep the drag handle less visually prominent while still meeting AA wcag standards.

**Comment by driskull** [comment]
> Now that we're using Action for the drag handle, we need to override it's icon color from text.3 to border.input to match our prior implementation. border.input is preferred to keep the drag handle less visually prominent while still meeting AA wcag standards.

Done

**Comment by geospatialem** [comment]
It looks like where multiple lists are provided with the current implementation the `label` would be required to provide context on where the `list-item` would move to via https://codepen.io/geospatialem/pen/JjgmKVb:

| With `label` | No `label` value |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/ce95a621-6875-4d0c-b4e1-7043b748b416) | ![image](https://github.com/user-attachments/assets/7b5062b1-0151-4251-a033-c38f78adf2c3) |

Wondering what folks think, if we should consider:
1. Require the `label` prop/attr
2. Have a fallback if `label` isn't specified and/or
3. Update the documentation that specifies a `label` property should be accompanied when working with multiple lists

cc  @driskull @jcfranco

**Comment by driskull** [comment]
I lean towards documentation or making label required. I'm not sure what the fallback would be.

**Comment by geospatialem** [comment]
> I lean towards documentation or making label required. I'm not sure what the fallback would be.

We have several other components that have a required `label` prop (`alert`, `card-group`, `carousel-`, `loader`, etc.), maybe we should do the same here?

**Comment by driskull** [comment]
Yeah. I think we can also document that the label is needed for moving between lists.

**Comment by geospatialem** [comment]
@DitwanP For verification see [this comment](https://github.com/Esri/calcite-design-system/issues/7537#issuecomment-2460544077) for a sample to test out. 🧪

**Comment by DitwanP** [comment]
🍡 Verified on `3.0.0-next.7`
