### ISSUE TITLE
Icons disappear while dragging in a nested calcite-list

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-design-system#7540]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

I am using a calcite list with a nested drag enabled list because I only want certain items to be draggable. While dragging an item in this nested list, the drag icons disappear but reappear when I release the item.

### Expected Behavior

I expect the icons to remain visible while dragging.

### Reproduction Sample

https://codepen.io/nid13240/pen/NWEZYdN

### Reproduction Steps

1. open the codepen above
2. try to drag items in the first list
3. observe that the icons disappear while dragging

I've also added a regular non-nested drag enabled list for comparison

### Reproduction Version

1.6.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.9`.
