### ISSUE TITLE
[List / Popover] List Display issues within Popover when filter-enabled

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7545]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using List within Popover and `filter-enabled` is true - some undesired visuals in a few situations:

In all browsers, when the popover is `overlay-positioning: absolute`, undesired placement of the filter bar. Notice some differences across browers:
<img width="1728" alt="positioning absolute all browsers" src="https://github.com/Esri/calcite-design-system/assets/4733155/255f70a9-4fde-40b9-8077-52cd3fac11b2">

In Safari, when the popover is `overlay-positioning: fixed`, undesired placement of the filter bar. Notice that is displays correctly in Chrome, but incorrect in different ways in Desktop vs. Mobile Safari.
<img width="1728" alt="positioning fixed safari issues" src="https://github.com/Esri/calcite-design-system/assets/4733155/ddb7feeb-66e2-4100-ad8f-29bcc7db2a5d">

### Expected Behavior

Correctly positioned filter bar regardless of browser, or parent Popover `overlay-positioning` value.

### Reproduction Sample

See below

### Reproduction Steps

For issues with overlay-positioning="absolute":
https://codepen.io/mac_and_cheese/pen/NWeWqQo?editors=1000

For issues with overlay-positioning="fixed" and Safari: 
https://codepen.io/mac_and_cheese/pen/qBLWKXZ?editors=1000

Open above in various browsers to see behavior.

### Reproduction Version

1.6.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by driskull** [comment]
its because the filter is positioned sticky.  Might be related to https://github.com/Esri/calcite-design-system/issues/5743#issuecomment-1314619243

**Comment by driskull** [comment]
@macandcheese if you add a `overflow:auto` to your content inside the popover then it seems to be fixed. We don't automatically overflow popover content. We could if we decided what heights those would be but currently its left up to the user.

**Comment by driskull** [comment]
https://codepen.io/driskull/pen/xxmxVwv?editors=1000

**Comment by geospatialem** [comment]
Research will be conducted to determine if the Safari issue is a browser bug, or if additional efforts could be tackled.

**Comment by driskull** [comment]
@macandcheese I'm not seeing the safari issue when I use the overflow fix I provided.

**Comment by geospatialem** [comment]
Assigning to @macandcheese per https://github.com/Esri/calcite-design-system/issues/7545#issuecomment-1687037823. ☝🏻

**Comment by macandcheese** [comment]
Closing as seems like this is expected / has workaround for now.
