### ISSUE TITLE
Borders inconsistent when list comprises both grouped and ungrouped list items

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#7546]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Given a list containing a mix of list items and grouped list items:
1. A border _does not_ appear before an item if the previous item is in a group.
2. A border _does_ appear before a group heading if the previous item is not in a group.

<img width="776" alt="Screenshot 2023-08-17 at 4 16 46 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/874eba6f-fe2d-4cac-814d-4bd5f8fed0ec">

### Expected Behavior

I expected borders to behave as they do in non-hybrid lists:
1. A border _always_ appears before an item unless it's the first item.
2. A border _never_ appears before a group heading.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/LYMYpGj

### Reproduction Steps

1. Visit reproduction sample
2. Verify no border appears between the **Waterfalls** and **Rivers** items
3. Verify a border appears before the **Building** group header

### Reproduction Version

1.6.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified on the `main` branch:  
![image](https://github.com/Esri/calcite-design-system/assets/5023024/f9169a11-8c99-4b28-a702-6424a9c47939)

**Comment by nwhittaker** [comment]
@geospatialem, I updated the [repro sample][1] to `1.11.0`. I see the border is gone from above the Buildings header, but I don't see a border between the Waterfalls and Rivers list items. Fair enough if this is the expected design, but I wanted to double-check…

<img width="283" alt="Screenshot 2023-11-27 at 10 27 01 AM" src="https://github.com/Esri/calcite-design-system/assets/421496/6b4c9c2d-1e35-45c2-99e6-c0db2f9937fa">

[1]: https://codepen.io/nwhittaker-esri/pen/LYMYpGj

**Comment by anveshmekala** [comment]
> @geospatialem, I updated the [repro sample](https://codepen.io/nwhittaker-esri/pen/LYMYpGj) to `1.11.0`. I see the border is gone from above the Buildings header, but I don't see a border between the Waterfalls and Rivers list items. Fair enough if this is the expected design, but I wanted to double-check…


Hi @nwhittaker , the border between list-item in  a group and other list-item should be present (In this case Waterfalls and Rivers). This is a bug and will fix it. Thanks for reporting.

**Comment by anveshmekala** [comment]
Hi @nwhittaker , the fix is installed in `1.11.1-next.2`. Could you please verify if it is working as expected? Thank you.

**Comment by nwhittaker** [comment]
>Hi @nwhittaker , the fix is installed in 1.11.1-next.2. Could you please verify if it is working as expected? Thank you.

@anveshmekala, I forked a new [code sample][1] and updated it to `1.11.1-next.2` and it looks good to me, thanks!

[1]: https://codepen.io/nwhittaker-esri/pen/WNPgwpz
