### ISSUE TITLE
Remove any logic where `disabled` affects state across components

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#7547]
### Description

Remove any logic where `disabled` affects state such as `open` across all relevant components. 

Several components set the `open` prop to false in the `open watcher` in a similar fashion:

```
@Watch("open")
  openHandler(): void {
    // emit events

    if (this.disabled) {
      this.open = false;
      return;
    }

    // do something
  }
```

### Proposed Advantages

It’s a good practice to separate concerns and maintain clear distinctions between different states and behaviors across components. 

### Which Component

- [x] `combobox` (`open`)
- [x] `dropdown` (`open`)
- [x] `input-date-picker` (`open`)
- [x] `input-time-picker` (`open`)
- [x] `split-button` (`active` – internal prop)

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

**Comment by geospatialem** [comment]
Spike in June to consider for the upcoming breaking change release and determine next steps if a breaking change is needed.

**Comment by DitwanP** [comment]
🍡 Verified on `3.0.0-next.17`
