### ISSUE TITLE
dropdown: inconsistent focus in safari with pointer and keyboard

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7549]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When user opens the dropdown via keyboard or pointer, the first item in list is not focused. The focus appears sometime and is very inconsistent

### Expected Behavior

When the dropdown is open via pointer or keyboard, the first focusable item in the dropdown list should be focused.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/NWeWNWw?editors=1000

### Reproduction Steps

1. Open the codepen in safari browser.
2. Click on the dropdown button and wait for the dropdown list
3. Observe that first item is not focused.
4. Close the dropdown list and tab into the dropdown button
5. Open the dropdown list by Enter or Space key.
6. Observe that first item in the list is not focused.

### Reproduction Version

1.5.0

### Relevant Info

Safari 16.6

### Regression?

1.4.3

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.6.1-next.2`.
