### ISSUE TITLE
auto-define.js issue prevents Calcite Components React from loading

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-design-system#7575]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Many, if not all, components don't load due to an auto-define.js error log. 
I noticed that also components are mentioned in the error logs that I don't use in my application
![image](https://github.com/Esri/calcite-design-system/assets/25850072/91bde87b-d876-472e-9a7d-6daca285fc10)

### Expected Behavior

The application loads as expected

### Reproduction Sample
https://github.com/arjanvanzutphen/ccr-auto-define-issue

### Reproduction Steps

1. Clone the repo
2. Run `npm install`
3. Run `npm run dev`
4. Open the page. Most likely: http://localhost:5173
5. See errors in Devtools' console

### Reproduction Version

1.6.0. in sample

### Relevant Info

1.6.1 shows the same behavior and is not showing the components as they should

### Regression?

1.5.1

### Priority impact

p3 - want for upcoming milestone

### Impact

The app doesn't get loaded. Version 1.6.0 is in this way unusable

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

Professional Services - Services Delivery

**Comment by geospatialem** [comment]
CodeSandbox can sometimes takes a few days to catch up to the `latest`, but if you open [the template](https://cdn.jsdelivr.net/npm/@esri/calcite-components@latest/dist/calcite/calcite.esm.js) and select the "Upgrade to latest" button in the "Dependencies" it will update to `1.6.1`. 
![image](https://github.com/Esri/calcite-design-system/assets/5023024/e8c699c8-25ca-40a6-8830-cfdc4bec95a4)

Or if its easier to setup a use case, here's [the sample with `1.6.1` setup](https://codesandbox.io/s/vigilant-james-x86ff5). 

@arjanvanzutphen WRT the above, could you add a sample with either the template upgraded to latest, or with the above link?

**Comment by jcfranco** [comment]
Looks like the `isBrowser` check we set up is failing in this case. `window`, `document`, `global` and `process` are available on the browser preview. cc @benelan

**Comment by jcfranco** [comment]
Maybe we can add some additional checks on the `process` object since we can't rely on these not being available because of bundlers. We can also look at using https://www.npmjs.com/package/browser-or-node or beefing up our checks based on that.

**Comment by geospatialem** [comment]
This also surfaced with the Maps SDK for JS team during initialization cc: @andygup.

<img width="875" alt="value-list-error" src="https://github.com/Esri/calcite-design-system/assets/5023024/70b30e6b-f3b0-4f55-84df-023ce9bc2240">

**Comment by andygup** [comment]
Thanks @geospatialem, I was able to repro using:

```
  "dependencies": {
    "@arcgis/core": "^4.27.6",
    "@esri/calcite-components-react": "^1.6.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.3",
    "vite": "^4.4.5"
  }
}
```

**Comment by andygup** [comment]
Here's a repro app: https://devtopia.esri.com/andy4683/arcgis-calcite-vite-react.  It should be using the latest version of all the deps.

Steps:
- `npm i`
- `npm run dev`
- View errors in console

**Comment by arjanvanzutphen** [comment]
Updated the issue with a repro sample with CCR version 1.6.0

**Comment by benelan** [comment]
Apparently vite requires a plugin to handle dynamic imports the way webpack does:
https://www.npmjs.com/package/vite-plugin-dynamic-import

Using the dynamic import plugin with the following vite config resolved the issue for me:

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import dynamicImport from "vite-plugin-dynamic-import";
import { resolve } from "path";

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "@esri/calcite-components": resolve(
        "node_modules",
        "@esri",
        "calcite-components",
      ),
    },
  },
  plugins: [
    react(),
    dynamicImport({
      filter(id) {
        return id.includes("/node_modules/@esri/calcite-components");
      },
    }),
  ],
});
```

Let me know if that doesn't work for anyone. 

For reference, we needed to use a dynamic import to make sure web components aren't defined on the server when using SSR frameworks. I'll switch our [CRA example](https://github.com/Esri/calcite-components-examples/tree/master/react) example that I use for testing to a Vite one since that's the industry standard nowadays.

**Comment by benelan** [comment]
I'll see if I can solve this in the vite config without using that plugin.

> It also looks like tree shaking is not supported with the React output target, which may mean auto-import will import all react wrappers and all stencil components, which is why we are seeing errors from unused modules.

When I was testing with your repro sample I only saw errors for all components in the dev server. When building and serving there was only one error for the component being used in the app.

> To me the auto-import feature feels like a major change with some unknowns, and it may be worth making it opt-in to see the impact on different apps first, and maybe delaying a full re-release until a major / breaking calcite version

I can look into making it opt in, but it would be adding even more magic because we are already patching Stencil's build to get it to work as is. The auto import already went out in 1.5.0 so unfortunately we can't delay it, and removing it would be a breaking change.

**Comment by rslibed** [comment]
This impacts ArcGIS Instant Apps

fyi @kellyhutchins @bcree11 @Csmith246

**Comment by rslibed** [comment]
> Apparently vite requires a plugin to handle dynamic imports the way webpack does: https://www.npmjs.com/package/vite-plugin-dynamic-import
> 
> Using the dynamic import plugin with the following vite config resolved the issue for me:
> 
> ```js
> import { defineConfig } from "vite";
> import react from "@vitejs/plugin-react";
> import dynamicImport from "vite-plugin-dynamic-import";
> import { resolve } from "path";
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   resolve: {
>     alias: {
>       "@esri/calcite-components": resolve(
>         "node_modules",
>         "@esri",
>         "calcite-components",
>       ),
>     },
>   },
>   plugins: [
>     react(),
>     dynamicImport({
>       filter(id) {
>         return id.includes("/node_modules/@esri/calcite-components");
>       },
>     }),
>   ],
> });
> ```
> 
> Let me know if that doesn't work for anyone.
> 
> For reference, we needed to use a dynamic import to make sure web components aren't defined on the server when using SSR frameworks. I'll switch our [CRA example](https://github.com/Esri/calcite-components-examples/tree/master/react) that I use for testing to a Vite one since that's the industry standard nowadays.

@benelan  Tried out the workaround but it doesn't appear to resolve the issue. App is using `@esri/calcite-components@1.7.0`

**Comment by benelan** [comment]
You should no longer need the vite plugin after updating to the 'v1.8.0' release that went out a few hours ago!

**Comment by geospatialem** [comment]
Verified with `1.8.0`

**Comment by arjanvanzutphen** [comment]
Updated CCR to `1.8.0` and works perfectly. Thanks!

**Comment by andygup** [comment]
Verified with JS SDK `4.27.6` and `@arcgis/core@4.28.0-next.20230907`.

**Comment by geospatialem** [comment]
Great to hear, thank you both @arjanvanzutphen and @andygup! 🎉

**Comment by mpayson** [comment]
Working for us too -- for Vite dev server, Vite production builds, and Vitest -- thank you!!
