### ISSUE TITLE
tabs: focuses tabpanel when first element inside panel is focusable element

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7576]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When the user activates the tab, the tabpanel is focusable irrespective of whether the first element in the content is focusable or not.

### Expected Behavior

If the first element in the tabpanel content is focusable then the tabpanel should not be included in the keyboard Tab sequence as per [W3Cspecs](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/#:~:text=Note%20that%20since,is%20not%20focusable.).

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/rNoVOrO?editors=1000

### Reproduction Steps

1. Open the Codepen
2. Activate the second calcite-tab with title `Component2` by clicking or space key (when focused).
3. Tab into the content 
4. Observe that content container is focused
5. Tab again and observe that `calcite-tab` link is focused.

### Reproduction Version

1.6.1

### Priority impact

p4 - not time sensitive

### Impact

This will impact `calcite-color-picker` component

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by Elijbet** [comment]
After some thought, it seems like this issue is not valid. We don't know what the contents of the `tabpanel` are. These elements might not be tabbable. If they aren't we would need to be able to tab into the content.

**Comment by DitwanP** [comment]
Closing due to the point made above. 👆
