### ISSUE TITLE
Tree: descendant tree-items are not selected when parent is selected on initial render in selection-mode='ancestor'

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7577]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a tree-item has selected attribute on initial render the descendant tree-items are not selected 

### Expected Behavior

If  a tree-item has selected attribute any descendant items are expected to be selected.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/GRPJpVX?editors=1000

### Reproduction Steps

1. Open the Codepen
2. Observe `tree-item` with text California has `selected` attribute. 
3. Observe none of the descendants are selected.

### Reproduction Version

1.6.1

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.7.1`, per fix from https://github.com/Esri/calcite-design-system/pull/7572. cc @anveshmekala
