### ISSUE TITLE
Documentation crashes when going from Icons to Components page

### ISSUE THREAD

**Issue by maxxxxxdlp** [Esri/calcite-design-system#7580]
### Description

1. Open this url - https://developers.arcgis.com/calcite-design-system/icons/?library=Calcite%20UI&version=3.23.7
2. Click on "Components" tab
3. Page crashes. React errors shown. Replicated in incognito browser tab

https://github.com/Esri/calcite-design-system/assets/40512816/aa194f8f-da7d-40f6-9673-9c0819bc145e

### Which Component

N/A

### Resources

**Chrome:** Version 115.0.5790.170 (Official Build) (arm64)

**Comment by macandcheese** [comment]
Thanks for the report @maxxxxxdlp - going to close this issue in this repository and open in the documentation site repository.
