### ISSUE TITLE
[Chip Group] TypeError in certain cases when populating in React programmatically 

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7585]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Related https://github.com/Esri/calcite-design-system/issues/7490

### Expected Behavior

No response

### Reproduction Sample

No response

### Reproduction Steps

No response

### Reproduction Version

1.6.1

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `main`.
