### ISSUE TITLE
[Calcite Button] Loading buttons are clickable in Firefox

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#7590]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Similar to https://github.com/Esri/calcite-design-system/issues/7043, buttons in a `loading` state are clickable in Firefox

### Expected Behavior

Since the button visually looks disabled, I'd expect it to have the same behavior as the `disabled` state and not be clickable

### Reproduction Sample

https://codepen.io/mpayson/pen/poqJZpY

### Reproduction Steps

1. Open code pen and devtools in Firefox
2. Click loading button, see console message
3. Click disabled, don't see console message

### Reproduction Version

1.6.1

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Update pattern for consistency across components, such as `block`, and `button` to truly be disabled when loading is enabled. For `panel` could use `block`'s scrim paradigm, where the header isn't covered and actions are available for use.

**Comment by amring1** [comment]
Can we up the priority on this one? It causes issues in analysis where users can submit multiple jobs in quick succession which causes failures.

**Comment by jcfranco** [comment]
This also affects Safari. 

We fixed stacked opacity on `calcite-button` when they are both `disabled` and `loading` in v1.10.0, so as a workaround, you can set both props on the component. https://codepen.io/jcfranco/pen/xxMELeX?editors=1111

**Comment by rebollin** [comment]
Hi there, would also like to up the priority of this bug if possible. This was reported as a release issue when saving in Map Viewer (it allows the user to create multiple maps). The workaround only partially resolved the issue, it works in chrome but not in FF

**Comment by geospatialem** [comment]
For consistency across the design system Calcite will keep the `loading` and `disabled` states as separate. 

In cases where `loading` is present and a `disabled` state is desired, folks can add both attributes, or properties, in to achieve the desired use case where the button in its loading state is disabled, as depicted in [Franco's reply above](https://github.com/Esri/calcite-design-system/issues/7590#issuecomment-1791059087), such as:

```html
<calcite-button id="loading" loading disabled>Add layer</calcite-button>
<script>
document.getElementById("loading").onclick = () => console.log("loading clicked")
</script>
```

Updating this issue to a documentation update to the `button` component page for context.

With the above in mind, @rebollin, please reach out if the above doesn't fit the MV use case as mentioned in your [comment above](https://github.com/Esri/calcite-design-system/issues/7590#issuecomment-1792747087), and we can discuss some additional options together.

**Comment by geospatialem** [comment]
This is both a code and doc update. Updating the milestone to December to tackle the code-portion, which will remove the `disabled` functionality when `loading` is `true`.

For folks interested in the anticipated expected behavior, please refer to https://github.com/Esri/calcite-design-system/issues/7590#issuecomment-1793080341.

cc: @jcfranco

**Comment by jcfranco** [comment]
Installed on `rc`.

**Comment by geospatialem** [comment]
Verified in `v2.0.0-rc.2`, where Calcite is keeping the [loading and disabled states separate](https://github.com/Esri/calcite-design-system/issues/7590#issuecomment-1793080341), for instance:

```html
<!-- This button is loading, but clickable -->
<calcite-button id="loading" loading>Add layer</calcite-button>

<!-- This button is disabled -->
<calcite-button id="disabled" disabled>Add layer</calcite-button>

<!-- This button is loading and disabled -->
<calcite-button id="disabledLoading" loading disabled>Add layer</calcite-button>
```
