### ISSUE TITLE
[CalciteList] Dropdowns at action-end are cut off in Safari if overflow-y: auto is set on the list

### ISSUE THREAD

**Issue by nikki-lea** [Esri/calcite-design-system#7599]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a dropdown is placed in a CalciteList with overflow-y: auto, the DropdownList will be truncated with no way to access the dropdown.

<img width="350" alt="Screenshot 2023-08-24 at 9 39 39 AM" src="https://github.com/Esri/calcite-design-system/assets/61667766/8faf265c-471d-442b-9932-80f9c191d52b">

### Expected Behavior

Expect to see the dropdown display and not be truncated

### Reproduction Sample

https://codesandbox.io/s/peaceful-worker-6clsy5?file=/src/App.js

### Reproduction Steps

1. Open with safari
2. Click the ellipses on the item2 list item
3. Dropdown does not display fully

### Reproduction Version

1.4.2

### Relevant Info

Safari only

### Priority impact

p4 - not time sensitive

### Impact

Release blocking, workaround provided

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Enterprise

**Comment by geospatialem** [comment]
Spike to confirm the use of z-index mentioned in [Franco's comment above](https://github.com/Esri/calcite-design-system/issues/7599#issuecomment-1692175316).

**Comment by driskull** [comment]
@geospatialem @jcfranco it was added in the big list enhancements PR for filtering and treegrid. https://github.com/Esri/calcite-design-system/commit/f489c57095ec21df1f427176d2d635675eea95d3

I think we can remove it. I don't see any reason it is needed.

**Comment by geospatialem** [comment]
@driskull Awesome news! If this seems like a low risk fix, we could add into inclusion for the upcoming maintenance release.

**Comment by driskull** [comment]
Its tough to determine the risk here. Ill defer to @jcfranco.

**Comment by jcfranco** [comment]
If we can confirm there's no visual regression in our test suite, we can consider this low risk since it's removing an unnecessary stacking context that might stir up trouble in similar configurations.

**Comment by driskull** [comment]
Yeah no regressions found in screenshot tests

**Comment by geospatialem** [comment]
Verified in `1.8.0` with https://codepen.io/geospatialem/pen/rNojOxe.
