### ISSUE TITLE
[Input Time Picker / Input Date Picker] Missing strings in translation.json file

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7603]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calcite Input Time Picker and Calcite Input Date Picker both source their t9n messages from two locations:
`@Prop({ mutable: true }) messageOverrides: Partial<InputTimePickerMessages & TimePickerMessages>;`

As a result, only the files imported via assetPath in the component end up in the `translations.json`.

In the case of `input-date-picker` - "dateFormat" only has an en value. It also has ":" colon at the end (this might be expected?)

### Expected Behavior

I'd expect all the strings to be available per component in the translations.json file.

### Reproduction Sample

`translations.json` :

For Input Time Picker - you can see the output below:

```
  "input-date-picker": {
        "chooseDate": {
            "ar": "اختر تاريخ",
            "bg": "Избор на дата",
            "bs": "Odaberite datum",
            "ca": "Trieu una data",
            "cs": "Zvolit datum",
            "da": "Vælg dato",
            "de": "Datum auswählen",
            "el": "Επιλογή ημερομηνίας",
            "en": "Choose date",
            "es": "Elegir fecha",
            "et": "Valige kuupäev",
            "fi": "Valitse päivämäärä",
            "fr": "Choisir la date",
            "he": "בחר תאריך",
            "hr": "Odaberite datum",
            "hu": "Válasszon dátumot",
            "id": "Pilih tanggal",
            "it": "Selezionare la data",
            "ja": "日付の選択",
            "ko": "날짜 선택",
            "lt": "Pasirinkite datą",
            "lv": "Izvēlieties datumu",
            "nl": "Datum kiezen",
            "no": "Velg dato",
            "pl": "Wybierz datę",
            "pt-BR": "Escolher data",
            "pt-PT": "Selecionar data",
            "ro": "Alegeți data",
            "ru": "Выбрать дату",
            "sk": "Vyberte dátum",
            "sl": "Izberi datum",
            "sr": "Odaberite datum",
            "sv": "Välj datum",
            "th": "เลือกวันที่",
            "tr": "Tarih seç",
            "uk": "Вибрати дату",
            "vi": "Chọn ngày",
            "zh-CN": "选择日期",
            "zh-HK": "選擇日期",
            "zh-TW": "選擇日期"
        },
        "dateFormat": {
            "en": "Date Format:"
        }
    },
```

### Reproduction Steps

-

### Reproduction Version

1.6.1

### Relevant Info

Note - the components themselves work fine, this is solely an exported documentation issue.

cc @anveshmekala @benelan 

### Priority impact

p3 - want for upcoming milestone

### Impact

This affects our ability to accurately display the translations in the documentation site for these components.

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
> In the case of input-date-picker - "dateFormat" only has an en value. It also has ":" colon at the end (this might be expected?)

At least in the [latest release](https://unpkg.com/@esri/calcite-components@1.9.2/dist/extras/translations-json.json), `dateFormat` appears to be included in all locales.

> Calcite Input Time Picker and Calcite Input Date Picker both source their t9n messages from two locations:
> @Prop({ mutable: true }) messageOverrides: Partial<InputTimePickerMessages & TimePickerMessages>;

This one is tricky since the translations themselves belong to the individual components, but `messageOverrides` covers both parent and supporting component/child overrides.

> As a result, only the files imported via assetPath in the component end up in the translations.json.

From the perspective of translations-source, `translations-json.json` properly reflects each component's associated message bundle. 

--- 

@macandcheese From the doc-site-perspective, would it be possible to have a way to merge those two message entries by having the parent/child relationship defined somewhere?

**Comment by macandcheese** [comment]
@jcfranco going to close this as the main issue of `dateFormat` only showing up for English has been resolved. I think we can punt on the associations of translation for the other components, or at least leave it for now as that is on the Gatsby side of things.
