### ISSUE TITLE
calcite-text-area font-size property (not scale)

### ISSUE THREAD

**Issue by tom12993** [Esri/calcite-design-system#7606]
### Description

I need to change the font size of the text-area input without changing the scale of the entire component.
Reason: I like the scale of the component set to "s" for the footer, but that makes the input text's font-size too small. I'd like to control those two separately.

### Acceptance Criteria

Styles variable like `--calcite-text-area-font-size` or something similar.

### Which Component

`calcite-text-area`

### Example Use Case

![image](https://github.com/Esri/calcite-design-system/assets/143228559/202eb498-0021-498f-acfd-a1c1629fa93a)
I'd like to avoid doing this:
```js
document.querySelector('calcite-text-area').shadowRoot.innerHTML += 
    `<style>textarea {font-size: 14px !important;}</style>`
```

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Monitor

**Comment by geospatialem** [comment]
Spike to determine the feasibility and consistency across the design system, in terms of the scaling of the component's text.

**Comment by geospatialem** [comment]
Verified with the Chromatic build on 9/23 and the following:

CSS:
```css
#feedback-notes {
  --calcite-text-area-font-size: 30px;
}
```

HTML:
```html
<calcite-text-area id="feedback-notes"></calcite-text-area>
```

![image](https://github.com/user-attachments/assets/a7113bb3-011a-4b03-8d84-0cec723255b1)

**Comment by tom12993** [comment]
Thank you

**Comment by tom12993** [comment]
@geospatialem Actually, the new change does not address my original usecase. I'd like to decouple the font-size of the main body and the footer. Can we add a token for `--calcite-text-area-footer-font-size` in the future?
