### ISSUE TITLE
`calcite-segmented-control` State becomes out-of-sync when adding/removing `calcite-segmented-control-items`.

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-design-system#7626]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When programmatically adding a new `calcite-segmented-control-item` to a `calcite-segmented-control`, the `calcite-segmented-control`'s state can become out-of-sync.

The issue occurs when setting the newly created `calcite-segmented-control-item`'s `checked=true`. The new item will appear checked, but you will not be able to click the previously selected item.

![chrome-capture-2023-7-30](https://github.com/Esri/calcite-design-system/assets/19629809/f62d5721-8b08-4be3-81ae-75a9835e5b94)

### Expected Behavior

When programmatically adding a new `calcite-segmented-control-item` to a `calcite-segmented-control` with `checked=true`, the `calcite-segmented-control` should maintain the correct state.

### Reproduction Sample

https://codepen.io/jmanke/pen/MWZyPZp?editors=1011

### Reproduction Steps

1. Observe 'Control 1' starts checked.
2. Click 'Modify items' to replace the first control ('Control 1') with a new item. The new item will be checked.
3. Try clicking 'Control 1' again. Notice it cannot be clicked.

### Reproduction Version

1.5.1

### Relevant Info

MacOS 13.4.1
Chrome 115.0.5790.170

Related issue: https://github.com/Esri/calcite-design-system/issues/6860

### Priority impact

p3 - want for upcoming milestone

### Impact

Low - We have a workaround in place but it's not ideal (hacky code). To reduce the number of workarounds in our codebase, we would like to see this issue resolved.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Dashboards

**Comment by driskull** [comment]
This one might already be fixed on the `@next` npm release.

**Comment by jmanke** [comment]
Just tried with `@next`, looks like it is! Closing.
