### ISSUE TITLE
calciteListChange event emitted on manual item disable/enable

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-design-system#7627]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When I manually enable/disable list items (by setting the `disabled` property), I notice that the calciteListChange event now gets emitted as of 1.5.0. For my use case, I manually set this property in the calciteListChange event handler which creates an infinite loop.

### Expected Behavior

I do not expect this event to be emitted when I manually change the `disabled` property on a list item. 

### Reproduction Sample

https://codepen.io/nid13240/pen/JjwXaoj?editors=1011

### Reproduction Steps

1. open the codepen above (currently set to calcite version 1.4.3)
2. select the first list item and observe the list items enable/disable as expected
3. change the version to 1.5.0 or later
4. select the first list item and observe the items enabling/disabling infinitely

### Reproduction Version

1.5.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified with `1.7.0-next.17` with the `calciteListChange` event.
