### ISSUE TITLE
[Refactor] Create utility for SelectedItemsAssertionOptions

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7633]
### Description

Create a shared utility for `SelectedItemsAssertionOptions` and related test helpers

### Proposed Advantages

cc @jcfranco 

### Which Component

All

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/9243.

Closing!
