### ISSUE TITLE
List/List Item: Improve drag UX

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7645]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Create designs for implementation for 3 different CSS classes (_see below_) for implementation to improve the `list` and `list-item` drag UX. 

cc: @driskull 

### Acceptance Criteria

Allow for styling 3 different CSS classes:
1. Item selected:  red border in attached image
2. Item being dragged: solid blue border.
3. Item drop area: dashed blue border.

### Relevant Info

**Current behavior**:
![bad](https://github.com/Esri/calcite-design-system/assets/5023024/44d33de1-d50c-4703-9785-2a71d7834828)

### Which Component

`list`, `list-item`

### Example Use Case

Calcite doesn't have different styles for the states above and it can make it difficult to discern where the user is putting the `list-item` being dragged.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by ashetland** [comment]
@macandcheese @SkyeSeitz @jacqueskeet Flagging us on this since what we decide for #2210 can hopefully apply here too.

**Comment by geospatialem** [comment]
Verified with https://codepen.io/geospatialem/pen/Yzdoyzq in `1.10.0-next.0`.

[verify-list-ux-drag](https://github.com/Esri/calcite-design-system/assets/5023024/c350d49b-644b-41b4-90b2-a4f9544b6dfb)
