### ISSUE TITLE
Avatar: css variable to adjust round corner

### ISSUE THREAD

**Issue by yannikmesserli** [Esri/calcite-design-system#7651]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add a css variable to set the border radius of the avatar so that developer can adjust it to their need

### Acceptance Criteria

border radius is settable using css varaible

### Which Component

Calcite Avatar

### Example Use Case

Urban is using the avatar to display user's avatar or initial. We would like to have it square in our search results:
<img width="946" alt="image-2023-07-03-21-05-15-851" src="https://github.com/Esri/calcite-design-system/assets/1910449/9b6a8d1b-9c0c-4998-9ec2-8830d79adf05">

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Urban

**Comment by macandcheese** [comment]
This should be addressed with https://github.com/Esri/calcite-design-system/issues/7180

**Comment by geospatialem** [comment]
This is part of the design token epic mentioned [here](https://github.com/Esri/calcite-design-system/issues/7651#issuecomment-1707346307), will verify once implemented.

**Comment by alisonailea** [comment]
`--calcite-avatar-corner-radius` has been added to #10280

**Comment by DitwanP** [comment]
🍠 Verified locally on `dev` 
![image](https://github.com/user-attachments/assets/c04a0ed5-59f7-4310-9f8f-5296a26228ad)
