### ISSUE TITLE
Custom ESLint rule to disable sorting for `ref` attribute, as it needs to be the last property in JSX to ensure it is up-to-date.

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#7659]
### Description

- This GitHub issue relates to an existing bug in the Stencil library (https://github.com/ionic-team/stencil/issues/4074). The current behavior is that the order of `ref` usage can result in outdated props/attributes when the callback is invoked.

- The expected behavior is for `ref` to be called immediately after the element is fully initialized with all props/attributes, aligning with similar mechanisms in other libraries like React and Preact.  Properties are applied in the order they are specified. If you place the `ref` at the end of the component's properties, it ensures that the component's render and updates are processed before the ref callback is triggered. This means the ref callback will have access to the fully rendered and updated component or DOM element.

- The suggested solution involves setting `ref` as the last property in JSX to ensure that node attributes/properties are up-to-date. However, this requires disabling the `jsx-sort-props` rule specifically for this case using an ESLint comment (`eslint-disable-next-line`) (#6530, #7584).

- The request is to create a custom ESLint rule that catches this pattern instead of relying on manual comments throughout the repository. 

### Proposed Advantages

Provides an automated solution to manual comments to disable sorting rules throughout the repository. 

### Which Component

All. 

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [X] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
Updated labels and verified locally. 🎉

The next step for this rule will be tackled in #8080.
