### ISSUE TITLE
[Modal] Deprecate `docked` property

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7668]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The new Sheet component, in `"block-end"`, provides the same functionality as `docked` Modal. We should deprecate the Modal property.

### Acceptance Criteria

Modal property `docked` deprecated

### Relevant Info

At some point, it might be worth looking at having Modal expect a slotted Panel like Shell Panel and Sheet - or provide all the slots of a Panel to Modal and have it render internally, to keep API and slot the same across all of these. 

### Which Component

Modal, Sheet

### Example Use Case

Reduce the amount of pattern duplication across components.

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Team has discussed a "modal/non-modal" property in the new [`calcite-dialog`](https://github.com/Esri/calcite-design-system/issues/7886) component with a rendered `calcite-panel`. If moving to a modal mode in Dialog, it would account for the need to address the "docked" property in `calcite-modal`.

**Comment by geospatialem** [comment]
Closing the above in favor of https://github.com/Esri/calcite-design-system/issues/7886, where the `dialog` component will be created, and once created and supported `modal` will be deprecated.
