### ISSUE TITLE
Sheet: Close event not triggered with `calciteSheetClose` event

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7681]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`Sheet`'s close event is not being triggered 

### Expected Behavior

`Sheet`s close event is triggered with `calciteSheetClose`.

### Reproduction Sample

https://codepen.io/geospatialem/pen/jOXrXQQ

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/jOXrXQQ)
2. Try to close the `sheet` by selecting the scrim
3. Re-load the sample
4. Try to close the `sheet` by selecting the close button
5. Re-load the sample
6. Lastly, try to close the `sheet` by pressing the `Esc` key

### Reproduction Version

1.7.0

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Related to https://github.com/Esri/calcite-design-system/issues/7655, pertaining to the `sheet` component.

**Comment by geospatialem** [comment]
Looks good when clicking the scrim on the `main` branch. 👍🏻 

@driskull Would we expect the `calciteSheetClose` to fire when the `Escape` key is also pressed?

**Comment by driskull** [comment]
Yes, is it not firing?

**Comment by geospatialem** [comment]
It doesn't seem to on `main` with code taken from https://codepen.io/geospatialem/pen/jOXrXQQ (there are some unstable tests impacting the `next` releases currently).

**Comment by driskull** [comment]
Seems to work fine locally.

**Comment by geospatialem** [comment]
Ah, thanks! Yes, we're good, was a testing issue when the component was opened and not using our [Core concepts](https://developers.arcgis.com/calcite-design-system/core-concepts/#loading-components).

Closing, as we're verified on the `main` branch with the scrim click and `Escape` key. 🎉
