### ISSUE TITLE
Action-group no longer honoring `flex-grow`

### ISSUE THREAD

**Issue by nel11211** [Esri/calcite-design-system#7687]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calcite-action-group` flex-grow is not being honored anymore.

Before:
![image](https://github.com/Esri/calcite-design-system/assets/66378014/a17ebae2-5eef-45db-bddd-3fe72400ab2c)

After:
![image](https://github.com/Esri/calcite-design-system/assets/66378014/7af46c96-24a3-48ac-a876-18d9cbad9b5d)

### Expected Behavior

The "Before" image above is the expected behavior.

### Reproduction Sample

https://codepen.io/nel11211/pen/wvRoZQd

### Reproduction Steps

See codepen for one example of a setup that yields the issue.

### Reproduction Version

1.7.0

### Regression?

1.6.0

### Priority impact

p4 - not time sensitive

### Impact

Low impact since we were able to resolve our issue by switching to using a horizontal `calcite-action-bar` instead of the `calcite-action-group`. But it is a bug with the action-group nonetheless.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Charts

**Comment by driskull** [comment]
@geospatialem can we add this to the current release?

**Comment by jcfranco** [comment]
Added to the upcoming maintenance release.

**Comment by geospatialem** [comment]
Verified in `1.8.0`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/7d189501-17a6-4260-8511-672df444b85e)
