### ISSUE TITLE
Dropdown: selection icon updates

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7688]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

To provide a clearer unselected multi-select state as well as align with updates to other Calcite components, update Dropdown's selection icons as documented in this [Figma file](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---icon-consistency-%5B7181%5D?type=design&node-id=592-63101&mode=dev).

This work was completed as part of epic #7181.

Screenshot for posterity:
<img width="961" alt="CleanShot 2023-09-06 at 11 09 50@2x" src="https://github.com/Esri/calcite-design-system/assets/108549080/d9c2d140-b188-4657-80dc-0c3f9d927aa6">

### Acceptance Criteria

Selection icons and hover states updated to match Figma designs.

### Relevant Info

Calcite Icons v3.24.2 required.

### Which Component

Dropdown

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by brittneytewks** [comment]
Removed Figma changes label as this will be tracked in monday.com
