### ISSUE TITLE
Input Time Picker clears value from popup when unfocusing it with hanidec and thai numbering systems

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#7689]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The popup value gets unexpectedly cleared when trying to close the popup with the zh-HK lang and hanidec numbering system.  This also happens with the thai numbering system.

### Expected Behavior

The time picker popup should always reflect the value that is currently stored in the text input, and the popup should always close when it is unfocused or clicked away from.

### Reproduction Sample

https://codepen.io/eriklharper/pen/rNoWgwX

### Reproduction Steps

1. Open Time Picker Popup
2. Click outside the popup to close it
3. Observe: value in Time Picker popup clears, value still present in the input and the popup persists

### Reproduction Version

v1.7.0

### Relevant Info

Happens consistently on all platforms.

### Regression?

?

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
Closing as `hanidec` and `thai` numbering systems are no longer supported (see https://github.com/Esri/calcite-design-system/issues/8216).
