### ISSUE TITLE
Range enabled `calcite-date-picker` doesn't apply styling accurately when `scale='s'`

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-design-system#7697]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

This is what the range enabled `calcite-date-picker` looks like when `scale='s'`

<img width="230" alt="Screen Shot 2023-09-07 at 9 40 58 AM" src="https://github.com/Esri/calcite-design-system/assets/55154968/47c47b40-9928-4958-8a32-351753eb5e4e">

### Expected Behavior

This is what the range enabled `calcite-date-picker` looks like when `scale='m'`

<img width="297" alt="Screen Shot 2023-09-07 at 9 44 22 AM" src="https://github.com/Esri/calcite-design-system/assets/55154968/2aaa52d7-47c8-41c0-80fa-63f564d00d7a">

### Reproduction Sample

https://codepen.io/joeyHarig/pen/JjwEyGB?editors=1000

### Reproduction Steps

1. Select a range on the small and medium date picker
2. Notice the difference in styling 

### Reproduction Version

1.7.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

ArcGIS Monitor

**Comment by Elijbet** [comment]
Can't seem to reproduce this issue with v2.7.1. The codepen link is broken, if the issue still exists, can we have the codepen reproduction back?

**Comment by geospatialem** [comment]
> Can't seem to reproduce this issue with v2.7.1. The codepen link is broken, if the issue still exists, can we have the codepen reproduction back?

This looks to be mitigated in `2.7.1` with https://codepen.io/geospatialem/pen/vYMVPNE.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/40e6565d-1d57-4549-a220-99e0b96e6dcd)


@joeyHarig - if you are able to reproduce, let us know and we can reopen to investigate.

**Comment by joeyHarig** [comment]
@geospatialem @Elijbet I cannot reproduce in `2.7.1` - thank you for double checking and reaching out
