### ISSUE TITLE
Calcite-block-section does not account for switch space when rendering text

### ISSUE THREAD

**Issue by ian13262** [Esri/calcite-design-system#7698]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When rendering text, `calcite-block-sections` do not account for the space taken up by a switch. Text should wrap on an additional line in this situation.
![image](https://github.com/Esri/calcite-design-system/assets/131201379/fca7963a-c535-43f4-ad77-b7fba2a54735)

![image](https://github.com/Esri/calcite-design-system/assets/44481292/4c5b64ee-095e-4bd5-857a-d0f81f43e8a8)

### Expected Behavior

Text should stop _before_ the switch and continue onto the next line if necessary.

### Reproduction Sample

https://codepen.io/iyouth66/pen/gOZgomO?editors=1100

### Reproduction Steps

(see codepen)

### Reproduction Version

1.7.0

### Relevant Info

N/A

### Regression?

`1.6.1`

### Priority impact

p2 - want for current milestone

### Impact

Smart mapping currently suffers from this issue:
![image](https://github.com/Esri/calcite-design-system/assets/131201379/2b6654ae-617d-4170-9bc4-be8c9e141a3b)

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Investigate if using the `stack` component could mitigate the above.

**Comment by AdelheidF** [comment]
Could this be get fixed before January? It's all over the place ...

![image](https://github.com/Esri/calcite-design-system/assets/44481292/fd843a29-237f-4022-962e-f8db2222146f)

**Comment by geospatialem** [comment]
@AdelheidF @ian13262 It looks like this is a regression [between `1.6.1` and `1.7.0`](https://github.com/Esri/calcite-design-system/compare/%40esri/calcite-components%401.6.1...%40esri/calcite-components%401.7.0) as a result of accessibility improvements to the component - added context to the issue summary above. 

More context:
- Works in `1.7.0-next.21`: https://codepen.io/geospatialem/pen/VwgaboK
- Doesn't work in `1.7.0-next.22`: https://codepen.io/geospatialem/pen/bGzpWPL
- Looks like a result of commit https://github.com/Esri/calcite-design-system/commit/1f44f6b0e05bcaf708015432ef64c8cb660101bd


Added a regression label and medium priority level, and hope to tackle before the close of 2023 with other priority issues.

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.3`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/fa601bcf-fcbb-48ae-b0b6-0d7a75b9c365)
