### ISSUE TITLE
Accordion: update chevron colors

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7710]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When expanded, the chevron is black.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/1f27fa88-5159-4d0e-ba73-2e8289121888)

### Expected Behavior

For system consistency, it should revert to `ui-text-3`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/b001d602-0f60-4f02-a81f-2f155435c530)

### Reproduction Sample

https://codepen.io/ashetland/pen/MWZpgRd

### Reproduction Steps

Expand an Accordion Item.

### Reproduction Version

v1.8.0

### Relevant Info

Figma designs for Accordion [here](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---icon-consistency-%5B7181%5D?type=design&node-id=914-348742&mode=dev). 

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.3`. 🙌🏻
