### ISSUE TITLE
Input Date Picker: update chevron colors

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7712]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Input Date Picker's chevrons are black in all states.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/9a5315fe-862e-4dbb-b5ab-044b8eb122d4)

### Expected Behavior

For system consistency, chevrons should be `ui-text-3` when idle and `ui-text-1` when hovered or pressed.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/8d09f1bc-3295-4159-b08b-d5852e15b9a7)

### Reproduction Sample

https://codepen.io/ashetland/pen/MWZpgRd

### Reproduction Steps

Interact with Input Date Picker.

### Reproduction Version

v1.8.0

### Relevant Info

Figma designs for Input Date Picker [here](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---icon-consistency-%5B7181%5D?type=design&node-id=914-348742&mode=dev).

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by brittneytewks** [comment]
Removed Figma changes label as this will be tracked in monday.com

**Comment by DitwanP** [comment]
🍡 Verified on `2.8.0-next.7`
