### ISSUE TITLE
Input Time Picker: update chevron colors

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7713]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Input Time Picker's chevrons are black in all states.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/447df79d-dbb7-473c-a898-46b9bf501758)

### Expected Behavior

For system consistency, chevrons should be `ui-text-3` when idle and `ui-text-1` when hovered or pressed.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a5d10f70-f0a7-4666-8a6e-6f555a6b19f0)

### Reproduction Sample

https://codepen.io/ashetland/pen/MWZpgRd

### Reproduction Steps

Interact with Input Time Picker

### Reproduction Version

v1.8.0

### Relevant Info

Figma designs for Input Time Picker [here](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---icon-consistency-%5B7181%5D?type=design&node-id=914-348742&mode=dev).

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by brittneytewks** [comment]
Removed Figma changes label as this will be tracked in monday.com

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.16`

![verify-chevrons](https://github.com/Esri/calcite-design-system/assets/5023024/4d8e36c5-37c6-4624-ba8c-30721f40f1be)
