### ISSUE TITLE
Disabled Combobox Items reveal icon onHover

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7719]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When hovering over a disabled Combobox Item, the `circle-disallowed` icon appears.

### Expected Behavior

I would expect no interaction on `disabled` items and thus no icon should appear.

### Reproduction Sample

https://codepen.io/ashetland/pen/YzdZPEM

### Reproduction Steps

Hover over `disabled` items in the open Combobox.

### Reproduction Version

v1.8.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
@BrunoCaimar Is helping us with this one! 🎉

**Comment by jcfranco** [comment]
Thanks again @BrunoCaimar for helping us out with this! 🏆

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.3`. 🎉
