### ISSUE TITLE
Enhancement: Make selected List item whitespace consistent

### ISSUE THREAD

**Issue by maxxxxxdlp** [Esri/calcite-design-system#7725]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

When rendering List with `selectionAppearance="icon"`, there is too much whitespace between the icon and the label:

![MicrosoftTeams-image](https://github.com/Esri/calcite-design-system/assets/40512816/e4c75dcd-cb80-4fbc-92aa-738b0a74ab8e)

### Acceptance Criteria

Reduce the whitespace (potentially whitespace to the right of the icon should match that to the left)

### Relevant Info

See how much more compact our pre-calcite design has been:

![MicrosoftTeams-image (1)](https://github.com/Esri/calcite-design-system/assets/40512816/059f1c46-32bc-4a31-acf6-65638c18f59d)

[(demo link)](https://zrh-app-sd-2.esri.com/arcgis-play/f/87t3)

Related issue: https://github.com/Esri/calcite-design-system/issues/6700

### Which Component

List

### Example Use Case

Used in the [ScaleRangeSlider](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-ScaleRangeSlider.html) JS API Widget

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
This effort will be handled in #7100, targeted for December.
