### ISSUE TITLE
Bug: selected list item border does not extent to custom content

### ISSUE THREAD

**Issue by maxxxxxdlp** [Esri/calcite-design-system#7726]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

1. Render a `<calcite-list>` with `selectionAppearance="border"`
2. Render a `<calcite-list-item>` and make it selected
3. Add child content to the `<calcite-list-item>`
4. The border left that signifies selected element does not extent to the custom content. The whitespace does not extend either. The background change on hover does not extend either.

See:
![Screenshot 2023-09-11 at 16 28 12](https://github.com/Esri/calcite-design-system/assets/40512816/c97bdd03-7401-4191-bb14-f63ad7d36eb4)

In my use case that looks like this:
![Screenshot 2023-09-11 at 16 28 44](https://github.com/Esri/calcite-design-system/assets/40512816/e70ee6b8-375b-439a-83de-7511728f0319)

Moreover, the border size and whitespace size of calcite item is not governed by a css variable, so while I can manually add matching styles to my custom content (see screenshot below), it might not match calcite in the future.

Same issue is present when using `selectionAppearance="icon"` (whitespace and hover background), but is less noticeable due to absence of border

### Expected Behavior

![Screenshot 2023-09-11 at 16 31 44](https://github.com/Esri/calcite-design-system/assets/40512816/8db2e49f-0322-409a-b105-d1bf26c213d4)

I understand that current behavior provides much more styling freedom, which might be desirable in some cases - if so, consider disregarding this bug request.

### Reproduction Sample

https://codepen.io/maxpatiiuk/pen/NWejjZy?editors=1010

### Reproduction Steps

1. Open https://codepen.io/maxpatiiuk/pen/NWejjZy?editors=1010
2. Select an item, and move focus elsewhere
3. See the border, which does not extend to the item contents. Also whitespace and hover background don't match

### Reproduction Version

1.8.0

### Priority impact

p4 - not time sensitive

### Impact

No impact. This would have impacted our previous design, but we decided to go with a different design that avoids facing this issue.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by macandcheese** [comment]
The default slot for List Item only supports adding calcite-list-item and calcite-list-item-group elements, it is not meant to contain content.

https://developers.arcgis.com/calcite-design-system/components/list-item/#api-reference-slots-unnamed

**Comment by maxxxxxdlp** [comment]
Ah, thanks for clarifying - I overlooked that.
feel free to close this issue as it doesn't impact our project

**Comment by geospatialem** [comment]
Closing per [Adam's comment on use](https://github.com/Esri/calcite-design-system/issues/7726#issuecomment-1715784623) and[Max's comment on impact](https://github.com/Esri/calcite-design-system/issues/7726#issuecomment-1715886286).
