### ISSUE TITLE
Click on a disabled button still causes a popover opening

### ISSUE THREAD

**Issue by cont-feofanov** [Esri/calcite-design-system#7732]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

A popover whose reference-element is a disabled calcite-button is opened on a button click.

### Expected Behavior

When a reference-element a disabled then a popover should not be displayed  when a disabled button was clicked.

### Reproduction Sample

https://codepen.io/cont-feofanov/pen/zYyzZwN?editors=100

### Reproduction Steps

See the sample

### Reproduction Version

1.8.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Business/Community Analyst

**Comment by geospatialem** [comment]
@cont-feofanov Would this [workaround](https://codepen.io/geospatialem/pen/LYMLyBo) support the use case, where the `trigger-disabled` attribute would compliment the `popover` when the `button` is `disabled`?

**Comment by cont-kolomeets** [comment]
@geospatialem Thank you for the workaround, but will it be fixed in the next release? It's a regression from 1.2.0.

**Comment by jcfranco** [comment]
@geospatialem Bumped the priority and updated milestone since we have a few spots where `pointerdown` is used instead of `click`, which may lead to inconsistent behavior.
