### ISSUE TITLE
Rotary knob (input element)

### ISSUE THREAD

**Issue by esride-nik** [Esri/calcite-design-system#7735]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### I'd like a rotary knob input element that acts pretty much like a slider.

Why? They're less space-consuming in the layout. They'd come in handy in case you have to bring in a lot of values that can be changed by the user.

Inspiration: 
- A mixer console: Mechanical sliders are used for the one "big value" per channel (volume), but there are rotary knobs for all the fiddly parts like gain, f/x loops and stuff.
![image](https://github.com/Esri/calcite-design-system/assets/1322415/4f5c605c-8b23-46ee-983a-ef844aba2e75)
- A digital version of it is often to be found on DAW UIs, like Ableton Live. 
![image](https://github.com/Esri/calcite-design-system/assets/1322415/8f0d01ec-3227-47b7-996f-d3c2f3cf0ab5)

#### Mandatory:
- min / max values (number range) can be defined
- current value property (set / get)
- setting the property via mouse/touch: klick on knob and hold while dragging up or down makes the knob turn and the value change (up=right, down=left)

#### Optional:
- label / input box to display and type in the current value
-more props inspired by the existing slider, like ticks, label-ticks, step etc.

#### Optional but super fancy and standing out from the slider:
Give the rotary knob an outer ring to display the current value within the range. Then give the knob a factor, that defines how many time it has to be fully turned to cover the full number range.
For example, look at the image below: The black knob in the center would have to be turned like 3 times to bring the value from min to max, while the left end of the cyan outer ring is always min and the right end is always max.
This gives the user the ability to enter super fine-grained values by turning the knob.
![image](https://github.com/Esri/calcite-design-system/assets/1322415/3d1343eb-e50b-4c30-89a6-a4785a8cf2ad)

### Which Component

New rotary knob component

### [Example Use Case](#exampleusecase)

+ It would be perfect as an exchange for the zoom level and tilt controls in the upper right corner of this demo: https://codepen.io/esride-Nik/pen/gOZgLdo. As the knobs would work in both ways, just imagine having knobs for all camera props and seeing them turn when navigating in the scene.
+ see "inspiration" above

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react

### Esri team

Professional Services - Services Delivery

**Comment by DitwanP** [comment]
Knobs as sliders have been reported as confusing to use. The interaction isn't intuitive, especially with mouse or touch input. Questions arise such as which axis affects the value and whether a circular motion is required. NNGroup has a good [writeup](https://www.nngroup.com/articles/sliders-knobs/#:~:text=the%20price%20chart.-,Virtual%20Knobs,-Virtual%20knobs%20or) on this topic, highlighting the ambiguity of traditional knobs. In most cases, vertical or horizontal sliders can achieve the same results in a simpler and more understandable way.
 
Additionally, we haven't seen significant demand for a component like this, so for that reason, we won't be adding this component at this time.
