### ISSUE TITLE
Group interaction components

### ISSUE THREAD

**Issue by esride-nik** [Esri/calcite-design-system#7737]
### Description

The [list of components](https://developers.arcgis.com/calcite-design-system/components/) is growing pretty large. I feel like they should be put in categories of some sort. My best guess for categories:
+ **Input components** are alreadygrouped nicely: They all accept text input.
+ There are lots of large **layout components** like panels and steppers.
+ There are **interaction components** that enable some sort of user input that is not textual, like slider, [rotary knob](https://github.com/Esri/calcite-design-system/issues/7735), button, checkbox, switch, select, dropdown, rating, pickers...
+ And then there are all these **little things** like chips, loader, progress which don't fall in an obvious category. Others like labels or filters could be **util components**, avatar could even be the foundation of a new group like **social components**.

In other API resources like [JSSDK](https://developers.arcgis.com/javascript/latest/api-reference/), these things are grouped into namespaces.
To deal with the fact that not all components might obviously fall into a certain category, you could use tags or keywords to make them searchable.

### Which Component

All of them

**Comment by driskull** [comment]
Yeah it would be nice to have the components placed into some kind of taxonomy. At least tagged because some components may fall into multiple categories.

**Comment by geospatialem** [comment]
Calcite does not plan to organize the documentation site by category at this time.
