### ISSUE TITLE
Add maxItems to `input-time-zone`

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7738]
### Check existing issues

- [X] #7739

### Description

`calcite-input-time-zone` uses `calcite-combobox` under the hood, so it'd be useful to add `maxItems` to allow users to limit the displayed items.

cc @macandcheese

### Acceptance Criteria

`maxItems` is added to the component and matches combobox's.

### Which Component

`calcite-input-time-zone`

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.0` with `<calcite-input-time-zone max-items="10"></calcite-input-time-zone>`:

![verified Input Time Zone with maxItems](https://github.com/Esri/calcite-design-system/assets/5023024/18e89f50-2889-4180-ada4-64ff698aba14)
