### ISSUE TITLE
Regression with alert opening events

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#7757]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When rendering a `<calcite-alert open>` element, the `calciteAlertBeforeOpen` and `calciteAlertOpen` events are no longer emitted.

### Expected Behavior

When rendering a `<calcite-alert open>` element, the `calciteAlertBeforeOpen` and `calciteAlertOpen` events are still emitted.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/PoXJLaG

### Reproduction Steps

1. Visit the code sample and open the console
2. See that `calciteAlertBeforeOpen` and `calciteAlertOpen` are not printed to the console

### Reproduction Version

1.8.0

### Regression?

1.4.3

### Priority impact

p1 - need for current milestone

### Impact

This is breaking some logic we have that runs before the alert opens to determine if we should suppress the alert, or not. As a result, the user is now getting alerted more often than needed.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.5`.
