### ISSUE TITLE
Stepper: add support for built-in translations

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7759]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Adds built-in translation support for `calcite-stepper` & `calcite-stepper-item` accessible labels added in #560

### Acceptance Criteria

- Accessible ARIA labels should have translations when user switches the language
- User should be able to override default translation strings.

### Which Component

`calcite-stepper`
`calcite-stepper-item`

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified on the `main` branch. All translations also appear to already be present across languages. ✨
