### ISSUE TITLE
Tooltip placement over actions in a flow item is incorrect

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-design-system#7764]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If you use a safari browser and have a structure like the following:
```ts
<calcite-panel>
        <div slot="header-content">Header</div>
        <calcite-flow>
          <calcite-flow-item>
            <calcite-action-group>
              <calcite-action>
                <calcite-tooltip label="home" closeOnClick overlayPositioning="fixed" slot="tooltip" placement="top">home</calcite-tooltip>
```
then you will see the tooltip does not appear correctly as it should be on top of the action and over top of the header. However if you switch the flow item to a panel then it works as expected. We should be able to use the flow item as intended and still maintain the same positioning for tooltips I think.

### Expected Behavior

Tooltips inside of flow items should overlay the header when `overlayPositioning` is set to `fixed` and `position` is set to `top`

### Reproduction Sample

https://codepen.io/sam11927/pen/dywNBJJ?editors=1000

### Reproduction Steps

1. open up the repro codepen in a safari or firefox browser
2. hover over the top action (flow item) and see that the positioning is below the action even though the code specifies `top` and `fixed`
3. repeat the same with the bottom action (calcite-panel) and see that the positioning is correct (this is just for reference)

### Reproduction Version

1.8.0

### Relevant Info

Safari or firefox browser needed, does not seem to repro in chrome

Safari version: `16.6 (18615.3.12.11.2)`

### Priority impact

p4 - not time sensitive

### Impact

Impacts analysis workflow's accessibility 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
This might be a result of the attribute use, where attributes use `"-"` and properties use camelCase, for instance:

- HTML attribute: `overlay-positioning`
- JS property: `overlayPositioning`

In testing with https://codepen.io/geospatialem/pen/NWewgrr with the updated attributes for `overlay-positioning` and `close-on-click` the functionality appears as-expected in Safari, FF, and Chrome. @sam11927 Can you take a peek to see if the updates mitigate the issue? And if the issue persists, could you provide the browser versions for troubleshooting?

**Comment by sam11927** [comment]
Thanks for the info, yeah I am not seeing it fixed with these updates unfortunately :(
Safari version: 16.6 (18615.3.12.11.2)

**Comment by geospatialem** [comment]
Confirmed as working with Sam via Teams. Closing the above.
