### ISSUE TITLE
Create reusable util for adjusting internal icon scale used within a component

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7765]
### Description

Stems from https://github.com/Esri/calcite-design-system/pull/7755/#discussion_r1329349259.

The logic to adjust internal icon scales (see https://github.com/Esri/calcite-design-system/blob/d05c79462855141db916b37e673b146d9a9c3d6f/packages/calcite-components/src/components/alert/alert.tsx#L289) should be extracted into its own util and used across all components.

cc @driskull @ashetland @SkyeSeitz 

### Proposed Advantages

DRYer code by having component use this util to get the effective internal icon scale.

### Which Component

* `accordion-item.tsx`
* `action.tsx`
* `alert.tsx`
* `button.tsx`
* `chip.tsx`
* `color-picker-hex-input.tsx`
* `color-picker.tsx`
* `combobox-item.tsx`
* `date-picker-month-header.tsx`
* `dropdown-item.tsx`
* `input-date-picker.tsx`
* `input-number.tsx`
* `input-text.tsx`
* `input.tsx`
* `modal.tsx`
* `notice.tsx`
* `pagination.tsx`
* `popover.tsx`
* `select.tsx`
* `tab-title.tsx`
* `table-header.tsx`
* `table-row.tsx`
* `time-picker.tsx`
* `tree-item.tsx`
* `XButton.tsx`

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

**Comment by driskull** [comment]
Sweet! this will be nice to have

**Comment by alhridoy** [comment]
Hi @jcfranco  I have reviewed the issue and I'd like to contribute by creating the reusable utility for adjusting internal
Icon scales. Is it alright if I take this up?

**Comment by driskull** [comment]
@alhridoy sounds great. Feel free to take it on! Let us know if you have any questions.

**Comment by jcfranco** [comment]
Thanks again @alhridoy for helping out with this! 🏆

**Comment by geospatialem** [comment]
Verified across components. 🎉
