### ISSUE TITLE
Add readonly prop to input-time-zone (like input-date-picker, input-time-picker)

### ISSUE THREAD

**Issue by JonUihlein** [Esri/calcite-design-system#7853]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Both `<calcite-input-date-picker>` and  `<calcite-input-time-picker>` support the `readOnly` property, which has different styling than the `disabled` property. This is a request for adding `readOnly` property to `<calcite-input-time-zone>` so we can keep styling consistent. We prefer `readOnly` for accessibility reasons since `disabled` prevents interaction with the component (and prevents things like copying the value by hand/keyboard). 

Mixed "readOnly" and "disabled":
![editor-timezone-disabled](https://github.com/Esri/calcite-design-system/assets/2378615/6bec2f5c-8c74-470b-ab49-6329a7e89733)

### Acceptance Criteria

Support for `readOnly` on `<calcite-input-time-zone>`

### Which Component

`<calcite-input-time-zone>`

### Example Use Case

Styles used by `<calcite-input-date-picker>` and `<calcite-input-time-picker>`

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by ashetland** [comment]
@josercarcamo Just saw this had a design label on it. Do you need anything from us on this one or just a quick review of the visuals?

**Comment by josercarcamo** [comment]
Hi @ashetland. I'm not sure. I didn't notice the "design" tag. I was just told by @JonUihlein to make it like the other readonly input elements, so I tried to match the UI/UX of the input date and time pickers.

**Comment by DitwanP** [comment]
@josercarcamo I'm having trouble verifying this issue. on this [codepen](https://codepen.io/Ditwan-Price/pen/YzMJVNB?editors=100) you can see that `read-only` is working as expected on the `date-picker` but not on the `input-time-zone`. 

I also ran the demos locally and it seems like it's working in regards to not allowing me to actually open the dropdown, but the styling there doesn't match. It looks like the components that get `read-only` don't show the dropdown arrow on the right side of the input but the `input-time-zone` is still showing it in the demos.

<img width="848" alt="image" src="https://github.com/Esri/calcite-design-system/assets/60022782/bf8f4078-13ce-4726-8c99-b62ed5265d5f">

**Comment by jcfranco** [comment]
[Belated] Picked up this one for the R2 release. Installed!

**Comment by DitwanP** [comment]
🍠 Verified on `main`
