### ISSUE TITLE
[Combobox Item] `--calcite-ui-icon-color` CSS Property does not work

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7854]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Using `--calcite-ui-icon-color` CSS Property does not work for Combobox Item. 

### Expected Behavior

I'd expect the override to take effect, as it does in other components.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/abPEvMQ?editors=1000

### Reproduction Steps

1. Open Codepen
2. Notice the override works for Dropdown
3. Notice the override does not work for Dropdown.

### Reproduction Version

1.8

### Priority impact

p2 - want for current milestone

### Impact

While expanding the available public css properties through the design token effort will make overriding icon colors easier (especially since we'll have values for individual icons like selection icon + the icon set via property) - this variable should still work.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Should be included in the [screenshot test stories](https://github.com/Esri/calcite-design-system/blob/14036c1354419222bc5b839af8b68675b17ebf62/packages/calcite-components/src/05-custom-theme.stories.mdx#L750 by adding a `combobox` with an `icon`.

**Comment by geospatialem** [comment]
We should check if this is mitigated by efforts in https://github.com/Esri/calcite-design-system/issues/7180 once completed.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev` 
![image](https://github.com/user-attachments/assets/2d3be671-6313-429a-ab70-0cb1c48c9bd8)
