### ISSUE TITLE
[Pagination] Responsive layout for specific XS layouts/dimensions

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7856]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A follow-up issue to https://github.com/Esri/calcite-design-system/issues/6687 to address specific XS screen dimensions, where `pagination` should be sized to accommodate specific XS dimensions, as not all use cases fit the 475px breakpoint.

_Note_ the start/end buttons are not yet in the Calcite UI icons, Skye added a high priority ticket for them to be added. The current button icons are local SVGs (currently noted in Figma).

cc @SkyeSeitz for design expertise, specifics with the breakpoint needed, and follow-up when working through the responsive update.

### Acceptance Criteria

- The last responsive addition should be consulted with Skye
- [Figma file](https://www.figma.com/file/iCQBMp5Q5zlSfyE9NxkdO7/Pagination---responsive?type=design&node-id=608%3A56424&mode=dev)
- Screenshot and GIF:
<img width="638" alt="MicrosoftTeams-image (21)" src="https://github.com/Esri/calcite-design-system/assets/5023024/495e5bb9-a505-4c6d-8fb4-7e33786b2fbf">

https://github.com/Esri/calcite-design-system/assets/5023024/751b0b3f-ec9e-475c-a76f-029227ff38d6

### Relevant Info

Part of epic https://github.com/Esri/calcite-design-system/issues/6670, originated from https://github.com/Esri/calcite-design-system/issues/6687

### Which Component

`pagination`

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by driskull** [comment]
A blocker for this would be adding a new breakpoint for a smaller size.

**Comment by geospatialem** [comment]
> A blocker for this would be adding a new breakpoint for a smaller size.

@driskull Should we migrate this issue to October to work out the new breakpoint?

**Comment by driskull** [comment]
@geospatialem Thats a good question for the design team, might be a good idea unless they can do it sooner.

**Comment by geospatialem** [comment]
> A blocker for this would be adding a new breakpoint for a smaller size.

> Should we migrate this issue to October to work out the new breakpoint?

> Thats a good question for the design team, might be a good idea unless they can do it sooner.

cc @SkyeSeitz WDYT?

**Comment by SkyeSeitz** [comment]
Hey folks! Discussed considering adding an additional breakpoint at 320px with Matt, which is generally the smallest mobile size. This could work just for Pagination or across all components if needed, but would love insight from @jcfranco if you lean one way or the other. 

Link to [Pagination specs](https://www.figma.com/file/iCQBMp5Q5zlSfyE9NxkdO7/Pagination---responsive?type=design&node-id=620%3A22251&mode=dev) with additional breakpoint.

**Comment by driskull** [comment]
Either way, if we add the breakpoint as a global breakpiont or a component breakpoint, can we put the new breakpoint in a token?

**Comment by driskull** [comment]
@geospatialem this should be spiked/blocked until we have another breakpoint to use for this work.

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.2`.
