### ISSUE TITLE
Syntax error setting `Infinity` on number input

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#7866]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Setting the value of a `<calcite-input-number>` input to `Infinity` generates a console error:

```
SyntaxError: Cannot convert Infinity0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 to a BigInt (at p-a48cbcc5.js:6:798)
    at BigInt (<anonymous>)
    at new a (p-a48cbcc5.js:6:798)
    at p-a48cbcc5.js:6:2771
    at p-a48cbcc5.js:6:2840
    at f (p-a48cbcc5.js:6:3094)
    at $ (p-a48cbcc5.js:6:2646)
    at K.setNumberValue (p-ceeae984.entry.js:6:4983)
    at K.valueWatcher (p-ceeae984.entry.js:6:6697)
    at p-5f56ab0e.js:6:8473
    at Array.map (<anonymous>) 
```

### Expected Behavior

No error is generated, with possibly the input's value showing as `"Infinity"`.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/jOXZVGJ

### Reproduction Steps

1. Visit the code sample and open the console
2. Click the **Set Infinity** button and see error logged to console

### Reproduction Version

1.8.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
@nwhittaker Thanks for filing the above, could you speak more to the use case of adding infinity in, and expecting an error in the log as a result?

**Comment by ethanbdev** [comment]
We ran into this too - I think since `Infinity` is a valid number in javascript, its reasonable for the prop to be set to this via jsx

**Comment by nwhittaker** [comment]
>…could you speak more to the use case of adding infinity in…

The non-reduced test case is when the input is used in a data-down, action-up flow:
1. The numeric input is rendered with a value from a data model.
2. The user enters a number larger than `Number.MAX_VALUE`.
3. The input's change handler uses `Number(input.value)` to coerce a number which resolves to `Infinity`.
4. This value then gets propagated back to the data model.
5. Updating the data model triggers a re-render which sets the input's value to `Infinity` and causes the crash.

>…and expecting an error in the log as a result?

This sounds backwards. An error in the log is the actual behavior. I'm expecting no error to be logged.

That being said, the non-reduced case is a bit naive. The consumer should either add support for `BigInteger` values, or set sane min/max attributes. However, and regardless of how you end up handling `Infinity` values, setting the input's value to `Infinity` shouldn't cause the component to crash.

**Comment by geospatialem** [comment]
Research spike needed to determine next steps on a good solution moving forward.

**Comment by jcfranco** [comment]
@benelan @eriklharper For the spike, could you team up to look into solutions for this and which components/parts would need to be updated?

**Comment by benelan** [comment]
I can tackle this on my end, I believe I know the solution

**Comment by DitwanP** [comment]
🍫 Verified locally on `main`
