### ISSUE TITLE
Flow: Support cancelling the calciteFlowItemBack event in order to prevent going back

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7869]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Allow calciteFlowItemBack event to be cancelled in order to prevent going back

### Acceptance Criteria

The cancelling of `calciteFlowItemBack` will prevent the `back` method from being called.

### Which Component

flow, flow-item

### Example Use Case

```
const lastFlowItem = document.querySelector("calcite-flow-item:last-of-type");
lastFlowItem?.addEventListener("calciteFlowItemBack", (event) => event.preventDefault());
```

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.7` with https://codepen.io/geospatialem/pen/JjwpJaZ.
