### ISSUE TITLE
List: add oldIndex and newIndex values to calciteListOrderChange event detail

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7875]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add additional event details to custom event

### Acceptance Criteria

List: add oldIndex and newIndex values to calciteListOrderChange event detail

### Which Component

List

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.12` with:

```js
document.querySelector("calcite-list").addEventListener("calciteListOrderChange", (evt) => {
  console.log(evt.detail.oldIndex);
  console.log(evt.detail.newIndex);
});
```
