### ISSUE TITLE
[Action Bar] overflow logic doesn't ungroup `menu-item` actions

### ISSUE THREAD

**Issue by gopal-y** [Esri/calcite-design-system#7881]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Action bar when `overflowActionsDisabled: false`, which is default, fails to repopulate the action elements in the menu slot until the wrapping component is resized to a very larger width.

### Expected Behavior

Add the action elements in the menu slot to the action bar default slot, when the width of the wrapping container is just enough to contain it.

### Reproduction Sample

https://codepen.io/im-the-developer/full/qBLooXP

### Reproduction Steps

1. Open the app
2. click on the OrientedImageryAction
3. A widget is displayed in a resizable calcite-shell-panel to the right of the app
4. Try resizing the shell-panel to a smaller width it can be observed that the action elements are moved to menu slot
5. Now resize the shell panel to a width which can contain the entire actions, it can be observed that the action elements are still in the menu slot.
6. Resize the shell panel to even larger width, it can be observed that the action elemnts are now visible in the default slot
[calcite-action-bar-bug.webm](https://github.com/Esri/calcite-design-system/assets/30383517/e53e82a8-41f0-40f2-b64a-e85b2f427daf)

### Reproduction Version

1.4.2

### Relevant Info

Windows 10, Microsoft Edge

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.12`.

![verify-7881](https://github.com/Esri/calcite-design-system/assets/5023024/2522e747-65ec-438e-b9da-15b46c7027e7)
