### ISSUE TITLE
[Dialog] Add new component, deprecate modal component

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7886]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The ModelBuider Web team is seeking a movable, non-attached component in early 2024 to support a workflow not requiring an additional click and is not restrictive for the user experience, where the use case cannot use `modal` as a solution.

We should identify if the new dialog component should support:
- Resizing
- Moving

Or, if not, what the recommended workflow would be for support with docking or an alternative approach.

### Acceptance Criteria

Design: **[Figma file](https://www.figma.com/design/wVqftT1aZDjwYVkDZ2V5fC/Dialog?node-id=874-25664&m=dev)** 🎨 

1. Dependency issues
    - **Panel**
        - [x] https://github.com/Esri/calcite-design-system/issues/6980
        - [x] https://github.com/Esri/calcite-design-system/issues/8979
        - [x] https://github.com/Esri/calcite-design-system/issues/8980
        - [x] https://github.com/Esri/calcite-design-system/issues/8981
    - **Modal**
        - [x] https://github.com/Esri/calcite-design-system/issues/7668
2. Add a new `dialog` component
    - "Render a `panel` inside" paradigm - refer to `popover`, `sheet`, and `shell-panel`
    - Properties
        - modal/non-modal
        - `kind`
        - `placement`
        - `heading`
        - `description`
        - `scale`
        - `scale-width`
        - `fullscreen` (under consideration 🚧 )
            - cc https://github.com/Esri/calcite-design-system/issues/6191 
        - `resizable` (under consideration 🚧 )
        - `draggable` (under consideration 🚧 )
    - Slots
        - `content`
        - `header`
3. Deprecate the `modal` component 

### Relevant Info

Originally reported in https://devtopia.esri.com/WebGIS/calcite-design-system/issues/163

### Which Component

New component

### Example Use Case

See the internal issue for additional context.

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by driskull** [comment]
> The use case cannot use modal as a solution.

Can you elaborate on this a bit? I don't see why a non blocking modal (scrim turned off) couldn't support this better.

It seems like modal would fit this use case better. 

I could see popover supporting resizing but not being a movable draggable object. Modal would be better for that use case. The whole point of popover (and floating-ui) is to attach to another element.

**Comment by driskull** [comment]
@geospatialem can we separate resizing into their own unique issues? I do see resizing as valid requests for both modal and popover. However, the dragging is probably only valid for modal or another component that is visually equivalent to modal but non blocking.

**Comment by driskull** [comment]
I think the best solution would be to deprecate `modal` and add a `dialog` component. The dialog component could have a property for `modal/non-modal` as well as properties for resizing and dragging.

**Comment by ethanbdev** [comment]
Totally open to the best solution, whether its enhancing the modal or a new dialog component to meet the use case

**Comment by ethanbdev** [comment]
Hey @geospatialem - could this be assigned to a milestone? I am not sure how far out you plan

**Comment by geospatialem** [comment]
> Hey @geospatialem - could this be assigned to a milestone for tracking? I am not sure how far out you plan

Hi @ethanbdev, this issue will need some design expertise prior to dev work, so there will likely be two milestones to address the effort. Design will be triaging issues late next week for consideration into an upcoming design sprint. cc @brittneytewks

**Comment by ethanbdev** [comment]
Perfect - thanks!

**Comment by macandcheese** [comment]
> I think the best solution would be to deprecate `modal` and add a `dialog` component. The dialog component could have a property for `modal/non-modal` as well as properties for resizing and dragging.

I think this is a good idea. It would also allow the new component to follow the “slot a Panel inside” paradigm Sheet, Shell Panel follow.

**Comment by mjuniper** [comment]
We have a use case for this. We want to show a non-modal privacy consent dialog positioned in the lower right of the screen like this:

![image](https://github.com/Esri/calcite-design-system/assets/942837/283053fc-776e-4dda-bada-cddc7514d928)

**Comment by macandcheese** [comment]
@geospatialem maybe we can repurpose this issue to encompass the discussion above re: Modal -> Dialog.

**Comment by macandcheese** [comment]
If we explore Panel as the expected slotted element in this new Dialog - it would align more closely with Shell Panel / Sheet DX and UI. We'd likely want to rename "Action bar" and "Fab" slots in Panel to be more generic like Modal's "sticky top and bottom" ones.

**Comment by Azadirachta** [comment]
Hello @geospatialem - Please could you suggest a possible timeline for this issue? Thank You!

Originally reported in https://devtopia.esri.com/WebGIS/calcite-design-system/issues/163

**Comment by geospatialem** [comment]
> Hello @geospatialem - Please could you suggest a possible timeline for this issue? Thank You!

@Azadirachta Thanks for reaching out! The new component effort is currently in the design backlog for consideration with other high priority bug fixes and enhancements - Calcite does not have a timeline at this time, but will update the issue in the coming weeks on the design efforts (note that the dev efforts for implementation would be in addition to the design).

**Comment by driskull** [comment]
Can we get a separate issue for adding `alerts` slot on `calcite-panel`? This way it will be installed and documented as a separate feat PR.

**Comment by driskull** [comment]
@SkyeSeitz @geospatialem from Figma docs, it says `keyboard user will get a live area notification and move via keyboard`. 

What should the text say for this aria-live area?

I'm assuming it would say something for moving and resizing via keyboard but I could use help with what exactly to say.

Arrow keys should move the dialog whereas arrow keys plus shiftKey should resize the dialog.

**Comment by geospatialem** [comment]
> @SkyeSeitz @geospatialem from Figma docs, it says `keyboard user will get a live area notification and move via keyboard`.
> 
> What should the text say for this aria-live area?
> 
> I'm assuming it would say something for moving and resizing via keyboard but I could use help with what exactly to say.
> 
> Arrow keys should move the dialog whereas arrow keys plus shiftKey should resize the dialog.

@driskull The role should provide the context of how to interact with the component, but we should support a label to provide additional context to what the purpose of the component is. Maybe we should have a default label, and the developer could specify using a `label` attr/prop? cc @SkyeSeitz

**Comment by geospatialem** [comment]
Verified in `2.11.0-next.25` in https://codepen.io/geospatialem/pen/rNEjemQ with the following (listed as attributes below, where applicable):
- Default slot
- `placement` for `"top-start"`, `"top"`, `"top-end"`, `"center"` (default), "`bottom-start"`, `"bottom"`, and `"bottom-end"`
- `kind` for `"brand"`, `"danger"`, `"info"`, `"none"` (default), `"success"`, `"warning"`
- `heading`
- `description`
- `scale`
- `width-scale`
- `open`
- `close-disabled`
- `loading`
- `menu-open`
- `modal`
- `overlay-positioning`

Of note the resizing and dragging of the component will be handled in https://github.com/Esri/calcite-design-system/issues/9875 anticipated for the August release.

There looks to be something off when `overlay-positioning="fixed"` and `menu-open` is present: https://codepen.io/geospatialem/pen/ZEdLWNZ, so will open a follow-up issue to tackle. cc @driskull
