### ISSUE TITLE
Action menu: add appearance property

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7888]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Action menu: add appearance property

### Acceptance Criteria

Action menu: add appearance property

### Which Component

action-menu

### Example Use Case

```html
<calcite-action-menu appearance="transparent">
      <calcite-action text="Plus" icon="plus" text-enabled></calcite-action>
      <calcite-action text="Minus" icon="minus" text-enabled></calcite-action>
      <calcite-action text="Table" icon="table" text-enabled></calcite-action>
    </calcite-action-menu>
```

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified with the `action-menu` where `appearance` is `"transparent"` and `"solid"`. 

cc @SkyeSeitz @ashetland @brittneytewks for Figma changes.
