### ISSUE TITLE
[date-picker] Max value constraint can't be cleared

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#7889]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Once the max value constraint is set on date-picker, it can't be removed

### Expected Behavior

The max value constraint can be removed

### Reproduction Sample

https://codepen.io/mpayson/pen/NWeMjGg

### Reproduction Steps

1. Open code pen
2. Open date input, see dates passed 9/27 are disabled
3. Click button to clear the constraint
4. Open date input, see dates passed 9/27 are still disabled

### Reproduction Version

1.8.0

### Relevant Info

Browser: Firefox

Also reproducible in the calcite-react bindings when setting the property like:

```ts
max={endDate ? formatDateInputString(endDate) : undefined}
```

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Verified in `2.9.0-next.2`. 🗓️ 

![verify-issue](https://github.com/Esri/calcite-design-system/assets/5023024/cff13569-a4d3-4cfb-97a8-d1b2768408d2)
