### ISSUE TITLE
ActionBar: When overflowActionsDisabled is true and then set to false, actions should be overflowed

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7891]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Currently, when `overflowActionsDisabled` is set to true and then set to false, actions are not overflowed. Meaning no overflowing occurs after the toggle happens.

### Expected Behavior

When `overflowActionsDisabled` is toggled from true to false, actions should start overflowing.

### Reproduction Sample

https://codepen.io/driskull/pen/poqVqKe?editors=1000

### Reproduction Steps

1. Open sample
2. Click toggle action
3. Notice actions are not overflowed

### Reproduction Version

1.8.0

### Regression?

No

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.12`.
