### ISSUE TITLE
Table horizontal scrollbar appears by default, even when scrolling is not required

### ISSUE THREAD

**Issue by ian13262** [Esri/calcite-design-system#7892]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calcite-tables` always seem to have a horizontal scrollbar, even when scrolling is not required.

### Expected Behavior

We shouldn't see a scrollbar at all in these cases, correct?

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/table/

### Reproduction Steps

1.) See the example on the Calcite docs.
![image](https://github.com/Esri/calcite-design-system/assets/131201379/5d028c65-adee-4397-8f74-2cda9885eaa1)

### Reproduction Version

1.8.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
@ian13262 - could you provide the browser and OS you experienced this with?

**Comment by ian13262** [comment]
This was on Chrome on Windows 10. I'm seeing it on Microsoft Edge too: 
![image](https://github.com/Esri/calcite-design-system/assets/131201379/d9cc0e7f-05dd-4f6b-9064-f1f38668b983)

**Comment by geospatialem** [comment]
This looks to be a result of the `.table-container` class where the [`overflow-x-scroll`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/table/table.scss#L27) is defined. It is not displayed on Mac OS browsers (and skipped), but displays on Windows OS.

**Comment by geospatialem** [comment]
Verified in Windows on Chrome with [the following Codepen](https://codepen.io/geospatialem/pen/oNJmWWB) in `1.9.2-next.1`.
