### ISSUE TITLE
Improve layout for alert screenshot diffs

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7893]
### Test type

Chromatic

### Which Component(s)

alert

### PR skipped, if applicable

#

### Additional Info

Alert stories need some fine tuning to prevent them from being clipped:

### screenshot
![Screenshot 2023-09-27 at 3 53 03 PM](https://github.com/Esri/calcite-design-system/assets/197440/54c15a61-4646-45a2-9bf0-a4545e2cfa97)

### story
![Screenshot 2023-09-27 at 3 53 09 PM](https://github.com/Esri/calcite-design-system/assets/197440/32b24e7e-ad56-4690-9f62-bab87098f992)

cc @ashetland

**Comment by DitwanP** [comment]
🍡 Verified by comparing snapshots
