### ISSUE TITLE
Table - allow users to change column width

### ISSUE THREAD

**Issue by ian13262** [Esri/calcite-design-system#7894]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

`calcite-tables` should allow users to adjust the widths of columns to most optimally display header/cell content. This would be similar to how tables in Google Docs/Microsoft Word/etc. allow for dynamic sizing.

### Acceptance Criteria

Being able to adjust column widths manually in a `calcite-table` would allow users to tweak their tables' design based on changing content/word lengths in columns.

### Which Component

`calcite-table`

### Example Use Case

We want to avoid something like this from happening in smart mapping raster panels: https://codepen.io/iyouth66/pen/ExGLqjX?editors=100. If a word in a `calcite-table-cell` is too long, the table will exceed any set `max-width`. We can prevent this by using `overflow-wrap`, but then the table will shrink the other columns unnecessarily. It would be more ideal if we could adjust the column widths manually to fit everything as desired.

![image](https://github.com/Esri/calcite-design-system/assets/131201379/734ebd4e-0949-4399-b137-3a40e60ad91a)

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
Aside from using `col-span`, which works in some set ups, currently the way to achieve this would be to have each cell contain an element with an explicit width within the column you wish to constrain (and not have the table layout be "fixed"). In the future, we can probably expose css variables to control this. Further, we do hope to have "user-resizable" column widths with a visual affordance, but this is not immediately planned.


In the meantime, you can use the workaround above of setting the desired width on an element within the cell. Not ideal, but should work in a pinch. https://codepen.io/mac_and_cheese/pen/LYqmvzY?editors=1000

**Comment by macandcheese** [comment]
Implementation note: this is a _dev-user_ story, to adjust and set a width for column. It is separate from the _end-user_ story to, as a user, adjust the width of the column.

**Comment by macandcheese** [comment]
Implementation note: this is a dev-user story, to adjust and set a width for column. It is separate from the end-user story to, as a user, drag / adjust the width of the column.

**Comment by macandcheese** [comment]
Implementation note: this is a  _dev-user_ story, to adjust and set a static width for a column. It is separate from the _end-user_ story to, as a user, drag and adjust the width of the column.

**Comment by macandcheese** [comment]
Hi @jfelicianiats this would be the issue to track for progress updates for this specific feature. We do plan to deliver more Table functionality, with some follow ups, tracked as an epic here: https://github.com/Esri/calcite-design-system/issues/7630

As a workaround, you can set a defined width on elements inside the Table Cell, which will constrain the column width. Note, this won't work in `layout="fixed"`, and for exact width, you can adjust for the padding of a Table Cell in a given scale: https://codepen.io/mac_and_cheese/pen/LYqmvzY?editors=1000

**Comment by jfelicianiats** [comment]
@macandcheese Thanks for the update.  As a side note the proposed workaround doesn't work in all cases.  If you set a specific width on table cell content, it has a limit to how small the column will become.  The use case I need it for is where the column is just a short abbreviation I need to make a small pixel width so its not obtrusively large.  In your example, the table column for "Date / Time" won't shrink beyond roughly 130px.

**Comment by geospatialem** [comment]
The request above is now achievable in `2.10.1`, and Adam provided a use case example for defining custom column widths [above](https://github.com/Esri/calcite-design-system/issues/7894#issuecomment-1983973600) via https://codepen.io/mac_and_cheese/pen/LYqmvzY. Closing out the above.
