### ISSUE TITLE
Tree single-persist selection mode bugs

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7899]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`selection-mode="single-persist"` has multiple bugs:

- Allows for multiple selections
- Missing single-select indicator
- Likely related to 👆: nested indentations are incorrect

![CleanShot 2023-09-28 at 12 54 50](https://github.com/Esri/calcite-design-system/assets/108549080/fbfc4129-cd08-4ad1-9690-c2f7f5965b5e)

### Expected Behavior

- [x] Allows for single selection only
- [x] Has single select indicator
- [x] Nested indents match other modes

### Reproduction Sample

https://codepen.io/ashetland/pen/OJrEOzE

### Reproduction Steps

1. Open the codepen
2. Select multiple items in single-persist Tree

### Reproduction Version

v1.8.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Setting the priority as low, unless other users or teams are experiencing similar issues and Calcite team members will "up" the priority.

**Comment by geospatialem** [comment]
Verified in `2.9.0-next.22`
