### ISSUE TITLE
Tree single select doesn't allow deselection

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7900]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

After a selection has been made, that selection cannot be deselected.

![CleanShot 2023-09-28 at 13 06 11](https://github.com/Esri/calcite-design-system/assets/108549080/ed4f3c4f-fd79-440f-bee1-55a068d945f0)

### Expected Behavior

I would expect to be able to deselect the item. This would match the distinction between `single` and `single-persist` from other components.

### Reproduction Sample

https://codepen.io/ashetland/pen/MWZXOqW

### Reproduction Steps

Attempt to deselect an item after a selection has been made.

### Reproduction Version

v1.8.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Efforts should be coupled with https://github.com/Esri/calcite-design-system/issues/7899

**Comment by geospatialem** [comment]
Verified in `2.9.0-next.22`.
