### ISSUE TITLE
[Table] Rename `zebra` property to `striped` 

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7906]
### Description

This one slipped under the radar during build and review. We should probably use `striped` instead of `zebra` to better align with `bordered` nomenclature

### Proposed Advantages

Consistency of property name / tense.

### Which Component

Table

### Relevant Info

Deprecate `zebra` and add support for `striped` - remove support for `zebra` next breaking change release.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

**Comment by driskull** [comment]
👋 🦓

**Comment by jcfranco** [comment]
> Deprecate zebra and add support for striped - remove support for zebra next breaking change release.

If we're deprecating, we can remove the `breaking changes` label. From what I can tell, there only `zebra`-related style is this one, so we could keep it until the next, next breaking changes release. Current one is planned for November.

How likely is `zebra` to be used in current, supported use cases? I'm guessing it's quite common. 🦓

**Comment by macandcheese** [comment]
@jcfranco - yeah, feel free to update, we can add `striped`, deprecate `zebra`, and remove it ... later ™️

**Comment by geospatialem** [comment]
Verified on the `main` branch with the `striped` attribute. Also, the `zebra` attribute is still working to ensure deprecation/support. 🎉
