### ISSUE TITLE
[Tree] selected items should be empty in `none` selection mode

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7909]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When tree is in `selection-mode="none"`, it should emit the selection event, but not alter the `selectedItems` property. Doing so would be in line with the behavior introduced by `calcite-dropdown`.

### Expected Behavior

When an item is selected, the selection event is emitted, but `selectedItems` should be empty.

### Reproduction Sample

https://codepen.io/jcfranco/pen/vYvroZz?editors=1001

### Reproduction Steps

Click on any tree item and see the console show the selected items

### Reproduction Version

1.8.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.16`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/ed8dd66d-d246-4769-9fda-f4c36314fcbc)
