### ISSUE TITLE
[Action Bar/Action Menu] active actions in action bar are not active in collapsed menu

### ISSUE THREAD

**Issue by gopal-y** [Esri/calcite-design-system#7910]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When active property of calcite-action is being used and when the container is resized, the calcite actions are moved to menu-actions and are not shown as active. This can be observed when more than one calcite-action is active.

### Expected Behavior

If more than one calcite-action item is active, it should be reflected in the collapsed menu-items as well.

### Reproduction Sample

https://codepen.io/im-the-developer/full/qBLooXP

### Reproduction Steps

1. Open the code pen
2. select more than one calcite action in the first action-group
3. now drag the side shell-panel to reduce the width and trigger the overflow
4. now open the menu to see the text-enabled actions, only one or none of the calcite-actions reflect the active behavior

### Reproduction Version

1.4.2

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by gopal-y** [comment]
https://github.com/Esri/calcite-design-system/assets/30383517/dac1aa03-1e4f-4539-86d1-6237bb18726e

**Comment by driskull** [comment]
Valid. This is because the action menu uses the `active` property to highlight the currently active action. It should probably use another internal property to do this visual change because `active` can be defined by the user.

**Comment by geospatialem** [comment]
Verified with `1.9.0-next.16`

![verify-7910](https://github.com/Esri/calcite-design-system/assets/5023024/97a2cf09-5653-4b43-b8cc-d86d725ec450)
