### ISSUE TITLE
🎃 𝗛𝗮𝗰𝗸𝘁𝗼𝗯𝗲𝗿𝗳𝗲𝘀𝘁 𝗗𝗲𝘁𝗮𝗶𝗹𝘀 𝗳𝗼𝗿 𝗣𝗮𝗿𝘁𝗶𝗰𝗶𝗽𝗮𝗻𝘁𝘀 👨‍💻

### ISSUE THREAD

**Issue by cyatteau** [Esri/calcite-design-system#7917]
**Greetings and happy Hacktoberfest 2023!** 

We're thrilled that you've chosen to participate in Hacktoberfest with us! Please bear in mind that during the month of October 🎃, the volume of pull requests (PRs), comments, and other interactions may be higher than usual. Therefore, we kindly ask for your patience while awaiting responses. To increase the likelihood of a successful PR, please adhere to the following guidelines:

- Familiarize yourself with the repository by reading the README.md.
- Review and follow all the guidelines outlined in [CONTRIBUTING.md](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md).
- Is this your first time contributing? Check out this [list of issues](https://github.com/Esri/calcite-design-system/labels/good%20first%20issue) labeled "good first issue", specifically selected for those who are just getting started!  
- Be sure to follow all the best practices defined in the Calcite Components [conventions](https://github.com/Esri/calcite-design-system/tree/main/packages/calcite-components/conventions).
- When you receive feedback on your PR, incorporate the changes into the same PR rather than creating a new one.
- Ensure your PR has a descriptive title, as this will facilitate a smoother review process.

If you haven't already, please check out our [blog article](https://www.esri.com/arcgis-blog/products/developers/developers/join-hacktoberfest-2023-celebrate-open-source-with-us/) 📃, which contains valuable information, including a list of participating Hacktoberfest repositories and details about our contest 🏆 and rules. Additionally, consider joining our [Slack channel](https://join.slack.com/t/esridevevents/shared_invite/zt-23rorvdmp-0o9GKeRgSOirY5TV98A31w) to join in the fun, receive announcements, interact with maintainers, Esri employees, and fellow participants, and have a place to ask any questions you may have.

**Comment by geospatialem** [comment]
Thank you to everyone participating in Hacktoberfest 2023! 🎃🏆 

We hope to have you and your friends and colleagues join in contributions, and future Hacktoberfest's!

And a **special thank you and shotout** ✨  to our new contributors 🙌🏻 :
- @alhridoy with a refactor ♻️  for https://github.com/Esri/calcite-design-system/issues/7765
- @BrunoCaimar with a fix 🔨 for https://github.com/Esri/calcite-design-system/issues/7719
- @abp6318 with a fix 🔧 for https://github.com/Esri/calcite-design-system/issues/7710
