### ISSUE TITLE
[Alert] Responsive layout on xs screens for `actions-end` and multiple alerts

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7921]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When `alert` is viewed with small dimensions (<475px) if slotted `"actions-end"` contain a lot of `text` (and are enabled with `text-enabled`) and/or contain multiple alerts, the content spans outside of the component.

Opened from verifying https://github.com/Esri/calcite-design-system/issues/6673.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/34df5b9b-8623-4a33-82d6-93f6ca052855)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/26b00d05-632a-4596-ac4e-d8e2393a1a42)

### Expected Behavior

Exact design specs tbd for `"actions-end"` with `text` and `text-enabled`.

Original content from #6673: [Figma file](https://www.figma.com/file/eradSav1w0c4viNljdROKk/Alert---responsive-%5B6673%5D?node-id=519%3A12408&mode=dev)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a7def15e-ee12-4a8f-a9c5-001abcda9eb5)

### Reproduction Sample

https://codepen.io/geospatialem/pen/VwqGbMg

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/VwqGbMg)
2. [Optional] Click the "Add alert to queue" button at least one time
3. Observe the `alert`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a169b858-51ae-415a-8e11-3801dc169e04)

### Reproduction Version

1.9.0-next.16

### Priority impact

p2 - want for current milestone

### Impact

Seems moderate for prioritization. Applies to smaller screen sizes/dimensions, but advanced configurations will be impacted.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
This is assigned to me, but I think this needs a design pass to determine how to handle the overflowing text-enabled actions. cc @ashetland @SkyeSeitz

**Comment by SkyeSeitz** [comment]
Tagged @jcfranco & @ashetland in [Figma file](https://www.figma.com/file/Xa83FCtnb70ocCGc8Pk0qH/Alert---xs-breakpoint-actions-end-%5B7921%5D?type=design&node-id=1%3A2&mode=dev) with truncation or wrapping considerations depending on slot limitations.

**Comment by geospatialem** [comment]
Assigning development efforts to November 

cc @jcfranco for the [two options](https://github.com/Esri/calcite-design-system/issues/7921#issuecomment-1777669287) Skye mentioned above for consideration.

**Comment by SkyeSeitz** [comment]
Note affecting proposed Alert responsiveness:
The implementation of queue stacking ([issue](https://github.com/Esri/calcite-design-system/issues/2835) slated for January) solves the Alert responsiveness concern at small breakpoints. 

Currently, the queue Chip takes up a significant amount of horizontal real estate along side the text causing the responsive concern of an excessively tall Alert. But with the plans to move the queue to the outside of this container, even the large Alert at the xs breakpoint can house a reasonable amount of content without needing the layout change. 

<img width="612" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/09054778-90cb-474e-a6eb-ce9c0a468244">

**Comment by jcfranco** [comment]
Closing based on ☝️.
