### ISSUE TITLE
Collapsible Panel affordance corrections

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7930]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Panel's collapse button is reversed when compared to other components like Accordion and Block.

The `title` attribute and `aria-label` also don't match.

### Expected Behavior

The default orientation matches Accordion and Block. Proposing adding a `collapse-inverted` prop to replicate the current behavior.

<img width="808" alt="CleanShot 2023-10-03 at 15 49 59@2x" src="https://github.com/Esri/calcite-design-system/assets/108549080/e7ea0582-9db0-4d31-8157-50c45b458019">

### Reproduction Sample

https://codepen.io/ashetland/pen/jOXeOXK

### Reproduction Steps

Compare with Block and Accordion in the provided codepen.

### Reproduction Version

v1.9.0

### Relevant Info

cc @driskull @SkyeSeitz 

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
Do we need to allow this to be customized? Can we just have the default match the  other places this chevron is used?

**Comment by ashetland** [comment]
> Do we need to allow this to be customized? Can we just have the default match the other places this chevron is used?

Good question for @asangma and @driskull. I believe there thinking was there particular use case required it be inverted, but this may be adding unnecessary complication.

**Comment by driskull** [comment]
I don’t think it’s special to popover. It really applies to any component that is anchored at the bottom of something to where when expanded it goes up instead of down.

**Comment by SkyeSeitz** [comment]
Would we consider this similar to Action Bar's position prop to determine expand direction based on if it is anchored to the start or end?

**Comment by geospatialem** [comment]
Verified in `1.9.1-next.0`. 

@driskull do we need to flip the behavior for the `collapseDirection` prop values? It looks like the chevron is opposite the value.

### `collapseDirection="up"`:
![image](https://github.com/Esri/calcite-design-system/assets/5023024/61336c17-2b7d-46d8-bda6-3aaf4445893a)

### `collapseDirection="down"`:
![image](https://github.com/Esri/calcite-design-system/assets/5023024/f48741a9-ceac-4b25-a47d-a09a9741ad56)

**Comment by driskull** [comment]
This property is internal for now. Should we close this issue or keep it open for more research to be completed?

**Comment by ashetland** [comment]
I'm fine closing this.

**Comment by geospatialem** [comment]
Closing per https://github.com/Esri/calcite-design-system/issues/7930#issuecomment-1749477115 and https://github.com/Esri/calcite-design-system/issues/7930#issuecomment-1749481497.
