### ISSUE TITLE
Combobox - filtering combobox items and selecting by tap fails to update the selected item

### ISSUE THREAD

**Issue by ian13262** [Esri/calcite-design-system#7934]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Here is a very specific workflow in **1.9 only** that does not follow expected combobox behavior:

1.) Click to open a combobox with multiple selected items
2.) Filter the items by typing some input
3.) Choose a filtered item, but carefully! This item **must** be:
* **Not** in its original position in the list
* Selected by **tapping** a trackpad (and occasionally by clicking with a mouse, but this is variable)

4.) The new item will not be selected appropriately.

### Expected Behavior

The workflow above should correctly select that tapped item, but it doesn't.

### Reproduction Sample

https://codepen.io/iyouth66/pen/LYMgEOW

### Reproduction Steps

See above.

Demo: 
https://github.com/Esri/calcite-design-system/assets/131201379/4367da0a-936d-44e5-b685-8349a3df30fc

### Reproduction Version

1.9

### Relevant Info

Windows 10 (must use trackpad **tap** to reliably reproduce this issue); Chrome Version 117.0.5938.150 (Official Build) (64-bit)

_Note_: Also seems to apply to the Mac OS trackpad.

cc @geospatialem - hoping to have this for 1.9.1, if time permits.

### Regression?

1.8

### Priority impact

p1 - need for current milestone

### Impact

All comboboxes are affected, particularly `single-persist` ones (time-zone component, field selection, etc.).

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Possibly related to https://github.com/Esri/calcite-design-system/pull/7721. The above sample works as-expected in `1.8.0-next.0`, but shows starting at `1.8.0-next.1`.

**Comment by geospatialem** [comment]
Verified in `1.9.1-next.1` with Windows trackpad in Chrome `Version 117.0.5938.149 (Official Build) (64-bit)`
