### ISSUE TITLE
[Input Time Zone] Doesn't display in Firefox browsers and console errors are present

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7944]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The Maps SDK for JS Editor form relies on the Time Zone component, which doesn't display in `1.9.0`. There are also errors on the page:

> Uncaught (in promise) TypeError: format: expected string, got undefined
> createTimeZoneItems https://js.arcgis.com/calcite-components/1.9.0/p-fcc3a585.entry.js:6
> createTimeZoneItems https://js.arcgis.com/calcite-components/1.9.0/p-fcc3a585.entry.js:6

### Expected Behavior

Similar to `1.8.0`, the component displays and no console errors are present.

### Reproduction Sample

https://codepen.io/geospatialem/pen/zYyMrpY

### Reproduction Steps

1. Open https://codepen.io/geospatialem/pen/zYyMrpY with Firefox
2. _Contact Kitty for username/password_
3. Click on the Edit Features "Select"
4. Select a point to edit
5. Select one of the objects in the list
6. Open the browser console
7. Observe the behavior and errors of:

> Uncaught (in promise) TypeError: format: expected string, got undefined
> createTimeZoneItems https://js.arcgis.com/calcite-components/1.9.0/p-fcc3a585.entry.js:6
> createTimeZoneItems https://js.arcgis.com/calcite-components/1.9.0/p-fcc3a585.entry.js:6

### Reproduction Version

1.9.0

### Relevant Info

Seems specific to Firefox browsers

### Regression?

1.8.0

### Priority impact

p1 - need for current milestone

### Impact

Very high - impacts MapViewer and Maps SDK for JS teams in the upcoming release Monday.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
cc @rebollin @jonuihlein @hgonzago

**Comment by geospatialem** [comment]
Verified in `1.9.1-next.1` with Firefox.

**Comment by jcfranco** [comment]
For context, we reopened due to bug in certain time zone grouping scenario.

**Comment by geospatialem** [comment]
Verified in `1.9.2-next.3` with Firefox.
