### ISSUE TITLE
Button doubly faded when in both `disabled` and `loading` states

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#7950]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Enabling both `disabled` and `loading` attributes on a `<calcite-button>` element causes the button to appear twice as faded as it would if only one of those attributes was applied.

### Expected Behavior

Button has the same amount of fading regardless if one or both attributes are enabled.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/button/

### Reproduction Steps

1. Navigate to the documentation sample for the Button component
2. Enable the `loading` attribute and see button becomes faded
3. Enable the `disabled` attribute and see button becomes more faded
4. Disable the `loading` attribute and see the button becomes less faded

### Reproduction Version

1.9.0

### Relevant Info

Somewhat related to https://github.com/Esri/calcite-design-system/issues/7590 in that a workaround for that issue to supply both `disabled` and `loading` attributes.

### Priority impact

p4 - not time sensitive

### Impact

Inconsistent UI where some buttons can look more faded than others despite being semantically the same in terms of their disabled state.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by jcfranco** [comment]
This would take care of https://github.com/Esri/calcite-design-system/issues/6453.

**Comment by geospatialem** [comment]
Verified in `1.10.0-next.7` with https://codepen.io/geospatialem/pen/zYeGaWv

![image](https://github.com/Esri/calcite-design-system/assets/5023024/911046a7-b582-4a36-af7f-1bf1f184b837)
