### ISSUE TITLE
When a calcite-input has both required and a pattern, the browser form validation is not working

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7952]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a form is submitted, the pattern and required props are not being honored

### Expected Behavior

When submitting a form, if the input pattern is not validated and the input is required, browser validation notifies the end user.

### Reproduction Sample

https://codepen.io/driskull/pen/KKbraXv

### Reproduction Steps

1. Open the codepen
2. Click on the empty input
3. Hit enter
4. The form should not be submitted.

See native HMTL example: https://codepen.io/driskull/pen/bGOQgYB

### Reproduction Version

1.8.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
Our form components require setting `name` for them to participate in form submission.

**Comment by jcfranco** [comment]
We should explicitly call this out in the doc. cc @geospatialem

**Comment by driskull** [comment]
ah, yeah that isn't obvious but I remember that. Yeah lets highlight the doc more 👍

**Comment by geospatialem** [comment]
Added to the [Core concepts](https://developers.arcgis.com/calcite-design-system/core-concepts/) page, due for release tomorrow 10/26.

**Comment by geospatialem** [comment]
Verified on production on the new [Core concepts' Forms](https://developers.arcgis.com/calcite-design-system/core-concepts/#forms) section.
