### ISSUE TITLE
stepper: No stepper-item is selected when first stepper-item is disabled

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#7953]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If the first stepper-item is `disabled` then  no stepper-item is `selected` by default.

### Expected Behavior

If first `stepper-item` is selected, the next enabled `stepper-item` should be `selected`.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/bGOQgJr?editors=1100

### Reproduction Steps

1. Open the CodePen.
2. Observe that second `stepper-item` is not selected.

### Reproduction Version

1.9.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.10.0-next.7`.
