### ISSUE TITLE
[Input Time Zone] Offset of `-660` is ignored

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7957]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

1. The `input-time-zone` component no longer supports setting `value` as `-660` (as of `1.9.0`). In these cases the user's default time zone is returned to the component.
2. The UTC-12/GMT-12 doesn't have an associated location, and as a result is reverting to the user's time zone.

cc @JonUihlein @hgonzago 

### Expected Behavior

The component's `value` is supported across all time zones.

### Reproduction Sample

https://codepen.io/jonuihlein/pen/OJraWgM

### Reproduction Steps

1. Open the [sample](https://codepen.io/jonuihlein/pen/OJraWgM)
3. Observe the `value` at `-600` shows the expected value for `GMT-10`
4. Change the `value` to any value higher than `-600`, such as `-660` or `-720`
5. The change should bring up `GMT-11` and `GMT-12` respectively, but it does not
    - Instead, it updates to the user's time zone

### Reproduction Version

1.9.0

### Regression?

1.8.0

### Priority impact

p1 - need for current milestone

### Impact

Very high - impacts Online and Maps SDK for JS teams in the October releases.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
Pinpointed the issue and it's with `timezone-groups`. It's not creating the proper group for time zones that have an offset of -11. I'll take a closer look.

**Comment by jcfranco** [comment]
This should be addressed by https://github.com/Esri/calcite-design-system/pull/7962.

**Comment by jcfranco** [comment]
The above PR landed. @geospatialem Can you test once there's an update to `next`? 🙇

**Comment by geospatialem** [comment]
> The above PR landed. @geospatialem Can you test once there's an update to `next`? 🙇

This LGTM. 🌟  

cc @JonUihlein @hgonzago for additional testing, here's a [Codepen](https://codepen.io/geospatialem/pen/MWZLMLp) with `next` and the `value` set to `-660`.

**Comment by geospatialem** [comment]
Verified in https://codepen.io/geospatialem/pen/MWZLMLp with `1.9.2-next.3`, where `GMT-12` displays without a grouping:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/f866ea0f-7b54-4ce4-b054-05dd28c50c65)

**Comment by jcfranco** [comment]
@geospatialem Your screenshot reminded me that for GMT-12 specifically, the label might be confusing to users. It represents `Etc/GMT+12` which [intentionally uses the inverted sign](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List), but its offset is indeed -12. This is the only group where there is no other IANA time zone identifier with a region. We could tackle this in a separate issue if there's a clearer way to present this info. cc @ashetland

**Comment by ashetland** [comment]
> @geospatialem Your screenshot reminded me that for GMT-12 specifically, the label might be confusing to users. It represents `Etc/GMT+12` which [intentionally uses the inverted sign](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List), but its offset is indeed -12. This is the only group where there is no other IANA time zone identifier with a region. We could tackle this in a separate issue if there's a clearer way to present this info. cc @ashetland

We could look at possible improvements to the name mode as well.

**Comment by ashetland** [comment]
> @geospatialem Your screenshot reminded me that for GMT-12 specifically, the label might be confusing to users. It represents `Etc/GMT+12` which [intentionally uses the inverted sign](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List), but its offset is indeed -12. This is the only group where there is no other IANA time zone identifier with a region. We could tackle this in a separate issue if there's a clearer way to present this info. cc @ashetland

We could look at possible improvements to the name mode as well.
