### ISSUE TITLE
[input-date-picker] sometimes render the date incorrectly

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-design-system#7958]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calcite-input-date-picker` sometimes render the date incorrectly (see screenshot)

![MicrosoftTeams-image (1)](https://github.com/Esri/calcite-design-system/assets/44479773/79cce23b-b611-4c2e-94ae-26e016ff59c9)

### Expected Behavior

`calcite-input-date-picker` should always render the date correctly

### Reproduction Sample

~Have not been able to get it to happen in Codepen~

https://codepen.io/benesri/pen/YzdodgJ

### Reproduction Steps

I don't have a great set of repro steps.  Seem to happen randomly and inconsistently.  I'm seeing it in the metadata editor on devext.arcgis.com in Firefox, but it's not reproducible 100% of the time.

@jcfranco mentioned that @benelan may know the cause and might be able to generate a repro case.

### Reproduction Version

1.9.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by benelan** [comment]
Sorry for the delay, here is the repro sample:
https://codepen.io/benesri/pen/YzdodgJ

@jcfranco and I discussed and agreed on a solution, so when this issue gets triaged to a milestone please assign it to me. Thanks!

cc @geospatialem

**Comment by mcollins-GPI** [comment]
@benelan I thought I was going crazy! Is there any workaround for this that you have found? It looks like it will get fixed when it does.

**Comment by DitwanP** [comment]
🧁 Verified locally on `main`
