### ISSUE TITLE
[input-date-picker] Using range, 2nd input's dropdown icon shows first date-picker 

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-design-system#7965]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Clicking on the second dropdown icon (marked yellow) shows the date-picker underneath the first input element
![image](https://github.com/Esri/calcite-design-system/assets/25850072/847b18d9-5270-4b5b-a548-ed9a21e889f4)

Note that clicking on the second input-date-picker element itself shows the date-picker underneath the second input element.
Behavior occurs with vertical and horizontal layout.

### Expected Behavior

Clicking on the second dropdown icon (marked yellow) in the second input element shows the first date-picker underneath

### Reproduction Sample

See documentation (https://developers.arcgis.com/calcite-design-system/components/input-date-picker/)

### Reproduction Steps

1. Go the the [input-date-picker](https://developers.arcgis.com/calcite-design-system/components/input-date-picker/) documentation sample
2. Enable the range property. A second input element for an end date appears
3. Make sure the input elements are not active. Click somewhere outside the input-date-picker element(s). Active elements are blue bordered, like below:
![image](https://github.com/Esri/calcite-design-system/assets/25850072/3cdbfc2b-7cac-4c49-a22c-a6d5a78baec2)
4. Click on the dropdown icon in the second input element.
5. The date-picker components will appear underneath the first input element.

### Reproduction Version

1.9.0

### Regression?

`1.3.0`, likely from https://github.com/Esri/calcite-design-system/pull/6715

### Priority impact

p4 - not time sensitive

### Impact

The end user must select the input element itself to have the date-picker component appear.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Professional Services - Services Delivery

**Comment by abp6318** [comment]
Dropping a comment as we found this bug over on Hub Discovery as well and are hoping it can be bumped up in time sensitivity. We are looking to have this fixed for our current milestone. Also leaving this here: https://devtopia.esri.com/dc/hub/issues/8086

@thomas-hervey looks like this issue has been logged by another team already.

**Comment by geospatialem** [comment]
Thanks @arjanvanzutphen and @abp6318 - it looks like this was introduced in `1.3.0` from https://github.com/Esri/calcite-design-system/pull/6715 for some a11y improvements back in March. We haven't yet triaged this issue into a milestone, but we've got some full initiatives throughout the remainder of 2023. 

If we allocated this to early 2024, would that work time-wise with your teams?

**Comment by geospatialem** [comment]
This is still present as of `2.1.0-next.11` via https://codepen.io/geospatialem/pen/eYxqxYj, but seems to perform better than it had initially.

**Comment by DitwanP** [comment]
🍠 Verified locally on `main`
