### ISSUE TITLE
calcite-list: support same 'shift' selection support as calcite-value-lists and don't select filtered out items

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#7966]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

value-list supported using the shift key to select multiple rows at once. This does not work with the new list.

https://codepen.io/afreitag/pen/jOXdbwq

If value list has a filter applied and you do this shift key selection then it also selects the hidden items. This should be fixed in list, filtered out items should not get selected.

### Acceptance Criteria

I can select 10 rows at once by clicking on the first row and clicking on the 10th row while holding the shift key pressed. Filtered out items should not be selected in this case.

### Which Component

calcite-list

### Example Use Case

Map Viewer attributes component which used value-list so far. But value-list has an issue when selecting multiple rows at once while a filter is in place. It ignores the filter in this case and selects too many items.

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment]
This would be nice to add to Table as well.

**Comment by AdelheidF** [comment]
Looks goo to me in 2.0 as well. Thanks.
