### ISSUE TITLE
Editing max-length property in text-area sandbox causes tab to crash

### ISSUE THREAD

**Issue by abp6318** [Esri/calcite-design-system#7968]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Editing the `max-length` property on the component sandbox crashes the page

https://developers.arcgis.com/calcite-design-system/components/text-area/ 

### Expected Behavior

Max length should be applied to sandbox text-area input and prevent users from adding characters past that length.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/text-area/

### Reproduction Steps

1. Visit https://developers.arcgis.com/calcite-design-system/components/text-area/
2. Go to the sample header under overview
3. Open the properties tab
4. Scroll down the properties tab and set the max-length to any number
5. The page crashes

### Reproduction Version

N/A

### Relevant Info

MacOS on Chrome

### Priority impact

p4 - not time sensitive

### Impact

Isn't a huge impact to my team given we can still test the component locally or on other platforms, it just breaks in the documentation.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Hub

cc. @thomas-hervey - here's the ticket in case you want to keep track of it

**Comment by macandcheese** [comment]
This even happens when switching to the sample with the pre-defined `maxLength` - so just the presence of the property is causing an issue somehow. The component sample renders inside an iFrame... @anveshmekala this came up again, this seems to only happen with Text Area and `maxLength`...

**Comment by geospatialem** [comment]
Spike to confirm if solely with the doc site, and to close here in favor of the documentation repo.

**Comment by geospatialem** [comment]
A spike will be performed in April to determine next steps, refer to https://github.com/Esri/calcite-design-system/issues/7968#issuecomment-1789681197 for additional details.

**Comment by DitwanP** [comment]
🍡 Verified locally on `main`
