### ISSUE TITLE
Add calcite-design-tokens to Github issue templates

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#7977]
### Summary

Currently new issue creation does not include @esri/calcite-design-tokens in the list of packages.

Calcite package
Select the relevant [package(s)](https://github.com/Esri/calcite-design-system/tree/main/packages) related to the request.

[ ] @esri/calcite-components
[ ] @esri/calcite-components-react
[ ] @esri/eslint-plugin-calcite-components

### Desired Outcome

Calcite package
Select the relevant [package(s)](https://github.com/Esri/calcite-design-system/tree/main/packages) related to the request.

[ ] @esri/calcite-components
[ ] @esri/calcite-components-react
[ ] @esri/eslint-plugin-calcite-components
[ ] @esri/calcite-design-tokens

**Comment by geospatialem** [comment]
Verified in the following issue templates:
- [x] [bug](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=bug%2C0+-+new%2Cneeds+triage&projects=&template=bug.yml)
- [x] [a11y](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=a11y%2Cbug%2C0+-+new%2Cp+-+high%2Cneeds+triage&projects=&template=accessibility.yml)
- [x]  [enhancement](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=enhancement%2C0+-+new%2Cneeds+triage&projects=&template=enhancement.yml)
- [x] [refactor](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=refactor%2C0+-+new%2Cneeds+triage&projects=&template=refactor.yml)
