### ISSUE TITLE
Export js format from design-tokens

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#7986]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add a new format to the transformer config that can be used for generating documentation on the Calcite docsite.

#### CI Verification

After #8050 is merged, output for the Calcite Design Tokens for each platform (including JS and ES6) can be observed and verified in the .snapshot files. 

#### Local Verification

1. checkout the branch locally
2. run `npm run build` at root
3. all build processess should pass
4. observe `calcite-design-tokens/dist` now contains platform folders
5. observe the platform folders include `js` and `es6` folders which contain token files that are not empty and have the `.js` and `.ts` file extensions.
6. These files align to the [JSON](https://www.w3.org/TR/json-ld11/) spec

### Relevant Info

https://amzn.github.io/style-dictionary/#/formats?id=javascriptmodule
https://amzn.github.io/style-dictionary/#/formats?id=typescriptmodule-declarations

### Which Component

design-tokens

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- @esri/calcite-design-tokens

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Re-assigned to development to finalize the snapshot tests, anticipated for later this week.

**Comment by geospatialem** [comment]
@alisonailea It looks like #8050 hasn't been merged in yet, reassigning until the PR has been merged to verify.
