### ISSUE TITLE
[input-time-zone] Add translations for other supported IANA time zones

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8005]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Safari and Firefox have additional time zones returned from `Intl.supportedValuesOf("timeZone")` that need to be translated for the offset mode:

* `Africa/Asmara`
* `Africa/Timbuktu`
* `America/Argentina/Buenos_Aires`
* `America/Argentina/Catamarca`
* `America/Argentina/ComodRivadavia`
* `America/Argentina/Cordoba`
* `America/Argentina/Jujuy`
* `America/Argentina/Mendoza`
* `America/Atikokan`
* `America/Ensenada`
* `America/Indiana/Indianapolis`
* `America/Kentucky/Louisville`
* `America/Montreal`
* `America/Nuuk`
* `America/Rosario`
* `Asia/Chongqing`
* `Asia/Harbin`
* `Asia/Ho_Chi_Minh`
* `Asia/Kashgar`
* `Asia/Kathmandu`
* `Asia/Kolkata`
* `Asia/Tel_Aviv`
* `Asia/Yangon`
* `Atlantic/Faroe`
* `Atlantic/Jan_Mayen`
* `CET`
* `CST6CDT`
* `EET`
* `EST`
* `EST5EDT`
* `Etc/GMT+1`
* `Etc/GMT+10`
* `Etc/GMT+11`
* `Etc/GMT+12`
* `Etc/GMT+2`
* `Etc/GMT+3`
* `Etc/GMT+4`
* `Etc/GMT+5`
* `Etc/GMT+6`
* `Etc/GMT+7`
* `Etc/GMT+8`
* `Etc/GMT+9`
* `Etc/GMT-1`
* `Etc/GMT-10`
* `Etc/GMT-11`
* `Etc/GMT-12`
* `Etc/GMT-13`
* `Etc/GMT-14`
* `Etc/GMT-2`
* `Etc/GMT-3`
* `Etc/GMT-4`
* `Etc/GMT-5`
* `Etc/GMT-6`
* `Etc/GMT-7`
* `Etc/GMT-8`
* `Etc/GMT-9`
* `Europe/Belfast`
* `Europe/Kyiv`
* `Europe/Tiraspol`
* `Factory`
* `HST`
* `MET`
* `MST`
* `MST7MDT`
* `PST8PDT`
* `Pacific/Chuuk`
* `Pacific/Kanton`
* `Pacific/Pohnpei`
* `UTC`
* `WET`
* `Africa/Asmera`
* `America/Buenos_Aires`
* `America/Catamarca`
* `America/Cordoba`
* `America/Godthab`
* `America/Indianapolis`
* `America/Jujuy`
* `America/Kralendijk`
* `America/Louisville`
* `America/Lower_Princes`
* `America/Marigot`
* `America/Mendoza`
* `America/Santa_Isabel`
* `America/St_Barthelemy`
* `Arctic/Longyearbyen`
* `Asia/Calcutta`
* `Asia/Katmandu`
* `Asia/Rangoon`
* `Asia/Saigon`
* `Atlantic/Faeroe`
* `Europe/Bratislava`
* `Europe/Busingen`
* `Europe/Kiev`
* `Europe/Mariehamn`
* `Europe/Podgorica`
* `Europe/San_Marino`
* `Europe/Vatican`
* `Pacific/Ponape`
* `Pacific/Truk`

*Note*: time zones without an associated region/city might not need translating

### Acceptance Criteria

Time zones listed above are added to the translation bundle.

### Relevant Info

Blocked issues: https://github.com/Esri/calcite-design-system/issues/8698

### Which Component

`calcite-input-time-zone`

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
This should be improved by #10289, which introduced changes to use consistent, canonical time zones and maps deprecated ones to canonical zones.

I’ll need to check if the latest strings cover all translations for both `offset` and `region`modes.

**Comment by jcfranco** [comment]
I'm not quite sure about translating entries for the `name` mode though. Listing the region/location by itself doesn’t seem very useful as it will miss context if you are unfamiliar with the associated time zone. I’m also unsure about translating IANA time zones directly (e.g., `America/Cd_Juarez` ➡️ `America/Ciudad Juárez` or `America - Ciudad Juarez, America` 🤔).

With the new `region` mode, I’m leaning towards keeping `name` as is (listing [IANA time zone identifiers](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)) and recommending users to use `offset` or `region` if they need translated time zone-related information.

@ashetland @richiecarmichael @emmilaakso212 WDYT?

**Comment by ashetland** [comment]
Is it worth deprecating `name` in favor of `region`? Is there a use case that `name` serves that `region` does not?

**Comment by richiecarmichael** [comment]
> With the new `region` mode, I’m leaning towards keeping `name` as is...

I agree.

> Is it worth deprecating `name` in favor of `region`?

Not sure without user feedback. One idea is that `name` could revert to raw (un-localized) IANA strings and the new `region` mode would be for localized and grouped time zones.

**Comment by jcfranco** [comment]
> > Is it worth deprecating name in favor of region? 
>
> Not sure without user feedback. 

Agreed, we could keep it for a a while and gauge feedback.

> One idea is that name could revert to raw (un-localized) IANA strings and the new region mode would be for localized and grouped time zones.

Do you mean as a doc/recommendation update or are you suggesting a tweak in functionality? The "revert" part threw me off. 😅

**Comment by jcfranco** [comment]
@richiecarmichael and I had a quick chat on ☝️ and we're both in agreement that `name` would be a better fit for use cases where the exact time zone identifier would be displayed (e.g., system administrator). If there's no objection, I can tweak the `name` mode to no longer replaces underscores with spaces from time zone item labels and display them as is.

**Comment by jcfranco** [comment]
> I’ll need to check if the latest strings cover all translations for both offset and region modes.

Confirmed! Similar to #8112, this should be fixed by #10289. cc @geospatialem @DitwanP

**Comment by jcfranco** [comment]
@geospatialem @DitwanP Sorry for the false alarm. 😅 This still needs `mode=name` to display time zone labels as is (IANA spec, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).

**Comment by geospatialem** [comment]
Verified with `3.0.0-next.42` in Firefox: https://codepen.io/geospatialem/pen/wBwKwwE with `mode` of `"offset"` and `"name"`.

_Note: There is a 🐛 with Chrome opened with https://github.com/Esri/calcite-design-system/issues/10895, where a [Chromium issue](https://issues.chromium.org/issues/381620359) has been logged to mitigate._
