### ISSUE TITLE
Investigate and leverage a github action to list contributors

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8010]
### Summary

We should acknowledge contributors to the project by listing them in the readme.

### Desired Outcome

Contributors are listed in the readme along with their profile photo, link to their GitHub, etc.

### Resources

Potential actions:

https://github.com/marketplace?category=&type=actions&verification=&query=contributor

**Comment by geospatialem** [comment]
Would be a nice to have to have this available to showcase contributors from Hacktoberfest, at the conclusion of October.

**Comment by driskull** [comment]
This one seems to be the most popular and best fits the use case: https://github.com/marketplace/actions/contribute-list

This one is made by Github, however the use case might not be the desired one: https://github.com/marketplace/actions/contributors-action

**Comment by DitwanP** [comment]
🍡 Verified

**Comment by geospatialem** [comment]
It doesn't look like the [list of contributors](https://github.com/Esri/calcite-design-system?tab=readme-ov-file#contributors) is being populated, reopening for further investigation

**Comment by DitwanP** [comment]
Will keep an eye out for the next run of the "Update Contributors" action in order to verify, but since we wont have a release for a while I'll move this to `verified` and close out for now.
