### ISSUE TITLE
Calcite-notice - Consider replacing eyeball with "Do not show again" checkbox"

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-design-system#8027]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

In calcite-notice, clicking the eyeball is required to ensure the message is not seen again. This is not really intuitve and many users are clicking the x, expecting that will fully dismiss the notice from showing again. 

![image](https://github.com/Esri/calcite-design-system/assets/50747646/d941cbec-2e9b-4c36-860d-e2d86313e081)

It has been suggested that a checkbox with "Do not show again" or similar might be more conventional / intuitve. 

### Acceptance Criteria

It has been suggested that a checkbox with "Do not show again" or similar might be more conventional / intuitve. 

### Which Component

calcite-notice

### Example Use Case

ArcGIS Online

### Priority impact

p2 - want for current milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment]
@zaramatheson this is a product-specific implementation and not something Calcite Alert provides by default. I do agree the screenshot / eyeball  to "dismiss and not show again" is a confusing pattern.

You could use the `description` or `link` slot to build something like this, but the "persist the setting" would be up to the app: https://codepen.io/mac_and_cheese/pen/zYyVQaL?editors=1000

**Comment by macandcheese** [comment]
@zaramatheson this is a product-specific implementation and not something Calcite Alert provides by default. I do agree the pattern shown in screenshot / 'eyeball  to "dismiss and not show again"' is confusing.

You could use the `description` or `link` slot to build something like this, but the "persist the setting" would be up to the app: https://codepen.io/mac_and_cheese/pen/zYyVQaL?editors=1000

**Comment by zaramatheson** [comment]
Thanks @macandcheese OK we will take a look at this on our end. Appreciate the codepen!

**Comment by macandcheese** [comment]
Sounds good @zaramatheson - I'm going to close this but please reach out or open another issue with anything else that comes up!
