### ISSUE TITLE
Support "Infinity" for calcite-input component

### ISSUE THREAD

**Issue by itsminj** [Esri/calcite-design-system#8032]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Can there be support added for parsing `Infinity` for the `max` value of `calcite-input` and `-Infinity` for the `-min` value?

In the codepen below, it shows an error in the console if it tries to parse `Infinity`
https://codepen.io/mjkim12/pen/WNPeNQj

I see another issue, but it requests "Infinity" for `calcite-input-number`:
https://github.com/Esri/calcite-design-system/issues/7866

### Acceptance Criteria

Allow "infinity" and "-Infinity" to be parsed for its `max` and `min` values, respectively

### Which Component

calcite-input

### Example Use Case

https://codepen.io/mjkim12/pen/WNPeNQj

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Web Analysis

**Comment by benelan** [comment]
What is the use case for setting min to -Infinity or max to Infinity? Isn't it equivalent to not setting min or max?

**Comment by jcfranco** [comment]
@itsminj We'll proceed to close this due to inactivity. Please feel free to reopen if there's additional information regarding the use case.
