### ISSUE TITLE
List Item Group

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#8039]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Some UI enhancement requests for ListItemGroup.

## Background color and hover states
ListItemGroup uses foreground-2. This can conflict with anything that use ui-background. It also makes for weird hover states. Suggest foreground-1 or even transparent.

### Current
![background color problem](https://github.com/Esri/calcite-design-system/assets/12503298/d4580c59-e770-4f9f-bb79-a47c3e6870de)

### Current hover state
![background color hover problem](https://github.com/Esri/calcite-design-system/assets/12503298/5b56194a-dee4-4e3f-9c42-1e25dc689e38)

### Using foreground-1 or transparent
![background color suggestion](https://github.com/Esri/calcite-design-system/assets/12503298/871a2b8b-345b-488a-a05e-3ad995c57572)

![background color hover solution](https://github.com/Esri/calcite-design-system/assets/12503298/4347d575-0ffd-4512-8a0a-6f0eda3401f1)

## Alignment
Labels don't align. This might be from the selection border?
![alignment](https://github.com/Esri/calcite-design-system/assets/12503298/c42f8062-dfbb-4c8c-b234-5f713ddd57b2)

## Caret spacing
It appears that the spacing is 1rem start and 0.75rem end. Visually, this feels imbalanced.

![caret spacing](https://github.com/Esri/calcite-design-system/assets/12503298/da12d4a2-a326-4450-b0e1-405de474d098)

## Expand/collapse versus selection
The hit area for expand/collapse versus selection is confusing. Suggest visually distinguishing between the two hover states.

![expands hit](https://github.com/Esri/calcite-design-system/assets/12503298/4115e55f-fe7c-402d-85cf-d4f4f63923d8)

This may require updating the "invisible" selection border color on hover.

### Acceptance Criteria

Not breaking stuff.

### Which Component

List Item Group

### Example Use Case

SDK LayerList, BasemapLayerList, and TableList.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by asangma** [comment]
cc @driskull

**Comment by macandcheese** [comment]
From a UI standpoint, IMO the List Item Group is an extremely heavy element, the combination of vertical height and font weight make these Lists quite ... large. I guess this applies to the items themselves, not just the groups. Maybe we can look to reduce the height of all of these by a bit. Over an entire UI this could be a drastic improvement.

**Comment by asangma** [comment]
@macandcheese Agreed! :)

**Comment by ashetland** [comment]
This [Figma file](https://www.figma.com/file/91sfHrYNt0Il6B4pEZZ749/List-spacing%2C-sorting%2C-group-heading-%5B7100%5D-%5B8039%5D-%5B8242%5D-%5B8667%5D?type=design&node-id=982%3A37071&mode=dev) covers designs for this issue and multiple related design revisions for List. cc @driskull

**Comment by DitwanP** [comment]
🍯 Verified on `2.8.0-next.10`
