### ISSUE TITLE
Add Input Message to form components for form validation

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#8057]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

We are in the process of improving our form validation story. One of the items is to replace the native validation message UI with `calcite-input-message` (#8000). First wee need to add an Input Message to our form components.

### Acceptance Criteria

- Add a `calcite-input-message` to our form components, which will display under the internal  element. 
- Add `validation-message` and `validation-icon` properties so users can change the message's values on their end.
- Investigate adding a way to adjust spacing between the internal form element and the input-message via a CSS variable.

### Which Component

The following input components need an internal input-message, and a `status` property if they don't have one.

- [x] combobox
- [x] input-time-zone
- [x] input-date-picker
- [x] input-number
- [x] input-text
- [x] input-time-picker
- [x] input
- [x] text-area

The following have the `required` property, which means they will need a validation message displayed via #8000.

- [x] select
- [x] checkbox [2]
- [x] radio-button-group [1]
- [ ] slider [1]
- [ ] rating [1] [3]
- [x] segmented-control [1] [3]

> [1]: needs design for `status` prop due to different UI than the "input components" listed above.
> [2]: needs design for internal `input-message` due to potential spacing issues
> [3]: `required` prop is marked as `internal` in #2777 pending design. Can be made public as part of this issue.

The following don't need an internal `input-message` for #8000 because they don't have any [constraint validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation) properties. Should they receive an internal `input-message` anyway? If so, do they need a `status` property as well?

- [ ] switch
- [ ] meter

### Example Use Case

Form validation and other help messages.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by benelan** [comment]
> @ashetland, @SkyeSeitz - I updated the issue body, but TLDR; the following components needs designs for the `status` property:
> 
> * `slider`
> * `radio-button-group`
> * `rating`
> * `segmented-control`
> 
> 
> Not sure where the invalid coloring should be applied for slider. Just the handle? Or the whole slider?
> 
> And then the other three all have child elements and I'm not sure how design wants the invalid styling, especially with focus.
> 
> `checkbox` needs design for the internal input message. Should the input-message be under the component, or inline? I feel like either would potentially break existing apps.
> 
> And then `switch` and `meter` do not need the `status` property and internal input-message for the validation work in #8000, but I'd like design feedback on whether they should be added anyway for consistency across all form components.

Added the `design` label to this issue and assigned designers for the above items. Let me know if I can answer any questions from my end. Thanks!

cc @geospatialem @brittneytewks

**Comment by benelan** [comment]
The following components were [installed](https://github.com/Esri/calcite-design-system/pull/8305) and [verified](https://codepen.io/benesri/pen/NWoQmmd?editors=1000) on `2.1.0-next.12`.

- combobox
- input-date-picker
- input-number
- input-text
- input-time-picker
- input-time-zone
- input
- select
- text-area

The following components are waiting for `status` property designs:

- slider
- radio-button-group
- rating
- segmented-control

The following components are waiting for validation message placement designs:

- checkbox

**Comment by SkyeSeitz** [comment]
[Figma link ](https://www.figma.com/file/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?type=design&node-id=991%3A94553&mode=dev)to the following specs:  

Checkbox
- Add invalid styling
- `validationMessage` can be part of Checkbox Group if built in the future

Slider
- No invalid styling required 
- Add `validationMessage`

Radio Button Group
- No invalid styling required
- Add `validationMessage`

Rating
- No invalid styling required 
- Add `validationMessage`

Segmented Control
- No invalid styling required 
- Add `validationMessage`
- Q: Is the required prop applicable since it should always have a selected item?

**Comment by jcfranco** [comment]
> Segmented Control
> 
> ...
> Q: Is the required prop applicable since it should always have a selected item?

Segmented control follows the [radio group pattern](https://www.w3.org/WAI/ARIA/apg/patterns/radio/), which does allow for none of the items to be selected initially (we have a [test for this use case](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/segmented-control/segmented-control.e2e.ts#L104) as well), so I think `required` is applicable from that perspective.

**Comment by driskull** [comment]
The latest comment says that rating and slider should have a validationMessage property? is that still the case? should there be an issue?

**Comment by SkyeSeitz** [comment]
From my memory, they should have a validationMessage prop to go with its required prop. Since invalid styling is not really effective on these components, the validationMessage prop would serve as the only visual invalid affordance.

**Comment by driskull** [comment]
Should we reopen this one or create a new one? @geospatialem @DitwanP
