### ISSUE TITLE
Add min/max to input time picker (like date picker)

### ISSUE THREAD

**Issue by JonUihlein** [Esri/calcite-design-system#8065]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add `min` and `max` properties to `<calcite-input-time-picker>` that act like the `min` and `max` properties on `<calcite-input-date-picker>`. I don't think `minAsDate` or `maxAsDate` make much sense for times, so all we need is `min` and `max`. 

Right now, we have to do our own validation for times in a given range, when this is handled automatically for us in the date picker.

### Acceptance Criteria

`min` and `max` properties added to `<calcite-input-time-picker>`

### Which Component

calcite-input-time-picker

### Example Use Case

Same use-case as `<calcite-input-date-picker>` which already has these properties. 

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by nwhittaker** [comment]
Also interested in this for Field Maps.

**Comment by DitwanP** [comment]
🍍 Verified https://codepen.io/benelan/pen/VwOGwZy?editors=1010
