### ISSUE TITLE
Combobox chevron is wrong size at `scale="l"`

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#8067]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Large scale Combobox uses a small scale chevron (16px).

### Expected Behavior

To match the rest of the system, it should be using a medium scale chevron (24px).

### Reproduction Sample

https://codepen.io/ashetland/pen/NWoGaoE?editors=1000

### Reproduction Steps

1. Open the codepen
2. Make a selection
3. Note the size of the x icons vs the chevron

### Reproduction Version

v1.9.2

### Relevant Info

cc @jcfranco 

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on `main` when the `combobox` is set to `scale` of `"large"`.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/8b777003-90a0-4043-94b7-2cfffd0ebb39)
