### ISSUE TITLE
Input: When typing after a validation error the typed in value is not shown

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8072]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When typing after a validation error the typed in value is not shown until another tab or form submission

### Expected Behavior

When a validation occurs and a user starts typing, the typed in value is displayed in the input immediately

### Reproduction Sample

https://codepen.io/driskull/pen/PoVZPWd?editors=1000

### Reproduction Steps

1. Open the codepen
2. Select username input
3. Hit enter without typing anything in
4. Start typing in a value
5. Value is not shown until tab or submit occurs the second time

### Reproduction Version

1.9.2

### Regression?

No

### Priority impact

p3 - want for upcoming milestone

### Impact

Usability/UX

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment]
@jcfranco my guess is that the hidden form input is getting focus after a validation occurs. Can we listen for any key event on the hidden input to return focus where it should be?

**Comment by DitwanP** [comment]
🍰 Verified locally on `main`
