### ISSUE TITLE
Improve doc formatting and add examples to commonTest utils

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#8079]
### Description

Enhance the documentation of the `commonTest utilities` by incorporating examples and cleaning up the formatting, similar to the illustration provided below.

```
/**
 * Helper for asserting slots.
 *
 * Note that this helper should be used within a describe block.
 *
 * @example
 * describe("slots", () => {
 *    slots("calcite-stack", SLOTS)
 * })
 *
 * @param {string} componentTagOrHTML - The component tag or HTML markup to test against.
 * @param {Record<string, string> | string[]} slots - A component's SLOTS resource object or an array of slot names.
 * @param {boolean} includeDefaultSlot - When true, it will run assertions on the default slot.
 */
export function slots(
```

### Proposed Advantages

Readability and ease of use.

### Which Component

commonTest utilities

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
I believe this is now complete based on current state of [test helpers](https://github.com/Esri/calcite-design-system/tree/main/packages/calcite-components/src/tests/commonTests) (thanks @Elijbet!).

Closing!
