### ISSUE TITLE
Add a fixer to custom ESLint rule to place `ref` last along with the ignore doc line and explainer

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#8080]
### Description

Follow-up to #7669 #7659.

We added a custom ESLint rule to provide a more granular prop ordering mechanism by forcing the `ref` attribute to be kept as the last property so we can ensure it is up-to-date.

The new rule warns but still requires us to apply the fix ourselves (add last along with the ignore doc line and explainer).

We need to add a fixer to ensure the `ref` is the last prop automatically and to add the ignore prop-sorting rule for that line. 
 

### Proposed Advantages

less manual work

### Which Component

custom ESLint rule

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [X] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍡 Verified on `main`
