### ISSUE TITLE
Make Dropdown Group not required 

### ISSUE THREAD

**Issue by Anastasiia-Boleiko** [Esri/calcite-design-system#8081]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

According to the [Calcite Dropdown ](https://developers.arcgis.com/calcite-design-system/components/dropdown/)docs: 

> Every [Dropdown Item](https://developers.arcgis.com/calcite-design-system/components/dropdown-item/) must have a parent [Dropdown Group](https://developers.arcgis.com/calcite-design-system/components/dropdown-group/).

However, in many cases, this grouping is not needed. Especially, when it comes to a short menu list where grouping is not needed, such a label is excessive. Using Dropdown Items without a Dropdown Group leads to a11y issues.

### Acceptance Criteria

A Dropdown Item is not required to have a parent Dropdown Group and could be a child of a direct child of a Calcite Dropdown.

### Relevant Info

This is a huge barrier to use this component across our app.

### Which Component

Calcite Droprown

### Example Use Case

https://codepen.io/anastasiia-zrh/pen/rNPxXVy?editors=1000

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Urban

**Comment by macandcheese** [comment]
> such a label is excessive.  
You don’t need to set ‘group-title’ at all if you don’t want a displayed label. 

Without ’group-title’ set, Dropdown Group provides selection mode and handles keyboard navigation, with no visual label.

Does that work for your use case? Keeping selection mode property at the Dropdown Group level allows multiple types of selection, which happens often enough.

**Comment by macandcheese** [comment]
> such a label is excessive.  
It’s not a required property - so you don’t need to set ‘group-title’ at all if you don’t want a displayed label. 

Without ’group-title’ set, Dropdown Group provides selection mode and handles keyboard navigation, with no visual label.

Does that work for your use case?

**Comment by macandcheese** [comment]
> such a label is excessive.  

It’s not a required property - there’s no need to set ‘group-title’ at all if you don’t want a displayed label. 

Without ’group-title’ set, Dropdown Group provides selection mode and handles keyboard navigation, with no visual label.

Does that work for your use case?

**Comment by macandcheese** [comment]
Apologies, I thought I had added Codepen, sorry for any confusion!

You need to use the Dropdown Group component but you do not need to set ‘group-title”. 

Does this work? On my end it works correctly w/r/t focus and keyboard navigation. 

https://codepen.io/mac_and_cheese/pen/NWoNjzw?editors=100

**Comment by Anastasiia-Boleiko** [comment]
@macandcheese Thanks a lot! That works well👍 Sorry for misunderstanding.
