### ISSUE TITLE
[tabs] Tab content scrollbar is cut off when tabs have a set height

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#8091]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If the tabs component has a fixed height and the tab content needs to scroll, the scrollbar gets cut off, and the down arrow in some scroll bars is not clickable

<img width="609" alt="Screenshot 2023-10-31 at 8 08 16 AM" src="https://github.com/Esri/calcite-design-system/assets/5892789/40e8066d-675a-4150-adee-a6d5ee93cfaf">

### Expected Behavior

The whole scroll bar is displayed

### Reproduction Sample

https://codepen.io/mpayson/pen/abXZoqX

### Reproduction Steps

1. Open the code pen
2. If scroll bars are always visible on your machine, see the scrollbar is cut off
3. If scroll bars are not always visible, try scrolling the tab content and see the scrollbar is cut off

### Reproduction Version

1.1.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by eriklharper** [comment]
I verified this on calcite next (latest main) and #8399 appears to have fixed this issue as well.  I tested Chrome, Firefox and Safari latest on macos and they all show the scrollbar in its entirety.  I would screenshot the result I'm seeing if I could, but doesn't seem modern browser versions let you persist the scrollbar in scrollable regions anymore.

**Comment by DitwanP** [comment]
🍫 Verified, basically the same info that Erik mentions above.
