### ISSUE TITLE
List DragEvent should type the dragged element correctly

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8111]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Enhance the `` event to properly type the dragged element types to HTMLCalciteListItemElement

`@Event({ cancelable: false }) calciteListOrderChange: EventEmitter<DragDetail>;`

```ts
export interface DragDetail {
  toEl: HTMLElement;
  fromEl: HTMLElement;
  dragEl: HTMLElement;
  newIndex: number;
  oldIndex: number;
}

```

### Acceptance Criteria

DragEvent details for HTML elements are properly typed

### Which Component

Calcite-list

### Example Use Case

N/A

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.3` with the `calciteListOrderChange`'s event detail (`evt.detail.toEl` and `evt.detail.fromEl`).
