### ISSUE TITLE
[Input Time Zone] Time zones - Add missing and remove obsolete

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-design-system#8112]
### Check existing issues
- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

This issue is similar to #8005. However many of the time zones listed are obsolete.

### Actual Behavior
There are 351 [canonical](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#Type) IANA time zones. Calcite is currently references 429 time zones, of which 133 are obsolete. Calcite is also missing 27 time zones as listed below.

#### The following times zones are missing from `Input Time Zone`:
America/Argentina/Buenos_Aires
America/Argentina/Catamarca
America/Argentina/Cordoba
America/Argentina/Jujuy
America/Argentina/Mendoza
America/Indiana/Indianapolis
America/Kentucky/Louisville
America/Nuuk
Asia/Ho_Chi_Minh
Asia/Kathmandu
Asia/Kolkata
Asia/Yangon
Atlantic/Faroe
CET
CST6CDT
EET
EST
EST5EDT
~Etc/GMT
Etc/GMT+1
Etc/GMT+10
Etc/GMT+11
Etc/GMT+12
Etc/GMT+2
Etc/GMT+3
Etc/GMT+4
Etc/GMT+5
Etc/GMT+6
Etc/GMT+7
Etc/GMT+8
Etc/GMT+9
Etc/GMT-1
Etc/GMT-10
Etc/GMT-11
Etc/GMT-12
Etc/GMT-13
Etc/GMT-14
Etc/GMT-2
Etc/GMT-3
Etc/GMT-4
Etc/GMT-5
Etc/GMT-6
Etc/GMT-7
Etc/GMT-8
Etc/GMT-9
Etc/UTC~
Europe/Kyiv
Factory
HST
MET
MST
MST7MDT
PST8PDT
Pacific/Kanton
WET

#### The following time zones are obsolete and probably should be removed. See [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#Type) for explanation.
Africa/Accra
Africa/Addis_Ababa
Africa/Asmera
Africa/Bamako
Africa/Bangui
Africa/Banjul
Africa/Blantyre
Africa/Brazzaville
Africa/Bujumbura
Africa/Conakry
Africa/Dakar
Africa/Dar_es_Salaam
Africa/Djibouti
Africa/Douala
Africa/Freetown
Africa/Gaborone
Africa/Harare
Africa/Kampala
Africa/Kigali
Africa/Kinshasa
Africa/Libreville
Africa/Lome
Africa/Luanda
Africa/Lubumbashi
Africa/Lusaka
Africa/Malabo
Africa/Maseru
Africa/Mbabane
Africa/Mogadishu
Africa/Niamey
Africa/Nouakchott
Africa/Ouagadougou
Africa/Porto-Novo
America/Anguilla
America/Antigua
America/Aruba
America/Blanc-Sablon
America/Buenos_Aires
America/Catamarca
America/Cayman
America/Coral_Harbour
America/Cordoba
America/Creston
America/Curacao
America/Dominica
America/Godthab
America/Grenada
America/Guadeloupe
America/Indianapolis
America/Jujuy
America/Kralendijk
America/Louisville
America/Lower_Princes
America/Marigot
America/Mendoza
America/Montreal
America/Montserrat
America/Nassau
America/Nipigon
America/Pangnirtung
America/Port_of_Spain
America/Rainy_River
America/Santa_Isabel
America/St_Barthelemy
America/St_Kitts
America/St_Lucia
America/St_Thomas
America/St_Vincent
America/Thunder_Bay
America/Tortola
America/Yellowknife
Antarctica/DumontDUrville
Antarctica/McMurdo
Antarctica/Syowa
Antarctica/Vostok
Arctic/Longyearbyen
Asia/Aden
Asia/Bahrain
Asia/Brunei
Asia/Calcutta
Asia/Katmandu
Asia/Kuala_Lumpur
Asia/Kuwait
Asia/Muscat
Asia/Phnom_Penh
Asia/Rangoon
Asia/Saigon
Asia/Vientiane
Atlantic/Faeroe
Atlantic/Reykjavik
Atlantic/St_Helena
Australia/Currie
Europe/Amsterdam
Europe/Bratislava
Europe/Busingen
Europe/Copenhagen
Europe/Guernsey
Europe/Isle_of_Man
Europe/Jersey
Europe/Kiev
Europe/Ljubljana
Europe/Luxembourg
Europe/Mariehamn
Europe/Monaco
Europe/Oslo
Europe/Podgorica
Europe/San_Marino
Europe/Sarajevo
Europe/Skopje
Europe/Stockholm
Europe/Uzhgorod
Europe/Vaduz
Europe/Vatican
Europe/Zagreb
Europe/Zaporozhye
Indian/Antananarivo
Indian/Christmas
Indian/Cocos
Indian/Comoro
Indian/Kerguelen
Indian/Mahe
Indian/Mayotte
Indian/Reunion
Pacific/Enderbury
Pacific/Funafuti
Pacific/Johnston
Pacific/Majuro
Pacific/Midway
Pacific/Ponape
Pacific/Saipan
Pacific/Truk
Pacific/Wake
Pacific/Wallis

### How to translate `"Etc/GMT[+/-nn]"`?
See [here](https://devtopia.esri.com/WebGIS/arcgis-js-api/blob/828145e1c7c5e9e3c0e50e545118bddde94abc3b/esri/widgets/TimeZoneLabel.tsx#L230-L232) for a technique how to use Intl to derive the localized equivalent of `GMT+/-nn`.

### Reproduction Steps
1. Scraped a list of canonical time zones from [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
2. Compared scraped list of time zones with calcite's t9n files using [this](https://comparetwolists.com/).

### Reproduction Version
1.10.0

### Regression?
No

### Priority impact
p3 - want for upcoming milestone

### Impact
Fairly minimal. However the following national capitals are currently absent.
America/Argentina/Buenos_Aires
Asia/Ho_Chi_Minh
Asia/Kathmandu
Asia/Yangon
Europe/Kyiv

### Calcite package
- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team
ArcGIS Maps SDK for JavaScript

// @jcfranco

**Comment by jcfranco** [comment]
Related, external, issue (for the obsolete removal part): https://github.com/jcfranco/timezone-groups/issues/1

**Comment by fendiaoxiaoshuazi** [comment]
Also for the `Urumqi ` the official time zone should be +8.

Calcite input time zone:
<img width="667" alt="image" src="https://github.com/Esri/calcite-design-system/assets/26078106/bc1a0fe4-39e0-4d7d-956a-7a5a266d4ad5">

Scene viewer:
<img width="356" alt="image" src="https://github.com/Esri/calcite-design-system/assets/26078106/dfc3e13a-e08f-491a-93c4-c2ac878d130a">

**Comment by richiecarmichael** [comment]
Per [IANA](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#URUMQI), `"Asia/Urumqi"` is GMT+6 year-round. [This](https://en.wikipedia.org/wiki/Xinjiang_Time) wiki page describes how and why both Urumqi Time (GMT+6) and Beijing Time (GMT+8) are observed in the Xinjiang region.

**Comment by fendiaoxiaoshuazi** [comment]
Hi @richiecarmichael, on the Microsoft Date & TIme settings panel, Urumqi still appears as UTC +8. I think both cases are used, so I only add this comment for your reference.
![image](https://github.com/Esri/calcite-design-system/assets/26078106/824601cb-d3f4-4720-8a3d-7bd9af1f0316)

**Comment by jcfranco** [comment]
The changes required by `timezone-groups` _might_ be breaking, so it might be good to move this one to target our breaking change release. cc @geospatialem

**Comment by jcfranco** [comment]
This should be handled by #10289 as it made changes to use consistent, canonical time zones and also maps deprecated time zones to canonical ones. Thus, it should no longer be considered a breaking change.

**Comment by DitwanP** [comment]
🍡 Verified
