### ISSUE TITLE
calcite-button, when using a link and setting disabled to true, the anchor tag gets a disabled property

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8140]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The anchor tag in the shadow DOM gets a disabled property set when it shouldn't

### Expected Behavior

```jsx
aria-disabled={childElType === "a" && (this.disabled || this.loading)}
disabled={childElType === "button" && (this.disabled || this.loading)}
```

### Reproduction Sample

https://codepen.io/driskull/pen/eYxvYMM

### Reproduction Steps

1. Open the codepen
2. Check inside the shadowDom
3. The anchor link has a disabled property
4. disabled is not a valid property on an anchor link.

### Reproduction Version

1.10

### Priority impact

p2 - want for current milestone

### Impact

A11y

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
Verified locally on `Main`
