### ISSUE TITLE
Split Button - consistent divider across appearances 

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#8142]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The vertical divider in Split Button should visually match across appearance values.

### Acceptance Criteria

See [Figma file](https://www.figma.com/file/hDaUTLscr9X7xeNygsAQIu/Split-Button---consistent-divider-across-appearances?type=design&node-id=501-3613&mode=dev). `outline` and `outline-fill` are updated to match `solid` and `transparent`.
<img width="906" alt="CleanShot 2023-11-07 at 14 02 58@2x" src="https://github.com/Esri/calcite-design-system/assets/108549080/bd1109fc-f311-467b-a409-d68b9bd4f9ba">

### Relevant Info

cc @jcfranco 

### Which Component

Split Button

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
Added `visual changes` label as this will tweak the `outline-fill` divider.

**Comment by geospatialem** [comment]
In verifying in `2.9.0-next.18` it looks like if a background color is added, the same color is placed in the empty space for the revised divider: https://codepen.io/geospatialem/pen/VwOjjOX

![image](https://github.com/Esri/calcite-design-system/assets/5023024/ec3d231b-9754-4a89-85bb-52c29fbfb733)

@josercarcamo reassigning back to ya and set to in development for further investigation. 🕵🏻

**Comment by geospatialem** [comment]
Verified in `2.9.0-next.21` with https://codepen.io/geospatialem/pen/VwOjjOX 🎉 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/9ec9d997-67f6-44a5-8f21-45f15371bb88)
