### ISSUE TITLE
Initial render issues due to dynamic import of custom elements in calcite-components-react

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#8143]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Some initial render issues have popped up that I traced back to the patch created in #7521. The patch uses a dynamic import to ensure the custom elements are not defined on the server, which causes errors. This may be an issue on Stencil's end, where they need to force a VDOM rerender when the components are hydrated.

The current workaround is to import/define the custom elements in addition to the react components. This was the only possible behavior until [`@esri/calcite-components-react@v1.5.0`](https://github.com/Esri/calcite-design-system/releases/tag/%40esri%2Fcalcite-components-react%401.5.0), when we enabled [`includeImportCustomElements`](https://stenciljs.com/docs/v2/react#includeimportcustomelements). See #7185 for examples.

### Expected Behavior

I expect one of the following:

1. No initial render issues when taking advantage of `includeImportCustomElements`. This means we would likely need to remove the patch and find a new solution for the SSR build errors brought up in #7486 and #7493. We should do additional testing after #8108 is installed, because Stencil may have resolved the issues on their end in the new versions.
2. Disable `includeImportCustomElements` to prevent confusion and buggy behavior. **This would be a breaking change**.

### Reproduction Sample

https://codesandbox.io/p/sandbox/calcite-components-react-hm5rwn?file=%2Fsrc%2FApp.tsx%3A5%2C74

### Reproduction Steps

1. The current state of the sample works properly
2. Remove lines 2-5 in App.tsx
3. Notice the slider appears to have a value of `0` even though the internal state is `50`. The banana icon at the end of the title also didn't render initially.
4. Move the slider or click the "Clear" button, and notice the icon appears and the slider starts behaving normally.

### Reproduction Version

1.10.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
Verified on code sandbox
