### ISSUE TITLE
Improve <calcite-input> suffixes and prefixes

### ISSUE THREAD

**Issue by hcampos-professional** [Esri/calcite-design-system#8154]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

When using a `<calcite-input>` or `<calcite-input-number>` with a `prefix-text` or `suffix-text`, users are finding it difficult to understand that the suffix and prefix are not clickable. Matters complicate further if the `clearable` property/attribute is set, since the button looks so similar to the suffix and prefix:

![CleanShot 2023-11-09 at 16 33 22](https://github.com/Esri/calcite-design-system/assets/136828178/2dcf9469-f1b6-423a-bf58-49c39ed2d113)

Another issue is that, when multiple inputs are placed next to each other, the suffixes and prefixes won't necessarily have the same with, which doesn't look great.

After some internal discussions, a proposal was floated: placing the suffix and/or prefix inside of the input itself. Here is a mockup of the proposal:

![image](https://github.com/Esri/calcite-design-system/assets/136828178/099f926d-2e6f-4389-a43b-a1236f42b252)

### Acceptance Criteria

- When `prefix-text` and/or `suffix-text` are specified, they should appear inside of the input instead of inside a bordered container.

### Which Component

- `<calcite-input>`
- `<calcite-input-*>`

### Example Use Case

The use case we're exploring at the moment is displaying multiple numerical values of a tool stacked vertically, each value with its unit displayed as a `suffix-text`. In this scenario, having all the suffixes with different widths and having the units appear clickable is not desirable.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by macandcheese** [comment]
We may need to explore ways of making the prefix visually distinct from the input content. Suffix doesn’t suffer from the same issue. 

It may still be nice to offer way to set the width of these via css property to ensure consistent widths, either when prefix/suffix or both are used. You might still end up with the “width stagger” depending on set up.

**Comment by Anastasiia-Boleiko** [comment]
The proposal looks great, +1 from the ArcGIS Urban team.
The current number input with a unit looks like:
![input with unit](https://github.com/Esri/calcite-design-system/assets/119309703/4e533c81-7197-494c-9205-c65732cee007)
In our case it's fine if a unit is close enough to the input value.

**Comment by macandcheese** [comment]
> The proposal looks great, +1 from the ArcGIS Urban team. The current number input with a unit looks like: ![input with unit](https://user-images.githubusercontent.com/119309703/281814225-4e533c81-7197-494c-9205-c65732cee007.gif) [ ![input with unit](https://user-images.githubusercontent.com/119309703/281814225-4e533c81-7197-494c-9205-c65732cee007.gif) ](https://user-images.githubusercontent.com/119309703/281814225-4e533c81-7197-494c-9205-c65732cee007.gif) [ ](https://user-images.githubusercontent.com/119309703/281814225-4e533c81-7197-494c-9205-c65732cee007.gif) In our case it's fine if a unit is close enough to the input value.

I think a persistent "trailing suffix" like shown here (but visible during entry) could be nice to explore.

**Comment by Anastasiia-Boleiko** [comment]
> > The current number input with a unit looks like: ![input with unit](https://user-images.githubusercontent.com/119309703/281814225-4e533c81-7197-494c-9205-c65732cee007.gif)  
> > In our case it's fine if a unit is close enough to the input value.
> 
> I think a persistent "trailing suffix" like shown here (but visible during entry) could be nice to explore.

Hi there! 👋

Could you please clarify when we can expect the input component such an update? It's important for ArcGIS Urban app for proper planning and prioritization.

**Comment by geospatialem** [comment]
> Hi there! 👋
> 
> Could you please clarify when we can expect the input component such an update? It's important for ArcGIS Urban app for proper planning and prioritization.

@Anastasiia-Boleiko Thanks for reaching out, relayed on your note to the design team. Designers will be prioritizing efforts for a future milestone late next week (dev work would be in a separate milestone). Stay tuned for additional updates in the future.

**Comment by hcampos-professional** [comment]
While it's would be a great addition, having only a CSS var will force apps to measure the max width of their prefixes/suffixes and then set the var accordingly. It would be great it Calcite provided a mechanism to do that OOTB, either as a utility or some property that would "link" multiple inputs in order to sync their prefixes and suffixes.

**Comment by Anastasiia-Boleiko** [comment]
Hi there! 
I noticed that the planned enhancement should enable visual alignment of prefixes and suffixes. However, the current solution does not address our specific issue. We are looking to transition to Calcite Input while maintaining clean forms without excessive clutter. I'm curious if you have any plans regarding the "trailing suffix" or a similar UI?

**Comment by hcampos-professional** [comment]
For the record, I would also be in favor of @Anastasiia-Boleiko's proposal, and see the "same width prefixes/suffixes" as a stop-gap measure.

**Comment by SkyeSeitz** [comment]
> While it's would be a great addition, having only a CSS var will force apps to measure the max width of their prefixes/suffixes and then set the var accordingly. It would be great it Calcite provided a mechanism to do that OOTB, either as a utility or some property that would "link" multiple inputs in order to sync their prefixes and suffixes.

For sure, @hcampos-professional - agree and I believe this could be most likely introduced as a part of a Form or Input Group component. @jcfranco, thoughts? Is this something that has come up in those conversations thus far? 

Thanks for the feedback, @Anastasiia-Boleiko! Yea, while the trailing suffix poses a few specific hurdles, we are currently exploring it and similar improvements [documented in this file](https://www.figma.com/file/zS8T4QWc8qLAJmtTHsyvlL/Inputs%3A-prefix%2Fsuffix-updates?type=design&node-id=604%3A44604&mode=dev), where our next step is to gather feedback on a solution we could implement at a major release.

**Comment by Anastasiia-Boleiko** [comment]
Thank you so much for sharing the details, that's really helpful!😊 So, if I understand correctly, depending on the feedback collected, the earliest release of the feature (trailing suffix) is expected to be in May 2024, right?

**Comment by SkyeSeitz** [comment]
Hey @Anastasiia-Boleiko sorry for the confusion! The exploration is in early stages so no concrete plans are set on further UI changes to the prefix/suffix, but if we decide to move forward with styling updates, a new issue will be created and targeted for a breaking change release.

**Comment by Anastasiia-Boleiko** [comment]
Hey👋,
We are also looking into [Inline Editable](https://developers.arcgis.com/calcite-design-system/components/inline-editable/) component. According to the docs, the default slot is `calcite-input`. However, when we add a `suffix` ([codepan example](https://codepen.io/anastasiia-zrh/pen/zYVxZmP?editors=100)), or change the type to `number` ([codepan example](https://codepen.io/anastasiia-zrh/pen/RwzNpYv?editors=100)), the component no longer appears as an Inline Editable.

Do you consider a new look of suffix or any other property to have a "transparent" display (without wrapping box) within the Inline Editable component? 😊

**Comment by hcampos-professional** [comment]
Another related pattern that appeared in some internal proposals is to have the suffix be a "dropdown" (or at least clickable) to allow users to select units, for example. If the suffix needs to be clickable or an actual select/dropdown, it may speak in favor of the current design where it already looks clickable.

That being said, the UI could be achievable by using the `action` slot of the `<calcite-input>`, except that slot is currently meant for a `<calcite-button>` and not a `<calcite-select>` or `<calcite-dropdown>`: https://codepen.io/hccampos/pen/mdZXXbP?editors=1000

**Comment by DitwanP** [comment]
🍡 Verified on `2.13.0-next.9` 
https://codepen.io/Ditwan-Price/pen/abgxyNW?editors=1100
