### ISSUE TITLE
List Item - Add a new slot to display content at the bottom of the content in a list item

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#8173]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

We are working on refactoring the JavaScript Maps SDK LayerList widget to use the Calcite Design System.  It turns out there isn't a good slot to put the legend in the list item. When adding the legend to the `content` slot the list item stretches the action buttons to match the height of the content and centers them vertically.

![MicrosoftTeams-image (6)](https://github.com/Esri/calcite-design-system/assets/2636825/d232af21-0521-40be-93b1-098cf13b6eff)

Using the `default` slot would result in the legend not being show unless the list item is open as well as producing alignment issues with nested children.

A new content slot (content-bottom) would be a great addition to list items to display content under the label description and actions.

### Acceptance Criteria

The ability to show a legend widget without alignment issues in a list item, similar to the way legends are currently shown in layer list items. https://developers.arcgis.com/javascript/latest/sample-code/widgets-layerlist-legend/

### Which Component

List Item

### Example Use Case

Refactoring the ArcGIS Maps SDK for JavaScript LayerList widget to use the Calcite Design System

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by sagewall** [comment]
cc @driskull @asangma

**Comment by driskull** [comment]
@geospatialem can we triage this one for November?

**Comment by macandcheese** [comment]
Is it possible to use a Block in any way for this?

**Comment by driskull** [comment]
I don't think so.

**Comment by macandcheese** [comment]
Is there an example of the desired UI? It's tough to tell from the screenshot - are there siblings? 

In the [linked example](https://developers.arcgis.com/javascript/latest/sample-code/widgets-layerlist-legend/), there's just a single item in that content area. For that case, a Block or even a Panel could make sense...

**Comment by driskull** [comment]
Here's another example: https://developers.arcgis.com/javascript/latest/sample-code/layers-imagerytilelayer/

The issue with block is we can't just insert it in the middle of a layerlist. We need a way to display content within a single list item that can be toggled by a user. This content should also be indented with the list item and not depend on the list item being open.

**Comment by macandcheese** [comment]
Yeah that makes more sense amongst sibling items.

**Comment by driskull** [comment]
Another example: https://codepen.io/driskull/pen/zYeEdvw?editors=1000

**Comment by driskull** [comment]
@macandcheese if we do want to make this collapsible content built in, we'll have list-item properties for `open`, `closed`, and some new property for content being open. Is that the route we want to go?

**Comment by macandcheese** [comment]
Yeah, bit of weird verbiage there with `closed` really meaning ... `dismissed`, but we've been down that road already, lol. 

We can just make it managed by the user and let them worry about the affordance for opening / closing (some cases may just be based on "selection" of `selectionMode:none`, which is fine. That way we only have to worry about adding a slot (named vs. default... could go either way - default matches Block, etc., but named matches "stack" more...)

**Comment by driskull** [comment]
Yeah I agree. We can just add a slot for placing content and let the user handle it for now. Down the road if this becomes a common use case, we can revisit toggling this content.

**Comment by geospatialem** [comment]
Verified locally with the `main` branch. There is a documentation update to add a sample in the near future. cc: @DitwanP
