### ISSUE TITLE
stepper: add tokens for responsive layout

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#8174]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Stepper component is using [fixed](https://github.com/Esri/calcite-design-system/pull/7744/files#diff-9c3caa940d36660ca607fca4703fd75f402c70b32d37f31b2111d81970fb0c9fR2) `min-width` length to determine displaying single item vs all items as part of responsive layout enhancement. Having these values in design tokens helps users to enhance the values as required. 

### Acceptance Criteria

1. Create tokens for `min-width` value for each scale.
2. Use the tokens in stepper component to access the `min-width` of `stepper-item` per scale.

### Which Component

`calcite-stepper`

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Could be considered as part of the efforts of https://github.com/Esri/calcite-design-system/issues/7180

**Comment by geospatialem** [comment]
In addition to the above, we should also add context to the [Stepper](https://developers.arcgis.com/calcite-design-system/components/stepper/) doc page regarding the width of the component, or container width, which includes:
- Small: 120px
- Medium: 180px
- Large: 200px

cc @DitwanP

**Comment by anveshmekala** [comment]
We longer need tokens for min-width of stepper-item as per #8461. Can we close this one? @geospatialem , @DitwanP

**Comment by geospatialem** [comment]
> We longer need tokens for min-width of stepper-item as per #8461. Can we close this one? @geospatialem , @DitwanP

Thanks @anveshmekala - marked the issue as installed pending verification. cc @DitwanP we may need an updated doc ref in our doc repo, more context above in https://github.com/Esri/calcite-design-system/issues/8174#issuecomment-1858578163.

**Comment by anveshmekala** [comment]
> > We longer need tokens for min-width of stepper-item as per #8461. Can we close this one? @geospatialem , @DitwanP
> 
> Thanks @anveshmekala - marked the issue as installed pending verification. cc @DitwanP we may need an updated doc ref in our doc repo, more context above in [#8174 (comment)](https://github.com/Esri/calcite-design-system/issues/8174#issuecomment-1858578163).

Don't think the min-width's are documented. We no longer use default min-width in stepper. As part of https://github.com/Esri/calcite-design-system/issues/8461 fix, imposing min-width is removed irrespective of the layout value.

**Comment by geospatialem** [comment]
Closing as no longer valid per Anvesh's comment above in https://github.com/Esri/calcite-design-system/issues/8174#issuecomment-1949305383.
