### ISSUE TITLE
List, Stack: action menus and handles slotted into list item and stack are not stretched to full height

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8187]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When an `action-menu` or `handle` component is slotted inside a `list-item` or `stack` component it does not get the full height.

### Expected Behavior

They should be stretched vertically just like the `action` slotted components are.

### Reproduction Sample

https://codepen.io/driskull/pen/wvNPYYg?editors=1010

### Reproduction Steps

1. Open the sample app
2. Inspect the height of the height of the banana action
3. Inspect the height of the handle component
4. Inspect the height of the action-menu component
5. All three should be the same height.

### Reproduction Version

1.10

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified on the `main` branch. 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/137bd8a6-7223-4a6d-8c2f-3a4b9ef090ea)
