### ISSUE TITLE
undefined is not iterable (cannot read property Symbol(Symbol.iterator)) in unwatchGlobalAttributes

### ISSUE THREAD

**Issue by tomwayson** [Esri/calcite-design-system#8193]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When transitioning between routes in our Ember application we see this error in the console:

![image](https://github.com/Esri/calcite-design-system/assets/662944/1532fb7b-f961-41b6-a36d-07ea7e2ef23c)

### Expected Behavior

calcite-components are destroyed w/o throwing errors.

### Reproduction Sample

https://brollywood.hikes.dev/explore?layout=grid&query=rapid%20transit&uiVersion=PR-12759

### Reproduction Steps

I'm sorry, I don't have a clean external reproduction, but you can observe for yourself w/in our app:

##### STEPS TO REPRODUCE
1. Go [here](https://brollywood.hikes.dev/explore?layout=grid&query=rapid%20transit&uiVersion=PR-12759)
2. Open the console
3. Click the result with the thumbnail and org name attribution 
4. observe the above errors in the console

### Reproduction Version

1.9.2

### Relevant Info

I've traced this down to [this line](https://github.com/Esri/calcite-design-system/blob/%40esri/calcite-components%401.9.2/packages/calcite-components/src/utils/globalAttributes.ts#L37
):

```tsx
    const [component, options] = elementToComponentAndObserverOptionsMap.get(target as HTMLElement);
```

Called from a button's `disconnectedCallback()` -> `unwatchGlobalAttributes(this)`

It's seems `elementToComponentAndObserverOptionsMap.get(target)` returns `undefined` so the `const [component, options]` fails.

Without getting into _why_ that returns `undefined`,  I wonder if we could resolve this by simply returning early in that case, like:

```diff
-    const [component, options] = elementToComponentAndObserverOptionsMap.get(target as HTMLElement);
+    const result = elementToComponentAndObserverOptionsMap.get(target as HTMLElement);
+    if (!result) { return };
+    const [component, options] = result;
```

### Regression?

1.4.1

### Priority impact

p2 - want for current milestone

### Impact

So far, our application seems to work despite these console errors, but we are not yet done w/ comprehensive testing since upgrading to 1.9.2, so there may be other places where this causes a more severe problem.

If the above proposal 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Hub

**Comment by DitwanP** [comment]
Hey @tomwayson 👋 Thanks for flagging this.

We'd love to dig into the issue, but the current example is a bit tricky to navigate. If you get a chance, could you simplify it a bit or provide a more isolated example? It'd help us get to the bottom of things faster.

**Comment by tomwayson** [comment]
Thanks @DitwanP 

I propose we wait to see if this affects anyone else before we try and create an isolated example since:
- this does not appear to be a blocker for us at this time
- I don't currently have the bandwidth to try and create an isolated example

If any of that changes, I'll try to figure out how to reproduce this outside of our Ember application.

**Comment by LeviRemi** [comment]
@tomwayson, I do not have an isolated example either yet, but can confirm I started seeing this error on Calcite `1.9.2`, and still see it on `2.0.0`. Took awhile to track down, but happy to see the same issue captured in detail here. Hope it gets resolved soon.

**Comment by jcfranco** [comment]
Thanks everyone for the additional info. Added to this release as a spike to create a repro case and to determine effort along with next steps.

**Comment by jcfranco** [comment]
In somewhat related news, the latest version of Stencil would allow us to drop our global attribute watching util and might fix this as a side effect. I've submitted a [refactor PR](https://github.com/Esri/calcite-design-system/pull/8407) for this.

@tomwayson @tannerjt @LeviRemi Would you be able to test with the following [local build](https://github.com/Esri/calcite-design-system/files/13652939/esri-calcite-components-2.1.0-next.5.tgz)?

**Comment by jcfranco** [comment]
Thanks to @LeviRemi, we've got an isolated repro case for this! 🎉

**Comment by jcfranco** [comment]
@geospatialem @brittneytewks We should be good to address this in this release. Moving milestone and assigning to myself. 💪

**Comment by DitwanP** [comment]
🍬 Verified locally with [isolated repro case](https://github.com/LeviRemi/calcite-undefined-repro)


https://github.com/Esri/calcite-design-system/assets/60022782/c83e6fac-e815-4865-ac73-f7a320b33bb9
