### ISSUE TITLE
dropdown: the `arrow-down`/`arrow-up` keys should open a dropdown

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8205]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Summary

dropdown: the `arrow-down`/`arrow-up` keys should open a dropdown

### Actual Behavior

Arrow keys have no effect.

### Expected Behavior

Using the arrow keys on a trigger should open the dropdown component.

### Reproduction Sample

https://codepen.io/driskull/pen/RwvxBZG?editors=1000

### Reproduction Steps

1. focus on the "plus" action
2. Use arrow down or arrow up key
3. Nothing happens

### Reproduction Version

1.10

### Working W3C Example/Tutorial

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role#keyboard_interactions

### Relevant Info

![image](https://github.com/Esri/calcite-design-system/assets/1231455/7f0629c2-7eeb-4aae-a6d0-55d16a2465b5)

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
We should look at other components with the same role to enhance similarly. cc @geospatialem

**Comment by jcfranco** [comment]
Looks like it's just `menu-item`. The internal `action-menu` already supports this. 🎉

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`


https://github.com/user-attachments/assets/dcd14147-191d-4aa5-9dc9-314aa759b036

What's shown in the recording is me using the up and down arrows to open the dropdown.
