### ISSUE TITLE
Popover: dismissible button hover has a rounded corners mismatch 

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#8208]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The two right corners of the dismissible button hover have mismatched corner radiuses. 

Easier to see in the current build
<img width="237" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/1337567a-e3d4-43fa-ae0b-eaa24355585f">
But will persist with https://github.com/Esri/calcite-design-system/pull/8194 's update to transparent actions. 
![image](https://github.com/Esri/calcite-design-system/assets/29716057/98f061eb-29db-42e4-ba02-e9d73cb6682e)

### Expected Behavior

Top right should match it's container's radius. Bottom right should have a border-radius of 0.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/popover/

### Reproduction Steps

1. Open Popover 
2. Hover dismissible button

### Reproduction Version

1.10.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `2.10.0-next.0`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/8555dbb4-228a-4cd3-b1b3-e596c5a1ec60)
