### ISSUE TITLE
Closed floating elements are taking up visual space when being dragged

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8214]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Floating elements are taking up visual space because they are set to `visibility:hidden`.

Is there any way we can make them not introduce scrollbars in certain scenarios?

### Expected Behavior

I would expect that any hidden menus are not taking up any visual space

### Reproduction Sample

https://codepen.io/driskull/pen/Rwvxyaj

### Reproduction Steps

1. Open sample
2. Notice the scrollbar appearing in the panel
3. The scrollbar is because of the dropdown which is not opened.
4. The banana icon opens a dropdown which is causing the issue

### Reproduction Version

1.10

### Priority impact

p2 - want for current milestone

### Impact

This is noticeable when a large menu is placed inside a list item and makes dragging experience pretty bad.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `1.12.0-next.6`
