### ISSUE TITLE
stepper-item: Remove unused messages 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#8223]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, `previousStep` and `nextStep` message strings are not used in the component  which are added as part of https://github.com/Esri/calcite-design-system/pull/7918/ and they are moved into `stepper` after the spec discussions.

### Acceptance Criteria

Remove `previousStep` and `nextStep` message strings from locale bundles.

### Which Component

calcite-stepper-item

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified the translations are no longer present on the `main` branch.
