### ISSUE TITLE
Tree: update selection affordance in ancestors mode

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#8227]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Update Tree `selection-mode="ancestors"` to use icons instead of checkboxes. This will visually align Tree with updates from epic #7181.

### Acceptance Criteria

Selection icons and hover states updated to match [Figma designs](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---update-icons-for-system-consistency-%5B7181%5D?type=design&node-id=1044-5483&mode=dev).

### Relevant Info

@geospatialem @brittneytewks These designs were originally included on a related, but separate issue. Logging this new one for inclusion in epic #7181.

### Which Component

Tree, Tree Item

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
The above was included in PR https://github.com/Esri/calcite-design-system/pull/9849, where the following was added to the `tree-item`:

https://github.com/Esri/calcite-design-system/blob/f2aa976f3c0d0ce69aa184a835da628e9898a4bd/packages/calcite-components/src/components/tree-item/tree-item.tsx#L235-L245
