### ISSUE TITLE
Investigate why icon component path isn't being fetched properly

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8228]
### Background

once I drag a list-item that has children, the caret icon disappears.

![Nov-17-2023 14-02-24](https://github.com/Esri/calcite-design-system/assets/1231455/b1791d67-bb7c-4484-83a7-436b5a289bc2)

![Screenshot 2023-11-17 at 2 03 41 PM](https://github.com/Esri/calcite-design-system/assets/1231455/3227db11-febc-417a-8be2-a6954b891cab)

I can't reproduce it with just calcite. 

Seems to be an issue where the path isn't being updated or fetched properly.

If I log out the pathData of the icon it's an empty string.

![image](https://github.com/Esri/calcite-design-system/assets/1231455/beb7a4f8-ddfa-4e1c-b27d-778f50102662)

### Desired Outcome

Discovery into why the icon isn't loading the path in certain scenarios.

**Comment by geospatialem** [comment]
Closing as a key was added to accommodate the above. Will re-open if it pops up again in a future release.
