### ISSUE TITLE
Fix code sample snippets not being visible inside file when viewed on GitHub

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#8231]
### Summary

Was told this might have been a bug that was previously fixed but when I try to view the '.mdx' under [component-sample-snippets](https://devtopia.esri.com/ArcGISDevelopers/calcite-documentation/tree/next/documentation/component-sample-snippets) I am unable to see the actual code sample. 

The files look like this: ![Screenshot 2023-11-21 at 11 30 08 AM](https://github.com/Esri/calcite-design-system/assets/60022782/c8cf231f-57f0-4e84-97ca-b9f15f69242d)

### Desired Outcome

I'm not sure if this is a known/expected behavior but ideally the code samples should be visible within the files underneath the title and description.

**Comment by benelan** [comment]
GitHub doesn't render mdx, you need to start the development server right @macandcheese?

**Comment by macandcheese** [comment]
Yeah, those are just markdown files, they shouldn’t render anything in GH. 

If you run the documentation site locally they are used by the component sample in Gatsby within the pages they are referenced. 

These don’t live in this repo - I think we can close. @DitwanP can you reach out if there are any issues with this?
