### ISSUE TITLE
ListItem: an item with an empty slotted list should have the open caret

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8241]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

an item with an empty slotted list does not get the open caret button

### Expected Behavior

an item with an empty slotted list should have the open caret

### Reproduction Sample

https://codepen.io/driskull/pen/MWLVZpZ?editors=1000

### Reproduction Steps

1. Open the sample
2. The item should have a care to open the item
3. Notice it does not.

### Reproduction Version

1.10

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
Verified on the main branch.
