### ISSUE TITLE
List: difficulty dragging into a child list

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8242]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Its difficult to drag a list item into an empty list because the list takes up no space.

It would be nice if an empty list had some reserved space area to drop items.

### Acceptance Criteria

Easier to drag into an empty list

### Relevant Info

https://codepen.io/driskull/pen/WNPzLdK?editors=1000

![Nov-21-2023 14-34-42](https://github.com/Esri/calcite-design-system/assets/1231455/ca4afe99-9155-4d09-a270-32e13b0ff30d)

### Which Component

list

### Example Use Case

See relevant info

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by driskull** [comment]
This needs to go to design first.

**Comment by sagewall** [comment]
@geospatialem would it be possible to prioritize this? It's causing come confusion and unpredictable behavior trying to drag items into group layers in the new JavaScript SDK layer list widget.

**Comment by ashetland** [comment]
@driskull Didn't this get merged into v.2.0?

**Comment by driskull** [comment]
I did a quick fix but this needs a proper design.

**Comment by driskull** [comment]
I think this could be solved by #7100 and indenting the whole item.

**Comment by sagewall** [comment]
Thought I'd mention this not only affects the JS SDK, but the applications that use our SDK like Map Viewer, Experience Builder and Instant Apps.

**Comment by ashetland** [comment]
Hey @sagewall and @zaramatheson is there something that @driskull's quick fix isn't addressing? Can you show us demo of the problem? I'm working on some related List designs, but I want to make sure I/we fully understand what's causing this issue. We might be able to expedite a better fix.

**Comment by sagewall** [comment]
Sure, Currently it's impossible to move an item down the list under an open group layer without adding it to the group.  If you move a layer up from further down the list, there isn't a way to add it to the group.

### Reproduction Steps

1. Open this [codepen](https://codepen.io/sagewall/pen/abMWmEB)
2. Open "Group Layer 3"
3. Move buffer5 up but not crossing the bottom of the "U.S. States Generalized from my content" layer.
4. Observe how the buffer5 layer is placed outside the group layer. I haven't been able to get it to add to the group layer from below. Unless I drag it slightly into the last group layer and then just slightly back down.
5. Drag the buffer5 layer above "Group Layer 3"
6. Moving it down under the last last layer in "Group layer 3" always results in it being added to the group layer.  I haven't been able to get it to not get added to the group layer


https://github.com/Esri/calcite-design-system/assets/2636825/fc2461f6-3218-4267-8004-47eaac5951d5

**Comment by sagewall** [comment]
Should we rename this issue "difficulty dragging into child list", I didn't notice the "empty" part in the name?

**Comment by ashetland** [comment]
This is super helpful. Thank you! Renaming might make sense. It doesn't look like "empty" is the issue here.

**Comment by ashetland** [comment]
This [Figma file](https://www.figma.com/file/91sfHrYNt0Il6B4pEZZ749/List-spacing%2C-sorting%2C-group-heading-%5B7100%5D-%5B8039%5D-%5B8242%5D-%5B8667%5D?type=design&node-id=982%3A37071&mode=dev) covers multiple related design revisions for List and includes a section for improvements to sorting. @driskull we've outlined our ideal for this, but we intend final details to be hammered out once we start building this and the related changes.

**Comment by driskull** [comment]
@ashetland @jcfranco when we deprecate the "classic" mode, which will become the default mode? "flat" or "nested"?

**Comment by ashetland** [comment]
My gut feeling is "nested" becomes the default, but I think @jcfranco also mentioned letting metrics decide this?

**Comment by ashetland** [comment]
@driskull Confirming that all we need to do for this issue is indent the entire item? We have some other possible improvements we'd like to test, but they could be separate from this issue.

**Comment by driskull** [comment]
Yes, thanks @ashetland

**Comment by driskull** [comment]
@ashetland PR ready for your review.

**Comment by DitwanP** [comment]
🍡 Verified on `2.8.0-next.10`

https://github.com/Esri/calcite-design-system/assets/60022782/0ab7e607-1095-44e3-9a86-fb4947ac55f1
