### ISSUE TITLE
calcite-modal, calcite-dropdown : rename `width` prop to `widthScale`

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#8250]
### Description

rename `width` prop in `calcite-modal` and `calcite-dropdown` with `widthScale` to be consistent with pattern in `calcite-sheet` and `shell-panel`

### Proposed Advantages

- Helps in providing consistent API across the repo .
- Provides pattern for using `width` vs `widthScale`

### Which Component

- [x] `calcite-modal` https://github.com/Esri/calcite-design-system/pull/8252
- [x] `calcite-dropdown` https://github.com/Esri/calcite-design-system/pull/8251

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by geospatialem** [comment]
Verified on the `rc` branch.
