### ISSUE TITLE
Add option to render icons (or other assets/components) synchronously

### ISSUE THREAD

**Issue by hcampos-professional** [Esri/calcite-design-system#8261]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

When displaying an icon in a `<calcite-icon>`, the actual icon is loaded asynchronously. This is fine if the page or component containing the icon is loading for the first time. However, in applications which show/hide elements dynamically, this poses some problems:
- The first time an icon is displayed, users have to wait some time for the icon to appear.
- Even if an icon was previously loaded into the page, creating a new instance referring to the same icon can still cause flickering, because the `<calcite-icon>` component is rendered and the icon itself only gets loaded and rendered asynchronously.

Here is a CodeSandbox which exemplifies the issue: [Sandbox](https://codesandbox.io/p/devbox/restless-moon-pff4yx?workspaceId=a8ef6e35-b632-4260-911d-bff54e173524)

### Acceptance Criteria

- We would like to have an option to preload certain icons. Once the icons are preloaded, Calcite components should render them synchronously to the DOM.
- After an icon is loaded (whether it was preloaded or not), subsequent renders should be synchronous.

### Which Component

`<calcite-icon>` and any other component using icons.

### Example Use Case

Within our applications we often have panels, popups, tooltips (etc) containing icons and which are rendered dynamically. Having icons flicker or pop into the app after these components are rendered provides a subpar user experience.

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by janett-baresel** [comment]
This also is a problem in Scene Viewer.

**Comment by jcfranco** [comment]
@hcampos-professional A few questions/notes:

1. Would you mind expanding a bit on `We would like to have an option to preload certain icons`? 
    1. Were you thinking on explicitly keeping track of which icons to preload? If so, this might be challenging to maintain since icons can change frequently across different components.
    1. Would preloading all icons be a valid path or is lazy-loading still desired?
1. https://github.com/Esri/calcite-design-system/pull/9197 was installed this year and might help mitigate some of the flickering concerns with rendering of loaded icons.
1. Would you mind double-checking the provided sandbox? I can't access it. 🥲

**Comment by jcfranco** [comment]
@hcampos-professional Thanks for the info. My main concern with util to preload a subset of icons is that it won't scale well and will be tricky to maintain, especially considering each icon has 3 scale variations that a component configures based on its own scale.

I've submitted [a PR](https://github.com/Esri/calcite-design-system/pull/10926) that adds a `preload` prop to icons that will allow you to do the following:

```ts
interface ScaledIconsToPreload {
  [scale: string]: IconName[];
}

async function preloadIcon(icon: string, scale: Scale): Promise<void> {
  const iconElement = document.createElement("calcite-icon");
  iconElement.icon = icon;
  iconElement.hidden = true;
  iconElement.preload = true; // ✨new✨
  iconElement.scale = scale;
  document.body.appendChild(iconElement);
  await customElements.whenDefined("calcite-icon");
  await iconElement.componentOnReady();
  iconElement.remove();
}

async function preloadIcons(
  iconsToPreload: ScaledIconsToPreload
): Promise<void> {
  await Promise.all(
    Object.entries(iconsToPreload).map(([scale, icons]) => {
      return Promise.all(
        icons.map((icon) => preloadIcon(icon, scale as Scale))
      );
    })
  );
}

const scaledIconsToPreload: ScaledIconsToPreload = {
  s: ["absolute-direction"],
};

await preloadIcons(scaledIconsToPreload);
```

Here's a preview using your sandbox example (uncached and throttled to slow 4G):
![preloading](https://github.com/user-attachments/assets/6213e85b-e102-45d1-9c89-10b73e8d896b)

Alternatively, since preloading all icons seems acceptable, I can explore adding a global config option for the icon component, in addition to the `preload` prop, to fetch icons as soon as they are appended to the DOM.

LMKWYT!

**Comment by hcampos-professional** [comment]
@jcfranco that looks pretty nice to me. Could work very well for tests, for example, to ensure everything is preloaded, and/or to wait for `componentOnReady()`. And seems like it could work for the SV team as well, but I'll let @janett-baresel comment on that.

**Comment by jcfranco** [comment]
Will proceed with the `preload` property for now. @janett-baresel LMK what you think about the global config option as another approach.

**Comment by geospatialem** [comment]
@hcampos-professional / @janett-baresel Would either of you be able to verify this one for us? I'm getting a failure with the vite.config file in the [Codesandbox example](https://codesandbox.io/p/devbox/restless-moon-pff4yx?workspaceId=a8ef6e35-b632-4260-911d-bff54e173524). 😢 

You can test with `3.0.0-next.57`+ with the `icon`'s new `preload` boolean prop.

**Comment by geospatialem** [comment]
Verified with Franco's [Codesandbox](https://codesandbox.io/p/devbox/calcite-icon-load-issue-forked-pyhtn5?file=%2Fsrc%2Findex.ts%3A28%2C29) with `3.0.0-next.76` and some of the contents [mentioned above](https://github.com/Esri/calcite-design-system/issues/8261#issuecomment-2515941460) with the `preload` boolean prop. 🎉

**Comment by hcampos-professional** [comment]
I've also been able to verify this within @arcgis/core with `3.0.0-next.75` 👍
