### ISSUE TITLE
[Shell / Shell Panel] When `content-behind` is set, Shell Panel in slot "panel-bottom" can position incorrectly

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8269]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When Shell has `content-behind` set, a Shell Panel of  in slot "panel-bottom" with `displayMode="float"` will not display properly if there is not content slotted in "panel-top".

### Expected Behavior

I'd expect the slotted "panel-bottom" content to always position in the bottom, without the need to populate "panel-top".

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/bGzjMLg?editors=1100

### Reproduction Steps

1. Open Codepen
2. See incorrectly positioned "bottom panel"
3. Uncomment `collapsed` "top panel"
4. See positioning is correct

### Reproduction Version

1.10

### Relevant Info

There are some inconsistencies with how this behaves when `content-behind` is set, or unset.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
The workaround is to have a collapsed Shell Panel, in the `panel-top` slot.

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.6`
https://codepen.io/Ditwan-Price/pen/eYwNExg?editors=1100
