### ISSUE TITLE
Input Time Zone - selection defaults to first option in list when selecting offset with multiple signatures

### ISSUE THREAD

**Issue by tayMAPNeil** [Esri/calcite-design-system#8272]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If you select a time zone that has multiple signatures with that offset, (e.g., GMT+10), the selected time zone will always fall back to the first option with that offset, even if it's not the one you've selected. 

### Expected Behavior

The selected time zone from the pick-list will be persisted in the time zone input. 

### Reproduction Sample

https://codepen.io/tmcneil/pen/JjxBQVL?editors=1000

### Reproduction Steps

1. Select input time zone component to select a time zone. 
2. Select (GMT+10) Brisbane and Lindeman from the list of available time zones. 
3. See that (GMT+10) Guam, Port Moresby, Saipan, and Truk is shown as the selected time zone. 

### Reproduction Version

1.11.0

### Relevant Info

I can reproduce this on [the sample in the developer documentation](https://next.sites.afd.arcgis.com/calcite-design-system/components/input-time-zone/#sample) and in Map Viewer's Editor panel when selecting a time zone. 

It is important to note that this issue is only reproducible when initially selecting a time zone. If you select a time zone and it defaults to the first time zone with that offset, selecting the time zone again will correctly display the chosen time zone in the component. 

### Priority impact

p3 - want for upcoming milestone

### Impact

This is impacting the editing capabilities when adding or updating features in Map Viewer via the Editor panel. The chosen timezone is not being initially selected, and requires you to select it again to persist the correct time zone.  

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Possibly related https://github.com/Esri/calcite-design-system/issues/8007 cc @jcfranco

**Comment by geospatialem** [comment]
Verified in `2.8.0-next.4` with https://codepen.io/tmcneil/pen/JjxBQVL

![verify-time-zone-bug](https://github.com/Esri/calcite-design-system/assets/5023024/0418eea1-d569-4153-b7d9-26b2c5143e9b)
