### ISSUE TITLE
Docs: Refactor `2.0.0` changelog prior to release

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8276]
### Description

Update the `2.0.0` changelog for clarity and context prior to release.

### Which Component

N/A - applies to the changelog

### Resources

- [Editing changlog entries prior to release](https://github.com/Esri/calcite-design-system/wiki/Monorepo#edit-changelog-entries)
- [How to fix release notes](https://github.com/googleapis/release-please#how-can-i-fix-release-notes)

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/8246.
