### ISSUE TITLE
Break Core Design Tokens into separate files for the different token group types

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8277]
### Description

Similar to Semantic tokens, Core tokens should be split into separate files organized in a "core" directory to facilitate ease of use when looking for a specific variable or group of variables.

This will have no effect on the behavior or output of the Calcite Design Tokens

### Proposed Advantages

- Make it easier to find existing tokens
- Make it easier to add tokens to specific token groups

### Which Component

all core tokens

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
@alisonailea I went ahead and marked this one as installed for v2. Could you update the labels as needed?

**Comment by geospatialem** [comment]
Verified in [calcite-design-tokens](https://www.npmjs.com/package/@esri/calcite-design-tokens) in `2.0.0`.
