### ISSUE TITLE
Remove unused Component Design Tokens

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8278]
### Description

There is a directory of "component" tokens in the calcite-design-tokens which are out of date and not currently in use. These should be removed.

### Proposed Advantages

- reduce the size of the calcite-design-token repo
- reduce confusion for consumers who may think the "component" tokens should be used

### Which Component

all component files in calcite-design-tokens

### Relevant Info

If/when component tokens are align on in Design these can be added back on an as-needed basis.

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
@alisonailea I went ahead and marked this one as installed for v2. Could you update the labels as needed?

**Comment by geospatialem** [comment]
Verified in [calcite-design-tokens](https://www.npmjs.com/package/@esri/calcite-design-tokens) in `2.0.0`.
