### ISSUE TITLE
Handle: add disabled property

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8282]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A disabled property on the handle would be super useful to be able to prevent dragging on a specific item.

### Acceptance Criteria

Add disabled property to handle to prevent interaction and appear disabled

### Which Component

handle

### Example Use Case

<calcite-handle disabled></calcite-handle>

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
Verified locally on `main`
