### ISSUE TITLE
ListItem: Add dragDisabled property

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8284]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

SortableJS has an option to filter or prevent dragging on an individual item. It would be good to have a way to prevent dragging easily on an item.

### Acceptance Criteria

Add a new property to prevent dragging on an individual item

### Which Component

ListItem

### Example Use Case

`<calcite-list-item drag-disabled></calcite-list-item>`

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `1.12.0-next.6` with the following:

```html
<calcite-list drag-enabled>
  <calcite-list-item drag-disabled label="Hiking trails" description="Designated routes for hikers to use." value="hiking-trails">
    <calcite-action slot="actions-end" icon="layer" text="Trails layer"></calcite-action>
  </calcite-list-item>
  <calcite-list-item label="Waterfalls" description="Vertical drops from a river." value="waterfalls">
    <calcite-action slot="actions-end" icon="layer" text="Waterfalls layer"></calcite-action>
  </calcite-list-item>
  <calcite-list-item label="Rivers" description="Large naturally flowing watercourses." value="rivers">
    <calcite-action slot="actions-end" icon="layer" text="Rivers layer"></calcite-action>
  </calcite-list-item>
</calcite-list>
```
