### ISSUE TITLE
fix tokens output for Gatby documentation

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8287]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

the json output for semantic.color.border.input breaks when we try to automate documentation in Gastby. Then word "input" is reserved word and must be updated.

js output is only used by gatsby but it needs json

### Expected Behavior

Change to `semantic.color.border.user-input`

Change js format to json

### Reproduction Sample

N/a

### Reproduction Steps

1. take the JSON output of calcite-design-tokens
2. load it into Gatsby
3. Observe a build failure

### Reproduction Version

N/A

### Priority impact

p0 - emergency

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by alisonailea** [comment]
Per conversation on https://github.com/Esri/calcite-design-system/pull/8288 and also over chat, we will leave "input" as is and instead create a new output format for Gatsby which uses an array of design tokens instead of setting each design token to a named key. 

```json
"color":  [
   ...,
  { name: "input", ....},
  ...
]
```

instead of 

```json
"color": {
  ...,
  input: { ... },
  ...
}
```

**Comment by jcfranco** [comment]
@alisonailea I went ahead and marked this one as installed. Could you add a quick summary of changes from the PR?

**Comment by geospatialem** [comment]
Verified with Adam's internal doc site preview branch.
