### ISSUE TITLE
[Checkbox] When `checked` is set to `false` the component contains a blue background

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8294]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When the `checkbox` component's `checked` attribute is set to `false` the component adds a blue background, without the check, but it doesn't appear as-expected.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/910ae372-2dcf-40c8-be30-51d64311858b)

```html
<calcite-checkbox checked="false"></calcite-checkbox>
```
Whereas, when the component does not contain the `checked` attribute, it appears as-expected:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/ff3e490d-05e3-4cfc-a624-9c8d527eac67)

```html
<calcite-checkbox></calcite-checkbox>
```

### Expected Behavior

Both instances below depict the same visually:

```html
<calcite-checkbox checked="false"></calcite-checkbox>
<calcite-checkbox></calcite-checkbox>
```

![image](https://github.com/Esri/calcite-design-system/assets/5023024/359914ee-4be1-4130-80fe-e615a0841347)

### Reproduction Sample

https://codepen.io/geospatialem/pen/PoVdQoG

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/PoVdQoG)
2. Observe the first example when the component contains `checked="false"`
3. Compare to the other iterations of the component and similarly to the `card` and `tile-select` component examples

### Reproduction Version

1.11.0

### Priority impact

p4 - not time sensitive

### Impact

This doesn't appear to be a regression, however it is confusing with other iterations across the design system for consistency. It is also listed as an attribute/property that can be toggled with values of `true` and `false`.

There is also a workaround, where the developer could toggle the `checked` property, making this a lower priority fix:
```html
<calcite-checkbox id="checkboxEl"></calcite-checkbox>
<calcite-button>Workaround toggle</calcite-button>
<script>
  document.querySelector("calcite-button").addEventListener("click", () => document.getElementById("checkboxEl").toggleAttribute("checked") )
</script>
```

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
I think that result is expected in a vanilla example like that. 

The attribute should be omitted completely. Maybe we need to document that “false” as a value wouldn’t be used, in a vanilla / attribute scenario vs. a property use case where {false / undefined} would work as expected.

**Comment by geospatialem** [comment]
Update should include the language around using boolean props/attributes across components. Could conduct an audit across components to clarify the use. For instance:

For instance, an example of what the documentation language could contain for `checked`:

> When the attribute is present, the component is checked.

Resource: https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

**Comment by geospatialem** [comment]
In addition to the above, add context around the [`hidden`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) property, with other [native global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) for context to folks.

**Comment by geospatialem** [comment]
The above is a Stencil-related pattern, and no code can be modified to fit the above. 

The documentation was updated based on the following comments https://github.com/Esri/calcite-design-system/issues/6304#issuecomment-1441354731 and https://github.com/Esri/calcite-design-system/issues/6304#issuecomment-1485605920, where it is [not recommended to set boolean attributes to `disabled={false}`](https://developers.arcgis.com/calcite-design-system/resources/frameworks/#boolean-attributes).

Closing out the above!
