### ISSUE TITLE
Align tokens with Figma variables

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8310]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Found some misalignments between Figma variables and tokens. 

### Acceptance Criteria

Calcite Token names and values should align with the Calcite Figma variables 

### Which Component

Core and Semantic tokens

### Priority impact

p1 - need for current milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
@alisonailea I went ahead and marked this one as installed for v2.
