### ISSUE TITLE
Tokens | Updates for docs output

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8315]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently when tokens are generated, each token has a key called "filePath" set by StyleDictionary which provides an absolute file path to the json file where the token is set. While useful this field will break snapshot tests as the snapshot is generated on a local machine while the tests are run in the Github CI.

This issue may be resolved by transforming the absolute file path to a path relative to the current working directory. Until this issue is resolved we can not have snapshots of the "js" or "docs" platform output.

Additionally the docs platform output should stringify all token values (needed by Gatsby) and need more metadata to make tokens easy to search and organize on the doc-site.

### Acceptance Criteria

- each token's `filePath` key is a string with a file path relative to the current working directory.
- docs platform output will stringify all token values
- Each core and semantic token gets a "extensions>calcite-schema" which defines all token naming schema meta data for use by documentation

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- @esri/calcite-design-tokens

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍫 Verified locally on `main`

`dist` folder includes `docs`
