### ISSUE TITLE
Include Stencil framework wrappers for VueJS

### ISSUE THREAD

**Issue by evanmosby** [Esri/calcite-design-system#8342]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

More recent versions of Calcite include [Stencil framework wrappers](https://stenciljs.com/docs/overview) for React and Angular. Would it be possible to include VueJS as well? The ArcGIS Monitor team recently migrated to using Vue 3.0 and TS - it would be quite helpful having more native type checking in the future!

### Acceptance Criteria

Stencil framework wrappers for Vue 3.0 included in future Calcite releases.

### Relevant Info

[VueJS Integration with Stencil | Stencil (stenciljs.com)](https://stenciljs.com/docs/vue)

### Which Component

All components

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Monitor

**Comment by geospatialem** [comment]
via @EmilyRagan:

> Hoping [the above] provide[s] wrapper components that would offer us TypeScript integrations for calcite components for things like prop completion and event handler types.

**Comment by geospatialem** [comment]
Spike to confirm the direction of web components across Esri and the direction for a Vue wrapper with Calcite.

**Comment by geospatialem** [comment]
Calcite is planning to adopt [Lit](https://lit.dev/) in the November breaking change release for `3.0`, which provides support to frameworks, with the exception of [React](https://lit.dev/docs/frameworks/react). With the migration to Lit, teams and users can leverage Vue and CC without a wrapper. Closing the above as support is already provided, and a Vue wrapper is not supported by Lit.
