### ISSUE TITLE
Color context (mode) tokens should only be applied with prefers-color-scheme when `.calcite-mode-auto` is applied

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8343]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When you change the light or dark appearance on a Mac, the light or dark color context tokens are applied automatically.

### Expected Behavior

Color context tokens should only be applied in css with prefers-color-scheme when a `.calcite-mode-auto` class is applied.

### Reproduction Sample

https://codepen.io/benesri/pen/RwgrjEx

### Reproduction Steps

1. Open a calcite-component that is not wrapped in a `.calcite-mode-auto` class
2. switch to the "light" or "dark" mode on your computer
3. observe the calcite-component does not change it's colors

### Reproduction Version

2.0

### Priority impact

p0 - emergency

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by omarkawach** [comment]
This is greatly impacting us on the ArcGIS Maps SDK for JavaScript components team. Watching.

**Comment by jmanke** [comment]
Dashboards is also seeing this in the authoring experience - dark mode will briefly flash before our theming logic kicks in (when system preference is set to dark).

**Comment by omarkawach** [comment]
Some examples of areas where the design system is dictating the styling for us 

Arcade editor (action)
![image](https://github.com/Esri/calcite-design-system/assets/49499098/e4eb4ccf-ea65-45ae-9092-9a625c033d99)

Our Storybook web component documentation site (tabs, chips, and cards)
![image (1)](https://github.com/Esri/calcite-design-system/assets/49499098/1cf8c220-baa4-4b4a-96d8-eb1e0b93c18c)
![image (2)](https://github.com/Esri/calcite-design-system/assets/49499098/069a8264-ae5a-4479-8ffa-594f077c43cd)
![image (3)](https://github.com/Esri/calcite-design-system/assets/49499098/18dfa91c-ffbc-4d21-be35-cf589f440fdf)

**Comment by geospatialem** [comment]
Verified in `1.12.0-next.7`  when the system settings are set to dark mode in Windows.
