### ISSUE TITLE
'\n' in token output files causing issues in Windows

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8350]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

'\n' is written into platform output in tokens

### Expected Behavior

tokens transformer should use npm `os.EOL` or `Prettier.format()`

### Reproduction Sample

N/a

### Reproduction Steps

1. try to run the token transformer on a windows machine
2. observe the token transformer fails to build

### Reproduction Version

2.0

### Relevant Info

Originally brought up by Ben in https://github.com/Esri/calcite-design-system/pull/8344#pullrequestreview-1766629720

### Priority impact

p1 - need for current milestone

### Impact

Blocking usage of token output files on Windows machines

### Calcite package
-  @esri/calcite-design-tokens

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on the `main` branch with Windows and git bash with the demo pages.
