### ISSUE TITLE
Tile Select: Remove dependency on Tile component

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#8351]
### Description

Move all UI and logic provided by `calcite-tile` into `calcite-tile-select`, without affecting any functionality of either component.

### Proposed Advantages

Removing `calcite-tile-select`'s dependency on `calcite-tile` will allow work to proceed on the new Tile redesign epic without breaking changes.  After this task is complete, redesign work on `calcite-tile` can proceed unhindered by any need to wait for a breaking change release since `calcite-tile-select` will continue to work independently. 

### Which Component

`calcite-tile-select`

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍭 Verified locally on `main`
