### ISSUE TITLE
List: drag handle cell should be accessible via arrow keys

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8366]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The drag handle can only be accessed using the tab key

### Expected Behavior

The drag handle can be accessed using ArrowRight key.

### Reproduction Sample

https://codepen.io/driskull/pen/ExrrdYW?editors=1000

### Reproduction Steps

1. Open sample
2. tab or focus to the list
3. Use right arrow to navigate within the list
4. Notice how the drag handle is not accessible that way.

### Reproduction Version

2.0.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍭 Verified locally on `main`
