### ISSUE TITLE
list: Add event for when a drag starts and ends

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8367]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add event for when dragging starts and when it ends

### Acceptance Criteria

Two events, one for when dragging starts and one for when it ends.

### Relevant Info

https://github.com/SortableJS/Sortable#options

### Which Component

list

### Example Use Case

In the Maps SDK, we need to know when a drag ends so we can revert the element being moved and let the VDOM handle the updating positioning of the element.

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍫 Verified locally on `main`
