### ISSUE TITLE
input-date-picker: Emits `change` event when `valueAsDate` is set programmatically when `range` enabled.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#8368]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calciteInputDatePickerChange` event is emitted when the user sets `valueAsDate` programmatically in range `calcite-input-date-picker`

### Expected Behavior

`calciteInputDatePickerChange` event shouldn't be emitted when `valueAsDate` is set programmatically. 

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/ZEwwqNa

### Reproduction Steps

1. Open the console in CodePen.
2. Observe that change event is emitted

### Reproduction Version

1.11.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified on `2.13.0-next.7`

No longer seeing event logged to console 
https://codepen.io/Ditwan-Price/pen/PorLGog?editors=1111
