### ISSUE TITLE
There are ESLint errors for a few rules 

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#8371]
### Summary

We have ESLint errors for the following rules

- `@typescript-eslint/no-duplicate-enum-values` - once [here](https://github.com/Esri/calcite-design-system/blob/81fab56c6e8a76623c3f0adcb3f9cde761f46b98/packages/calcite-components/src/components/resources.ts#L3-L6)
- `@stencil-community/reserved-member-names` - lots of places related to the `hidden` prop

- `@stencil-community/ban-exported-const-enums` a few places in `resource.ts` files e.g. [here](https://github.com/Esri/calcite-design-system/blob/81fab56c6e8a76623c3f0adcb3f9cde761f46b98/packages/calcite-components/src/components/resources.ts#L3-L6) and [here](https://github.com/Esri/calcite-design-system/blob/81fab56c6e8a76623c3f0adcb3f9cde761f46b98/packages/calcite-components/src/components/value-list/resources.ts#L5-L7)

### Desired Outcome

Resolve the ESLint errors (if possible) And re-enable the rules that were disabled in #8372

**Comment by jcfranco** [comment]
This was addressed by https://github.com/Esri/calcite-design-system/pull/9123. Closing!
