### ISSUE TITLE
Unnecessary scroll bar in calcite-color-picker in Chrome & Edge

### ISSUE THREAD

**Issue by tayMAPNeil** [Esri/calcite-design-system#8379]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

A small, unnecessary scroll bar appears next to the RGB / HSV input section of the color-picker. 

https://github.com/Esri/calcite-design-system/assets/124625149/3e911ee3-8509-4764-94dd-29f173ca4561

### Expected Behavior

No scrollbar should display. 

### Reproduction Sample

https://next.sites.afd.arcgis.com/calcite-design-system/components/color-picker/

### Reproduction Steps

1. Open the calcite-color-picker component sample on Chrome or Edge browser. 
2. See an unecessary scroll bar to the right of the HSV/RGB input. 

### Reproduction Version

1.10.0

### Relevant Info

This is not an issue on the FF browser. 

I was able to repro on a Windows PC using Edge or Chrome. My colleague on a Mac can also see the scrollbar on the sample page (image below). 
<img width="389" alt="image" src="https://github.com/Esri/calcite-design-system/assets/124625149/6051a18b-e055-491e-88ad-76c6bdbd3ee0">

Potentially related to https://github.com/Esri/calcite-design-system/issues/8139

### Regression?

1.9.0

### Priority impact

p3 - want for upcoming milestone

### Impact

Relatively minor impact, but would be nice to fix. We leverage the color-picker in various areas of Map Viewer. 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Thanks for filing, @tayMAPNeil! 

Will work towards a solution in the linked issue mentioned above, #8139, and will verify if the fix mitigates the above `color-picker` issue once implemented (_targeted for this month's release_).

**Comment by eriklharper** [comment]
Tested locally, and I'm no longer seeing the issue on latest.  I think this fixed it: #8399.

**Comment by DitwanP** [comment]
Like @eriklharper mentioned I think this was fixed with the issue he mentioned about. Closing this one.
