### ISSUE TITLE
calcite-action-bar: tooltip causing wrong width for action bar

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#8386]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Before and after look of right action bar when adding calcite-blocks in flow-item panel.
![image](https://github.com/Esri/calcite-design-system/assets/44481292/7abf1e9a-0627-423c-a5ea-7e9631d94f83)  ![image](https://github.com/Esri/calcite-design-system/assets/44481292/f7c9e090-28ba-4db2-b06d-3c75b4fd994e)

Contact me for a test case.

cc @driskull 

### Expected Behavior

Action bar width doesn't change.

### Reproduction Sample

N/A

### Reproduction Steps

Open MV and notice 2 action bars, right and left, in the viewer. Click on popup config action to open that panel. Then click 'add content' and 'Fields list'. Notice that the action bar on the left disappears and there is blank space at the right of the MV.
If you hover over the expand icon of the action bar it corrects itself.

### Reproduction Version

2.0.0

### Regression?

Yes

### Priority impact

p0 - emergency

### Impact

Very visible in MV

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment]
@AdelheidF can you try creating a reproduction of this to help with verification?

**Comment by AdelheidF** [comment]
Here is an attempt, but adding a block or re-ordering blocks doesn't cause it in this codepen.
https://codepen.io/afreitag/pen/JjxVMXQ

**Comment by driskull** [comment]
@kevindoshier could this also be caused by the MV not using version 2.0 at the time?

**Comment by AdelheidF** [comment]
not fixed with 2.1.0-next.8

**Comment by driskull** [comment]
I'll take another look. 👀

**Comment by driskull** [comment]
I can't reproduce this one. ok to close @AdelheidF?

**Comment by AdelheidF** [comment]
We installed a workaround using `overlayPositioning="fixed"` on `calcite-action-group` and `calcite-tooltip`. With that we don't see the issue anymore.

We can re-open if someone else runs into it.
