### ISSUE TITLE
chore(modal): update e2e tests with the dedicated `openClose` commonTests helper

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#8391]
### Description

Substitute e2e tests on modal with the new `openClose` commonTests helper that covers all of the existing cases.

### Proposed Advantages

This will simplify test setup, ensure testing consistency across all our `openClose` components, and enhance test maintainability.

### Which Component

modal

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by Elijbet** [comment]
We have 4 cases with `emit on [initialization] with animations enabled/disabled`. The only difference in the old setup that the helper doesn't cover is the user-initiated click option. Is there any significance in setting the `open` property directly versus calling a `click` method? 

I will go ahead and start on swapping the old tests with the new helper, and if this component has any specific testing considerations, we should enhance the helper instead with the missing options.

**Comment by jcfranco** [comment]
>  Is there any significance in setting the open property directly versus calling a click method?

Not at the moment, as open/close events emit whether triggered by user interaction or directly setting the `open` prop. We can enhance the helper as you suggested if this changes later (see https://github.com/Esri/calcite-design-system/issues/8453#issuecomment-1972146890).

Closing as verified.
