### ISSUE TITLE
Combobox - Make icon/label spacing consistent between dropdown items and selected item

### ISSUE THREAD

**Issue by rebollin** [Esri/calcite-design-system#8396]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The spacing between the calcite icon used in the combobox component is different than the spacing seen in the dropdown options.
![image](https://github.com/Esri/calcite-design-system/assets/121894974/fa1415d3-7010-44d9-a557-25830fd7f5e1)

### Acceptance Criteria

The spacing between the label and icon should be consistent between the selected option and dropdown options

### Which Component

Combobox input

### Example Use Case

We just switched to using the combobox in the Update Data modal. We noticed that the spacing is off and not adjustable.

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by ashetland** [comment]
@jcfranco @eriklharper I think this snuck in with the updates from #4326

**Comment by macandcheese** [comment]
![Screenshot 2023-12-11 at 10 26 16 AM](https://github.com/Esri/calcite-design-system/assets/4733155/214b7dd1-7068-4c21-b409-6174c352cd39)

There also seems to be some uneven spacing in Input, may be worth looking at all of these to make sure this is cleared up across the board.

**Comment by jcfranco** [comment]
@macandcheese Great catch. Let's create a separate issue for this since `combobox` doesn't use `calcite-input` internally.

**Comment by jcfranco** [comment]
@macandcheese It looks like spacing might look different depending on [the icon used](https://codepen.io/jcfranco/pen/gOEoJWg).

![Screenshot 2024-01-29 at 4 09 20 PM](https://github.com/Esri/calcite-design-system/assets/197440/5c295695-b390-4b57-af5b-f30412e56858)

**Comment by eriklharper** [comment]
> @macandcheese Great catch. Let's create a separate issue for this since `combobox` doesn't use `calcite-input` internally.

Perhaps it should?

**Comment by jcfranco** [comment]
☝️
![](https://media1.tenor.com/m/2M8-iXvYBJoAAAAC/maybe-robert-downey-jr.gif)

**Comment by geospatialem** [comment]
Verified in `2.5.0-next.2` with https://codepen.io/geospatialem/pen/XWGyLxg:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/91f4aafb-5e85-4467-9b3b-1ab756cb0fcf)
