### ISSUE TITLE
ListItem: Add event for when open is toggled

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8434]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add event for when open is toggled

### Acceptance Criteria

An event like `calciteListItemOpenToggle` to know when a user has toggled the open property via user interaction.

### Relevant Info

Need a way to know when a list item has been opened.

### Which Component

list-item

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍠 Verified locally on `main`

![image](https://github.com/Esri/calcite-design-system/assets/60022782/2babf523-0bc9-4302-9253-e05f68bacc59)
