### ISSUE TITLE
list: Add event details to calciteListDragStart and calciteListDragEnd events.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8437]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

list: Add event details to calciteListDragStart and calciteListDragEnd events.

### Acceptance Criteria

drag event details are added to the event.detail of these two events.

### Which Component

list

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍡 Verified locally on `main`

![image](https://github.com/Esri/calcite-design-system/assets/60022782/dc1f5154-b939-4cb4-b60f-d045c6b881a9)
