### ISSUE TITLE
filter: console warning is displayed on component load

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8457]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When loading the filter component, the following warning is always displayed.

```
console.warn(`No data was passed to the filter function.
    The data argument should be an array of objects`);
```

### Expected Behavior

This console warning is only shown to developers implementing the filter component.

### Reproduction Sample

https://codepen.io/driskull/pen/KKEPMrK

### Reproduction Steps

1. Load codepen
2. Open console

### Reproduction Version

2.1.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍮 Verified locally on `main`
