### ISSUE TITLE
list: newIndex event detail for calciteListOrderChange is incorrect when ArrowDown key is used

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8464]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

newIndex event detail for calciteListOrderChange is incorrect when ArrowDown key is used

### Expected Behavior

event detail should be accurate

### Reproduction Sample

https://codepen.io/driskull/pen/mdobRNz?editors=1000

### Reproduction Steps

1. open codepen
2. open console
3. click on first drag icon
4. hit the space key
5. hit the down arrow key
6. notice the newIndex is 2 when it should be 1.

### Reproduction Version

2.1.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
Hey @driskull, the original issue is fixed, but I was messing around with the sample and realized that when you do the same ArrowDown key on the last item in the list, then the `newIndex` says its `"0"` but it actually just moves to the second spot in the list. 

Do we want to do a separate issue for that or if you want to include it with this one.


https://github.com/Esri/calcite-design-system/assets/60022782/bfae4733-a93f-49b1-af57-33ec689926dd

**Comment by driskull** [comment]
Lets reuse this issue. We can reopen. Thanks for finding it!

**Comment by DitwanP** [comment]
🍭 Verified locally on `main`
