### ISSUE TITLE
calcite-list: selectedItems value inaccurate when list is filtered

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-design-system#8468]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If filtering is enabled on a calcite-list, the selectedItems property on the list only reflects selected items in the currently filtered data.

### Expected Behavior

I expect the selectedItems property to include all selected items even if they were previously selected but don't appear in the current list filter.

### Reproduction Sample

https://codepen.io/nid13240/pen/RwdbqoZ?editors=1010

### Reproduction Steps

1. open the codepen above
2. filter for "apple" and select "apple"
3. change the filter to "kiwi" and select "kiwi"
4. observe that the selectedItems property (which is printed below) only includes "kiwi" after the second selection even though "apple" is still selected

### Reproduction Version

2.1.0

### Priority impact

p1 - need for current milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified in `2.2.0-next.5`:

![verify-list-filter-selections](https://github.com/Esri/calcite-design-system/assets/5023024/8e4d304e-4048-49d7-aefb-b6d47e9d2edf)

**Comment by AdelheidF** [comment]
Looks good to me too, thanks!
