### ISSUE TITLE
[Combobox] When `selectionDisplay="fit"/"single"`, unexpected `delete` key UX

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8469]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When Combobox has "fit" (and has "overflowed") or "single" value for `selectionDisplay` - there is unexpected behavior when using the `delete` key and an empty input. It behaves as if it is in "all" value - deleting unseen Chips and unselecting the items.

https://github.com/Esri/calcite-design-system/assets/4733155/ed55142b-4e05-4df6-8837-576c517f562c

### Expected Behavior

I would only expect that behavior in "all", since the `delete` deletes a visible chip. As Chip have `closable`, maybe this is unexpected and users should be able to "arrow left" into a Chip Group and use the Chip close button interaction / focus to close?

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/KKEPrYP?editors=1000

### Reproduction Steps

1. Visit Codepen
2. Select items
3. Use `delete` in an un-filled input

### Reproduction Version

2.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `2.4.0` - adjusted the milestone to the January `2.2.0` release.
