### ISSUE TITLE
Handle: add property to prevent a handle from being deactivated on blur

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8485]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Handle: add property to prevent a handle from being deactivated on blur

### Acceptance Criteria

When a draggable item is moved, in cases with VDOM the handle is being deactivated because blur is being called during a keyboard move. This will allow the ability to temporarily disable the functionality during a keyboard move.

### Which Component

handle

### Example Use Case

N/A

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍬 Verified locally on `main`
