### ISSUE TITLE
[Table] When Table is `bordered`, double border can occur with slotted `table-footer` Table Rows.

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8508]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Currently, if you have a `bordered` Table, and Table Rows slotted in `table-footer`, a double border can result:

<img width="997" alt="Screenshot 2023-12-27 at 4 46 36 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/035bc82f-e283-4a08-af3f-e56e1e21d1c4">

### Expected Behavior

No double border
<img width="997" alt="Screenshot 2023-12-27 at 4 46 01 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/e5b59b86-5415-4718-9a8c-0a5187237d63">

### Reproduction Sample

-

### Reproduction Steps

-

### Reproduction Version

2.1

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍠 Verified locally on `main`
