### ISSUE TITLE
[List item] Child elements behavior can be toggled `open` without selection change and event dispatch

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8515]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A way to opt in to an stripped-down behavior when clicking a `list-item` that contains nested `list-item`s.

_Originally posted in https://github.com/Esri/calcite-design-system/issues/6544, diverging the two separate functions - selection and filtering - for development efforts._

cc @nwhittaker 

### Acceptance Criteria

Clicking the content area of a list-item with nested list-items:
* Toggle's the list-item's `open` property to show/hide the nested list-items.
* Does not mark the list-item as `selected` and does not trigger its `calciteListItemSelect` event.
* Does not deselect the previously selected list-item.
* Clicking any of the list-item's actions does not toggle the `open` property.

### Relevant Info

Originally posted in https://github.com/Esri/calcite-design-system/issues/6544, diverging the two separate functions - selection and filtering - for development efforts.

### Which Component

`list-item`

### Example Use Case

The Field Maps web app would like to use the calcite-list element to display the layers in a map. For group layers, nested layers are shown as child list-items.

Selecting a leaf layer navigates the app for further handling of the layer. However, the app does not provide further handling for group layers. They are treated more like folders that organize sets of layers -- so clicking them in the list should have no effect other than to drill down to leaf layers.

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
A figma resource was added via [this comment](https://github.com/Esri/calcite-design-system/issues/6544#issuecomment-1540964945) and [a follow-up comment](https://github.com/Esri/calcite-design-system/issues/6544#issuecomment-1544485296) to this [Figma file](https://www.figma.com/file/xsoNW0ysPJQUEi8WYFwFHz/List-selection-behavior-%5Bissue-6544%5D?type=design&node-id=509-24962):
 
![image](https://github.com/Esri/calcite-design-system/assets/5023024/9a5fd255-a6e6-44a3-b69d-6681477117ae)

**Comment by driskull** [comment]
> Toggle's the list-item's open property to show/hide the nested list-items.

The default action for a list item is selection. If selection-mode is "none" then we could open the nested list item if it has one if that is the request here.

> Does not mark the list-item as selected and does not trigger its calciteListItemSelect event.

I think the selection-mode of "none" is what this is for.

> Does not deselect the previously selected list-item.

I think the selection-mode of "none" is what this is for.

> Clicking any of the list-item's actions does not toggle the open property.

This should already be the case.

**Comment by ashetland** [comment]
I think some context was lost when this issue was split off from #6544. From this [comment](https://github.com/Esri/calcite-design-system/issues/6544#issuecomment-1540964945): 

> **Selection modes**
> Final proposal for revising the existing single and multiple selection-modes and adding children and multichildren can be found in this [Figma file](https://www.figma.com/file/xsoNW0ysPJQUEi8WYFwFHz/List-selection-behavior-%5Bissue-6544%5D?type=design&node-id=509-24962). See also the image below. This would be consistent with changes to Tree in issue https://github.com/Esri/calcite-design-system/issues/6912 and pr https://github.com/Esri/calcite-design-system/pull/6926.

The idea was to flush out the selection modes for List to match those in Tree so there would be modes where the parent List Item could act more like a folder. In `selection-mode="single | multiple"` these parent List Items would not be selectable and the hit target for expanding or collapsing would be the entire item and not just the chevron. `selection-mode="children | multichildren"` would match the current behaviors of List. cc @nwhittaker @ade10176 

Having said all that, it's possible we may need to revisit this strategy as part of our holistic design rethink related to #7100. cc @macandcheese @SkyeSeitz

**Comment by driskull** [comment]
> The idea was to flush out the selection modes for List to match those in Tree so there would be modes where the parent List Item could act more like a folder.

I don't think we would need to add these additional modes if we just add expand/collapse support to `list-item-group`s since they don't have any selection. I prefer this to adding additional modes that complicate the UX.

**Comment by driskull** [comment]
The figma changes proposed would introduce breaking changes. We don't want to alter the way the current single or multiple selection works.

**Comment by nwhittaker** [comment]
>I don't think we would need to add these additional modes if we just add expand/collapse support to list-item-groups since they don't have any selection. I prefer this to adding additional modes that complicate the UX.

Agreed with this and we actually have an enhancement request for expanding/collapsing groups at https://github.com/Esri/calcite-design-system/issues/6537.

>We would need a design for this in order to proceed

One design consideration is that we'd want to style top-level groups differently from nested groups. For example, the **Layers** and **Rivers** groups within this [prototype][1].

[1]: https://codepen.io/nwhittaker-esri/pen/bGxeMVq

**Comment by driskull** [comment]
Can we close this one in favor of #6537? We could triage it and get design started. cc @geospatialem

**Comment by geospatialem** [comment]
Based on the discussion above - closing in favor of #6537, which will support the collapsing of `list-item-group`s comprised of `list-items`
