### ISSUE TITLE
handle: Add public property for selecting a handle and a public event for when selection changes

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8522]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Handle should have a public property for setting whether or not its selected as well as an event that fires when a handle is clicked/toggled.

### Acceptance Criteria

Add public property for selecting a handle and a public event for when selection changes

### Which Component

handle

### Example Use Case

```
<calcite-handle selected onCalciteHandlechange={...} />
```

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍭 Verified locally on `main`
