### ISSUE TITLE
ListItem: Add ability to programmatically set drag selection

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8523]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

- Add a property to set the drag handle as selected
- Add an event for when the drag handle has been selected
- This allows the ListItem the ability to store the state of being selected for drag in cases where the VDOM needs to recreate the element.

### Acceptance Criteria

- `dragSelected` or `dragHandleSelected` property
- `calciteListItemHandleChange`  or `calciteListItemDragHandleChange` event.

### Which Component

ListItem

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍮 Verified locally on `main`
