### ISSUE TITLE
`<calcite-list-item>` elements with `hidden` attributes are visible

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#8539]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `<calcite-list-item>` elements with `hidden` attributes are visible.

### Expected Behavior

The `<calcite-list-item>` elements with `hidden` attributes are hidden.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/MWxaLRp

### Reproduction Steps

1. Open the repro sample.
2. See the hiking trails and waterfall list items are visible despite having `hidden` attributes.

### Reproduction Version

2.1.0

### Relevant Info

Spun off from https://github.com/Esri/calcite-design-system/issues/6544#issuecomment-1874647103.

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by DitwanP** [comment]
🍠 Verified locally on `main`
