### ISSUE TITLE
Bug(calcite-slider):  [i18n-RTL] minus (-) is being added to right of the number for the tick-labels

### ISSUE THREAD

**Issue by gopal-y** [Esri/calcite-design-system#8544]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Minus sign displays to the right of the number when ticks is set to a number and labelTicks is enabled

```html
<div dir="rtl">
  <calcite-slider
    label-ticks="true"
    max="10"
    min="-10"
    ticks="5"
    value="5"
   />
</div>
```
![image](https://github.com/Esri/calcite-design-system/assets/30383517/588a7272-7182-440f-84c5-6d06fc6f5be6)

### Expected Behavior

Minus sign displays to the right of the number when ticks is set to a number and labelTicks is enabled

### Reproduction Sample

https://codepen.io/im-the-developer/pen/KKEdEQX

### Reproduction Steps

This can be reproduced by 
1. setting up the container direction to `rtl`
2. setting label-ticks="true", a range using min and max

### Reproduction Version

2.1.0

### Relevant Info

- This behavior occurs in RTL languages.

- This behavior also occurs on FF/Edge Chromium/Safari browsers.

### Priority impact

p1 - need for current milestone

### Impact

impacts widgets used in MapViewer

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
@gopal-y It looks like this was a previously reported issue in #3167. 

Updated the original issue's context from the content added above and added some team context to MV and the Maps SDK team. Calcite team members will triage the issue in an upcoming milestone for mitigation.

Closing out the above in favor of #3167.
