### ISSUE TITLE
[Design tokens] Support focus with tokens previously named `--calcite-ui-focus-color`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8548]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

With `2.x` we've moved into a new naming convention for tokens. There doesn't appear to be a focus token available, where previously there was a `--calcite-ui-focus-color` variable in `1.x`. We are still able to leverage the `--calcite-color-brand` token, but that doesn't seem like it fits the use case.

Is this something we should make available, and/or if that is the intent to drive folks to the `--calcite-color-brand` token?

cc @alisonailea 

Below is a screenshot from [this sample](https://codepen.io/geospatialem/pen/wvOMMwe) showcasing the behavior when trying to leverage `--calcite-ui-focus-color`, which is no longer available in `2.x`:
![focus-color-current](https://github.com/Esri/calcite-design-system/assets/5023024/29f43f4b-b83d-41dc-8762-7f36b64cf774)

### Expected Behavior

Would expect we'd have support for folks to define both a `--calcite-color-brand` and `:focus` color, if they choose to do so, similar to what was [proposed in March 2023](https://github.com/Esri/calcite-design-system/issues/3392#issuecomment-1481920535).

> Add two CSS variables for customization at the root or component level (actual text TBD):
> 
> - `--calcite-ui-focus-offset` (default to what is currently most common (-2px?))
> - `--calcite-ui-focus-color` (defaults to ui-brand)

![focus-color](https://github.com/Esri/calcite-design-system/assets/5023024/40619ea0-07f9-4955-8866-60d0f3e78a4f)

- [ ] Also refer to https://github.com/Esri/calcite-design-system/issues/6857 for the differing uses of brand and focus colors.

### Reproduction Sample

https://codepen.io/geospatialem/pen/wvOMMwe

### Reproduction Steps

1. Open the [1.11 sample with `--calcite-ui-focus-color`](https://codepen.io/geospatialem/pen/wvOMMwe)
2. Observe the sample works as-expected with `1.11.0`
3. Comment out the `1.11.0` libs
4. Uncomment the `2.1.0` libs
5. Observe the focus color and offset is not available in `2.1.0`
6. Open the [updated `2.1.0` sample](https://codepen.io/geospatialem/pen/zYbGPqm)
7. Observe the `--calcite-color-brand` token example works as a workaround to assign the specified color to the component's `:focus`. ~However there is no workaround for `--calcite-ui-focus-offset-invert`~ Update: It looks like there is an updated prop of `--calcite-offset-invert-focus`, but the legacy variable is not available.

### Reproduction Version

`2.1.0`

### Regression?

`1.11.0`

### Priority impact

p2 - want for current milestone

### Impact

Seems like something we should prioritize with the upcoming Online 24.R1 release.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Additional context on the previous implementation of `--calcite-ui-focus-offset` in the previous `global.scss` file: 
https://github.com/Esri/calcite-design-system/blob/4081bb9bc50d2994ebd46df54400412009da4691/packages/calcite-components/src/assets/styles/global.scss#L53

**Comment by maxpatiiuk** [comment]
Can you please clarify if `--calcite-ui-focus-offset-invert: 0;` would make outline be inside the element, or would it just set offset to 0 (but still have outline outside the element)?

**Comment by geospatialem** [comment]
> Can you please clarify if `--calcite-ui-focus-offset-invert: 0;` would make outline be inside the element, or would it just set offset to 0 (but still have outline outside the element)?

Adding context in addition to our chat, [here's some context when it was implemented](https://github.com/Esri/calcite-design-system/issues/3392#issuecomment-1520931324) in April 2023 and a [codepen updated to 2.1.0](https://codepen.io/geospatialem/pen/PoLzzjg). When the `--calcite-offset-invert-focus` is set to `1`, it will hug the component, if supported.

**Comment by geospatialem** [comment]
Verified in `2.5.0`.
