### ISSUE TITLE
[Icon] Add support for a new token for the component's color and remove last remaining `-ui-`named css var

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8549]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Update the `--calcite-ui-icon-color` to reflect our new naming convention without the `-ui-` reference, in alignment with our other tokens.

Related issue: #7180

### Acceptance Criteria

- [x] Add a component token for `icon`, currently depicted as `--calcite-ui-icon-color`
- [x] Continue to support `--calcite-ui-icon-color` as a legacy option for folks, deprecating the current value

### Relevant Info

Pertains to the component specific css:
https://github.com/Esri/calcite-design-system/blob/624c8b47e9f25b16be76711f7e9fa134125cc76b/packages/calcite-components/src/components/icon/icon.scss#L6

### Which Component

`icon`

### Example Use Case

Current implementation: https://codepen.io/geospatialem/pen/gOEPrYz

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-design-tokens

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
