### ISSUE TITLE
[Input Date Picker] Overlapping focus state styles

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8555]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The Input Date Picker, when in `layout="vertical"` has some strange focus behavior:

![Screenshot 2024-01-04 at 10 49 09 AM](https://github.com/Esri/calcite-design-system/assets/4733155/f1a81103-0a04-423c-9f73-b77a9a1ae6eb)
![Screenshot 2024-01-04 at 10 48 55 AM](https://github.com/Esri/calcite-design-system/assets/4733155/ba44e297-7d6f-40dc-9017-b97e0fbac663)

https://github.com/Esri/calcite-design-system/assets/4733155/ff7af231-dc5b-46a2-b3c6-66894fcdbcdb

Clicking a second time will show the full outline.

### Expected Behavior

I'd expect a different display that doesn't have a "missing" portion of the border covered by the arrow. Maybe when one is focused the icon can be hidden, allowing a full focus outline that happens on the "second click" currently.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/wvOMXxZ?editors=1000

### Reproduction Steps

1. Open codepen
2. Focus one of the inputs

### Reproduction Version

2.1

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Addressing in #6721 since the new design will no longer rely on the range arrow between calendar icons.
![image](https://github.com/Esri/calcite-design-system/assets/29716057/b7352d50-a2d3-4d99-b38b-a776cc0eabb7)
