### ISSUE TITLE
[List] Add a notice when list items are filtered down to no results.

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#8564]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently when a list component is filtered, and there are no results, there is no indication that the filtered list contains no items.
<img width="205" alt="image" src="https://github.com/Esri/calcite-design-system/assets/2636825/1de8c650-9bfd-407c-b079-420333ea02f6">

It would be nice if a calcite notice was presented to users when the list is filtered down to zero list items. Possibly something like this: https://codepen.io/mtb-alan/pen/JjzGvJP
<img width="214" alt="image" src="https://github.com/Esri/calcite-design-system/assets/2636825/f71c6ef8-3d10-4d0b-aaaf-f21dc388adb9">

cc @driskull @asangma @geospatialem

### Acceptance Criteria

Some sort of notification to users that no list items remain.

### Relevant Info

This has been requested as part of the ArcGIS Maps SDK Layer List widget redesign.

Related issue: https://github.com/Esri/calcite-design-system/issues/6133

### Which Component

List

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by macandcheese** [comment]
I feel like this should be up to the implementing team. 

Maybe a team wants to display a simple message-only Notice, but maybe it's a notice populated with title, description, icon, or it's another type of content entirely.

It should be pretty simple to have a conditionally displayed Notice based on the length of `filteredItems` property:

https://codepen.io/mac_and_cheese/pen/ZEPWbWL?editors=1000

**Comment by macandcheese** [comment]
If we want the List / Filter component to handle the show / hide of this arbitrary content, maybe a "no results slot" that is conditionally shown?

**Comment by driskull** [comment]
I like the idea of the slot since it would make it a lot easier to implement and still allow it to be customizable.

**Comment by sagewall** [comment]
I like the slot idea as well

**Comment by driskull** [comment]
To clarify, this slot is only for when a filter exists? or would we want it displayed anytime there are no items within the list?

**Comment by driskull** [comment]
@geospatialem we already have the aria live notifying the user of filtered results. Do we need to also make this slot content `aria-live="polite"`?

**Comment by geospatialem** [comment]
> @geospatialem we already have the aria live notifying the user of filtered results. Do we need to also make this slot content `aria-live="polite"`?

Yes, good call out 👍🏻 

Adding another live region will be helpful for AT. The polite setting seems sufficient, and would announce when other content is done reading.

**Comment by geospatialem** [comment]
Verified on the `main` branch and with `2.2.0-next.14`:

```html
<calcite-list filter-enabled filter-text="banana" selection-appearance="border" selection-mode="single">
  <calcite-notice slot="filter-no-results" icon kind="warning" scale="s" open>
    <div slot="title">No fruits found</div>
    <div slot="message">Try a different fruit?</div>
  </calcite-notice>
  <calcite-list-item label="Apples" value="apples"></calcite-list-item>
  <calcite-list-item label="Oranges" value="oranges"></calcite-list-item>
  <calcite-list-item label="Pears" value="pears"></calcite-list-item>
</calcite-list>
```

cc: @driskull It doesn't sound like JAWS or NVDA is picking up content from the `"filter-no-results"` slot, even with a `p` or `span` tag (even when adding the `role="region"` to the slot. Think it might be related to the shadow dom, however both are picking up that 0 records are displaying, so it still seems like we're covered in providing context to users.
