### ISSUE TITLE
Create an Angular template app for troubleshooting/reporting Angular specific bugs 

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#8567]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

We should have an Angular environment available for users to use when reporting Angular related issues, similar to how we have one in place for React. 

### Acceptance Criteria

- We should have a Codesandbox, or something similar for Angular - similar to the [React template](https://codesandbox.io/p/sandbox/calcite-react-template-p95kp?file=%2Fsrc%2FApp.js)

- The issue templates should be updated to include the new Angular one, which should be included in the following templates:
    - [a11y](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=a11y%2Cbug%2C0+-+new%2Cp+-+high%2Cneeds+triage&projects=&template=accessibility.yml)
    - [bug](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=bug%2C0+-+new%2Cneeds+triage&projects=&template=bug.yml)

### Which Component

N/A

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in the a11y and bug issue templates on the `main` branch. ✨
