### ISSUE TITLE
[Input] Make 'resize' property available for use with 'textarea' Input type

### ISSUE THREAD

**Issue by pllcoster** [Esri/calcite-design-system#8568]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently when using a `calcite input` component with its `type` property set to `textarea`, there is no easy way to set the `resize` css property of the `textarea`. In particular to set this property when using the React calcite components appears to require accessing the textarea inside a shadow root via refs.

In the case of the dedicated `calcite textarea` component, there is a `resize` property available for this purpose. This meets our needs for the time being, however the overall component style and some of its functionality is different compared to the 'Input' textarea.

### Acceptance Criteria

New `resize` property on the Input component allowing the css `resize` property of the textarea to be set, similarly to the calcite 'TextArea' `resize` property.

### Which Component

Input

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Knowledge

**Comment by geospatialem** [comment]
The [Text Area](https://developers.arcgis.com/calcite-design-system/components/text-area/) component should be leveraged using its `resize` attr/prop in coordination with the `columns` and/or `rows` attrs/props. 

```html
<calcite-text-area resize="both" rows="4"></calcite-text-area>
```

The Input's `type="textarea"` is aimed for deletion in an upcoming release - if there are specific enhancements needed to the Text Area, the Calcite team can help evaluate a solution or we can reopen and repurpose the above. Currently closing as unplanned.
