### ISSUE TITLE
[combobox] combobox filterDisabled item disappears when textLabel changes

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-design-system#8609]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `calcite-combobox-item` with `filterDisabled` turned on will disappear if we change the `textLabel` props dynamically when watching for `calciteComboboxFilterChange`

![combobox](https://github.com/Esri/calcite-design-system/assets/37349324/9f75a277-55b2-4939-874c-586a14d769f1)

### Expected Behavior

Such items should still be when the `textLabel` changed

One use case is when we want to show `Create new folder` text by default and when there is no filter result found, we will show `No result, create <filter text> name?`

### Reproduction Sample

https://codepen.io/ptmdmusique/pen/bGZgaoX?editors=1000

### Reproduction Steps

1. Open codepen
2. Click on the filter and start typing
3. Notice when the item is still there when start typing the first few characters but then disappears 

### Reproduction Version

~2.1.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Created https://github.com/Esri/calcite-design-system/issues/8707, which considers an empty state of the component - separate from the bug reported above.

**Comment by jcfranco** [comment]
The original issue was fixed by https://github.com/Esri/calcite-design-system/issues/7212 (see [updated repro case](https://codepen.io/jcfranco/pen/OJYEXLK?editors=1000)).

**Comment by geospatialem** [comment]
Verified in `2.10.0-next.8` with https://codepen.io/jcfranco/pen/OJYEXLK.
