### ISSUE TITLE
calcite action with slot as header-menu-actions no longer calls onclick

### ISSUE THREAD

**Issue by previnWong** [Esri/calcite-design-system#8628]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If you have a calcite-action with a slot as "header-menu-actions", the onclick event does not fire.  If you change to "control" the onclick fires. But I lose the drop down menu that it creates.

click no longer works (header-menu-actions)
![image](https://github.com/Esri/calcite-design-system/assets/11183838/ec318ea6-5973-4fcc-9b44-2814a7032d4e)

click works (control)
![image](https://github.com/Esri/calcite-design-system/assets/11183838/fc0bceb6-40e1-46a6-bb1a-93af7845d33d)

### Expected Behavior

action with slot "header-menu-actions" use to fire the onclick event.

### Reproduction Sample

https://codepen.io/pwongEsri/pen/MWxmbRr?editors=1000

### Reproduction Steps

switch the slot in line 16 - from control to header-menu-actions to see the onclick event no longer fires

### Reproduction Version

2.2.0

### Relevant Info

Windows, Chrome

### Regression?

worked on the version of calcite equal to JS Maps SDK 4.28

### Priority impact

p2 - want for current milestone

### Impact

Users cannot remove the item in the block, thus widget will be broken

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Solutions

**Comment by nCastle1** [comment]
Not sure if its related, but I noticed blur-related issues with the LayerList with Widgets sample. Repro app: https://zrh-app-sd-2.esri.com/arcgis-play/f/L3uf
