### ISSUE TITLE
calcite-action-menu

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-design-system#8632]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

With 2.2.0, it appears that click events for `calcite-action` within a `calcite-action-menu` are not bubbling up or even being fired

### Expected Behavior

click events should work

### Reproduction Sample

https://codepen.io/kevindoshier/pen/BabdPgQ

### Reproduction Steps

1. Open the above sample
2. Click on the "Save" action-menu, then click and action within and see nothing is logged to the console
3. Switch to calcite 2.1.0, repeat above steps and see that the icon name is logged to the console

### Reproduction Version

2.2.0

### Regression?

2.1.0

### Priority impact

p0 - emergency

### Impact

We cant update MV to 2.2.0 until this is fixed since we rely on action-menus in a few places

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Thanks for reaching out! We just mitigated this via https://github.com/Esri/calcite-design-system/issues/8628 and https://github.com/Esri/calcite-design-system/pull/8627 yesterday.

If updating the Codepen to `2.2.1-next.1`, the statements are logging to the console: https://codepen.io/geospatialem/pen/mdoMGgB

@kevindoshier Can you confirm if the changes are resolved on your end as well?

**Comment by geospatialem** [comment]
Closing per the above discussion on a earlier fix. 🎉
