### ISSUE TITLE
[List/List Item] Add non-interactive option to remove hover/pointer changes

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8634]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

We restored `list`'s pointer and hover states for consistency in #6700, as it was previously supported and discussed when implemented in #6123.

![cursor](https://github.com/Esri/calcite-design-system/assets/5023024/216ac8ae-e4e8-4114-a241-6a6d4378639e)

We should add a new selection mode to remove the hover/pointer behavior for someone that wants the existing `selectionMode` of `"none"` and different styling.

![default](https://github.com/Esri/calcite-design-system/assets/5023024/b4279b7a-2788-4440-bb51-4e3c047a32bb)

### Acceptance Criteria

~~Add a new selection mode to remove the hover/pointer behavior for someone that wants the existing `selectionMode` of `"none"` and different styling.~~
~~Maintain the restored pointer behavior when `selectionMode` is `"none"`~~

- [ ] See [Calcite Design Solution](https://github.com/Esri/calcite-design-system/issues/8634#:~:text=Calcite%20(dev)-,Calcite%20Design%20Solution,-Based%20on%20team) below for final implementation.
- [x] Determine if other components, such as `chip-group` and `chip` should also have similar behavior. If so, a new issue, or issues if multiple components are impacted, can be created 
    -  _Note (via Aaron 🧠): not needed as the components do not have interaction states. When `chip` is used on its own or in a `chip-group` with `selection-mode="none"` they are not interactive._

### Relevant Info

Created as a result of the efforts of #6700 and related #6123.

Refer to https://github.com/Esri/calcite-design-system/issues/6700#issuecomment-1896911919 for more details.

This would also close #5664 based on this [comment](https://github.com/Esri/calcite-design-system/issues/5664#issuecomment-1972089356).

### Which Component

- `list`
- `list-item`

### Example Use Case

1. `2.2.0` example with default: https://codepen.io/geospatialem/pen/ExMvGZJ
2. `2.2.1-next.1` example with pointer: https://codepen.io/geospatialem/pen/XWGaopO

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

# Calcite Design Solution
Based on team discussion, we recommend the following:

Add an `interaction-mode=“interactive” (default) | “static”` prop. `static` removes interaction styling and pointer changes.

If using `static` with `selection-mode="single" | "single-persist" | "multiple"`, the `selection-appearance` modes would be affected in the following ways:
- `selection-appearance=“icon”` would still function in the `static` mode. The icon would remain the hit area for selection, but interaction styling and pointer changes would be removed from the main content area.
- `selection-appearance=“border”` would conflict with `static` mode.
  - This appearance mode necessitates the entire item being the hit area for selection.
  - Setting a selection mode, a border appearance, and static together would produce a developer warning message and fallback.
    - Falling back to `interactive` may make the most sense here as falling back to an icon appearance feels more disruptive and could be potentially more difficult for a user to debug.
    - Possible message (final language TBD): “selection-appearance=“border” requires interaction-mode=“interactive”.

**Comment by macandcheese** [comment]
Yeah, this could be useful for Chip Group. Ultimately it will be up to the implementer in this mode to ensure the user interaction with the element performs an action or gives user feedback somehow. 

It does kind of open the door to a kind of unmanaged selection mode, where dev-users could potentially end up building their own selection affordances, etc. so we could potentially end up with folks re-creating the other selection modes but with different UX.

We should consider which of these we want to use the “none” name for consistency. Dropdown for example has a “none” that would behave like this new selectionMode, if we say “none” has no interaction on hover then that will be an outlier (and maybe some other compoennts).

**Comment by asangma** [comment]
➕ from me on this one.
We could use this.

**Comment by macandcheese** [comment]
Another option could be an ‘interactionMode’ prop with “static” / “interactive” values like we added in Table. Maybe not quite the same but it could enable this in all selection modes, not just a single one. 

This could make the label area non focusable / hoverable in all selection modes, leaving the selection affordance and any action-slots interactive.

**Comment by ashetland** [comment]
Not sure how that would work in `selection-appearance="border"`

**Comment by ashetland** [comment]
Broad question about this one. Is this a selection mode or is it something that would disable selection modes altogether? Like readOnly? If readOnly, does that then get confusing if actions are slotted? Maybe not?

**Comment by ashetland** [comment]
Added design recommendations to the top. @geospatialem Not sure if we want to update the title or anything else?

**Comment by geospatialem** [comment]
Verified in `2.14.0-next.15` when `list` has `interaction-mode="static"` and `"selection-mode="none"`:

```html
<calcite-list interaction-mode="static" selection-mode="none">
    ...
</calcite-list
```
![verify-interaction](https://github.com/user-attachments/assets/7f083bc0-18c1-4f27-bbba-9866ee166db7)
