### ISSUE TITLE
Popup of the input-time-picker is not being closed when empty after clicking outside the control

### ISSUE THREAD

**Issue by pandzel** [Esri/calcite-design-system#8639]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Popup stays on the screen after clicking anywhere outside the control if no hours selected in the popup.

### Expected Behavior

Popup should disappear. It does disappear but after selecting full time in the popup. Also, input-date-picker works correctly in the identical scenario.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-picker/

### Reproduction Steps

- access https://developers.arcgis.com/calcite-design-system/components/input-time-picker/
- click on the control to open the popup
- without entering any value, click anywhere outside the control
- note that popup stays on the screen

### Reproduction Version

2.2.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by nwhittaker** [comment]
Seeing the same bug with non-empty time pickers as well ([repro][1]):

https://github.com/Esri/calcite-design-system/assets/421496/12288ab6-8197-41d1-b259-682c0a65e3b5

---
After opening the time picker by clicking its caret button, it doesn't exhibit the expected auto-close behavior (closed by outside click) until the user changes its value in the picker:

https://github.com/Esri/calcite-design-system/assets/421496/2e7b0e7c-d44b-4a0e-a150-9e1e67fcb5dc

---
Interestingly, if the non-empty picker is opened by clicking anywhere else on the input, the expected auto-close behavior is maintained:

https://github.com/Esri/calcite-design-system/assets/421496/3ff5fba3-1f50-47dd-810e-f10dfdda7db7

[1]: https://codepen.io/nwhittaker-esri/pen/QWPRKGE

**Comment by hgonzago** [comment]
We are also seeing this when working in the JavaScript SDK's Editor widget. Is there any update on when this could be addressed? We have gotten questions brought up from Enterprise and AGOL MapViewer users.

A note regarding this is that the issue only appears to happen if the time picker input is empty. If a value is added and then you click outside of it, it will close and allow another input to take focus.

Here is another standalone app showing this https://codepen.io/tristan-morrison/pen/abgKLmG

**Comment by geospatialem** [comment]
Reallocating to September to target Calcite's final 24.R3 release in September based on the priority discussed with @hgonzago, also mentioned in [her comment above](https://github.com/Esri/calcite-design-system/issues/8639#issuecomment-2310859180) as it impacts additional teams, including Enterprise and MapViewer. 💪🏻

**Comment by geospatialem** [comment]
Verified in `2.12.2-next.1`:

![verify-8639](https://github.com/user-attachments/assets/92dd81e4-6328-46a0-a942-f45ea0d6e476)

**Comment by hgonzago** [comment]
@geospatialem I'm still seeing the issue using the original sample app in the first comment which now points to 2.12.2. 

On my Mac, I've cleared out the cookies, tried it on Chrome, FF, and Safari but no dice.

Is there something else I need to do to get this to work properly?

**Comment by hgonzago** [comment]
Sweet, thank you Kitty. Figured I was missing something. Thanks for the quick reply :-)
