### ISSUE TITLE
[Table] Add a non-keyboard-navigable mode to Table

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8659]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, the Table component supports navigation and focus of Table Cell with arrow keys. This is useful, but not all the time - and will be more useful when we add built-in editable table cells and other datagrid functionality.

### Acceptance Criteria

Adds a new `interactionMode` property (or other name) that defaults to the current behavior, but supports a "none" mode that allows the Table to render without focusable Table Cell or keyboard navigation other than default browser behavior between areas like selection, pagination, etc.

### Relevant Info

Focusable content within Table Cell should not be impacted - these will still be keyboard navigable as expected. cc @geospatialem 

### Which Component

Table, Table child components

### Example Use Case

This will allow for more "static table" use cases where the datagrid-navigation  keyboard method could be unexpected.

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
The component now bypasses keyboard navigation, but during the PR review when JAWS and NVDA were active both tables and content were still accessible via keyboard. 

During verification observed both JAWS and NVDA can no longer access the content via [this codepen](https://codepen.io/geospatialem/pen/oNVQQOa) in `2.5.0-next.2`. cc @macandcheese
