### ISSUE TITLE
[List item] Multiple slotted actions are not keyboard accessible 

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8664]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When multiple `action`s are slotted in a `list-item`, after the first `action` the remaining elements are not keyboard accessible.

### Expected Behavior

The `tab` keys should navigate through the component and all of its slotted actions.

### Reproduction Sample

https://codepen.io/geospatialem/pen/qBvpKYO

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/qBvpKYO)
2. Try to navigate through the component with the `tab` key
3. Observe it gets stuck after the first slotted action, when more than one `action` is present
4. Change the version to `2.1.0`
5. Observe the keyboard functionality works as-expected

### Reproduction Version

`2.3.0`

### Relevant Info

Possibly related to https://github.com/Esri/calcite-design-system/issues/8493, the regression occurs between `2.1.0` and `2.2.0`

### Regression?

`2.1.0`

### Priority impact

p4 - not time sensitive

### Impact

High

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Enterprise

**Comment by DitwanP** [comment]
🍡 Verified locally on `main`
