### ISSUE TITLE
Add "readonly" prop/style to Combobox (match style of other "readonly" components).

### ISSUE THREAD

**Issue by JonUihlein** [Esri/calcite-design-system#8666]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Requesting a `readOnly` equivalent for Combobox, to match the styles of other `readOnly` inputs. We avoid using `disabled` to allow selection of text within the input. The styling of `readOnly` is different compared to `disabled` and makes the form look strange.

### Acceptance Criteria

A property to allow matching the styling of other `readOnly` inputs. 

### Which Component

Combobox

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍯 Verified on `main`
