### ISSUE TITLE
Nested List Items no longer correctly align

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#8667]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When any items are nested in a List, space for the expand affordance is not accounted for in all items, breaking nested alignment.
![CleanShot 2024-01-29 at 16 03 58@2x](https://github.com/Esri/calcite-design-system/assets/108549080/d2706c0c-5d14-491a-8629-848279e3cb85)

### Expected Behavior

When nested items are present in a List, the space for the expand affordance is accounted for in all items to maintain proper alignment.
![CleanShot 2024-01-29 at 16 03 36@2x](https://github.com/Esri/calcite-design-system/assets/108549080/1848cdf1-624b-4978-8666-6b7b27f77082)

### Reproduction Sample

https://codepen.io/ashetland/pen/VwRyOQa?editors=1000

### Reproduction Steps

Expand the second item and note the alignment of the children as well as the item at the top that has no children.

### Reproduction Version

v2.3.0

### Regression?

v2.1.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
Correcting this bug will result in the visual change depicted below
![Frame 304](https://github.com/Esri/calcite-design-system/assets/108549080/f890910a-aec8-498c-9e7c-9f8b03c2ef1d)

**Comment by ashetland** [comment]
This [Figma file](https://www.figma.com/file/91sfHrYNt0Il6B4pEZZ749/List-spacing%2C-sorting%2C-group-heading-%5B7100%5D-%5B8039%5D-%5B8242%5D-%5B8667%5D?type=design&node-id=982%3A37071&mode=dev) covers designs for this issue and multiple related design revisions for List. cc @driskull

**Comment by driskull** [comment]
@ashetland @SkyeSeitz  I have some concerns about the design summary...

The summary says that the "classic" mode should maintain existing padding and spacing. That would mean that each mode would have its own styles. Id rather ovoid that if necessary because its harder to maintain. I thought the purpose of these modes would just be how the chevron is rendered and takes up space?

Can we just revise the spacing/padding in all modes?

**Comment by driskull** [comment]
@asangma do you know why list uses a shadow to imitate a border? It seems like it was added way back when in this PR: https://github.com/Esri/calcite-design-system/commit/5a279fa08b8cf392b5c3a28e042fd0cec888745a#diff-eabf53fd207751173a994b841b67b64fe226fffdef099ebd21169883d20fa0f2R10

I'd like to use a real border instead if possible but wanted to check with you.

**Comment by asangma** [comment]
@driskull 

> do you know why list uses a shadow to imitate a border? 

This was a throwback habit to a time before good box standards. We can use a real life authentic certified border.

**Comment by ashetland** [comment]
@driskull I confirmed with @jcfranco that we'd like to wait on adding modes to List until later. I will open a new `breaking change` issue to address that.

To do for this issue should just be:
- [ ] update indent value to 1.5rem/24px
- [ ] update border implementation from a shadow to a border (`color.border.3`)

**Comment by driskull** [comment]
@ashetland thanks. I'll ping @jcfranco. Was hoping to be able to use the new "nested" mode in the Maps SDK widgets.

**Comment by driskull** [comment]
@ashetland ready for review.

**Comment by DitwanP** [comment]
🍠 Verified on `2.8.0-next.10`
