### ISSUE TITLE
Allow for rounding of inputs by variable

### ISSUE THREAD

**Issue by justinprather** [Esri/calcite-design-system#8673]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

It would be nice to situationally apply rounded corners to inputs, as we are targeting a more consumer-friendly visual design while also using Calcite.

### Acceptance Criteria

Able to customize. Perhaps through variable. 

### Which Component

[Calcite Input](https://developers.arcgis.com/calcite-design-system/components/input/)

### Example Use Case

Example: We are looking to add an obvious search input to the Calcite Navigation in the Hub management UI. It would be helpful if we could customize the display of the input.

![image](https://github.com/Esri/calcite-design-system/assets/40360522/e337477c-8fce-471f-99ca-717d701c6b87)

Youtube example:
![image](https://github.com/Esri/calcite-design-system/assets/40360522/19cb447c-0135-4f27-8b47-67e509406096)

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Hub

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
![image](https://github.com/user-attachments/assets/134b6898-7754-48f2-b333-e5985ebcefe4)
