### ISSUE TITLE
chip: Do not render calcite-icon unless an icon is needed to display

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8674]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

calcite-chip internally renders a calcite-icon without assigning a icon property to it. 

### Expected Behavior

Instead, do not render the calcite-icon internally

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/chip-group/

### Reproduction Steps

1. Set selection-mode to "single"
2. verify that no internal icon components are rendered when a chip is not selected

![image](https://github.com/Esri/calcite-design-system/assets/1231455/df598834-56a2-42e0-a9e2-7367bb6ff9a7)

### Reproduction Version

2.3.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍬 Verified locally on `main`
