### ISSUE TITLE
Input message animates on DOM attachment

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#8677]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When attaching a `<calcite-input-message>` element to the DOM, the size of the message fluctuates:

https://github.com/Esri/calcite-design-system/assets/421496/bca5c49a-33a0-4705-a0b9-ab320213c805

### Expected Behavior

The size of the message does not fluctuate:

https://github.com/Esri/calcite-design-system/assets/421496/de781aea-552b-4f1d-826b-5917cf9e84d9

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/yLwvEMK

### Reproduction Steps

1. Visit the reproduction sample
2. Click the **Validate** button to see the message (re)appear

### Reproduction Version

2.3.0

### Relevant Info

Similar to https://github.com/Esri/calcite-design-system/issues/4291.

### Priority impact

p3 - want for upcoming milestone

### Impact

Field Maps generates a form from user data. Each field in the form could show error or warning messages at various times in response to the user's interactions. Since the form could have any number of fields, we create input-message elements on-demand rather than all up-front (and initially hidden).

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by macandcheese** [comment]
Agreed we probably don’t need to animate in at all, just show or hide this.

**Comment by jcfranco** [comment]
This might be addressed by https://github.com/Esri/calcite-design-system/issues/8571.

**Comment by jcfranco** [comment]
Confirmed! https://codepen.io/jcfranco/pen/bGJGjEJ

**Comment by jcfranco** [comment]
Closing based on ☝️. Thanks!
