### ISSUE TITLE
[Input] Allow customization of prefix-text and suffix-text width

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8688]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The `prefix-text` and `suffix-text` functionalities of Input determine their width from the length of the provided string. This is expected, but in a situation where multiple Input are aligned, and the string lengths are different, it can cause visual misalignment.
![image](https://github.com/Esri/calcite-design-system/assets/4733155/acfccb6c-2777-4bc5-9969-9b6ff4d096eb)

### Acceptance Criteria

Css properties for `--calcite-input-prefix-text-width` and `--calcite-input-suffix-text-width` are exposed to allow for this customization.
![image](https://github.com/Esri/calcite-design-system/assets/4733155/d8d0d4b1-4725-4f49-abde-675bc77d6ebf)

### Relevant Info

@SkyeSeitz @ashetland - We'll likely want to decide if we "start-align" or "end-align" the `suffix-text` here. `prefix-text` seems safe to always "start-align". I suppose we could also decide this based on the `alignment` property of Input, should we want to.

We have https://github.com/Esri/calcite-design-system/issues/8154 to track general updates to this functionality, but these enhancements will be useful regardless of visual changes.

### Which Component

Input and any Input-based components that accept these options.

### Example Use Case

I have multiple Input stacked with varying `prefix-text` and `suffix-text` lengths. I'd like these to align.

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
For design expertise to determine support for the above.

**Comment by SkyeSeitz** [comment]
> @SkyeSeitz @ashetland - We'll likely want to decide if we "start-align" or "end-align" the suffix-text here. prefix-text seems safe to always "start-align". I suppose we could also decide this based on the alignment property of Input, should we want to.

Agreed "start-align" for prefix regardless of alignment. "end-align" for suffix as a default makes sense to me and "start-align" if input alignment is sent to end.

**Comment by DitwanP** [comment]
Was moved to `3 - installed` during design triage in order to verify that this is resolved by #8154. Could also be closed since it looks to essentially be the same thing @geospatialem thoughts?

**Comment by geospatialem** [comment]
@DitwanP SGTM! 🚀

**Comment by DitwanP** [comment]
Closing this issue out because it's been addressed in #8154
