### ISSUE TITLE
Hover actions disabled on icons that are slotted to a disabled list-item

### ISSUE THREAD

**Issue by nel11211** [Esri/calcite-design-system#8692]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

**This behavior began as of 2.2.0 and later.**

We have a few controls as list-items that include an info icon slotted to the end. When the user hovers this icon, it opens an info tooltip for the user. 

There are some cases where certain list-item controls are disabled, since the conditions for choosing that option are not met. But in such cases we still want the user to be able to read the info tooltip explaining the option by hovering the info icon.

The problem is that (as of 2.2.0) the tooltip will not appear if the list-item in which the reference element is slotted is disabled. In fact, even if we try to role our own tooltip triggered using native hover events, it still does not work.

### Expected Behavior

I'm not sure exactly what is expected from the perspective of the Calcite Design System as a whole. But from our team's perspective, we need tooltips to show up on slotted icons even if the parent list-item is disabled. Or we need some workaround that we aren't aware of.

### Reproduction Sample

https://codepen.io/nel11211/pen/qBvKoKB

### Reproduction Steps

1. Remove the `disabled` attribute on the `calcite-list-item`.
2. Hover the info icon on the far right.
3. **Tooltip appears as expected.**
4. Add the `disabled` attribute to the `calcite-list-item`.
5. Hover the info icon on the far right.
6. **Tooltip does not appear.**

### Reproduction Version

2.4.0

### Regression?

2.1.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Charts

**Comment by nel11211** [comment]
I see this may be a duplicate of https://github.com/Esri/calcite-design-system/issues/5664, but I'll leave it for Calcite team to make that determination.

**Comment by jcfranco** [comment]
@nel11211 Thanks for opening this issue. We'll be closing as a duplicate. FWIW, we'll be exploring adding an option to list items to not be interactive (w/o using `disabled`). This should help with your use case and also allow `disabled` to behave consistently across components (preventing interaction with the element and any respective children).

If you wouldn't mind, could you share a bit more info regarding the previous, working behavior? I tried version 2.0.0, but have not been able to get tooltips to show up on hover.
