### ISSUE TITLE
Focus not moving from menu button to items `calcite-action-menu`

### ISSUE THREAD

**Issue by vc2310** [Esri/calcite-design-system#8695]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

There are menu items that appears to receive focus when the menu button is activated, but the focus indicator remains visible on the menu button as well. Examples include:

"..." Add menu button
"Edit" menu item

### Expected Behavior

Focus should automatically jump to the first item in the menu when the menu is activated.

### Reproduction Sample

https://codepen.io/geospatialem/pen/poYVRWQ

### Reproduction Steps

1. Open the codepen.
2. Click on the menu and expand it.
3. Focus will be seen on both options like:
![image](https://github.com/Esri/calcite-design-system/assets/32973475/f5aacc3c-61a5-479b-aefe-38227de05639)

### Reproduction Version

2.4.0

### Priority impact

p3 - want for upcoming milestone

### Impact

This has been marked by Level Access as an accessibility issue. 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Enterprise

**Comment by driskull** [comment]
This is expected as its using the `active-descendant` method of focusing which is preferred.

https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/

I think we can close this one.

**Comment by driskull** [comment]
cc @geospatialem for confirmation and any other issues that may come up like this.

**Comment by geospatialem** [comment]
> This is expected as its using the active-descendant method of focusing which is preferred. https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/

Agreed, on the [active descendant doc](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_focus_activedescendant) it refers to:

> When the container has DOM focus, the value of aria-activedescendant on the container tells assistive technologies which element is active within the widget. Assistive technologies will consider the element referred to as active to be the focused element even though DOM focus is on the element that has the aria-activedescendant property. And, when the value of aria-activedescendant is changed, assistive technologies will receive focus change events equivalent to those received when DOM focus actually moves.

I updated the original Codepen, https://codepen.io/geospatialem/pen/poYVRWQ to wait for the component on ready, using async and await, to set it to `open` and use the `setFocus` method, so the context is shown programatically:

```js
// Wait until the component is ready
// Then set the component to `open` and call the `setFocus` method
(async () => {
  await customElements.whenDefined("calcite-action-menu");
  await document.querySelector("calcite-action-menu").componentOnReady();
  document.querySelector("calcite-action-menu").open = true;
  document.querySelector("calcite-action-menu").setFocus();
})();
```

> I think we can close this one.

Agreed - closing per https://github.com/Esri/calcite-design-system/issues/8695#issuecomment-1935157673 and the above.
