### ISSUE TITLE
[i18n-HCS]: <calcite-input-time-zone mode="name"/> ignore language setting and show time zone name in English

### ISSUE THREAD

**Issue by BLin2525** [Esri/calcite-design-system#8698]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

![image](https://github.com/Esri/calcite-design-system/assets/109546792/9d4b367f-1cc2-4d69-bdae-9fecf655fa13)

### Expected Behavior

Calcite should honor language setting and show the time zone name in the specified language. below mode="Offset" setting works 
![image](https://github.com/Esri/calcite-design-system/assets/109546792/d8d28609-4e1a-4cfa-b8b7-7b1f3d20d961)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-zone/

### Reproduction Steps

1, open https://developers.arcgis.com/calcite-design-system/components/input-time-zone/
![image](https://github.com/Esri/calcite-design-system/assets/109546792/25f966ab-4599-4a38-938a-97cccf661bb6)
2, click Edit button.
3, change body section into 
![image](https://github.com/Esri/calcite-design-system/assets/109546792/1a9e21d2-3675-4096-a5ef-5c38b72f44ba)
4, observe, the time zone name at the bottom of the page turns into English.

### Reproduction Version

2.2.0

### Relevant Info

Edge, Chrome on Windows 10

### Regression?

no, this is new found issue

### Priority impact

p2 - want for current milestone

### Impact

it affects downstream apps like ExB, with time zone name not being able to be localized.
![image](https://github.com/Esri/calcite-design-system/assets/109546792/f5756bef-d6d1-48ed-9c0e-466ee795ba3b)

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by jcfranco** [comment]
@ashetland We discussed this briefly and decided to translate values for this mode. Added the design label in case this needs additional considerations.

**Comment by ashetland** [comment]
Nope should be g2g, I think.

**Comment by jcfranco** [comment]
Based on https://github.com/Esri/calcite-design-system/issues/8005#issuecomment-2379789520, this would no longer be valid.

**Comment by geospatialem** [comment]
Verified with `3.0.0-next.42` in Firefox for `displayMode` of `"name"`, `"offset"`, and `"region"` with https://codepen.io/geospatialem/pen/wBwKwwE. 🎉 

_Note: There is a 🐛 with Chrome opened with https://github.com/Esri/calcite-design-system/issues/10895, where a [Chromium issue](https://issues.chromium.org/issues/381620359) has been logged to mitigate._
