### ISSUE TITLE
[Time Zone] Contents on 'time zone' dropdown list in FF browsers are inconsistent with the same dropdown list in other browsers

### ISSUE THREAD

**Issue by BLin2525** [Esri/calcite-design-system#8699]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

There are UTC, WET listed on the time zone dropdown list in firefox, while there is no such zone in other browsers like Edge and Chrome

![image](https://github.com/Esri/calcite-design-system/assets/109546792/3ab09b06-361d-44ce-82c5-049fc263f1dc)
 

### Expected Behavior

The content on the time zone dropdown list should be consistent across all browsers. such as below screen in Chrome
![image](https://github.com/Esri/calcite-design-system/assets/109546792/92008e1a-949e-48bc-bcb8-9ef00920f719)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-zone/

### Reproduction Steps

1. launch Firefox brower and navigate into https://developers.arcgis.com/calcite-design-system/components/input-time-zone/
2. click the properties icon on the top-right of sample  windows.
3. select "name" on the mode field.
4. move the scroll bar for the time zone input to bottom, 
5. observe, there are UTC, WET zones at the bottom. 

### Reproduction Version

2.2.0

### Relevant Info

FireFox in Windows 10, IOS, 

### Regression?

no, this is new found issue

### Priority impact

p3 - want for upcoming milestone

### Impact

This makes content of timezone in the downstream apps inconsistent between Firefox and other browsers.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by jcfranco** [comment]
Blocked by https://github.com/jcfranco/timezone-groups/issues/2 and https://github.com/jcfranco/timezone-groups/issues/1.

**Comment by jcfranco** [comment]
The changes required by `timezone-groups` _might_ be breaking, so it might be good to move this one to target our breaking change release. cc @geospatialem

**Comment by jcfranco** [comment]
This was addressed by #10289 as it made changes to use consistent, canonical time zones and also maps deprecated time zones to canonical ones. Thus, it should no longer be considered a breaking change.

**Comment by DitwanP** [comment]
🍡 Verified
