### ISSUE TITLE
[input-time-zone] Allow to show UTC instead of GMT with the input time zone picker offset mode 

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#8716]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The current input time zone offset mode only allow to show GMT. Is it possible to support showing UTC as an option.

### Acceptance Criteria

Support showing UTC as an option.

### Which Component

calcite-input-time-zone

### Priority impact

p4 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Survey123

**Comment by jcfranco** [comment]
@fendiaoxiaoshuazi Thanks for submitting this issue. Would you mind sharing more details behind this request? Is this about enhancing the existing "offset" mode or would this need to introduce a new mode that mainly displays UTC options a certain way?

**Comment by fendiaoxiaoshuazi** [comment]
Hi, @jcfranco, we would like an enhancement to the existing "offset" mode. Currently, the "offset" mode can only show "GMT", and we would like an option to switch "GMT +/- *" to "UTC +/- *". 
![image](https://github.com/Esri/calcite-design-system/assets/26078106/e90b09fd-638d-46ce-9773-784387f44b1e)

Like the time zone picker of Scene Viewer.
![image](https://github.com/Esri/calcite-design-system/assets/26078106/e037dd75-8cac-4fe4-b2ad-b23a63e6b233)

**Comment by fendiaoxiaoshuazi** [comment]
Currently Survey123 connect and field app use the UTC for the time picker. The web app utilizes the Calcite input-time-zone show GMT. Therefore, we need the UTC mode in the Calcite input-time-zone to make them consistent.

Here are the reasons why we choose UTC:
- According to Anna:
> The general guideline for all Esri  products is to follow UTC, not GMT. So if you display UTC – you’re good and don’t need to change anything.

**Comment by jcfranco** [comment]
Belated thanks for the info, @fendiaoxiaoshuazi!

Adding related issue: https://github.com/Esri/calcite-design-system/issues/9018.

**Comment by jcfranco** [comment]
Moved to the June release as this is needed for #9018. cc @geospatialem

**Comment by geospatialem** [comment]
Verified in `2.10.0-next.10` with the new `offset-style` attribute (`offsetStyle` prop) with the following values:
- `"user"` (_default_)
- `"gmt"` and
- `"utc"`

For example:
```html
<calcite-input-time-zone offset-style="utc"></calcite-input-time-zone>
```

![image](https://github.com/Esri/calcite-design-system/assets/5023024/ad84b314-f567-49b6-818b-630f5cfbbc7b)
