### ISSUE TITLE
[combobox] `selection-mode="single-persist"` doesn't work correctly when items have same values

### ISSUE THREAD

**Issue by dasa** [Esri/calcite-design-system#8720]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If there are multiple items with the same values, you can't select between them and they both appear selected when using `selection-mode="single-persist"`. This isn't an issue with "single" selection mode.

<img width="954" alt="image" src="https://github.com/Esri/calcite-design-system/assets/828058/5091c7f2-6b43-46d0-b4a2-a250f737f7b3">

### Expected Behavior

You can select each item individually.

### Reproduction Sample

https://codepen.io/dpaddock/pen/oNVPKOz?editors=100

### Reproduction Steps

Select Mining, and then try to select Mining 2.

### Reproduction Version

2.4.0

### Relevant Info

Chrome 121

### Priority impact

p3 - want for upcoming milestone

### Impact

Can workaround for now by using "single" selection mode.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Related https://github.com/Esri/calcite-design-system/issues/8043

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`

The behavior now allows each item to be selected individually.  

https://github.com/user-attachments/assets/b0fccf4c-0155-430b-8b3d-45de0d7e8520
