### ISSUE TITLE
[combobox-item] Update component's props for consistency

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#8737]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

1. Deprecate textLabel in favor of heading
2. Add heading prop, which will fallback to textLabel if unspecified
3. Add label, which will fallback to value if not specified

2 and 3 naming would align with [#8737](https://github.com/Esri/calcite-design-system/issues/8737)

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
We should consider adding a `label` property, where we deprecate the `textLabel` property.

`label` should be required, where `value` should be optional.

_Of note, if we add in a `description` property, the `label` (or "heading" takes precedence for AT)._

**Comment by jcfranco** [comment]
Sharing for posterity, for this release we would:

1. deprecate `textLabel` in favor of `heading`
2. add `heading` prop, which will fallback to `textLabel` if unspecified
3. add `label`, which will fallback to `value` if not specified
4. create issue to drop `textLabel` prop and make `heading` required and `value` optional by 4.0

2 and 3 naming would align with [#8737](https://github.com/Esri/calcite-design-system/issues/8737).

**Comment by aPreciado88** [comment]
@jcfranco @geospatialem I created this [issue](https://github.com/Esri/calcite-design-system/issues/9989) to follow up on:

`create issue to drop textLabel prop and make heading required and value optional by 4.0`

**Comment by DitwanP** [comment]
🍡 Verified locally
