### ISSUE TITLE
Combobox Item shows the type for the value property as a string instead of any

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#8738]
### Description

Change the type of the `value` property to be `any` instead of `string`.

### Which Component

`combobox-item`

### Resources

[Combobox Item value property](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#api-reference-properties-value)

**Comment by macandcheese** [comment]
@DitwanP can you open this in the docs repo - no action is needed in this repo? There is an open PR in that project to change how we display types in the reference which should resolve this. Thanks!
