### ISSUE TITLE
Add guidelines for local package patching

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#8755]
### Summary

We should have guidelines defined for when we need to do local patching on a dependency and how to go about doing the patching.

### Desired Outcome

Guidelines for patching dependencies in a markdown format stored on this repository

### Resources

https://github.com/Esri/calcite-design-system/pull/8751#pullrequestreview-1881541898

**Comment by jcfranco** [comment]
Created [wiki entry](https://github.com/Esri/calcite-design-system/wiki/patching-packages) for patching packages. 

@driskull @geospatialem @DitwanP Since it's a wiki page, can y'all help review?

**Comment by driskull** [comment]
Looks good!

**Comment by geospatialem** [comment]
> Since it's a wiki page, can y'all help review?

Agree with Matt, this is great doc! 🏆

**Comment by geospatialem** [comment]
Verified in the [wiki under patching packages](https://github.com/Esri/calcite-design-system/wiki/patching-packages) 📦
