### ISSUE TITLE
Fix miscellaneous chores entries for synced version updates

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8763]
### Description

https://github.com/Esri/calcite-design-system/pull/8762 fixed an issue causing synced version updates in the changelogs to look like the following (notice `undefined` below):

> ## [2.2.0](https://github.com/Esri/calcite-design-system/compare/@esri/calcite-components-react@2.1.0...@esri/calcite-components-react@2.2.0) (2024-01-17)
> 
> ### Miscellaneous Chores
> 
> - **@esri/calcite-components-react:** Synchronize undefined versions

### Which Component

React and Angular wrapper changelogs

### Resources

https://github.com/search?q=repo%3AEsri%2Fcalcite-design-system+%22synchronize+undefined+versions%22&type=code

**Comment by geospatialem** [comment]
Verified! ✅
