### ISSUE TITLE
Close button in tab-titles are slightly misaligned

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8772]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The close button is positioned flush on the top, but is not aligned with the bottom border.

<img width="160" alt="Screenshot 2024-02-16 at 1 58 49 PM" src="https://github.com/Esri/calcite-design-system/assets/197440/24b1c9b0-5a35-4faf-b7e1-6c1ec1974084">

![Screenshot 2024-02-16 at 3 01 18 PM](https://github.com/Esri/calcite-design-system/assets/197440/d1f77d3b-c49f-4272-a663-a5c8ef3bf6f7)

### Expected Behavior

The close button should either be flush or have the same offset on both top/bottom sides.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/tabs/

### Reproduction Steps

1. Enable the `closable` prop on the tab-title
2. Click on the component and tab to the close-button

### Reproduction Version

2.5.1

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.23` 👌
![image](https://github.com/user-attachments/assets/43bcd389-cadd-42c0-b86e-f7e6a164955b)
![image](https://github.com/user-attachments/assets/aef4e17c-c590-43e1-b34d-3c944126c0f5)
