### ISSUE TITLE
[Table] Complex Table Cell arrangements with `rowSpan` can have missing borders

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8778]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

In some complex cases, the expected border is not displayed when row or or cell combinations use `rowSpan`
<img width="930" alt="Screenshot 2024-02-19 at 9 00 11 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/9d2ddc11-e11a-47ea-b451-8d42e0554e4b">

### Expected Behavior

I'd expect the borders to be present
<img width="930" alt="Screenshot 2024-02-19 at 8 59 51 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/0d470195-0619-44f9-8e8f-6b1abdd6e3d8">

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/XWGGLgv?editors=100

### Reproduction Steps

1. Visit Codepen
2. View missing border
3. Change CDN links to 2.1
4. Notice border is restored

### Reproduction Version

2.5.1

### Relevant Info

This is only occurring in complex DOM set up - it is happening because of the way the "border classes" are determined and conditionally applied. Need to handle a case where the last item is not displayed as such due to `rowSpan` use.

### Regression?

2.1

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `2.5.2-next.2`.
