### ISSUE TITLE
[Combobox] Long placeholder text to remain truncated when input is active 

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#8792]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, the placeholder text loses its truncation when active. I don't believe this behavior provides any benefit since the placeholder text is not scrollable. 
Idle:
<img width="415" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/1ff79af1-701d-475e-b73b-b8b4927ae0ec">

Active:
<img width="417" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/d618c49f-b29a-44ea-8960-80d322fb439a">

### Acceptance Criteria

The placeholder text remains truncated when the Combobox input is active. 

### Relevant Info

Related: #7020

### Which Component

Comobobox

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by Elijbet** [comment]
Note that it is the browser's default functionality is to show the whole placeholder on active/focus, which is why it removes the applied ellipsis. But I agree that it isn't helpful here.

**Comment by SkyeSeitz** [comment]
Since we discovered the browser prevents us from trimming in focus/active modes and I am seeing this in other Design Systems thus far as well, we are good to close out this issue. We discussed the possibility of applying a fade out instead of the ellipsis, but concluded it it did not add much, where the cut off is a more common pattern.
