### ISSUE TITLE
Style tab container focus outline to align with other components

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8799]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Focusing on the tab container currently uses the default browser styling.

<img width="622" alt="Screenshot 2024-02-21 at 11 00 57 AM" src="https://github.com/Esri/calcite-design-system/assets/197440/4bdfdc74-58f7-4035-8bb5-0dc5291c9a27">
<img width="622" alt="Screenshot 2024-02-21 at 11 01 08 AM" src="https://github.com/Esri/calcite-design-system/assets/197440/f5d707da-4cd6-4bd9-92c1-aa8247c06d43">

### Acceptance Criteria

Tab container should use the same styling for the focus outline.

<img width="366" alt="Screenshot 2024-02-21 at 10 58 57 AM" src="https://github.com/Esri/calcite-design-system/assets/197440/b8dc6408-4135-4a4f-84e4-70c8fb6e84b3">

<img width="359" alt="Screenshot 2024-02-21 at 10 58 53 AM" src="https://github.com/Esri/calcite-design-system/assets/197440/58c6cae1-6f70-4d4f-bbad-00a789ce2344">

### Which Component

`calcite-tab`

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
I went ahead and submitted a PR for this since I had a local fix during the review of https://github.com/Esri/calcite-design-system/pull/8616/.

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.11` with Windows in Chrome:

![verify-tabs-focus](https://github.com/Esri/calcite-design-system/assets/5023024/84f3abe3-1996-410c-bba7-e75497ef4c46)
