### ISSUE TITLE
Replace animated selected tab-title indicator with simpler selection styling

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8800]
### Description

Simplification of tab-title was [suggested in #8616](https://github.com/Esri/calcite-design-system/pull/8616#issuecomment-1942738868):

> I suggest we get rid of the "zoom border animation", it is adding a bit of confusion to a crowded area (IMO). Just render the active state visual with a border or inset box-shadow.

### Proposed Advantages

* reduce component complexity
* avoid alignment issues
* streamline component design

### Which Component

`calcite-tab-nav`

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.23`
