### ISSUE TITLE
calcite-chip programatic selection

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-design-system#8801]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If I have a calcite-chip-group with selection-mode set to 'single' and I programmatically select chips within the group, the other chips remain visibly selected. 

### Expected Behavior

I expect all other chips to be automatically deselected when I programmatically select a chip in the group.

### Reproduction Sample

https://codepen.io/nid13240/pen/ZEPZjMN

### Reproduction Steps

1. open the codepen above (the first chip should be selected already)
3. click the button to programmatically select the middle chip
4. observe that two chips are selected

### Reproduction Version

2.5.1

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by DitwanP** [comment]
🍡 Verified on `2.8.0-next.16`
