### ISSUE TITLE
fix calcite-preset references to --calcite-color-brand

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8807]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Currently calcite-preset references to `--calcite--color-brand`

### Expected Behavior

calcite-preset should reference `--calcite-color-brand`

### Reproduction Sample

https://codepen.io/alisonailea/pen/bGZyWMp/b97c5c6b14ea56cfd81ce8b2e7af110f

### Reproduction Steps

1.  Open Dev Tools
2. find the .wrapper 
3. set :focus-within
4. notice the final fallback for the outline-color is --calcite--color-brand

### Reproduction Version

2.5.1

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `2.6.0-next.2`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a8a7eabb-c462-4cd6-be5d-4860e9c36b2a)
