### ISSUE TITLE
Calcite Loader 2.5.1

### ISSUE THREAD

**Issue by msamwill** [Esri/calcite-design-system#8824]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Loader not spinning https://developers.arcgis.com/calcite-design-system/components/loader/#Best%20Practices in Edge for Business, 121.02277.128.  Developer console errors refer to https://px.ads.linkin.com/wa.  Also not working in FireFox, developer consol states ignoring the less retricted referrer policy "no-referrer-when-donwgrade".

### Expected Behavior

Expect graphic in sample to be animated.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/loader/#Best%20Practices

### Reproduction Steps

1. go to sample page using latest version of Edge or FireFox https://developers.arcgis.com/calcite-design-system/components/loader/#Best%20Practices

### Reproduction Version

2.5.1

### Relevant Info

Windows 11 22H2.  Edge for Business v121.02277.128 (64-bit) or Firefox 123.0 (64-bit)

### Priority impact

p4 - not time sensitive

### Impact

Trying to test Calcite-Loader at version 2.5.1 with Chrome performance fix and animation is not working.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Tested with Windows 10 on Edge `v121.02277.128 (64-bit)` and FF `v121.02277.128 (64-bit)`, but am unable to reproduce. 

@msamwill Do you have animations disabled on Windows by chance? Here's a Microsoft Community post with some specifics pertaining to [Windows 11 and animations](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-animations-dont-work/5521ce0c-0a0e-4f05-9db0-6688f8dc9ba6).

Calcite provides support for folks that have animations disabled in Windows and reduced motion on Mac, which may be what you are experiencing.

**Comment by msamwill** [comment]
Thank you! Animations were turned off.  I'm not sure how that happened but it was in fact the cause of the issue.
