### ISSUE TITLE
Popover - Allow `flipPlacements` to allow logical placements such as `leading` and `trailing`

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-design-system#8825]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

In the `calcite-popover`, I would expect the `flipPlacements` to accept the same placement types as `placement`, but this doesn't seem to be the case. I wanted to use `leading` and `trailing` placements in `flipPlacements`, but it's not supported.

| `flipPlacements` | `placement` |
| ------------- | ------------- |
| <img width="988" alt="Screenshot 2024-02-23 at 8 01 25 AM" src="https://github.com/Esri/calcite-design-system/assets/19629809/f16e3b20-46ed-4533-b58b-00948e0be1c2">  | <img width="1047" alt="Screenshot 2024-02-23 at 8 02 46 AM" src="https://github.com/Esri/calcite-design-system/assets/19629809/d9a9d6c1-64e2-4c2f-a336-efa506e0e57f"> |

### Acceptance Criteria

Allow `flipPlacements` to use logical placements (like in `placement`) to support `leading` and `trailing` variations.

### Relevant Info

See [codepen](https://codepen.io/jmanke/pen/RwdzpWp) for example of `leading` and `trailing` not supported.

### Which Component

`calcite-popover`

### Example Use Case

I want my `flipPlacements` to be `rtl` aware for left/right placements - for example, I'd like the placement to fallback to the left in `ltr` mode, and to the right when in `rtl` mode.

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Dashboards

**Comment by geospatialem** [comment]
Verified in `2.10.0-next.0`:

![verify](https://github.com/Esri/calcite-design-system/assets/5023024/151a811f-89f4-4839-9429-07685fb4d530)
