### ISSUE TITLE
[Tile/Tile Group] Add selection behavior

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#8834]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As part of the Tile Redesign epic, Tile Groups need to support selection behavior.

### Acceptance Criteria

Tile Groups should support the following selection modes:

- [x] `none`
- [x] `single`
- [x] `single-persist`
- [x] `multiple`

Tile Groups should also support the following selection appearances:

- [x] `icon`
- [x] `border`

### Which Component

`calcite-tile` and `calcite-tile-group`

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍭 Verified locally on `main`
