### ISSUE TITLE
[Card] Slotted footer content can inherit defined styles

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8855]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Card's footer content can inherit the style set on all slotted content. Elsewhere, like `heading` and `description` slots, this is expected as by default this will be text content. For the Footer slots, this is less often the case and we should avoid setting this. As always users can override any style on content they slot themselves.

### Expected Behavior

These styles should not be applied by default.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/vYMYdEy?editors=1000

### Reproduction Steps

1. Open Codepen
2. View Issue

### Reproduction Version

2.6

### Regression?

2.5.1

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍠 Verified on `main`
