### ISSUE TITLE
Unable to drag-select all or some of label or validation message text

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#8867]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Double clicking on, or performing a drag selection (`mousedown` + `mousemove`), on an input's label or validation message text results in losing the selection and focus shifting to the input when the user ends the drag.

For switches, checkboxes, and radios, the input's `checked` property is toggled by a drag selection.

### Expected Behavior

Matching the native of behavior of when a drag operation is detected, focus is not shifted and the selection remains after the drag ends.

Double-clicking on a word in the label blurs the input after the second click and selects the word. Clicking within the validation message does not focus the input.

For switches, checkboxes and radios, the input's `checked` property is not toggled by a drag selection. To match the native behavior, double-clicking may toggle the property, but focus should not end up on the control.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/xxebVxo

### Reproduction Steps

1. Visit the repro sample
2. Attempt to make selections within the label and/or input message text of the first input
3. Attempt to make selections within the input message of the second input
4. Attempt to make selects within the labels of the switch, checkbox, and radio inputs

### Reproduction Version

2.10.1

### Relevant Info

If the input message is not considered part of the label, then ~resolving https://github.com/Esri/calcite-design-system/issues/6702 could fix selections within the input message shifting focus~. _- Never mind, it looks like the issue is still present with just an input message and no label. I'll update the repro._

One suggestion is to, in the label's click handler, bail if a [range selection][1] exists.

### Priority impact

p3 - want for upcoming milestone

### Impact

Impact is towards usability. In some cases error messages may contain error codes that the user may want to copy/paste.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Selection/type#range

**Comment by nwhittaker** [comment]
Not sure what happened to the codepen as it appeared to be missing the labels and messages. I updated it to the latest Calcite and to reflect the repro steps.

**Comment by driskull** [comment]
> Clicking within the validation message does not focus the input.

This one might need to be a separate issue. The `calcite-input-message` component is within other components and I also noticed that the click handler in input isn't ignoring this component so its setting focus when clicked.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.10`
https://codepen.io/Ditwan-Price/pen/zYVPvJj?editors=1010

Everything is working as expected except for the input with the validation messages. There is a separate issue to address this [here](https://github.com/Esri/calcite-design-system/issues/10006).
