### ISSUE TITLE
[Panel] Add `-space` css properties for `header-content` slot

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8907]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

It is common to slot rich content into the `header-content` slot of a Panel. Currently, they have baked-in padding that isn't always desirable - where slotted items are intended to be full-height.

I'd like to have the ability to remove this with a `calcite-panel-header-content-space` (or similarly named) css property.

### Acceptance Criteria

I have the ability to control the padding of the slots mentioned above.

### Example Use Case

<img width="333" alt="Screenshot 2024-03-07 at 9 19 06 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/4f9d4127-1fc2-4f63-8589-e11c1b872b0a">

<img width="319" alt="Screenshot 2024-03-07 at 9 20 15 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/899acd92-a53f-453f-9f50-4e7acebd5fe3">

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
Seems like `--calcite-panel-footer-space` already exists, missed that. Request stands for `header-content` 😄

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
![image](https://github.com/user-attachments/assets/88ff0847-91a0-43b1-a92a-3141604373c9)
