### ISSUE TITLE
Remove Docs tab from storybook

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8911]
Prior to the [documentation site](https://developers.arcgis.com/calcite-design-system/), our storybook was the primary means of documentation. It is now mainly used for screenshot tests, so we no longer require the Docs tab.

Relevant lines to remove:

* https://github.com/Esri/calcite-design-system/blob/d552e80ef6211e4dd85599b40a9950275cec4f82/packages/calcite-components/.storybook/utils.tsx#L72-L79
* https://github.com/Esri/calcite-design-system/blob/9f97296f23a8952a20234b5950faf1f5392b0b2a/packages/calcite-components/.storybook/main.ts#L4
* https://github.com/Esri/calcite-design-system/blob/7222dd7f661c7f630b77c20f60ab4d2299009ddd/packages/calcite-components/.storybook/preview.ts#L33-L48

The [`util:build-docs`](https://github.com/Esri/calcite-design-system/blob/c95edfe591c72e84ff07a459ab8cba7a79a9d40a/packages/calcite-components/package.json#L43) script should no longer need to pass the `--docs` flag to the Stencil build. The script may need to be renamed because of this.

**Comment by geospatialem** [comment]
Verified on the Storybook site. 🎉
