### ISSUE TITLE
[Combobox]  Enter key unexpectedly selects / deselects items when dropdown is closed

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8919]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using a Combobox, as a user I can close the dropdown, and still be able to select and deselect the "last focused item" with the Enter key.

https://github.com/Esri/calcite-design-system/assets/4733155/cbba547e-4da4-4e5d-bd3b-9f7d2edc1b73

### Expected Behavior

When the Combobox dropdown is closed, I would not expect the Enter key to select or deselect anything.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/PogZddL?editors=100

### Reproduction Steps

1. Open the Combobox developer site https://developers.arcgis.com/calcite-design-system/components/combobox/ / Codepen https://codepen.io/mac_and_cheese/pen/PogZddL?editors=100
2. Open the dropdown
3. Close the dropdown
4. Use enter key
5. Notice the last focused item will be selected / deselected

### Reproduction Version

2.6.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.11`.
