### ISSUE TITLE
[Stepper] When programmatically switching to / from `layout="horizontal-single"`, component breaks 

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#8931]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When programmatically adjusting the `layout` property to / from `horizontal-single`, the component does not correctly display the steps. It only displays a single step. In some cases, it displays all the step text on top of one another. Switching between only `horizontal` and `vertical` works fine. The issue is worse after adjusting the width of the component - I think the resizeObserver in the component is causing it. And probably unneeded since this is just changed via prop value.

https://github.com/Esri/calcite-design-system/assets/4733155/1b604b1b-b002-4314-83ed-99adc92030fe

### Expected Behavior

I'd expect the component to toggle between states without issue.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/jORrZvr

### Reproduction Steps

1. Open Codepen
2. Switch to / from the `horizontal-single` `layout` mode. 
3. Notice only a single step will appear in `horizontal-single` with all step text stacked.
4. Adjust the preview window width.
5. Notice the component now behaves differently - showing only a single step, even while switching between the previously-unaffected `horizontal` and `vertical`

### Reproduction Version

2.6.0

### Priority impact

p1 - need for current milestone

### Impact

This happens when programmatically setting the property. The Codepen shows a button-click example, but a more realistic implementation is in the Codepen, a simplified "responsive adjustment" to the property value.

Quick look at the code suggests something in `determineActiveStepper()` or the width-determining `resizeObserver()` could be the issue. Since the property is not set based on width change of the Stepper component, do we need to monitor width? The bug is worse (only shows a single step) after adjusting the page width. The bug is still present before this, just not as bad.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.5` with https://codepen.io/geospatialem/pen/qBwbaxp:

![responsive-stepper-validate](https://github.com/Esri/calcite-design-system/assets/5023024/35e8b27f-4795-4fd2-8bd9-ee66800daf99)
