### ISSUE TITLE
CalciteTable: double scrollbar

### ISSUE THREAD

**Issue by olga-knyazeva** [Esri/calcite-design-system#8947]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When CalciteTable is placed in a container that has `position: relative; overflow: auto;` and the table is bigger than the container, two sets of scrollbars appear. The table has its own scrollbars, and the parent container has another set. The visible part of the table is limited by the parent container size.

### Expected Behavior

Only scrollbars from the CalciteTable itself show up, the table doesn't overflow its container.

### Reproduction Sample

https://codepen.io/Olga-Knyazeva-the-bashful/pen/yLrabwa

### Reproduction Steps

1. Observe the table has double scrollbars.

### Reproduction Version

2.6.0

### Relevant Info

Versions before 2.5.1 don't have the issue.

Please note that the issue doesn't occur in Firefox.

I suspect this could be due to the `.assistive-text` elements that have `position: absolute`.

### Regression?

2.4.0

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Urban

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.10`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/a9ac2430-0025-47ba-80f0-350b3c03b48e)
