### ISSUE TITLE
[List Item] - calcite-select becomes unresponsive in a calcite-list-item if drag-disabled is true

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#8954]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

A calcite select component becomes unresponsive when placed in a calcite-list-item with drag-disabled set to true.

### Expected Behavior

The calcite select component should behave and respond normally.

### Reproduction Sample

https://codepen.io/sagewall/pen/eYogBjN

### Reproduction Steps

1. Open this [codepen](https://codepen.io/sagewall/pen/eYogBjN)
2. Observe how the calcite select in the test2 list item doesn't respond normally.

### Reproduction Version

2.6.0

### Relevant Info

Doesn't seem to be browser or OS dependent

### Priority impact

p2 - want for current milestone

### Impact

This is impacting custom list item content the LayerList widget in the JavaScript Maps SDK.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by sagewall** [comment]
cc @driskull

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.11`

![image](https://github.com/Esri/calcite-design-system/assets/5023024/d82ca218-1f67-44e7-94ee-5ce7f0dc95ea)
