### ISSUE TITLE
CSS/Sass font stack values are not valid

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8963]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The value for CSS + Sass font stacks is not comma-delimited and do not get applied properly.

**global.css**

```css
--calcite-font-family-code: Monaco Consolas "Andale Mono" "Lucida Console"
    monospace; /* Font family for code with fallbacks */
--calcite-font-family: "Avenir Next World" "Avenir Next LT Pro" Avenir
    "Helvetica Neue" sans-serif; /* Primary font with fallbacks */
```

**global.scss**

```scss
$calcite-font-family-code: Monaco Consolas "Andale Mono" "Lucida Console"
  monospace; // Font family for code with fallbacks
$calcite-font-family: "Avenir Next World" "Avenir Next LT Pro" Avenir
  "Helvetica Neue" sans-serif; // Primary font with fallbacks
```

### Expected Behavior

For the above font-family list values to be comma-delimited.

### Reproduction Sample

https://codepen.io/jcfranco/pen/KKYaqPK

### Reproduction Steps

1. Open the codepen and compare the styled div elements.

### Reproduction Version

2.6.0

### Relevant Info

This is impacting https://github.com/Esri/calcite-design-system/pull/8388.

### Priority impact

p2 - want for current milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [X] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.11`:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/5de6fc0e-2a70-47f0-a969-c8d8b1f06868)
