### ISSUE TITLE
calcite-alert: Long continuous text message is cutoff in the calcite-alert component

### ISSUE THREAD

**Issue by sakship2204** [Esri/calcite-design-system#8978]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

For a long text message in the calcite-alert component, which doesn't fit in the width of the screen area, the extra text on the end gets cutoff and is not displayed correctly.
<img width="1181" alt="Screenshot 2024-03-21 at 12 38 52 PM" src="https://github.com/Esri/calcite-design-system/assets/148040911/f820c177-318e-4666-8815-6196c65927aa">

### Expected Behavior

The long text message be wrapped  properly such that the extra text is displayed in the next line of the calcite-alert component.

### Reproduction Sample

--

### Reproduction Steps

1. Prepare a clean EN browser.
2. Launch URL https://www.arcgis.com/ and sign in with valid account.
3. Go to Notebook page.
4. Click "Manage" button and select "Manage files".
5. Click the user name on the left and select a user except the current user.
6. Create a folder with a long name continuous without space (e.g. 255 characters continuous without space.
7. Click the folder name.
8. Go back to Home folder, select the folder with long name and click "Delete" button.
9. On "Permanently delete" dialog, click "Delete" button.

### Reproduction Version

--

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
Because text is slotted, as a workaround for this, you can set a style on the slotted element: https://codepen.io/mac_and_cheese/pen/xxeqMoV?editors=1000

**Comment by geospatialem** [comment]
Since the above is slotted, the [workaround mentioned by Adam above](https://github.com/Esri/calcite-design-system/issues/8978#issuecomment-2012763749) is the recommended approach and the above is not scoped within Calcite.

Closing the above issue out as unplanned.
