### ISSUE TITLE
[Panel & Flow Item] Add `"content-top"` slot

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8980]
### Check existing issues
- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description
Add a new slot to the `panel` and `flow-item` components - `"content-top"` below the `action-bar` slot so we can render in a new Dialog component using the "sticky" functionality currently provided in the Modal component.

### Acceptance Criteria
1. Slot should be sticky as it is Modal
2. Slot should come with overridable padding
3. The following css var should be added to match Modal's current overrides:
**--calcite-panel-content-top-padding**: Specifies the padding of the component's `content-top` slot

### Relevant Info
A dependency needed for the Dialog + Modal component effort in https://github.com/Esri/calcite-design-system/issues/7886
See [Figma file](https://www.figma.com/design/wVqftT1aZDjwYVkDZ2V5fC/Dialog?m=dev&node-id=621%3A4874) for specs
<img width="1397" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/9d8d33e2-22df-4306-ae53-4ddce9a2f540">

### Which Component

`panel`
`flow-item`

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by driskull** [comment]
Should we add these slots to `flow-item` as well?

**Comment by jcfranco** [comment]
Good question. I think it'd be good for consistency, but I'll defer to @SkyeSeitz and @ashetland.

**Comment by SkyeSeitz** [comment]
Would Flow Item ever be used instead of Panel in Dialog's modal mode?

**Comment by driskull** [comment]
I could see that

**Comment by SkyeSeitz** [comment]
I am ok with adding this and related enhancements in #7886 to Flow Item. Thanks for bringing it up, @driskull.

**Comment by DitwanP** [comment]
@SkyeSeitz I 👀 the tile change, should this be reassigned in order to include the Flow Item as well?

**Comment by DitwanP** [comment]
🍡 Verified on `2.9.0-next.18`
