### ISSUE TITLE
CalciteCombobox close button behavior

### ISSUE THREAD

**Issue by Horiatu** [Esri/calcite-design-system#8989]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calcite-combobox, multiple selection, closable: when you close all items, it still shows a close button for an empty item: 

![image](https://github.com/Esri/calcite-design-system/assets/7327557/fabe055d-4c38-46b6-9527-cd5f77fff59b)

Now click the global x (close) button:

![image](https://github.com/Esri/calcite-design-system/assets/7327557/73a02e1f-e11e-454e-828f-c3188c32c9c6)

For:
  "dependencies": {
    "@arcgis/core": "^4.29.10",
    "@esri/calcite-components-react": "^2.6.0",

### Expected Behavior

The item X (not text, but edit marker) should not exist.

### Reproduction Sample

https://codesandbox.io/p/devbox/jovial-keller-q7h6sc?file=%2Fsrc%2FApp.jsx%3A16%2C29

### Reproduction Steps

N/A

### Reproduction Version

For:   "dependencies": {     "@arcgis/core": "^4.29.10",     "@esri/calcite-components-react": "^2.6.0",

### Relevant Info

Windows 10, Chrome Version 122.0.6261.129 (Official Build) (64-bit)

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by macandcheese** [comment]
Hi @Horiatu - thanks for opening this. It seems the Codesandbox isn't public - could you change the permissions? If there is sensitive content or other non-public code, you can share the link with us through Teams.

**Comment by Horiatu** [comment]
It seems that for now it does not reproduce.
A reason may be that it is not typescript but jsx.
The original project which I was auditing is not open for me now – I cannot see the exact details of that project at this time.
I had to put the link there because the field was mandatory, the bug report would not save without.

Tx,

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

**Comment by Horiatu** [comment]
Hi Ditwan,

In the meantime, the owner of the project has been removed the functionality where I have initially noticed the bug, while my simulation does not show it.
So, no – I cannot find any additionally information on how to reproduce it.

Tx,

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

**Comment by DitwanP** [comment]
Closing this out because we don't have enough info and cannot reproduce.
