### ISSUE TITLE
[List] Dismissed `closable` List Items leave behind extra space

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9005]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When dismissing a list Item with `closable` - extra space is left behind. It's pretty minor in a vacuum, but dismissing multiple in a row becomes obvious:

https://github.com/Esri/calcite-design-system/assets/4733155/cd3b1452-8998-43b2-85ac-b7a49ccc4ff7

### Expected Behavior

![Leave_No_Trace_Logo-1536x732](https://github.com/Esri/calcite-design-system/assets/4733155/3160f878-0962-4dc1-8de0-9e7c0c2d9e78)

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/LYvjpgb?editors=1000

### Reproduction Steps

1. Open Codepen
2. Close many List Items
3. Notice extra space

### Reproduction Version

2.6.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by driskull** [comment]
Looks like its this selector in the `calcite-list`

`::slotted(calcite-list-item)`

its applying a 1px margin to emulate a border.

https://github.com/Esri/calcite-design-system/blob/2bb1ee24bb317c95e2bef8165c75583fe98ad714/packages/calcite-components/src/components/list/list.scss#L31-L34

If we switch to an actual border this might not be an issue.

**Comment by DitwanP** [comment]
🍠 Verified on `2.7.2-next.5`
