### ISSUE TITLE
Calcite tabs broken with React + Vite

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#9010]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calcite tabs don't load and there is an error in the console `Uncaught DOMException: Operation is not supported`

### Expected Behavior

Calcite tabs load

### Reproduction Sample

https://github.com/mpayson/calcite-debug

### Reproduction Steps

1. Clone repo
2. `npm install`
3. `npm run dev`
4. Open page, see tabs don't load

### Reproduction Version

2.7

### Regression?

Yes

### Priority impact

p1 - need for current milestone

### Impact

Can't upgrade

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by DitwanP** [comment]
🍡 Verified with provided sample repo on `2.7.1`
