### ISSUE TITLE
[input time zone] Update the open picker to make the ability to search more obvious

### ISSUE THREAD

**Issue by emmilaakso212** [Esri/calcite-design-system#9017]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As a user selecting timezone values, I want to know that the field is searchable, rather than just a selection. 

### Acceptance Criteria

When the timezone dropdown is open:
- Show a search icon on the left side of the combobox
- Change default text from “Select a field” to “Search options”
- Add option to have custom placeholder text in the box
- If custom placeholder text is longer than available space, truncate the text and show ellipsis

[See design in Figma](https://www.figma.com/file/JXlrtCx8WmsXZRk8Lzd9Oq/Timezone%2Ftime-based-filters?type=design&node-id=244%3A170504&mode=dev&t=sZtk9aueJq3GU4xz-1)

### Relevant Info

Agreed upon work with Calcite team in support of time zone picker update for 24-R3.
- Also related to https://github.com/Esri/calcite-design-system/issues/9018

### Which Component

Timezone picker

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by emmilaakso212** [comment]
cc: @jcfranco

**Comment by geospatialem** [comment]
Aiming for dev implementation prior to R3 based on Online priorities - currently targeted for July. cc @emmilaakso212

**Comment by jcfranco** [comment]
A few notes on the acceptance criteria:

> Change default text from “Select a field” to “Search options”

The component doesn't use this text by default, but it can be customized via `messageOverrides`.

> Add option to have custom placeholder text in the box

See note on `messageOverrides` above.

> If custom placeholder text is longer than available space, truncate the text and show ellipsis

The component already does this, but it appears Firefox is the only one that truncates consistently. Chrome truncates on pointer down _outside_ of the component and Safari truncates on pointer down anywhere on the page (see https://codepen.io/jcfranco/pen/wvLJExw?editors=100). I'll create a separate issue to investigate this further.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.4`
