### ISSUE TITLE
[input time zone] add a time zone picker null state

### ISSUE THREAD

**Issue by emmilaakso212** [Esri/calcite-design-system#9020]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As a map author who wants to define feature template defaults, I want to be able to choose a default timezone for data entry, or leave it blank.

### Acceptance Criteria

- Create the option to include a time zone picker null state
- Use null value "Not set" 
- When picker is active, show current selection “Not set” at the top of the list
- Replace null value if a time zone is chosen
- User can scroll back to the top or search for “not set” to go back to the null state
[
See designs in Figma](https://www.figma.com/file/JXlrtCx8WmsXZRk8Lzd9Oq/Timezone%2Ftime-based-filters?type=design&node-id=244%3A170583&mode=dev&t=9zsUwmYpjRYD6307-1)

### Relevant Info

Requested by Taylor McNeil and Jasmine Reyes for feature editing enhancements related to default time zones for 24-R2

### Which Component

Input time zone

### Priority impact

p1 - need for current milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by emmilaakso212** [comment]
cc: @jcfranco

**Comment by tayMAPNeil** [comment]
Just giving this a ping. This enhancement will be really important for the add/delete field components for this release (for authoring TSO fields with no default value). 

@emmilaakso212 everything still on track?

**Comment by emmilaakso212** [comment]
@jcfranco @geospatialem @tayMAPNeil echoing Taylor's question above. Let's make sure we prioritize the time zone picker tickets appropriately based on the remaining time, and our discussion around time zone work.

**Comment by jcfranco** [comment]
@tayMAPNeil @emmilaakso212 Thanks for the ping. We have not triaged this yet on our end, but we are aware of the priority. I'll update this and related `input-time-zone` issues to reflect this and we'll take that into consideration when we do planning next week. cc @geospatialem

**Comment by geospatialem** [comment]
@tayMAPNeil @emmilaakso212 Calcite is targeting this month's release (April) to introduce the null state to land as part of R2.

**Comment by DitwanP** [comment]
🍡 Verified on `2.8.0-next.10`, input time zone is clearable and can have a default empty (`null`) value.
