### ISSUE TITLE
[combobox] highlight matching search terms

### ISSUE THREAD

**Issue by emmilaakso212** [Esri/calcite-design-system#9026]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As someone who is searching for an option in the combobox, I want to see how my search matches the options  that are being shown. 

### Acceptance Criteria

When searching using combobox, highlight matching values:

- by making them Avenir medium, color: text/1
- by adding a color: foreground/current as a highlight behind them

[See designs in Figma](https://www.figma.com/file/JXlrtCx8WmsXZRk8Lzd9Oq/Timezone%2Ftime-based-filters?type=design&node-id=244%3A170518&mode=dev&t=8qxI4u9uFamOc3x8-1)

### Relevant Info

If there are other components that have a search component, we should be consistent across them. For implementation in 24-R3. 

### Which Component

Combobox

### Example Use Case

Highlighting the search term in filtered results helps people understand why they're seeing an option

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by emmilaakso212** [comment]
cc: @jcfranco

**Comment by driskull** [comment]
I think this would be ideal for the Search widget in the Maps SDK as well.

**Comment by geospatialem** [comment]
Aiming for dev implementation prior to R3 based on Online priorities - currently targeted for June. cc @emmilaakso212

**Comment by DitwanP** [comment]
🍡 Verified on `2.10.0-next.8` 👌
![combobox-highlight-filter-matches](https://github.com/Esri/calcite-design-system/assets/60022782/7ab39fae-8086-4ffd-877e-f1a428832662)
