### ISSUE TITLE
Multi-select chip group affordance enhancement

### ISSUE THREAD

**Issue by mattdente** [Esri/calcite-design-system#9055]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The current multi-select chip group's affordance is not entirely clear. Rounded selection indicators could be perceived as single-select radio buttons.

<img width="796" alt="image" src="https://github.com/Esri/calcite-design-system/assets/145046900/3818be32-187b-40bc-927f-9b6e3b6c7c4e">

After consulting with Adam, he proposed an enhancement for multi-selection chips where by the selection indicator is a square/box which looks more like a checkbox (i.e. a better affordance we suspect).

<img width="1216" alt="Screenshot 2024-04-03 at 2 18 35 PM" src="https://github.com/Esri/calcite-design-system/assets/145046900/b795c0a9-b96f-402b-8d21-fa3968e08e3f">

### Acceptance Criteria

The proposed new design would function in the same way as it currently does, but instead of presenting a round selection indicator, the multi-select chips would present a square selection indicator.

### Which Component

Chip group (https://developers.arcgis.com/calcite-design-system/components/chip-group/)

### Example Use Case

In Data Pipelines, when a user "runs" a pipeline, the "run details" can produce a long list of results. We're using the multi-select chip filter to allow users to filter by run detail message type like so:
![chip-filter-screenshot](https://github.com/Esri/calcite-design-system/assets/145046900/6a3ee6d0-5b0e-4d62-8c48-99fa8513c8d0)

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by ashetland** [comment]
> I think this would be a good improvement for system consistency. Might require a double check of #7425 to ensure the new icon glyph still works at small scales.
> 
> cc @ashetland @SkyeSeitz

Agreed. Might make sense to pair with #7425 for the double-check.

**Comment by ashetland** [comment]
Here's the design spec for this one https://www.figma.com/design/HB1Ollf1D1Csy2PtXJ3Hai/Chip-selection-affordance-%26-padding?node-id=501-15580&m=dev

**Comment by mattdente** [comment]
Nice. I can't tell by looking at this spec, so just want to confirm, the component will allow you to show an unselected checkbox or radio button state? 

![image](https://github.com/Esri/calcite-design-system/assets/145046900/e9f4ccb5-b28d-4a58-b843-c62b416fa803)

**Comment by ashetland** [comment]
@mattdente This would update the multi-select appearance. If you'd like to see an empty state in the `selection-mode="single"`, would you be able to log a new issue?

![CleanShot 2024-05-16 at 10 58 08@2x](https://github.com/Esri/calcite-design-system/assets/108549080/252f5879-0d15-45c4-9e32-e888a5a040d2)

**Comment by mattdente** [comment]
Thanks for clarifying, @ashetland. I do think the same affordance (unselected radio button state) for the single select group would be an improvement. If you, and @macandcheese both agree, I can write up the issue.

**Comment by mattdente** [comment]
Makes sense. I'll stay tuned for any feedback I may see during usability studies on the single-select behavior, it may be just fine. I have no direct observations of that being a problem. It does feel inconsistent with multi-select, but perhaps that's not a problem either.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
