### ISSUE TITLE
split up commonTest helpers into individual modules

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9056]
### Description

`commonTests` has grown since we introduced it and it's time to split it up to make it easier to follow and maintain.

Stems from https://github.com/Esri/calcite-design-system/pull/9027#discussion_r1548434437.

### Proposed Advantages

Test helpers should be easier to follow and maintain.

### Which Component

`commonTests`

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍠
