### ISSUE TITLE
List loses divider lines when consumer includes Tailwind

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#9058]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The divider lines between list-items in a list are lost when used in an app that also uses of Tailwind.

<img width="288" alt="Screenshot 2024-04-03 at 6 09 25 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/da6bc2d3-0619-4e07-9042-beecca228687">

### Expected Behavior

The divider lines are not impacted by whether the consumer uses Tailwind.

<img width="288" alt="Screenshot 2024-04-03 at 6 09 35 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/6ff95c43-8611-4a3c-9ba6-965e0ef05538">

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/rNbpqXw

### Reproduction Steps

1. Visit the repro and observe the deficit of visible divider lines.

### Reproduction Version

2.7.1

### Relevant Info

The root cause appears to stem from whether or not the `--tw-shadow` variable is defined.

```css
calcite-list-item {
  --tw-shadow: revert-layer;
}
```
One workaround is to set the variable to `revert-layer` but this doesn't have great browser support yet. Another workaround is to set the list-item's `box-shadow` style manually.

### Priority impact

p3 - want for upcoming milestone

### Impact

Impact is an inconsistent experience for consumers and hard-coded workarounds that add maintenance risk.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
The design token effort may mitigate the above, will re-verify the component once tokens are shipped, anticipated in the April milestone.
