### ISSUE TITLE
Panel: Allow esc key to be cancelled and prevent closing

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9070]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When calling preventDefault on a panel for the esc key it will still close the panel

### Expected Behavior

When calling preventDefault on a panel for the esc key it will **not** close the panel

### Reproduction Sample

https://codepen.io/driskull/pen/bGJLQOe?editors=1010

### Reproduction Steps

1. Open code sample
2. tab or click on the panel
3. hit escape key
4. panel should not be closed

### Reproduction Version

1.7.1

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified on `2.7.2-next.5`
