### ISSUE TITLE
input-date-picker: closes date-picker when switching between months using arrow/page keys.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#9082]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When the user opens the input-date-picker and navigate to activeDate with keyboard or mouse ,  using arrow keys or page keys to navigate next or previous month closes the input-date-picker. 

### Expected Behavior

arrow/page keys should not close input-date-picker when navigating between months.

### Reproduction Sample

https://codepen.io/anvesh-mekala/pen/QWPmYzo

### Reproduction Steps

1. Open Codepen sample.
2. Open the input-date-picker using mouse or keyboard.
3. Tab into the date-picker. ( requires multiple Tabs to focus activeDate)
4. Once the activeDate is focused , use arrowDown or arrowUp to navigate to different month.
5. Repeat the above step and use pageDown/pageUp keys to navigate different month.
6. Observe when the activeDate is in the first week and arrowUp closes the input-date-picker.
7.  Observe when the activeDate is in the last week and arrowDown closes the input-date-picker.
8. Observe using pageDown/pageUp closes the input-date-picker .

### Reproduction Version

2.7.1

### Relevant Info

Related to https://github.com/Esri/calcite-design-system/issues/9062

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified in `2.8.0-next.15`
