### ISSUE TITLE
Clean up fake Storybook knobs and set up controls for simple stories

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9084]
### Summary

https://github.com/Esri/calcite-design-system/pull/9030 introduced fake knobs to ease migration to Storybook v8 as `@storybook/addon-knobs` is no longer supported. Knobs used in `simple` stories should be restored via `@storybook/addon-controls` and any other knob-usage should be cleaned up. 

### Desired Outcome

1. Replace knobs with controls for `simple` stories
2. Remove knobs used in all other stories
3. Drop `createComponentHTML` and related utils and replace each story using this with HTML instead.

### Resources

[`createComponentHTML`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/.storybook/utils.tsx#L43-L56)
[`filterComponentAttributes`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/.storybook/utils.tsx#L65-L74)
[Example of story using ☝️](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/accordion/accordion.stories.ts#L90-L119)
https://storybook.js.org/docs/essentials/controls

**Comment by DitwanP** [comment]
🍡 Verified locally
