### ISSUE TITLE
Remove `enforce-ref-last-prop` rule from the provided config

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#9087]
### Description

Disable/remove `enforce-ref-last-prop` custom esLint plugin rule from the recommended config as it is no longer needed with Stencil v4.14.1.

### Proposed Advantages

Reduces the number of unnecessary checks performed during linting.
Ensures that the ESLint configuration remains current with the latest best practices.

### Which Component

@esri/eslint-plugin-calcite-components

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [X] @esri/eslint-plugin-calcite-components

**Comment by geospatialem** [comment]
Verified on the `main` branch
