### ISSUE TITLE
Remove `strict-boolean-attributes` rule from the provided config

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#9089]
### Description

Disable/remove `strict-boolean-attributes` custom esLint plugin rule from the recommended config as it is no longer needed with Stencil v4.14.1 and can be replaced by [`ban-default-true`](https://github.com/stencil-community/stencil-eslint/blob/main/docs/ban-default-true.md).

### Proposed Advantages

Reduces the number of unnecessary checks performed during linting.
Ensures that the ESLint configuration remains current with the latest best practices.

### Which Component

@esri/eslint-plugin-calcite-components

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [X] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
Might be impacted by #10310.

**Comment by jcfranco** [comment]
> We might still need this after https://github.com/Esri/calcite-design-system/issues/10310.

Confirmed. Closing!
