### ISSUE TITLE
incorrect focus outline color

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#9099]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Design identified a mistake in the outline color of calcite components. This is currently brand-hover color.

### Expected Behavior

The outline color should be the calcite-brand color.

### Reproduction Sample

https://codepen.io/alisonailea/pen/MWRGpYm/d0a829b2883098189c816aac0fb40537

### Reproduction Steps

1. Open dev-tools
2. select the calcite component
3. :focus the component
4. outline color should be #007ac2

### Reproduction Version

2.7.0

### Regression?

1.11.0

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
@alisonailea Thanks for fixing this! Could you update the issue lifecycle label per our [guidelines](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md#lifecycle)?

**Comment by geospatialem** [comment]
> @alisonailea Thanks for fixing this! Could you update the issue lifecycle label per our [guidelines](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md#lifecycle)?

@alisonailea Is this issue resolved so we can verify it's working as intended? If so, per Franco's note above, can you update the lifecycle label so we can verify? TIA! 🙌🏻

**Comment by geospatialem** [comment]
Verified in `2.8.0-next.7`. 

cc @alisonailea if there is more work needed, let us know and we can reopen.
