### ISSUE TITLE
Add more details about commit message format to the contributing doc

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9116]
### Description

We currently link to [Ionic's conventions](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md#commit-message-format), but we should explicitly document this for our purposes.

Additionally, this section should include examples.

### Which Component

N/A

### Resources

https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md#commit-message-format

**Comment by geospatialem** [comment]
Verified on [contributing.md](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md#commit-message-format).
