### ISSUE TITLE
Add CSS class map pattern entry to conventions doc

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9117]
### Description

The following CSS class map pattern is used across many components, but this is not documented in our conventions.

* https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/action/resources.ts#L1-L13
* https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/action/action.tsx#L270-L272
* https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/action/action.tsx#L242

Additionally, we should update it to include dynamically generating classes shown [here](https://github.com/Esri/calcite-design-system/pull/9033#discussion_r1561473729).

### Which Component

N/A

**Comment by geospatialem** [comment]
Verified in the [convention readme](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/conventions/README.md#class-names).
