### ISSUE TITLE
[Carousel] Improve support for high item counts

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#9121]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Carousel is currently best used with a small number of items. It could be worth supporting more items or "slides" that exceeds the page indicator display. A user could have 15 slides, but only has space for 5 page indicators.

### Acceptance Criteria

A large number of Carousel Items could be supported via a maxPagesDisplayed property or this could be automatic based on width and space available. If there are more items than there are page indicators, there would need to be some kind of queuing-like visual affordance to inform the user that there are more pages than the currently visible indicators show. Would also need to explore what it would look like when the user reaches the last item and loops back to the beginning item.

### Relevant Info

cc @macandcheese 

### Which Component

Carousel

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by asangma** [comment]
I think adding support for a CarouselMenu might also be a good solution.

**Comment by macandcheese** [comment]
> I think adding support for a CarouselMenu might also be a good solution.

I don't know if a Carousel's main purpose is to serve intention-based browsing like that ("show me slide 5 of 8").

I understand this makes sense in some cases (a gallery of known imagery, selected features, etc. - "I want to go to view feature abc") - but I'd expect a navigation experience like that to be built somewhere _around_ the Carousel - in a Panel with associated UI, etc.

In the future, each "representative dot" might also not represent a single entity - but maybe representing 2/3 Carousel Items in view: https://github.com/Esri/calcite-design-system/issues/9104

Main intention with this is to resolve the following:

<img width="1065" alt="Screenshot 2024-07-02 at 12 05 55 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/3e915443-ae10-4db7-9ba2-d50eed1a8603">
<img width="388" alt="Screenshot 2024-07-02 at 12 16 13 PM" src="https://github.com/Esri/calcite-design-system/assets/4733155/5619399e-ec16-4b23-9754-3fd566baf317">


I'd propose something like the following:

Add a `max-displayed-items` property that when set:
- Reduces the number of displayed "representative dots" to the value of the property.
- When "more slides exist in a direction" - represent the "last shown" with some combination of a different icon size / icon color. This is a pretty common affordance for this behavior - if a user is "at the end" this icon change is not used. (Note - this behavior could be affected by future properties to allow / disallow "wraparound scrolling" - but that doesn't exist currently)
 - Ensuring the "play / pause" and arrows (if using "inline" display mode) are always visible.

Thoughts:
- This could be useful at all viewport widths - so while we can / maybe should do this automatically when the Carousel becomes "too narrow" - I think the property might also make sense for other use cases. We could decide "which wins" in some cases if needed and we wanted to implement the "auto collapsing".

**Comment by DitwanP** [comment]
🍠 Verified locally on `dev`

https://github.com/user-attachments/assets/348b238c-7be8-4d35-a3f1-86a211b7a497
