### ISSUE TITLE
[calcite-input-number]: calcite-input-number allowing character "e"

### ISSUE THREAD

**Issue by jasdelreyes** [Esri/calcite-design-system#9155]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calcite-input-number` allows character of "e".

### Expected Behavior

`calcite-input-number` should only accept number inputs.

### Reproduction Sample

https://codepen.io/jasdelreyes/pen/KKYGLPp?editors=100

### Reproduction Steps

Type any character into the field. Notice that numbers are allowed (expected) and the character "e" (not expected).

### Reproduction Version

~2.7.1

### Priority impact

p1 - need for current milestone

### Impact

This impacts a new workflow in the Map Viewer slated for R02.

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
@jasdelreyes the [`integer` property](https://developers.arcgis.com/calcite-design-system/components/input-number/#api-reference-properties-integer) can be used to disable exponential notation, where:

> When `true`, restricts the component to integer numbers only and disables exponential notation.

For instance: https://codepen.io/geospatialem/pen/JjVVzKW

![image](https://github.com/Esri/calcite-design-system/assets/5023024/b5f86dc7-3083-4ea5-a099-0b39107dd462)

Closing out the above request as not planned.
