### ISSUE TITLE
Use calcite-ui-icons >= 3.27.8

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-design-system#9162]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

For ArcGIS Components, we need the icon that has been implemented in calcite-ui-icons 3.27.8.

### Acceptance Criteria

calcite dependency has been updated accordingly.

### Which Component

All

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified the new subtype icon on the `main` branch. ✅ 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/13516793-c9d0-4661-afbc-b7d52c200939)
