### ISSUE TITLE
[Input Date Picker] Multiple components with and without `range` can create buggy behavior

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9167]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When multiple `input-date-pickers` with, or without `range` are active in an app, the component's can observe a buggy behavior when interacting with the `date-picker`.

For instance, with `range` active:
![picker-issue](https://github.com/Esri/calcite-design-system/assets/5023024/04c046a4-a4c8-4b3b-a200-a7341ec20dc4)

### Expected Behavior

Multiple `input-date-pickers` can be present in an app with no buggy behavior.

### Reproduction Sample

- https://codepen.io/geospatialem/pen/oNOJweO
- https://codepen.io/nwhittaker-esri/pen/rNbgLEy

### Reproduction Steps

**First sample**:
1. Open the [sample](https://codepen.io/geospatialem/pen/oNOJweO)
2. Open the first `input-date-picker` 
3. Open the first range from the `input-date-picker`
4. Open the second `input-date-picker`
5. Observe the behavior
6. The same process can be repeated with the second `input-date-picker` and attempting to open the first `input-date-picker`

**Second sample**:
1. Open the [sample](https://codepen.io/nwhittaker-esri/pen/rNbgLEy)
2. Open the first `input-date-picker`
3. Open the second `input-date-0picker`
4. Observe the behavior

### Reproduction Version

2.7.1

### Relevant Info

- Surfaced in feedback from a user on Fri April 19:
 > Dropdown bounces when going between months if you have two date pickers sitting side by side in the ui.
- Maybe related to some of the behavior seen in #8557

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
The efforts of #3455 seem to resolve the behavior from above. Will confirm if the behavior is mitigated once the efforts of #3455 are merged - targeted for May 2024.

**Comment by nwhittaker** [comment]
@geospatialem, I'm seeing the same bug with two non-range pickers as well. I have [a repro][1] in case you want to roll that into the testing for this one, or I can create a separate issue.

[1]: https://codepen.io/nwhittaker-esri/pen/rNbgLEy

**Comment by geospatialem** [comment]
> @geospatialem, I'm seeing the same bug with two non-range pickers as well. I have [a repro](https://codepen.io/nwhittaker-esri/pen/rNbgLEy) in case you want to roll that into the testing for this one, or I can create a separate issue.

@nwhittaker Good catch - updated the context of the issue above to include `range` and non-range and added your Codepen sample to the above for context and verification.

**Comment by DitwanP** [comment]
Verified locally on `dev` and I think this issue has been resolved as a result of #3455 being completed. 

https://github.com/user-attachments/assets/c74b7145-59bd-4371-b6dc-c7326c46fa11
