### ISSUE TITLE
[List]: add mode prop for choosing between flat and nested lists

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#9173]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A way to control nesting behavior in List. Nested list items need to hold space for the expand button, but this space is undesirable in lists that, base on workflow, will never have nested items.

This would be a breaking change and should be paired with #7100.

### Acceptance Criteria

Add a `mode="flat" (default) | "nested"` property.

In `flat`, Lists are rendered flat, without collapsible nesting. If an item is nested in the DOM, it is rendered, but not indented.

In `nested`, a blank space is reserved for the expand button in every item.

Before/after example:
![CleanShot 2024-11-20 at 13 02 04@2x](https://github.com/user-attachments/assets/cd11963a-9828-4843-942c-d57fbf45aa1f)

### Relevant Info

cc @driskull @jcfranco 

### Which Component

List
List Item

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
Updated the description to include a before/after screenshot using the current build of List. Spacing will be improved with #7100.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`

**Comment by geospatialem** [comment]
For documentation purposes later, here's a codepen sample in `3.0.0-next.29`: https://codepen.io/geospatialem/pen/MYggPPV. cc @DitwanP 

```html
<calcite-list display-mode="nested">
```
