### ISSUE TITLE
[List Item]: add icon-end/start props

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#9175]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

List Item should match other similar components in this regard and include properties for `icon-end` and `icon-start`. This would improve the OOTB experience when adding icons to list items vs the current workflow of relying the content slots. 

### Acceptance Criteria

- [x] icon-end/start props added
- [x] default color should be `text.3`
- [x] when the item is selected, the color should match the heading (`text.1`)
- [x] icons should be `scale="m"` (24px) on `scale="l"` List Items

![image](https://github.com/user-attachments/assets/4bb971e6-ce60-4b87-89d1-b2b07ac245c4)

### Which Component

List Item

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @driskull

**Comment by geospatialem** [comment]
Listed as a `p - high` to ensure all related list visual and breaking changes are in alignment for the November breaking change release. While the above is not a breaking or visual change it relates to other breaking changes such as #7100. cc @ashetland

**Comment by ashetland** [comment]
Due to the refactor required by #7100, it might make sense to wait to add these until after 7100 is complete.

**Comment by geospatialem** [comment]
Verified on Storybook with the `icon-start` and `icon-end` attributes (`iconStart` and `iconEnd` props) and selection states. 👍🏻

**Comment by aPreciado88** [comment]
Created follow up [issue](https://github.com/Esri/calcite-design-system/issues/11021) to split storybook screenshot.
