### ISSUE TITLE
Tooling: Add a priority option to the test template

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9191]
### Summary

Update the test issue template to include a dropdown and automation that adds a priority label, based on the dropdown content.

### Desired Outcome

Add in a priority label of `p - high`, `p - medium`, or `p - low` depending on the dropdown selection.

### Resources

- test.yml
- addPriorityLabel.js

**Comment by DitwanP** [comment]
🍬 Verified in test issue template.
