### ISSUE TITLE
Ensure all components inherit font-family 

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#9205]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Relates to https://github.com/Esri/calcite-design-system/issues/7175
Ensure all components inherit font-family and reference the variables from Calcite Design Tokens

### Acceptance Criteria

- [ ] calcite-presets should reference `--calcite-font-family` for sans fonts and `--calcite-font-family-code` for mono fonts.
- [ ] there should not be any references to `--calcite-sans-family` in calcite-components
- [ ] there should be no changes to the applied font faces in the UI

### Which Component

all

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-design-tokens

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍭 Verified
