### ISSUE TITLE
[Tip / Tip Group / Tip Manager] Deprecate components

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9228]
### Description

Now that Carousel and Carousel Item have landed, we can proceed with deprecating the set of Tip components.

The Tip Manager and Tip Group component can be directly replaced with Carousel / Carousel Item.

The Tip component can be replaced with a Notice, a Card, a Tile, or custom content.

### Which Component

Tip, Tip Group, Tip Manager

### Resources

Per @jcfranco, we should target 2.9 for this deprecation.

**Comment by DitwanP** [comment]
🍠 Verified on `main`
