### ISSUE TITLE
Add ability to check a form component's validity for setting custom messages

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#9229]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add a way to check the [`ValidityState`](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) of a component so custom validation messages can be set based on different constraints. The implmentation will be switched to use [`elementInternals`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals) once it has full support (#8126).

### Acceptance Criteria

The following items are required:

- A [`calciteInvalid`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event) event, which fires when the form is submitted with invalid values.
- A readonly [`validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/validity) property on form components, which exposes the `ValidityState`. This will allow users to conditionally set custom validation messages based on the issue.

### Which Component

Form associated components

### Example Use Case

https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation#complex_constraints_using_the_constraint_validation_api

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `2.8.0-next.19` with [Ben's codepen](https://codepen.io/benelan/pen/oNOORrB?editors=1010) using the `validityStates`. 🎉
