### ISSUE TITLE
[Tile] apply center alignment to only x axis

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#9252]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`alignment="center"` middle aligns Tile's content on the y axis in addition to center aligning on the x axis causing misalignment of headers in Tile Group.
<img width="717" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/098e1f8d-d53e-4a9a-9b5b-8ed166cb3608">

I am also seeing some off center Tiles on `alignment="center" (see codepen below)
<img width="480" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/df0c3e16-f95c-4feb-a373-a9b13a2e8a0d">

### Expected Behavior

`alignment="center"` only centers Tile's content on the x axis, but keeps it top aligned on the y axis.
<img width="730" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/966ade7e-68d4-4658-ad27-de435ca1dd8f">

### Reproduction Sample

https://codepen.io/skyeseitz/pen/RwOzVoP?editors=1000

### Reproduction Steps

See codepen provided.

### Reproduction Version

2.8.0

### Relevant Info

cc @eriklharper @ashetland @macandcheese 

### Priority impact

p4 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍭 Verified on `2.9.0-next.18`
