### ISSUE TITLE
Deprecate [Tile Select& Tile Select Group]

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#9253]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Functionality from Tile Select and Tile Select Group has now been implemented into Tile & Tile Group as of 2.8.0 allowing us to deprecate and direct users to to the components & functionality. 

### Relevant Info

A part of the Tile Design epic #6662 
cc @eriklharper @ashetland @macandcheese 

### Which Component

Tile Select & Tile Select Group

### Priority impact

p4 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
Verified on `main`
![image](https://github.com/Esri/calcite-design-system/assets/60022782/48fc0fdf-ba6e-4a46-92a7-7b7cb2a4900c)
