### ISSUE TITLE
[Tooling] Add framework examples to the monorepo packages

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9256]
### Summary

Add the [framework examples](https://github.com/Esri/calcite-components-examples) repo, to the Calcite monorepo packages.

Part of the monorepo package epic from https://github.com/Esri/calcite-design-system/issues/7122

### Desired Outcome

Adding more Calcite packages to the repo and splitting existing functionality into encapsulated workspaces will improve maintainability and discoverability.

### Resources

Additional discussion and context is also linked in https://github.com/Esri/calcite-design-system/issues/7122.

**Comment by DitwanP** [comment]
🍡 Verified locally
