### ISSUE TITLE
[Tooling] Add priorities to the existing tooling issue template

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9258]
### Summary

CI and tooling related issues almost always have a low or high priority, but do not include the option to address a priority on issue creation. Propose we add a dropdown option for our team to add in the priority, with "low" being the default.

### Desired Outcome

- [x] The tooling issue template provides a required dropdown with priority
- [x] Upon creation of the issue a priority label is added to the issue via the CI

### Resources

[Tooling issue template](https://github.com/Esri/calcite-design-system/issues/new?assignees=&labels=tooling%2C0+-+new%2Cneeds+triage&projects=&template=tooling.yml)

**Comment by DitwanP** [comment]
🍡 Verified with new test issue. 🤖
