### ISSUE TITLE
Remove support for kebabified global attributes (`enter-key-hint`, `input-mode`)

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9260]
### Description

https://github.com/Esri/calcite-design-system/pull/9245/ fixed a regression caused by refactoring components to use global attributes, where kebab-cased global attributes were unintentionally removed. 

This should be removed in a major release to allow us to fully rely on global attributes.

### Proposed Advantages

Removal of workaround.

### Which Component

`input`, `input-text` and `input-number`.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
Blocked by #10310.

**Comment by DitwanP** [comment]
🍡 Verified locally using example from Franco: https://codepen.io/jcfranco/pen/QWeRebN?editors=1000
(the updated attributes should no longer show up on internal inputs)
