### ISSUE TITLE
`input-date-picker`, `input-time-picker` and `list` not updating messages when lang changes

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9268]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`input-date-picker`, `input-time-picker` and `list` are not updating messages when the locale changes (per [`t9n`'s doc]( https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/utils/t9n.ts#L65-L66)).

### Expected Behavior

The internal labels to be translated after changing locale.

### Reproduction Sample

https://codepen.io/jcfranco/pen/xxevvbE
https://codepen.io/jcfranco/pen/KKYOYzj
https://codepen.io/jcfranco/pen/ExJqJeX

### Reproduction Steps

1. Open provided codepen and see the console
2. Note how both EN and ES locales show the same value for the internal labels

### Reproduction Version

2.18.0

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍮 Verified on `2.9.0-next.18`
