### ISSUE TITLE
Multiple tiles with the selected attribute display as selected in both single and single-persist groups

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#9271]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Including the `selected` attribute on more than 1 `calcite-tile` element inside `calcite-tile-group` with either `single` or `single-persist` selection modes appear selected when only the last one should be.

### Expected Behavior

According to the [HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#using_radio_inputs) for radio buttons, the last selected element in DOM order should be the selected element.

![image](https://github.com/Esri/calcite-design-system/assets/821864/2c289af7-b906-4f0c-bed2-7eb10112d444)

### Reproduction Sample

https://codepen.io/eriklharper/pen/NWmQZoL?editors=1010

### Reproduction Steps

1. Open the Codepen Reproduction Sample
2. Observe that all Tiles that include a `selected` attribute appear selected.

### Reproduction Version

2.8.0

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified on `2.9.0-next.4`
