### ISSUE TITLE
[Button & Action]: Referenced `tooltip` isn't invoked on mobile devices

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9273]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

On mobile devices both `button` and `action` components will not invoke a referenced `tooltip` on tap.

https://github.com/Esri/calcite-design-system/assets/5023024/45715ae4-b7be-42ee-992f-f6b425c7c95a

### Expected Behavior

- [x] `button` should trigger a referenced `tooltip` on mobile devices on tap, similar to click
- [x] `action` should trigger a referenced `tooltip` on mobile devices on tap, similar to click

![desktop](https://github.com/Esri/calcite-design-system/assets/5023024/3edbf603-8540-4bfd-9fcd-754949b3f432)

### Reproduction Sample

https://codepen.io/geospatialem/pen/OJGKGrY

### Reproduction Steps

1. [Open the sample](https://codepen.io/geospatialem/pen/OJGKGrY) on a mobile device
2. Try to tap on either the `button` or `action` to invoke the associated `tooltip`
3. Observe the behavior

### Reproduction Version

2.8.0

### Relevant Info

Tested on iOS

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `2.11.0-next.21` on iOS in Chrome and confirmed behavior for click events is unchanged with Windows on Chrome. 🙌🏻

**Comment by macandcheese** [comment]
Is there any way we can verify iOS specific fixes in Safari as well as that is the default device browser?

**Comment by geospatialem** [comment]
For sure, also verified in Safari for `2.11.0-next.21`. ✨
