### ISSUE TITLE
Docs: [Shell/Shell Center Row] Update slots for consistent refs to Shell Panel

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9275]
#### Phase I - targeted May 2024
We need to update the `shell` slots to ref `shell-panel` and not `shell-center-row` , which should be changed for the following slots:
- [x] `panel-bottom`
- [x] `panel-top`
- [x] `center-row`

#### Phase II - targeted June 2024
- [x] We should also deprecate the `shell-center-row` component, once #7513 has been executed, per https://github.com/Esri/calcite-design-system/issues/9275#issuecomment-2098890482

### Which Component

`shell`

### Resources

- [Doc site](https://developers.arcgis.com/calcite-design-system/components/shell/#slots)
- [Component](https://github.com/Esri/calcite-design-system/blob/27a82dcaf8b091c609b3bf765d8c8617c447d8e7/packages/calcite-components/src/components/shell/shell.tsx#L10-L22)

**Comment by geospatialem** [comment]
@DitwanP The dependent issue of #7513 is anticipated to land, but we can move this into August to ensure the doc update. More context in the change provided here: https://github.com/Esri/calcite-design-system/issues/7513#issuecomment-2256581535

**Comment by DitwanP** [comment]
🍭Verified on doc site
