### ISSUE TITLE
Tile directly reassigns CSS variables within the component

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#9278]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Tile component tokens as CSS can not be reassigned by users because the tokens are directly assigned within the component.

### Expected Behavior

As a user I should be able to give each component token new values and have those take precedence over the internal token assignments, including for classes and states

### Reproduction Sample

https://codepen.io/alisonailea/pen/yLWBXbq/c1ce40abeafb2210def6108a2b745c5f

### Reproduction Steps

1. open the link
2. observe the tile that has the class ".selected" 
3. notice the border is still blue and not red

### Reproduction Version

2.8.1-next.3

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
@alisonailea Would the above also be closed in favor of https://github.com/Esri/calcite-design-system/issues/7180 per https://github.com/Esri/calcite-design-system/pull/9279#issuecomment-2105110408?

**Comment by geospatialem** [comment]
Closing in favor of #7180 as discussed in the team mid-milestone discussion and mentioned in the [comment above](https://github.com/Esri/calcite-design-system/issues/9278#issuecomment-2107959032) on 5/13. cc @alisonailea
