### ISSUE TITLE
List Item - make it more obvious when drag-disabled 

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-design-system#9283]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

ListItem has `drag-disabled`. This is good, but there are cases when the drag will never be enabled. In those cases it would be a better UX if the drag-handle were not rendered or at least were rendered with even lower opacity.

I propose to be able to hide the handle when `drag-disabled` or reduce the opacity of a disabled handle more.

In this example, the child items may never need drag and drop while the parent would regularly need drag.

![image](https://github.com/Esri/calcite-design-system/assets/12503298/61ddcf28-a174-4775-892d-eb51fb0f2996)

cc @driskull

### Acceptance Criteria

- [ ] When `drag-disabled`, hide drag handle, but retain space for it (see [icon set to blank example below](https://github.com/Esri/calcite-design-system/issues/9283#:~:text=Lower%20opacity%20(0.25)-,Icon%20set%20to%20blank,-driskull%20added%20the))

### Which Component

ListItem

### Example Use Case

CatalogLayer. Because the structure of this layer type, its children may never need drag and drop.

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by asangma** [comment]
Reopening this.
Based on implementation in our JS SDK for LayerList, it would still be useful to selectively turn off the drag handle for specific ListItems in a List that has drag-enabled.

**Comment by asangma** [comment]
In this example, there are two items that whose dragging cannot be enabled. While the handles are disabled, the lowered opacity doesn't provide a great amount of contrast.

![image](https://github.com/Esri/calcite-design-system/assets/12503298/dd4cd194-b5a4-4b10-84ee-efd26756f54f)

**Comment by asangma** [comment]
Lower opacity (0.25)
![image](https://github.com/Esri/calcite-design-system/assets/12503298/81ca0769-6fd8-41a2-90cb-d4ed81b93d57)

Icon set to `blank`
![image](https://github.com/Esri/calcite-design-system/assets/12503298/e0a8943c-612b-4c6b-a1b2-cec29fec9b50)

**Comment by driskull** [comment]
This would be for design to consider. Added the label

**Comment by asangma** [comment]
Thanks @driskull. 🤘🏾

**Comment by ashetland** [comment]
Updated the Acceptance Criteria above to use `icon="blank"` or similar approach to hide the drag handle, but retain space for it.

**Comment by driskull** [comment]
We can do this in conjunction with https://github.com/Esri/calcite-design-system/issues/7537

**Comment by DitwanP** [comment]
🍡 Verified, this was indeed completed alongside #7537. The drag icon is removed when list item is set to `drag-disabled`.

https://codepen.io/Ditwan-Price/pen/zxOowGW?editors=1010
