### ISSUE TITLE
[List Item] Selection padding has too much space when the List's width is reduced

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9290]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When updating from `value-list` to `list` in smaller width use cases for selections, additional padding is added, which effects the look of the component:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/df9a9b78-ccf6-4c01-9534-f55e17e3537b)

| Before with `value-list`  | After with `list` |
| ------------- | ------------- |
| <img src="https://github.com/Esri/calcite-design-system/assets/5023024/78324d77-64ec-4167-b8fb-bf94e190b024" alt="" /> | <img src="https://github.com/Esri/calcite-design-system/assets/5023024/ed46d4b6-83a0-43fc-b848-2f3ed61bf503" alt="" />  |

### Expected Behavior

Replace the existing `12px` padding to the right of the component's `selectionAppearance` of `"icon"` for `selectionMode`'s of `"multiple"`, `"single"` and `"single-persist"` to `4px` with the [`--calcite-spacing-xxs` token](https://developers.arcgis.com/calcite-design-system/foundations/tokens/reference/#spacing):

![image](https://github.com/Esri/calcite-design-system/assets/5023024/4063bfe9-f690-4d47-93e0-1fd4ec2e3bc7)

![image](https://github.com/Esri/calcite-design-system/assets/5023024/8f85aec0-1ffb-4fb4-bdb9-bd20407e7ce8)

### Reproduction Sample

https://codepen.io/geospatialem/pen/WNBNeNe

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/WNBNeNe?editors=1100)
2. Observe the padding on the left example: `selection-mode="icon"`
3. Observe the padding in the other two examples
4. This can also be observed on the [documentation site samples](https://developers.arcgis.com/calcite-design-system/components/list/)
5. Compare to [this `value-list` sample](https://codepen.io/geospatialem/pen/YzbzZrx)

### Reproduction Version

2.8.0

### Relevant Info

_Refer to the impact statement below._

### Priority impact

p1 - need for current milestone

### Impact

Came up when the Analysis team converted their `pick-list` to `list`, where when confined to a smaller width panel, the padding takes up a considerable amount of space. They are considering reverting back to `pick-list` if a fix cannot be mitigated, and would have to migrate over after the breaking change release when #7100 is implemented.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Web Analysis

**Comment by geospatialem** [comment]
cc @amring1

**Comment by DitwanP** [comment]
🍡 Verified locally on `hotfix`
<img width="423" alt="image" src="https://github.com/Esri/calcite-design-system/assets/60022782/6f6d0d73-e0c6-40a4-b6b8-f613e0c2ef74">
