### ISSUE TITLE
[Tooling] Communicate component deprecations and upcoming removal via console

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9295]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Communicate component deprecations and future major version targeted release for developers to start transition to other  supported components.

### Acceptance Criteria

If a component is deprecated, we communicate to developers:
- [ ] its deprecation and 
- [ ] when the anticipated removal will take place (e.g., `3.0`, `4.0`, etc.)

### Which Component

Will currently apply to:
- **Pick List**: Pick List, Pick List Group, Pick List Item in `3.0`
- **Value List**: Value List, Value List Item in `3.0`
- **Tip**: Tip, Tip Group, Tip Manager in `4.0`
- **Tile Select**: Tile Select, Tile Select Group in `4.0`

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Awesome, this going to be a great addition! @jcfranco It looks like there is one deprecation missing for the `value-list-item` in this [codepen](https://codepen.io/geospatialem/pen/wvLzoKp). Relaying this back over to ya to add in. 🕵🏻

**Comment by DitwanP** [comment]
🍡 Looks great! Verified locally on `dev`
![image](https://github.com/user-attachments/assets/5ffab4af-0776-4e3a-ab97-6ac04e84666a)
