### ISSUE TITLE
Allow custom icons in Dropdown

### ISSUE THREAD

**Issue by Anastasiia-Boleiko** [Esri/calcite-design-system#9331]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Allow custom icons to be used in the Dropdown Item. Currently it supports calcite icons only.

### Acceptance Criteria

Allow custom icons to be used in the Dropdown Item.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/dropdown-item/

### Example Use Case

Our use case: We need to use different icons including Calcite icons and custom icons.
<img width="180" alt="Screenshot 2024-05-14 at 16 59 32" src="https://github.com/Esri/calcite-design-system/assets/119309703/06832e95-05fc-486e-bc6c-7a17a2b92fdb">

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Urban

**Comment by geospatialem** [comment]
Closing in favor of the slot additions for the component requested in https://github.com/Esri/calcite-design-system/issues/5784.
