### ISSUE TITLE
[table] Add option to remove selection chips for single-selection mode

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-design-system#9353]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

We received feedback during holistic testing that calcite-table's selection chips suggest users can make multiple selections, even in single selection mode. It'd be great to be able to remove or hide these chips. In addition, for our use case, users are required to make a selection, so removing the "Clear" button would be useful as well

### Acceptance Criteria

A new property is CSS variable that allows hiding the selection chips in calcite able

### Which Component

`calcite-table`

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by mpayson** [comment]
> Is the behavior described there (the "none" display mode) sufficient - we could add that "none" value first / more easily?

I think so, if I'm understanding correctly the `selectionDisplay` is the chips, so setting it to `none` would remove the chips above the table, but keep the selection column and row highlights in the table?

For context, here is our current impl

<img width="1111" alt="Screenshot 2024-05-16 at 12 39 40 PM" src="https://github.com/Esri/calcite-design-system/assets/5892789/f7b538e9-0ec6-40a8-8d7d-cecfde058097">

Here is our design

<img width="688" alt="Screenshot 2024-05-16 at 12 42 32 PM" src="https://github.com/Esri/calcite-design-system/assets/5892789/ca38d6fb-12fb-455a-a067-77f02d5d2b5c">

**Comment by DitwanP** [comment]
🍠 Verified locally on `main`
