### ISSUE TITLE
Tile: slotted content can over-extend the boundary

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#9358]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calcite-tile` with a slotted 500px square image over extends the visible boundary.

<img width="656" alt="image" src="https://github.com/Esri/calcite-design-system/assets/821864/956a9651-e91f-406d-80db-88d8f40d4781">

### Expected Behavior

Image does not extend past the border of the tile.

### Reproduction Sample

https://codepen.io/geospatialem/pen/GRaJdwE

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/GRaJdwE)
2. Observe the image is larger than the tile's border box.

### Reproduction Version

1.7.0

### Relevant Info

Wasn't fully resolved in #4701.

### Regression?

No

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

It looks like slotted content, such as images don't appear to be adjusted, which _might_ be expected. But it doesn't look like devs could adjust the `tile` or `tile-group` CSS to accommodate width.

@eriklharper Wondering if we need to explore more options, or open a new issue? For instance, with `2.9.0-next.9` and the following sample: https://codepen.io/geospatialem/pen/GRaJdwE:

![image](https://github.com/Esri/calcite-design-system/assets/5023024/63b008bf-7aa3-47da-b739-500512f76729)

_Originally posted by @geospatialem in https://github.com/Esri/calcite-design-system/issues/4701#issuecomment-2111278323_

**Comment by DitwanP** [comment]
🍠 Verified on `2.9.0-next.18`
