### ISSUE TITLE
[Color Picker] Color field design improvement for values and scales

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9415]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The design phase for adding alpha channel support to Color Picker (issue https://github.com/Esri/calcite-design-system/issues/749) proposed additional improvements that were intended to be tackled after the initial alpha channel support was implemented. This issue is to document the remaining tasks to complete, and the two items below should be considered together for next steps for their implementation.

**_Note: depending on the discussions, could result in a breaking change._**

cc @ashetland

### Acceptance Criteria

- [x] Consider changing updating the widths of Color Picker at each scale. Proposed widths are 200px (small), 240px (medium), 304px (large).
    - [ ] Should we consider as a new prop?
    - [ ] Related issue #8463, is it possible to change how the color field in drawn to enable responsive resizing?
- [ ] Also consider updating color fields to be square. This will ensure saturation and brightness values have a linear relationship and improve the UX of selecting a color inside the field. **(note: this could be unnecessary if the color field can be responsive to container sizes)** 
  - [ ] Run past internal teams for additional expertise and insights
  - [ ] Should we consider as a new prop?

### Relevant Info
[Figma file
](https://www.figma.com/design/3YZypHvasD8KT4Y6cmQRKy/Color-Picker-[add-opacity-support]-[issue-%23749]?node-id=1014-25331&t=YL585DzJhOrZgS3N-11)
Part of the https://github.com/Esri/calcite-design-system/issues/7163 epic

### Which Component

`color-picker`

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
Sizing changes (main breaking change) are now installed.

**Comment by jcfranco** [comment]
Actually, the responsiveness part is separate, so I'll label this as installed. 🎉

**Comment by geospatialem** [comment]
Verified on `3.0.0-next.40` with https://codepen.io/geospatialem/pen/xbKxNxX:

![image](https://github.com/user-attachments/assets/778ee277-94d5-47a0-be15-ea5be621fb2f)
