### ISSUE TITLE
input-date-picker: selecting day activates previous day in certain cases

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#9422]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When I pick a date from earlier times ( e.g. ~1850) from the DatePicker, `event.target.value` returns a day before the selected date. `event.target.valueAsDate` returns the correct value.

https://github.com/Esri/calcite-design-system/assets/821864/b4fa287c-64ea-4aae-86be-c7218e09e0be

### Expected Behavior

`event.target.value` returns the equivalent year, month and day as `valueAsDate`.

### Reproduction Sample

https://codepen.io/nsulzberger_esri/pen/gOJMjyd (input-date-picker)
https://codepen.io/nsulzberger_esri/pen/rNgLKMK (date-picker)

### Reproduction Steps

1. Change your system timezone to `Europe/Zurich`
2. Open the linked codepen
3. Select March 7th, 1850 from the Date Picker popup
4. Result: March 6th, 1850 is selected instead of March 7th.

### Reproduction Version

2.8

### Relevant Info

The current implementation uses the `dateToISO` util function which relies on `Date.prototype.toISOString` method on the Date object stored in `valueAsDate`.  `toISOString` [returns the date in UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString), not in the local time which is what will be reflected in `valueAsDate`, which can lead to discrepancies like this where the two values won't match.  Since `valueAsDate` is a Date object and will thus always format in local time, we should avoid using `toISOString` for computing `value`.

We won't be able to add spec test coverage for changing the `dateToISO` because we can't emulate timezones in the spec environment.  We should be able to test in specific timezones in the e2e environment.

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by nsulzberger** [comment]
@eriklharper I am not sure, but I think the ticket description is not quite correct, the title is right.
date-picker has the behavior you are describing. `value` contains the day before, but `valueAsDate` is fine. So users can work around that.

The bad issue is in the input-date-picker, where the codepen is here: https://codepen.io/nsulzberger_esri/pen/gOJMjyd

![2024-05-30_22-12-57](https://github.com/Esri/calcite-design-system/assets/4539468/1927e79f-15f8-4e0f-8fa6-8b5ef5a8766e)
Here `valueAsDate` also contains the wrong value.

**Comment by eriklharper** [comment]
> @eriklharper I am not sure, but I think the ticket description is not quite correct, the title is right. date-picker has the behavior you are describing. `value` contains the day before, but `valueAsDate` is fine. So users can work around that.
> 
> The bad issue is in the input-date-picker, where the codepen is here: https://codepen.io/nsulzberger_esri/pen/gOJMjyd
> 
> ![2024-05-30_22-12-57](https://private-user-images.githubusercontent.com/4539468/335364739-1927e79f-15f8-4e0f-8fa6-8b5ef5a8766e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDk0MDEsIm5iZiI6MTcxNzYwOTEwMSwicGF0aCI6Ii80NTM5NDY4LzMzNTM2NDczOS0xOTI3ZTc5Zi0xNWY4LTRlMGYtOGZhNi04YjVlZjVhODc2NmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTczODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE4N2VkNGY5MTZiODk4NjA0MmQxY2FkZjJlODVlNjgzZjdjZDZkNzkwOGYxMGMyYmQ3ZjA0M2ViMTc0MGEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHl5oLxLQiqEtwo5TbQhmBxJLRG6Cj44Q2TCsK1adbU) [ ![2024-05-30_22-12-57](https://private-user-images.githubusercontent.com/4539468/335364739-1927e79f-15f8-4e0f-8fa6-8b5ef5a8766e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDk0MDEsIm5iZiI6MTcxNzYwOTEwMSwicGF0aCI6Ii80NTM5NDY4LzMzNTM2NDczOS0xOTI3ZTc5Zi0xNWY4LTRlMGYtOGZhNi04YjVlZjVhODc2NmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTczODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE4N2VkNGY5MTZiODk4NjA0MmQxY2FkZjJlODVlNjgzZjdjZDZkNzkwOGYxMGMyYmQ3ZjA0M2ViMTc0MGEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHl5oLxLQiqEtwo5TbQhmBxJLRG6Cj44Q2TCsK1adbU) ](https://private-user-images.githubusercontent.com/4539468/335364739-1927e79f-15f8-4e0f-8fa6-8b5ef5a8766e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDk0MDEsIm5iZiI6MTcxNzYwOTEwMSwicGF0aCI6Ii80NTM5NDY4LzMzNTM2NDczOS0xOTI3ZTc5Zi0xNWY4LTRlMGYtOGZhNi04YjVlZjVhODc2NmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTczODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE4N2VkNGY5MTZiODk4NjA0MmQxY2FkZjJlODVlNjgzZjdjZDZkNzkwOGYxMGMyYmQ3ZjA0M2ViMTc0MGEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHl5oLxLQiqEtwo5TbQhmBxJLRG6Cj44Q2TCsK1adbU) [ ](https://private-user-images.githubusercontent.com/4539468/335364739-1927e79f-15f8-4e0f-8fa6-8b5ef5a8766e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDk0MDEsIm5iZiI6MTcxNzYwOTEwMSwicGF0aCI6Ii80NTM5NDY4LzMzNTM2NDczOS0xOTI3ZTc5Zi0xNWY4LTRlMGYtOGZhNi04YjVlZjVhODc2NmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTczODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE4N2VkNGY5MTZiODk4NjA0MmQxY2FkZjJlODVlNjgzZjdjZDZkNzkwOGYxMGMyYmQ3ZjA0M2ViMTc0MGEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHl5oLxLQiqEtwo5TbQhmBxJLRG6Cj44Q2TCsK1adbU) Here `valueAsDate` also contains the wrong value.

Thanks Nicole for reporting that!  I've added some tests and verification for `input-date-picker` too, which is also fixed by the changes I made.

**Comment by DitwanP** [comment]
🍭 Verified locally on `dev`

https://github.com/Esri/calcite-design-system/assets/60022782/50fd5bcb-7d2c-4e9e-8e81-8365c71d29b5

**Comment by nsulzberger** [comment]
Cool, thanks for fixing!
