### ISSUE TITLE
[Carousel] Carousel Items shouldn't animate when using `Home` / `End` and destination Carousel Item is currently active

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9471]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When the Carousel component is focused, and keyboard is used to navigate with `Home` and `End` - the component should not animate if the currently active Carousel Item is first, or last, and matches the destination.

The behavior should match the behavior of clicking on a currently active Carousel Item's representative "dot", or using the `Space` or `Enter` key on a currently active Carousel Item's representative "dot".

### Expected Behavior

If the currently active Carousel Item is first, and a user navigates with `Home`, or the currently active Carousel item is last, and a user navigates with `End`, the animation should not play. 

https://github.com/Esri/calcite-design-system/assets/4733155/0f0ba6fb-abf1-4841-9e82-50c3cfc59849

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/pomRYPd?editors=100

### Reproduction Steps

1. Open Codepen
2. Focus the Carousel component, and use `Home` / `End` while the first / last Carousel Item are already active.
3. Notice the animation occurs.
4. Try to "re-activate" an active Carousel Item by clicking the dot, or using `Space` / `Enter` on the active dot, and notice the animation (correctly) does not occur.

### Reproduction Version

2.9.0

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.23`
