### ISSUE TITLE
`setFocus` method not working on `input-date-picker` and `input-time-picker`

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-design-system#9491]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

1. Calling `setFocus()` on `input-date-picker` shifts focus to the picker's trigger button.
2. Calling `setFocus()` on `input-time-picker` does not shift focus at all.

| Actual date focus | Actual time focus |
| - | - |
| <img width="393" alt="Screenshot 2024-05-31 at 11 45 54 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/0ebfd029-1a80-4425-8e24-ed26650a8684"> | <img width="393" alt="Screenshot 2024-05-31 at 11 46 26 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/89acdb17-48c9-4599-987b-4416e4cb2482"> |

### Expected Behavior

1. Focus shifts to the date input's text field part first. This matches the focused state if the user had navigated to the input via keyboard.
2. Focus shifts to the time input's text field part.

| Expected date focus | Expected time focus |
| - | - |
| <img width="393" alt="Screenshot 2024-05-31 at 11 46 04 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/18f8fd1e-1abd-454e-9220-e33549265c17"> | <img width="393" alt="Screenshot 2024-05-31 at 11 46 34 PM" src="https://github.com/Esri/calcite-design-system/assets/421496/43899a85-7792-4dec-bece-9f769c90ace3"> |

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/QWRppqZ

### Reproduction Steps

1. Visit the repro and click the various buttons to call `setFocus()` on the different input types.
2. Compare with how focus is set on the `calcite-input` element.

### Reproduction Version

1.9.0

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

Impact is degraded usability and accessibility to the end user -- specifically in flows where focus may need to be temporarily captured and then restored programmatically (e.g. presenting a modal).

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
calling `focusFirstTabbable` in setFocus could be a potential fix.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
