### ISSUE TITLE
[Alert] Refactor register event

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9499]
### Description

Refactor the current `dispatchEvent` to have a register of elements. Can be coupled with the effort of https://github.com/Esri/calcite-design-system/issues/9340

### Proposed Advantages

Updated pattern and consistency across the design system

### Which Component

`alert`

### Relevant Info

https://github.com/Esri/calcite-design-system/blob/570529fdc1bc13f68446c7535dc0e58538e49612/packages/calcite-components/src/components/alert/alert.tsx#L197

https://github.com/Esri/calcite-design-system/blob/570529fdc1bc13f68446c7535dc0e58538e49612/packages/calcite-components/src/components/alert/alert.tsx#L359

Related to epic https://github.com/Esri/calcite-design-system/issues/7200

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by driskull** [comment]
Seems like this is a duplicate of https://github.com/Esri/calcite-design-system/issues/9340

**Comment by geospatialem** [comment]
> Seems like this is a duplicate of #9340

@driskull They seem separate to me, but we can combine them into one. Is #9340 the preferred issue for tracking? If so I can add the context above into the effort and move it to December closing out the above.

**Comment by driskull** [comment]
Reading them again, they are separate but they can be tackled at the same time. 👍

**Comment by DitwanP** [comment]
🍠 Verified
