### ISSUE TITLE
Popover is closed when created and opened dynamically (`components` output target)

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9504]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Popovers that are created, opened and appended to the DOM programmatically are not visible.

cc @mpayson

### Expected Behavior

Popovers to be visible if they are toggled programmatically.

### Reproduction Sample

https://github.com/mpayson/calcite-debug

### Reproduction Steps

1. Clone the reproduction sample above and checkout the branch `popover`
2. Run the app with developer console open
3. Click the "Click me" button
4. Notice popover is not displayed

### Reproduction Version

2.8.5

### Regression?

2.8.4

### Priority impact

impact - p0 - emergency

### Impact

This will prevent initial display of all dynamically created/opened popovers.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by DitwanP** [comment]
🍠 Verified on `2.10.0-next.1`Popover is now being displayed.
![image](https://github.com/Esri/calcite-design-system/assets/60022782/9fdb230f-ca4b-4978-8326-d4c363a0c466)
