### ISSUE TITLE
bug: Missing @types/sortablejs dependency

### ISSUE THREAD

**Issue by maxpatiiuk** [Esri/calcite-design-system#9505]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Calcite typings are using types from the Sortablejs library, for example in this file:

```tsx
// node_modules/@esri/calcite-components/dist/types/components/value-list/value-list.d.ts
import Sortable from "sortablejs";
...
```

Yet, `@types/sortablejs` is not included as a "dependency" (it's as devDependency instead, and in the root monorepo package.json rather than calcite-components's package.json)

This cause TypeScript errors for consumer of calcite package when they try to typecheck their app if they have `"skipLibCheck":false` in their tsconfig.json (otherwise, the type would get silently resolved to `any` - not ideal)

```yaml
> npx tsc --noEmit
../../../node_modules/@esri/calcite-components/dist/types/components/value-list/value-list.d.ts:2:22 - error TS7016: Could not find a declaration file for module 'sortablejs'. '/Users/mak13180/site/esri/arcgis-web-components/node_modules/sortablejs/Sortable.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`

2 import Sortable from "sortablejs";
                       ~~~~~~~~~~~~

../../../node_modules/@esri/calcite-components/dist/types/utils/sortableComponent.d.ts:1:22 - error TS7016: Could not find a declaration file for module 'sortablejs'. '/Users/mak13180/site/esri/arcgis-web-components/node_modules/sortablejs/Sortable.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`

1 import Sortable from "sortablejs";
```

### Expected Behavior

Since Calcite's types rely on Sortablejs types, `@types/sortablejs` must be made into a dependency

### Reproduction Sample

https://github.com/maxpatiiuk/calcite-missing-dependency

### Reproduction Steps

1. Checkout the repository - `git clone https://github.com/maxpatiiuk/calcite-missing-dependency`
2. Run `npm install`
3. Run `npx tsc`

### Reproduction Version

2.0.0

### Relevant Info

See relevant articles:
- https://teams.microsoft.com/l/message/19:5795f61bee984b808e71464ff2c73b09@thread.skype/1709872217873?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=30b31ec5-c158-4a79-9db7-80cefdec97a1&parentMessageId=1709872217873&teamName=JSAPI%20team%20(internal)&channelName=Sharing&createdTime=1709872217873
- https://stackoverflow.com/a/46011417/8584605
- https://www.reddit.com/r/typescript/comments/byar8w/tool_to_tell_me_which_types_deps_should_be_deps/
- https://github.com/apollographql/apollo-client/issues/713
- https://github.com/microsoft/types-publisher/issues/81

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍡 Verified locally with using repo provided above on version `2.11.0-next.12`

**Comment by DitwanP** [comment]
🍡 Verified locally with using repo provided above on version `2.11.0-next.12`
