### ISSUE TITLE
Slider text is occasionally selected when dragging the pin

### ISSUE THREAD

**Issue by evan-cx** [Esri/calcite-design-system#9522]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Slider labels and ticks are highlighted when moving the pin around.

![image](https://github.com/Esri/calcite-design-system/assets/103277214/1137c0ea-4d28-4ca3-8b15-dc432eff2220)
![calcite_slider_text_selected](https://github.com/Esri/calcite-design-system/assets/103277214/a31ba9bd-7533-43ad-b3b9-be636a2b597e)

### Expected Behavior

I'm expecting that text would not get highlighted when dragging the pin around.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/slider/

### Reproduction Steps

Use the "Slider with Label Formatter" sample.

### Reproduction Version

2.8 (?)

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

Was noted during system testing as something that we want to have fixed by end of September.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Potential solution is using `user-select="none"`

**Comment by driskull** [comment]
user-select:none on the appropriate label container is the correct fix for this. This could be a "good first issue" as its pretty basic.

**Comment by jcfranco** [comment]
If we ever wanted to make the drag area smaller to allow label/tick selection (e.g., custom formatter), we could also call `preventDefault` on the `pointerdown` to prevent selection.

**Comment by geospatialem** [comment]
Verified in `2.12.0-next.20` 🎉 

![verify-9522](https://github.com/user-attachments/assets/f03d0819-eeab-4912-ad13-f182ee732df6)
