### ISSUE TITLE
Design tokens: Refactor for alignment across the design system

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9524]
### Description

Refactor the following tokens to be in alignment with Figma and code prior to completing the effort of #7180:

- [x] Remove the following from `semantic > font`:
    - [x] letter-spacing
    - [x] paragraph-spacing
    - [x] text-decoration
    - [x] text-case
- [x] Reassign `font > font-weight > bold` in semantic tokens  to `{core.font.weight.demi}`

In #7180 epic
- [x] Make sure date-picker-month `.week-header` uses `--calcite-font-weight-bold`

### Proposed Advantages

Consistency across design and engineering and in alignment for design tokens.

### Which Component

All components

### Relevant Info

Related to the epic of #7180

### Calcite package
- [X] @esri/calcite-design-tokens

**Comment by alisonailea** [comment]
Looking into this again. I remember doing this already. Going to check some branches to see if I can get this in sooner.

**Comment by DitwanP** [comment]
🍡 Verified
