### ISSUE TITLE
Move component types into component-specific interfaces files

### ISSUE THREAD

**Issue by aPreciado88** [Esri/calcite-design-system#9526]
### Description

Some types in [interfaces](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/interfaces.ts) are not being shared between components. Move these types into component-specific `interfaces.ts` files.

### Proposed Advantages

[interfaces](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/interfaces.ts) will only contain types that are shared.

**Comment by geospatialem** [comment]
Verified on the `main` branch. ✨
