### ISSUE TITLE
Refactor tooltip simple story interface

### ISSUE THREAD

**Issue by aPreciado88** [Esri/calcite-design-system#9537]
### Description

Refactor the simple story interface within [`tooltip.stories.ts`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/tooltip/tooltip.stories.ts) to use props from the component's class.

### Proposed Advantages

Keeps the interface in sync with the component's props.

### Which Component

calcite-tooltip

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
🍡 Verified
