### ISSUE TITLE
[Tile] slots are start aligned on center alignment component

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#9540]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When Tile's alignment prop = "`center`", slotted content aligns to the _start_ in Tile's `content-top` & `content-bottom` slots. 

![image](https://github.com/Esri/calcite-design-system/assets/29716057/493cb382-7566-4213-a84b-d8ac818b7cda)

### Expected Behavior

When Tile's alignment prop = "`center`", slotted content aligns to the _center_ in Tile's `content-top` & `content-bottom` slots. 

<img width="162" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/412f6471-11f3-453e-a5cd-7cc54a7942e8">

![image](https://github.com/Esri/calcite-design-system/assets/29716057/74ad4701-bf18-41d3-894c-dbe6790e26f4)

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/vYwJGJm?editors=1000

### Reproduction Steps

See content-bottom slots with start aligned chips.

### Reproduction Version

2.9.0

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.6`

**Comment by SkyeSeitz** [comment]
> @aPreciado88 Noticing the chips are centered but the text is still not. @SkyeSeitz The text is supposed to be centered as well right? https://codepen.io/Ditwan-Price/pen/vYqOJQz?editors=1000

Correct - text should be centered. Thanks for catching.

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.7` 
https://codepen.io/Ditwan-Price/pen/vYqOJQz
