### ISSUE TITLE
[calcite-split-button] Enhancement request to add a property to control dropdown placement

### ISSUE THREAD

**Issue by doreenbrinkman** [Esri/calcite-design-system#9542]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Dropdown is placed automatically. It would be helpful to control the placement of the dropdown in the `calcite-split-button`.

### Expected Behavior

Dropdown from `calcite-split-button` is able to be placed.

### Reproduction Sample

https://codepen.io/doreenbrinkman/pen/QWRMEje

### Reproduction Steps

1.  Run the sample which changes the placement to a more desired position
2. Comment out the JS script code and see position before

### Reproduction Version

2.8.3

### Relevant Info

Examples of when placement is needed.

No placement:
![image](https://github.com/Esri/calcite-design-system/assets/156362075/08ab5ad5-5964-48a2-878d-8da18255376e)

With placement:
![image](https://github.com/Esri/calcite-design-system/assets/156362075/85ee66e9-58dd-4b98-a56d-87ca4a49ee62)

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

We have workarounds to the issue (using the JS code) but it would be nice to use a new property to control.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
