### ISSUE TITLE
Sometimes calcite-notice doesn't show the icon when icon sets to true 

### ISSUE THREAD

**Issue by qingyingwu** [Esri/calcite-design-system#9562]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Using ArcGIS Velocity, sometimes the calcite-notice doesn't show the icon when `icon` sets to true as the screenshot shown below:

![image](https://github.com/Esri/calcite-design-system/assets/6733057/0daf8038-4886-4949-96ea-5a3eebd890ac)

As an experiment, adding another calcite-notice by providing an icon name, the icon shows correctly: 

![image](https://github.com/Esri/calcite-design-system/assets/6733057/045a525e-22bb-4d82-9462-faf1f21c990a)

the code used for the screenshot above: 
```
      <CalciteNotice open kind="success" icon width="full">
        <div slot="message">
          {t('Steps.IdentifyKeyFields.NoLocationNeeded', {
            labelKey
          })}
        </div>
      </CalciteNotice>
      <CalciteNotice open kind="success" icon="layers-reference" width="full">
        <div slot="message">
          {t('Steps.IdentifyKeyFields.NoLocationNeeded', {
            labelKey
          })}
        </div>
      </CalciteNotice>
```

In ArcGIS Velocity, the issue was not always reproducible. At some places, the calcite-notice shows the icon consistently, and at some other places most of the time it doesn't show the icon. The link below contains testing details:
https://devtopia.esri.com/WebGIS/arcgis-velocity-online/issues/15021#issuecomment-4822238

### Expected Behavior

calcite-notice should display the icon correctly. 

### Reproduction Sample

[repro sample](https://codesandbox.io/p/devbox/calcite-notice-velocity-g7hy4m?file=%2Fsrc%2FApp.jsx%3A29%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx3q032x0008356lkh3swi3v%2522%252C%2522sizes%2522%253A%255B81.3603950980032%252C18.639604901996805%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx3q032w0003356lh5rr0x10%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx3q032w0005356lsdhuuoqx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx3q032w0007356lziozbgk0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.748227629814146%252C44.251772370185854%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx3q032w0003356lh5rr0x10%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3q032w0002356lp92b2edf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxaovkc90002356leityzymk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A29%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A29%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx3q032w0003356lh5rr0x10%2522%252C%2522activeTabId%2522%253A%2522clxaovkc90002356leityzymk%2522%257D%252C%2522clx3q032w0007356lziozbgk0%2522%253A%257B%2522id%2522%253A%2522clx3q032w0007356lziozbgk0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3q032w0006356leojdqti0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx3q032w0006356leojdqti0%2522%257D%252C%2522clx3q032w0005356lsdhuuoqx%2522%253A%257B%2522id%2522%253A%2522clx3q032w0005356lsdhuuoqx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3q032w0004356lydpi2ooj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx3q032w0004356lydpi2ooj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduction Steps

1. add a calcite-notice and set `icon` to true. 

The reproduction sample shows that calcite-notice doesn't show the icon consistently when setting icon to true. 

### Reproduction Version

2.9.0

### Priority impact

impact - p3 - not time sensitive

### Impact

Minor impact that slightly degrades user experience

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Velocity

**Comment by jcfranco** [comment]
As a workaround, you can use `icon=""` on the custom-element or to use the React wrapper with one of the suggested [boolean attribute gotcha workarounds](https://developers.arcgis.com/calcite-design-system/resources/frameworks/#boolean-attributes) (see [updated repro case](https://codesandbox.io/p/devbox/calcite-notice-velocity-forked-pzcm3z?file=%2Fsrc%2FApp.jsx%3A6%2C1)).

This is a known issue with React and booleans. In this case, the mixed boolean + string type adds another layer to this gotcha. When using a boolean attribute, the React wrapper handles it properly, but when using the custom element directly (i.e., not the wrapper), React will set `icon="true"`, which the component will then use as the icon name. You can see this in the console:

<img width="702" alt="Screenshot 2024-06-27 at 12 13 57 PM" src="https://github.com/Esri/calcite-design-system/assets/197440/33bbd36d-c8eb-4d5c-8d0b-be531cfb6e82">

We recommend using the wrapper for React use cases, so not sure if adding a note about this to the doc is appropriate. cc @benelan @geospatialem 

Closing based on the above.
