### ISSUE TITLE
[calcite-input-date-picker]: Header is clickable when not indicated.

### ISSUE THREAD

**Issue by jasdelreyes** [Esri/calcite-design-system#9566]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Issue: https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/51046
![image](https://github.com/Esri/calcite-design-system/assets/107893471/2bc9477f-4ecc-4193-8196-943c20c9637a)

### Expected Behavior

We expect the calendar picker's header to not be clickable, especially not in the area that the left and right arrows show/hide once the end of a range is reached.

### Reproduction Sample

https://codepen.io/jasdelreyes/pen/GRaMorV

### Reproduction Steps

Reproduction Steps are outlined in the codepen above.

### Reproduction Version

~2.8.3

### Relevant Info

Use Firefox browser

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Closing in favor of the effort, which will tackle the above, in https://github.com/Esri/calcite-design-system/issues/3455 and PR #8402.

**Comment by jasdelreyes** [comment]
@geospatialem Do you know the timeline of this update to the `calcite-input-date-picker` component?

**Comment by geospatialem** [comment]
> @geospatialem Do you know the timeline of this update to the `calcite-input-date-picker` component?

@jasdelreyes We're anticipating prior to 24.R3, but that may change. However, we'll continue to update our internal resource page if the timeline changes since we know this impacts teams.
