### ISSUE TITLE
date-picker: Add wide name for months in `en-CA` locale.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#9579]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, `en-CA` bundle for date-picker calendar data provides abbreviated format only for month. With the enhancements in https://github.com/Esri/calcite-design-system/issues/3455 , it is possible for users to switch between abbreviated format and wide name format. To support this scenario , wide name for months is required for `en-CA` locale.

### Acceptance Criteria

1. Adds wide month names for `en-CA` locale.
2. Users should be able to switch between wide and abbreviated format.

### Relevant Info

Can be coupled with https://github.com/Esri/calcite-design-system/issues/3455

### Which Component

date-picker

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by annierm18** [comment]
@anveshmekala I have the en-CA data. Just a note, the existing data for months-abbreviated and days-abbreviated have been updated.

[ca-gregorian.json](https://github.com/user-attachments/files/16034524/ca-gregorian.json)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.21` - [Codepen](https://codepen.io/Ditwan-Price/pen/dyBpWev?editors=1010)
