### ISSUE TITLE
Using calcite-tile's selected property throws type errors

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-design-system#9582]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When setting the `selected` property on a `calcite-tile` element, the following Typescript error occurs:

![image](https://github.com/Esri/calcite-design-system/assets/821864/3057cf63-d590-46f1-8858-71ff44d46369)

### Expected Behavior

Users should be able to set `selected` for setting the initial selected state without any type/compilation errors.

### Reproduction Sample

TBD

### Reproduction Steps

1. Create a Typescript app
2. `npm install @esri/calcite-components`
3. Try using `calcite-tile` by creating an instance of it and setting the `selected` property/attribute on it.
4. Result: TS error

### Reproduction Version

2.9

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍭 Verified locally on `dev`
