### ISSUE TITLE
Combobox: Once a value is typed in, arrow left and arrow right keys do not work

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9614]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Summary

Once a value is typed in, arrow left and arrow right keys do not work

### Actual Behavior

Once a value is typed in, arrow left and arrow right keys do not work

### Expected Behavior

ArrowRight and ArrowLeft keys work for selecting text already entered

### Reproduction Sample

https://codepen.io/driskull/pen/pompmZd?editors=1000

### Reproduction Steps

1. open codepen
2. type into combobox
3. try to use arrow right or arrow left keys on text typed in

### Reproduction Version

2.9.0

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
