### ISSUE TITLE
combobox: do not open when no filtered results are shown

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9617]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When typing in a combobox, it always opens when there is text

### Expected Behavior

when typing in a combobox, it only opens when there are filtered items to show

### Reproduction Sample

https://codepen.io/driskull/pen/mdYpZgq?editors=1000

### Reproduction Steps

1. open https://codepen.io/driskull/pen/mdYpZgq?editors=1000
2. type "xskdlsdl" or some random characters to guarantee no matches
3. notice how the combobox is open
4. The combobox should not be open.

### Reproduction Version

2.9.0

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `2.10.0-next.2` 🎉
