### ISSUE TITLE
Color picker: component enhancements

### ISSUE THREAD

**Issue by aPreciado88** [Esri/calcite-design-system#9624]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

-Auto select values when clicking on input fields. This should apply to all inputs in `color-picker`.
-Improved value commit:
1. The hex input should auto-commit a valid 6-char (or 8-char if alpha-channel is enabled).
2. A 3-char (or 4-char with alpha-channel) shorthand value would commit onBlur.
3. Channel inputs should auto-commit valid values. If the user deletes the value completely, there would be no change. If left blank, the original value should be restored onBlur.

-onBlur should include clicking anywhere outside the input. As of v1.8.0, the user must click outside the entire component.

### Which Component

`color-picker`

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

[Figma file](https://www.figma.com/design/h0vqgnnTvcDhrsJLyiQyOm/Color-Picker%3A-apply-entered-hex-value-immediately-[7057]?node-id=566-7568&t=e8AcRjJ3e3rTEPNW-0)

**Comment by DitwanP** [comment]
🍡Verified on `2.11.0-next.15`
