### ISSUE TITLE
Calcite Combo-Box Dropdown Falls Outside of MapView When Using Version Management Component 

### ISSUE THREAD

**Issue by mdebella10** [Esri/calcite-design-system#9649]
### Check existing issues

- [ ] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The Version Management component employs a calcite-combobox dropdown (floating-ui-container) that expands outside of the map view. This is due to it being placed in the upper right corner. This only happens when the text in the dropdown is long, which causes the width to expand to fit the text on a single line. 

![VMCalciteDropdownDefault](https://github.com/Esri/calcite-design-system/assets/156034818/07028622-01fa-42e2-80af-cb57ffd83848)

### Expected Behavior

Could we add a property to the combox dropdown (floating-ui-container) to set the width so it doesn't expand outside the bounds of the map. The image below has had the dropdown set to the width of the combo-box. 

![VMCalciteDropdownWidthEqualToComboBox](https://github.com/Esri/calcite-design-system/assets/156034818/507faac9-af76-4fe7-a9bf-728627211ab9)

### Reproduction Sample

Message me directly for creds and testing env

### Reproduction Steps

1. Open the component
2. Select the drop down
3. Drop down will expand out of bounds

### Reproduction Version

2.9.0

### Relevant Info

Windows 10 & 11, Chrome & Firefox

### Priority impact

impact - p1 - need for current milestone

### Impact

The scroll bar is obscured when the component expands beyond the limits of the map-view. 

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
@mdebella10 Following-up to see if we can create a repro case outside of MV. I've been unable to reproduce as a standalone with https://codepen.io/geospatialem/pen/dyEgOXo in `2.9.0` and `2.10.1`.

**Comment by mdebella10** [comment]
@geospatialem I'll go ahead and close this, my apologies!
