### ISSUE TITLE
list: slotted list-items that are not direct children of a list should get a drag handle

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9662]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

list-item's slotted inside a div within a list do not get drag handles when dragging is enabled

### Expected Behavior

Both of the lists in the sample codepen should work the same.

### Reproduction Sample

https://codepen.io/driskull/pen/eYaMPdB?editors=1000

### Reproduction Steps

1. Open codepen
2. Notice how the first list is missing drag handles on some items
3. Notice how the second list has drag handles on some items
4. These lists should be equal

### Reproduction Version

2.9.0

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
@driskull This is what I'm seeing when testing locally, the drag handles show up but I'm unable to actually drag them. Are you getting the same results?

https://github.com/Esri/calcite-design-system/assets/60022782/d38464cf-e305-4e34-a4c7-4d2738220f47

**Comment by driskull** [comment]
Ah, dang. Well I solved part of the issue. I'll need to investigate to see if we can get dragging to work in the above scenario.

At first glance, it seems like Sortable has to have direct children but I'll investigate more.

Can we open a new issue for the dragging part @DitwanP?

**Comment by DitwanP** [comment]
Technically the issue of showing drag handles has been resolved so closing this out, will be creating a new issue for fixing the dragging functionality.
