### ISSUE TITLE
Proposal for Calcite Design System documentation

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#9673]
## The problem

We have reinstated the Github Wiki but it is difficult to maintain because Github does not allow for PRs against the wiki. Making team reviews difficult.

## Solution

1. Create a "calicte-documentation" package
1. Create a github action that watches for changes in the "calcite-documentation" package on "/main". When changes are found it will update the Github Wiki automatically with the changes found in the documentation package.
1. Github Wiki itself should be considered `read-only`

### Which Component

all packages 

### Resources

https://github.com/devonfw/devon4j/blob/develop/.github/workflows/github_actions.yml

**Comment by jcfranco** [comment]
Closing per our discussion. 

To recap, we want to keep the wiki open to the whole team to lower the barrier to doc stuff and use something similar to a `calcite-documentation` package, from this proposal, for official doc (e.g., [releasing doc](https://github.com/Esri/calcite-design-system/blob/0ec0371a0ab7dc10c96ea6c98f8a7c2419ae913b/documentation/releasing.md#L4)).
