### ISSUE TITLE
List in panel with list items with more than one action with tooltips causes horizontal overflow

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#9674]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

List in panel with list items with more than one action with tooltips causes horizontal overflow.

### Expected Behavior

No horizontal overflow.

### Reproduction Sample

https://codepen.io/COV-GIS/pen/xxNzVxO

### Reproduction Steps

Comment out/in the tooltip in the second action. Doing so on the first tooltip does nothing.

Invoking tooltips, clicking actions and adding additional list items can cause additional sizing problems.

Non-panel example w/o the issue: https://codepen.io/COV-GIS/pen/XWwYKme?editors=1000

### Reproduction Version

2.9.0

### Regression?

I believe it started when this was fixed: https://github.com/Esri/calcite-design-system/issues/8611

### Priority impact

impact - p3 - not time sensitive

### Impact

Low. Mainly aesthetics.

Feel free to improve the title of this issue.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
@COV-GIS Would the following solution of adding `overlay-position="absolute"` to the tooltips accommodate the need? https://codepen.io/geospatialem/pen/Jjqmoba

**Comment by geospatialem** [comment]
Awesome, glad that helps and `placement` is another great attr/prop! As far as the above, we can work on some documentation samples, but otherwise, good to close the above out, @COV-GIS?

**Comment by COV-GIS** [comment]
Check roger.
