### ISSUE TITLE
Enhancement: Modify list to support layer-list design

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-design-system#968]
### Description

- support layer-list design

https://codepen.io/mtb-alan/pen/PoqQOBJ

### Acceptance Criteria 

- Slot for leading actions (drag handle & tree action)
- Slot for trailing actions (visibility and menu icon)
- Modify styles to handle selected state with left border

#### Which Component

- calcite-list
- calcite-list-item

#### Example Use Case

Component could be used internally within the layerlist, tablelist and basemaplayerlist API widgets.

cac issue: https://github.com/Esri/calcite-app-components/issues/980

**Comment by jcfranco** [comment]
@kat10140 Can you confirm if `calcite-list` would solve this or do you need value-list to be updated?

**Comment by driskull** [comment]
I think this should be a `refactor` issue to use the `calcite-list` internally.

**Comment by macandcheese** [comment]
AFAIK all the items in the OP have been added - `calcite-list` now has a "bordered" selection appearance, and uses the "stack" pattern to implement the mentioned slots.

Thinking we can close this as an implementation of a layer list is ultimately up to a consuming app cc  @driskull , @kat10140

**Comment by driskull** [comment]
Yes this can be closed.

**Comment by macandcheese** [comment]
Closing based on above.
