### ISSUE TITLE
Calcite slider with snap=true and step=1 can present floating point, non-integer values

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-design-system#9684]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The calcite slider allows users to select values that are very close to, but not quite, a round integer value.   See below:
![image](https://github.com/Esri/calcite-design-system/assets/36513418/4924ee91-8eea-4e96-af4f-7389b9b9a732)

### Expected Behavior

When snap=true and step=1 (or any other integer value), the slider should only change to exactly integer values (no decimal place).  

### Reproduction Sample

Documentation (ArcGIS Knowledge Studio /  Teams chat)

### Reproduction Steps

Please see the conversation in teams chat

@benelan indicated he was already aware of this issue since Slider isn't using a util that handles precision issues.

### Reproduction Version

2.8

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

Everything works, but it looks unprofessional in our app.  For applications where exact integer values are required, it makes the slider component unusable.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Knowledge

**Comment by geospatialem** [comment]
@RSantosGIS Would you be able to put together a sample for us above to troubleshoot? We're trying to determine if this is React-specific.

**Comment by RSantosGIS** [comment]
I tried to create something in the sandbox but wasn't able to reproduce, and since Ben indicated that you guys already knew about a problem with rounding numbers I didn't pursue it further.  If you need me to, I can make an issue to try to spend some more time on this for the repro case

**Comment by benelan** [comment]
Picking this up now, here is a repro sample: https://codepen.io/benelan/pen/jOjxbRg

**Comment by DitwanP** [comment]
🍡 Verified on 2.12.-next.34
