### ISSUE TITLE
[Block-section] Apply missing CSS class to start/end icon

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#9703]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

 Icon uses class instead of value for styling.

### Expected Behavior

Update to use class.

### Reproduction Sample
https://codepen.io/jcfranco/pen/vYwoOaW?editors=1000

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.0`
