### ISSUE TITLE
CalciteCombobox React component won't show selected ComboboxItem if it was initially disabled

### ISSUE THREAD

**Issue by fnquinteros** [Esri/calcite-design-system#9719]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

This happens when the initial state of one or more items inside a Combobox is "disabled". After enabling those items, they are selectable, but when selected, the value doesn't show up in the Combobox.

### Expected Behavior

After enabling an item, if selected, they should show up on the combobox like any other selected item.

### Reproduction Sample

[link to sandbox](https://codesandbox.io/p/devbox/objective-maria-lc79hd?file=%2Fsrc%2FApp.jsx%3A8%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxn19c5e00073b6n0hn7wnpq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxn19c5e00023b6nrt0879qo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxn19c5e00043b6nz9wlp5oz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxn19c5e00063b6n88xhf03j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxn19c5e00023b6nrt0879qo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxn19c5d00013b6n1xwlax59%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly30h7i900023b6mdow7c1zy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly30nlm0002s3b6m2yko7ck3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxn19c5e00023b6nrt0879qo%2522%252C%2522activeTabId%2522%253A%2522cly30nlm0002s3b6m2yko7ck3%2522%257D%252C%2522clxn19c5e00063b6n88xhf03j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxn19c5e00053b6n3hv3vh9h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxn19c5e00063b6n88xhf03j%2522%252C%2522activeTabId%2522%253A%2522clxn19c5e00053b6n3hv3vh9h%2522%257D%252C%2522clxn19c5e00043b6nz9wlp5oz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxn19c5e00033b6n2irhu29l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxn19c5e00043b6nz9wlp5oz%2522%252C%2522activeTabId%2522%253A%2522clxn19c5e00033b6n2irhu29l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduction Steps

1. Open Combobox.
2. Select every enabled item. You should see its value appear on the combobox when it's selected
3. Enable item 3 by clicking the button.
4. Select item 3 now that it's enabled. You can see that its value won't appear on the Combobox.
5. Select any other item that was not initially disabled. All of them show up as expected.

### Reproduction Version

calcite-components-react 2.10.1

### Relevant Info

This happens regardsless of browser or OS. When investigating the issue, I found that the Combobox component saves the "displayable" items in an array, but leaves out any disabled items. It seems this array is not updating after an item is enabled.

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

We're now using a hacky workaround to make this component work for the usage we give to it. We pass every item enabled and disable the necessary ones after the Combobox is rendered. It's not nice, but it works.

It's a common case that items inside a combobox get enabled and disabled depending on other components, so this happens fairly often.

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Urban

**Comment by jcfranco** [comment]
Related: https://github.com/Esri/calcite-design-system/issues/9888.

**Comment by jcfranco** [comment]
This also occurs outside of React. Here's a vanilla JS repro case: https://codepen.io/jcfranco/pen/LYKWgOv?editors=100

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.4`
https://codesandbox.io/p/devbox/gifted-snowflake-zv8d89?file=%2Fpackage.json
