### ISSUE TITLE
calcite-input-time-picker: meridiem on wrong side for Korean

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#9720]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

If the time is after 12:00:00 then the meridiem is initially on the wrong side. Only if you change a value then does it correct itself.

![image](https://github.com/Esri/calcite-design-system/assets/44481292/00754a5c-d8da-4b9d-a0d2-8ea0573ff1ea)

### Expected Behavior

meridiem for Korean should always be on left side

### Reproduction Sample

https://codepen.io/afreitag/pen/WNBVQJQ

### Reproduction Steps

Open second time picker, observe. Then change a value and observe.

### Reproduction Version

2.8.6

### Regression?

no

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified in `2.11.0-next.21`.

![image](https://github.com/user-attachments/assets/e83fda5f-eba8-4867-bd14-44b3e9539ca6)
