### ISSUE TITLE
Update calciteConfig message when same or different versions

### ISSUE THREAD

**Issue by odoe** [Esri/calcite-design-system#9721]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, when the `globalThis.calciteConfig` is checked if a Calcite version is loaded, it emits a message that doesn't distinguish if the same version or a different version was loaded.

There are cases when the same version could be loaded if an app that uses Stencil built components mixes `import` of components and `defineCustomElements`, which is probably not best practice.

Not sure what the message when the same version is loaded should be, but definitely a distinct warning when a different version is loaded, probably means something went wrong.

### Acceptance Criteria

- [ ] Two messages for when the same Calcite version or a different Calcite version is loaded.
- [ ] Confirm regular Vite setup doesn't add the same message with [our example](https://github.com/Esri/calcite-components-examples/tree/main/vite)

### Which Component

calcite-components/src/utils/config.ts

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
> Confirm regular Vite setup doesn't add the same message with [our example](https://github.com/Esri/calcite-components-examples/tree/main/vite?rgh-link-date=2024-07-01T23%3A03%3A44Z)

@odoe I can't reproduce the same-version warning with the vite example. Do you have any suggestions on how to get the warning?

**Comment by odoe** [comment]
@jcfranco I made a repro here
https://github.com/odoe/calcite-dupe-issue

It updates the `main.js` to do both `defineCustomElements` and an import from map components. This will trigger the loading of the config file from two different dist folders in calcite.

```js
import './style.css';
// loads calcite from components folder
import { defineCustomElements as defineCalciteElements } from "@esri/calcite-components/dist/loader";
// loads calcite from esm folder
import "@arcgis/map-components/dist/components/arcgis-map";

defineCalciteElements(window, {
  resourcesUrl: "https://js.arcgis.com/calcite-components/2.10.1/assets",
});

const loader = document.createElement('calcite-loader');
document.body.appendChild(loader);
```

**Comment by jcfranco** [comment]
@odoe @cov-gis Thanks for your help on this one! ✨💪✨

We changed the approach to instead display an info message showing the stamped version to avoid confusion when the same or mismatched versions are encountered. The [PR description](https://github.com/Esri/calcite-design-system/pull/9739) adds a bit more detail if you're curious.

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.9`
