### ISSUE TITLE
Add automation for moving related issues to verification when main issue is closed out

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#9722]
### Priority impact

p - low

### Summary

In the last few weeks something that has continued to pop up is some issues could be resolved through an issue/PR currently in progress, but they need to still be executed prior to validation. Currently the PE's are assigning those issues to themselves and periodically need to remember to check if the main issue has been closed out and then proceed to verify if it resolves the related one.

### Desired Outcome

Hopefully an automation to notify us when the original issue is closed out and moves the related one to a label that shows it's ready to test.

**Comment by geospatialem** [comment]
@DitwanP Updating triage labels! ⭐🚀⭐

**Comment by DitwanP** [comment]
🍭 Verified by testing with another issue that was about to be closed, see above bot comment for proof.

Also...
<img width="277" alt="Screenshot 2024-05-21 at 11 06 30 AM" src="https://github.com/user-attachments/assets/adfdd7e5-63bf-48f0-9b4a-da5f68aca396">
