### ISSUE TITLE
Question: existing configuration and unexpected behavior

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#9725]
What does this mean?

![image](https://github.com/Esri/calcite-design-system/assets/14297903/ba1d5d4b-86c9-4e53-b376-170fa2c82bf3)

Thanks.

**Comment by jcfranco** [comment]
2.10.0 (see https://github.com/Esri/calcite-design-system/issues/8848) added a way to check the components version at runtime. It does so by 'stamping' the version onto a global `calciteConfig` variable when Stencil's global script executes. This warning message will be displayed if there is an existing `version` on the global config when stamping. We have [an issue](https://github.com/Esri/calcite-design-system/issues/9721) to revisit the message to provide better context.

Would you mind sharing more info about your use case? It might be useful for #9721.

**Comment by jcfranco** [comment]
> Not 100% on this but after some digging methinks it's because of vite/rollup and all the magic module optimization, bundling and loading. My only suggestion would be to not warn if the versions match.

@COV-GIS Would you be able to share more details behind your use case? I started working on #9721 and was not able to reproduce this same-version warning with the `calcite-components-examples` repo. The version check happens at the global script level, which should be happening once, so there might be something else going on.

**Comment by COV-GIS** [comment]
Here you go @jcfranco: https://github.com/CityOfVernonia/vite-map-app
