### ISSUE TITLE
[Block] Where no `heading` is defined the component adds spacing

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9753]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a `block` is specified without a `heading` the component contains spacing, which was not present in the `2.9.0` release.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/c7add178-9aaf-4946-aa3c-174ef95167cd)

### Expected Behavior

The same behavior depicted in `2.9.0`: https://codepen.io/driskull/pen/poXvddG

![image](https://github.com/Esri/calcite-design-system/assets/5023024/5fe4e58b-abe9-4f16-8a1a-70a6c87e2374)

### Reproduction Sample

https://codepen.io/driskull/pen/wvLBPPj

### Reproduction Steps

1. Open the [sample with `2.10.1`](https://codepen.io/driskull/pen/wvLBPPj)
2. Observe the spacing
3. Open the [sample with `2.9.0`](https://codepen.io/driskull/pen/poXvddG)
4. Observe the spacing

### Reproduction Version

`2.10.1`

### Relevant Info

Possibly related to https://github.com/Esri/calcite-design-system/pull/9535/files#diff-153092ac5984c89017b0d1b44791101b55a8a9272dec6d47a6bd4063f0427499R24 from https://github.com/Esri/calcite-design-system/pull/9535

### Regression?

`2.9.0`

### Priority impact

impact - p1 - need for current milestone

### Impact

Effects the Maps SDK for JavaScript editor

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev` 

Box model in `2.10.1` (unwanted padding):
<img width="295" alt="Screenshot 2024-07-15 at 5 14 40 PM" src="https://github.com/user-attachments/assets/1b6f89f0-850d-4dca-8964-0aea8179bafc">


Box model of the header element (notice no unwanted padding): 
<img width="295" alt="Screenshot 2024-07-15 at 5 11 09 PM" src="https://github.com/user-attachments/assets/465544e8-74b9-4be0-868c-a5799b8b1d71">
