### ISSUE TITLE
List: Can't drag and drop list items successfully with nested lists (Potentially Android only)

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#9764]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When a list contains another list in a list-item and drag-enabled is true the list items fail to move as expected and the list becomes unresponsive when an item is dragged.

There was a fix for this recently that seems to only have resolved it for iOS devices. #9521 

### Expected Behavior

The drag and drop behavior works on mobile devices using touch gestures with nested lists.

### Reproduction Sample

https://codepen.io/sagewall/pen/LYoyryy

#### Browserstack repro on Galaxy s23 using Chrome

https://private-user-images.githubusercontent.com/2636825/348023582-cace8736-b729-436d-b4dd-5bc522c7dcb4.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MDI5NzQsIm5iZiI6MTcyMDgwMjY3NCwicGF0aCI6Ii8yNjM2ODI1LzM0ODAyMzU4Mi1jYWNlODczNi1iNzI5LTQzNmQtYjRkZC01YmM1MjJjN2RjYjQubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMTY0NDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y2ZTFiN2ZmODdlM2E3ZWI1MTI1ZGRiNTUwMzIxNGE1OGQ0OWRhOTc3YmVhOGY3OGZmZjJhNTEwZjE2Y2ExMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sK2vhjOB2de5vvPPH9ttZZVGlHU2_E87xfvjt_x89Uk

### Reproduction Steps

1. Open this [codepen](https://codepen.io/sagewall/full/LYoyryy) on an Android device
2. Expand the "Nested List Item"
3. Try to drag and drop any of the list items
4. Observe how the list becomes unresponsive or the list items fail to move

### Reproduction Version

2.10.0

### Relevant Info

Pixel 7 - Chrome
Galaxy s23 - Chrome

### Priority impact

impact - p1 - need for current milestone

### Impact

This impacts the LayerList, BasemapLayerList, and TableList Javascript SDK widgets and the applications that use them like Map Viewer, Experience Builder and Instant Apps.

Also identified as a bug via BUG-000167708.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by DitwanP** [comment]
[List of devices and browsers tested](https://esriis-my.sharepoint.com/:x:/g/personal/sag11876_esri_com/EdzWEUIDC7dFiAd5TCpZaEwB2n_lH-dPSIU-k5OTKo3GEA?email=Ditwan_Price%40esri.com&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720807845955&web=1) provided by Sage.

It looks like it mainly is an issue with chromium based browsers.

**Comment by geospatialem** [comment]
Spike to determine a fix in coordination with the third party Sortable library for next steps.

**Comment by driskull** [comment]
@DitwanP I have tested this on android using Browserstack with it seems to work fine IF not used in codepen. I think codepen is the issue. If you have a simple web page like this without the use of codepen and its iframe, it works fine.

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
</head>

<body>
  <script type="module"
    src="https://cdn.jsdelivr.net/npm/@esri/calcite-components@latest/dist/calcite/calcite.esm.js"></script>
  <link rel="stylesheet" type="text/css"
    href="https://cdn.jsdelivr.net/npm/@esri/calcite-components@latest/dist/calcite/calcite.css" />

  <calcite-list drag-enabled group="nested" label="test" selection-mode="multiple">
    <calcite-list-item open label="Hi! 1" description="hello world">
      <calcite-list drag-enabled group="nested" selection-mode="multiple">
        <calcite-list-item open label="Hi! 2" description="hello world">
          <calcite-list drag-enabled group="nested" selection-mode="multiple">
            <calcite-list-item label="Hi! 3" description="hello world">
              <calcite-list drag-enabled group="nested" selection-mode="multiple"></calcite-list>
            </calcite-list-item>
            <calcite-list-item label="Hi! 4" description="hello world"></calcite-list-item>
          </calcite-list>
        </calcite-list-item>
        <calcite-list-item label="Hi! 5" description="hello world"></calcite-list-item>
      </calcite-list>
    </calcite-list-item>
    <calcite-list-item label="Hi! 6" description="hello world"></calcite-list-item>
    <calcite-list-item drag-disabled label="Hi! 7" description="hello world"></calcite-list-item>
  </calcite-list>
</body>

</html>
```

**Comment by sagewall** [comment]
I think we can probably close this issue.  When I deployed @driskull's example outside of codepen it seems to behave as expected on my Pixel 7. https://sagewall.github.io/test-images/list.html

**Comment by driskull** [comment]
@geospatialem can we close?

**Comment by geospatialem** [comment]
Closing per @sagewall's [comment above](https://github.com/Esri/calcite-design-system/issues/9764#issuecomment-2377220524) 👍🏻
