### ISSUE TITLE
panel, flow-item: add beforeClose property

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9769]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add beforeClose property to both panel and flow-item in order to support stopping a panel from being closed.

### Acceptance Criteria

panel, flow-item: add beforeClose property

### Relevant Info

Required for dialog component

### Which Component

panel, flow-item

### Example Use Case

```js
panel.beforeClose = () => Promise.reject();
```

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.9`
