### ISSUE TITLE
panel: add alerts slot

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9772]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

add alerts slot to panel to constrain alerts to the panel in question

### Acceptance Criteria

alerts can be slotted into a panel and contained within that panel

### Relevant Info

https://github.com/Esri/calcite-design-system/issues/7886#issuecomment-2224099221

### Which Component

panel

### Example Use Case

```html
<calcite-panel>
<calcite-alert slot="alerts"></calcite-alert>
</calcite-panel>
```

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
@driskull Is this how it's intended to look or is it supposed to be above the buttons? 
![Screenshot 2024-07-16 at 10 59 06 AM](https://github.com/user-attachments/assets/50ceb8e0-79eb-4216-b591-39eefbd75feb)

**Comment by driskull** [comment]
Yes, that is how I intended, it is just constrained inside the panel. Maybe we should ask @SkyeSeitz and @ashetland ?

**Comment by SkyeSeitz** [comment]
Is the Alert slot always tied to the content inside the bounds of Panel's default slot? Or would that ever be too narrow? 
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/f0573a6c-33f4-4e10-99e3-cff9104fea21">

**Comment by driskull** [comment]
My thinking was that it might be too narrow in some cases.

**Comment by SkyeSeitz** [comment]
I assumed the same and defaulted to positioned to the Panel itself. I am fine with that if no one else has any objections.

**Comment by ashetland** [comment]
This may be fine as a starting point and could be updated after feedback. My initial reaction is it does feel awkward covering the footer like that and might be nice if it had some margin to force it higher? But as I said, could wait for feedback on it.

**Comment by driskull** [comment]
Let me know what you prefer. I can make it appear over the content if that's the way we want to go.

**Comment by ashetland** [comment]
"Wait for feedback" is the consensus. ✅

**Comment by DitwanP** [comment]
🍡Verified on `2.11.0-next.11`
