### ISSUE TITLE
add `metadata` support to combobox items

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9796]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Adding item metadata support to combobox would help with filtering and also be consistent with other components with filtering capabilities.

### Acceptance Criteria

Add a `metadata` property to `combobox-item`, which is used in combobox filtering.

### Which Component

`calcite-combobox`, `calcite-combobox-item`.

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.23`
https://codepen.io/Ditwan-Price/pen/oNrzJJv?editors=1010
