### ISSUE TITLE
[Shell Panel] Unexpected behavior when resizing via click

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9807]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Placeholder from UC:

### Expected Behavior

Placeholder from UC

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/QWXyvqw?editors=1010

### Reproduction Steps
- View codepen 
- Use mouse to click resizable affordance
- Notice the jump in height
- Focus the resizable affordance
- Notice the issue does not occur

### Reproduction Version

Latest

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
While the original Codepen with this issue now works on the latest - other similar reproduction case does not: https://codepen.io/mac_and_cheese/pen/JjQLYrW?editors=1000

Same issue as originally - clicking on the resize affordance adjusts size of adjacent content, but does not occur when using keyboard focus / arrows to adjust.

Re-opening cc @geospatialem @DitwanP

**Comment by driskull** [comment]
@macandcheese is it working on the next version?

https://codepen.io/driskull/pen/ExBEVdW?editors=1000

**Comment by macandcheese** [comment]
Yep it does - the original issue was resolved in 2.11.1, not the latest example.

**Comment by driskull** [comment]
I guess https://github.com/Esri/calcite-design-system/pull/9912 fixed it.
