### ISSUE TITLE
[Tab Title] Fix hover styling in `bordered` appearance

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9854]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Follow up issue for hover style fix from #9666 

### Expected Behavior

I would not expect the bottom border in `bordered` and "top alignment" to cover the Tab container area:
![Screenshot 2024-07-25 at 10 55 56 AM](https://github.com/user-attachments/assets/9c6a4130-fd1f-4505-917f-08b39455dfb2)

### Reproduction Sample

-

### Reproduction Steps

-

### Reproduction Version

Next

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev` 
![image](https://github.com/user-attachments/assets/c760e331-2dbb-4a71-8373-264e561f74b6)
