### ISSUE TITLE
FlowItem: footer slots are conflicting with each other

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9855]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using a flow-item and slotting a footer-start or footer-end it just uses the footer slot internally.

### Expected Behavior

It should honor footer-start and footer-end

### Reproduction Sample

https://codepen.io/driskull/pen/wvLzNMP?editors=1000

### Reproduction Steps

1. Open the codepen
2. notice footer slots aren't working properly
3. footer-start should be on the left and footer-end should be on the right

### Reproduction Version

2.10

### Regression?

No

### Priority impact

impact - p1 - need for current milestone

### Impact

Regression from https://github.com/Esri/calcite-design-system/issues/8981

https://github.com/Esri/calcite-design-system/pull/9374

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified on `2.11.0-next.24`
![image](https://github.com/user-attachments/assets/f1f8ffe0-5951-4d67-a60c-0caa97944e49)
