### ISSUE TITLE
Panel: footer-end should appear at the end

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9857]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

footer-end slot appears centered if there is no footer-start slot

### Expected Behavior

footer-end should always appear at the end

### Reproduction Sample

https://codepen.io/driskull/pen/yLdawGa?editors=1010

### Reproduction Steps

1. open the codepen
2. notice how the slotted button is centered instead of at the end
3. uncomment the footer-start slotted button
4. Notice how it now looks correctly

### Reproduction Version

2.10.1

### Regression?

No

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
![image](https://github.com/user-attachments/assets/28c45b70-df33-49a9-9ec1-7b0a98e9bcdc)
