### ISSUE TITLE
[Panel & Flow Item] `heading` and `description` line heights

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#9862]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

To align with issue #7623, both the `heading` and `description` should be assigned `calcite-font-line-height-relative-snug` and the margin between them removed.

### Acceptance Criteria

See above.
When only one text prop is used, the remaining text should be vertically centered in the header.

### Relevant Info

cc @driskull @SkyeSeitz 

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by aPreciado88** [comment]
This is planned to be installed during a December/January release.

**Comment by geospatialem** [comment]
Verified with `flow` and `panel` in `3.0.0-next.51` 🎉
