### ISSUE TITLE
[Dialog] Add padding to default Panel slot

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#9869]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Match the current Modal paradigm where the default slot provides overridable padding to align its slotted content to the header and footer content. 

### Acceptance Criteria

1. Dialog adds padding to Panel's default slot matching the padding values of header & footer at each scale
2. Add css prop to override padding on default slot
<img width="1591" alt="image" src="https://github.com/user-attachments/assets/45af6c74-6cb5-4752-8e5d-241c046f518b">

### Relevant Info

Link to Figma specs: https://www.figma.com/design/wVqftT1aZDjwYVkDZ2V5fC/Dialog?node-id=1361-52175&t=Z5ugz3gneENwbHPj-11

### Which Component

Dialog

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`

Only the finest of custom hand-woven paddings here 🎩🧐:
![image](https://github.com/user-attachments/assets/140bc26d-15d2-432b-928f-aae80c738556)
