### ISSUE TITLE
[Dialog] Support CSS variables for adjusting specific locations via CSS

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9879]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Allow developers to adjust custom placement using CSS variables outside of the `placement` attr/prop.

### Acceptance Criteria

- [ ] Allow developers to customize placing of the component using CSS variables, such as `margin-*` or `offset-x`/`offset-y`, etc.

### Relevant Info

Related to the team need of the following:

> Adjust using margins/css placement to fit it more in context with the node that opens the [component].

### Which Component

`dialog`

### Example Use Case

https://codepen.io/geospatialem/pen/xxogVyx

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by alisonailea** [comment]
suggested 
`--calcite-dialog-space-x` `--calcite-dialog-space-y`

**Comment by driskull** [comment]
@alisonailea for the positioning, do we want users to set negative values or should we have 4 vars that equate to top/left/bottom/right?

**Comment by alisonailea** [comment]
> @alisonailea for the positioning, do we want users to set negative values or should we have 4 vars that equate to top/left/bottom/right?

I don't think we should have 4 vars unless absolutely necessary. If we want to allow for negative values maybe "offset" is a better term.

```
--calcite-dialog-offset-x: -10px;
--calcite-dialog-offset-y: 10px;
```

**Comment by geospatialem** [comment]
Verified in `2.12.0-next.15` with the following CSS variables:

```css
calcite-dialog {
  --calcite-dialog-offset-x: 10rem;
  --calcite-dialog-offset-y: 5rem;
}
```
