### ISSUE TITLE
[Combobox Item] update heading color

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#9881]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

To match List Item and other components with a `heading` and a `description`, the color of the `heading` should be `text.1` in all states.
![CleanShot 2024-07-29 at 11 32 02@2x](https://github.com/user-attachments/assets/7960f04a-ff19-4455-a6d1-3163eebcfc78)

### Acceptance Criteria

Color of `heading` changed to `text.1`

### Relevant Info

The current colors make the hierarchy of information difficult to understand.
Related to #7623 

cc @jcfranco 

### Which Component

Combobox Item

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
