### ISSUE TITLE
Tooltip: enhance test to cover shadow root elements

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#9885]
### Priority impact

p - high

### Test type

New test

### Which Component(s)

tooltip

### Additional Info

https://github.com/Esri/calcite-design-system/pull/9878/files#r1695674556

- Add additional tests to cover focusing in and out of tooltip reference elements within a shadowRoot
- Tests should cover focusin/focusout

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
![image](https://github.com/user-attachments/assets/27881f15-2324-4c44-8bbb-9dc69b44f048)
