### ISSUE TITLE
calcite-action: add CSS variables for spacing replacing deprecated compact behavior

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#9889]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The compact property got removed from calcite-action, see https://github.com/Esri/calcite-design-system/issues/3859

Could we please add some CSS spacing variables to get back to the compact behavior?

cc @alisonailea 

### Acceptance Criteria

new CSS spacing variables

### Which Component

calcite-action

### Example Use Case

see https://github.com/Esri/calcite-design-system/issues/3859#issuecomment-2257022196

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment]
I don’t think we should pursue this - adjusting the interior padding of the component like this shouldn’t be incentivized. A standalone calcite button could be a solution for this use case.

cc @ashetland @SkyeSeitz to confirm

**Comment by ashetland** [comment]
> I don’t think we should pursue this - adjusting the interior padding of the component like this shouldn’t be incentivized (not a content slot where we often see that). A standalone calcite button could be a solution for this use case.
> 
> cc @ashetland @SkyeSeitz to confirm

Agreed.

**Comment by geospatialem** [comment]
@AdelheidF Closing out the above per [Adam's comment above](https://github.com/Esri/calcite-design-system/issues/9889#issuecomment-2260518846), but we can work through some options together to ensure the team has direction for current and future implementations.
