### ISSUE TITLE
[Combobox] placeholder icon color does not match other components

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#9935]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The placeholder icon is black.

### Expected Behavior

The placeholder icon should be `text.3`.

### Reproduction Sample

https://codepen.io/ashetland/pen/mdZWLwz

### Reproduction Steps

See that Input Time Picker and Input Date Picker use `text.3`

### Reproduction Version

v2.10.1

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `2.12.0-next.5`:

![image](https://github.com/user-attachments/assets/a650effa-1351-44f6-ac08-51ada29f9005)
