### ISSUE TITLE
Bug - unnecessary scroll bar appears for list items that contain a nested list

### ISSUE THREAD

**Issue by sagewall** [Esri/calcite-design-system#9949]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Beginning with version 2.10.0 an unnecessary scroll bar appears for list items containing a nested list when it has the keyboard focus.
![scrollbar](https://github.com/user-attachments/assets/38afc27b-d8ab-4247-a4b4-a88f28196476)

### Expected Behavior

No scroll bar appears

### Reproduction Sample

https://codepen.io/sagewall/pen/KKjWOEM

### Reproduction Steps

1.  Open the codepen
2. Expand the ACS School Enrollment Variables - Boundaries list item
3. Collapse the list item
4. Notice how a scroll bar appears in the list item while it retains the keyboard focus
5. Click somewhere outside the list or hit tab
6. Notice how the scrollbar goes away

### Reproduction Version

2.10.0

### Relevant Info

Could be related to [this commit](https://github.com/Esri/calcite-design-system/commit/b3d2cb26c9df609c3b6c06be672ab70f6227d4e3).

### Regression?

2.9.0

### Priority impact

impact - p2 - want for an upcoming milestone

### Impact

Impacts the ArcGIS Maps SDK widgets and components that use the calcite list.  This also affects all the app teams that use the JS SDK like Map Viewer, Scene Viewer, Experience Builder and Instant Apps.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by geospatialem** [comment]
Verified in `2.12.0-next.5`:

![verify-scrollbar](https://github.com/user-attachments/assets/d6b22194-2b8f-4ad1-9a07-0bc1bf0fb777)
