### ISSUE TITLE
BUG-000169703 Segmented Control does not respect `scale` beyond first page load

### ISSUE THREAD

**Issue by fdeters** [Esri/calcite-design-system#9955]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Filed as `BUG-000169703` 🐛 

The `calcite-segmented-control-item` does not respect the `scale` property on the `calcite-segmented-control` if the element was rendered after the initial page load. Specifically, I'm seeing a `calcite-segmented-control` with `scale="s"` render as though it had `scale="m"`.

### Expected Behavior

I expect the `calcite-segmented-control` and `calcite-segmented-control-item` to respect the `scale` property at all times.

### Reproduction Samples

1. https://codepen.io/driskull/pen/WNqjrpq
2. https://gis.oregonmetro.gov/metromap

#### First sample
1. Open [the sample](https://codepen.io/driskull/pen/WNqjrpq)
3. Watch the component load on initialization
4. Observe the appended child item load in with a different scale than the parent

#### Second sample
Also, we can see this behavior on my team's live app:
1. Visit [gis.oregonmetro.gov/metromap](https://gis.oregonmetro.gov/metromap)
5. Once the page loads, you should see a modal with a legal disclaimer. The modal has a `calcite-segmented-control` in the bottom left that can be used to switch the language. It is rendering correctly with `scale="s"`.
![image](https://github.com/user-attachments/assets/d729b87e-01f2-4519-b12e-54fd64a6574c)
6. Click "I agree", then navigate to the "About" page using the nav in the top-right.
7. Go to the "Terms of Use" section using the tab navigation on the About page.
8. Click "View disclaimer" in the body of the Terms of Use section. This re-opens the same `calcite-modal` we saw in step 2. You can now see that the `calcite-segmented-control-item` is rendering as though it had `scale="m"`, even though it still has `scale="s"`.
![image](https://github.com/user-attachments/assets/36377510-7ebd-4ed5-8312-653e4675e74b)

Notice that the `calcite-segmented-control` visible in the site header never changes and always shows as `scale="s"`, like it should.

When I first encountered this bug, we were using that same `calcite-segmented-control` component in other areas of the application, and it exhibited the same issue.

### Reproduction Version

2.9.0

### Relevant Info

**OS:** Windows 10
**Browser:** Observed on recent versions of Chrome, Edge, and Firefox
**JS Framework:** EmberJS 5.10 with `@embroider/router@2.1.8`

### Priority impact

impact - p3 - not time sensitive

### Impact

Currently, it's just a minor annoyance. It could cause layout issues for other users.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A<div><div><div>The calcite-segmented-control-item does not honor the scale property on calcite-segmented-control of Calcite Design System if the element is rendered post the initial page load.</div></div>
<span><b>Salesforce ID:</b> <a href="https://desktopqa/SFTriage?sfid=BUG-000169703">BUG-000169703</a></span><br/>
<span><b>Salesforce Submitter:</b> Ashish Boban</span><br/>
<span><b>Salesforce Submit Date:</b> 8/02/2024 10:47 PM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Steps to Repro:</b> <p><strong>Steps to Reproduce:</strong></p><ol><li>Open the sample - https://codepen.io/driskull/pen/WNqjrpq?editors=1010.</li><li>Watch the component load on initialization</li><li>Observe the appended child item loads with a different scale than the parent.</li></ol><p><strong>Other Information: This issue is also highlighted in the GitHub page for Calcite Design System - </strong>https://github.com/Esri/calcite-design-system/issues/9955.</p><p><br></p><p><strong>Customer Data Specific Bug:</strong></p><p>No</p><p><br></p><p><strong>Repro Environment Details:</strong></p><p>Windows OS 11.0, ArcGIS Maps SDK for JavaScript v4.30, Chrome browser.</p><p><br></p><p><strong>Sample Environment Access Information: NA</strong></p><p><br></p><p><strong>Development/PSIRT request?</strong></p><p>No</p><p><br></p><p><strong>Attached Files: </strong><span style="color: rgb(68, 68, 68); background-color: rgb(255, 255, 255);">Yes</span></p><p><strong>Attached Video: </strong>No</p><p><strong>Attached Logs: </strong>No</p><p><strong>Attached Data: </strong>Yes</p><p><strong>Reproducible in Latest Version: </strong>Yes</p></span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000169703</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> Calcite Design System</span><br/>
<span><b>Functional Category:</b> Calcite Design System</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 2.8</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div>

**Comment by jcfranco** [comment]
@fdeters Thanks for submitting this! Could you provide an isolated reproduction case for us to look into?

**Comment by driskull** [comment]
Here's a repro: https://codepen.io/driskull/pen/WNqjrpq?editors=1010

**Comment by geospatialem** [comment]
This was also filed as `BUG-000169703`

**Comment by geospatialem** [comment]
Verified with the Chromatic build using [Matt's example](https://codepen.io/driskull/pen/WNqjrpq):

![image](https://github.com/user-attachments/assets/c3f101d5-dc6a-4867-b7c4-4f9feadf9fe5)
