### ISSUE TITLE
[Alert] Allow the Alter component to position itself based on the extent of its closest parent container

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#9971]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently, the alter component positions itself based on the extent of the entire page, and we would like to have the alter component positions based on the closest parent container.

### Acceptance Criteria

Allow the alter component to be positioned based on the extent of the closest parent container.

### Which Component

Alter

### Example Use Case

We create a feature report component embedded in the Experience builder. The alter component hosted in the feature report component is not in our expected position.
![image](https://github.com/user-attachments/assets/7c3c83dd-e1e8-419d-be94-18af7f34ee50)
which

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [ ] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Survey123

**Comment by driskull** [comment]
We added an `alerts` slot to the `calcite-panel` component which can handle this use case.

**Comment by nanzhang01** [comment]
Thanks @driskull. I tried using the alerts slot in the calcite-panel component(here is my testing page: https://codepen.io/nan9266/pen/wvLmoWJ), but seems it didn't fully address the issue.  Could you please let me know about any additional adjustments or provide additional guidance? Thanks.

**Comment by nanzhang01** [comment]
Thanks @driskull ! The updated codepen works perfectly and has resolved our issue. Much appreciated!

**Comment by geospatialem** [comment]
> We added an `alerts` slot to the `calcite-panel` component which can handle this use case.
>  https://codepen.io/driskull/pen/JjQLpxo

The `panel`'s `"alerts"` slot accommodates the above:

```html
      <calcite-panel>
        Left panel with calcite-alert in it.
          <calcite-alert open kind="danger" slot="alerts" placement="top">
             ...
          </calcite-alert>
      </calcite-panel>
```

Closing the above as unplanned.
