### ISSUE TITLE
Display country for selected time zone (region mode)

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#9973]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Stems from a follow-up conversation on https://github.com/Esri/calcite-design-system/issues/9018#issuecomment-2260350211.

Displaying the country inline in the selection will provide more context to users.

cc @AdelheidF @richiecarmichael @emmilaakso212 @ashetland @bsvensson 

### Acceptance Criteria

In region mode, when a time zone is selected, the country should be displayed in the selected item.

![Screenshot 2024-08-06 at 10 44 25 AM](https://github.com/user-attachments/assets/5ade762e-4201-4e0a-9c87-59d1cbf04e25)

### Relevant Info

An embedded style was also brought up, but might need further discussion with the team. 

![353820489-8969c885-4478-42f2-9cba-b8e517284e4e copy](https://github.com/user-attachments/assets/e1eb40d9-4429-4099-9a0c-e909a9cba560)

In the meantime, developers can achieve this by using read-only mode and overriding the semantic token CSS props (see [example](
https://codepen.io/jcfranco/pen/jOjwPpB)).

### Which Component

`calcite-input-time-zone`

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified in `2.12.0-next.12` with the following HTML:

```html
<calcite-input-time-zone mode="region"></calcite-input-time-zone>
```

![image](https://github.com/user-attachments/assets/98da2e14-a1d7-4d12-b668-1033d0f03e84)
