### ISSUE TITLE
[Input] Deprecate the `"textarea"` `type`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9974]
### Description

With the [`text-area`](https://developers.arcgis.com/calcite-design-system/components/text-area/) component we should consider leading users in this direction rather than using it via the `input` component.

We've had enhancement requests, like https://github.com/Esri/calcite-design-system/issues/8568 surface, where the `text-area` component should be leveraged instead.

### Which Component

`input`

### Resources

Once deprecated we should consider for the `4.0` breaking change release in late 2025 - and proactively add it to our list in Confluence once verified.

**Comment by DitwanP** [comment]
Verified 

<img width="277" alt="Screenshot 2024-05-21 at 11 06 30 AM" src="https://github.com/user-attachments/assets/867747f2-2c3f-4bf1-a9e1-0d0c9f8adcbb">
