### ISSUE TITLE
Add context to documentation deprecations

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9975]
### Priority impact

p - high

### Summary

Allow team members to specify a convention type commit that will add a doc-only change to our changelog to ensure deprecations are communicated to internal teams and users.

### Desired Outcome

Where we deprecate properties or values, we should be able to have certain commits automatically added, via our CI, to the changelog.

For instance:
- Deprecating `action's` `compact` property: https://github.com/Esri/calcite-design-system/issues/3859
- Removing `input`'s `type="textarea"`: https://github.com/Esri/calcite-design-system/issues/9974

**Comment by DitwanP** [comment]
Closing as complete for now, will actually verify in future release. 
<img width="277" alt="Screenshot 2024-05-21 at 11 06 30 AM" src="https://github.com/user-attachments/assets/c202d31a-9204-4ce8-b9d6-be35dcf48aef">
