### ISSUE TITLE
[Dialog] Add `outsideCloseDisabled` prop

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9986]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

`dialog` currently has a `beforeClose` prop, which passes a function to run before the component closes. However `beforeClose` is called no matter how close is called on the component. In some cases we want to prevent the component's scrim from closing the component.

### Acceptance Criteria

When `outsideCloseDisabled` is present disables the closing of the component when clicked outside.

### Which Component

`dialog`

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by ellenupp** [comment]
On a similar note, can dialog also have the `escapeDisabled` prop that modal has?

**Comment by driskull** [comment]
@ellenupp what is the use case for just preventing the escape key from closing a dialog?

Would the `beforeClose` property work for you? You could throw an error in that function.

You could also setup a keydown event on the dialog and call preventDefault() on it.

**Comment by ellenupp** [comment]
@driskull We have a lot of complicated workflows (element configuration) in modals and don't want people to accidentally close out of it. Especially when the escape key can be used for other purposes in the modal like closing dropdowns. 

> Would the beforeClose property work for you? You could throw an error in that function.

I don't think so, we wouldn't know what the original keyboard event was. 

> You could also setup a keydown event on the dialog and call preventDefault() on it.

This doesn't work when putting the handler on the dialog itself it seems, only on the slotted content.

**Comment by driskull** [comment]
@ellenupp can you create an issue for this feature request? That would help getting this feature in.

**Comment by ellenupp** [comment]
@driskull Sure, https://github.com/Esri/calcite-design-system/issues/10080

**Comment by driskull** [comment]
Thanks!! Appreciate it.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.23`
https://codepen.io/Ditwan-Price/pen/rNEpoqq?editors=1000
