### ISSUE TITLE
[Pagination] Enhance component's interactive states

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9991]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Updates the `pagination` interactive states as part of the larger epic in https://github.com/Esri/calcite-design-system/issues/9299.

#### Current state
![image](https://github.com/user-attachments/assets/6180f1b4-d79b-44d3-976e-c3a272704cd5)

### Acceptance Criteria

- [x] Add 2px gap between all of the component's elements
- [x] Update chevron icon on `:hover` and `:pressed` to `text.1` (currently `brand`)
- [x] Update background color on `:pressed` to `foreground.3`
- [x] Update inactive page `:pressed` to `text.1` and `foreground.3`
- [x] Increase active state `:focus` bottom `border` to `4px`

![image](https://github.com/user-attachments/assets/36a6b001-7ba1-4655-a5fa-a0228f47b80b)

### Relevant Info

[Figma file](https://www.figma.com/design/c6v9o8y5KgztitlvDudaQy/Interactive-state-audit-%26-improvements?node-id=1-2&t=J8pxiqWOzqfYHpD3-0)

### Which Component

`pagination`

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified on `2.14.0-next.13`
https://codepen.io/Ditwan-Price/pen/qBerpEQ?editors=1000
