### ISSUE TITLE
[Rating and Slider] Add form support via `required` and `validationMessage` for error handling

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9999]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The `rating` and `slider` components do not support form validation, as indicated in #8057.

### Expected Behavior

Form validation support. Since invalid styling is not effective on `slider` and `rating`, the `validationMessage` prop would serve as the only visual invalid affordance when a value is not added and `required` is present.

### Reproduction Sample

https://codepen.io/geospatialem/pen/ZEdJaLr

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/ZEdJaLr)
2. Observe neither component have support for `required` or `validationMessage` properties/attributes

### Reproduction Version

`2.11.1`

### Relevant Info

Follow-up to https://github.com/Esri/calcite-design-system/issues/8057 and https://github.com/Esri/calcite-design-system/issues/8000

Link to Figma specs: https://www.figma.com/design/5QDPzXr21qQcPTkXR1Ouga/Form-Validation-%5BEpic-4598%5D?node-id=956-94284&m=dev&focus-id=1194-2726

### Priority impact

impact - p3 - not time sensitive

### Impact

Medium-High for consistency across the design system with regards to error handling

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by DitwanP** [comment]
🍡 Verified on `2.14.0-next.19`

https://codepen.io/Ditwan-Price/pen/BaXrBoO
